### ISSUE TITLE
关于标注文件格式切换的疑问

### ISSUE THREAD

**Issue by manjusaka999** [CVHub520/X-AnyLabeling#1]
首先感谢您的工作，这个工具非常有意思，但是有一点我在工具中没有发现，就是亮点中的“支持转换成标准的COCO-JSON、VOC-XML以及YOLOv5-TXT文件格式”，请问这个功能是内置的吗？还是需要编写脚本自行转换？

**Comment by ou525** [comment]
界面上确实没看到可以导出这些格式的选项

**Comment by CVHub520** [comment]
> 首先感谢您的工作，这个工具非常有意思，但是有一点我在工具中没有发现，就是亮点中的“支持转换成标准的COCO-JSON、VOC-XML以及YOLOv5-TXT文件格式”，请问这个功能是内置的吗？还是需要编写脚本自行转换？

感谢您的关注。目前还未植入到工具里面，需要加个控件，可以先通过脚本转换下，设置下路径即可：
https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/label_converter.py

**Comment by CVHub520** [comment]
> 界面上确实没看到可以导出这些格式的选项

您好，同楼上。
