### ISSUE TITLE
是否所有格式的数据都依赖json

### ISSUE THREAD

**Issue by fi5** [CVHub520/X-AnyLabeling#101]
假如其他人给我一批YOLOtxt数据来修改，这个工具是没有办法识别的，它必须要有json才可以？

**Comment by CVHub520** [comment]
您好， @fi5 ，可以通过这个[脚本](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/label_converter.py)一键转换下即可导入。

**Comment by fi5** [comment]
好的。感谢！！
