### ISSUE TITLE
是否可以支持export yolo pose format?

### ISSUE THREAD

**Issue by ckcraig01** [CVHub520/X-AnyLabeling#103]
感謝精美的作品, 目前看到有: yolov6-lite face的model
希望能支持輸出格式, 包含bbox + kpts. 
https://github.com/ultralytics/ultralytics/blob/main/docs/datasets/pose/index.md

- Format with Dim = 2
<class-index> <x> <y> <width> <height> <px1> <py1> <px2> <py2> ... <pxn> <pyn>
- Format with Dim = 3
<class-index> <x> <y> <width> <height> <px1> <py1> <p1-visibility> <px2> <py2> <p2-visibility> <pxn> <pyn> <p2-visibility>
In this format, <class-index> is the index of the class for the object,<x> <y> <width> <height> are coordinates of bounding box, and 
<px1> <py1> <px2> <py2> ... <pxn> <pyn> are the pixel coordinates of the keypoints. The coordinates are separated by spaces.

也許需要定義對應的yaml, 如文中:
```
-Keypoints
kpt_shape: [17, 3]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]

-Classes dictionary
names:
  0: person
```

(當然instance seg. -> bbox + instance seg. 也希望能支持)
https://github.com/ultralytics/ultralytics/blob/main/docs/datasets/segment/index.md
能適配yolov5/v6/v7/v8的使用, 我認為會非常有幫助, 謝謝!

**Comment by CVHub520** [comment]
Hi, @ckcraig01 :
Thank you for your feedback and suggestions! I'm pleased to inform you that the X-AnyLabeling now support the YOLOv8-pose model. You can update the source code and try using it to achieve the desired output, which includes bounding boxes and keypoints. This will be a valuable addition to your workflow. If you have any further questions or need assistance, please don't hesitate to reach out.

Thank you for your support!
CVHub

**Comment by ckcraig01** [comment]
Thank you for your promptly feedback. we could find yolov8-pose only by building from source. However, from the results of its inference, it is still lacking a group_id, which means it can't build associations. The output results can be imagined as if we used a separate person detector (e.g., YoloV7) + a separate 5-keypoint regressor (e.g., RSN-18), which would yield the same effect. However, this obviously doesn't effectively associate the landmark features with the person. Thanks again.

**Comment by CVHub520** [comment]
Hi, @ckcraig01, thank you for your kindly feedback and valuable input. I'm pleased to inform you that the `X-AnyLabeling` have now added support for the `group_id` feature. I recommend pulling the latest source code to try it out.

As for the compiled executable version would be provided as soon as possible. Your suggestions are greatly appreciated, and I'm committed to making the tool even more effective for associating landmark features with individuals.

If you have any further questions or need assistance, please don't hesitate to reach out.

Best regards,
CVHub
