### ISSUE TITLE
WIN10上 CPU版本闪退

### ISSUE THREAD

**Issue by AryaDan11** [CVHub520/X-AnyLabeling#106]
加载已有的自定义模型，一般的SAM没有问题，但是到LVM-SAM模型后，CPU版本会产生闪退的情况，请问具体是什么情况，后面再加载SAM也会闪退

**Comment by AryaDan11** [comment]
加载已有的自定义模型，一般的SAM没有问题，但是到LVM-SAM模型后，CPU版本会产生闪退的情况

**Comment by CVHub520** [comment]
Hi, @AryaDan11:
I've tried to replicate the scenario you described, and I haven't encountered any instances of crashing when loading custom models, including the LVM-SAM model, on the CPU version. Everything appears to be functioning normally. 

I would recommend two things: first, ensure that you are using the [latest](https://github.com/CVHub520/X-AnyLabeling/releases/tag/v1.1.0) version of the software, as updates may have resolved any issues. Second, consider running the application from the source code, as this can provide more detailed error messages and help diagnose the problem more effectively.

If you continue to experience crashes, please let me know, and I'll work on resolving the issue together.

Best regards,
CVHub
