### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by ibarbecue** [CVHub520/X-AnyLabeling#107]
你好，请问docker中可以运行成功吗？试过了，展示界面有问题

**Comment by CVHub520** [comment]
Hi, @ibarbecue , i haven't personally tried running it in a Docker container, so I can't provide specific guidance on any display issues you might be experiencing. However, running graphical applications inside a Docker container can sometimes require additional setup for proper display handling. You may want to look into configuring X11 forwarding or other solutions to address the display problems you're encountering.
