### ISSUE TITLE
最新发布版1.1.0- cpu.exe 使用yolo格式，进行标注，保存后，跳转到未标注图片，再跳转回去，报错

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#108]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/401b4e48-aabf-459d-b0a9-af0f779b9233)

**Comment by aiyou9** [comment]
找到原因了，是老的标注文件，重新保存就没问题

**Comment by aiyou9** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/df1334cc-0bc0-4614-a38f-b38fe634a08f)

**Comment by CVHub520** [comment]
Hi, @aiyou9 , thank you for your valuable feedback. It appears that the issue you encountered was related to older annotation files. Saving the annotations again resolved the problem. Your feedback is much appreciated, as it helps us identify and address potential issues like this. If you have any more feedback or encounter any other issues, please don't hesitate to let us know.

**Comment by aiyou9** [comment]
旧标签文件，可以通过命令，转换成yolo，再转换成现在的新的 x-anylabeling的标签，解决这个问题吗？

**Comment by CVHub520** [comment]
> 旧标签文件，可以通过命令，转换成yolo，再转换成现在的新的 x-anylabeling的标签，解决这个问题吗？

Yes, you can try this. Actually, the key is that ensure the `imagePath` in *.json file can be found by the system.

**Comment by aiyou9** [comment]
> > 旧标签文件，可以通过命令，转换成yolo，再转换成现在新的x-anylabeling的标签，解决这个问题吗？
> 
> 是的，你可以尝试这个。其实关键是保证`imagePath`*.json文件能够被系统找到。

好的，我试试，还有用vscode 对整个文件夹里标注文件，替换文件路径
