### ISSUE TITLE
可以参考一下这个https://github.com/tzutalin/labelImg 的功能改进版本

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#11]
https://github.com/ZeXin-Wang/labelimg

**Comment by CVHub520** [comment]
谢谢你的建议。

**Comment by aiyou9** [comment]
遮挡问题，这位大佬加了置顶功能
https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/docs/%E5%8A%9F%E8%83%BD%E8%AF%B4%E6%98%8E.md#4%E9%81%AE%E6%8C%A1%E5%85%B3%E7%B3%BB%E8%B0%83%E6%95%B4
