### ISSUE TITLE
关于多分类属性标注使用问题

### ISSUE THREAD

**Issue by Syorst** [CVHub520/X-AnyLabeling#111]
您好！非常感谢最新版本有加入多分类属性标注功能，但是使用遇到了一些问题。
Q: 如何进行多分类属性标注
A: 可参考以下步骤：

    准备好一个自定义属性标签文件，具体示例可参考[attributes.json](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/attributes.json)；
    运行X-AnyLabeling，点击Import-Import Attributes File导入上一步的标签文件；
    加载图片，绘制目标矩形框，标签必须与自定义类别标签一致；
    右键或者快捷键Ctrl+J打开编辑模式；
    点击选中目标，右上角即可进行标签属性的标注。 注：如果你打算使用AI模型进行预打标，可先加载对应的模型，选择一键运行所有图像功能，再进行微调即可。
请教一下第二步Import按钮在哪里？找了半天没找到，多谢！

**Comment by CVHub520** [comment]
Hello!  @Syorst:
Thank you for your appreciation of the new multi-class attribute labeling feature. Regarding your question, the "Import" button for the second step is currently not available in the latest compiled GUI version. As some of the new features are still in development, the most recent GUI compilation hasn't been released yet.

If you're eager to try out the multi-class attribute labeling functionality, I recommend pulling the latest source code and running it. This way, you can experience the latest developments firsthand.

Feel free to reach out if you have any more questions or need further assistance.

Best regards,
CVHub

**Comment by Syorst** [comment]
> Hello! @Syorst: Thank you for your appreciation of the new multi-class attribute labeling feature. Regarding your question, the "Import" button for the second step is currently not available in the latest compiled GUI version. As some of the new features are still in development, the most recent GUI compilation hasn't been released yet.
> 
> If you're eager to try out the multi-class attribute labeling functionality, I recommend pulling the latest source code and running it. This way, you can experience the latest developments firsthand.
> 
> Feel free to reach out if you have any more questions or need further assistance.
> 
> Best regards, CVHub

好的多谢！gui版本计划什么时间发布呢

**Comment by CVHub520** [comment]
You're welcome! As for the GUI version release, I aim to release it as soon as possible. Keep an eye on the repository for updates, and you'll be among the first to know when the new version is available.

**Comment by CVHub520** [comment]
Hi, @Syorst ,  the latest version, [v2.0.0](https://github.com/CVHub520/X-AnyLabeling/releases/tag/v2.0.0), has been released. Thank you for your patience, and feel free to give it a try.

**Comment by Syorst** [comment]
> Hi, @Syorst , the latest version, [v2.0.0](https://github.com/CVHub520/X-AnyLabeling/releases/tag/v2.0.0), has been released. Thank you for your patience, and feel free to give it a try.

尝试了一下，导入attributes.json。内容如下：
{
    "person": {
        "wearsGlasses": ["yes", "no"],
        "wearsMask": ["yes", "no"],
        "clothingColor": [
            "red",
            "green",
            "blue"
        ]
    }
}
然后导入图片绘制矩形框，标签输入person，有无效标签提示，内容为无效标签‘person’，验证类型‘['person']’,如何解决该问题？

**Comment by CVHub520** [comment]
> > Hi, @Syorst , the latest version, [v2.0.0](https://github.com/CVHub520/X-AnyLabeling/releases/tag/v2.0.0), has been released. Thank you for your patience, and feel free to give it a try.
> 
> 尝试了一下，导入attributes.json。内容如下： { "person": { "wearsGlasses": ["yes", "no"], "wearsMask": ["yes", "no"], "clothingColor": [ "red", "green", "blue" ] } } 然后导入图片绘制矩形框，标签输入person，有无效标签提示，内容为无效标签‘person’，验证类型‘['person']’,如何解决该问题？

I will fix it later, please waiting for update.

**Comment by CVHub520** [comment]
@Syorst, This Issue resolved; please pull the latest source code or download the most recent GUI version for execution.
