### ISSUE TITLE
paddle使用问题

### ISSUE THREAD

**Issue by zhaojunliing** [CVHub520/X-AnyLabeling#112]
paddle怎么生成onnx文件，怎么配置yaml文件，有示例吗

**Comment by CVHub520** [comment]
> paddle怎么生成onnx文件，怎么配置yaml文件，有示例吗

Hi, @zhaojunliing, you can refer to [this](https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop).

**Comment by zhaojunliing** [comment]
paddle是需要自己修改吗

**Comment by CVHub520** [comment]
Hi there,

Could you please specify which model you are referring to? If it's one of the models listed in [models_list](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/models_list.md), you shouldn't need to make modifications. However, if it's a new model, you'll need to implement the preprocessing and postprocessing logic yourself. You can find guidance on this in the [custom_model documentation](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md).

Let me know if you have further questions or if there's anything else I can help you with.

**Comment by zhaojunliing** [comment]
我是用[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection)
训练了一个模型，正常导出onnx了，但是不能使用

models_list 中rtdetr_r50vd_6x_coco.onnx是基于飞浆的，我配置文件按照这个改，还是不能使用

还有一个功能，自动AI识别后，怎么停止自动识别

**Comment by CVHub520** [comment]
Hello, @zhaojunliing, if you've trained a model using PaddleDetection and successfully exported it to ONNX, you'll need to create a custom model integration for it. It's not possible to directly use the `rtdetr_r50vd_6x_coco.onnx` configuration for a PaddleDetection model unless it's specifically an rtdetr model.

To integrate your custom PaddleDetection model, you'll need to write the model inference logic yourself. You can refer to the documentation on loading custom_model.md.

As for stopping the automatic AI recognition, currently, you can't stop it manually once initiated. The recognition process usually occurs instantaneously, and the tool is designed to handle it seamlessly. If you have further questions or if there's anything else I can assist you with, feel free to let me know.
