### ISSUE TITLE
Linux-GPU安装

### ISSUE THREAD

**Issue by larryKra** [CVHub520/X-AnyLabeling#113]
我按照如下步骤在linux上运行

安装所需的 GPU 环境；
requirements-gpu.txt
修改 ./anylabeling/app_info.py 文件：
...
__preferred_device__ = "GPU"  # GPU or CPU
重新运行即可。

但是得到如下告警，然后没有往下继续运行了。
This plugin does not support propagateSizeHints()
This plugin does not support raise()

请问有人遇到过嘛

**Comment by CVHub520** [comment]
Hi, @larryKra, maybe you can try to set ` QT_QPA_PLATFORM='offscreen'`. If the issue still raise, you should reinstall the package, make sure that the verson of qt fit your system.

**Comment by larryKra** [comment]
> Hi, @larryKra, maybe you can try to set ` QT_QPA_PLATFORM='offscreen'`. If the issue still raise, you should reinstall the package, make sure that the verson of qt fit your system.

hi， I have set QT_QPA_PLATFORM='offscreen' in my ~/.bashrc file, but the waring stll exists.  And which package u mentioned should be reinstalled?

**Comment by CVHub520** [comment]
Hi, it seems like you've set QT_QPA_PLATFORM='offscreen' in your ~/.bashrc file, but the warning persists. There could be a couple of reasons for this.

One possibility is that your current execution environment lacks graphical resources, such as when running in a Docker environment or when X11, a graphical window management system, is not available. Ensure that your environment provides the necessary graphical resources.

Additionally, make sure the version of PyQt5 you are using is compatible with your current production environment. Trying a different version might resolve the issue. Of course, these are general suggestions, and there could be other factors specific to your machine environment. It might be necessary to troubleshoot and experiment based on your setup.

**Comment by larryKra** [comment]
> Hi, it seems like you've set QT_QPA_PLATFORM='offscreen' in your ~/.bashrc file, but the warning persists. There could be a couple of reasons for this.
> 
> One possibility is that your current execution environment lacks graphical resources, such as when running in a Docker environment or when X11, a graphical window management system, is not available. Ensure that your environment provides the necessary graphical resources.
> 
> Additionally, make sure the version of PyQt5 you are using is compatible with your current production environment. Trying a different version might resolve the issue. Of course, these are general suggestions, and there could be other factors specific to your machine environment. It might be necessary to troubleshoot and experiment based on your setup.

Thank u for ur reply. I have checked graphical resources by enter "echo $XDG_SESSION_TYPE" and it's X11. And the app runs in conda virtual environment. 

The second point u mentioned about the version of PyQt5. Can u offer some suggested version of related setup.

**Comment by CVHub520** [comment]
Thank you for the additional information. I apologize for the delayed response. It's good to know that you're running in an X11 environment, and the application is in a conda virtual environment. Regarding PyQt5 versions, the tool has been tested with version 5.15.7. If you encounter issues with the current version, you might consider trying this specific version to see if it resolves the problem.

Has the issue been resolved on your end? If not, feel free to provide more details, and I'll do my best to assist you.
