### ISSUE TITLE
能不能增加色块覆盖功能，以遮挡不想标注的模糊目标

### ISSUE THREAD

**Issue by zhaotun** [CVHub520/X-AnyLabeling#114]
在对图片进行标注时，有些目标模棱两可、似是而非，如果对这些目标进行标注，会因其质量差而影响训练精度，如果完全不标注，它确实也是一种目标。还有一种情况就是，有些区域密集目标比较多，如果对目标进行逐一标注，会比较费时，能否开发一个覆盖功能，对这种不太确定的目标或者不想标注的区域直接用色块进行覆盖，遮挡那些目标或区域，这样就能保证更好的标注质量，并降低在训练过程中的不确定性，现有的一些标注工具似乎都没有这个功能，能不能开发一下。

**Comment by CVHub520** [comment]
Hello, @zhaotun:

Thank you for sharing your thoughts and suggestions. I understand your concern about ambiguous or challenging-to-annotate objects, and your idea of introducing a coverage or masking feature is interesting. While this specific feature might not be currently available, you can employ an alternative approach by using an "ignore" label and subsequently processing the annotated data based on this label during training.

Your feedback is valuable, and we'll consider it for future updates. If you have any more ideas or if there's anything else I can assist you with, feel free to let me know.

Best regards,
CVHub
