### ISSUE TITLE
problem about loading model train by myself

### ISSUE THREAD

**Issue by Chlhacker** [CVHub520/X-AnyLabeling#115]
Hi,it shows  the message "miss config num_masks",what is it suppose to be?

**Comment by CVHub520** [comment]
> Hi,it shows the message "miss config num_masks",what is it suppose to be?

Hi, @Chlhacker, just append the `num_masks` hyper-parameter. For example, you can refer [this](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov8s_seg.yaml).

**Comment by Chlhacker** [comment]
> > Hi,it shows the message "miss config num_masks",what is it suppose to be?
> 
> Hi, @Chlhacker, just append the `num_masks` hyper-parameter. For example, you can refer [this](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov8s_seg.yaml).

thanks for your reply, the problem is already fixed, and it's really a great tools!!!
