### ISSUE TITLE
yolov8-pose-6x模型最后想生成yolo格式，而不是默认的格式，我在选择yolo格式的时候数据是什么样的？请教

### ISSUE THREAD

**Issue by LiYangDoYourself** [CVHub520/X-AnyLabeling#117]

**Comment by CVHub520** [comment]
Hi, @LiYangDoYourself , u can refer this video [toturial](https://www.bilibili.com/video/BV18j411v7qB/?vd_source=938654fc70710bf1d11daa4b779d2418).
