### ISSUE TITLE
OCR文字修改

### ISSUE THREAD

**Issue by xiaocheng1215** [CVHub520/X-AnyLabeling#118]
用模型预测文字框和文字识别后，对于识别错误的需要手工修正，但是文字修改区域在右侧，离文字框比较远，使用不是很方便，能否把文字修改区域显示在文字框上方，这样眼睛只需要专注一个地方（文字框区域），可以大大提高效率，谢谢

**Comment by CVHub520** [comment]
Hi, @xiaocheng1215, thank you for your suggestion. I appreciate your feedback on improving the user experience. However, at the moment, I don't have immediate plans or a timeline to implement this specific feature. I'll certainly consider it for future updates, and your input is valuable in helping me prioritize enhancements.
