### ISSUE TITLE
加载自定义模型并推理没有结果

### ISSUE THREAD

**Issue by perces** [CVHub520/X-AnyLabeling#12]
我用yolov7-main分支训练的模型，使用：
python export.py --weights /lvol1/jjpeng/yolov7/runs/train/terminal_status_landi_newland_pax_newpos_verfone/weights/best.pt --end2end  --simplify --topk-all 100 --iou-thres 0.65 --conf-thres 0.35 --img-size 1280 1280 --max-wh 1280进行导出onnx模型。导出过程无问题，使用onnx推理也验证模型没问题。验证结果如下：
![image](https://github.com/CVHub520/X-AnyLabeling/assets/67944897/dc37b3f6-9fe2-46af-abb8-e1824b509864)

但是按照教程配置并使用自定义模型的时候，加载似乎没有问题，但是运行后没有任何输出。
![image](https://github.com/CVHub520/X-AnyLabeling/assets/67944897/996995c6-584b-4348-a64e-e05f3d1f87eb)
以下是我的yaml配置文件：
![image](https://github.com/CVHub520/X-AnyLabeling/assets/67944897/e2093383-638c-4feb-a255-be4b3da32b16)

**Comment by CVHub520** [comment]
您好，请参考以下导出命令，不要加后处理：

```bash
python export.py --weights /lvol1/jjpeng/yolov7/runs/train/terminal_status_landi_newland_pax_newpos_verfone/weights/best.pt --simplify --img-size 1280 1280
```
