### ISSUE TITLE
标注视频时，是否具有追种模式？

### ISSUE THREAD

**Issue by Syorst** [CVHub520/X-AnyLabeling#120]
例如，在进行关键点标注时，只需标注第一帧，后续帧会自动标注出来，人工只需对后续帧的框的位置和关键点的位置进行微调即可，不用重新画框

**Comment by CVHub520** [comment]
Hi, @Syorst:

For the scenario you've described, where keypoint annotation is required for only the first frame and subsequent frames should be automatically annotated, you can achieve this by enabling the "Keep Previous Annotation" mode. This mode automatically copies the annotations from the previous frame, allowing you to make minor adjustments to the bounding box and keypoint positions without having to redraw them. However, it doesn't support [XMem](https://github.com/hkchengrex/XMem)-like mode.

Additionally, you may find the built-in tracking models useful for this purpose.

If you have any more questions or if there's anything else I can assist you with, feel free to let me know.

Best regards,
CVHub
