### ISSUE TITLE
只标注需要的类别

### ISSUE THREAD

**Issue by CoachingJane** [CVHub520/X-AnyLabeling#121]
如图，我只需要car这个类别
![image](https://github.com/CVHub520/X-AnyLabeling/assets/44397199/5da40d77-caa9-4a0f-85b9-396f47c0c1e3)
模型选择为
![image](https://github.com/CVHub520/X-AnyLabeling/assets/44397199/fffd6647-5dce-47b7-b79b-abca4f761cf1)
选择保存格式为yolo，运行报错，输出为空
![image](https://github.com/CVHub520/X-AnyLabeling/assets/44397199/f552f5db-c1e0-4c6e-9db0-a1a33f265192)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/44397199/a1e80743-e04d-4fa8-94f4-374d7403340e)
切换为VOC正常运行，结果正常
![image](https://github.com/CVHub520/X-AnyLabeling/assets/44397199/389524a2-f9fe-4a1e-8bb8-5f03a5163331)
但是无论哪种情况，我都无法只标注我需要的类别，请问暂时不支持这个功能还是我的使用方法不对
（ps：貌似视频读入的路径不支持包含中文）

**Comment by CVHub520** [comment]
Hello, @CoachingJane: 

Thank you for bringing this to our attention. Currently, the DAMA_YOLO model doesn't support class filtering, but I'm pleased to inform you that this feature is in development and is expected to be included in the next release, which is scheduled for the next few days. Once the update is released, you will be able to use the `filter_classes` field in the configuration file to specify the classes you want to annotate.

Here's an example of how to use it:
```yaml
type: damo_yolo
...
classes:
  - person
  - car
  - dog
  - cat
  - apple
  - phone
  - ...
filter_classes:
  - car
  - apple
```

Regarding the video input, currently, it relies on the OpenCV library, and therefore, it does not support Chinese characters in the file path. Please consider using English characters or symbols in the file path for video input.

If you have any more questions or if there's anything else I can assist you with, feel free to let me know.

Best regards,
CVHub

**Comment by CoachingJane** [comment]
您的意思是现阶段的自动标注都不支持还是只有包括DAMA YOLO在内的部分模型不支持？因为我还试了其他的模型，好像也不会理会我写的classes.txt，生成全类别的标注

**Comment by CVHub520** [comment]
Hi, @CoachingJane, I apologize for any confusion. Currently, the latest version of X-AnyLabeling supports label filtering for certain models, including DAMO_YOLO. To achieve this, you need to correctly configure the `filter_classes` field in the YAML configuration file.

For instance, if your original model supports detection for five classes:
```yaml
classes:
  - person
  - car
  - apple
  - tree
  - book
```
And you only want to annotate the "car" class, you can add the following to your YAML configuration:

```yaml
filter_classes:
  - car
```
Please make sure you've set up the `filter_classes` field appropriately.  Specifically, you may refer to this [yaml](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov5m_bytetrack.yaml), which can better show you the details.

If you encounter any issues or have further questions, feel free to let me know. Cheers.
