### ISSUE TITLE
python anylabeling/app.py

### ISSUE THREAD

**Issue by Zomcxj** [CVHub520/X-AnyLabeling#123]
①：Failed to load translation for zh_CN. Using default language.
②：无法加载图标
windows下自己编译出来的cpu.exe同样如此

**Comment by CVHub520** [comment]
Hi, @Zomcxj , could u try to solve it by running the following command:
```bash
pyrcc5 -o anylabeling/resources/resources.py anylabeling/resources/resources.qrc
```
If the issue still persists, may be you should consider run following commands:
```bash
python scripts/generate_languages.py
pyrcc5 -o anylabeling/resources/resources.py anylabeling/resources/resources.qrc
```
Hope these ways can address u question, cheers.

**Comment by Zomcxj** [comment]
命令行太长。
Updating 'anylabeling/resources/translations/en_US.qm'...
    Generated 0 translation(s) (0 finished and 0 unfinished)
    Ignored 238 untranslated source text(s)
命令行太长。
Updating 'anylabeling/resources/translations/zh_CN.qm'...
    Generated 238 translation(s) (238 finished and 0 unfinished)
看起来是成功了   但是依旧存在那两个问题

**Comment by CVHub520** [comment]
> 命令行太长。 Updating 'anylabeling/resources/translations/en_US.qm'... Generated 0 translation(s) (0 finished and 0 unfinished) Ignored 238 untranslated source text(s) 命令行太长。 Updating 'anylabeling/resources/translations/zh_CN.qm'... Generated 238 translation(s) (238 finished and 0 unfinished) 看起来是成功了 但是依旧存在那两个问题

A potential problem is the lack of relevant Chinese fonts.

**Comment by Zomcxj** [comment]
解决了这个问题app.py中路径有问题，以推送修改
但是图标还是无法加载，望解答
