### ISSUE TITLE
Why the App Can't Start

### ISSUE THREAD

**Issue by hustwayway** [CVHub520/X-AnyLabeling#128]
![Snap3](https://github.com/CVHub520/X-AnyLabeling/assets/128948867/1879cbb5-e063-423c-95ec-41936460351a)

**Comment by CVHub520** [comment]
Hello, @hustwayway:

To resolve the `AttributeError: 'NoneType' object has no attribute 'items'` issue, please try deleting the .anylabelingrc file in your user directory and restart the application.

```bash
#Windows
del C:\Users\${Username}\.anylabelingrc

#Linux&Mac
rm ~/.anylabelingrc
```

If you encounter any further issues, feel free to reach out for assistance.

Best regards,
CVHub
