### ISSUE TITLE
希望能够在标注完，设置透明度的颜色，一键填充标注框，检查是否有遗漏

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#13]
主要针对一张图中，目标数量较多的情况，不是通用场景，优先级不高

**Comment by CVHub520** [comment]
> 主要针对一张图中，目标数量较多的情况，不是通用场景，优先级不高

您好，这个可以通过开启编辑模式(`Ctrl+J`)实现，会自动填充颜色。

**Comment by aiyou9** [comment]
> > 主要针对一张图中，目标数量较多的情况，不是通用场景，优先级不高
> 
> 您好，这个可以通过开启编辑模式(`Ctrl+J`)实现，会自动填充颜色。

您好，编辑模式，不支持全选对象列表，全部填充颜色，目前，我用上下键，移动来一个个看，代替了
