### ISSUE TITLE
Error in loading model: Missing config: num_masks

### ISSUE THREAD

**Issue by Karlvision** [CVHub520/X-AnyLabeling#134]
当我添加自定义模型以后，提示Error in loading model: Missing config: num_masks 。我使用的yolov8n-seg模型。
以下是我的配置
![image](https://github.com/CVHub520/X-AnyLabeling/assets/50682981/58bd1a08-bc84-47e5-a345-c5382dbb8b33)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/50682981/869242d5-913c-409f-88f9-0b9d8359a448)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/50682981/227c1f3c-1aa8-4f35-96a1-a575b8f913c8)

**Comment by CVHub520** [comment]
Hi, @Karlvision:
The issue you encountered with the error message "Error in loading model: Missing config: num_masks" has been addressed in the latest version. Kindly download the latest source code and run the application. 

If you encounter any further issues or have additional questions, please feel free to ask.

Best regards,
CVHub

**Comment by ABCD98989988520** [comment]
@CVHub520 我使用你的最新版本的源程序运行还是遇到了“Error in loading model: Missing config: num_masks ”，请问作者这是什么情况呀？

![Image](https://github.com/user-attachments/assets/0581e79e-f236-4596-adac-9ff560e3cb4c)

![Image](https://github.com/user-attachments/assets/d63866c1-9efb-4ff2-9a71-25d40196389c)

![Image](https://github.com/user-attachments/assets/3459484a-2b45-46ed-b007-0daf23acd2be)

**Comment by CVHub520** [comment]
@ABCD98989988520 您好，请通过 `git clone` 拉取最新的源码，请按照官方配置文件设置：https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov8x_pose_p6.yaml

**Comment by ABCD98989988520** [comment]
@CVHub520 好的，谢谢！应该是类别名称使用纯数字导致的异常，目前已经恢复正常了！非常感谢作者的指导！
