### ISSUE TITLE
是否支持后台运行自动标注？

### ISSUE THREAD

**Issue by elepherai** [CVHub520/X-AnyLabeling#137]
你好，想问下X-AnyLabeling在不打开工具界面的情况下，是否支持后台运行自动标注？像标签转换那样的

**Comment by CVHub520** [comment]
@elepherai : Hi, X-AnyLabeling is not designed to support automatic annotation directly without opening the tool interface. Its primary purpose is to provide users with an interactive annotation tool. 

If you need automation for annotation tasks, you may consider integrating with X-AnyLabeling by writing custom scripts. This can be done by calling the relevant APIs to interact with the tool and achieve some level of automation.

Best regards,
CVHub

**Comment by littleYaang** [comment]
你好，如何调用api以实现后台自动标注呢？这将给大量标注带来极大的便利，恳请你给出一些示例。

**Comment by CVHub520** [comment]
@littleYaang, Hello, currently, this functionality is not supported. You can try encapsulating the [model inference](https://github.com/CVHub520/X-AnyLabeling/tree/main/anylabeling/services/auto_labeling) and expose it as an API to achieve automated labeling on the backend.
