### ISSUE TITLE
How to extract *.png files, while selecting video in X-AnyLabeling tool

### ISSUE THREAD

**Issue by lenka-79** [CVHub520/X-AnyLabeling#138]
Hi,

when you select a specific video while in X-AnyLabeling tool, it will extract automatically *.jpg images/files in to specify a output directory, but Is there any option to extract *.png images/files instead of *.jpg's.

Please let me know if any option available in the tool.

Thanks in Advance,
L V Giribabu.

**Comment by CVHub520** [comment]
@lenka-79, hello, Giribabu, currently, the program is configured to save images in the default format, which is jpg. If you need to set it to png, you can achieve this by modifying the source code. Specifically, you can locate [this line](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/views/labeling/label_widget.py#L3221) and replace "jpg" with your desired format.

If you have any further questions or encounter difficulties, feel free to ask. I'm here to assist you.

Thanks,
CVHub

**Comment by lenka-79** [comment]
Hi,

Thank you very my for your support, now I am able to get it.

Regards,
L V GiriBabu.

**Comment by lenka-79** [comment]
Right now we have few concerns/issues with Xanylabeling tool  

1) how to select/use auto run option in this tool

-> while using this option,  some frames are skipping b/w the video ( apporx. 30 to 40% farems are skipped) ( tried 2 different models with Grounding dino & Yolo V8 ultralytics )

2) how to remove /eliminate false detection in frame

-> some times more no of classes are detecting , how to eliminate it, even thought we are using 1 class in my customized class.txt file

3) can we do 100% automation possible using this tool..

Thanks,
L V Giribabu
