### ISSUE TITLE
How to get Yolo.txt format instead of *.Json file as an output 

### ISSUE THREAD

**Issue by lenka-79** [CVHub520/X-AnyLabeling#139]
Hi,

While doing annotation using X-AnyLabeling tool, default output format is saving as *.json files in to specify a output directory,
but in the weblink mentioned 

![image](https://github.com/CVHub520/X-AnyLabeling/assets/152685134/b9ff564b-9ecb-4669-9e2d-613822837377)

how to get yolo.txt file instead of  Json.txt files in output 

Thanks,
L V Giribabu.

**Comment by CVHub520** [comment]
Hi, @lenka-79:

Exporting YOLO labels is straightforward. 

First, you need to prepare a custom label file, and you can refer to the sample file provided [here](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/classes.txt). 
Secondly, after importing the task, click on `Format` at the top of the interface, then choose `YOLO`. Next, import the pre-prepared custom label file. 
Finally, the TXT label file will be automatically saved in the same directory as the current image, under a folder named "labels."

If you encounter any difficulties or have further questions, please feel free to ask. I am here to assist you to the best of my ability.

Best regards,
CVHub

**Comment by lonngxiang** [comment]
> Hi, @lenka-79:
> 
> Exporting YOLO labels is straightforward.
> 
> First, you need to prepare a custom label file, and you can refer to the sample file provided [here](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/classes.txt). Secondly, after importing the task, click on `Format` at the top of the interface, then choose `YOLO`. Next, import the pre-prepared custom label file. Finally, the TXT label file will be automatically saved in the same directory as the current image, under a folder named "labels."
> 
> If you encounter any difficulties or have further questions, please feel free to ask. I am here to assist you to the best of my ability.
> 
> Best regards, CVHub

uploading  a custom label file, software freezes

**Comment by CVHub520** [comment]
> > Hi, @lenka-79:
> > Exporting YOLO labels is straightforward.
> > First, you need to prepare a custom label file, and you can refer to the sample file provided [here](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/classes.txt). Secondly, after importing the task, click on `Format` at the top of the interface, then choose `YOLO`. Next, import the pre-prepared custom label file. Finally, the TXT label file will be automatically saved in the same directory as the current image, under a folder named "labels."
> > If you encounter any difficulties or have further questions, please feel free to ask. I am here to assist you to the best of my ability.
> > Best regards, CVHub
> 
> uploading a custom label file, software freezes

Hi, @lonngxiang, the new version is released, ignore the above method, please git clone the latest source code and follow this [toturial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md).
