### ISSUE TITLE
为SAM分割，标注的矩形，在完成时，设置增加长宽，特定的目标检测，需要四周光影分界线

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#14]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/d8378002-dd86-4859-965d-4cd6d83714fc)

**Comment by xinyuanTan** [comment]
同样的需求

**Comment by aiyou9** [comment]
> 同样的需求

我准备在这个批量的里面改，
https://github.com/gyhdc/LabelSAM-for-yolo

**Comment by aiyou9** [comment]
这个项目增加了一些操作sam的功能  
https://github.com/branislavhesko/segment-anything-ui

**Comment by aiyou9** [comment]
大佬建议了，可以自己在代码里，加计算的默认放大系数，因此关闭了
