### ISSUE TITLE
Group shortcut key G

### ISSUE THREAD

**Issue by Sean27oz** [CVHub520/X-AnyLabeling#141]
Group shortcut key G can only be used once, multiple groups appear in a frame, you can only manually group.

**Comment by CVHub520** [comment]
Hello, @Sean27oz :

Thank you for bringing this to my attention. Currently, the group shortcut key 'G' is designed to work only for the selected target. Therefore, you can achieve grouping for multiple targets within a frame by holding down the Ctrl key and clicking on each target you want to include. Subsequently, you can use the 'G' or 'U' shortcut keys to trigger the grouping/un-grouping action.

If you have any further questions or encounter any issues, please feel free to ask.

Best regards,
CVHub

**Comment by Sean27oz** [comment]
不好意思，我可能又没表达清楚问题～～

再仔细描述一下：在同一帧中，如果存在多个组别，快捷键只支持第组归类，第二组用快捷键G是无法实现归组功能的，只能手动输入组别才能实现第二组的归组。您可以复现一下，我用的是最新源码，在ubuntu18下编译的可执行文件，CPU版本。谢谢！

**Comment by Sean27oz** [comment]
另外还有一个建议，同一帧中的多目标分割的时候，能否将不同分割目标区域通过不同颜色区分，这样对于提效有很大帮助，一眼就能看出标注是否有问题。目前是只有分割的线颜色不一样。

**Comment by CVHub520** [comment]
Thank you for providing additional details. The grouping feature will be re-evaluated in a later update. Please stay tuned for further announcements.
