### ISSUE TITLE
ctrl+v貌似不生效

### ISSUE THREAD

**Issue by 3287134551** [CVHub520/X-AnyLabeling#145]
我用了cpu最新的exe，但是复制和粘贴貌似没用。只能手动用鼠标右键复制和粘贴

**Comment by 3287134551** [comment]
我看了下粘贴还是ctrl+d，而且粘贴还会跑偏

**Comment by CVHub520** [comment]
> 我用了cpu最新的exe，但是复制和粘贴貌似没用。只能手动用鼠标右键复制和粘贴

@3287134551, Hello, the latest source code has already fixed many bugs and introduced numerous new features. Feel free to download and experience it. 

As some features are still in ongoing development and refinement, the latest compiled version may not be available yet. Therefore, please run it from the source code side for now. 

Keep an eye out for future updates, and thank you for your patience.

Best Regards,
CVHub

**Comment by 3287134551** [comment]
okok，Thank you
