### ISSUE TITLE
Error in loading model :'YOLOv5' object has no attribute ' stride '

### ISSUE THREAD

**Issue by laoruiwen** [CVHub520/X-AnyLabeling#146]
type: yolov5
name: stone1010
display_name: stone1010
model_path: stone1010.onnx
input_width: 1280
input_height: 1280
nms_threshold: 0.45
confidence_threshold: 0.6
classes:
  - stone
anchors:
  - [11,10, 17,14, 21,21]  # P3/8
  - [21,25, 27,26, 32,32]  # P4/16
  - [45,27, 44,44, 84,78]  # P5/32

**Comment by meihuanhan** [comment]
这个怎么解决的呀

**Comment by laoruiwen** [comment]
您好!您的邮件我已收到,感谢您的来信,我会尽快予以您回复,谢谢!~~

**Comment by CVHub520** [comment]
> 这个怎么解决的呀

Hi, @meihuanhan, there is no need to append `stride` param in config.yaml. If the yolov5 version u using now are large than v5.0, please don't add the `anchors` in it.

For more detail, you can learn from this [toturial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md).

If you still encouter issues, please feel free to contact me in wechat: ww10874.
