### ISSUE TITLE
yolov8_pose骨骼点越界

### ISSUE THREAD

**Issue by ChaocunChen** [CVHub520/X-AnyLabeling#147]
用yolov8x-pose标注发现骨骼点越界了（keypoint超出人体框），这不合理吧

**Comment by CVHub520** [comment]
@ChaocunChen ，Hi, thank u for your kindly feedback, I will check it as soon as possiable.

**Comment by ChaocunChen** [comment]
> @ChaocunChen ，Hi, thank u for your kindly feedback, I will check it as soon as possiable.
我在anylabeling/services/auto_labeling/yolov8_pose.py代码85、86 行添加x = max(min(x, xmax - 1), xmin + 1) y = max(min(y, ymax - 1), ymin + 1) 这样是不是合理的呢

**Comment by CVHub520** [comment]
This issue has been resolved. Please update the source code to use.
