### ISSUE TITLE
Visualisation Oriented Bounding Box

### ISSUE THREAD

**Issue by Robert-Ven** [CVHub520/X-AnyLabeling#148]
Hi,

Is it possible to add a visualiation of the top direction for oriented bounding boxes? Either by giving a defined corner of the rotation box a different shape, or adding a line going up? 
For our dataset, we are interested in the 2D pose of objects, so the center X, Y, and theta. To make sure we label consistently, we would like to be able to see this. 

Best,
Robert

**Comment by CVHub520** [comment]
Hi Robert,

Thank you for reaching out and sharing your requirements. I appreciate your insights into improving the visualization of oriented bounding boxes. I understand the need for clearer indications of the box orientation.

I will certainly take your suggestions into consideration. Please bear with me as I work on implementing these enhancements. If you have any further details or specific preferences, feel free to let me know.

Thank you for your patience and understanding.

Best regards,
CVHub

**Comment by Robert-Ven** [comment]
Hi, 

If possible, I can also try to change it myself and put in a pull request. Can you point me to the files that would need changing for this? 

Best,
Robert

**Comment by CVHub520** [comment]
Yeadh, I'm glad to hear that you're planning to do that.

Specifically, you can try implementing this feature in the [drawing event](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/views/labeling/widgets/canvas.py#L923C17-L923C17).
