### ISSUE TITLE
yolov6人脸模型只出现了人脸关键点没有出现人脸框

### ISSUE THREAD

**Issue by Suyixiu** [CVHub520/X-AnyLabeling#150]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/35776880/cdfe166d-164f-478c-b847-4aab78b7735a)
对于上述图片，KUNKUN的脸框并没有显示出来，对应的yaml文件中我已经将confidence_threshold阈值调整为0.1，但是框还是不出

**Comment by CVHub520** [comment]
@Suyixiu, Hi, sorry, it's my fault. 

You can reproduce iKun's face by adding the following line of code to line 156 of this [file](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/yolov6_face.py):

```python3
shapes.append(rectangle_shape)
```
