### ISSUE TITLE
在linux上运行yolov8_pose模型标注时缺失人体框

### ISSUE THREAD

**Issue by ChaocunChen** [CVHub520/X-AnyLabeling#151]
我在linux机器上下载了代码，运行python anylabeling/app.py 用yolox_pose模型进行标注，发现人体框没有出现，只有骨骼点，我查看了https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/yolov8_pose.py 代码没有发现异常，但是标注结果确实缺少了人体框；另外我自己编译了linux-gpu版本运行，也是一样的问题，我不知道问题出现在哪儿，可以帮忙看下吗，非常感谢！@CVHub520  PS：我用release下的 X-AnyLabeling-CPU.exe(https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.1.0/X-AnyLabeling-CPU.exe) 标注人体框和骨骼点都是正常的,并且我自己编译win-cpu版本也是正常的

**Comment by CVHub520** [comment]
Hello, @ChaocunChen:

Due to the recent reconstruction in the new version, if you're missing the body boxes when annotating with the YOLOv8_pose model on Linux, don't worry, you just simply add the `show_boxes` parameter to the configuration file and set its value to True. 

This should display the body boxes as expected. If the issue persists, please let me know for further assistance.

Best regards,
CVHub

**Comment by ChaocunChen** [comment]
> Hello, @ChaocunChen:
> 
> Due to the recent reconstruction in the new version, if you're missing the body boxes when annotating with the YOLOv8_pose model on Linux, don't worry, you just simply add the `show_boxes` parameter to the configuration file and set its value to True.
> 
> This should display the body boxes as expected. If the issue persists, please let me know for further assistance.
> 
> Best regards, CVHub

我在配置文件里设置了show_shapes: true show_boxes: true  运行python anylabeling/app.py 结果依然没有人体框，检查json标注文件也没有person这一类别，请帮帮我吧，谢谢

**Comment by CVHub520** [comment]
> > Hello, @ChaocunChen:
> > Due to the recent reconstruction in the new version, if you're missing the body boxes when annotating with the YOLOv8_pose model on Linux, don't worry, you just simply add the `show_boxes` parameter to the configuration file and set its value to True.
> > This should display the body boxes as expected. If the issue persists, please let me know for further assistance.
> > Best regards, CVHub
> 
> 我在配置文件里设置了show_shapes: true show_boxes: true 运行python anylabeling/app.py 结果依然没有人体框，检查json标注文件也没有person这一类别，请帮帮我吧，谢谢

Can u show me your custom *.yaml config file?

**Comment by CVHub520** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/1ebd56b6-4891-4547-a642-21c5c39a808b)

**Comment by ChaocunChen** [comment]
> > > Hello, @ChaocunChen:
> > > Due to the recent reconstruction in the new version, if you're missing the body boxes when annotating with the YOLOv8_pose model on Linux, don't worry, you just simply add the `show_boxes` parameter to the configuration file and set its value to True.
> > > This should display the body boxes as expected. If the issue persists, please let me know for further assistance.
> > > Best regards, CVHub
> > 
> > 
> > 我在配置文件里设置了show_shapes: true show_boxes: true 运行python anylabeling/app.py 结果依然没有人体框，检查json标注文件也没有person这一类别，请帮帮我吧，谢谢
> 
> Can u show me your custom *.yaml config file?

@CVHub520 我之前修改了anylabeling/configs/anylabeling_config.yaml文件，现在修改了anylabeling/configs/auto_labeling/yolov8x_pose_p6.yaml，结果正常了，非常感谢！
