### ISSUE TITLE
masks = self.crop_mask_np(masks, downsampled_bboxes) ？

### ISSUE THREAD

**Issue by deepConnectionism** [CVHub520/X-AnyLabeling#155]
https://github.com/CVHub520/X-AnyLabeling/blob/4a62d6810aa4e74a2e90b584a9a5050f9ef63774/anylabeling/services/auto_labeling/__base__/yolo.py#L347-L348

Why do this twice?

**Comment by CVHub520** [comment]
Hi, @deepConnectionism, thank u for pointing that out. Although it doesn't affect the final inference results, the redundant code line has been removed.
