### ISSUE TITLE
自助导出的rtdetr_r50vd_6x_coco.onnx模型无法使用

### ISSUE THREAD

**Issue by huangye123** [CVHub520/X-AnyLabeling#156]
1、Paddle Model Export
cd PaddleDetection
python tools/export_model.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml -o weights=https://bj.bcebos.com/v1/paddledet/models/rtdetr_r50vd_6x_coco.pdparams trt=True --output_dir=output_inference

2、Convert ONNX Format
paddle2onnx --model_dir=./output_inference/rtdetr_r50vd_6x_coco/ --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 16 --save_file rtdetr_r50vd_6x_coco.onnx

3、导出的ONNX模型的信息
![image](https://github.com/CVHub520/X-AnyLabeling/assets/28778519/11d996bb-24e6-49b8-a056-addf02a6d3d1)

4、使用导出的ONNX模型进X-AnyLsbeling，执行AI，报异常
2023-12-17 10:51:26.5901947 [W:onnxruntime:, graph.cc:108 onnxruntime::MergeShapeInfo] Error merging shape info for output. 'tile_3.tmp_0' source:{} target:{-1}. Falling back to lenient merge.
Error in predict_shapes: unsupported operand type(s) for /: 'str' and 'int'

5、X-AnyLsbeling下载的模型信息
![image](https://github.com/CVHub520/X-AnyLabeling/assets/28778519/3393f626-6004-4d2c-b8bf-461717256ecb)

6、附导出的ONNX模型、yaml配置文件 ，测试图片
链接：https://pan.baidu.com/s/1VUFIv0Phmy43TCcS4RjdFg?pwd=1wz5 
提取码：1wz5

**Comment by CVHub520** [comment]
Hi, @huangye123, u can refer this [toturial](https://zhuanlan.zhihu.com/p/628660998) for exporting your custom model.

If you still encounter issues or need further assistance, please feel free to ask me.

Best regards,
CVHub
