### ISSUE TITLE
Error in predict_shapes: list index out of range

### ISSUE THREAD

**Issue by huangye123** [CVHub520/X-AnyLabeling#157]
1、如果推理出的标签索引值，在模型配置文件中classes中不存在对应的时

通过代码方式启动，会报异常Error in predict_shapes: list index out of range

通过exe方式启动，界面不会报异常

建议界面可以提示异常信息。

type: rtdetr
name: rtdetr_r50vd_6x_coco
display_name: rtdetr_r50vd_6x_coco
model_path: D:\\Soft\\rtdetr_r50vd_6x_coco.onnx
score_threshold: 0.2
classes:
- person

**Comment by CVHub520** [comment]
Thanks for your suggestion; I will take it into consideration for the future.
