### ISSUE TITLE
For customized model annotation 

### ISSUE THREAD

**Issue by profLeeli** [CVHub520/X-AnyLabeling#158]
Hi， if I want to use this for my own pre-train yolov8 model for annotation or do some fine-tune for the model using in software, how should I do?

**Comment by CVHub520** [comment]
> Hi， if I want to use this for my own pre-train yolov8 model for annotation or do some fine-tune for the model using in software, how should I do?

Hi, @profLeeli, your can refer to this [docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md).
