### ISSUE TITLE
，运行发现这个错误，怎么解决呢

### ISSUE THREAD

**Issue by jasonccs** [CVHub520/X-AnyLabeling#159]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/17975766/875fcaa0-9feb-4bcc-852f-8ec6c76ccd6c)

**Comment by CVHub520** [comment]
Hi, @jasonccs, which custom model type have you loaded? For example, YOLOv5, SAM, or another?

**Comment by jasonccs** [comment]
导入 YOLOv5 模型的分类  onnx 文件。

**Comment by CVHub520** [comment]
This feature that you loaded is not supported now. Could you please provide me with a zip package including your custom weights in *.onnx format and a picture that can detect objects on your local machine? Please send it to [cv_hub@163.com](mailto:cv_hub@163.com).

**Comment by CVHub520** [comment]
Hi, the latest source code now supports [yolov5-cls](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov5s_cls.yaml) and [yolov8-cls](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov8s_cls.yaml). Feel free to download and give it a try. 

If you encounter any issues, please don't hesitate to contact me. Best regards.
