### ISSUE TITLE
YOLO格式标注导入

### ISSUE THREAD

**Issue by ChenjieXu** [CVHub520/X-AnyLabeling#161]
我用其他模型生成的YOLO标签，想导入这个Xanylabeling进行标注的更改，如何导入这个YOLO标签。

**Comment by CVHub520** [comment]
> 我用其他模型生成的YOLO标签，想导入这个Xanylabeling进行标注的更改，如何导入这个YOLO标签。

Hi, @ChenjieXu, this setup is very easy.

1. Update the latest source code;
2. Prepare a classes.txt file, refer to [this](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/classes.txt);
3. Upload your custom image folder and click the `Upload->Upload YOLO Annotations` button, then just follow the tips in the top status bar to select the corresponding file or folder.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/820231d8-3b82-4218-b5ae-68082d527d92)

If you encounter any issues, please feel free to contact me.

Best Regards,
CVHub

**Comment by ChenjieXu** [comment]
因为我之前用的是release 2.1.0，所以没有看到您说的功能。很高兴能听到这个功能在最新的代码中已经实现了。我会去尝试，感谢CVHub为我们带来的这么好用的工具。
