### ISSUE TITLE
Some idea to improve ease of use

### ISSUE THREAD

**Issue by TRYOKETHEPEN** [CVHub520/X-AnyLabeling#163]
(1) When labeling rectangle at bottom of the picture,  the "OK/select label name" window is hidden.

(2) When labeling rectangle at right edge of picture, and the picture is zoomed in,  there's no gap between the picture and the window slider. It's easy to touch the slider by mistake. 

(3) Could you refer to LabelStudio, using num key to select corresponding labelname and start draw: 
Original: keyboard "R"  -> mouse draw  ->  mouse double click to select labelname  -> finish
To be:     keyboard "1" to select the corresponding label  -> mouse draw  -> finish

**Comment by TRYOKETHEPEN** [comment]
right edge problem example: 
![edgeproblem](https://github.com/CVHub520/X-AnyLabeling/assets/114904417/90f29521-63e4-40b9-aefc-23105d6af24e)

bottom problem example: 
![bottomproblem](https://github.com/CVHub520/X-AnyLabeling/assets/114904417/42284b00-1039-4946-8525-b5f439db83c5)

**Comment by TRYOKETHEPEN** [comment]
For problem 2, I suggest  that sets windows sliders disable during draw process.

(4) Can I use middle mouse button to drag the picture by set ".anylabelingrc" file, how?

**Comment by CVHub520** [comment]
Hello, @TRYOKETHEPEN:

Thank you for your attention. I'll address your concerns one by one:

(1) When labeling a rectangle at the bottom of the picture, if the "OK/select label name" window is obscured, try double-clicking the top of the window. It will maximize the window and make it more accessible.

(2) Similar to the first point, the suggestion to add a gap or disable the window sliders during the draw process at the right edge of the picture when zoomed in will be considered for future improvements.

(3) While the suggestion to use number keys for label selection and drawing like LabelStudio is interesting, it may lead to confusion when there are a large number of labels. Additionally, X-AnyLabeling supports various modes beyond Rectangle, and the design needs to consider compatibility with other modes.

(4) Currently, using the middle mouse button to drag the picture is not a built-in feature. If you wish to implement this, you can consider adding the relevant logic in the source code.

Thank you for your valuable feedback. If you have any more suggestions or encounter further issues, feel free to reach out.

Best regards,
CVHub

**Comment by CVHub520** [comment]
@TRYOKETHEPEN Hey there!

I'm glad to inform you that the latest source code had support the (1) and (2) feature, welcome to use. Happy labeling! 😄

**Comment by CVHub520** [comment]
@TRYOKETHEPEN We've implemented the shortcut functionality now. (#945)
