### ISSUE TITLE
Automation with XAnylabeling tool

### ISSUE THREAD

**Issue by lenka-79** [CVHub520/X-AnyLabeling#164]
Hi,

As per our earlier discussions listed below 

1) https://github.com/CVHub520/X-AnyLabeling/issues/139 &

2) https://github.com/CVHub520/X-AnyLabeling/issues/149

while doing this 

![image](https://github.com/CVHub520/X-AnyLabeling/assets/152685134/460f9461-e892-4236-8958-d22b60755add)

prepared customized class.txt file like below -> 

![image](https://github.com/CVHub520/X-AnyLabeling/assets/152685134/e546d773-2a05-4814-aee7-59ddb67ad3c6)

and tried to do the automation with xanylabeling tool

but we didn't observe any change with & without these modifications,

Please let me know if miss anything here.

Thanks,
L V Giribabu.

**Comment by CVHub520** [comment]
@lenka-79, Hi, let's forget the previous information first.

The X-AnyLabeling has been reconstructed already. Now, if you want to get the YOLO format, just annotate the image as usual. When you've completed the job, click the export button in the top menus, and choose the corresponding format. Note that before you do this step, prepare a [classes.txt](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/classes.txt) first. Then, you will get the results you expected.

The second part is below:
```
Can we eliminate these false detections (multiple bounding boxes appearing on the same pedestrian, some bounding boxes not appearing, etc.) with a licensed tool?
```

To eliminate multiple bounding boxes that appear on the same pedestrian, I suggest adding a relative parameter, for example, `--agnostic`, or adjusting the `nms_threshold` score. This should be modified in the *.yaml configuration file, like [this](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov5s.yaml).

Please note that:

- agnostic:

>   Definition: The term "agnostic" in YOLOv5 refers to the ability of the model to perform object detection in an agnostic manner with respect to class predictions. When the agnostic parameter is set to True, the non-maximum suppression (NMS) operation considers all classes collectively during the post-processing step, rather than treating each class separately.

> Usage: If you set agnostic=True, it means that the NMS operation will be applied without considering the specific class of the object, resulting in potentially higher recall but lower precision. This can be useful in scenarios where you are more interested in detecting objects in general rather than distinguishing between different classes.

- nms_threshold:

> Definition: The NMS threshold is a parameter used during the post-processing step to filter out redundant bounding boxes and keep only the most confident ones. NMS is applied to remove overlapping bounding boxes that may correspond to the same object.

> Usage: The nms_threshold parameter defines the IoU (Intersection over Union) threshold for NMS. Bounding boxes with IoU higher than this threshold are considered as overlapping, and NMS will suppress the one with lower confidence. A higher threshold will result in more aggressive suppression, potentially removing some true positive detections, while a lower threshold may allow more overlapping boxes to be retained.
Typical Value: The value of nms_threshold is typically set between 0.4 and 0.7, but it can be adjusted based on the specific requirements of the application and the characteristics of the dataset.

**Comment by lenka-79** [comment]
Hi,

Thanks for detailed explanation & will work on it and update to u soon..

Regards,
L V GiriBabu.

**Comment by CVHub520** [comment]
In my view, whether to change the value depends on your needs.

**Comment by lenka-79** [comment]
Hi,

Right now I am using 2 different models for doing annotation

1) Yolo-V8m model for doing annotation

![image](https://github.com/CVHub520/X-AnyLabeling/assets/152685134/6ba6938c-5cd5-4366-8ace-5682e196daa3)

if I change/modify the nms_threshold as per my requirement @ yolov8m.yaml file & load the Yolo-v8m model in xanylableing,  will it take updated yolov8m.yaml & reflect the results( avoid redundant bounding boxes) ??

2)  GroundingDino model for doing annotation

if I change/modify the box_threshold as per my requirement @ GroundingDino.yaml file & load the GroundingDino model in xanylableing,  will it take updated GroundingDino .yaml & reflect the results( avoid redundant bounding boxes) ??

Regards,
L V Giribabu.

**Comment by CVHub520** [comment]
Hi, @lenka-79, I think maybe you should learn the hyper-parameters in the model first.
