### ISSUE TITLE
edge_sam model download error with 404

### ISSUE THREAD

**Issue by mengdongwei** [CVHub520/X-AnyLabeling#166]
very good work !!!
bu when i try to use edge sam, i got an error.
the error is "Could not download https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.2.0/edge_sam_encoder.onnx: HTTP Error 404: Not Found"

**Comment by CVHub520** [comment]
Hi, @mengdongwei, the latest version has not been released yet. You can download the weights from the [Baidu Nesk](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/models_list.md).
