### ISSUE TITLE
一些小问题优化建议

### ISSUE THREAD

**Issue by threerog** [CVHub520/X-AnyLabeling#167]
- 设置输出标签格式后(以`yolo`为例，已经导入了标签列表)，能不能在标记完对象设置标签时下面列表中显示出全部标签快速选择；目前情况是只显示已经手动输入过的标签

下面这两点可忽略
- 设置指定输出标签格式后(以`yolo`为例)，创建`labels/*****.txt`的同时创建`train`文件夹将对应的图片拷贝过去
- 右下侧的文件列表可以增加个文件数量(总文件数量/已标记文件量)和当前文件名称或序号显示(直接在窗口标题显示也可以)，文件列表优先显示文件名称，目前情况是文件路径太长 不能直接看到文件名

**Comment by CVHub520** [comment]
Hello, @threerog:

In the latest source code, there's no need to set the label format in advance anymore. You can now export various formats after completing the annotation. I'll be releasing a new version and tutorial in the next few days. 

Regarding the issue of displaying all labels for quick selection in the label list after setting the output label format, you only need to input each label once when it first appears. If you still find it inconvenient, you can open the configuration file `.anylabelingrc` in the user directory and set the `labels` field, as shown below:

```
labels
  - person
  - car
  - ...
```

As for the two points you mentioned at the end, copying files to a `train` folder upon creating the label file and displaying file quantity and current file name or index in the file list, these features are not implemented as they might not be universally applicable. 

The second point about displaying the current progress is already supported in the latest source code. Feel free to give it a try; however, please note that the GUI version (X-AnyLabeling v2.1.0) currently does not support these features.

Best regards,
CVHub

**Comment by threerog** [comment]
> Hello, @threerog:
> 
> In the latest source code, there's no need to set the label format in advance anymore. You can now export various formats after completing the annotation. I'll be releasing a new version and tutorial in the next few days.
> 
> Regarding the issue of displaying all labels for quick selection in the label list after setting the output label format, you only need to input each label once when it first appears. If you still find it inconvenient, you can open the configuration file `.anylabelingrc` in the user directory and set the `labels` field, as shown below:
> 
> ```
> labels
>   - person
>   - car
>   - ...
> ```
> 
> As for the two points you mentioned at the end, copying files to a `train` folder upon creating the label file and displaying file quantity and current file name or index in the file list, these features are not implemented as they might not be universally applicable.
> 
> The second point about displaying the current progress is already supported in the latest source code. Feel free to give it a try; however, please note that the GUI version (X-AnyLabeling v2.1.0) currently does not support these features.
> 
> Best regards, CVHub

- 我尝试了你提到的`.anylabelingrc`文件`labels`配置项，英文标签正常，但是中文标签启动报错
```
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\AnyLabeling\anylabeling\app.py", line 222, in <module>
    main()
  File "C:\Users\Admin\Desktop\AnyLabeling\anylabeling\app.py", line 153, in main
    config = get_config(config_file_or_yaml, config_from_args)
  File "C:\Users\Admin\Desktop\AnyLabeling\.\anylabeling\config.py", line 82, in get_config
    config_from_yaml = yaml.safe_load(f)
  File "C:\App\anaconda3\envs\anylabeling\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\App\anaconda3\envs\anylabeling\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\App\anaconda3\envs\anylabeling\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\App\anaconda3\envs\anylabeling\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\App\anaconda3\envs\anylabeling\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\App\anaconda3\envs\anylabeling\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa7 in position 710: illegal multibyte sequence
```
- 手动输入的中文标签在导出时中文乱码(`VOC`)

- 仍觉得文件列表进度显示非常有必要

- 通过`.anylabelingrc`文件`labels`配置项来设置默认标签列表是影响所有项目，而之前的导入模式是仅限本次启动，可能更合理一点，以上只是个人看法。

**Comment by threerog** [comment]
导入`yolo`标签时是否考虑支持直接导入`yolo`标准的`yaml`文件
```
path: C:\Users\Admin\Desktop\yolov8
train: ***
val: ***
test: ***
names:
  0: 标签1
  1: 标签2
  2: 标签3
```
将`yaml.names`作为`labels`

**Comment by CVHub520** [comment]
1. The issue of `Chinese` label import displaying as garbled characters is not related to the tool itself. This is due to the lack of Chinese fonts in the current system environment. You can refer to the following steps to configure it.
```
# Linux
cd /usr/share/fonts
sudo mkdir myfonts
cd myfonts
sudo cp /mnt/c/Windows/Fonts/simsun.ttc .
sudo mkfontscale
sudo mkfontdir
sudo fc-cache -fv
```
Note: In this case, /mnt/c/Windows/Fonts/simsun.ttc is the file for the SimSun font. You can copy your preferred Chinese-supported *.ttc file to the myfonts directory.

2. As mentioned before, the latest source code already supports displaying the progress in the current file list. Please refrain from using the GUI version for now.

3. The current behavior is intentional; please observe it closely.

4. The UI localization part will be improved in the upcoming release. Thank you for your attention!

**Comment by CVHub520** [comment]
> 导入`yolo`标签时是否考虑支持直接导入`yolo`标准的`yaml`文件
> 
> ```
> path: C:\Users\Admin\Desktop\yolov8
> train: ***
> val: ***
> test: ***
> names:
>   0: 标签1
>   1: 标签2
>   2: 标签3
> ```
> 
> 将`yaml.names`作为`labels`

Please note that this is not a universal requirement, and defining it in a unified style is beneficial for reducing the learning curve for users. Given that X-AnyLabeling is currently fully open source, you can easily customize and develop this option by writing just a few lines of code.

**Comment by CVHub520** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/71b1516b-d59c-4c61-8850-dfff7d0478a9)

**Comment by threerog** [comment]
1. 通过`.anylabelingrc`文件`labels`配置项设置中文标签启动报错
2. 工具导出标签时中文乱码

这些问题和系统应该没什么关系吧,我是windows且支持中文字体

**Comment by CVHub520** [comment]
> 1. 通过`.anylabelingrc`文件`labels`配置项设置中文标签启动报错
> 2. 工具导出标签时中文乱码
> 
> 这些问题和系统应该没什么关系吧,我是windows且支持中文字体

This issue has been fixed. Please update the source code and run it again.

 If you still encounter problems, feel free to contact me.

**Comment by threerog** [comment]
中文已经正常支持了
我无意间尝试数值型标签时工具启动报错,我记得之前有人反馈过关于数值标签异常的问题
```
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\AnyLabeling\anylabeling\app.py", line 222, in <module>
    main()
  File "C:\Users\Admin\Desktop\AnyLabeling\anylabeling\app.py", line 202, in main
    win = MainWindow(
  File "C:\Users\Admin\Desktop\AnyLabeling\.\anylabeling\views\mainwindow.py", line 30, in __init__
    self.labeling_widget = LabelingWrapper(
  File "C:\Users\Admin\Desktop\AnyLabeling\.\anylabeling\views\labeling\label_wrapper.py", line 24, in __init__
    view = LabelingWidget(
  File "C:\Users\Admin\Desktop\AnyLabeling\.\anylabeling\views\labeling\label_widget.py", line 134, in __init__
    self.label_dialog = LabelDialog(
  File "C:\Users\Admin\Desktop\AnyLabeling\.\anylabeling\views\labeling\widgets\label_dialog.py", line 134, in __init__
    self.label_list.addItems(labels)
TypeError: index 2 has type 'int' but 'str' is expected
```

不好意思,我可能有点多事

**Comment by CVHub520** [comment]
Hello, for label with numeric values as the first command, please add quotes around them, as shown below:

```
...
labels:
- car
- '1'
- 苹果
- _phone
```

Thank you for your feedback and suggestions. 

If you have any further questions or need assistance, feel free to reach out again.

Cheers.

**Comment by threerog** [comment]
太棒了
