### ISSUE TITLE
【BUG】空标注会自动继承上一张图片的标注

### ISSUE THREAD

**Issue by kbaicai** [CVHub520/X-AnyLabeling#170]
复现步骤
1.我们在列表中某一个图片（假设是image_03），原来有标注，但是后面又清空了标注（生成了json文件，但是shape数组为空）
2.再检查的时候，从image_02跳到image_03的话，image_03会自动继承image_02的标注，并且写入json文件

**Comment by CVHub520** [comment]
Hello, @kbaicai, thank you for your feedback. 

This is not a bug but a feature where you have enabled the option to automatically inherit labels from the previous frame. You can disable this option to prevent automatic inheritance. 

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/54fd126d-5d5f-4a9a-bd12-11414b0ce406)

Also, I strongly recommend running from the source code as the GUI version is outdated and lacks many new features. A new version is expected to be released later this week, so please stay tuned for updates.

**Comment by kbaicai** [comment]
got it, thanks a lot

**Comment by CVHub520** [comment]
> got it, thanks a lot

You're welcome.
