### ISSUE TITLE
删除文件后，文件列表会重新加载，并定位到第一张图

### ISSUE THREAD

**Issue by huangye123** [CVHub520/X-AnyLabeling#171]
删除后重新定位到第一张图，需要回之前标定的图片顺序就比较麻烦。
![image](https://github.com/CVHub520/X-AnyLabeling/assets/28778519/c8fef2cd-e70d-4e4b-a57d-ae98df152f41)

建议：删除并重新加载时，定位自动切到下一张，而非第一张，这样比较友好一些。

**Comment by CVHub520** [comment]
@huangye123, Hi, the delete image operation itself is not intended to be a frequent action. It's suggested to use a "discard" label for marking images that can be removed later after completing all tasks. This way, you can avoid frequent deletions during the labeling process.

Additionally, considering that the GUI version you are using is quite outdated, I strongly recommend running from the source code to experience the latest features and improved stability.
