### ISSUE TITLE
windows打包錯誤

### ISSUE THREAD

**Issue by ss880426** [CVHub520/X-AnyLabeling#172]
打包cpu版本出現的錯誤請問該如何解決?
ValueError: Unsupported icon subimage format (rebuild PIL with JPEG 2000 support to fix this)

**Comment by CVHub520** [comment]
Hi, @ss880426, try to update the PIL package via `pip install --upgrade pillow`;

And, If the format used for the icon is JPEG 2000, consider changing it to a supported format, such as PNG.

**Comment by ss880426** [comment]
update後可以打包了
但是運行執行檔後會出現
importerror: error: recursion is detected during loading of "cv2" binary extensions. check opencv installation.

**Comment by CVHub520** [comment]
Before attempting to package and compile, make sure that all required dependencies are correctly installed.

**Comment by ss880426** [comment]
我有確認過有安裝了
