### ISSUE TITLE
导入标签软件卡死退出 

### ISSUE THREAD

**Issue by lonngxiang** [CVHub520/X-AnyLabeling#174]
导入标签软件卡死退出 ，多次测试一样；
导入yolo格式：https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/classes.txt

**Comment by lonngxiang** [comment]
用的windows cpu版本

**Comment by CVHub520** [comment]
> 用的windows cpu版本

Hello, @lonngxiang, thanks for your input. Could you please share the detailed error message with me so that I can pinpoint the issue?

**Comment by lonngxiang** [comment]
> > 用的windows cpu版本
> 
> Hello, @lonngxiang, thanks for your input. Could you please share the detailed error message with me so that I can pinpoint the issue?

下载的最新版本，打开软件，点击导入选项，然后导入txt标签文本，软件菜单就显示灰色没法操作，然后就卡死退出了
![image](https://github.com/CVHub520/X-AnyLabeling/assets/40717349/20fcc478-91e3-480e-9e73-e88a639984ea)

**Comment by lonngxiang** [comment]
li另外txt是中文label
![image](https://github.com/CVHub520/X-AnyLabeling/assets/40717349/9608a0cf-378b-47ce-8e59-7fad24b500ca)

**Comment by CVHub520** [comment]
Note that:
- Before you click the  `Upload` button, please loading the annotated images first;
- please remember choose your yolo labels folder after upload the classes.txt;

If you can confirm that the above steps are correct, please compress your sample images, YOLO label files, and the classes.txt file into a zip archive and send it to cv_hub@163.com.
