### ISSUE TITLE
这是否是一个前后端分离的项目？

### ISSUE THREAD

**Issue by jaffe-fly** [CVHub520/X-AnyLabeling#175]
我是否可以只启动后端接口使用？我看带service 中的代码里面依然后pyqt 的使用？我应该如何只是用自动标注的后端接口？

**Comment by CVHub520** [comment]
Hello, @jaffe-fly:

Currently, the X-AnyLabeling tool doesn't separate the auto-labeling interface as an independent module. 

However, you can extract the interface on your own by isolating the PyQt-related interactions. For specific examples, you can refer to this [example](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/export_grounding_dino_onnx.py).
