### ISSUE TITLE
旋转框标注的时候，画框是没有角度的，如何画出带角度的框

### ISSUE THREAD

**Issue by simplewy** [CVHub520/X-AnyLabeling#176]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/119155382/1190deb2-96eb-4a91-8722-4b5b86b75e77)

**Comment by CVHub520** [comment]
Hi, @simplewy, you can refer this [toturial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md).

**Comment by simplewy** [comment]
谢谢  看到文档了
