### ISSUE TITLE
导出mask时，如果一个标签有多处标注，只能导出一处

### ISSUE THREAD

**Issue by miaojun22** [CVHub520/X-AnyLabeling#177]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/103490833/6f5dbba4-56d0-478e-84c7-627a532c8c40)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/103490833/031ca7d9-09a0-4251-9be0-599b8445296c)
如图，在原图上residual标签有两处标注，导出mask后只有png上只有一处residual标签。

这是我用的颜色映射表文件：
[mask_color_map.json](https://github.com/CVHub520/X-AnyLabeling/files/13782676/mask_color_map.json)

**Comment by CVHub520** [comment]
Hi, @miaojun22,
Thank you for your feedback! The issue has been resolved. Your input is greatly appreciated. 

Feel free to reach out if you have any more suggestions or questions. 

Best regards,
CVHub
