### ISSUE TITLE
Export label to Yolo Throw Error

### ISSUE THREAD

**Issue by airylinus** [CVHub520/X-AnyLabeling#179]
`  File "d:\dataset\X-AnyLabeling-main\tools\label_converter.py", line 1056, in <module>
    main()
  File "d:\dataset\X-AnyLabeling-main\tools\label_converter.py", line 981, in main
    converter.custom_to_yolov5(src_file, dst_file)
  File "d:\dataset\X-AnyLabeling-main\tools\label_converter.py", line 237, in custom_to_yolov5
    x_center = (points[0][0] + points[2][0]) / (2 * image_width)`

Expect:
    success with correct result files

**Comment by CVHub520** [comment]
Hello, @airylinus

The latest X-AnyLabeling version, v2.2.0, now supports one-click export of labels in YOLO format. I highly recommend upgrading to the latest version or pulling the latest source code for the best experience. You can refer to the documentation ([en](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md) | [zh_CN](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md)) for usage instructions.

**Comment by jimmy123j** [comment]
Export Data always fail and show not inline
![2023-12-31 16 00 15](https://github.com/CVHub520/X-AnyLabeling/assets/46530155/c88dc8a9-42c7-4b76-8884-4370a3442a33)

**Comment by CVHub520** [comment]
Hi, @jimmy123j, consider incorporating the term 'Bump' into your custom classes.txt file before exporting the YOLO labels.

**Comment by jimmy123j** [comment]
> Hi, @jimmy123j, consider incorporating the term 'Bump' into your custom classes.txt file before exporting the YOLO labels.

Thanks for reply, does any classes.txt sample for newbie
and may export be auto create classes.txt will be friendly for newbie

**Comment by CVHub520** [comment]
Hello, you are absolutely right. I understand why an automated classes.txt creation could be a thoughtful tool for beginners. However, the creation of a custom category file is inherently a user's initiative activity. It is virtually impossible to automate this because what categories each user needs can only be known beforehand by the user themselves. 

I would recommend you to refer to a particular [tutorial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md) for a concrete example of how to manually create a classes.txt file. 

Please let me know if you require further assistance or have any other queries.

Best regards.

**Comment by CVHub520** [comment]
Due to inactivity, this issue is temporarily closed. Feel free to reopen for further assistance or new issues.

**Comment by bjovc** [comment]
Hi,

I am trying to export my annotations with the YOLO format. For the labelling process I used YOLOV8x-Seg Ultralitycs, and so I prepared the classes.txt file by loading the model, printing its classes and copying them. 

However, when I try to export the labels with YOLO format, after 200-700 images it shows me the following error:
operands could not be broadcast together with shapes (0,) (1,2)

My classes.txt file is almost identical to the one shared [here](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/classes.txt#L52), changing only the spelling of some of them. 

Thank you in advance for your help.

**Comment by CVHub520** [comment]
> Hi,
> 
> I am trying to export my annotations with the YOLO format. For the labelling process I used YOLOV8x-Seg Ultralitycs, and so I prepared the classes.txt file by loading the model, printing its classes and copying them.
> 
> However, when I try to export the labels with YOLO format, after 200-700 images it shows me the following error: operands could not be broadcast together with shapes (0,) (1,2)
> 
> My classes.txt file is almost identical to the one shared [here](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/classes.txt#L52), changing only the spelling of some of them.
> 
> Thank you in advance for your help.

Hi, @airylinus; thank you  for your feedback! To further find the issue you have encounted, please check the label file with *.json format first; you can observe that waht the difference between the 200-700 image's label and the others.

If you have any other question, please don't hesitate to concat me.

**Comment by bjovc** [comment]
I have looked into the issue and it seems that it only happens when the area of an annotation is very small or two annotations overlap. I fixed the problematic frames by hand in the end.
