### ISSUE TITLE
使用后的效果问题

### ISSUE THREAD

**Issue by BOOSTMKII** [CVHub520/X-AnyLabeling#18]
<img width="1280" alt="屏幕截图 2023-06-20 225310" src="https://github.com/CVHub520/X-AnyLabeling/assets/34444796/2fec8761-2bbe-48ce-9c3a-fb44c3056408">
<img width="1280" alt="屏幕截图 2023-06-20 223646" src="https://github.com/CVHub520/X-AnyLabeling/assets/34444796/c403fe3c-e17e-4d8a-94d0-eb65dc46340d">
为什么使用蔬菜图片效果很不错，但分析我自己的图片时，完全无法分割出任何物体呢？是模型加载问题还是图片问题

**Comment by BOOSTMKII** [comment]
图片分辨率太高了。

**Comment by aiyou9** [comment]
> 图片分辨率太高了。

图片长宽比，有没有影响？

**Comment by BOOSTMKII** [comment]
> > 图片分辨率太高了。
> 
> 图片长宽比，有没有影响？

我觉得没有。
