### ISSUE TITLE
[Enhancement] Duplicate Polygons without offset

### ISSUE THREAD

**Issue by SuhaibAlHindi** [CVHub520/X-AnyLabeling#180]
I just hate having to reset the positions of the detections after I duplicate them, I wish if there is an option to just not move the detections.

I know where the line that requires modification: 
  
In 
X-AnyLabeling/anylabeling/views/labeling/widgets/canvas.py
Line 914 

![image](https://github.com/CVHub520/X-AnyLabeling/assets/138457261/290d2373-6e71-41ef-993a-34627dfcce28)

**Comment by CVHub520** [comment]
Hi, @SuhaibAlHindi, thank you for your feedback. Your input is highly valued and plays a crucial role in refining our processes. If you have any further suggestions, questions, or concerns, please don't hesitate to share them with us. 
We appreciate your engagement and look forward to continually improving our services based on your valuable insights.
