### ISSUE TITLE
2.2版本视频文件无法打开进行标注

### ISSUE THREAD

**Issue by daka935** [CVHub520/X-AnyLabeling#182]
2.2版本视频文件无法打开进行标注

**Comment by CVHub520** [comment]
Hi, @daka935:
You can try running the source code to troubleshoot the specific cause of the error. 

Alternatively, if it's convenient, you can send the video source files to the email address cv_hub@163.com, and we will take a look when time permits.

Best regard,
CVHub

**Comment by CVHub520** [comment]
Due to inactivity, this issue is temporarily closed. Feel free to reopen for further assistance or new issues.

**Comment by 202112213501021** [comment]
> 嗨，：您可以尝试运行源代码来排除错误的具体原因。
> 
> 或者，如果方便，您可以将视频源文件发送到 [cv_hub@163.com](mailto:cv_hub@163.com) 电子邮件地址，我们会在时间允许时查看。
> 
> 最好的问候，CVHub

您好，我也是这个问题，我用的是你们的视频，也打不开

**Comment by CVHub520** [comment]
> > 嗨，：您可以尝试运行源代码来排除错误的具体原因。
> > 或者，如果方便，您可以将视频源文件发送到 [cv_hub@163.com](mailto:cv_hub@163.com) 电子邮件地址，我们会在时间允许时查看。
> > 最好的问候，CVHub
> 
> 您好，我也是这个问题，我用的是你们的视频，也打不开

1. 检查下文件名或文件路径是否含有中文字符；
2. 更新到最新版本尝试。
