### ISSUE TITLE
Error in predict_shapes: axes don't match array

### ISSUE THREAD

**Issue by MinhThanghus** [CVHub520/X-AnyLabeling#183]
Thank you for the source code
I create model yolov5 segmentation
But encountered the following error when embedding it in the model:
Error in predict_shapes: axes don't match array
Do you know any way to solve it?
Thank you very much

**Comment by CVHub520** [comment]
Hello, @MinhThanghus:

Thank you for providing the information. With regards to your query, could you please specify whether you are using a locally customized model or one provided by X-AnyLabeling for inference?

If it is a customized model, you might want to use the [netron](https://netron.app/) tool to compare the consistency of the input and output nodes. At the same time, please ensure that the parameters in the configuration file are correctly configured.

Looking forward to your reply to provide a more accurate solution.

Best regards.

**Comment by CVHub520** [comment]
Due to inactivity, this issue is temporarily closed. Feel free to reopen for further assistance or new issues.

**Comment by CColdMoon** [comment]
Hello，@CVHub520 
I used a custom model, and when performing segmentation processing, some images can be recognized, but some images will prompt "Error in predict_shapes: axes don't match array". What is the reason for this? According to online research, I thought it was a problem with RGB images that were not 3-channel, but after converting the images, it still doesn't work. The version I am using is X-AnyLabelling-2.2.0
![1](https://github.com/CVHub520/X-AnyLabeling/assets/144866753/0f741a77-ebd8-4358-b87c-c1b89f0f6422)
![2](https://github.com/CVHub520/X-AnyLabeling/assets/144866753/ec92a5e4-f1fe-4940-8588-8f1e80027017)
![3](https://github.com/CVHub520/X-AnyLabeling/assets/144866753/1ea3f92d-59ff-4b8d-8703-075e23a9c81a)

**Comment by CVHub520** [comment]
> xes don't match array

Hi, thank you for providing valuable feedback. If it's convenient for you, could you please package a zip file containing your custom model, configuration YAML, and the images with errors mentioned above? Kindly send the zip file to the email address: cv_hub@163.com. Thank you!

**Comment by yimengweima0** [comment]
我使用的 X-AnyLabelling-2.3.0，使用默认的YOLOV8x-seg在自动标注也出现了同样的错误，请问你解决了吗

**Comment by yimengweima0** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/50518889/4cdec5cb-b3df-403b-a87b-ebaf4bf64b2b)
当我自动标注到这张就报错了

**Comment by yimengweima0** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/50518889/b72f86de-e02f-4464-be79-93417c865591)

**Comment by CColdMoon** [comment]
> 我使用的 X-AnyLabelling-2.3.0，使用默认的YOLOV8x-seg在自动标注也出现了同样的错误，请问你解决了吗

The author said it has been resolved and will be updated later.

**Comment by yimengweima0** [comment]
> > 我使用的 X-AnyLabelling-2.3.0，使用默认的YOLOV8x-seg在自动标注也出现了同样的错误，请问你解决了吗
> 
> The author said it has been resolved and will be updated later.
Thank you very much！

**Comment by yimengweima0** [comment]
Thank you very much！

**Comment by CVHub520** [comment]
@yimengweima0 @CColdMoon @MinhThanghus 
This issue has been fixed. Please update to the latest source code and try to it again.

**Comment by yimengweima0** [comment]
仍然会遇到问题，(label) lwh@lwh ~/G314/label/X-AnyLabeling$ python anylabeling/app.py 
Gtk-Message: 10:32:14.501: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 10:32:25.349: GtkDialog mapped without a transient parent. This is discouraged.
/home/lwh/G314/label/X-AnyLabeling/./anylabeling/services/auto_labeling/utils/points_conversion.py:481: RuntimeWarning: invalid value encountered in cast
  for x in masks.astype("uint8"):
段错误 (核心已转储)

**Comment by yimengweima0** [comment]
自动标注到一张图片，这种情况也会闪退：
(label) lwh@lwh ~/G314/label/X-AnyLabeling$ python anylabeling/app.py 
Gtk-Message: 10:34:29.449: GtkDialog mapped without a transient parent. This is discouraged.
段错误 (核心已转储)

**Comment by CVHub520** [comment]
Hi, @yimengweima0 , thank you for providing valuable feedback. If it's convenient for you, could you please package a zip file containing your custom model, configuration YAML, and the images with errors mentioned above? Kindly send the zip file to the email address: [cv_hub@163.com](mailto:cv_hub@163.com). Thank you!

**Comment by MinhThanghus** [comment]
@CVHub520 
Thank you very much, thank you for your support
🙇
