### ISSUE TITLE
Automate annotation is taking time 

### ISSUE THREAD

**Issue by lenka-79** [CVHub520/X-AnyLabeling#184]
Hi,

we are using xanylableing tool for Pedestrian annotation, facing some challenges 

1)   trying to annotate one video (around 1800 frames/images) which is having Pedestrian's  as an objects  

while using Auto labeling in tool like 

![image](https://github.com/CVHub520/X-AnyLabeling/assets/152685134/9a5f84d4-d904-4d37-9f4b-93117c4d6513)
 
I am able to get the annotated yolo.txt output but it is taking around 2 to 3 hours to complete one video record which is having 1800 frames around.

I think, complete thing is running on GPU as per my understanding 

![image](https://github.com/CVHub520/X-AnyLabeling/assets/152685134/92d8c84c-08a2-4691-9724-b74120c84497)

Is this taking that much time to finish the auto labeling? or did I miss any thing here, please let me know..

Thanks,
Giri.

**Comment by CVHub520** [comment]
Hello Giri,

From the information you've provided, it does seem like the tool is not utilizing the GPU, which could be causing the long execution time for video annotations. Normally, operations involving large amounts of frame like this should see speed benefits when run on a GPU.

I would recommend running the X-AnyLabeling tool from the source while ensuring that all the necessary dependencies for GPU usage are properly installed as per the version requirements. 

However, it is generally a good practice to always look through the installation instructions or [documentation](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/get_started.md) provided by the tool's official source, as they usually include steps specifically for enabling GPU support.

But please be aware that the time it takes can also depend on the complexity and amount of data being processed, as well as the capabilities of your hardware.

Let me know if you need more help or if there are other questions.

Best regards.
