### ISSUE TITLE
Unable to generate annotated output yolo.txt files with new xanylabeling tool/release version  

### ISSUE THREAD

**Issue by lenka-79** [CVHub520/X-AnyLabeling#185]
Hi,

we are able to generate annotated yolo.txt files using xanylabeling tool with previous version(fews week back),
but now we downloads new xanylableing packages from gitrepo & verify it for the same, unable to get the yolo.txt files.

upload/export options are available in new tool/version, but unable to get/generate the yolo.txt file even though we load proper class.txt file & we are getting proper *.json files in the corresponding path. 

bcs same thing we done it with previous version tool, we are able to generate it.   
 
plz let me know if miss any here..

Thanks,
Giri.

**Comment by CVHub520** [comment]
Hello Giri,

Thanks for reaching out. It seems like there may have been changes in the latest version of the X-AnyLabeling tool that you downloaded from the Git repository. The manner of exporting settings might differ in the newer version from the older one. Here is a simplified process for you:

1. Make sure you've properly annotated the current task and verified it
2. Prepare a classes.txt file that the tool can use as reference
3. Click on the 'Export->Export YOLO Annotations' button to generate the files.

You should be able to export at any time without needing to set the mode beforehand. Also, the same thing applies to other types of export settings, and you should see the yolo.txt file in the same path as the *.json files. For more detail, you can refer to this [toturial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md).

If you're still facing issues, please provide additional information about the steps you're following and any error messages you're seeing.

Best regards.
