### ISSUE TITLE
work with custom yolov8-seg and sam

### ISSUE THREAD

**Issue by gbo999** [CVHub520/X-AnyLabeling#187]
hey there, 

i want to work with custom yolov8-seg model that i already trained, and to work with pointing segemnetation like sam.

how can i achieve that?

**Comment by CVHub520** [comment]
Hello, @gbo999:
Deploying a custom model requires specific steps, generally, here's a [toturial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/custom_model.md) you can refer that.
