### ISSUE TITLE
最新win10X-AnyLabeling-GPU软件闪退

### ISSUE THREAD

**Issue by hanlei96** [CVHub520/X-AnyLabeling#188]
下载了最新版本的windows的X-AnyLabeling-GPU.exe，打开后加载yolov8的pose模型，加载结束后软件闪退

**Comment by CVHub520** [comment]
Hello, @hanlei96:

It sounds like the issue you're experiencing with X-AnyLabeling tool crashing after loading the yolov8 pose model may have to do with a mismatch between your current CUDA environment and the version the software was compiled with.

I strongly recommend running it using the source code. If you need to use the compiled version, you can also compile it based on your hardware environment. For details, please refer to the [help guide](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs/zh_cn) on GitHub.

If these steps do not resolve your issue, please provide more information, and I will endeavor to assist you further.

Best Regards.
