### ISSUE TITLE
YOLOv8模型推理无结果，YOLOv5结果正常，都是默认模型

### ISSUE THREAD

**Issue by xuxinda** [CVHub520/X-AnyLabeling#19]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/37835128/f505cd0d-f392-4dda-ab31-70b184e7b868)

**Comment by CVHub520** [comment]
您好，可以将你的配置文件和模型权重打包发上来看看。

**Comment by xuxinda** [comment]
用的是默认选项里自动下载的yolov8模型

**Comment by alfheim1993** [comment]
我用了release cpu最新版，一样的问题，自动下载的yolov5可以正常自动标注，自动下载的yolov8的所有模型都无法正常标注，但是yolov8的分割模型又是正常的，所以这应该是软件bug

**Comment by CVHub520** [comment]
@xuxinda @alfheim1993 问题已修复，从直接从
![主页](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/a8120dc1-ddb5-4233-a6c1-120714c975d1)下载。

**Comment by CVHub520** [comment]
@xuxinda @alfheim1993 问题已修复，请直接从主页 `README.md` 下载。

**Comment by alfheim1993** [comment]
好的，非常感谢

> @xuxinda @alfheim1993 问题已修复，请直接从主页 `README.md` 下载。

**Comment by xuxinda** [comment]
> @xuxinda @alfheim1993 问题已修复，请直接从主页 `README.md` 下载。

非常感谢
