### ISSUE TITLE
导出功能支持关键点标注数据coco/yolo格式导出么？

### ISSUE THREAD

**Issue by Syorst** [CVHub520/X-AnyLabeling#190]
支持导出coco/yolo格式关键点标注数据么？

**Comment by CVHub520** [comment]
Hi, @Syorst:

Currently, our export functionality does not support the export of keypoint annotation data in the COCO/YOLO format. 

Nevertheless, your suggestion is indeed vital and is recognized. If you have some ownership and feel enthusiastic about it, you are most welcome to submit a Pull Request (PR) on GitHub to address this feature. Your contribution would be greatly beneficial for the entire user community.

If you need detailed instructions or assistance regarding the submission of a PR, please let me know. I am always here to help.

Best regards.
