### ISSUE TITLE
导出mask标签没有输出

### ISSUE THREAD

**Issue by zl2048** [CVHub520/X-AnyLabeling#193]
我标注好一张图片，点击导出-导出mask标签，并选择了格式正确的color table文件，软件弹出“annotation exported successfully! Check the results in: XXX"，但那个文件夹里并没有输出的mask图片，这是为什么？我已经尝试过目录中不包含中文。
使用release 2.2.0的win CPU和linux CPU的可执行文件直接运行，都存在这个问题

**Comment by CVHub520** [comment]
Hello @zl2048:

May I ask if you have drawn any Polygon objects on your image? The mask export feature of the software works by generating a mask based on the Polygon objects present in the image.

Please make sure you have properly drawn and labeled Polygon objects on your image before attempting to export masks.

If you have done this and the issue still persists, do let us know so we can assist you further. 

Best regards.

**Comment by zl2048** [comment]
Yes, the problem is indeed due to that I haven't drawn any polygon objects, but only rectangles. The issue is solved. Thank you very much.

**Comment by zl2048** [comment]
The problem is solved
