### ISSUE TITLE
x-anylabeling在win电脑和Mac电脑都会报以下错误

### ISSUE THREAD

**Issue by jiaxueying1997** [CVHub520/X-AnyLabeling#194]
![图像2024-1-10 15 06](https://github.com/CVHub520/X-AnyLabeling/assets/64617891/974d8849-d239-4eb3-8555-0e5af5e503bf)
导入模型正常，但是没办法出来检测框，使用官方自带的yolov5模型，标记两个后，软件出现闪退现象。

**Comment by CVHub520** [comment]
Hello, @jiaxueying1997:

We appreciate your patience and sincerely apologize for the inconvenience you're experiencing. We would recommend updating the software you are currently using. A new version has been released, with improvements and bug fixes that might solve the issue you are experiencing. 

In case you continue to face any challenges or if you have any further queries, don't hesitate to reach out to us again.

Best regards.

**Comment by jiaxueying1997** [comment]
Thank you for your reply
