### ISSUE TITLE
Same mark will be automatically saved in next image while creating any new mark 

### ISSUE THREAD

**Issue by tttoddyang** [CVHub520/X-AnyLabeling#196]
Open Images folder->press shortcut "R" or others to create any new mark->press D to next image, then the same size and name mark will be automatically saved in the next image.

**Comment by CVHub520** [comment]
Hello,

From your description, it seems like the "Auto Use Last Label" option in the settings may be turned on. This option will automatically copy and save tags from the current image to the next image when you navigate to it. 

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/77113044-74f0-4bed-869e-a33304cc723c)

To resolve this issue, you can simply go to Settings and turn off or uncheck this option manually, or press `Ctrl+Y` directly.

Please let us know if you need further assistance.

Best regards.
