### ISSUE TITLE
ValueError: cannot find shape: <anylabeling.views.labeling.shape.Shape object at 0x7fbb12a88bb0>

### ISSUE THREAD

**Issue by Abdulhadiasa** [CVHub520/X-AnyLabeling#197]
while labeling previously labelled segmentation files using YOLO format, the following error pops up after a crash
```
Traceback (most recent call last):
  File "/home/abed/Documents/label-tools/X-AnyLabeling/./anylabeling/views/labeling/label_widget.py", line 1978, in shape_selection_changed
    item = self.label_list.find_item_by_shape(shape)
  File "/home/abed/Documents/label-tools/X-AnyLabeling/./anylabeling/views/labeling/widgets/label_list_widget.py", line 181, in find_item_by_shape
    raise ValueError(f"cannot find shape: {shape}")
ValueError: cannot find shape: <anylabeling.views.labeling.shape.Shape object at 0x7fbb12a88bb0>
Aborted (core dumped)
```
it works for a while and after the same image that it crashes on, it works fine.

**PS:** when I reload the YOLO labels, previously edited labels (auto-saved as JSON) is overwritten when uploading the YOLO files again, auto export could help not lose labels after a crash.

**Comment by CVHub520** [comment]
Hello, @Abdulhadiasa

I'm sorry to hear that you're experiencing issues with the tool. From what you've described, it seems like the program crashes when trying to load certain images that were previously labeled. This should not be happening regularly and we'll need more information to resolve the issue.

However, we would appreciate it if you could provide us with more details about these issues, perhaps with specific examples or a more detailed explanation of the steps leading to the issues. This will greatly enhance our ability to find a resolution.

We appreciate your cooperation and patience.

Cheers.

**Comment by CVHub520** [comment]
Thanks for expanding on your problem. I see now that the error occurs when you zoom in after working with labels. It's noteworthy that upon reloading, you can manipulate labels on the same image without issue. I'm sorry to hear that this has been a hindrance in your work.
Please continue to keep us informed if the problem persists or if you encounter any other difficulties. I'm here to support you.

**Comment by mogazheng** [comment]
same here

**Comment by CVHub520** [comment]
> same here

@mogazheng, Hi, when you are carrying out a labeling task, the corresponding label file is automatically saved in the current directory (unless you've set a save path). 

Hence; even if a crash occurs for some reason, all you need to do is reload the dataset without needing to overwrite it by uploading YOLO or other format files. After the whole dataset is labeled, you can then export it in your required format at any time.

Best regards.
