### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by bjovc** [CVHub520/X-AnyLabeling#199]
Hello,

I am trying to use X-AnyLabelling for labelling a couple of videos with YOLOv8-Seg Ultralytics. However, the app keeps crashing after what seems like encountering a frame with no detections (even if it worked just fine with no detection frames from the same video before). This has happened both when running the model with the button 'Run' by hand and when using 'Auto run all images at once'.

I am running the program via source code. Usually I get the following output, although sometimes it doesn´t say anything about axes.

$ python3 anylabeling/app.py 
Error in predict_shapes: axes don't match array
Segmentation fault (core dumped)

I would appreciate some help to understand what's causing the error.

**Comment by CVHub520** [comment]
Hello, @bjovc:

I'm sorry to hear that you're encountering issues with X-AnyLabelling when labeling your videos with YOLOv8-Seg Ultralytics. 

Please verify the correctness of your ONNX model transformation. To do this, you could use the [Netron](https://netron.app/) tool to compare your model's input and output nodes with those of the built-in model.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/2c5ce318-0da4-409b-b901-4c0166c28e59)


Please don't hesitate to reach out if you need more assistance or if you have further questions.

Best regards,
CVHub

**Comment by bjovc** [comment]
The model I am using is the YOLOv8x-Seg Ultralytics provided by the application. I have verified it with Netron and there are no differences with the image you provided. 

I have now succesfully processed the video by skipping some of the problematic frames, but I would still like to understand the problem.

Thanks!
