### ISSUE TITLE
多目标跟踪

### ISSUE THREAD

**Issue by xiangyangaa** [CVHub520/X-AnyLabeling#2]
可以自动标注多目标跟踪MOT格式的数据集吗？

**Comment by CVHub520** [comment]
> 可以自动标注多目标跟踪MOT格式的数据集吗？

有点工作量，需求大的话后期可以支持，可尝试下 Track-Anything 这类型的 demo 先。

**Comment by xiangyangaa** [comment]
我觉得需求还是比较大的，因为如果要做多目标跟踪的话，标注的工作量比检测大的多。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月08日 17:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [CVHub520/X-AnyLabeling] 多目标跟踪 (Issue #2) |

可以自动标注多目标跟踪MOT格式的数据集吗？

有点工作量，需求大的话后期可以支持，可尝试下 Track-Anything 这类型的 demo 先。

**Comment by aiyou9** [comment]
Segment Anything(sam)项目整理汇总（持续更新…）https://zhuanlan.zhihu.com/p/630529550   里面有收集一些做目标追踪的项目

**Comment by CVHub520** [comment]
@xiangyangaa ，您好，多目标跟踪已支持，欢迎尝试。

**Comment by jiyuwangbupt** [comment]
> @xiangyangaa ，您好，多目标跟踪已支持，欢迎尝试。

您好，请问多目标跟踪怎么导入和导出，我这边失败了。使用yolov5——bytetrack进行标注的。点击导入属性文件报错直接闪退了。
![image](https://github.com/CVHub520/X-AnyLabeling/assets/37127150/e514d101-1948-452f-bfe1-82574730190f)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/37127150/3e320ce1-6abe-4da2-862b-ce2d63854972)
