### ISSUE TITLE
下载.exe版本如何指定conda环境？

### ISSUE THREAD

**Issue by Beforcer** [CVHub520/X-AnyLabeling#20]
下载的exe文件可以运行，但是加载模型的时候无法指定自己的conda环境，软件中没有看到能够指定环境的选项，除非用源码编译

**Comment by CVHub520** [comment]
您好，可执行文件就是直接运行的，无须指定conda环境。如果你的下载gpu版本的可执行文件，由于编译的时候这边是使用 onnxruntime-v1.14.0版本，需要安装指定版本的cuda环境才能正常调用显存资源，具体可参考此[链接](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html)，cpu无影响。
