### ISSUE TITLE
【bug】开始标注时，如果取消了画框后填入标签信息，画的框不消失，还能在打开的其他图片中继续存在

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#200]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/40248afc-c927-4b30-87e0-602aae0e7163)

![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/1da3c0a2-8702-4716-82e1-2f743f571a0e)

![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/66ba6c7d-db92-477d-bb06-fd4afbe27cbb)

**Comment by CVHub520** [comment]
Hi, @aiyou9, sorry for the inconvenience caused. 

When you cancel the drawing box, you can press the 'R' key again to reset it. This should prevent the box from persisting in other images that you open.

If you have any further issues or questions, feel free to let me know.
