### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:x

### ISSUE THREAD

**Issue by biyuefeng** [CVHub520/X-AnyLabeling#201]
我在微调SAM后，用新的模型转为了onnx，然后使用X-anylabeling时，出现上述错误，并闪退。请问是什么原因呢？谢谢。

**Comment by CVHub520** [comment]
Hello,

I'm sorry to hear that you are having this issue. It appears there's an issue with the ONNX model you've created after fine-tuning SAM.

Consider that, for efficiency, X-AnyLabeling operates by separating the processes of encoding and decoding. You need to divide your model into an Encoder and a Decoder, and make sure their input and output nodes align with the built-in models (you could use the Netron tool to verify this).

For more detailed guidance, please refer to this [tutorial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md).

If you have additional questions or challenges, please don't hesitate to ask for help.

Best regards.

**Comment by biyuefeng** [comment]
您好，我就是按照官方链接导出的encoder和decoder（https://github.com/vietanhdev/samexporter#sam-exporter）。
我在上述链接导出encoder和decoder后，在samexporter中，是可以利用导出的encoder和decoder进行推理的。


但是，在X-AnyLabeling中就会出现闪退的情况，报错如下：



期待您的回复，谢谢！


人生海海海布里
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CVHub520/X-AnyLabeling"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月12日(星期五) 上午9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CVHub520/X-AnyLabeling] onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:x (Issue #201)





 
Hello,
 
I'm sorry to hear that you are having this issue. It appears there's an issue with the ONNX model you've created after fine-tuning SAM.
 
Consider that, for efficiency, X-AnyLabeling operates by separating the processes of encoding and decoding. You need to divide your model into an Encoder and a Decoder, and make sure their input and output nodes align with the built-in models (you could use the Netron tool to verify this).
 
For more detailed guidance, please refer to this tutorial.
 
If you have additional questions or challenges, please don't hesitate to ask for help.
 
Best regards.

**Comment by CVHub520** [comment]
Hi, i'm sorry to about to hear that.

If the issue is still encounted, please zip your model weight and corresponding config yaml file and a test image, send them to the email address: [cv_hub@163.com](mailto:cv_hub@163.com). 

This way, I can further investigate the issue for you.

**Comment by CVHub520** [comment]
Hi, @biyuefeng:

Thank you for your cooperation. I utilized the config file and weight file you provided and everything appears to be functioning properly on my end. 

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/1f930c42-ff26-4999-b738-bd2aa885df50)

I would suggest you update the source code and try running it from the source. You could initially use CPU for inference to ensure that the whole process is executable. 

If the problem persists or you need further assistance, please don't hesitate to ask.

Good luck!
