### ISSUE TITLE
导出为YOLO格式后.txt文件内容空白

### ISSUE THREAD

**Issue by Jielu-ee** [CVHub520/X-AnyLabeling#202]
<img width="855" alt="3894da47aaa02f2e2959fe97bd8c6fa" src="https://github.com/CVHub520/X-AnyLabeling/assets/108175520/eb4f74aa-4e6f-48c1-9aa0-23f45094d741">
<img width="479" alt="6ba0f9adc2bbed015657e119c63c743" src="https://github.com/CVHub520/X-AnyLabeling/assets/108175520/888d6fa7-1751-4316-bb3f-cf6216c60e74">

**Comment by CVHub520** [comment]
Hello,

Sorry to hear about the issue you're experiencing. Please ensure your labelled objects are of `Rectangle` and `Polygon` types, as these are the compatible formats. 

If they already are, you might want to zip your images, label files, and corresponding classes.txt file, and send them to the specified email address: cv_hub@163.com. This way, I can further investigate the issue for you.

If you have any additional questions or need further assistance, feel free to let me know.

Best regards.

**Comment by CVHub520** [comment]
Hello,

I've received the data you sent. As I mentioned earlier, the current X-AnyLabeling tool only supports `rectangle` and `polygon` objects (corresponding to detection and segmentation tasks, respectively). 

However, from the label file you provided, it appears that you are using the `linestride` object. This is not a valid conversion-supported type. If you are currently working on a semantic segmentation task, I suggest you set it to the `polygon` type and then proceed with the export settings.

**Comment by CVHub520** [comment]
BTW, you can view the overall statistics of the current task's annotations by using the shortcut key combination Ctrl+G.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/60b0b3ad-b263-4321-8a25-ea0ecf2c96dc)

**Comment by daysofchasingdream** [comment]
> BTW, you can view the overall statistics of the current task's annotations by using the shortcut key combination Ctrl+G.
> 
> ![image](https://private-user-images.githubusercontent.com/72010077/296138658-60b0b3ad-b263-4321-8a25-ea0ecf2c96dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MjY0MzYsIm5iZiI6MTcxMzYyNjEzNiwicGF0aCI6Ii83MjAxMDA3Ny8yOTYxMzg2NTgtNjBiMGIzYWQtYjI2My00MzIxLThhMjUtZWEwZWNmMmM5NmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDE1MTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2Njk1ZTJjNTk3MjU2YTFhZGFmODUzNGRkYjc4ZjNkZDQwMTRkZWI1MzYwOGVkZWM1NTg4M2ZmMzgyOTA2NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5tssod6wEzBvbqdG95-QnE1mrUR6A-IpqI1m1nyOIlo)

您好，打扰您了，我也碰到了相同的问题，导出为YOLO格式的时候txt文件是空的，然后我重新检查了其中的框，是矩形框。想请问一下这个是什么原因导致的，谢谢您~
![image](https://github.com/CVHub520/X-AnyLabeling/assets/67813534/fc5aef50-84af-4f68-b2d4-673c1a3c7bc1)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/67813534/fb38a167-12f5-462e-98ae-9f9a1f9625dc)
