### ISSUE TITLE
5000images takes one hour at least.I expect TensorRT accelerate autolabel efficiency in the future.We need it autolabel faster and fasterthx

### ISSUE THREAD

**Issue by wcelll** [CVHub520/X-AnyLabeling#203]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/101629172/d199b216-01fd-42e7-bca5-8873591508e4)
Hello, dear CVHUB developer, I found that the current prediction delay based on onnxruntime-gpu is relatively high and the prediction speed is relatively slow. Can a TensorRT quantitatively accelerated version be developed in the future, which can improve the prediction speed. Now I have 5,000 images that need to be automatically annotated. My GPU is NVIDIA RTX4080. My current graphics memory overhead is less than 2GB. Is there any way to improve prediction efficiency and reduce the delay of model inference?
![image](https://github.com/CVHub520/X-AnyLabeling/assets/101629172/1ef1d158-1add-4131-9249-d9e78be22838)

**Comment by CVHub520** [comment]
Hello wcelll,

Thank you for your suggestion and feedback. The running speed depends on the size of your model and the time it takes for inference. 

Considering manpower development issues, I plan to support TensorRT acceleration in the future. If you are familiar with the deployment of TensorRT, you only need to replace the backend of ORT accordingly.

Also, note that we would be delighted if you can help contribute to the project with a pull request!

Best regards.

**Comment by CVHub520** [comment]
Hi @wcelll, 

I'm happy to inform you that we've already addressed this performance issue in our latest code branch. 

These improvements have significantly reduced the processing time, especially for large image batches like your 5000-image case.

You can try these improvements by pulling the latest code from our main branch. Let me know if you still experience any performance issues!
