### ISSUE TITLE
我的电脑缩放图片闪退

### ISSUE THREAD

**Issue by KarmaFire1** [CVHub520/X-AnyLabeling#206]
我在使用的时候不管是放大还是缩小 。有很大的几率崩溃，闪退。重新运行又可以操作一段时间。用不了10分钟100%就会闪退,崩溃。每次崩溃的点都是在缩放图片的时候。求大佬解决

**Comment by CVHub520** [comment]
Hi, Could you please provide specific error information to help identify the issue?

**Comment by KarmaFire1** [comment]
32G内存不够吗  只不过品牌是七彩虹的
