### ISSUE TITLE
请问后面会支持RTMDetObb模型吗

### ISSUE THREAD

**Issue by DingRizhi** [CVHub520/X-AnyLabeling#208]
看到最新版本已经支持RtmDet模型，非常感谢作者们的贡献！
不知后续是否会支持RtmDe-obb模型

**Comment by CVHub520** [comment]
Hello, @DingRizhi:

We do appreciate your acknowledgment. Rest assured, RTMDet-obb is considered to be added to the plan list. We also welcome Pull Requests. Please, don't hesitate to reach out if you need more help.

Best regards.
