### ISSUE TITLE
导出yolo标签报错

### ISSUE THREAD

**Issue by yimengweima0** [CVHub520/X-AnyLabeling#209]
导出yolo标签，一直提示类别不在list，这些类别都不是自己定义
![2024011601⁄16⁄24](https://github.com/CVHub520/X-AnyLabeling/assets/50518889/5af03549-06b4-4173-be79-2208d0df2eba)

**Comment by wgqhandsome** [comment]
你解决了这个问题了吗

**Comment by CVHub520** [comment]
Hi @wgqhandsome. This [docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#41-yolo%E6%A0%87%E7%AD%BE) can guide you on how to export YOLO annotations correctly.
