### ISSUE TITLE
自动标注，下载模型过程中闪退

### ISSUE THREAD

**Issue by Chenastron** [CVHub520/X-AnyLabeling#214]
v2.3.0
X-AnyLabeling-GPU.exe
而且打开文件夹需要点击两次，才能弹出对话框

**Comment by CVHub520** [comment]
Hi, @Chenastron:

For the GPU version, it relies on a particular CUDA environment. Please try running the CPU version or directly running the source code.

**Comment by TheSmileXiao** [comment]
我有着相同的问题， 不论是直接运行发行版还是运行源代码都在加载模型的过程中闪退，我的CUDA版本是11.8, 系统是WINDOWS。

**Comment by CVHub520** [comment]
Hi, @TheSmileXiao:

I'm sorry to hear about that. Could you please specify which model you are trying to load when the issue occurs? This information will help us in providing a more accurate solution.

**Comment by TheSmileXiao** [comment]
> Hi, @TheSmileXiao:
> 
> I'm sorry to hear about that. Could you please specify which model you are trying to load when the issue occurs? This information will help us in providing a more accurate solution.

All the models are not downloadable, I run them with the source code and in cmd it shows a missing file
cublaslt64_12.dll

**Comment by CVHub520** [comment]
Thank you for your feedback. To address the issue, you can copy the cublaslt64_12.dll file from the bin subfolder of the CUDA Toolkit installation directory. Alternatively, I recommend trying the CPU version initially to ensure compatibility with your machine.
