### ISSUE TITLE
is there support of pose labeling? i didn't saw any tutorial or how to do it

### ISSUE THREAD

**Issue by gbo999** [CVHub520/X-AnyLabeling#215]
is there support of pose labeling? i didn't saw any tutorial or how to do it

**Comment by CVHub520** [comment]
Hello @gbo999,

If you want to label keypoint tasks, you can turn on the `point` mode for labeling keypoints in manual mode. In addition, the tool has also built in multiple pose estimation [models](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/model_zoo.md) to provide a more powerful automatic labeling engine.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/49b1c8c3-f5ba-43c5-8645-54713f4c0728)

Best regards.
CVHub

**Comment by gbo999** [comment]
But how to deal with bounding boxes numbers and unvisible?
