### ISSUE TITLE
Integration of Dual Fine-Tuned YOLOv8n Models for Assisted Annotation to Create a Unified Dataset

### ISSUE THREAD

**Issue by yihong1120** [CVHub520/X-AnyLabeling#217]
Dear X-AnyLabeling Maintainers,

I hope this message finds you well. I am reaching out to inquire about the possibility of utilising two separately fine-tuned YOLOv8n models for the purpose of assisted annotation within the X-AnyLabeling tool. My objective is to generate a cohesive dataset that benefits from the strengths of both models.

To elaborate, I have two `.pt` files corresponding to YOLOv8n models that have been fine-tuned on distinct but related datasets. I am interested in understanding if there is a provision within X-AnyLabeling to employ these models simultaneously or in a sequential manner to annotate a new set of images. The aim is to leverage the combined predictive capabilities of both models to enhance the accuracy and reliability of the annotations.

Could you please advise on the following points:
1. Does X-AnyLabeling support the integration of multiple models for assisted annotation?
2. If so, what would be the recommended approach to merge the inference results from two models to create a unified dataset?
3. Are there any best practices or considerations to keep in mind when using multiple models for annotation purposes?

I believe that the ability to combine insights from multiple specialised models could significantly improve the annotation process, especially for complex datasets where different models may excel in recognising particular classes or aspects.

Thank you for your time and the remarkable work you have done with X-AnyLabeling. I eagerly await your guidance on this matter.

Best regards,
yihong1120

**Comment by CVHub520** [comment]
Hi there,

Certainly! It's quite straightforward, and you just need to inherit from the Model class. For more details, you can refer to the documentation [here](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/custom_model.md#22-unadapted-models). 

For specific examples, you can check out the following instances:
- [yolox_dwpose.py](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/yolox_dwpose.py)
- [yolov5_ram.py](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/yolov5_ram.py)

Feel free to create any tool flows according to your specific needs. Let me know if you have any further questions.

Best regards,
CVHub
