### ISSUE TITLE
如何导出关键点标注文件，导出voc格式xml里面不含人体关键点的标注

### ISSUE THREAD

**Issue by CodingPerNight** [CVHub520/X-AnyLabeling#218]
导出的xml内容：
<?xml version="1.0" ?>
<annotation>
  <folder>D:\workData\AJY\datasets\POSE\images\Annotations</folder>
  <filename>000024_0eac958726e548a5a44a0f40fb545ebb_2-0001.jpg</filename>
  <size>
    <width>1280</width>
    <height>720</height>
    <depth>3</depth>
  </size>
  <object>
    <name>person</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>532.0</xmin>
      <ymin>134.0</ymin>
      <xmax>777.0</xmax>
      <ymax>677.0</ymax>
    </bndbox>
  </object>
  <object>
    <name>person</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>957.0</xmin>
      <ymin>41.0</ymin>
      <xmax>1045.0</xmax>
      <ymax>286.0</ymax>
    </bndbox>
  </object>
</annotation>

不含关键点

**Comment by CVHub520** [comment]
Hello, @CodingPerNight:

Currently, there is no support for exporting keypoints. If convenient, you can provide a reference sample for me to look at. If suitable, we might consider supporting it in the future.

Best regards.

**Comment by CodingPerNight** [comment]
好的 谢谢解答。

**Comment by zz-zik** [comment]
我也遇到了这个需求，目前有没有实现点标注导出为voc格式呢
