### ISSUE TITLE
json文件格式

### ISSUE THREAD

**Issue by xiaobaixuejava** [CVHub520/X-AnyLabeling#219]
软件很好，但是我使用上有问题，我在使用AnyLabeling.exe的时候，json文件是
      "points": [
        [
          380.7692307692308,
          396.9230769230769
        ],
        [
          466.15384615384613,
          580.0
        ]
      ],
而您的这个软件是有4个元素的，导致我的txt格式转换有问题，不知道您这边能不能加个选择可以让json文件有2个或者4个元素？
还有一个问题就是能不能支持选择 yolo的label文件夹，我通过yolo识别了一个文件夹的文件，希望您这边能读取这个label文件夹的txt文件，然后可以匹配上图片，最后支持批量的json和txt文件夹互转好方便直接使用，谢谢大佬了

**Comment by CVHub520** [comment]
Hello, @xiaobaixuejava:

X-AnyLabeling currently supports both 2-point and 4-point modes for loading and exporting in the YOLO format. If you haven't already, you might want to give that a try, make sure you are using the latest version. Additionally, you can directly use X-AnyLabeling, which covers all the functionalities of AnyLabeling.

Best regards,
CVHub

**Comment by xiaobaixuejava** [comment]
Hello, how do I set the JSON file to have 2-point coordinates in the annotation software? Also, with the latest version of the CPU package, I can't export label files. Instead, it opens a txt file. I am using YOLOv8 for my project. So, my process involves organizing the source images, then using a trained .pt file to detect objects, generating a txt file with YOLOv8 recognized labels, converting it to JSON, and using annotation software to verify the YOLO detection results for calibration. After that, I convert it back to a txt file through code. I wonder if in the future, the developers could support directly importing/exporting txt files and exporting all recognized image annotation files to txt, so I don't have to convert files back and forth

**Comment by CVHub520** [comment]
Hi, @xiaobaixuejava; If you're only interested in training YOLO models, you don't need to worry about JSON files at all. Also, the X-AnyLabeling software has supported direct YOLO-TXT file importing and exporting from quite early on; you don't need to do these conversions yourself.
Hence, you should either update your version or download the code and run it directly, following the [user_guide](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md) to proceed.
