### ISSUE TITLE
请问图形界面怎么进行标注格式的选择？

### ISSUE THREAD

**Issue by koihoo** [CVHub520/X-AnyLabeling#22]
我在图像界面和issue里面查找了标注格式转换的相关信息，但没有查找到具体操作。
请问图形界面怎么进行标注格式的选择？

**Comment by CVHub520** [comment]
您好，目前还未加控件，可参考此[脚本](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/label_converter.py)进行转换。

**Comment by aiyou9** [comment]
yolo to custom 有转换成功吗？好像标注文件后缀名判断，少写了判断标注文件后缀名
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/528eeeb5-a476-4197-82ac-3547d0cda749)
修改后，args.input 传进yolov5_to_custom后，报错

**Comment by aiyou9** [comment]
批量转换yolo格式到x-anylabeling有问题，请修复一下这个脚本

**Comment by CVHub520** [comment]
> 批量转换yolo格式到x-anylabeling有问题，请修复一下这个脚本

您好，代码已修复，请重新尝试！【[链接](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/label_converter.py)】

**Comment by aiyou9** [comment]
> > 批量转换yolo格式到x-anylabeling有问题，请修复一下这个脚本
> 
> 您好，代码已修复，请重新尝试！【[链接](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/label_converter.py)】

1、排除已存在的子文件夹。包括文件夹名中起始为 . 命名的。在jupyter里，会生成 .ipynb_checkpoints 文件夹
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/102af479-15ea-49d2-b59f-5c1cf1f61cec)


2、运行中断后，重新运行，需要排除已经生成的 .json 的标注文件
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/5e1cf270-5f7d-4823-9483-37f974bbddbb)

**Comment by aiyou9** [comment]
哦，第二个，是因为json 没输出到 ，输出文件夹

**Comment by aiyou9** [comment]
> > 批量转换yolo格式到x-anylabeling有问题，请修复一下这个脚本
> 
> 您好，代码已修复，请重新尝试！【[链接](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/label_converter.py)】

本地运行没问题，就是转换结果，输出文件夹，是图像文件夹，不是输出文件夹

**Comment by CVHub520** [comment]
> > > 批量转换yolo格式到x-anylabeling有问题，请修复一下这个脚本
> > 
> > 
> > 您好，代码已修复，请重新尝试！【[链接](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/label_converter.py)】
> 
> 本地运行没问题，就是转换结果，输出文件夹，是图像文件夹，不是输出文件夹

这个没办法，写到其他文件夹会报错，还没对不同系统的文件路径格式做兼容。

**Comment by 1320414730** [comment]
感谢分享，希望能够加入几种常见格式的保存输出

**Comment by aiyou9** [comment]
> 感谢分享，希望能够加入几种常见格式的保存输出

转成coco，基本上都有转换脚本吧？
