### ISSUE TITLE
后期能否支持直接使用yolo的pt来识别文件夹？

### ISSUE THREAD

**Issue by xiaobaixuejava** [CVHub520/X-AnyLabeling#220]
后期能否支持直接使用yolo的pt来识别文件夹？ 希望大佬能加入这个功能

**Comment by CVHub520** [comment]
We appreciate your interest. This feature is indeed something we are considering for future releases. Please stay tuned for updates.

**Comment by monkeycc** [comment]
这个建议好

可以用yolov8的框架
什么都能支持

**Comment by lishulincug1** [comment]
很期待！

**Comment by lishulincug1** [comment]
> 这个建议好
> 
> 可以用yolov8的框架 https://github.com/ultralytics/ultralytics
> 
> 什么都能支持 @CVHub520

[ultralytics](https://github.com/ultralytics/ultralytics) ultralytics打包有问题，而且还是多线程的，在pyqt一起打包后运行有问题，有什么好的处理方式不？

**Comment by mcmy** [comment]
我试过了，缺点就是要把pytorch和ultralytics打包进去，ultralytics内包含了cudnn，打包的exe有2GB+，目前还是不建议，转换onnx后导入一样能用

**Comment by CVHub520** [comment]
Duplicate of #401.
