### ISSUE TITLE
RTMDet-M-RTMO-M OpenMMLab自动标注存在问题

### ISSUE THREAD

**Issue by CodingPerNight** [CVHub520/X-AnyLabeling#221]
有部分图片没有自动标注的预测结果，报错信息：Error in predict_shapes: index 0 is out of bounds for axis 0 with size 0
推测问题可能是RTMDet人体检测的结果与RTMO关键点检测的结果长度不相同导致的。

**Comment by CVHub520** [comment]
Hello, @CodingPerNight:

Thank you for reporting the issue. If it is convenient for you, could you please send the problematic images to our dedicated email address: cv_hub@163.com so that we can further investigate the root cause of this issue?

Best regards.

**Comment by CodingPerNight** [comment]
我的图像是客户的私有数据集，不方便外传，请理解。我可以提供我的分析，可以参考：
RTMO是一个POSE的单阶段模型，它本身就有det头与keypoints头，我看到工具是将RTMDet的person检测结果（多个）与RTMOkeypoints头的kp检测结果（多个）进行了关联，我怀疑是这两个结果的长度不一致导致的问题。比如有5个人，但是只有4组keypoints。

**Comment by CVHub520** [comment]
> 我的图像是客户的私有数据集，不方便外传，请理解。我可以提供我的分析，可以参考： RTMO是一个POSE的单阶段模型，它本身就有det头与keypoints头，我看到工具是将RTMDet的person检测结果（多个）与RTMOkeypoints头的kp检测结果（多个）进行了关联，我怀疑是这两个结果的长度不一致导致的问题。比如有5个人，但是只有4组keypoints。

Hello, the source code has already been updated. Feel free to give it a try at your convenience. If you encounter any issues again, please don't hesitate to let me know. By the way, the RTMO model is invoked when the detected bounding boxes are provided, so it's highly likely not related to the reason you mentioned.

**Comment by CodingPerNight** [comment]
> > 我的图像是客户的私有数据集，不方便外传，请理解。我可以提供我的分析，可以参考： RTMO是一个POSE的单阶段模型，它本身就有det头与keypoints头，我看到工具是将RTMDet的person检测结果（多个）与RTMOkeypoints头的kp检测结果（多个）进行了关联，我怀疑是这两个结果的长度不一致导致的问题。比如有5个人，但是只有4组keypoints。
> 
> Hello, the source code has already been updated. Feel free to give it a try at your convenience. If you encounter any issues again, please don't hesitate to let me know. By the way, the RTMO model is invoked when the detected bounding boxes are provided, so it's highly likely not related to the reason you mentioned.

感谢修复，我克隆了最新的代码，但是问题依然存在。

我调试了一下，当RTMdet检测出来person bbox后，如果rtmo模型在这个bbox里面没有检测出来keypoints，会触发这个bug。希望这个描述对您有帮助。

（我之前对代码的理解确实有误，感谢指正）

**Comment by CVHub520** [comment]
> > > 我的图像是客户的私有数据集，不方便外传，请理解。我可以提供我的分析，可以参考： RTMO是一个POSE的单阶段模型，它本身就有det头与keypoints头，我看到工具是将RTMDet的person检测结果（多个）与RTMOkeypoints头的kp检测结果（多个）进行了关联，我怀疑是这两个结果的长度不一致导致的问题。比如有5个人，但是只有4组keypoints。
> > 
> > 
> > Hello, the source code has already been updated. Feel free to give it a try at your convenience. If you encounter any issues again, please don't hesitate to let me know. By the way, the RTMO model is invoked when the detected bounding boxes are provided, so it's highly likely not related to the reason you mentioned.
> 
> 感谢修复，我克隆了最新的代码，但是问题依然存在。
> 
> 我调试了一下，当RTMdet检测出来person bbox后，如果rtmo模型在这个bbox里面没有检测出来keypoints，会触发这个bug。希望这个描述对您有帮助。
> 
> （我之前对代码的理解确实有误，感谢指正）

Thanks for your advise, I'll check it later.
