### ISSUE TITLE
retangle保存json

### ISSUE THREAD

**Issue by Zomcxj** [CVHub520/X-AnyLabeling#222]
当标注目标时，会以起始点开始顺时针保存，只有按标准左上角第一点右下角第二点标注格式是正确的，如果从右下角往左上角标，则json保存坐标会以右下角为起始点顺时针保存，导致转换VOC时xmin和xmax ymin和ymax交换    in point4

**Comment by CVHub520** [comment]
Hi, @Zomcxj, thank you for your valuable feedback.

Now, the problem solved, please pull the source code again and try.
