### ISSUE TITLE
在已有数据集上通过AI增加标签，而不是覆盖

### ISSUE THREAD

**Issue by AHideoKuzeA** [CVHub520/X-AnyLabeling#223]
您好，我注意到使用AI标注会导致导入的Annotation被AI推理结果覆盖，请问如果我希望在原有标签的基础上使用AI增加标注，是否有相关的功能

**Comment by CVHub520** [comment]
Please could you inform me which model you are currently using?

**Comment by AHideoKuzeA** [comment]
感谢您的回答，我使用的是GroundingDINO（SwinB-QInt8）IDEA模型，在输入text prompt后先前的标注会被覆盖

**Comment by CVHub520** [comment]
> 感谢您的回答，我使用的是GroundingDINO（SwinB-QInt8）IDEA模型，在输入text prompt后先前的标注会被覆盖

Hello, you can consider adjusting the `replace` arguments to False in [this line](https://github.com/CVHub520/X-AnyLabeling/blob/a73cc7674c9b95d66955cc458efee6bb90d661a9/anylabeling/services/auto_labeling/grounding_dino.py#L211) for potential improvement.

**Comment by AHideoKuzeA** [comment]
谢谢您及时的回应，我会尽快尝试并反馈改进的效果

**Comment by AHideoKuzeA** [comment]
谢谢您及时的回应，我会尽快尝试并反馈改进的效果

**Comment by AHideoKuzeA** [comment]
非常感谢您的解答，我的问题成功的解决了
