### ISSUE TITLE
VOC format 

### ISSUE THREAD

**Issue by kexul** [CVHub520/X-AnyLabeling#224]
Hi, huge thanks for this great project! 

Should the <bndbox> label in VOC lable be integer? 

For example, here is the label exported by X-AnyLabeling: 
```
 <bndbox>
      <xmin>2371.0</xmin>
      <ymin>1153.0</ymin>
      <xmax>3094.0</xmax>
      <ymax>2154.0</ymax>
    </bndbox>
```

In the example file [here](https://roboflow.com/formats/pascal-voc-xml), they have: 
```
<bndbox>
	<xmin>179</xmin>
	<xmax>231</xmax>
	<ymin>85</ymin>
	<ymax>144</ymax>
</bndbox>
```

**Comment by CVHub520** [comment]
Hello, @kexul:

Thank you for your suggestion. We really appreciate your contribution to our project!

In response to your question, whether the label in VOC should be an integer - we have made a synchronized modification to this based on your advice. Please try pulling the latest source code for further testing.

Best regards,
CVHub

**Comment by kexul** [comment]
Thank you so much for the speedy response, it means a lot!
