### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sjxxrh** [CVHub520/X-AnyLabeling#226]
When an existing voc label folder is loaded, a batch json file is generated in the image folder, and the current image does not display the existing label, the next label will display the following error.
"bytes-like object is required, not 'NoneType，而不是“NoneType，确保E/X-AnyLabeling-main/images/00016,json是一个有效的标签文件。"

**Comment by CVHub520** [comment]
> When an existing voc label folder is loaded, a batch json file is generated in the image folder, and the current image does not display the existing label, the next label will display the following error. "bytes-like object is required, not 'NoneType，而不是“NoneType，确保E/X-AnyLabeling-main/images/00016,json是一个有效的标签文件。"

Hi @sjxxrh, could you please provide the error images along with their corresponding labels? Kindly send them to the email address: cv_hub@163.com. Thanks!

**Comment by sjxxrh** [comment]
It has been sent to [cv_hub@163.com], thank you.

**Comment by CVHub520** [comment]
Resolved in  [#fcbce8d](https://github.com/CVHub520/X-AnyLabeling/commit/fcbce8dca9f661afbb9788bbc06c7c8c68999cb1).
