### ISSUE TITLE
在AI加点状态中，按ESC界面会消失，变为全白

### ISSUE THREAD

**Issue by leozjr** [CVHub520/X-AnyLabeling#228]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/44260371/55c14620-3e10-490c-81ca-ab2bcb06d0c0)

在此状态下操作界面依然全白，需要重启软件才能恢复正常。

版本为2.3.0最新版

**Comment by CVHub520** [comment]
Hello, @leozjr:

Thank you for your observation. After testing, we haven't been able to recreate the issue that you've described. If this is a sporadic issue, it might be unavoidable. However, if it consistently appears, please provide us with the specific steps to recreate the issue. This information will assist our team in better pinpointing and addressing the problem.

Best regards,
CVHub

**Comment by Water-Disappear** [comment]
是的，当我第一次按AI标注的矩形框想要取消时我按了ESC键之后就界面全白了，需要重启软件才能恢复
![界面全白](https://github.com/user-attachments/assets/17b4a2d5-7ebf-41ce-a03b-99bcbb29f28c)

**Comment by CVHub520** [comment]
@leozjr @Water-Disappear 

最新代码分支已修复。
