### ISSUE TITLE
初始打开软件时，打开文件夹需要点击按钮两次才能打开

### ISSUE THREAD

**Issue by leozjr** [CVHub520/X-AnyLabeling#229]
如题，应该是个BUG

**Comment by CVHub520** [comment]
Thank you for your feedback. The current design of the software requires that you double-click the folder when initially loading the interface. Subsequent actions can be triggered with a single click.

**Comment by benbtx** [comment]
遇到了，求解。。。win.activateWindow()也不行。。。setWindowFlags。。。手动触发一下clicked x信号？

**Comment by CVHub520** [comment]
Thank you for your feedback. @benbtx; I think this situation is not a major inconvenience, does add an extra step to the initial setup process. However, once that first step is complete, the interface can be used efficiently with single-click interactions. 😄
