### ISSUE TITLE
自行下载和添加模型的方法

### ISSUE THREAD

**Issue by xinyuanTan** [CVHub520/X-AnyLabeling#23]
打开路径：X-AnyLabeling-main\anylabeling\configs\auto_labeling  找到想要使用的模型的yaml文件，如 segment_anything_vit_h_quant
![image](https://github.com/CVHub520/X-AnyLabeling/assets/39583658/c38c9e3c-c3cd-45c3-b170-07f94ac1b550)
将其复制到希望存放的位置，用记事本打开，使用任意下载工具或方法下载encoder_model_path，decoder_model_path后的2个onnx文件
![image](https://github.com/CVHub520/X-AnyLabeling/assets/39583658/d6230bd2-cd73-4e51-8a84-b60253207ec2)
然后复制到与yaml同路径下，在修改encoder_model_path，decoder_model_path为相同路径：
![image](https://github.com/CVHub520/X-AnyLabeling/assets/39583658/e9680e79-de71-4d95-afe7-36f15a0b8f58)
然后在加载模型种选择 加载自定义模型，选择新创建的yaml文件即可。
![image](https://github.com/CVHub520/X-AnyLabeling/assets/39583658/9fa1e2c7-dc6b-4f84-9e0a-24a032a4b613)

**Comment by leslielee619** [comment]
多谢

**Comment by JAYCHOU2020** [comment]
> 打开路径：X-AnyLabeling-main\anylabeling\configs\auto_labeling 找到想要使用的模型的yaml文件，如 segment_anything_vit_h_quant ![image](https://user-images.githubusercontent.com/39583658/251964360-c38c9e3c-c3cd-45c3-b170-07f94ac1b550.png) 将其复制到希望存放的位置，用记事本打开，使用任意下载工具或方法下载encoder_model_path，decoder_model_path后的2个onnx文件 ![image](https://user-images.githubusercontent.com/39583658/251964477-d6230bd2-cd73-4e51-8a84-b60253207ec2.png) 然后复制到与yaml同路径下，在修改encoder_model_path，decoder_model_path为相同路径： ![image](https://user-images.githubusercontent.com/39583658/251964520-e9680e79-de71-4d95-afe7-36f15a0b8f58.png) 然后在加载模型种选择 加载自定义模型，选择新创建的yaml文件即可。 ![image](https://user-images.githubusercontent.com/39583658/251964584-9fa1e2c7-dc6b-4f84-9e0a-24a032a4b613.png)

如何部署Medical-SAM-Adapter-main的模型？如何找到相应的yaml文件

**Comment by JAYCHOU2020** [comment]
自己训练的Medical-SAM-Adapter-main的模型只有一个文件checkpoint_best.pth，如何分成yaml文件里所需要的encoder和decoder 的onnx文件 呢？

**Comment by CVHub520** [comment]
> 自己训练的Medical-SAM-Adapter-main的模型只有一个文件checkpoint_best.pth，如何分成yaml文件里所需要的encoder和decoder 的onnx文件 呢？

您好，可以参考此[文档](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md)

**Comment by jaffe-fly** [comment]
> > 自己训练的Medical-SAM-Adapter-main的模型只有一个文件checkpoint_best.pth，如何分成yaml文件里所需要的encoder和decoder 的onnx文件 呢？
> 
> 您好，可以参考此[文档](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md)

这个链接404了

**Comment by CVHub520** [comment]
> > > 自己训练的Medical-SAM-Adapter-main的模型只有一个文件checkpoint_best.pth，如何分成yaml文件里所需要的encoder和decoder 的onnx文件 呢？
> > 
> > 
> > 您好，可以参考此[文档](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md)
> 
> 这个链接404了

Hi, @jaffe-fly, you can assess this [link](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md).

**Comment by babyta** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/37787795/5579df28-7521-4d4b-a1b2-11092af2c93b)
出错了

**Comment by libra-bola** [comment]
我加载完模型窗口就关掉了，也没报错信息

**Comment by babyta** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by CVHub520** [comment]
> 我加载完模型窗口就关掉了，也没报错信息

Duplicated with #528.
