### ISSUE TITLE
多目标跟踪

### ISSUE THREAD

**Issue by jiyuwangbupt** [CVHub520/X-AnyLabeling#230]
您好，请问多目标跟踪怎么导入和导出，我这边失败了。使用yolov5——bytetrack进行标注的。点击导入属性文件报错直接闪退了。
![image](https://github.com/CVHub520/X-AnyLabeling/assets/37127150/a249f275-392d-4251-b742-92026dc732b7)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/37127150/1d1261bc-2bdb-4eab-b5d5-23ff7c53f464)

**Comment by CVHub520** [comment]
Hello, @jiyuwangbupt:

I understand that you are having difficulties with the import and export functionality for multi-object tracking (MOT) using yolov5-bytetrack for annotation. The attribute file is designed for a multi-label classification model and may not be compatible with the MOT task.

For multi-object tracking, the export format is usually in MOT.csv, for reference, you may want to check this [file](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/demo_video/demo_video.csv).

Additionally, you can follow the guide detailed in this [toturial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E5%A4%9A%E7%9B%AE%E6%A0%87%E8%B7%9F%E8%B8%AA) to avoid further issues.

Best regards,
CVHub
