### ISSUE TITLE
使用SAM标注旋转框

### ISSUE THREAD

**Issue by DeepJackNotFound** [CVHub520/X-AnyLabeling#231]
怎么使用SAM去标旋转框呢

**Comment by CVHub520** [comment]
Hello, @DeepJackNotFound:

Currently, there haven't been any specific tools or methods regarding the use of SAM to mark rotating boxes in the documentation we have available. If you do come across any relevant and cutting-edge techniques, we would welcome your suggestions. X-AnyLabeling can consider incorporating it based on evaluation.

Best Regards,
CVHub
