### ISSUE TITLE
能否提供模型包的合集，我们这一个一个下载太慢了，想测试一下不同模型的效果，非常感谢

### ISSUE THREAD

**Issue by ZJDATY** [CVHub520/X-AnyLabeling#232]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/29767049/1cd987da-8fe2-491e-a0f2-20e0fec95b3b)
@CVHub520  能否上传一份模型合集，我想把这里面的模型复制到 
`C:\Users\Administrator\anylabeling_data\models` 这里面直接使用。
![image](https://github.com/CVHub520/X-AnyLabeling/assets/29767049/461a9c9b-cf16-4199-8c1e-aee4af563899)
一个一个下载实在是太慢了。
 Thank you！

**Comment by CVHub520** [comment]
To streamline the model download process, you can refer to the [model_zoo.md](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/model_zoo.md) document. It provides a list of all public models available in X-AnyLabeling.

**Comment by ZJDATY** [comment]
感谢回复，尽管不是我想要的合集
