### ISSUE TITLE
Error in predict_shapes: operands could not be broadcast together with shapes (1,2,6) (19200,2) 

### ISSUE THREAD

**Issue by analwang** [CVHub520/X-AnyLabeling#233]
I had import my model successfully, but when run it the terminal said:” Error in predict_shapes: operands could not be broadcast together with shapes (1,2,6) (19200,2) “ without any box on my image.

**Comment by analwang** [comment]
![86490e0547455e7c28a454300aed9047](https://github.com/CVHub520/X-AnyLabeling/assets/41179787/76975038-0a8d-49e7-896c-cbea34f5a663)

**Comment by analwang** [comment]
![2159191bdbfc27a9655f907ef0096e37](https://github.com/CVHub520/X-AnyLabeling/assets/41179787/ce95564e-7f51-49f4-a52e-68269c443297)

**Comment by CVHub520** [comment]
To resolve the error you're experiencing, you might want to try the following solutions:

- Remove the 'anchors' parameter.
- The category 'Yes' may be recognized as a boolean variable in Python. It's recommended to put it in quotes to indicate that it's a string, helping to avoid confusion.

**Comment by analwang** [comment]
“Yes”
