### ISSUE TITLE
【功能需求】导出yolov8-obb格式的标签数据

### ISSUE THREAD

**Issue by ZJDATY** [CVHub520/X-AnyLabeling#236]
https://docs.ultralytics.com/zh/datasets/obb/

**Comment by CVHub520** [comment]
Hello @ZJDATY,

Thanks for reaching out. The latest source code already supports the YOLOv8_obb format. You're welcome to give it a try! Please note, however, that the released GUI version has not yet incorporated this support.

Best Regards,
CVHub

**Comment by linzengmin** [comment]
Traceback (most recent call last):
  File ".\label_converter.py", line 1057, in <module>
    main()
  File ".\label_converter.py", line 1017, in main
    converter.custom_to_dota(src_file, dst_file)
  File ".\label_converter.py", line 662, in custom_to_dota
    for shape in data["shapes"]:

**Comment by CVHub520** [comment]
> Traceback (most recent call last): File ".\label_converter.py", line 1057, in main() File ".\label_converter.py", line 1017, in main converter.custom_to_dota(src_file, dst_file) File ".\label_converter.py", line 662, in custom_to_dota for shape in data["shapes"]:

Hi, @linzengmin, currently, the x-anylabeling tools has already support to export yolov8_obb annotations directly from GUI, please feel free to give it try!
