### ISSUE TITLE
The ONNX link for Depth-Anything is invalid?

### ISSUE THREAD

**Issue by dosemeion** [CVHub520/X-AnyLabeling#237]
https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.3.1/depth_anything_vitl14.onnx

**Comment by CVHub520** [comment]
> https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.3.1/depth_anything_vitl14.onnx

Hi, @dosemeion; Apologies for the inconvenience. The latest version v2.3.1 is currently under testing. In the meantime, you can download it from [Baidu nesk](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md) first. For more help, you can refer to this [docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md). Thank you for your understanding.
