### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by yugogogogo** [CVHub520/X-AnyLabeling#238]
安装教程进行安装，运行python anylabeling/app.py出现如下报错
<img width="750" alt="屏幕截图 2024-01-27 161529" src="https://github.com/CVHub520/X-AnyLabeling/assets/124115482/2abaf54e-f7da-429a-afa6-577e384bbea1">

**Comment by CVHub520** [comment]
Hi, @yugogogogo, you can remove the default config file (~/.anylabelingrc) where located in the user directory, and try to it again.

**Comment by vvwcap** [comment]
> Hi, @yugogogogo, you can remove the default config file (~/.anylabelingrc) where located in the user directory, and try to it again.

don't find,I didn't have this document, but I still reported this error

**Comment by vvwcap** [comment]
> Hi, @yugogogogo, you can remove the default config file (~/.anylabelingrc) where located in the user directory, and try to it again.

I removed the .xanylabelingrc and it was resolved, thanks

**Comment by CVHub520** [comment]
Hi, @vvwcap:

For the latest versions, we have unified the configuration file to be named `.xanylabelingrc`, We strongly recommend updating to the [latest version](https://github.com/CVHub520/X-AnyLabeling) when you get a chance. It offers more stable usage, abundant new features, and access to more models.
