### ISSUE TITLE
下载模型时闪退（when downloading the model，X-AnyLabeling crashed immediately）

### ISSUE THREAD

**Issue by caopancake** [CVHub520/X-AnyLabeling#239]
version：X-AnyLabeling v2.3.0 [X-AnyLabeling-GPU.exe] [X-AnyLabeling-CPU.exe]

**Comment by CVHub520** [comment]
Thank you for your feedback. May I ask which model you were testing when the crash occurred?

**Comment by caopancake** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:30:42_Pacific_Standard_Time_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
___________________________________________________________
Python 3.11.5
__________________________________________________________
cudnn-windows-x86_64-8.9.7.29_cuda12-archive
___________________________________________________
很奇怪，我可以用pycharm运行你们的源代码的cpu版本。。。。。。
运行起来没问题，但是用exe版本就运行不了，下载模型时候闪退

**Comment by CVHub520** [comment]
If that's the case, I would suggest you compile the code by yourself if necessary.
