### ISSUE TITLE
可以添加删除文件的功能吗？

### ISSUE THREAD

**Issue by eastDongD** [CVHub520/X-AnyLabeling#242]
在自制数据集中很容易出现质量特别差或十分相似的图片，对训练有一定的影响。想找一个按钮，可以直接删除该图片（或者快捷键删除）

**Comment by CVHub520** [comment]
Hello, @eastDongD:

Yes, your suggestion has been utilized, and you can now try it with the latest source code. The shortcut for deleting (Ctrl+Shift+Del) is now supported. Please note:

1. After updating the source code, please delete the configuration file `~/.anylabelingrc` in the local user directory first;
2. User data will not be genuinely "deleted", but rather moved to the `_delete` folder in the same-level root directory.

Best Regards,
CVHub
