### ISSUE TITLE
快捷键

### ISSUE THREAD

**Issue by Zomcxj** [CVHub520/X-AnyLabeling#244]
修改了anylabeling_config.yaml然后编译导出exe 发现初始快捷键并没有改变，还是需要手动去c盘修改 请问怎么解决

**Comment by CVHub520** [comment]
Hello, @Zomcxj:

The X-AnyLabeling tools will first read from the configuration file in the user directory (~/.anylabelinrc). If this file does not exist, a new .anylabelinrc will be generated according to anylabeling_config.yaml.

If you encounter any issues, please do not hesitate to contact me.
Thanks!
