### ISSUE TITLE
如何调整旋转的最小幅度

### ISSUE THREAD

**Issue by Chtt-123** [CVHub520/X-AnyLabeling#246]
您好！现在的最小旋转幅度是一度，是否可以设置一个更小的旋转幅度，比如0.1,0.01的旋转幅度

**Comment by CVHub520** [comment]
> 您好！现在的最小旋转幅度是一度，是否可以设置一个更小的旋转幅度，比如0.1,0.01的旋转幅度

Hi, @Chtt-123, thanks for your attention.

To adjust the rotation angle, you can make modifications in this [line](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/views/labeling/widgets/canvas.py#L22).
