### ISSUE TITLE
When annotating a rotated box, it is not possible to select points outside the image.

### ISSUE THREAD

**Issue by zdreamer1980** [CVHub520/X-AnyLabeling#247]
English 
        First of all,Thank you very much for your contributions to the open-source community. This morning, I was still struggling with annotating the yolov8n-obb model. There was an issue with the angles predicted by x-AnyLabeling, which did not align with the results obtained using my script. However, when I returned after lunch, I saw that you had already provided an update – truly impressive!
        While using the tool, I encountered some issues. As the title suggests, I am annotating data for the yolov8-obb model training, and many objects in my images are positioned near the edges. For the rotated rectangular boxes, some corner points need to be placed outside the image, but your annotation tool currently doesn't allow selecting points outside. I hope you can assist in addressing this matter.

中文版：
        非常感谢您为开源事业做的贡献，上午的时候我还在为yolov8n-obb的模型辅助标注烦恼， x-AnyLabeling预测的角度存在问题，与我用脚本的结果不一致，结果吃完午饭回来您就更新了 ，实在太六了。
        不过，在使用的时候我也遇到了一些问题，正如标题所言，我在为yolov8-obb模型训练进行标注数据，我的图片中有很多目标都是靠近边缘的。旋转的矩形框的部分角点需要在图像外部，但是您的标注工具无法在外面选点。希望可以帮忙修复一些。

![image](https://github.com/CVHub520/X-AnyLabeling/assets/158547928/803393b4-4b41-4aa2-a4ed-fb63dc863a2b)

**Comment by zdreamer1980** [comment]
Hello @CVHub520 @David-19940718 @hdnh2006 I've encountered an issue here, and I was wondering if you could provide some guidance?

**Comment by CVHub520** [comment]
Hello, @zdreamer1980:

Thank you for reaching out. One thing that we need to clarify here is, how are the rotated boxes that extend beyond the image handled during your training?

Best Regards,
CVHub

**Comment by CVHub520** [comment]
If you do need boxes that rotate outside the boundary during your training, you can modify a few pieces of code in the `canvas.py` file:
```
#Line300
Change: if self.out_off_pixmap(pos): -> if self.out_off_pixmap(pos) and self.create_mode != "rotation":

#Line779
Change: if self.out_off_pixmap(pos): -> if self.out_off_pixmap(pos) and shape.shape_type != "rotation":

#Line788-794
Comment out these lines of code.

#Line820
Replace the following function.:
    def bounded_move_shapes(self, shapes, pos):
        """Move shapes. Adjust position to be bounded by pixmap border"""
        rotation_flag = False
        for shape in shapes:
            if shape.shape_type == "rotation":
                rotation_flag = True
                break
        if self.out_off_pixmap(pos) and not rotation_flag:
            return False  # No need to move
        o1 = pos + self.offsets[0]
        if self.out_off_pixmap(o1) and not rotation_flag:
            pos -= QtCore.QPoint(min(0, int(o1.x())), min(0, int(o1.y())))
        o2 = pos + self.offsets[1]
        if self.out_off_pixmap(o2) and not rotation_flag:
            pos += QtCore.QPoint(
                min(0, int(self.pixmap.width() - o2.x())),
                min(0, int(self.pixmap.height() - o2.y())),
            )
        # XXX: The next line tracks the new position of the cursor
        # relative to the shape, but also results in making it
        # a bit "shaky" when nearing the border and allows it to
        # go outside of the shape's area for some reason.
        # self.calculateOffsets(self.selectedShapes, pos)
        dp = pos - self.prev_point
        if dp:
            for shape in shapes:
                shape.move_by(dp)
            self.prev_point = pos
            return True
        return False
```

**Comment by zdreamer1980** [comment]
> Hello, @zdreamer1980:
> 
> Thank you for reaching out. One thing that we need to clarify here is, how are the rotated boxes that extend beyond the image handled during your training?
> 
> Best Regards, CVHub

Thank you very much for your quick response. 
Yolov8-obb retained the points that crossed the boundary. This can be seen from the visualizations it generates. In addition, during inference,the trained model will also output points outside the image .

By the way, I really like the annotation software you developed. I think it will be mainstream for a long time. 
Best Regards,
