### ISSUE TITLE
自動標註

### ISSUE THREAD

**Issue by ChenPingChen** [CVHub520/X-AnyLabeling#248]
請問自動標註功能可以先使用一個自訂義模組進行標註後，再使用另一個自訂義模組進行新增標註嗎？

**Comment by CVHub520** [comment]
> 請問自動標註功能可以先使用一個自訂義模組進行標註後，再使用另一個自訂義模組進行新增標註嗎？

Hi, @ChenPingChen:

If you need to join multiple models for annotation, it is suggested to write it as a pipeline for one-click calling. For reference, you can check out [custom_model.md](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md).
