### ISSUE TITLE
发现一个对53个开源数据集做SAM微调训练的工作，大佬评估一下，是否有必要接入

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#249]
https://github.com/yuhoo0302/Segment-Anything-Model-for-Medical-Images?tab=readme-ov-file

这个工作，收集并整理了 53 个开源数据集，并构建了一个包含 18 个模态、84 个对象、125 个对象模态配对目标、1050K 2D 图像和 6033K 掩模的大型医学分割数据集。并进行了SAM大模型的微调训练，给了h/b 的训练结果
大佬评估一下，值不值得接入X-anylabeling

**Comment by aiyou9** [comment]
只提供了pth文件，可能不好做转onnx

**Comment by CVHub520** [comment]
Hello, @aiyou9:

Thank you very much for your suggestion. Unfortunately, after attempting it, we have found that the actual performance of this model is relatively poor. In the future, if you have similar suggestions, you might want to try it yourself first, before making a recommendation.

By the way, the converted model is attached below for anyone interested to download and have a try.

[download link.](https://pan.baidu.com/s/1GpURy8oswtFzx-HLeNrV3A?pwd=jfts)

Best Regards,
CVHub

**Comment by CVHub520** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/35f44d87-6142-4d53-bd1d-a02d4ba30673)

**Comment by aiyou9** [comment]
好的，抱歉，轻率了，下次我测试好，以为发的top 10分的期刊，效果可以
