### ISSUE TITLE
自动使用上一次的label和保持之前的缩放尺寸这两个功能有BUG

### ISSUE THREAD

**Issue by Beforcer** [CVHub520/X-AnyLabeling#25]
1.自动使用上一次的label，经常使用的不是上次的label
2.保持之前的图像缩放尺寸，有时候突然就变回原图了

**Comment by CVHub520** [comment]
您好，“自动使用上一次的label”请确保你的图片分辨率是一致的。如果图片分辨率不一致，请不要使用该功能。
第2个问题暂时没遇到过，可能跟你的机器有关。

**Comment by Beforcer** [comment]
> 您好，“自动使用上一次的label”请确保你的图片分辨率是一致的。如果图片分辨率不一致，请不要使用该功能。 第2个问题暂时没遇到过，可能跟你的机器有关


> 我的图像分辨率是一样的，我是开着保持之前的图像缩放进行标注的。标注的时候一般都是一个类别一个类别的标，这样省去了选择类别的时间，自动使用上次的label分别率不一样也应该能用吧，这个无法修复吗
