### ISSUE TITLE
What modifications should be made to the model trained using yolov8_pose

### ISSUE THREAD

**Issue by gaoxinstudent** [CVHub520/X-AnyLabeling#252]
I have a model trained based on yolov8_pose, with a total of 14 classes, and inference rectangles and four key points for each class. I don't know how to modify the code to make AnyLabeling annotate with my model.
I explored some modifying ways myself, but it didn't work. My modifications are shown in the image below.

First, I wrote a config file, but I don't know if it makes sense.
![屏幕截图 2024-02-11 135859](https://github.com/CVHub520/X-AnyLabeling/assets/150144360/31f9ccda-5316-4c2e-b079-6c81578731e9)
Then, I modified the part of the yolov8_pose.py that deals with keys.
![屏幕截图 2024-02-11 140215](https://github.com/CVHub520/X-AnyLabeling/assets/150144360/f7f21fe9-1df7-4d0d-9721-89b33f533cdc)
That's all the changes I made, and when I select the model, it's not labeled, and I guarantee that the model is usable and accurate.

**Comment by CVHub520** [comment]
Thanks for your feedback. 

Regarding the customization of the model, I would recommend enabling debug mode for debugging. 

Usually, for preprocessing and model inference, no modifications are required if you haven't made any changes to the original training framework. 

Additionally, you might want to check the input and output nodes of the ONNX model and compare them with the example model provided by X-AnyLabeling to ensure the results are in accordance with your expectations.

**Comment by gaoxinstudent** [comment]
Thanks for your answer! I didn't make any changes to the original yolov8_pose framework, just made the following changes to the coco_pose.yaml configuration file on the source code:nc:1--->nc:14 keypoints_shape:[17,3]--->[4,2].The output of the model is [1,26,8400], where 26=x,y,w,h,14*conf,4*(x,y). I don't know if it's because of the configuration file error or because I need to modify the X-AnyLabeling inference code about yolov8_pose, but in the screenshot of the configuration file I mentioned earlier, the model generation annotation cannot be loaded. I've given my *.pt and *.onnx models below and a picture of what needs to be labeled if you need it.
链接：https://pan.baidu.com/s/1UgRX0A3_KOye-Sx7mxVCpg?pwd=0000 
提取码：0000

**Comment by CVHub520** [comment]
Currently, customization for pose estimation models is not natively supported. If you need to use a custom pose estimation model, you will have to modify the source code to adapt to the changes you've made. Please make sure that you modify the inference code in X-AnyLabeling to handle the specific output of your custom yolov8_pose model.

Should you encounter any difficulties or need further assistance, feel free to reach out.
