### ISSUE TITLE
Web Application

### ISSUE THREAD

**Issue by mmortazavi** [CVHub520/X-AnyLabeling#253]
Thanks for the cool application, I like the seamless custom model integration, it works just great. 
Is there plan to provide a web application in near future? It has a huge benefit for self-hosting in a cloud env rather OS (Win or Linux)?

**Comment by CVHub520** [comment]
Hi, @mmortazavi:

Your suggestion sounds great! Thank you for the valuable feedback. However, due to a limitation of necessary manpower, time, and energy, implementing such a feature might be indefinitely postponed at this point.

Best Regards,
CVHub
