### ISSUE TITLE
How to solve the problem of flashing when X-AnyLabeling runs automatic labeling

### ISSUE THREAD

**Issue by wangxirui123456789** [CVHub520/X-AnyLabeling#255]
I trained a custom keypoint detection model using yolov8n pose and converted the model's pt file to onnx format. I successfully imported the model into the software, but when I clicked the button to start automatic annotation, it paused for a while before crashing directly.I searched online for many methods but none of them solved the problem.how I can solve this problem?

**Comment by CVHub520** [comment]
Hello,

I see that you're having trouble with automatic annotation using a custom keypoint detection model. I'd recommend running and debugging the file from the source code to identify at which step your model is failing.

If you're still running into problems after trying the proposed solution, please provide the complete error details so we can better investigate the issue together.

For further assistance, you can also join our WeChat discussion group. Please add the WeChat ID: ww10874 and mention 'X-AnyLabeling' when you apply.

Best regards.

**Comment by wangxirui123456789** [comment]
发自我的荣耀手机-------- 原始邮件 --------发件人： CVHub ***@***.***>日期： 2024年3月4日周一 13:30收件人： CVHub520/X-AnyLabeling ***@***.***>抄送： wangxirui123456789 ***@***.***>, Author ***@***.***>主    题： Re: [CVHub520/X-AnyLabeling] How to solve the problem of flashing when X-AnyLabeling runs automatic labeling (Issue #255)
Closed #255 as completed.
