### ISSUE TITLE
未在GUI界面找到标签管理选项

### ISSUE THREAD

**Issue by dan3577** [CVHub520/X-AnyLabeling#256]
已下载最新的GUI版本，想批量删除上百张person标签，除了通过filter_classes功能，GUI界面未来是否会增加一键修改或者删除标签的功能？

**Comment by CVHub520** [comment]
> 已下载最新的GUI版本，想批量删除上百张person标签，除了通过filter_classes功能，GUI界面未来是否会增加一键修改或者删除标签的功能？

您好，感谢关注。目前该功能已支持，暂未发布新版本，可先下载源码使用，具体可参考此[教程](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E5%BF%AB%E9%80%9F%E6%A0%87%E7%AD%BE%E4%BF%AE%E6%94%B9%E5%8A%9F%E8%83%BD)。
