### ISSUE TITLE
why my model can use in Anylabeling but can not use in X-Anylabeling 

### ISSUE THREAD

**Issue by shiguang111222** [CVHub520/X-AnyLabeling#258]
![Uploading 1708572326844.jpg…]()

**Comment by CVHub520** [comment]
Hi, @shiguang111222:

I understand that you're having trouble using your model in X-Anylabeling, even though it works in Anylabeling. 

Could you tell me what model you're using and the specific issue you receive? 

Furthermore, it appears there may be wrongs with the image link you provided. Could you please upload it once more?

**Comment by shiguang111222** [comment]
I trained the model with yolov8, and when exporting onnx, I set imagsz = 8192. When I use anlabeling, it works fine, but when I get the model to X-anlabeling, it doesn't work. I guess it's caused by the large setting of imagsz. When I change it to imagsz = 1024, both work. But my original photos are all 8192 * 8192, I hope to use the model directly without cutting. Anlabeling can be done, and I think X-anlabeling should work too.
https://github.com/shiguang111222/111222/blob/main/1.jpg
https://github.com/shiguang111222/111222/blob/main/2.jpg

**Comment by CVHub520** [comment]
Thanks for your feedback! 

By default, X-AnyLabeling leverages ORT as its backend inference engine, which may consume a sizable amount of memory. However, the latest version supports the DNN backend which should help alleviate your issue. 

I recommend fetching the latest source code and trying again. Here's how you can specify the backend and the input dimension in your configuration file:

```custom.yaml
type: xxx
...
engine: dnn
input_width: xxx
input_height: xxx
```

Please replace 'xxx' with the appropriate values that suit your needs.
