### ISSUE TITLE
【ui优化】标签输入框，自动适应窗口，呼出的位置，能够自动显示全部，当前，呼出标签输入框，有一半在屏幕外，还有拖一下

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#260]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/f6b40051-3826-4c3c-b9b1-39ac079e90d6)

**Comment by aiyou9** [comment]
右键菜单，倒是自适应界面，会显示全，不会超出界面

**Comment by CVHub520** [comment]
Hi there! @aiyou9:

Thank you for bringing up the issue #260 regarding the label input box UI optimization. We're glad to inform you that we've implemented an update to address your concern. The label dialog now automatically adjusts its popup position to ensure it remains fully visible within the screen boundaries, even when invoked from the edge.

This enhancement prevents the dialog from partially appearing off-screen, eliminating the need for manual adjustment. We encourage you to try out the new functionality and let us know how it improves your experience. Your feedback is invaluable in helping us refine our tools.

Please feel free to test this update and share any further suggestions or issues you may have. Thank you for contributing to making our application better!

Happy labeling! 😄
