### ISSUE TITLE
【ui优化】文件菜单下的自动保存和保存图像数据在内的文件，这两个是一个勾选与否的选项，建议也做成，点击后，图标显示为打钩

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#262]
看不出来是否勾选了自动保存，以及保存图像数据在内的文件
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/9f6576e9-1e76-492f-b60c-69deb02fcecc)

其他后做的菜单里选项里的√，比较好
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/69647964-e2c8-4dfc-9994-cbc835383453)

**Comment by CVHub520** [comment]
您好，此项功能被开启后是有背景框显示的。

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/1ebd19ce-3d85-4efa-805d-cdece903b0e7)

**Comment by aiyou9** [comment]
没有看出点击后，有变化，一直都有橘红色背景
