### ISSUE TITLE
模型库

### ISSUE THREAD

**Issue by hgc1** [CVHub520/X-AnyLabeling#265]
请问模型库中，第一个目标检测的示意图效果用的是哪个算法的模型，也就是那个检测标牌，交通灯，道路标线的模型，谢谢

**Comment by CVHub520** [comment]
> 请问模型库中，第一个目标检测的示意图效果用的是哪个算法的模型，也就是那个检测标牌，交通灯，道路标线的模型，谢谢

您好，这个是私有算法，目前暂不开放。目前开源的算法模型库可参考[model_zoo.md](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/model_zoo.md). 此外，你也可以根据自己的业务场景部署自定义的算法模型。
