### ISSUE TITLE
可否对原HBB框进行旋转，直接将标注转化为OBB框。

### ISSUE THREAD

**Issue by QiuChenFeng** [CVHub520/X-AnyLabeling#267]
目前进行的检测任务采用了HBB框， 后续将转为OBB检测；希望X-AnyLabeling可以提出【可旋转HBB，将其转化为OBB】这个功能。这样的好处在于：
当我进行HBB任务想转化为OBB任务时，在标注的过程中除了可以借鉴原标签、更大的好处是 在无标签的情况下，可以在原训练好的HBB下的模型进行预标注，加速OBB模型开发

**Comment by CVHub520** [comment]
> 目前进行的检测任务采用了HBB框， 后续将转为OBB检测；希望X-AnyLabeling可以提出【可旋转HBB，将其转化为OBB】这个功能。这样的好处在于： 当我进行HBB任务想转化为OBB任务时，在标注的过程中除了可以借鉴原标签、更大的好处是 在无标签的情况下，可以在原训练好的HBB下的模型进行预标注，加速OBB模型开发

您好，感谢关注。目前该功能已支持，可拉取最新源码，加载图像，点击上面菜单栏->"工具"(Tool)->"Convert HBB to OBB"即可一键转换。
