### ISSUE TITLE
【多目标跟踪】是否支持指定目标进行跟踪？只跟踪指定目标

### ISSUE THREAD

**Issue by firelgh** [CVHub520/X-AnyLabeling#268]

**Comment by CVHub520** [comment]
您好，目前提供的MOT便是对指定目标进行跟踪，具体可参考该[配置文件](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov5m_bytetrack.yaml)，关键是设置`filter_classes`参数。

**Comment by firelgh** [comment]
> 您好，目前提供的MOT便是对指定目标进行跟踪，具体可参考该[配置文件](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov5m_bytetrack.yaml)，关键是设置`filter_classes`参数。
好的，多谢!
那是否支持手动选择标记待跟踪目标呢？即该待跟踪目标类别，不在配置文件的类别内

**Comment by CVHub520** [comment]
> > 您好，目前提供的MOT便是对指定目标进行跟踪，具体可参考该[配置文件](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov5m_bytetrack.yaml)，关键是设置`filter_classes`参数。
> > 好的，多谢!
> > 那是否支持手动选择标记待跟踪目标呢？即该待跟踪目标类别，不在配置文件的类别内

此类功能暂未支持。

**Comment by firelgh** [comment]
Ok ， thanks



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月26日 13:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [CVHub520/X-AnyLabeling] 【多目标跟踪】是否支持指定目标进行跟踪？只跟踪指定目标 (Issue #268) |

您好，目前提供的MOT便是对指定目标进行跟踪，具体可参考该配置文件，关键是设置filter_classes参数。
好的，多谢!
那是否支持手动选择标记待跟踪目标呢？即该待跟踪目标类别，不在配置文件的类别内

此类功能暂未支持。
