### ISSUE TITLE
【功能需求】是否能支持SAM分割一整张图片中的所有目标，再转换成多边形，多选，修改标签

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#269]
不用了多选，可以用x-anylabeling的快速标签纠正功能，不过这个功能，目前只支持矩形框

**Comment by CVHub520** [comment]
> 不用了多选，可以用x-anylabeling的快速标签纠正功能，不过这个功能，目前只支持矩形框

您好，修改标签请使用”标签管理“功能，可支持任意的`shape_type`.

**Comment by aiyou9** [comment]
嗯嗯，那能支持，sam的分割整张图里所有对象吗？

**Comment by CVHub520** [comment]
该功能使用频率过低，暂不考虑支持，如有需要可自信下载源码进行二次开发。
