### ISSUE TITLE
可否利用nvidia triton，把模型推理放在远端服务器中运行，提高标注速度

### ISSUE THREAD

**Issue by talebolano** [CVHub520/X-AnyLabeling#270]
目前进行的预标注任务使用本地cpu和gpu，如能使用triton远端部署模型，可加快标注速度

**Comment by CVHub520** [comment]
理论上问题不大，可以将推理后端切换下试试，具体可定位到[这里](https://github.com/CVHub520/X-AnyLabeling/tree/main/anylabeling/services/auto_labeling/engines)。
