### ISSUE TITLE
【bug】UnboundLocalError: local variable 'rect' referenced before assignment

### ISSUE THREAD

**Issue by LWQ2EDU** [CVHub520/X-AnyLabeling#271]
使用Windows-CPU版进行标注时，导入百度网盘下载的yolov8n-pose.onnx模型进行预标注，运行时报错`UnboundLocalError: local variable 'rect' referenced before assignment`

完整报错信息：
```bash
(anylabel) E:\X-AnyLabeling>python anylabeling/app.py
Traceback (most recent call last):
  File "E:\X-AnyLabeling\.\anylabeling\views\labeling\widgets\canvas.py", line 1034, in paintEvent
    cx = rect.x() + rect.width() / 2
UnboundLocalError: local variable 'rect' referenced before assignment
```

**Comment by LWQ2EDU** [comment]
看了一下，标注文件已经生成了，应该是解析显示的地方有问题
[test.json](https://github.com/CVHub520/X-AnyLabeling/files/14399313/test.json)

**Comment by CVHub520** [comment]
> 看了一下，标注文件已经生成了，应该是解析显示的地方有问题 [test.json](https://github.com/CVHub520/X-AnyLabeling/files/14399313/test.json)

感谢反馈，已修复，可先下载源码使用，GUI等后续版本一起更新。
