### ISSUE TITLE
【功能需求】加载数据集标注时提供进度展示

### ISSUE THREAD

**Issue by lartpang** [CVHub520/X-AnyLabeling#279]
因为我使用的功能涉及到了Mask，实际相关代码在这里：

https://github.com/CVHub520/X-AnyLabeling/blob/102bc9f0ccbfa120e85b3ea62c82b9207498190f/anylabeling/views/labeling/label_widget.py#L3571-L3586

由于Mask读取较慢，大量数据导入时这里会阻塞界面，或许提供一个进度条会更好？

**Comment by CVHub520** [comment]
> 因为我使用的功能涉及到了Mask，实际相关代码在这里：
> 
> https://github.com/CVHub520/X-AnyLabeling/blob/102bc9f0ccbfa120e85b3ea62c82b9207498190f/anylabeling/views/labeling/label_widget.py#L3571-L3586
> 
> 由于Mask读取较慢，大量数据导入时这里会阻塞界面，或许提供一个进度条会更好？

已支持，请拉取最新源码尝试。
