### ISSUE TITLE
从源码如何启动X-anylabeling

### ISSUE THREAD

**Issue by chen960** [CVHub520/X-AnyLabeling#280]
我follow官方文档，最后python anylabeling/app.py启动的是anylabeling
![image](https://github.com/CVHub520/X-AnyLabeling/assets/35607059/a19920b2-43d4-488c-b943-21242ea496f5)

**Comment by chen960** [comment]
解决了，同个虚拟环境中之前安装了anylabeling，可能有一些冲突导致的，卸载anylabeling就好了

**Comment by CVHub520** [comment]
> 解决了，同个虚拟环境中之前安装了anylabeling，可能有一些冲突导致的，卸载anylabeling就好了

感谢反馈 :)
