### ISSUE TITLE
Auto run: ‘invalid model type, please choose a valid model-type to run.’ 

### ISSUE THREAD

**Issue by mella2023** [CVHub520/X-AnyLabeling#281]
When I choose a model, it shows ‘model loaded.Ready for labeling.’ But I click ‘auto run’ and it turns into ‘invalid model type, please choose a valid model-type to run.’ 
I resized dataset images as 256x256 to fit the model, and loaded the SAM-MED2D as a custom model according to this article(https://github.com/CVHub520/X-AnyLabeling/issues/23)
<img width="960" alt="error" src="https://github.com/CVHub520/X-AnyLabeling/assets/125442252/07af9995-a83e-4ad8-902a-c8ed456d51cc">
<img width="1042" alt="error1" src="https://github.com/CVHub520/X-AnyLabeling/assets/125442252/50858f60-f977-466d-8fc8-64156171f6ff">
<img width="1440" alt="error3" src="https://github.com/CVHub520/X-AnyLabeling/assets/125442252/f47a589a-994c-4092-8ab2-06b67fb8a022">
, it still doesn’t work. Anyone knows how to solve this?

**Comment by CVHub520** [comment]
Hi, @mella2023:

Please remove the key `engine`. The current model sam-med2d does not have support in the DNN backend.

**Comment by mella2023** [comment]
> Hi, @mella2023:
> 
> Please remove the key `engine`. The current model sam-med2d does not have support in the DNN backend.

Hi，I removed the key engine and it still shows ‘invalid model type, please choose a valid model-type to run’. I also tried Depth Anything (ViT-Base), SAM-HQ (ViT-Base) and YOLOv5s-Seg Ultralytics, none of them work.

**Comment by HonestyBrave** [comment]
yes，i meet the same question
我也遇到了相同问题，模型加载对了，但是运行自动标注按钮，就报报无效的模型
![image](https://github.com/CVHub520/X-AnyLabeling/assets/16200506/d6c2ff5e-94e8-4eda-88d3-1c501bda9a4f)

![image](https://github.com/CVHub520/X-AnyLabeling/assets/16200506/2b42305f-9cfc-42b6-bc4d-e462be47409d)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/16200506/792e467a-26f3-431b-87ce-134afca8a84a)

**Comment by CVHub520** [comment]
> yes，i meet the same question 我也遇到了相同问题，模型加载对了，但是运行自动标注按钮，就报报无效的模型 ![image](https://private-user-images.githubusercontent.com/16200506/309169323-d6c2ff5e-94e8-4eda-88d3-1c501bda9a4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTY0OTgsIm5iZiI6MTcwOTUxNjE5OCwicGF0aCI6Ii8xNjIwMDUwNi8zMDkxNjkzMjMtZDZjMmZmNWUtOTRlOC00ZWRhLTg4ZDMtMWM1MDFiZGE5YTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAxMzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMDMxNTk1NzRiYjAzZTM1NDM4OGFjOTNmYTRmZWZmOTAwOTZlZGFkNTQ3MTEzYWQwYzZlYjc5MzdmMzVlZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dKsurpkK59o6AThqsZn7xSwhzPLOdO-gODg7ZkPUIxc)
> 
> ![image](https://private-user-images.githubusercontent.com/16200506/309169262-2b42305f-9cfc-42b6-bc4d-e462be47409d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTY0OTgsIm5iZiI6MTcwOTUxNjE5OCwicGF0aCI6Ii8xNjIwMDUwNi8zMDkxNjkyNjItMmI0MjMwNWYtOWNmYy00MmI2LWJjNGQtZTQ2MmJlNDc0MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAxMzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZDM2M2M1YzQ3NDFhNzQxZjhhZWJkZWVmYTlhOTY1ZGM3N2MxNzcxZTI5YTY0MDEzNTAxYmVkOTFhZThjZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FkKOeSfvxWm3N5HCNRdjQ8SKxPe9a81JX4a3V5gP8Zw) ![image](https://private-user-images.githubusercontent.com/16200506/309169421-792e467a-26f3-431b-87ce-134afca8a84a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTY0OTgsIm5iZiI6MTcwOTUxNjE5OCwicGF0aCI6Ii8xNjIwMDUwNi8zMDkxNjk0MjEtNzkyZTQ2N2EtMjZmMy00MzFiLTg3Y2UtMTM0YWZjYThhODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAxMzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4OWY3ODhjODQzOGQxYTUxMWEwNTY3Y2YxMzAyY2RhMDUwODZhMWYxZGNhMDljMDVhZTc5YjU0NTU2MGM1MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TDhNJpyxReKGaMXZoPEzZMaz3-JnUBE25_ULK3mgeNU)

请问下你这边是基于源码运行的吗？

**Comment by CVHub520** [comment]
Hello @HonestyBrave and @mella2023,

Please note that this isn't a bug. When using the SAM series models, you should follow the guide available at [user_guide-ZH](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#sam-%E7%B3%BB%E5%88%97%E6%A8%A1%E5%9E%8B) or [user_guide-EN](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md#sam-series-models). 

Please refrain from using the `Auto run` button in the left menu as this function does not support SAM-like models that require prompts.
