### ISSUE TITLE
初始按钮无效与标签概率展示

### ISSUE THREAD

**Issue by Leshntan** [CVHub520/X-AnyLabeling#283]
# 说明
我刚入手尝试X-AnyLabeling，加上本人水准不高，遇到了三块问题，在这里希望能得到解惑
## 1. 初始化
我在页面初始化后第一次点击无论什么按钮总是无效，有些时候不知道是卡还是什么别的问题，可能点击无效的次数会更多一点，不清楚是打开后还没完全加载的问题还是别的影响。
## 2. 标签与概率
在label-studio使用时，我用目标检测的打标，可以在打标的框上选择展示标签名，如果是使用ml_backend预测的，还能展示这些标签的概率，但是在这里我似乎并没有找到相应的设置。虽然在图片右边是有所有标签名的，但是不能在对应的目标上快速看到对应标签名，在纠错时的效率大大降低。这里我不清楚是我没有找到设置还是暂时还没有这一块内容。
## 3. 导出格式
我需要的是YOLO的txt格式，但我注意到自动保存依旧是先保存JSON，再需要手动点击导出，才能在文件夹下多出txt的部分。或许实现方法就是通过读取json实现转换，但是这在一方面增加了空间的占比，另一方面我需要设置文件夹类型分组才能快速找到对应的txt集。所以我希望能够之后设置为哪个格式就直接自动保存是哪种类型。当然这部分没太大影响，算是次要的问题或是建议

**Comment by CVHub520** [comment]
@Leshntan ，HI：
1. 初始化是怕误触，第一次是无效的，后面不会；
2. 因为考虑到目标一多的话展示标签名，或者加score，界面很凌乱，后面可以考虑加个勾选让用户自行选择；目前你可以将鼠标悬停到目标框上，会显示对应目标的标签；
3. 您好，转yolo只是你的个人需求，还有很多其它格式要支持，因此需要定义一个统一的格式，然后标注完成后用户再根据自身需求导出需要的标签即可；另外这个标签文件属于文本信息，所占的存储空间可以忽略不记。
txt或者其它格式都会默认保存再跟图片文件夹或标签文件夹的同级根目录下。
---
最后，目前代码是开源的，关于你提到的这些小功能完全可以自行修改下，这个不涉及到复杂的算法或者逻辑，可以尝试下。

**Comment by Leshntan** [comment]
好的感谢
