### ISSUE TITLE
圆形绘制无法导出YOLO格式数据

### ISSUE THREAD

**Issue by lilian132** [CVHub520/X-AnyLabeling#284]
经测试，圆形绘制无法导出YOLO格式数据，但是矩形和多边形可以，工具版本: "2.3.2"。

**Comment by CVHub520** [comment]
> 经测试，圆形绘制无法导出YOLO格式数据，但是矩形和多边形可以，工具版本: "2.3.2"。

您好，目前YOLO好像还不支持圆形检测吧？
