### ISSUE TITLE
【功能需求】当前分支，支持摁住ctrl键，鼠标划过标注，选中，但是右击，没有编辑所有选中标注标签的功能，希望能支持

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#286]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/8510230d-abb1-4316-af16-3fbf45696f1d)

**Comment by aiyou9** [comment]
这样，可以增强自动标注后，用户深度修改标注的标签

**Comment by CVHub520** [comment]
考虑到不同shape_type和group_id等字段可能导致的冲突，此功能暂不考虑开发。

**Comment by aiyou9** [comment]
最好多选这个，从ctrl 改成shift，在crtl+鼠标滚轮，缩放时，会容易多选，选的超出放大区域，还不知道，旋转框时一起旋转，还不知道

**Comment by aiyou9** [comment]
> 最好多选这个，从ctrl 改成shift，在crtl+鼠标滚轮，缩放时，会容易多选，选的超出放大区域，还不知道，旋转框时一起旋转，还不知道
