### ISSUE TITLE
Video makes empty directory 

### ISSUE THREAD

**Issue by Valengou** [CVHub520/X-AnyLabeling#288]
Hi, when I open a video I want to tag, it process it but generates an empty directory without the frames. Do you know what could be the issue? I'm running it directly from the .exe GUIs you've provided ñ.

**Comment by CVHub520** [comment]
Hello, @Valengou:

There could be multiple reasons for the issue you're facing. Here are a couple of possible solutions you could try:

1. Try using an official test video file to see if it can be properly parsed and loaded. This could help rule out any issues with the file itself.
2. Try running the application from source code. This could provide more detailed error information, which will help in further troubleshooting.

If you continue to experience difficulties, please feel free to reach out for further assistance.

Best regards,
CVHub

**Comment by 202112213501021** [comment]
> 嗨，当我打开要标记的视频时，它会处理它，但会生成一个没有帧的空目录。你知道问题出在哪里吗？我直接从您提供的.exe GUI 运行它 ñ。

你好，请问为什么我打不开视频文件

**Comment by 202112213501021** [comment]
> 您好， ：
> 
> 您面临的问题可能有多种原因。以下是您可以尝试的几种可能的解决方案：
> 
> 1. 尝试使用官方测试[视频文件](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/demo_video.mp4)，看看是否可以正确解析和加载。这有助于排除文件本身的任何问题。
> 2. 尝试从源代码运行应用程序。这可以提供更详细的错误信息，这将有助于进一步的故障排除。
> 
> 如果您仍然遇到困难，请随时联系我们寻求进一步的帮助。
> 
> 最好的问候，CVHub

你好，我为什么打不开视频文件，我用的是源码，并且是最新版的
