### ISSUE TITLE
导入dota类型标签进行修改时，进行旋转框的大小修改时会直接将旋转框置为水平，大大增加微调时间

### ISSUE THREAD

**Issue by goodfishboy** [CVHub520/X-AnyLabeling#289]
导入dota类型标签进行修改时，进行旋转框的大小修改时会直接将旋转框置为水平，大大增加微调时间

**Comment by CVHub520** [comment]
> 导入dota类型标签进行修改时，进行旋转框的大小修改时会直接将旋转框置为水平，大大增加微调时间

已修复，请更新源码。
