### ISSUE TITLE
导入yolov8-obb标签就行修改时，修改时的框并非旋转矩形框

### ISSUE THREAD

**Issue by goodfishboy** [CVHub520/X-AnyLabeling#290]
导入yolov8-obb标签就行修改时，修改时的框并非旋转矩形框，而是多边形框

**Comment by CVHub520** [comment]
@goodfishboy, 您好，已支持yolov8-obb标签转自定义标签，请更新源码尝试。
![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/5f7decc4-a0c8-4895-952c-e939bb643b40)
