### ISSUE TITLE
使用下载的最新版本,加载自定义模型,识别精度很低，服务器上预测成功的图片，在本地自动打标一个也打不上

### ISSUE THREAD

**Issue by phphappy** [CVHub520/X-AnyLabeling#291]
服务器上预测标注很准，
使用如下命令导出模型， yolo export model=best.pt format=onnx
配置自定义模型打标，一个也打不上。麻烦老师给看一下！
具体配置如下：
type: yolov8
name: inv-yolov8
display_name: inv-yolov8 (inv-yolov8)
model_path: best.onnx
input_width: 640
input_height: 640
num_masks: 32
score_threshold: 0.3
nms_threshold: 0.45
confidence_threshold: 0.25
classes:
  - inv_code
  - inv_no
  - inv_date
  - chk_code
  - buyer_name
  - buyer_tax_no
  - seller_name
  - seller_tax_no
  - un_tax_amt

![微信截图_20240304181510](https://github.com/CVHub520/X-AnyLabeling/assets/2278180/50043991-4a35-4f6c-861f-d6c6dbdc8edc)

![微信图片_20240304181654](https://github.com/CVHub520/X-AnyLabeling/assets/2278180/406e4d6d-10fa-4aab-b0c8-1a3c02576f09)

链接：https://pan.baidu.com/s/1ZDyCis3d-DANbvKvTJEoiA 
提取码：xzt6

**Comment by CVHub520** [comment]
@phphappy ，您好，`det` 任务请移除 `num_masks` 参数。

**Comment by phphappy** [comment]
看了别的Issues才加的num_masks 参数，不加之前也不行。之前的配置是这样的：
type: yolov8
name: inv-yolov8
display_name: inv-yolov8 (inv-yolov8)
model_path: best.onnx
input_width: 640
input_height: 640
nms_threshold: 0.45
confidence_threshold: 0.25
classes:
  - inv_code
  - inv_no
  - inv_date
  - chk_code
  - buyer_name
  - buyer_tax_no
  - seller_name
  - seller_tax_no
  - un_tax_amt

**Comment by phphappy** [comment]
本地直接使用导出的onnx模型做预测，也没有什么问题
![1709606461016](https://github.com/CVHub520/X-AnyLabeling/assets/2278180/5aa41168-0364-4652-93d5-937bacb17bcd)

**Comment by CVHub520** [comment]
> 本地直接使用导出的onnx模型做预测，也没有什么问题 ![1709606461016](https://private-user-images.githubusercontent.com/2278180/309964478-5aa41168-0364-4652-93d5-937bacb17bcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTk0NzIsIm5iZiI6MTcwOTYxOTE3MiwicGF0aCI6Ii8yMjc4MTgwLzMwOTk2NDQ3OC01YWE0MTE2OC0wMzY0LTQ2NTItOTNkNS05MzdiYWNiMTdiY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDYxMjUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Q4N2ZmZDljNzk5MzlhNjU1NDBmYTBmMzcxNWEzNWM4ZmE4MmUwNzk0YTFiYTBiNjRkOGIxZmE0MjBiNDdhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kQFYgzBHKqsifDyMjBe_KcnLKJAhsNNVDtzecimvusY)

麻烦将pt文件和确保能得到目标框的测试图片一起打个压缩包发到邮箱我这边查看下。

**Comment by phphappy** [comment]
> 麻烦将pt文件和确保能得到目标框的测试图片一起打个压缩包发到邮箱我这边查看下。

已经将邮件发送至：cv_hub@163.com

**Comment by CVHub520** [comment]
您好，这边看了下你的图片存在异常，请参考 #216 检查并修正您的数据集。

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/86305c1b-1199-42e3-9622-427f2b8a8e5a)

**Comment by phphappy** [comment]
> 您好，这边看了下你的图片存在异常，请参考 #216 检查并修正您的数据集。
> 
> ![image](https://private-user-images.githubusercontent.com/72010077/310022407-86305c1b-1199-42e3-9622-427f2b8a8e5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTMyMDMsIm5iZiI6MTcwOTY5MjkwMywicGF0aCI6Ii83MjAxMDA3Ny8zMTAwMjI0MDctODYzMDVjMWItMTE5OS00MmUzLTk2MjItNDI3ZjJiOGE4ZTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAyNDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZGM0NjFlNmIxMDkyYmZhNjhmOTMwYzI4NTE1MGFmZjMyNWQ3YzY1ZmMyMTFlZjE5NGUzOTdkYjU3MTlmNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eCjaGSHl6INmKQ3zbRWOtjADWl6s4vugqz6eD-eYHnc)
老师，图片有异常？异常的话yolo8才会检测不出来的

**Comment by phphappy** [comment]
> > 您好，这边看了下你的图片存在异常，请参考 #216 检查并修正您的数据集。
> > ![image](https://private-user-images.githubusercontent.com/72010077/310022407-86305c1b-1199-42e3-9622-427f2b8a8e5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTMyMDMsIm5iZiI6MTcwOTY5MjkwMywicGF0aCI6Ii83MjAxMDA3Ny8zMTAwMjI0MDctODYzMDVjMWItMTE5OS00MmUzLTk2MjItNDI3ZjJiOGE4ZTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAyNDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZGM0NjFlNmIxMDkyYmZhNjhmOTMwYzI4NTE1MGFmZjMyNWQ3YzY1ZmMyMTFlZjE5NGUzOTdkYjU3MTlmNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eCjaGSHl6INmKQ3zbRWOtjADWl6s4vugqz6eD-eYHnc)
> > 老师，图片有异常？异常的话yolo8才会检测不出来的

能说一下，您做了哪些改动吗？

**Comment by CVHub520** [comment]
> #216

您好，原理可参考图像的 EXIF 相关信息，这个网上挺多的，比如[这个](https://developer.qiniu.com/dora/kb/1560/information-about-photo-exif-rotation-parameters-in-the-understanding-of-orientation?category=kb)。

所以虽然你人眼看起来图片是正常的，但其实内部的数值矩阵是被旋转过的，因此您需要根据图像内置的 EXIF 信息去纠正，具体的方法你可以参考 #216。
