### ISSUE TITLE
【BUG】当前最新版本，旋转框标注，闪退，报错

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#292]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/1d5c83af-7236-4499-b6ce-62b5e5de9541)

**Comment by CVHub520** [comment]
您好，请问是基于最新源码运行的还是？另外请把复现步骤简单说明下，这边测试发现旋转框创建、操作、删除等功能是正常的。

**Comment by CVHub520** [comment]
Closing the issue for now. Should the problem persist, please feel free to reopen the issue.
