### ISSUE TITLE
windows的两个版本的运行yolov8 pose模型，闪退

### ISSUE THREAD

**Issue by zxkke** [CVHub520/X-AnyLabeling#293]
另外 矩形标注里面添加点标签，导出yolo标签，点标签不会导出来

**Comment by zxkke** [comment]
运行yolov8 pose模型生成json之后闪退，再次打开该文件夹，程序也会闪退，只有把那个json文件删除，才能再次打开那个文件夹

**Comment by CVHub520** [comment]
您好，请参考#271，目前 GUI 版本有点问题，新版本还在测试当中，可先下载源码运行。
