### ISSUE TITLE
Exe file seen as virus

### ISSUE THREAD

**Issue by Valengou** [CVHub520/X-AnyLabeling#294]
Hi I've made some changes to your code  to add some features and when i distrute the .exe file to other users windows sees it as a virus,

Do you know what could be done to solve this?

I've used pyinstaller --noconfirm anylabeling-win-cpu.spec

**Comment by CVHub520** [comment]
Hi, @Valengou:

I'm sorry to hear about that, but I haven't encountered this issue before. 

Perhaps you could try temporarily disabling your antivirus and firewall? And then follow the given steps to compile. This might help to determine if the antivirus software is causing the false positive detection.
