### ISSUE TITLE
软件闪退

### ISSUE THREAD

**Issue by f549263766** [CVHub520/X-AnyLabeling#295]
情况1：运行模型自动标注后，选择矩形框模型手动标注，此时软件闪退；
情况2：重新打开软件，定位到已标注的文件，此时软件闪退；
情况3：自动标注后，点击总览，此时软件闪退。

**Comment by CVHub520** [comment]
> 情况1：运行模型自动标注后，选择矩形框模型手动标注，此时软件闪退； 情况2：重新打开软件，定位到已标注的文件，此时软件闪退； 情况3：自动标注后，点击总览，此时软件闪退。

您好，请提供具体的报错的信息，这样描述过于笼统，建议源码运行下定位下具体的原因。

**Comment by f549263766** [comment]
> > 情况1：运行模型自动标注后，选择矩形框模型手动标注，此时软件闪退； 情况2：重新打开软件，定位到已标注的文件，此时软件闪退； 情况3：自动标注后，点击总览，此时软件闪退。
> 
> 您好，请提供具体的报错的信息，这样描述过于笼统，建议源码运行下定位下具体的原因。

源码运行，定位到canvas.py中fillRect传入了float类型的数据
![image](https://github.com/CVHub520/X-AnyLabeling/assets/44324039/49280edd-c717-4e1f-a01d-e70a21a46124)

**Comment by CVHub520** [comment]
看样子貌似是你加载其它的标签文件有问题。你可以随便找几张新的图片，标注运行下试试。

**Comment by f549263766** [comment]
> 看样子貌似是你加载其它的标签文件有问题。你可以随便找几张新的图片，标注运行下试试。

并不是，新建文件夹，放入新图像，无标签文件，点击矩形框标注，随后闪退，报错同上。

**Comment by CVHub520** [comment]
这个错误可能与 PyQt5 在 Windows 上的特定版本或配置有关。在某些情况下，Qt 在 Windows 上可能对坐标值有严格的要求，可能不允许使用浮点数。

这边修复了下，你可以更新下源码重新运行下试试。

**Comment by f549263766** [comment]
已成功运行，感谢~

**Comment by richiy** [comment]
你好，我这里源码运行时也有闪退问题，重现步骤：
1、选择自动标注
2、下载指定模型A
3、关闭程序后再重启
4、再次选择自动标注，此时左上方模型列表那里显示没有模型
5、重新选择模型A，提示下载，但过1-2s闪退，控制台没有报错信息

版本信息：
PyQt5                          5.15.7
onnxruntime-gpu       1.20.0
torch                          2.5.1+cu121

**Comment by CVHub520** [comment]
> 你好，我这里源码运行时也有闪退问题，重现步骤： 1、选择自动标注 2、下载指定模型A 3、关闭程序后再重启 4、再次选择自动标注，此时左上方模型列表那里显示没有模型 5、重新选择模型A，提示下载，但过1-2s闪退，控制台没有报错信息
> 
> 版本信息： PyQt5 5.15.7 onnxruntime-gpu 1.20.0 torch 2.5.1+cu121

Why is there still a torch environment here? Please pull the latest source code first and create a clean environment for installation according to the tutorial.
