### ISSUE TITLE
功能待优化

### ISSUE THREAD

**Issue by HePengguang** [CVHub520/X-AnyLabeling#296]
利用SAM自动编注，加减点目前只能手动操作，最好改成鼠标左边++，右键--。

**Comment by CVHub520** [comment]
> 利用SAM自动编注，加减点目前只能手动操作，最好改成鼠标左边++，右键--。

目前加减点可以通过快捷键 `Q `和 `E` 进行快速切换，鼠标负责提供 `prompt`。
