### ISSUE TITLE
功能建议以及个别功能不知道啥意思

### ISSUE THREAD

**Issue by eastDongD** [CVHub520/X-AnyLabeling#297]
- 建议添加使用上一张图片标注结果的功能。
- `保留先前的注释`  功能不知道什么意思

**Comment by CVHub520** [comment]
@eastDongD ，您好，`保留先前的注释` 就是自动使用上一张图片标注的结果。

**Comment by eastDongD** [comment]
我打开这个功能后，从A图片切换到B图片，B图片没有A图片的标注结果（B图片已经被提前标注过一次）（我是用代码跑出voc结果后，用的旧版本的voc转custom代码标注的，两个custom的格式好像不一样，但是也能看）
