### ISSUE TITLE
yolov8-seg使用自定义模型，自动标注没有效果

### ISSUE THREAD

**Issue by atpalain** [CVHub520/X-AnyLabeling#298]
onnx和yaml文件放在同一目录下，加载模型也成功，但是点击自动标注的运行按钮什么都检测不出来。
yaml文件如下：
`type: yolov8
name: yolov8m-seg-r20230620
display_name: FlangeDefectNew
model_path: best.onnx
nms_threshold: 0.45
confidence_threshold: 0.3
classes:
  - dirty
  - dent mark
  - yellow mark
  - scratch`

**Comment by atpalain** [comment]
待标注图片为8位图像，尺寸位640*640，首先确认一下yaml是否编写正确：
type: yolov8
name: yolov8m-seg-r20230620
display_name: FlangeDefectNew
model_path: best.onnx
nms_threshold: 0.45
confidence_threshold: 0.3
classes:
  - dirty
  - dent mark
  - yellow mark
  - scratch

**Comment by atpalain** [comment]
![2024-03-08 10 53 52](https://github.com/CVHub520/X-AnyLabeling/assets/54426593/8fc1e2d0-2220-4007-b475-718bec966100)

**Comment by atpalain** [comment]
> 您好，@atpalain:
> 
> 根据提供的信息，`type` 字段似乎设置错误，默认为检测模型，分割模型可以改为：`type: yolov8_seg` 再重新尝试下。

感谢，按照你说的修改，就可以了。

修改之后的文件如下：
type: yolov8_seg
name: yolov8m-seg-r20230620
display_name: FlangeDefect (yolov8m-seg)
model_path: best.onnx
input_width: 640
input_height: 640
nms_threshold: 0.45
confidence_threshold: 0.3
classes:
  - dirty
  - dent mark
  - yellow mark
  - scratch

**Comment by CVHub520** [comment]
Congratulations! I'm glad to hear that. 

If you encounter any issues, please don't hesitate to contact me!

**Comment by atpalain** [comment]
大概找到原因了，不选择输出目录就不会出现这个错误，换句话说就是待标注图片跟生成的json文件在同一目录下就能正常运行。个人感觉不太合理，请问是不是哪里操作出问题了呢？

**Comment by dahaigui** [comment]
> > 您好，@atpalain:
> > 根据提供的信息，`type` 字段似乎设置错误，默认为检测模型，分割模型可以改为：`type: yolov8_seg` 再重新尝试下。
> 
> 感谢，按照你说的修改，就可以了。
> 
> 修改之后的文件如下： type: yolov8_seg name: yolov8m-seg-r20230620 display_name: FlangeDefect (yolov8m-seg) model_path: best.onnx input_width: 640 input_height: 640 nms_threshold: 0.45 confidence_threshold: 0.3 classes:
> 
> * dirty
> * dent mark
> * yellow mark
> * scratch

我按照你这种方法做了一个修改了我的yaml文件，但是还是识别不出来，具体的yaml文件如下：
![image](https://github.com/CVHub520/X-AnyLabeling/assets/47802187/d176f76c-f077-42d3-abc7-9759ca551a42)
不知道我和你的yaml文件的区别在哪，导致我这个无法识别。
