### ISSUE TITLE
一次性全部标注

### ISSUE THREAD

**Issue by ou525** [CVHub520/X-AnyLabeling#3]
非常感谢分享，现在导入模型后，只能单帧进行标注，是否可增添一次性全部生成选项

**Comment by CVHub520** [comment]
> 非常感谢分享，现在导入模型后，只能单帧进行标注，是否可增添一次性全部生成选项

您好，这个需求目前来看意义不是很大。当前你可以通过快捷键 i 一键自动标注（非 SAM-based 模型），由于最终还是需要人工再检查一遍，所以到头来还是要一帧帧过。

**Comment by ou525** [comment]
一帧一帧过是应该的，不过每次都需要点一次就费劲了(几千次点击起码)，只是建议。

**Comment by aiyou9** [comment]
嵌入ov-seg，可以对图片中一类目标，使用text prompt 进行安类别，多轮分割，把所有目标分割出来

为anylabeling创建 ONNX  https://github.com/facebookresearch/ov-seg/issues/11
加载ov-seg分割 模型  https://github.com/vietanhdev/anylabeling/issues/89

![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/75a4f6b8-3ff9-4691-b90a-14c925efe607)

**Comment by aiyou9** [comment]
https://github.com/gradient-ai/AutoYOLO

https://blog.paperspace.com/autoyolo/

**Comment by aiyou9** [comment]
一次性批量标注单一目标，https://github.com/gyhdc/LabelSAM-for-yolo

**Comment by aiyou9** [comment]
后面可以等等 fastsam https://github.com/CASIA-IVA-Lab/FastSAM ，他们也要做标注功能

**Comment by Answergeng** [comment]
> 
确实需要这个功能

**Comment by aiyou9** [comment]
> 
他们提供了微调代码，大佬，看看能不能转换模型，到x-anylabeling 中调用，希望可以形成循环标注
https://github.com/facebookresearch/ov-seg/blob/main/open_clip_training/README.md

**Comment by aiyou9** [comment]
Yolo NAS 对象检测，提示 SAM，进行分割
https://github.com/RATHOD-SHUBHAM/SegmentAnything

**Comment by CVHub520** [comment]
> Yolo NAS 对象检测，提示 SAM，进行分割 https://github.com/RATHOD-SHUBHAM/SegmentAnything
> 
> how_to_use_yolo8v_with_sam https://github.com/RATHOD-SHUBHAM/SegmentAnything/blob/master/how_to_use_yolo8v_with_sam.ipynb

您好， @aiyou9 ，yolo-sam功能已支持，请更新版本。

**Comment by aiyou9** [comment]
> > Yolo NAS 对象检测，提示 SAM，进行分割 https://github.com/RATHOD-SHUBHAM/SegmentAnything
> > how_to_use_yolo8v_with_sam https://github.com/RATHOD-SHUBHAM/SegmentAnything/blob/master/how_to_use_yolo8v_with_sam.ipynb
> 
> 您好， @aiyou9 ，yolo-sam功能已支持，请更新版本。

已经测试，很香

**Comment by CVHub520** [comment]
您好， @ou525 @Answergeng  “运行全部”功能已支持，可重新更新源码，导入图片，选择模型，按下快捷键：Ctrl+M尝试。
