### ISSUE TITLE
Yolo-World-L Tencent

### ISSUE THREAD

**Issue by adrianlangley** [CVHub520/X-AnyLabeling#300]
Hi,  Love the program.  I've just downloaded the 2.3.3 release and am getting an error for the above mentioned model:  
"Error in loading model: Could not download or initialize yolow model".   The other models seem to be working fine.  I get the same problem if I run the source code and change the config file.  Any ideas on why it's not working?

**Comment by CVHub520** [comment]
Hi, @adrianlangley:

I'm upload the model already, try it again later.

**Comment by adrianlangley** [comment]
Thank you so much.

Adrian.
