### ISSUE TITLE
Importing the local model failed

### ISSUE THREAD

**Issue by 202112213501021** [CVHub520/X-AnyLabeling#301]
I imported sam models according to the tutorial, and I put them (1. in a folder again) and (2. The original yaml directory) all flash back!!
![屏幕截图 2024-03-10 000558](https://github.com/CVHub520/X-AnyLabeling/assets/141103647/c4f22766-f4e8-45b7-a108-6349ad1ebc5b)

**Comment by CVHub520** [comment]
Hi, @202112213501021:

Thank you for your feedback. Can you share your config YAML file with me?

**Comment by 202112213501021** [comment]
谢谢您百忙之中给我回信，下面是详细信息：
config文件





第一种放置方法


第二种放置方法



都是闪退结束




                       
原始邮件
                       
                     

发件人："CVHub"< ***@***.*** &gt;;

发件时间：2024/3/10 13:21

收件人："CVHub520/X-AnyLabeling"< ***@***.*** &gt;;

抄送人："202112213501021"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [CVHub520/X-AnyLabeling] Importing the local model failed (Issue#301)




 
Hi, @202112213501021:
 
Thank you for your feedback. Can you share your config YAML file with me?

**Comment by CVHub520** [comment]
您好，你这边的图片貌似上传失败了，可重新上传下。

**Comment by 202112213501021** [comment]
谢谢您百忙之中给我回信，下面是详细信息：
config文件
![image](https://github.com/CVHub520/X-AnyLabeling/assets/141103647/9534c7d0-1f9d-4a9e-89d0-65a636c6b985)

第一种放置方法
![image](https://github.com/CVHub520/X-AnyLabeling/assets/141103647/c43d2592-6d44-445c-8f1a-93b7121875ef)

第二种放置方法
![image](https://github.com/CVHub520/X-AnyLabeling/assets/141103647/e355c4d7-f88d-48e1-bdf4-267a5edb6dea)

都是闪退结束
![image](https://github.com/CVHub520/X-AnyLabeling/assets/141103647/8b3ccef4-8e9a-4664-b0e5-2b55ebcfc0a4)

**Comment by CVHub520** [comment]
好的。请问这模型是从官方下载下来的，还是你的自定义模型？另外你是用 cpu 还是 gpu 推理的？最后可能是内存不足问题，要不你先试一下 edge-sam，看下能不能正常推理，来排除下这个问题。

**Comment by 202112213501021** [comment]
官方下载的；gpu 推理的；edge-sam，也不能正常推理

**Comment by CVHub520** [comment]
这个是由于 cuda 版本不兼容，这边建议您使用源码运行，edge-sam 在 cpu 版本上也可以推理得很快。另外如果您需要执行 gpu 推理的话，需要一定的环境搭建技能，具体可以把这几个[官方教程](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs/zh_cn)看一下。
