### ISSUE TITLE
功能需求：希望能有标注进度的显示

### ISSUE THREAD

**Issue by wangyang581** [CVHub520/X-AnyLabeling#305]
在标注一定数据之后，如果出现闪退情况重新加载数据，不容易找到之前标注的进度，可以参考paddlelabel在标注图片的顶部显示当前标注的图像是第几张

**Comment by CVHub520** [comment]
您好，标注进度一直都有显示的，在底部状态栏。

**Comment by wangyang581** [comment]
看到了，谢谢回复
