### ISSUE TITLE
yolov5 segmented error

### ISSUE THREAD

**Issue by 2375963934a** [CVHub520/X-AnyLabeling#306]
我将我的yolov5m-seg生成的pt文件转换成onnx格式加载模型进去并修改了yaml文件，但是运行的时候不进行标注
![image](https://github.com/CVHub520/X-AnyLabeling/assets/140362467/fd416d6d-52d7-4a9c-b489-af813579a5f4)
会卡在这里，然后就退出程序了请问该怎么解决

**Comment by CVHub520** [comment]
您好，请问源码运行下，贴下报错信息。另外请提供下您的配置文件截图以及onnx模型的输入输出节点信息。

**Comment by 2375963934a** [comment]
这是配置文件截图
![image](https://github.com/CVHub520/X-AnyLabeling/assets/140362467/a097657c-67cf-46e0-aeb3-3a7d1e8eaafd)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/140362467/963f909d-db31-4a12-b968-513f8ec4c04f)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/140362467/5fc8ea30-bf31-4354-b3f7-489f2de467e1)

**Comment by CVHub520** [comment]
您好，感谢反馈。看起来貌似是你的路径没设置对。你可以保持上述配置文件的设置，然后新建一个文件夹，将你转换好的 onnx 文件和这份配置文件放置到新建文件夹下。最后再通过界面导入自定义模型选择此配置文件即可。

**Comment by 2375963934a** [comment]
![Uploading image.png…]()
还是不会进行标注

**Comment by 2375963934a** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/140362467/04806571-f61c-4a60-9fa2-e6a98a2318ed)
显示完成推理但是没有进行标注也没有生成标签文件

**Comment by CVHub520** [comment]
请问内置的 yolov5-seg 能正常运行吗？

**Comment by 2375963934a** [comment]
![Uploading image.png…]()
内置的直接闪退了

**Comment by CVHub520** [comment]
我看你这模型还没下载成功吧？

**Comment by CVHub520** [comment]
可以把模型权重、配置文件和一张确保能推理出目标的图片打包发送至邮箱：cv_hub@163.com

**Comment by dahaigui** [comment]
我这里也遇到了类似问题，
![image](https://github.com/CVHub520/X-AnyLabeling/assets/47802187/b604869c-be4e-4317-b26e-e00a6e59c428)
用官方的代码可以实现预测。

**Comment by CVHub520** [comment]
@dahaigui，Hi，感谢反馈！
如果方便的化，麻烦将模型权重、配置文件和一张确保能推理出目标的图片打包发送至邮箱：[cv_hub@163.com](mailto:cv_hub@163.com)

**Comment by dahaigui** [comment]
> @dahaigui，Hi，感谢反馈！ 如果方便的化，麻烦将模型权重、配置文件和一张确保能推理出目标的图片打包发送至邮箱：[cv_hub@163.com](mailto:cv_hub@163.com)

已经发送到您的邮箱了，麻烦了！

**Comment by CVHub520** [comment]
> > @dahaigui，Hi，感谢反馈！ 如果方便的化，麻烦将模型权重、配置文件和一张确保能推理出目标的图片打包发送至邮箱：[cv_hub@163.com](mailto:cv_hub@163.com)
> 
> 已经发送到您的邮箱了，麻烦了！

收到，谢谢！

**Comment by 2375963934a** [comment]
请问这个问题解决了吗

**Comment by CVHub520** [comment]
> 请问这个问题解决了吗

如果方便的话，麻烦提供下模型权重、配置文件和一张服务器模型能推理出目标的图片打包发送至邮箱：[cv_hub@163.com](mailto:cv_hub@163.com) 以更好的定位问题。

**Comment by 2375963934a** [comment]
已经发送到您的邮箱了，麻烦了！

**Comment by CVHub520** [comment]
您好，麻烦在运行前仔细检查自己的配置文件与实际模型是否相符，你的标签类别信息和模型文件信息明显对应不上，请不要自己随便发挥。

```YAML
type: yolov5_seg
name: yolov5s-seg-r20231027
display_name: YOLOv5s-Seg Ultralytics
model_path: best.onnx
nms_threshold: 0.45
confidence_threshold: 0.25
classes:
  - zase
  - feibian
  - bapi
  - queliao

```

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/29bb847b-57f8-4e6e-994a-9f9be8827cd0)



![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/f1af14cc-127d-485e-b020-f24db781ce81)

**Comment by 2375963934a** [comment]
在我的电脑上运行就直接闪退了呀

**Comment by 2375963934a** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/140362467/6a7bcf43-8748-480b-97c6-f3382c14ae9c)
卡死在这然后闪退  yaml配置文件是这样子的
![image](https://github.com/CVHub520/X-AnyLabeling/assets/140362467/eba929c8-2fab-4992-a634-61b9fb345442)
没有报错直接闪退
![image](https://github.com/CVHub520/X-AnyLabeling/assets/140362467/29c108c9-13ab-4503-8410-6fa59a93510d)

**Comment by CVHub520** [comment]
@2375963934a，您好，建议使用 CPU 环境运行，有可能是 CUDA 版本不匹配。

**Comment by 2375963934a** [comment]
我的cuda是12.1的成功运行了一张图片然后就闪退了，是什么原因

**Comment by CVHub520** [comment]
> 我的cuda是12.1的成功运行了一张图片然后就闪退了，是什么原因

可以贴下具体的报错信息

**Comment by 2375963934a** [comment]
没有报错信息就是直接闪退了

**Comment by CVHub520** [comment]
> 没有报错信息就是直接闪退了

那应该就是版本没安装对，你这边如果不会配环境的话建议还是用cpu，环境搭建是比较麻烦，具体你可以查看[官方文档](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html)。
