### ISSUE TITLE
如何进行ocr标注

### ISSUE THREAD

**Issue by ywangboluo** [CVHub520/X-AnyLabeling#309]
您好，我想对文档图片中每个文本框文本进行标注，希望文本直接显示在文本框上方，我已有部分标注，希望对其进行修改，我在网上见到相关标注图片，但是没有找到如何进行标注
![Uploading ocr.png…]()

**Comment by CVHub520** [comment]
> > 可以尝试执行下内置的 [ch_ppocr_v4](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/ch_ppocr_v4.yaml) 模型推理下[样例图片](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/examples/demo_ocr.png)，观察下输出的标签文件，将您的部分标注信息组织为对应的标签样式即可。
> 
> 标注时文本是可以直接在文本框上方的吧，我看您给的这个图片只有文字内容来着；如果可以的话，导入部分标注信息是使用"Upload Attributes File"吗

不是的，你可以打开一张图片手动标注一个矩形框，选中右键点击编辑标签选项，其中标签名就是这个目标框的名称（例如再OCR里面可以取一个text），而描述字段就具体的文字内容。

正如我上面所说的，你可以先完成上述步骤，然后将这部分标签文件和您的图片文件放到同一个目录即可，不需要额外导入。

**Comment by ywangboluo** [comment]
> 可以尝试执行下内置的 [ch_ppocr_v4](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/ch_ppocr_v4.yaml) 模型推理下[样例图片](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/examples/demo_ocr.png)，观察下输出的标签文件，将您的部分标注信息组织为对应的标签样式即可。

我需要怎么输出模型的结果呢，我直接打开输出目录里的json文件，里面的imgdata是一些乱码

**Comment by CVHub520** [comment]
imgdata是base64编码，你可以通过上方菜单栏找到相关设置将其勾选掉就行。另外你需要的应该是 `description` 字段的内容，这个已经很小白化的操作了，建议随便自己找张图试标一下就清楚了。
