### ISSUE TITLE
[Question] - json file overwrited with wrong content when switch images with keyboard D / A 

### ISSUE THREAD

**Issue by airylinus** [CVHub520/X-AnyLabeling#310]
**Version:** 

2.3.0 / 2.3.3

**OS Platform**

Windows11 / exe file from github release

**What Did you do**

1. Open directory and make empty label ( no detect appear ) on images_1.jpg
2.  Switch to next image by press D
3.  Make some labels on images_2.jpg
4. Switch back to images_1.jpg by press A

**Expected result**

1. label on images_1.jpg is empty, cause we don't label anything on it;
2. there are no object in images_1.json 

**Actual result**

1. labels (one label or more) appears in images_1.jpg
2. images_1.json were updated with wrong content

**Comment by CVHub520** [comment]
Hi, @airylinus:

Thank you for providing detailed information on your issue. However, this is most likely not a bug but might result from the unintentional enabling of the feature to automatically keep the labels of the previous image (commonly used in auto-tracking or similar image target labeling scenarios).

To resolve this, you can try going to the `Edit` menu at the top and uncheck the `Keep Previous Annotation` option; or simply, you can toggle it by using the shortcut `Ctrl+P`.

If you encounter any more issues, please do not hesitate to contact me, I'll be happy to assist you further.

Best regards,
CVHub
