### ISSUE TITLE
怎么删除笔误出现的类别

### ISSUE THREAD

**Issue by heivens** [CVHub520/X-AnyLabeling#311]
![lQLPJxa4EQbfRCHNAhbNASCw66r6JS9sDf8F4Z3mHJk6AA_288_534](https://github.com/CVHub520/X-AnyLabeling/assets/52856640/557299e0-513b-4468-ad57-d03ed4dc89d9)
标注时因为手抖标了个不存在的类(452)，怎么才能在labels窗口中删除这个类呢，我以确保在已标注的类别中没有出现452这个类

**Comment by CVHub520** [comment]
您好，由于某个类通常可能会关联到多张图像，删除标签名这个选项极大概率可能会引发程序闪退，因此暂不支持此操作。

作为替代方案，你可以按下快捷键 Ctrl+G 来检查当前标注任务的统计预览信息，表格内会展示每个类别标签名的标注数量。当然，你也可以重启当前界面，会自动释放已加载标签。

**Comment by CVHub520** [comment]
最新 v3.3.1 版本以支持对误出现标签类别进行删除。（#1191 ）
