### ISSUE TITLE
导出标签文件出错

### ISSUE THREAD

**Issue by m1ngxiao** [CVHub520/X-AnyLabeling#312]
我需要导出yolo标签，选中导出—YOLO标签或者COCO标签，都报’sheep‘ is not in list
![image](https://github.com/CVHub520/X-AnyLabeling/assets/50391448/4a825bf0-527c-4e9e-bc1e-206848a4a4b1)

**Comment by CVHub520** [comment]
您好，请按照[教程](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E6%A0%87%E7%AD%BE%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA)配置你的 `classes.txt` 文件，上述错误已经提示你 sheep 类别名不存在，请添加进去。

**Comment by magic-chai** [comment]
我遇到了一样的问题，classes.txt文件里面有这个类别

**Comment by weiweiboni2** [comment]
配置了![image](https://github.com/user-attachments/assets/97ee451d-412f-44f0-ad1c-ffb0d60f0b15)
但还是出现
![image](https://github.com/user-attachments/assets/583c0094-ca3f-4906-908d-db53cdbaf0c7)

**Comment by CVHub520** [comment]
> 配置了![image](https://private-user-images.githubusercontent.com/103353067/386038071-97ee451d-412f-44f0-ad1c-ffb0d60f0b15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjI1OTIsIm5iZiI6MTczMTU2MjI5MiwicGF0aCI6Ii8xMDMzNTMwNjcvMzg2MDM4MDcxLTk3ZWU0NTFkLTQxMmYtNDRmMC1hZDFjLWZmYjBkNjBmMGIxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwNTMxMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OGEyNDA3YmY1OGM1NWY5ZTI5YmYwYjczODI3MTJjYzMzMTk0ZTUyMmNmNmQ5YWY2MzJjMTQ4YmVkYTVmNWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2PCH-_PaaaeC-R3S-IhK7I03eCcKVymu5CsXuRWXOy8) 但还是出现 ![image](https://private-user-images.githubusercontent.com/103353067/386038248-583c0094-ca3f-4906-908d-db53cdbaf0c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjI1OTIsIm5iZiI6MTczMTU2MjI5MiwicGF0aCI6Ii8xMDMzNTMwNjcvMzg2MDM4MjQ4LTU4M2MwMDk0LWNhM2YtNDkwNi05MDhkLWRiNTNjZGJhZjBjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwNTMxMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmUzNDZkMDg3ZTU1MDRhY2VjZTE2YzkxMTUyZDEwYmM5MjE3NzhlZWI4ODhlODkxNGRiZjFiY2YzZDViM2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i7SfeKxycfPL3rXcY8US6GoyybZM8yn9cZVfLZJa0JY)

检查下是否有多余的空格，另外请贴一下终端输出日志。

**Comment by weiweiboni2** [comment]
输出这个![image](https://github.com/user-attachments/assets/f5552e25-6bbd-4c8b-bebb-6cd9732b2302)
下图算是导入标签成功了吗，
![image](https://github.com/user-attachments/assets/24e2b62b-ec06-4e3a-a715-808b6ad7dcd0)
下面三张图是导入流程，打开目录时，一般会选择重新新建一个文件夹，因为如果文件夹是默认的data(图片）路径时，图三警告选yes数据会被覆盖掉，程序直接闪退
![image](https://github.com/user-attachments/assets/32133c11-9701-4264-9e6d-ffbb95bbbf26)
![image](https://github.com/user-attachments/assets/9d836dd1-8078-472a-b4bb-7e2a4126acf6)
![image](https://github.com/user-attachments/assets/324f4684-a032-425c-b915-8c3262b3ed09)

**Comment by magic-chai** [comment]
你这个标签做的有问题，要换行

**Comment by weiweiboni2** [comment]
程序闪退了之后怎么能从闪退的地方接着开始标哇

**Comment by weiweiboni2** [comment]
![image](https://github.com/user-attachments/assets/66145fa8-f044-47ff-9ba6-65bd2086e0e7)
自动保存了.json文件

**Comment by Heaven-cool** [comment]
![Image](https://github.com/user-attachments/assets/51ba36fe-ebea-4b22-9658-4883e8666917)
我在导出VOC检测框的时候报错

**Comment by Heaven-cool** [comment]
这是什么原因呀，有没有大佬知道的，帮忙解决一下
