### ISSUE TITLE
【功能需求】对不匹配 SAM 模型的输入大小的图像，进行预处理，提高检测效果

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#316]
Segment Anything 使用 1024 x 1024 像素的固定图像大小进行训练。与此大小不匹配的输入将在内部调整大小以匹配它。因此，将“Segment Anything”应用于更大的图像通常会导致较差的结果，因为它将被大幅下采样并且图像中的对象变得太小。
参考来源：
https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#tips-tricks

**Comment by CVHub520** [comment]
您好，这边只是提供一个模板，具体的模型层面的改进可根据自身需求去进行自定义开发。
