### ISSUE TITLE
【功能需求】提供一个滑块，在全选右侧列表，标注对像时，能够调整标注框中颜色的透明度，用于来回拖动几次，让眼睛视野不断移动，快速查看不匹配的标注，有利于自动标注的快速标注

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#317]
在顶部加个拖动框，或者其他快捷键+鼠标滚轮的配合，快速来回调整填充色的透明度，便于利用人的动态视力，快速筛查自动标注出错的标注框
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/f77cbd0a-ba06-4305-964e-fef8962b302e)
对框中的填充色，调整透明度，用于快速搜索，自动标注覆盖不对的标注，在标注人员的视野移动中，通过快速来回拖动填充颜色的透明度，快速筛查，自动标注的不符合的标注，进行人工校正
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/bb01e610-a9a3-4007-bf82-c8a70ebc6be3)

**Comment by CVHub520** [comment]
暂不支持。
