### ISSUE TITLE
Unable to run my custom YOLOv8-Segmentation model with this error: Error in predict_shapes: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by wafiq1211** [CVHub520/X-AnyLabeling#318]
Hello, I'm unable to run my own custom segmentation model for auto annotation that was converted from YOLOv8. I followed the command on Ultralytics website on converting to ONNX using `yolo export model=path/to/best.pt format=onnx`. What should I do? Should I try to use a different model?

**Comment by CVHub520** [comment]
Hi, @wafiq1211:

Thank you for your feedback. Perhaps you could try visualizing the ONNX model using [Netron](https://netron.app/). This way, you can observe the differences in input and output nodes between your custom model and the official one.

**Comment by wafiq1211** [comment]
Here are the input and output nodes of my custom model and the official one:
Custom model:
![Screenshot 2024-03-18 044234](https://github.com/CVHub520/X-AnyLabeling/assets/70130091/27704eee-0738-480a-9b61-a24a8cffddb6)
![Screenshot 2024-03-18 044107](https://github.com/CVHub520/X-AnyLabeling/assets/70130091/bf62c03a-0682-440a-8dc8-206a1a9f0512)

Official model:
![Screenshot 2024-03-18 044306](https://github.com/CVHub520/X-AnyLabeling/assets/70130091/2b79a8ba-2dd1-4ca9-8b06-a4b81ea5d299)
![Screenshot 2024-03-18 044131](https://github.com/CVHub520/X-AnyLabeling/assets/70130091/a70b27cd-5183-47d3-98aa-ffb9852d6f5c)

Where should I go from here? Should the input and output nodes be the same?

**Comment by CVHub520** [comment]
Sorry to bother you, could you please provide the specific information about the input and output nodes? You can click on the input nodes, and a detailed information panel will pop up on the right. Also, please provide a screenshot of your custom YAML file.

**Comment by wafiq1211** [comment]
<img width="494" alt="Screenshot 2024-03-18 at 15 12 24" src="https://github.com/CVHub520/X-AnyLabeling/assets/70130091/4b06f0fd-feb9-4391-ac62-0118b81fbd10">
<img width="502" alt="Screenshot 2024-03-18 at 15 05 34" src="https://github.com/CVHub520/X-AnyLabeling/assets/70130091/8bee5909-0416-4942-8b81-ff476395f69a">
Thanks in advance

**Comment by CVHub520** [comment]
![yolov8s-seg](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/f982555b-8270-44eb-be9e-31d077042a7b)

Thank you for providing further information!

From the visualization of the node graph, it seems that there have been some changes in the export settings of the new version of the YOLOv8 model, which we need to investigate further. 

If indeed there have been official changes, it need some time to adapt, you may have to wait for future updates.

Btw, you can modify the sourcce code if possiable.

**Comment by CVHub520** [comment]
Hi, @wafiq1211:

Based on the latest test results, there have been no changes to the ultralytics official conversion interface and input/output nodes. Please make sure you are based on the official code repository and using the correct export command. Specifically, you can refer to the following export settings:
```python
# export.py
# ultralytics-8.1.40
from ultralytics import YOLO

# Load a model
model = YOLO('/path/to/your/custom//yolov8-seg.pt')  # load a custom trained model

# Export the model
model.export(format='onnx')
```
You just need to run `python export.py`.

This issue will be temporarily closed. If you have more findings or questions in the future, feel free to reopen the discussion.

Best wishes!
