### ISSUE TITLE
載入Segmentation相關的模型時報錯

### ISSUE THREAD

**Issue by CryMasK** [CVHub520/X-AnyLabeling#32]
https://github.com/vietanhdev/anylabeling/issues/86  
  
相同的錯誤有人回報在原版的issue區，我自己遇到的情況是這樣：  
我原本裝的是CUDA 11.8跟cudnn 8.9.3，開啟原版的GPU版有成功載入onnxruntime的模型進行偵測，但才點到第三個物件，程式就崩潰。重開之後，就無法載入模型，出現該條錯誤。  
嘗試裝上正確的CUDA跟cudnn，仍然出現同樣的錯誤。  
  
改使用X-AnyLabeling，仍有同個錯誤，  
但比較特別的是，X-AnyLabeling中新增的「YOLO相關的Segmentation模型」也會出現同樣錯誤（一般YOLO模型不會）

**Comment by CVHub520** [comment]
非常抱歉，暂时未能复现出这个问题，如果可能的话，可以提供更详细的上下文信息，将具体的报错信息贴上来。
