### ISSUE TITLE
Hello author, do you have the C++code for yolov8_obb?

### ISSUE THREAD

**Issue by yxl23** [CVHub520/X-AnyLabeling#320]

**Comment by CVHub520** [comment]
Hi, implementing YOLOv8_obb in C++ is straightforward. You can refer to this [script](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/export_yolov8_obb_onnx.py) for guidance.

**Comment by yxl23** [comment]
Okay, thank you, the author
