### ISSUE TITLE
【Bug】 删除标注文件按钮有bug

### ISSUE THREAD

**Issue by jiangtangaaaa** [CVHub520/X-AnyLabeling#321]
Steps: Click the Open Single File button=>Open a tagged image=>Click the Delete Tagged button in the menu bar=>Program crashes
The following is a step diagram
![image](https://github.com/CVHub520/X-AnyLabeling/assets/101043186/d1ca4ccd-2317-4ebb-ab00-d530bb114d7b)
Here is a screenshot of the bug
![image](https://github.com/CVHub520/X-AnyLabeling/assets/101043186/65fa0412-4847-4f83-b72f-29ca4a76c241)

The problem is that when you click the Delete button, your program directly deletes the corresponding json file, and then calls self. reset_state() to set self. filename to None. I hope the author can fix this problem. Thank you very much

**Comment by jiangtangaaaa** [comment]
@CVHub520

**Comment by CVHub520** [comment]
Hi, @jiangtangaaaa:

Thanks for your feedback!

However, the feature to delete label files cannot be triggered when loading a single image, so the situation you described should not occur. Can you provide detailed steps to replicate this issue? 

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/9b2ffc73-6557-445f-bcf6-0ea305e23ee6)

**Comment by jiangtangaaaa** [comment]
> Hi, @jiangtangaaaa: 你好：
> 
> Thanks for your feedback!感谢您的反馈！
> 
> However, the feature to delete label files cannot be triggered when loading a single image, so the situation you described should not occur. Can you provide detailed steps to replicate this issue?但是，加载单个图像时无法触发删除标签文件的功能，因此不会出现您描述的情况。您能否提供复制此问题的详细步骤？
> 
> ![image](https://private-user-images.githubusercontent.com/72010077/314425667-9b2ffc73-6557-445f-bcf6-0ea305e23ee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODUxMjUsIm5iZiI6MTcxMDk4NDgyNSwicGF0aCI6Ii83MjAxMDA3Ny8zMTQ0MjU2NjctOWIyZmZjNzMtNjU1Ny00NDVmLWJjZjYtMGVhMzA1ZTIzZWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAxMzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZTdkZTIzY2I4YjE1NTRiOWQ5YzE5N2Q5MDc5MDY2YjE2ZDliNDE5YTE1ODQ4ZDU3MzAwZjkwNWM0MzdhYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XuLeSVvFtU23wxL98cm_3dhF_jLwKewj4pxLx8SB3ZE)

大佬你好，我测试有两种情况，可以供您参考
情况1：加载有标注文件的图像，我测试，您的垃圾桶按钮是亮的
情况2：加载没有标注的图像==》绘制标记==》菜单栏file==》open file菜单栏==》再次打开这张图片==》垃圾桶按钮亮
当然，第二种情况我估计没人去尝试，但是情况1是存在的，您可以测试一下然后给我一个反馈
谢谢大佬回复
![image](https://github.com/CVHub520/X-AnyLabeling/assets/101043186/a10e4857-fe5c-48e1-9e75-1afb1928b8d3)

**Comment by jiangtangaaaa** [comment]
还有加载文件夹的时候，点击垃圾桶按钮==》canvas空白了==》还得点击上一张或者下一张==》图像才显示出来
是不是   不应该在reset_state函数里把self.filename = None呢

**Comment by CVHub520** [comment]
> > Hi, @jiangtangaaaa: 你好：
> > Thanks for your feedback!感谢您的反馈！
> > However, the feature to delete label files cannot be triggered when loading a single image, so the situation you described should not occur. Can you provide detailed steps to replicate this issue?但是，加载单个图像时无法触发删除标签文件的功能，因此不会出现您描述的情况。您能否提供复制此问题的详细步骤？
> > ![image](https://private-user-images.githubusercontent.com/72010077/314425667-9b2ffc73-6557-445f-bcf6-0ea305e23ee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODUxMjUsIm5iZiI6MTcxMDk4NDgyNSwicGF0aCI6Ii83MjAxMDA3Ny8zMTQ0MjU2NjctOWIyZmZjNzMtNjU1Ny00NDVmLWJjZjYtMGVhMzA1ZTIzZWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAxMzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZTdkZTIzY2I4YjE1NTRiOWQ5YzE5N2Q5MDc5MDY2YjE2ZDliNDE5YTE1ODQ4ZDU3MzAwZjkwNWM0MzdhYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XuLeSVvFtU23wxL98cm_3dhF_jLwKewj4pxLx8SB3ZE)
> 
> 大佬你好，我测试有两种情况，可以供您参考 情况1：加载有标注文件的图像，我测试，您的垃圾桶按钮是亮的 情况2：加载没有标注的图像==》绘制标记==》菜单栏file==》open file菜单栏==》再次打开这张图片==》垃圾桶按钮亮 当然，第二种情况我估计没人去尝试，但是情况1是存在的，您可以测试一下然后给我一个反馈 谢谢大佬回复 ![image](https://private-user-images.githubusercontent.com/101043186/314900661-a10e4857-fe5c-48e1-9e75-1afb1928b8d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5OTA0OTAsIm5iZiI6MTcxMDk5MDE5MCwicGF0aCI6Ii8xMDEwNDMxODYvMzE0OTAwNjYxLWExMGU0ODU3LWZlNWMtNDhlMS05ZTc1LTFhZmIxOTI4YjhkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQwMzAzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmE3NDEyOTU1ZWE1NWJmMDE2NjY1N2IwZTYyMTNkYjA3Nzk3MGIwOTc2MTE0MzI3YTk3NWUyNzdiMTkxYmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8CqGqOT91gIEbWBQnZnhLVmvsDCLnOJ0c8hN575dCDI)

您好，这张加载单张图像的，一般是用于调试，如果还要去点击删除按钮，完全是极小概率的需求，所以没有优化的必要性。

**Comment by CVHub520** [comment]
> 还有加载文件夹的时候，点击垃圾桶按钮==》canvas空白了==》还得点击上一张或者下一张==》图像才显示出来 是不是 不应该在reset_state函数里把self.filename = None呢

稍微优化了下，可以更新源码体验下。另外删除文件这个功能本身不建议频繁使用。

**Comment by jiangtangaaaa** [comment]
> > 还有加载文件夹的时候，点击垃圾桶按钮==》canvas空白了==》还得点击上一张或者下一张==》图像才显示出来 是不是 不应该在reset_state函数里把self.filename = None呢
> 
> 稍微优化了下，可以更新源码体验下。另外删除文件这个功能本身不建议频繁使用。

感谢大佬~~
