### ISSUE TITLE
用efficientvit-sam  标注分割图像哪地方可以修改轮廓，调整轮廓吗

### ISSUE THREAD

**Issue by skycat88** [CVHub520/X-AnyLabeling#322]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/112526954/0d6d9f51-2ea0-442e-8cdb-6d8fe5d70cba)

**Comment by CVHub520** [comment]
您好，可以通过快捷键 `Ctrl+j` 切换到编辑模式进行调整，屏幕左侧有显示当前所处模式。

**Comment by skycat88** [comment]
您好，进入到编辑模式了，我记得之前有过功能，自动分割的数据点可以点击变少一点，请问还有这个功能吗
![image](https://github.com/CVHub520/X-AnyLabeling/assets/112526954/20f4c12b-1a95-4dc0-9e90-100f26737652)

**Comment by skycat88** [comment]
@CVHub520

**Comment by CVHub520** [comment]
您好，可以按住 `Shift` 键点击您要消除的顶点即可。

**Comment by skycat88** [comment]
按住Shift 键，消除点击十几次，闪退了
![image](https://github.com/CVHub520/X-AnyLabeling/assets/112526954/709bc205-6e6f-4c21-9821-4aea30f5ba17)

**Comment by skycat88** [comment]
点太多，能有批量化，删除点的操作吗

**Comment by CVHub520** [comment]
> 点太多，能有批量化，删除点的操作吗

建议根据自己需要改下 sam 模型的相关后处理代码，可以自己加个平滑后处理操作一劳永逸。

**Comment by CVHub520** [comment]
> 按住Shift 键，消除点击十几次，闪退了 ![image](https://private-user-images.githubusercontent.com/112526954/314357363-709bc205-6e6f-4c21-9821-4aea30f5ba17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDE4MDgsIm5iZiI6MTcxMDkwMTUwOCwicGF0aCI6Ii8xMTI1MjY5NTQvMzE0MzU3MzYzLTcwOWJjMjA1LTZlNmYtNGMyMS05ODIxLTRhZWEzMGY1YmExNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwMjI1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGU4NGY3ZjAxZDJiMmUzOTNkYTFjNTA0MDNjZWQzMGZjZjc2MDM1MWJkODVjOTA3ZTZhOGExM2UyMTUyNDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7E_DOSyXLKB9pFKoY-4ur2ZLt83IxO7lus5DnbzUZpQ)

请问是每次都会还是，一般什么情况下会触发？

**Comment by skycat88** [comment]
@CVHub520 
目前观察可能 应该是，我切换模型导致， 切换一次，显卡涨一次，然后就死了，

**Comment by CVHub520** [comment]
> @CVHub520 目前观察可能 应该是，我切换模型导致， 切换一次，显卡涨一次，然后就死了，

这个跟你上面的错误有什么关系？
