### ISSUE TITLE
如果我已经标注好了自动框，批量自动化生成Sam  分割结果，应该如何操作

### ISSUE THREAD

**Issue by skycat88** [CVHub520/X-AnyLabeling#323]

**Comment by skycat88** [comment]
@CVHub520   是这样的，我标注好后根据检测框，顺便得到批量得到sam 的分割标签，我在脚本里做好，分割的json 结果，再再您提供的工具中微调一下，这样好像能快点

**Comment by CVHub520** [comment]
Got it! I will close this issue now. If you have any further inquiries or need to continue the discussion, please don't hesitate to reopen it.

**Comment by 1272203655** [comment]
> @CVHub520 是这样的，我标注好后根据检测框，顺便得到批量得到sam 的分割标签，我在脚本里做好，分割的json 结果，再再您提供的工具中微调一下，这样好像能快点

您好 我现在有这种需求 需要根据检测的矩形框 转为分割掩码  请问您是如何做的 能否提供一些建议 或脚本
