### ISSUE TITLE
用sam 相关标注不准确的的框，会漂移，不是画框区域得到的分割区域是否有问题

### ISSUE THREAD

**Issue by skycat88** [CVHub520/X-AnyLabeling#324]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/112526954/f23da418-fa64-404a-9d10-171dbea1de67)

**Comment by skycat88** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/112526954/d27ccbde-2a5f-4728-b1c0-31574f83c42a)

**Comment by skycat88** [comment]
@lartpang    框画的是下面区域但是，分割的是上面的区域，换一张猫狗的图片，同样的操作，标注是正常的

**Comment by CVHub520** [comment]
> @lartpang 框画的是下面区域但是，分割的是上面的区域，换一张猫狗的图片，同样的操作，标注是正常的

有可能是模型适应不了这种 domain，需要自己为微调下。Medical 相关的建议可以用 SAM-Med2D 或其它适合的模型。
