### ISSUE TITLE
框超出图片无法拖拽

### ISSUE THREAD

**Issue by huyunlei** [CVHub520/X-AnyLabeling#325]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/57059809/43d37e17-2bfa-4b62-90b0-d39ceee5f9b3)

**Comment by huyunlei** [comment]
这种情况是继承上一个图片的标签所导致，下一张图片比上一张图片小

**Comment by CVHub520** [comment]
> 这种情况是继承上一个图片的标签所导致，下一张图片比上一张图片小

您好，保留上一张图片标签仅限同一分辨率场景下使用。

**Comment by huyunlei** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您发来的邮件已经收到，我会尽快给您回复。
