### ISSUE TITLE
SAM-Med2D + Yolo

### ISSUE THREAD

**Issue by biyuefeng** [CVHub520/X-AnyLabeling#326]
Hello, in multitasking segmentation, I saw support for MobileSAM+yolov5.
Now, I want to use the SAM-Med2D+Yolo approach, how should I modify it? Thank you!

**Comment by CVHub520** [comment]
Hi, @biyuefeng:

Thanks for reaching out. You can carry out the SAM-Med2D+Yolo approach by following the steps of this [toturial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/custom_model.md#22-unadapted-models) as a reference based on the given [example](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/yolov5_sam.py).

Good luck! :)

**Comment by biyuefeng** [comment]
I made the modifications according to the plan you provided, but I kept getting errors. Will you update the SAM-Med2D+Yolov8 plan in the future?


人生海海海布里
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CVHub520/X-AnyLabeling"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月20日(星期三) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CVHub520/X-AnyLabeling] SAM-Med2D + Yolo (Issue #326)





 
Hi, @biyuefeng:
 
Thanks for reaching out. You can carry out the SAM-Med2D+Yolo approach by following the steps of this toturial as a reference based on the given example.
 
Good luck! :)

**Comment by CVHub520** [comment]
Hi, @biyuefeng; I'm sorry, but typically I do not support such custom requirements. I regret to inform you that it is unlikely that we will update the SAM-Med2D+YoloV8 plan in the future.
