### ISSUE TITLE
文本标签自动标注

### ISSUE THREAD

**Issue by ClearTorch** [CVHub520/X-AnyLabeling#33]
什么时候支持文本OCR自动标注，paddleocr v3模型？

**Comment by CVHub520** [comment]
> 什么时候支持文本OCR自动标注，paddleocr v3模型？

人手不够，暂时先加入排期，感谢你的关注。

**Comment by CVHub520** [comment]
@ClearTorch 您好，已接入最新的 PP-OCRv4 模型，欢迎使用。
