### ISSUE TITLE
如何连续绘制矩形？

### ISSUE THREAD

**Issue by retioa11** [CVHub520/X-AnyLabeling#330]
绘制完一个矩形后，进入到了编辑模式，需要再次点击左侧的绘制矩形按钮，才能再次绘制矩形。操作繁琐，可否实现不需要点击绘制矩形按钮，便可连续绘制矩形？

**Comment by CVHub520** [comment]
> 绘制完一个矩形后，进入到了编辑模式，需要再次点击左侧的绘制矩形按钮，才能再次绘制矩形。操作繁琐，可否实现不需要点击绘制矩形按钮，便可连续绘制矩形？

您好，可直接左手按下 `r` 键快速绘制矩形，无需点击左侧的绘制矩形按钮。

**Comment by monkeycc** [comment]
每张图都要按R
确实比较繁琐

是不是可以这样
下拉菜单 

增加是否一直绘制
未选择
矩形标注  √
多点标注
....

每次切换的时候 判断一下
自动给用户按R
这样就不用每次让用户按R了

默认 未选择
就是默认的模式 
每一张都要用户自己手动

**Comment by retioa11** [comment]
是的，若想实现连续标注，无需按下快捷键或者点击按钮，可否指点一下需要改哪个地方的代码？ 我自己想办法改也可以，有点等不及了。做标注的同事，感觉您这个软件很好用，但是就是只有这个地方如果再方便一点，就更好了。

**Comment by CVHub520** [comment]
> 是的，若想实现连续标注，无需按下快捷键或者点击按钮，可否指点一下需要改哪个地方的代码？ 我自己想办法改也可以，有点等不及了。做标注的同事，感觉您这个软件很好用，但是就是只有这个地方如果再方便一点，就更好了。

你好，首先两手配合标注完全可以达到一个同步的状态，你在标注的时候可以根据自己的需要左手按下对应快捷键自动激活想要的绘制模式，例如矩形框，旋转框，多边形等，这效率其实是更高的。因为你右手鼠标在绘制时，左手完全是一个空闲的状态。

以前的版本一直都是默认连续绘制的，但是这样有个问题，就是你标注完想要修正的话就必须得切回编辑模式，这时候要补的话又得切换为绘制模式。另一方面就是上面说的，多任务切换很麻烦。任何设计总是有利有弊，如果需要连续绘制功能，可下载以前的版本，具体是哪一版可能得自己找找，太久忘记了。

**Comment by CVHub520** [comment]
> 每张图都要按R 确实比较繁琐
> 
> 是不是可以这样 下拉菜单
> 
> 增加是否一直绘制 未选择 矩形标注 √ 多点标注 ....
> 
> 每次切换的时候 判断一下 自动给用户按R 这样就不用每次让用户按R了
> 
> 默认 未选择 就是默认的模式 每一张都要用户自己手动 @CVHub520

好的，感谢你的建议，后期有时间的话会考虑下，但这个目前不是一个亟需的功能，因此短时间内可能不会支持。

**Comment by CVHub520** [comment]
@retioa11 @monkeycc 最新源码以支持连续绘制矩形功能，请及时更新，感谢支持！

**Comment by CVHub520** [comment]
> 你好，目前使用的打包好的 .exe文件还是无法实现保持标注模式

Please refer to [this](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#74-%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E7%BC%96%E8%BE%91%E6%A8%A1%E5%BC%8F).

**Comment by nothingws** [comment]
> > 你好，目前使用的打包好的 .exe文件还是无法实现保持标注模式
> 
> Please refer to [this](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#74-%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E7%BC%96%E8%BE%91%E6%A8%A1%E5%BC%8F).

好的，谢谢，可以了
