### ISSUE TITLE
模型下载，建议提供全部模型下载包

### ISSUE THREAD

**Issue by monkeycc** [CVHub520/X-AnyLabeling#333]
模型下载，建议提供全部模型下载包
全部打包好

到时候直接解压到anylabeling_data\models

现在要一个一个的下载
比较麻烦

**Comment by CVHub520** [comment]
> 模型下载，建议提供全部模型下载包 全部打包好
> 
> 到时候直接解压到anylabeling_data\models
> 
> 现在要一个一个的下载 比较麻烦

您好，全部的模型下载包一来非常大，二来没有什么场景能用到几十个模型，因此没什么必要。
