### ISSUE TITLE
不要使用灰色按钮，看不清楚文字的

### ISSUE THREAD

**Issue by monkeycc** [CVHub520/X-AnyLabeling#334]
![微信截图_20240322093801](https://github.com/CVHub520/X-AnyLabeling/assets/6490927/e10277ca-7374-44c7-9269-2d996252b7a7)

灰色底 黑色字
不好看清楚文字

可以调整为白色文字？
或者背景不要灰色？

**Comment by CVHub520** [comment]
您好，这个是因为系统开了深色模式，目前该功能还在测试阶段，UI存在问题，建议将系统的深色模式关闭先，等后续版本的更新。

**Comment by 1240498481** [comment]
使用Segment Anything的时候出来的分割线也是灰色，眼睛都要瞎了

**Comment by aiyou9** [comment]
> 使用Segment Anything的时候出来的分割线也是灰色，眼睛都要瞎了

这个可以对标签设定对应的颜色?????，看看doc
