### ISSUE TITLE
Error in predict_shapes: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))

### ISSUE THREAD

**Issue by AImagicAI** [CVHub520/X-AnyLabeling#335]
您好，我在使用自己微调的SAM模型和YOLO进行组合时，会报如下错误：
Error in predict_shapes: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))

但是，我在分别使用SAM和YOLO模型时，他们是可以正常运行的。这是两个onnx模型不匹配的缘故吗？
谢谢！

**Comment by CVHub520** [comment]
> 您好，我在使用自己微调的SAM模型和YOLO进行组合时，会报如下错误： Error in predict_shapes: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))
> 
> 但是，我在分别使用SAM和YOLO模型时，他们是可以正常运行的。这是两个onnx模型不匹配的缘故吗？ 谢谢！

你需要将 YOLO 的输出强制转换成 float 类型送入 SAM。

**Comment by AImagicAI** [comment]
`    def predict_shapes(self, image, filename=None) -> AutoLabelingResult:
        """
        Predict shapes from image
        """
        if image is None:
            return []

        try:
            cv_image = qt_img_to_rgb_cv_img(image, filename)
        except Exception as e:  # noqa
            logging.warning("Could not inference model")
            logging.warning(e)
            return []

        if filename not in self.image_embed_cache:
            image_embedding = self.encoder_model(cv_image)
            blob = self.preprocess(cv_image, upsample_mode="letterbox")
            outputs = self.net.get_ort_inference(blob=blob, extract=False)
            boxes, _, class_ids, _ = self.postprocess(outputs)

            shapes = []
            for box, class_id in zip(boxes, class_ids):
                label = str(self.classes[int(class_id)])
                x1, y1, x2, y2 = list(map(int, box))
                point_coords = np.array([[x1, y1], [x2, y2]], dtype=np.float32)
                point_labels = np.array([2, 3], dtype=np.float32)
                masks = self.decoder_model.run(
                    img_embeddings=image_embedding["image_embedding"],
                    origin_image_size=image_embedding["origin_image_size"],
                    point_coords=point_coords,
                    point_labels=point_labels,
                )
                if len(masks.shape) == 4:
                    masks = masks[0][0]
                else:
                    masks = masks[0]
                results = self.post_process(masks, label=label)
                shapes.append(results)
            result = AutoLabelingResult(shapes, replace=True)
            self.image_embed_cache[filename] = image_embedding
            return result
        else:
            point_coords, point_labels = self.get_input_points()
            image_embedding = self.image_embed_cache[filename]
            masks = self.decoder_model.run(
                img_embeddings=image_embedding["image_embedding"],
                origin_image_size=image_embedding["origin_image_size"],
                point_coords=point_coords,
                point_labels=point_labels,
            )
            if len(masks.shape) == 4:
                masks = masks[0][0]
            else:
                masks = masks[0]
            shapes = self.post_process(masks)
            result = AutoLabelingResult(shapes, replace=False)
            return result

    def unload(self):
        del self.net
        del self.encoder_model
        del self.decoder_model
`
我参考的是yolov8_efficientvit_sam.py源码，是需要对这个predict_shapes函数进行修改吗？我暂时还未找到yolo的输出类型转化。

**Comment by AImagicAI** [comment]
您好，我看这里的输出anchor是float类型的。
我参考的是yolov8_efficientvit_sam.py源码，是需要对这个predict_shapes函数进行修改吗？我暂时还未找到yolo的输出类型转化。
谢谢！



                       
原始邮件
                       
                     

发件人："CVHub"< ***@***.*** &gt;;

发件时间：2024/3/22 10:14

收件人："CVHub520/X-AnyLabeling"< ***@***.*** &gt;;

抄送人："AImagicAI"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [CVHub520/X-AnyLabeling] Error in predict_shapes:[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type.Actual: (tensor(uint8)) , expected: (tensor(float)) (Issue #335)




  
您好，我在使用自己微调的SAM模型和YOLO进行组合时，会报如下错误： Error in predict_shapes: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))
 
但是，我在分别使用SAM和YOLO模型时，他们是可以正常运行的。这是两个onnx模型不匹配的缘故吗？ 谢谢！
  
你需要将 YOLO 的输出强制转换成 float 类型送入 SAM。

**Comment by CVHub520** [comment]
您好，你可以定位到这一行：
```
...
point_coords = np.array([[x1, y1], [x2, y2]], dtype=np.float32)
```

**Comment by AImagicAI** [comment]
我这行，是有dtype=np.float32的。
point_coords = np.array([[x1, y1], [x2, y2]], dtype=np.float32)
point_labels = np.array([2, 3], dtype=np.float32)
我使用的yolov8_efficientvit_sam.py源码。我用原来的EfficientvitSAM和yolov8n模型，是可以正常运行的。
但是，我将EfficientvitSAM替换为自己微调后的SAM_Med2D时，就会出错。Error in loading model: float() argument must be a string or a number, not 'YOLOv8_EfficientViT_SAM'

不清楚是不是onnx模型的问题？但是，我只使用sam-med2d的模型时，也是可以正常运行的。


希望得到您的帮助。谢谢！！！



                       
原始邮件
                       
                     

发件人："CVHub"< ***@***.*** &gt;;

发件时间：2024/3/22 14:07

收件人："CVHub520/X-AnyLabeling"< ***@***.*** &gt;;

抄送人："AImagicAI"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [CVHub520/X-AnyLabeling] Error in predict_shapes:[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type.Actual: (tensor(uint8)) , expected: (tensor(float)) (Issue #335)




 
您好，你可以定位到这一行：
 ... point_coords = np.array([[x1, y1], [x2, y2]], dtype=np.float32)

**Comment by CVHub520** [comment]
您好， 自定义模型可以参考下这个[教程](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md#22-%E6%9C%AA%E9%80%82%E9%85%8D%E6%A8%A1%E5%9E%8B)，你这边需要注册到模型列表中才能生效。
