### ISSUE TITLE
增加导出全部标签名..txt

### ISSUE THREAD

**Issue by monkeycc** [CVHub520/X-AnyLabeling#336]
保存子图
或者
保存yolo格式

都提示要 标签名.txt

我是用AI自动标注的
那么多标签名
我怎么手打出来呢

既然有个 标签统计
应该增加一个 导出标签

**Comment by CVHub520** [comment]
> 保存子图 或者 保存yolo格式
> 
> 都提示要 标签名.txt
> 
> 我是用AI自动标注的 那么多标签名 我怎么手打出来呢
> 
> 既然有个 标签统计 应该增加一个 导出标签

您好，考虑一下情况：
1. 有没有可能，用户只想要某一类或某几类的标签；
2. 作为软件设计者，你如何事先知道用户需要将某个类别的编号映射为哪个下标索引？每次都随机映射吗？
3. 既然你需要这么“多”的标签类别，那么事先大概率有一个“文档”介绍或定义，完全可以借助 GPT 之类的工具帮你自动组织、提取、整理成所需的格式直接复制过来即可。
‘一款软件的设计交互是需要考虑多种需求，不是针对单个用户来设计的；代码已经开源，你这边完全可以定制符合自身需求的功能，达到效率最大化。

**Comment by monkeycc** [comment]
在 标签统计页面
增加一个 导出全部标签
数量不包含为0的标签名称

标签.txt
```
aa
bb
cccc
ddd
eee
```


这样就可以了

这样有需要的用户
自己可以导出
不需要的用户 也不影响

这样的话 保存子图或者保存yolo格式的时候
用户不就方便了
直接导入这个标签.txt 就行了

--------------------------------------------------------------------
至于你考虑的    “”用户想自定义导出标签“”
用户可以自己删除 标注好的标签 
再导出

如果想要导出自定义标签
这种就涉及到复杂问题了
1.要能筛选标签
2.只导出筛选后的标签和图片数据，保存到一个新的数据集目录

这种功能确实是暂时不需要的
--------------------------------------------------------------------

当然这个只是建议
只是希望框架能越来越好而已

**Comment by CVHub520** [comment]
您好，非常感谢你的建议。但还是存在我上面提到的一个问题，就是作为软件的设计者，我事先是无法知道用户需要将哪个标签映射到哪个索引，这在很多场景下是受限的，例如 `yolo` 等；如果你随机导出一份包含 classes 的标签文件，光去调整标签的顺序所耗费的时间和精力还不如用户自行手动定义完在上传。

**Comment by monkeycc** [comment]
可以这样，用户点击导出的时候
直接获取文件夹所有的标注文件json
然后统计标签名称，再导出
这样呢

**Comment by CVHub520** [comment]
> 可以这样，用户点击导出的时候 直接获取文件夹所有的标注文件json 然后统计标签名称，再导出 这样呢

不是这个问题，比如对于 YOLO 的 Darknet 格式，类别名和索引和强绑定的，一一对应的。如果由于你导出的时候标签关系映射错乱的话，后续训练是会乱的，并不是说获取不到类别名。如果当前导出格式不需要这种依赖关系是不需要提供类别标签文件的。
