### ISSUE TITLE
Error opening file

### ISSUE THREAD

**Issue by 202112213501021** [CVHub520/X-AnyLabeling#338]
'shapes'
Make sure "xxxxxx/1.json"is a valid lablel file
My image folder contains a json file, why can't I open the image

**Comment by CVHub520** [comment]
Hi, @202112213501021:

It seems like you are trying to use a JSON file as a label file for an image, but encountered an error. To help you, I need more information. Can you please clarify:

1. What version of X-AnyLabeling are you trying to use to open the image and the JSON file?
2. How is the JSON file formatted? Is it a standard x-anylabeling format label file, or something else?
3. Have you tried opening the another image and label pairs, and does it work there?
For more important, can you share the contents of the JSON file if convenient?
Once you provide this information, I'll be better equipped to help you troubleshoot the issue.

**Comment by Chimaco37** [comment]
我也遇到了同样的问题
![image](https://github.com/CVHub520/X-AnyLabeling/assets/77201421/e7311f66-1313-4caf-9aee-20f28b53bcc0)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/77201421/bc69f0de-b10e-47bf-98db-db5799494f6a)
版本：X-anylabeling-CPU.exe v2.3.4

json文件示例：
{
  "version": "1.0.0",
  "flags": {},
  "shapes": [
    {
      "label": "Tassel",
      "text": "",
      "points": [
        [
          329.5238095238096,
          264.6031746031746
        ],
        [
          323.70370370370375,
          345.02645502645504
        ],
        [
          325.8201058201059,
          420.1587301587302
        ],
        [
          323.70370370370375,
          477.3015873015873
        ],
        [
          335.8730158730159,
          477.3015873015873
        ],
        [
          336.93121693121697,
          420.6878306878307
        ],
        [
          343.2804232804233,
          363.5449735449735
        ],
        [
          344.8677248677249,
          293.1746031746032
        ],
        [
          343.2804232804233,
          276.2433862433862
        ],
        [
          342.22222222222223,
          267.77777777777777
        ],
        [
          341.6931216931217,
          261.95767195767195
        ],
        [
          337.98941798941803,
          256.6666666666667
        ]
      ],
      "group_id": null,
      "shape_type": "polygon",
      "flags": {}
    }
  ],
  "imagePath": "..\\images\\23-11-HN-CG-003-14_mp4-0000_jpg.rf.a76449b713d3b6ff01944e45387f5fe7.jpg",
  "imageData": null,
  "imageHeight": 480,
  "imageWidth": 640
}

对应图像：
![23-11-HN-CG-003-14_mp4-0000](https://github.com/CVHub520/X-AnyLabeling/assets/77201421/322c03e5-4386-47f8-ad9e-f78e65d4d187)

这个json文件就是通过x-anylabeling标注生成的，请问应该如何操作进行标注文件修复。十分感谢！

**Comment by 202112213501021** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/141103647/86ce0ec1-40fb-4b5a-a132-d50a5eb25edf)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/141103647/4888cba8-753f-4eb3-92aa-cf097846d939)

**Comment by Chimaco37** [comment]
> 'shapes' Make sure "xxxxxx/1.json"is a valid lablel file My image folder contains a json file, why can't I open the image

maybe its because the imagePath in json file isnt correct, you can go check it. after i correct the imagePath line, my image can be shown.
original malfunction one:
![image](https://github.com/CVHub520/X-AnyLabeling/assets/77201421/efdc56c2-86ec-43c3-adf4-106a9231a88a)
right one:
![image](https://github.com/CVHub520/X-AnyLabeling/assets/77201421/018de672-9b40-4b57-8a0b-db7777d09034)

**Comment by CVHub520** [comment]
@202112213501021 

Hi, thanks for your feedback! 

The file you provided does not match the built-in label format used by X-AnyLabeling (for example, you can refer to [this](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/demo.json) or just uploading a source image file and annotate it, then open the saved label file, where is always under the same directory as the image folder by default), which means it cannot be loaded directly into the tool. 

However, it appears to be in the COCO JSON format. For guidance on how to upload a custom file of this format, please refer to the documentation provided here: [docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md).

**Comment by CVHub520** [comment]
> > 'shapes' Make sure "xxxxxx/1.json"is a valid lablel file My image folder contains a json file, why can't I open the image
> 
> maybe its because the imagePath in json file isnt correct, you can go check it. after i correct the imagePath line, my image can be shown. original malfunction one: ![image](https://private-user-images.githubusercontent.com/77201421/316312745-efdc56c2-86ec-43c3-adf4-106a9231a88a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTM5MzcsIm5iZiI6MTcxMTI5MzYzNywicGF0aCI6Ii83NzIwMTQyMS8zMTYzMTI3NDUtZWZkYzU2YzItODZlYy00M2MzLWFkZjQtMTA2YTkyMzFhODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE1MjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NjRkNzhkZDg3NjRkNzk5ZGQ0NTdlMDA1YmM2ZDkyYWFhMTNjYzVkMTVjMzcwNGI3MGU1YWU0OTk0OTUwMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AYCYFs8KmvxixqrA-E5AlewPv0PDRPeaOiV2I23mpY0) right one: ![image](https://private-user-images.githubusercontent.com/77201421/316312762-018de672-9b40-4b57-8a0b-db7777d09034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTM5MzcsIm5iZiI6MTcxMTI5MzYzNywicGF0aCI6Ii83NzIwMTQyMS8zMTYzMTI3NjItMDE4ZGU2NzItOWI0MC00YjU3LThhMGItZGI3Nzc3ZDA5MDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE1MjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiODY4NzIwNmZjMGQ0NmE4NTQyM2FiYmU0YmM5MWZlNGI1ODUxZGRhMjQ1ZGZlMzk4ZGJhMjUzNGYyYWQ2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lPUhhtLfqLKBpLqTwJZAkkoeAiyNf3z-1lrA19Jv_Mo)

That sounds great! There might exist another alternative way to address this problem, which involves changing the output directory yourself.

**Comment by 202112213501021** [comment]
> @202112213501021
> 
> 您好，感谢您的反馈！
> 
> 您提供的文件与 X-AnyLabeling 使用的内置标签格式不匹配（例如，您可以参考[此](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/demo.json)文件或仅上传源图像文件并对其进行注释，然后打开保存的标签文件，默认情况下始终与图像文件夹位于同一目录下），这意味着它无法直接加载到工具中。
> 
> 但是，它似乎是 COCO JSON 格式。有关如何上传此格式的自定义文件的指导，请参阅此处提供的文档：[docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md)。

我的问题是打开不了与其对应的图片，而不是上传，我的json文件中并没有imagePath，它是分割的json文件。我能不能没有json文件的限制，仅仅打开图片。

**Comment by CVHub520** [comment]
> > @202112213501021
> > 您好，感谢您的反馈！
> > 您提供的文件与 X-AnyLabeling 使用的内置标签格式不匹配（例如，您可以参考[此](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/demo.json)文件或仅上传源图像文件并对其进行注释，然后打开保存的标签文件，默认情况下始终与图像文件夹位于同一目录下），这意味着它无法直接加载到工具中。
> > 但是，它似乎是 COCO JSON 格式。有关如何上传此格式的自定义文件的指导，请参阅此处提供的文档：[docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md)。
> 
> 我的问题是打开不了与其对应的图片，而不是上传，我的json文件中并没有imagePath，它是分割的json文件。我能不能没有json文件的限制，仅仅打开图片。

您好，你可以把同名json文件先剪切出来放到其它目录下，再打开软件重新加载对应的图像文件即可。

注意，如果当前图像目录下存在对应同名的json文件，软件会将其视为标注文件加载并尝试解析，此时如果json文件格式与内置模板不符则会导致加载失败。

**Comment by 202112213501021** [comment]
> > > @202112213501021
> > > 您好，感谢您的反馈！
> > > 您提供的文件与 X-AnyLabeling 使用的内置标签格式不匹配（例如，您可以参考[此](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/demo.json)文件或仅上传源图像文件并对其进行注释，然后打开保存的标签文件，默认情况下始终与图像文件夹位于同一目录下），这意味着它无法直接加载到工具中。
> > > 但是，它似乎是 COCO JSON 格式。有关如何上传此格式的自定义文件的指导，请参阅此处提供的文档：[docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md)。
> > 
> > 
> > 我的问题是打开不了与其对应的图片，而不是上传，我的json文件中并没有imagePath，它是分割的json文件。我能不能没有json文件的限制，仅仅打开图片。
> 
> 您好，你可以把同名json文件先剪切出来放到其它目录下，再打开软件重新加载对应的图像文件即可。
> 
> 注意，如果当前图像目录下存在对应同名的json文件，软件会将其视为标注文件加载并尝试解析，此时如果json文件格式与内置模板不符则会导致加载失败。

是的，只能这么办了，感谢你的回复

**Comment by CVHub520** [comment]
> > > > @202112213501021
> > > > 您好，感谢您的反馈！
> > > > 您提供的文件与 X-AnyLabeling 使用的内置标签格式不匹配（例如，您可以参考[此](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/demo.json)文件或仅上传源图像文件并对其进行注释，然后打开保存的标签文件，默认情况下始终与图像文件夹位于同一目录下），这意味着它无法直接加载到工具中。
> > > > 但是，它似乎是 COCO JSON 格式。有关如何上传此格式的自定义文件的指导，请参阅此处提供的文档：[docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md)。
> > > 
> > > 
> > > 我的问题是打开不了与其对应的图片，而不是上传，我的json文件中并没有imagePath，它是分割的json文件。我能不能没有json文件的限制，仅仅打开图片。
> > 
> > 
> > 您好，你可以把同名json文件先剪切出来放到其它目录下，再打开软件重新加载对应的图像文件即可。
> > 注意，如果当前图像目录下存在对应同名的json文件，软件会将其视为标注文件加载并尝试解析，此时如果json文件格式与内置模板不符则会导致加载失败。
> 
> 是的，只能这么办了，感谢你的回复

好的，不客气。
