### ISSUE TITLE
【需求】侧边栏[标注]里的Label可编辑

### ISSUE THREAD

**Issue by jiangtangaaaa** [CVHub520/X-AnyLabeling#339]
大佬，侧边栏标注里的各个Label，要是实现可以编辑、删除，这个功能复杂吗
![image](https://github.com/CVHub520/X-AnyLabeling/assets/101043186/9db69857-3500-45ba-8b53-06943c8a56ac)

**Comment by Zomcxj** [comment]
工具-标签管理里有啊

**Comment by CVHub520** [comment]
> 大佬，侧边栏标注里的各个Label，要是实现可以编辑、删除，这个功能复杂吗 ![image](https://private-user-images.githubusercontent.com/101043186/316382024-9db69857-3500-45ba-8b53-06943c8a56ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTA5OTQsIm5iZiI6MTcxMTM1MDY5NCwicGF0aCI6Ii8xMDEwNDMxODYvMzE2MzgyMDI0LTlkYjY5ODU3LTM1MDAtNDViYS04YjUzLTA2OTQzYzhhNTZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwNzExMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2U3ZDQ2Y2MwYjg5ODg1ZDQ1NjkwOGJlZWRhYWE1Mjc3Y2UzOWY3N2QwMDcyZTJiNDRkMTFhMTdkZGU5MTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L4RT_qZp-YhC8Sldjc1Vsmoch5f_PRDTyV-tUjvplVc)

您好，这个版本有点旧了，麻烦下载最新版本体验。最新版支持对当前任务标签进行编辑、删除，入口[同上](https://github.com/CVHub520/X-AnyLabeling/issues/339#issuecomment-2017283734)

**Comment by jiangtangaaaa** [comment]
> > 大佬，侧边栏标注里的各个Label，要是实现可以编辑、删除，这个功能复杂吗 ![image](https://private-user-images.githubusercontent.com/101043186/316382024-9db69857-3500-45ba-8b53-06943c8a56ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTA5OTQsIm5iZiI6MTcxMTM1MDY5NCwicGF0aCI6Ii8xMDEwNDMxODYvMzE2MzgyMDI0LTlkYjY5ODU3LTM1MDAtNDViYS04YjUzLTA2OTQzYzhhNTZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwNzExMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2U3ZDQ2Y2MwYjg5ODg1ZDQ1NjkwOGJlZWRhYWE1Mjc3Y2UzOWY3N2QwMDcyZTJiNDRkMTFhMTdkZGU5MTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L4RT_qZp-YhC8Sldjc1Vsmoch5f_PRDTyV-tUjvplVc)
> 
> 您好，这个版本有点旧了，麻烦下载最新版本体验。最新版支持对当前任务标签进行编辑、删除，入口[同上](https://github.com/CVHub520/X-AnyLabeling/issues/339#issuecomment-2017283734)

大佬，目前咱们编辑标签是以新增的形式，标签目前支持删除吗？
打扰了
![image](https://github.com/CVHub520/X-AnyLabeling/assets/101043186/c42f8f84-e5a0-43c7-a26c-9c443f37e12f)

**Comment by CVHub520** [comment]
> > > 大佬，侧边栏标注里的各个Label，要是实现可以编辑、删除，这个功能复杂吗 ![image](https://private-user-images.githubusercontent.com/101043186/316382024-9db69857-3500-45ba-8b53-06943c8a56ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTA5OTQsIm5iZiI6MTcxMTM1MDY5NCwicGF0aCI6Ii8xMDEwNDMxODYvMzE2MzgyMDI0LTlkYjY5ODU3LTM1MDAtNDViYS04YjUzLTA2OTQzYzhhNTZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwNzExMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2U3ZDQ2Y2MwYjg5ODg1ZDQ1NjkwOGJlZWRhYWE1Mjc3Y2UzOWY3N2QwMDcyZTJiNDRkMTFhMTdkZGU5MTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L4RT_qZp-YhC8Sldjc1Vsmoch5f_PRDTyV-tUjvplVc)
> > 
> > 
> > 您好，这个版本有点旧了，麻烦下载最新版本体验。最新版支持对当前任务标签进行编辑、删除，入口[同上](https://github.com/CVHub520/X-AnyLabeling/issues/339#issuecomment-2017283734)
> 
> 大佬，目前咱们编辑标签是以新增的形式，标签目前支持删除吗？ 打扰了 ![image](https://github.com/CVHub520/X-AnyLabeling/assets/101043186/c42f8f84-e5a0-43c7-a26c-9c443f37e12f)

已支持。
