### ISSUE TITLE
COCO2custom converter is not working

### ISSUE THREAD

**Issue by hdnh2006** [CVHub520/X-AnyLabeling#34]
Hello,

I am trying to convert a dataset from coco to labelme format and it seems there's some error dealing with dictionaries:

```
python tools/label_converter.py --src_path ~/Downloads/Tayqan_1.v5i.coco/train/_annotations.coco.json --dst_path ~/Downloads/Tayqan_1.v5i.coco/train/ --img_path ~/Downloads/Tayqan_1.v5i.coco/train/ --mode coco2custom
Starting conversion to coco2custom format...
Traceback (most recent call last):
  File "tools/label_converter.py", line 399, in <module>
    main()
  File "tools/label_converter.py", line 392, in main
    converter.coco_to_custom(args.src_path, args.dst_path, args.img_path)
  File "tools/label_converter.py", line 289, in coco_to_custom
    "imagePath": img_dic[dic_info["file_name"]],
KeyError: 'PHOTO-2022-12-07-00-31-19-2_jpg.rf.00a6a50ec0c8efe0815b459e14226c46.jpg'
```

I think the problem is your code is handling the filename as a key of the dictionary. 

I am attaching my json in case you want to check the error.
[_annotations.coco.zip](https://github.com/CVHub520/X-AnyLabeling/files/12182267/_annotations.coco.zip)

**Comment by hdnh2006** [comment]
Additionally, the repo is not able to convert segmentation, just bboxes. Woyld you plan to add this feature?

**Comment by CVHub520** [comment]
Yeah, we will add this feature later.

**Comment by hdnh2006** [comment]
Solved with [this](https://github.com/CVHub520/X-AnyLabeling/pull/35#event-9995639576) PR.
