### ISSUE TITLE
The problem of labeling key points

### ISSUE THREAD

**Issue by yywjacson** [CVHub520/X-AnyLabeling#341]
Mark the rotation box + key points. Can you mark all the boxes first and then add key points one by one?
Thanks for the answer！

**Comment by CVHub520** [comment]
Hi, @yywjacson:

Thank you very much for your suggestion. 

Yes, the current support for key point marking in X-AnyLabeling is not perfect, and I plan to take time later to optimize it. 

At the same time, we also warmly welcome PRs. Let's work together to create a fantastic application.

Best regards,
CVHub
