### ISSUE TITLE
切换模型后，显存没有立即释放，导致切换到后续模型的时候，提示显存不足

### ISSUE THREAD

**Issue by 1240498481** [CVHub520/X-AnyLabeling#343]
第一次使用的是Segment Anything(Vit-Large Quant)，标注完一两个以后，切换到GroundingSAM-SwingB with HQ-SAM-VitL-Qint8时，提示 
```
Error in loading model: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: 
/onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, 
onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 2097152

2024-03-28 10:06:48.673006688 [E:onnxruntime:, inference_session.cc:1785 operator()] Exception during initialization: 
/onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, 
onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 2097152
```
直接加载GroundingSAM-SwingB with HQ-SAM-VitL-Qint8模型是可以的

**Comment by CVHub520** [comment]
> 第一次使用的是Segment Anything(Vit-Large Quant)，标注完一两个以后，切换到GroundingSAM-SwingB with HQ-SAM-VitL-Qint8时，提示
> 
> ```
> Error in loading model: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: 
> /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, 
> onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 2097152
> 
> 2024-03-28 10:06:48.673006688 [E:onnxruntime:, inference_session.cc:1785 operator()] Exception during initialization: 
> /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, 
> onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 2097152
> ```
> 
> 直接加载GroundingSAM-SwingB with HQ-SAM-VitL-Qint8模型是可以的

可能没完全释放掉，这个目前有待完善。
