### ISSUE TITLE
AI预标注，有办法可以不清除之前模型的标注结果吗？

### ISSUE THREAD

**Issue by youyuge34** [CVHub520/X-AnyLabeling#345]
在目标检测任务上，打标好了100张图片，这时候我想增加一个检测类别 例如键盘，可以使用 GroundingDino 来单独做键盘的预标注。但是现在软件会清除之前的标注结果。
目前我能想到的方案就是手动合并 2个json标注结果。请问作者，有更优雅的解决方案吗？

**Comment by CVHub520** [comment]
hello，这个可以自己改下源码，只需要将 [replace](https://github.com/CVHub520/X-AnyLabeling/blob/16d7f2330d6e79e771f743bfce5cb88d3515f99a/anylabeling/services/auto_labeling/grounding_dino.py#L211) 参数设置为`False`即可。

**Comment by youyuge34** [comment]
感谢，已成功
