### ISSUE TITLE
Request for some semantic segmentation models, not instance segmentation.

### ISSUE THREAD

**Issue by Anleeno-Xu** [CVHub520/X-AnyLabeling#346]
Hi,  dear author, do you have any plans to support mainstream semantic segmentation models? Like PaddleSeg or others. Thanks.

**Comment by CVHub520** [comment]
Hi, @Anleeno-Xu:

Thank you for your interest!

Unfortunately, there are currently no plans to support models like PaddleSeg. However, you can use SAM series models for segmentation and directly export semantic segmentation masks through X-AnyLabeling. 

We also warmly welcome you to submit a PR. If you need further assistance, please feel free to contact.

Best wishes!
