### ISSUE TITLE
为何我无法使用gpu运行

### ISSUE THREAD

**Issue by Mayuyu007123** [CVHub520/X-AnyLabeling#347]
app_info.py i changed to GPU, but still using my cpu to labeling

**Comment by CVHub520** [comment]
您好，可以参考下https://github.com/CVHub520/X-AnyLabeling/issues/188.

**Comment by Mayuyu007123** [comment]
i am using 
![image](https://github.com/CVHub520/X-AnyLabeling/assets/102665743/b088d64b-2956-4e52-b905-6a1d0e2dbace)

the requirements-gpu.txt :

opencv-contrib-python-headless==4.7.0.72
PyQt5==5.15.7
imgviz==1.5.0
natsort==8.1.0
termcolor==1.1.0
PyYAML==6.0
onnx==1.13.1
onnxruntime-gpu>=1.17.0
qimage2ndarray==1.10.0
lapx==0.5.5
darkdetect==0.8.0
tqdm
scipy
shapely
pyclipper
filterpy
tokenizers


but after pip install the pip install -r requirements-gpu-dev.txt



ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
inference 0.9.11 requires onnxruntime<=1.15.1, which is not installed.
autodistill-yolov8 0.1.4 requires ultralytics==8.0.81, but you have ultralytics 8.1.34 which is incompatible.
inference 0.9.11 requires shapely<=2.0.1, but you have shapely 2.0.3 which is incompatible.
inference-gpu 0.9.12rc1 requires inference-cli==0.9.12rc1, but you have inference-cli 0.9.11 which is incompatible.
inference-gpu 0.9.12rc1 requires onnxruntime-gpu<=1.15.1, but you have onnxruntime-gpu 1.17.1 which is incompatible.
inference-gpu 0.9.12rc1 requires shapely<=2.0.1, but you have shapely 2.0.3 which is incompatible.

**Comment by Mayuyu007123** [comment]
when i downgrade to the compatible version is same still using cpu

**Comment by Mayuyu007123** [comment]
> 您好，可以参考下#188.
我發現直接使用gpu的exe選擇 model的時候就會沒有回應然後應用程式直接跳出來,但是cpu的exe沒有

**Comment by CVHub520** [comment]
We highly recommend that you create a separate virtual environment and install the compatible version of the ORT-GPU package to avoid dependency conflicts.
