### ISSUE TITLE
unsupported icc profile class 70727472

### ISSUE THREAD

**Issue by cunesewangst** [CVHub520/X-AnyLabeling#348]
<img width="768" alt="微信图片_20240329105418" src="https://github.com/CVHub520/X-AnyLabeling/assets/101552921/0eb15d92-f323-41b7-9ef4-5f956863bb8d">

**Comment by cunesewangst** [comment]
一打开一两百兆的图像就开始出现这种报错，请问最多支持多大的图片啊

**Comment by CVHub520** [comment]
> <img alt="微信图片_20240329105418" width="768" src="https://private-user-images.githubusercontent.com/101552921/317940720-0eb15d92-f323-41b7-9ef4-5f956863bb8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTE0NTUsIm5iZiI6MTcxMTY5MTE1NSwicGF0aCI6Ii8xMDE1NTI5MjEvMzE3OTQwNzIwLTBlYjE1ZDkyLWYzMjMtNDFiNy05ZWY0LTVmOTU2ODYzYmI4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwNTQ1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTZjYjczNzkyYWFkNTU3Yzk1MjI0YWRjY2UzZWZhNjU3MTM0NTc5NzdjZjE2MjY0Mzg1OWRkNzhmYmZlNzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.21qM5T1rR2mBKXPDth5iQymgj-fXoe1DCWiMnl5GmNA">

您好，考虑到 OpenCV 库将其限制为 SHORT MAX (32767) 值，似乎不支持大于该值的大小。
