### ISSUE TITLE
How to Associate Keypoints with Multiple Targets in Image Annotation?

### ISSUE THREAD

**Issue by GalSang17** [CVHub520/X-AnyLabeling#351]
假如我的图像中是多个目标，但我发现软件标注后的关键点是离散的，没有和目标框关联起来，现在软件是支持的吗？

**Comment by CVHub520** [comment]
> 假如我的图像中是多个目标，但我发现软件标注后的关键点是离散的，没有和目标框关联起来，现在软件是支持的吗？

您好，目前是通过设置group_id来绑定和关联的，这块体验暂时比较差，后面需要优化下，敬请留意，同时也欢迎提PR。

**Comment by wxl0105** [comment]
有没有具体的yaml文件格式

**Comment by CVHub520** [comment]
> 有没有具体的yaml文件格式

您好，这个跟yaml文件无关。
