### ISSUE TITLE
RAM Performance Discrepancy: Significant Difference Between Measured and Demo Results

### ISSUE THREAD

**Issue by longchuanshu** [CVHub520/X-AnyLabeling#352]
RAM实测效果跟实际在RAM的demo中差异很大，这是转onnx导致的么？

**Comment by CVHub520** [comment]
> RAM实测效果跟实际在RAM的demo中差异很大，这是转onnx导致的么？

您好，RAM这个模型很早前整的，我记得差异应该不是很大吧？当然也有可能是我转换的方式不太对，具体的差异我没评测过，这边主要是提供一个模板给大家用，具体的性能或者速度等方面的提升还是建议根据自己的任务去做定制化的适配。

另外，我看官方好像还出了个 RAM++，改天抽空可以试试。

**Comment by CVHub520** [comment]
Hey there! @longchuanshu, just wanted to let you know that the issue with the gap has been addressed and fixed in commit #657.
