### ISSUE TITLE
Directory Instructions: Navigation Links Not Working, Pages Not Loading Properly

### ISSUE THREAD

**Issue by monkeycc** [CVHub520/X-AnyLabeling#353]
目录说明，不能正常的导航链接
页面不能正常跳转

## 📄 目录

- [🥳 新功能](#🥳-新功能-⏏️)
- [👋 简介](#👋-简介-⏏️)
- [🔥 亮点](#🔥-亮点-⏏️)
  - [🗝️关键功能](#🗝️关键功能-)
  - [⛏️模型库](#⛏️模型库-)
- [📋 教程](#📋-教程-⏏️)
  - [📜 文档](#📜-文档-⏏️)
    - [🔜快速开始](#🔜-快速开始-⏏️)
    - [📋用户手册](#📋-用户手册-⏏️)
    - [🚀加载自定义模型](#🚀-加载自定义模型-⏏️)
  - [🧷快捷键](#🧷-快捷键-⏏️)
- [📧 联系](#📧-联系-⏏️)
- [✅ 许可](#✅-许可-⏏️)
- [🏷️ 引用](#🏷️-引用-⏏️)

**Comment by CVHub520** [comment]
您好，这个网页端是有点问题，本地的话是正常的。后面抽空再改改，感谢你的建议。
