### ISSUE TITLE
导出yolo格式出现问题

### ISSUE THREAD

**Issue by Mrtigerhandsome** [CVHub520/X-AnyLabeling#354]
照片标注及预览正常，但是导出yolo格式txt后出现数字大于1

**Comment by CVHub520** [comment]
> 这是json文件内容 { "version": "0.3.3", "flags": {}, "shapes": [ { "label": "1", "text": "", "points": [ [ 1799, 806 ], [ 2023, 1043 ] ], "group_id": null, "shape_type": "rectangle", "flags": {} }, { "label": "1", "text": "", "points": [ [ 1032, 701 ], [ 1712, 1175 ] ], "group_id": null, "shape_type": "rectangle", "flags": {} } ], "imagePath": "calf-standing-001629-001646_1.jpg", "imageData": null, "imageHeight": 2560, "imageWidth": 1440 } 这张图片是1440*2560，但是在json文件中这两个参数反了，导致大于一，这应该是是bug的原因

您好，你这个是半年前的版本了吧，中间已经迭代了上百次了，麻烦更新到最新版本。

**Comment by hnjerryluo** [comment]
> > 这是json文件内容 { "version": "0.3.3", "flags": {}, "shapes": [ { "label": "1", "text": "", "points": [ [ 1799, 806 ], [ 2023, 1043 ] ], "group_id": null, "shape_type": "rectangle", "flags": {} }, { "label": "1", "text": "", "points": [ [ 1032, 701 ], [ 1712, 1175 ] ], "group_id": null, "shape_type": "rectangle", "flags": {} } ], "imagePath": "calf-standing-001629-001646_1.jpg", "imageData": null, "imageHeight": 2560, "imageWidth": 1440 } 这张图片是1440*2560，但是在json文件中这两个参数反了，导致大于一，这应该是是bug的原因
> 
> 您好，你这个是半年前的版本了吧，中间已经迭代了上百次了，麻烦更新到最新版本。

新版和旧版标注的不兼容吗？升级新版进行了大量标注后才发现JSON内的points数组定义与之前不同了，之前标注和新标注必须区分出来使用不同版本的convert进行转换。

**Comment by hnjerryluo** [comment]
> > > > 这是json文件内容 { "version": "0.3.3", "flags": {}, "shapes": [ { "label": "1", "text": "", "points": [ [ 1799, 806 ], [ 2023, 1043 ] ], "group_id": null, "shape_type": "rectangle", "flags": {} }, { "label": "1", "text": "", "points": [ [ 1032, 701 ], [ 1712, 1175 ] ], "group_id": null, "shape_type": "rectangle", "flags": {} } ], "imagePath": "calf-standing-001629-001646_1.jpg", "imageData": null, "imageHeight": 2560, "imageWidth": 1440 } 这张图片是1440*2560，但是在json文件中这两个参数反了，导致大于一，这应该是是bug的原因
> > > 
> > > 
> > > 您好，你这个是半年前的版本了吧，中间已经迭代了上百次了，麻烦更新到最新版本。
> > 
> > 
> > 新版和旧版标注的不兼容吗？升级新版进行了大量标注后才发现JSON内的points数组定义与之前不同了，自己修改了下才转换成功，之前一直没注意到这问题，导致训练结果始终异常，后来才发现是标注转换的问题。
> 
> 您好，兼容的，只不过是针对矩形框将两点模式转换为四点模式。
你好，我在使用label_converter进行YOLO格式转换时，旧版标注的结果会造成报错 
File "E:\AI\X-AnyLabeling-main\tools\label_converter.py", line 248, in custom_to_yolov5
    x_center = (points[0][0] + points[2][0]) / (2 * image_width)
                               ~~~~~~^^^
IndexError: list index out of range
我是修改以下才转换成功，不知是否是我使用的问题。
`# 增加兼容旧版本
                if len(points) == 2:
                    # 转换成四个坐标点的形式，顺序为左上、右上、右下、左下
                    rect_coords = [
                        points[0],  # 左上角坐标
                        [points[1][0], points[0][1]],  # 右上角坐标
                        points[1],  # 右下角坐标
                        [points[0][0], points[1][1]]  # 左下角坐标
                    ]
                    points = rect_coords`

**Comment by CVHub520** [comment]
> > > > > 这是json文件内容 { "version": "0.3.3", "flags": {}, "shapes": [ { "label": "1", "text": "", "points": [ [ 1799, 806 ], [ 2023, 1043 ] ], "group_id": null, "shape_type": "rectangle", "flags": {} }, { "label": "1", "text": "", "points": [ [ 1032, 701 ], [ 1712, 1175 ] ], "group_id": null, "shape_type": "rectangle", "flags": {} } ], "imagePath": "calf-standing-001629-001646_1.jpg", "imageData": null, "imageHeight": 2560, "imageWidth": 1440 } 这张图片是1440*2560，但是在json文件中这两个参数反了，导致大于一，这应该是是bug的原因
> > > > 
> > > > 
> > > > 您好，你这个是半年前的版本了吧，中间已经迭代了上百次了，麻烦更新到最新版本。
> > > 
> > > 
> > > 新版和旧版标注的不兼容吗？升级新版进行了大量标注后才发现JSON内的points数组定义与之前不同了，自己修改了下才转换成功，之前一直没注意到这问题，导致训练结果始终异常，后来才发现是标注转换的问题。
> > 
> > 
> > 您好，兼容的，只不过是针对矩形框将两点模式转换为四点模式。
> > 你好，我在使用label_converter进行YOLO格式转换时，旧版标注的结果会造成报错
> > File "E:\AI\X-AnyLabeling-main\tools\label_converter.py", line 248, in custom_to_yolov5
> > x_center = (points[0][0] + points[2][0]) / (2 * image_width)
> > ~~~~~~^^^
> > IndexError: list index out of range
> > 我是修改以下才转换成功，不知是否是我使用的问题。
> 
> # 增加兼容旧版本
> ```
>           if len(points) == 2:
>               # 转换成四个坐标点的形式，顺序为左上、右上、右下、左下
>               rect_coords = [
>                   points[0],  # 左上角坐标
>                   [points[1][0], points[0][1]],  # 右上角坐标
>                   points[1],  # 右下角坐标
>                   [points[0][0], points[1][1]]  # 左下角坐标
>               ]
>               points = rect_coords
> ```

您好，这个很早就兼容了，你这边可能没更新到新版本。
