### ISSUE TITLE
旋转框导入和导出问题

### ISSUE THREAD

**Issue by sjxxrh** [CVHub520/X-AnyLabeling#356]
您好，我想问下这个旋转框的标签文件不能导入xml的标签文件吗？还有一个问题是在软件上画旋转框只能保存json文件吗？不能导出旋转框的xml标签文件吗？

**Comment by CVHub520** [comment]
> 您好，我想问下这个旋转框的标签文件不能导入xml的标签文件吗？还有一个问题是在软件上画旋转框只能保存json文件吗？不能导出旋转框的xml标签文件吗？

您好，当前仅支持主流的格式，不同训练框架需要的格式大都不同，不可能去适配每一个。
软件标注默认都会通过内置的模板（*.json）文件进行保存，用户可以根据菜单栏接口导出主流的格式。
个别小众的标签文件格式需要自行根据json文件写脚本去解析和转换。
