### ISSUE TITLE
Error in predict_shapes: list index out of range问题

### ISSUE THREAD

**Issue by Amberonetwo** [CVHub520/X-AnyLabeling#357]
大佬您好，在使用yolov8训练了一个旋转模型导入后如图，类别经反复对比，无法知其原因，求作者大大提提建议
![image](https://github.com/CVHub520/X-AnyLabeling/assets/134777873/4bf0961d-2796-4d6c-b8da-180d52ee6316)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/134777873/3ac07326-464d-43f0-9bc9-6a9c7935ffdf)
始终报错Error in predict_shapes: list index out of range

**Comment by CVHub520** [comment]
您好，YOLOv8 旋转检测的配置文件请参考[这个](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov8s_obb.yaml)，请不要随意添加多余的参数。

**Comment by Amberonetwo** [comment]
谢谢作者大大这么快回复我的问题，可是很显然这个依然会抱上面的错误
![image](https://github.com/CVHub520/X-AnyLabeling/assets/134777873/583b75c7-140b-4bdf-a2b1-516790978f3d)

**Comment by Amberonetwo** [comment]
谢谢作者大大，问题已经解决，是type配置不正确，
