### ISSUE TITLE
旋转框标注可以直接转成yolov8的OBB格式标签吗？

### ISSUE THREAD

**Issue by isOreo** [CVHub520/X-AnyLabeling#358]
旋转框标注可以直接转成yolov8的OBB格式标签吗？转DOTA格式报错：list index out of range

**Comment by CVHub520** [comment]
> 旋转框标注可以直接转成yolov8的OBB格式标签吗？转DOTA格式报错：list index out of range

可以的，麻烦根据教程自行设置导出。

**Comment by isOreo** [comment]
请问哪有教程？
---- 回复的原邮件 ----
***@***.***>发送日期2024年04月05日 19:13 ***@***.***> ***@***.***>,
***@***.***>主题Re: [CVHub520/X-AnyLabeling] 旋转框标注可以直接转成yolov8的OBB格式标签吗？ (Issue #358)
旋转框标注可以直接转成yolov8的OBB格式标签吗？转DOTA格式报错：list index out of range
可以的，麻烦根据教程自行设置导出。

**Comment by CVHub520** [comment]
参考[教程](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E6%A0%87%E7%AD%BE%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA)。
