### ISSUE TITLE
Auto-Annotation Crashes on Windows 10 with YOLOv5-RestNet50 Model

### ISSUE THREAD

**Issue by youlikesoilove** [CVHub520/X-AnyLabeling#359]
我是windows10平台，我直接下载了EXE格式文件。
我之前用了Labelme标注工具标注的一些标注文件和图像正确导入后。这都是正常的，显示也正常。
我做水面目标船的目标检测标注，当我选用模型YOLOv5-RestNet50，下载完成。提示“模型已加载。已经准备好进行数据标注。”
当我点击“运行”后，就闪退。并且无任何报错框弹出。
我想问这是为什么？是需要导入自己训练的模型吗？还是因为什么？

**Comment by youlikesoilove** [comment]
补充：我用的是GPU版的

**Comment by CVHub520** [comment]
> 补充：我用的是GPU版的

您好，GPU版本闪退是因为与当前CUDA环境不兼容，请下载源码根据教程安装使用，或者建议直接使用CPU环境，可满足90%的应用场景。

**Comment by youlikesoilove** [comment]
额、我检查了、应该是GPU的问题。

**Comment by JimmyLauren** [comment]
你好，我这边的同样是GPU的版本，刚开始是可以用AI自动标注的，后面就突然闪退了，这个大概是什么问题呢？

**Comment by CVHub520** [comment]
> 你好，我这边的同样是GPU的版本，刚开始是可以用AI自动标注的，后面就突然闪退了，这个大概是什么问题呢？

您好，建议用源码运行，方便查看完整的报错信息。
