### ISSUE TITLE
Process finished with exit code -1073740791 (0xC0000409)

### ISSUE THREAD

**Issue by 202112213501021** [CVHub520/X-AnyLabeling#360]
I have a problem with software crashing. After I imported a folder with many pictures into the software, I wanted to replace the current picture with a new one, so I manually imported a single picture and the software crashing. I'm using the latest version 2.3.5.Hope to get your reply as soon as possible, help me!

**Comment by 202112213501021** [comment]
Hope to get your reply as soon as possible, help me!

**Comment by CVHub520** [comment]
Hi @202112213501021, thank you for bringing this issue to our attention.

We recommend running the source code instead of using the compiled software directly. Without detailed information, troubleshooting the issue becomes challenging.

**Comment by 202112213501021** [comment]
> 嗨，感谢您提请我们注意这个问题。
> 
> 我们建议运行源代码，而不是直接使用编译后的软件。如果没有详细信息，则对问题进行故障排除变得具有挑战性。

I'm just running the source code

**Comment by CVHub520** [comment]
这个应该是Pycharm的问题，建议自行上网搜索解决方案或使用vscode等替代工具。
