### ISSUE TITLE
关于MOT标注的功能

### ISSUE THREAD

**Issue by youlikesoilove** [CVHub520/X-AnyLabeling#361]
您的工作确实很伟大，我研究了下午一会儿，已经能够上手，首先感谢您们相关的工作。
我有以下问题：
第一、我了解到X-AnyLabeling工具是不能直接进行连续帧图片的目标跟踪数据及制作的，我是需要将制作成Video吗？
第二、我通过阅读user_guide.md，了解到您的工具是基于目标跟踪模型进行自动标注的（应该都是基于COCO数据集），我是否能够手动标注MOT数据集？（COCO中boat类型的类别较少，检测精度不高）

**Comment by CVHub520** [comment]
您好，首先感谢您 @youlikesoilove  的关注。现在回答下关于您提到的两个问题：

> 第一、我了解到X-AnyLabeling工具是不能直接进行连续帧图片的目标跟踪数据及制作的，我是需要将制作成Video吗？

X-AnyLabeling 工具目前是支持对连续帧图片进行自动目标跟踪的，您不需要制作成 Video，可以直接按下快捷键 `Ctrl+U` 以文件夹的形式导入当前批次的连续帧。

> 第二、我通过阅读user_guide.md，了解到您的工具是基于目标跟踪模型进行自动标注的（应该都是基于COCO数据集），我是否能够手动标注MOT数据集？（COCO中boat类型的类别较少，检测精度不高）

目前自动标注功能只是简单提供两个 MOT 模型示例，正如您所看到的，例如 ByteTrack 等跟踪模型；这边建议您可以根据自己的任务简单训练一个目标检测器，只需简单更换模型路径即可替换原有的 COCO 预训练检测器。当然，你这边也可以手动标注 MOT 数据集，只需设置 group_id 和 label 字段即可。
