### ISSUE TITLE
seek help

### ISSUE THREAD

**Issue by 202112213501021** [CVHub520/X-AnyLabeling#362]
I want to know which piece of the source code controls the mask of the tag, like if I click head：
![image](https://github.com/CVHub520/X-AnyLabeling/assets/141103647/98a0593b-84fb-43c2-8b42-5341691d5405)
How do I get the clicked label, and how do I export only this piece of mask？

**Comment by CVHub520** [comment]
Hi, you can refer to the following link for the relevant information: [canvas.py](https://github.com/CVHub520/X-AnyLabeling/blob/c57412141e177d8e58e00c9360c53f80290e80f4/anylabeling/views/labeling/widgets/canvas.py#L393C17-L393C18).

**Comment by 202112213501021** [comment]
> Hi, you can refer to the following link for the relevant information: [canvas.py](https://github.com/CVHub520/X-AnyLabeling/blob/c57412141e177d8e58e00c9360c53f80290e80f4/anylabeling/views/labeling/widgets/canvas.py#L393C17-L393C18).
Can I export the mask of this piece separately, it is very important to me!!!

**Comment by CVHub520** [comment]
> > Hi, you can refer to the following link for the relevant information: [canvas.py](https://github.com/CVHub520/X-AnyLabeling/blob/c57412141e177d8e58e00c9360c53f80290e80f4/anylabeling/views/labeling/widgets/canvas.py#L393C17-L393C18).
> > Can I export the mask of this piece separately, it is very important to me!!!Can you help me

Sure. If you want to export the specificed mask you can refer to this [toturial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md#annotations-uploadexport).

**Comment by CVHub520** [comment]
Yeap. FIrstly, tell me which type, e.g., yolo, coco, voc or the others are you want to export?

**Comment by 202112213501021** [comment]
> Yeap. FIrstly, tell me which type, e.g., yolo, coco, voc or the others are you want to export?

I want to convert to a mask binary image

**Comment by CVHub520** [comment]
Understood. You might want to follow the tutorial as outlined earlier. If everything is set up correctly, it should generate the corresponding binary mask image based on your specified color map, and it will automatically ignore any undefined labels.

**Comment by 202112213501021** [comment]
> Understood. You might want to follow the tutorial as outlined earlier. If everything is set up correctly, it should generate the corresponding binary mask image based on your specified color map, and it will automatically ignore any undefined labels.

Sorry, my meaning is not clear. I say again.If I have three labeled labels, I only want to export one of them, so I just asked you at the beginning, how to select the current label that my mouse clicked

**Comment by CVHub520** [comment]
As I mentioned above, you can only fill in the category you need in the export template and then try to export the mask image directly. Usually, if it goes smoothly, the result will screen out the undefined categories.

**Comment by 202112213501021** [comment]
> As I mentioned above, you can only fill in the category you need in the export template and then try to export the mask image directly. Usually, if it goes smoothly, the result will screen out the undefined categories.

What I'm going to do now is add a button on top of your software that allows me to export arbitrary masks, so I want to be a little bit smart, now, I want to get a very important variable.
The category selected by my mouse, which variable it is,
like
![image](https://github.com/CVHub520/X-AnyLabeling/assets/141103647/65031be6-c76c-401b-bfcd-62fb2a1c7536)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/141103647/1e0d1083-7d88-412d-b7f0-3faee2df30f9)
or
![image](https://github.com/CVHub520/X-AnyLabeling/assets/141103647/b8940b9a-19a7-4b8c-9059-1eaff73e4cb6)

**Comment by CVHub520** [comment]
Understood. Dose you need a feature that allows you to automatically export the corresponding binary mask image by pressing the shortcut key after the mouse clicks on the target of interest, right? 

If this is the case, that feature is a personalized requirement, and need to modify the source code to adapt by yourself.
