### ISSUE TITLE
x-anylabeling标签换文件夹就打不开

### ISSUE THREAD

**Issue by yywjacson** [CVHub520/X-AnyLabeling#363]
旋转框标注，标签文件放错文件夹了，移到其他文件夹就在软件中打不开了
![image](https://github.com/CVHub520/X-AnyLabeling/assets/129293851/5cdd1d4a-61ef-4eb5-b588-3b539290dac1)

**Comment by CVHub520** [comment]
菜单栏-文件-更改输出目录，将保存目录重定位到你的标签文件夹。

**Comment by yywjacson** [comment]
> 菜单栏-文件-更改输出目录，将保存目录重定位到你的标签文件夹。

不是，更改了，报错
![标签错误](https://github.com/CVHub520/X-AnyLabeling/assets/129293851/d75d5461-355f-48c6-ac11-7a766a3fda7d)

**Comment by CVHub520** [comment]
> > 菜单栏-文件-更改输出目录，将保存目录重定位到你的标签文件夹。
> 
> 不是，更改了，报错 ![标签错误](https://private-user-images.githubusercontent.com/129293851/320340864-d75d5461-355f-48c6-ac11-7a766a3fda7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTU1OTUsIm5iZiI6MTcxMjU1NTI5NSwicGF0aCI6Ii8xMjkyOTM4NTEvMzIwMzQwODY0LWQ3NWQ1NDYxLTM1NWYtNDhjNi1hYzExLTdhNzY2YTNmZGE3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwNTQ4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWNjNTUyYjc5YjQ1NDRmOWJiMzk5NmQyZGFmYTk0ZDE0NmNlMWM3N2E4YjAwYjAzOWZmZDBkNjgyZWRhN2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AUq1upRToTBQKmfQvVUPtDCyKjwNH_JF1nlg_8ZBcpw)

好的，你这边当前使用的版本号麻烦提供下。
