### ISSUE TITLE
模型预测的时候效果挺好转化成onnx来标注就没有什么效果

### ISSUE THREAD

**Issue by 2375963934a** [CVHub520/X-AnyLabeling#364]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/140362467/ccd6e4e8-ab9e-4802-ba79-85883e1359e7)
这个图像都不进行标注

**Comment by 2375963934a** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/140362467/d21d149a-6e5b-4349-b258-fa6b93ebd108)

**Comment by CVHub520** [comment]
Onnx模型与Pt模型的精度一般只会相差一点，这种情况就是没正确转换。
