### ISSUE TITLE
[Question] 如何修改应用程序字体样式与字体大小？

### ISSUE THREAD

**Issue by jiangtangaaaa** [CVHub520/X-AnyLabeling#365]
大佬，你的菜单栏字体大小是写死的吗？
我尝试把菜单栏字体变大一点，menu.setStyleSheet("font-size: 50px;")  或者font = QtGui.QFont() font.setPointSize(50) menu.setFont(font)
都不起作用
希望大佬指点我一下。万分感谢！！

**Comment by CVHub520** [comment]
您好，如需修改字体样式及大小，可参考如下示例修改[app.py](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/app.py)：
```python
    ...
    win = MainWindow(
        app,
        config=config,
        filename=filename,
        output_file=output_file,
        output_dir=output_dir,
    )
  ...
      style_sheet = """
      QWidget {
          font-size: 18px;
          font-family: "Segoe UI";
      }
      """
      win.setStyleSheet(style_sheet)
    ...
```

**Comment by jiangtangaaaa** [comment]
@CVHub520 感谢大佬指点我！感谢
大佬，我多嘴问一句，我测试侧边栏保存按钮，它一直是灰色禁用状态，它的作用是什么呢？在什么场景下会启用呢？
![image](https://github.com/CVHub520/X-AnyLabeling/assets/101043186/3a8f43d3-e112-4fc4-8a75-ed1d42a6606c)

**Comment by CVHub520** [comment]
一般勾选了自动保存，这个按钮就没有作用了。

**Comment by jiangtangaaaa** [comment]
> 一般勾选了自动保存，这个按钮就没有作用了。

谢谢大佬~~打扰了
