### ISSUE TITLE
【BUG】关于在长方形和多边形标注切换的Bug

### ISSUE THREAD

**Issue by jiangtangaaaa** [CVHub520/X-AnyLabeling#368]
大佬您好，刚才发现一个bug，我不知道怎么规避它，由于不能上传视频，我尽量的描述的清晰点，打扰您了！
step1:点击打开文件或者文件夹按钮
step2:点击旋转框按钮，点击一下
step3:然后点击多边形标注按钮
现象：软件闪退  必现
————————————
step2：点击多边形按钮
step3：画两下或者画三下
step4：点击长方形标注
现象：软件闪退  偶现
(点击快捷键同样适用)

这个操作虽然不属于正常操作，但是界面闪退的这个问题，我该怎么规避呢？
再次希望您指点一下我，万分感谢

**Comment by CVHub520** [comment]
> 大佬您好，刚才发现一个bug，我不知道怎么规避它，由于不能上传视频，我尽量的描述的清晰点，打扰您了！ step1:点击打开文件或者文件夹按钮 step2:点击旋转框按钮，点击一下 step3:然后点击多边形标注按钮 现象：软件闪退 必现 ———————————— step2：点击多边形按钮 step3：画两下或者画三下 step4：点击长方形标注 现象：软件闪退 偶现 (点击快捷键同样适用)
> 
> 这个操作虽然不属于正常操作，但是界面闪退的这个问题，我该怎么规避呢？ 再次希望您指点一下我，万分感谢

可以调试下程序，在异常处采用try-except规避。
