### ISSUE TITLE
MOT postprocessing of drawing frames of trackings  and thereby a video

### ISSUE THREAD

**Issue by shuyueW1991** [CVHub520/X-AnyLabeling#369]
I really appreciate the work of X-AnyLabeling, which is MARVELLOUS. However, i find the postprocessing of MOT detection and tracking video should be added. Therefore I write a small snippet so that after MOT operation, you can run this script and you can get a movie.mp4 registering trackings of objects.

The code is here: [<script src="https://gist.github.com/shuyueW1991/2fa7b1726a22a168317b6a3fbd83c51b.js"></script>](url)

A capture of such image is like this:
![newframe_602](https://github.com/CVHub520/X-AnyLabeling/assets/28128426/99d9d0d9-7b1c-4cd5-bf33-f2ffc4606e7e)

There are two editable parts in the script:
The first input is the folder path of the frames and the csv filer path (which is default under folder <MOT>).
These can be edited under the line `if __name == '__main__':`
The second is at the beginning of code, i.e. `index2color` dict, where you should assign at least the index-color pairs as many as the most id one frame can get.
And there are still some comments that you can reference.

Anyway, I hope everyone encountering same problem can use it. Cheers.

**Comment by shuyueW1991** [comment]
添加了多目标跟踪视频的后处理 , 写了一个小程序使您可以在 MOT 操作之后运行此脚本，并获得记录对象轨迹的 movie.mp4

**Comment by CVHub520** [comment]
> 添加了多目标跟踪视频的后处理 , 写了一个小程序使您可以在 MOT 操作之后运行此脚本，并获得记录对象轨迹的 movie.mp4

Thank you for your valuable contribution to X-AnyLabeling!

**Comment by CVHub520** [comment]
#562

**Comment by CVHub520** [comment]
#602
