### ISSUE TITLE
下载了gpu版本的exe文件，根据onnx1.14安装了CUDA 11.6以及cudnn 8.5.0.69，但是加载segment anything（Vit-b Quant）模型还是报错。

### ISSUE THREAD

**Issue by Burrowsliu** [CVHub520/X-AnyLabeling#37]
博主您好：
我下载了gpu版本的exe执行文件，运行加载segment anything模型报错，onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page,make sure they're in PATH,and that your GPU is supported。
![1](https://github.com/CVHub520/X-AnyLabeling/assets/129054914/827b63a3-ce9b-4e8d-a311-3caa34abc8e2)

以下是我的操作步骤，帮忙看看是什么问题，多谢多谢！！！

1.我检查了CUDA版本，nvcc-V :
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:28:54_Pacific_Standard_Time_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0
![2](https://github.com/CVHub520/X-AnyLabeling/assets/129054914/dd06d08d-43e4-4d46-9acb-009da2ed3b49)
![3](https://github.com/CVHub520/X-AnyLabeling/assets/129054914/7ffa5dc4-4b56-40e5-9f91-df5ecdf450b1)

2.安装onnx要求的cudnn 8.5.0.96版本，并且将所有lib,include,bin文件拷贝到了CUDA 11.6的文件夹中。

3.进入CUDA安装路径：C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\extras\demo_suite运行bandwidthTest.exe以及deviceQuery.exe检测cudnn安装成功。
![4](https://github.com/CVHub520/X-AnyLabeling/assets/129054914/9cdd994c-571a-4dbd-9eec-521b68e2e344)
![5](https://github.com/CVHub520/X-AnyLabeling/assets/129054914/b83a1292-2484-4d14-946f-b22c1cc21d53)

4.使用cup版本的exe，运行segment anything (Vit-b Quant)模型没有问题，只是运行gpu版本exe会报错。
![6](https://github.com/CVHub520/X-AnyLabeling/assets/129054914/06a24661-cdb8-4fd7-8c8c-96af7a663a9d)

5.onnxruntime的要注，下载的CUDA与cudn.
![8](https://github.com/CVHub520/X-AnyLabeling/assets/129054914/4bfaa79d-828e-4c1a-9d5c-0ce667228e0a)

**Comment by June1124** [comment]
我也遇到了同样的问题，测试onnxrunitme输出以下信息
![image](https://github.com/CVHub520/X-AnyLabeling/assets/52447302/4b9a1b22-b4b8-4a13-8d52-9a2330da746b)

**Comment by CVHub520** [comment]
您好，已修复，请尝试 v0.2.0 新版本，后续更新一个Q&A具体介绍下如何自己编译。 @June1124 @Burrowsliu
