### ISSUE TITLE
How to install and run the downloaded executable file?

### ISSUE THREAD

**Issue by zwcity** [CVHub520/X-AnyLabeling#370]
https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.3.5/X-Anylabeling-Linux-CPU

@ubuntu:~/download$ ./X-Anylabeling-Linux-CPU
Traceback (most recent call last):
  File "app.py", line 19, in <module>
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIKZPgyI/libglib-2.0.so.0)
[14983] Failed to execute script 'app' due to unhandled exception!

**Comment by CVHub520** [comment]
Hi, @zwcity:

This is a problem with the system dependency libraries. You may need to search online for a solution. It appears that your system is missing the required `GLIBC_2.28` version. You might need to upgrade your GLIBC version to fix this issue.

**Comment by zwcity** [comment]
In fact, I need to run the software on a Ubuntu device that cannot connect to the network. So the method you mentioned for installing GLIBC_2.28 may not be very feasible. Is there any other way? I can run the source code normally in the local Conda environment, so I have tried using Conda to run in the same way in the Docker container, but it has not been successful and encountered this problem.
``` 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
Aborted (core dumped)
```
I have tried installing some related dependency files in the container, but none of them worked.

**Comment by CVHub520** [comment]
This [link](https://blog.csdn.net/LOVEmy134611/article/details/107212845) might be work.

**Comment by zwcity** [comment]
Thank you very much. It really worked
