### ISSUE TITLE
导出yolo标签问题

### ISSUE THREAD

**Issue by ashore927** [CVHub520/X-AnyLabeling#372]
你好！请问，如果我需要同时导出矩形标签和点标签，我应该怎样编辑classes.txt文件？

**Comment by CVHub520** [comment]
> 你好！请问，如果我需要同时导出矩形标签和点标签，我应该怎样编辑classes.txt文件？

您好，当前YOLO格式仅支持导出矩形标签或掩码标签，暂不支持导出点标签。
