### ISSUE TITLE
【question】向您请教一个问题

### ISSUE THREAD

**Issue by jiangtangaaaa** [CVHub520/X-AnyLabeling#374]
大佬您好，我是一名qt小白，特此向您请教一个问题
在打开标签管理界面之后，无法点击主窗口菜单栏和右上角的x号
![image](https://github.com/CVHub520/X-AnyLabeling/assets/101043186/c435f835-fa1b-4c1f-8d15-ae8d9d7cc041)

在打开统计总览的时候，主页面置灰冻结，同样无法打开其他窗口
![image](https://github.com/CVHub520/X-AnyLabeling/assets/101043186/c482b706-275e-4629-aa58-ec4d40b32db1)

这两个操作是怎么实现的，大佬

**Comment by CVHub520** [comment]
> 在打开标签管理界面之后，无法点击主窗口菜单栏和右上角的x号

A: 在打开标签管理界面时，主窗口本就不应该允许直接关闭，请先完成当前子窗口操作再关闭主窗口。

> 在打开统计总览的时候，主页面置灰冻结，同样无法打开其他窗口
同理，请先关闭当前子窗口再执行其它操作。

**Comment by jiangtangaaaa** [comment]
@CVHub520  我的意思是，您这个逻辑是怎么实现的，我想学习一下，谢谢大佬！
