### ISSUE TITLE
建议自定义模型目录

### ISSUE THREAD

**Issue by monkeycc** [CVHub520/X-AnyLabeling#375]
建议自定义模型目录
默认下载到C盘
会占用C盘空间

--------------------------------------------

最好展示模型列表 以及模型地址
方便用户批量下载

<urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
不然用户经常是下载不了模型
需要翻墙

----------------------------------------------

这样用户就可以下载全部模型
放到自定义的目录了

**Comment by CVHub520** [comment]
> 建议自定义模型目录,默认下载到C盘,会占用C盘空间

A: 用户可以自定义保存路径。

> 最好展示模型列表 以及模型地址，方便用户批量下载

A: 绝大多数场景不可能会用到全部模型。

> <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

A: 可以走网盘下载本地路径加载的方式。
