### ISSUE TITLE
矩形标注的标注文件,labelme打不开

### ISSUE THREAD

**Issue by monkeycc** [CVHub520/X-AnyLabeling#376]
矩形标注的标注文件,
labelme打不开

```python

  File "E:\anaconda3\envs\PY311\Lib\site-packages\labelme\app.py", line 1279, in loadLabels
    shape.flags.update(flags)
TypeError: 'NoneType' object is not iterable

```

**Comment by CVHub520** [comment]
X-AnyLabeling uses a four-point annotation mode, and internally it is compatible with other annotation tools like LabelMe. 

However, LabelMe is not compatible with X-AnyLabeling in return.
