### ISSUE TITLE
【BUG】Custom2YOLO 导出有bug，只能在输出文件夹不存在时，运行一次

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#38]
# 报错
```
(XAnyLabelingenv) D:\gitlib\github\BioVbreed\X-AnyLabeling>python tools/label_converter.py --src_path imgDB\images --dst_path imgDB\label\130xyolo --classes imgDB\la
bel\classes.txt --mode custom2yolo
Starting conversion to custom2yolo format...
Converting files:   0%|                                                                                                          | 1/1820 [00:00<04:01,  7.52file/s]
Traceback (most recent call last):
  File "tools/label_converter.py", line 399, in <module>
    main()
  File "tools/label_converter.py", line 372, in main
    os.makedirs(args.dst_path, exist_ok=False)
  File "C:\Users\zhenyuchen\.conda\envs\XAnyLabelingenv\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'imgDB\\label\\130xyolo'
```
# 输出结果
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/06b21d7a-4974-478a-a211-2673416badf4)

**Comment by aiyou9** [comment]
> # 报错
> ```
> (XAnyLabelingenv) D:\gitlib\github\BioVbreed\X-AnyLabeling>python tools/label_converter.py --src_path imgDB\images --dst_path imgDB\label\130xyolo --classes imgDB\la
> bel\classes.txt --mode custom2yolo
> Starting conversion to custom2yolo format...
> Converting files:   0%|                                                                                                          | 1/1820 [00:00<04:01,  7.52file/s]
> Traceback (most recent call last):
>   File "tools/label_converter.py", line 399, in <module>
>     main()
>   File "tools/label_converter.py", line 372, in main
>     os.makedirs(args.dst_path, exist_ok=False)
>   File "C:\Users\zhenyuchen\.conda\envs\XAnyLabelingenv\lib\os.py", line 223, in makedirs
>     mkdir(name, mode)
> FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'imgDB\\label\\130xyolo'
> ```
> 
> # 输出结果
> ![image](https://user-images.githubusercontent.com/15712822/257077694-06b21d7a-4974-478a-a211-2673416badf4.png)

# 修复
将这一行，从循环语句，移出到判断转换任务类型，其他的可能也需要移动
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/b5aaa56d-cef1-4e29-9853-dcc5ed1fd4a1)

**Comment by CVHub520** [comment]
您好，已修改。
