### ISSUE TITLE
gpu模式下使用自定义的模型遇到的错误

### ISSUE THREAD

**Issue by ClakChinese** [CVHub520/X-AnyLabeling#380]
以下是报错信息
————————
(yolo) PS F:\Project\X-AnyLabeling-main> & F:/Software/miniconda3/envs/yolo/python.exe f:/Project/X-AnyLabeling-main/anylabeling/app.py      
2024-04-19 07:46:53.5644568 [E:onnxruntime:Default, provider_bridge_ort.cc:1548 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 
126 "" when trying to load "F:\Software\miniconda3\envs\yolo\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is 
set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-04-19 07:46:53.6466415 [E:onnxruntime:Default, provider_bridge_ort.cc:1548 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 
126 "" when trying to load "F:\Software\miniconda3\envs\yolo\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Error in loading model: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.

QWindowsWindow::setGeometry: Unable to set geometry 2906x1017+0+23 (frame: 2922x1056-8-8) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x1017+0+23 (frame: 1936x1056-8-8) margins: 8, 31, 8, 8 minimum size: 2906x559 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=2922,598 maxtrack=0,0)
————————
报错中出现了一个我电脑上没有的路径(D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857)，我的电脑只有C盘和F盘，但是这个路径显示的是D盘，我在自己的脚本中引用onnxruntime并加载模型是可以正常加载，所以我猜测可能是不小心把CUDA PATH写成了固定的路径，也可能是我配置的有问题，望解答。

**Comment by tiancailin** [comment]
1：
onnxruntime(-gpu)回退到1.15，但是这个我不是特别确定，光回退这个还是报错，但是我懒得upgrade到1.17了
安装 tensorRT（这个我是装了才解决的）
2：
问候onnxruntime团队+老黄爪牙们的木琴吧，他们整体的依赖版本一塌糊涂

说一下我的环境，照着装应该没错
python:3.9.13
driver:551.76，为了玩游戏装的gameready版-_-
cuda runtime (12.1)
torch(2.2.2+cu121，stable version)
cudnn-windows-x86_64-8.9.6.50_cuda12-archive.zip
TensorRT-8.6.1.6.Windows10.x86_64.cuda-12.0.zip

别问我为啥知道这么详细，我刚坏了个硬盘重装了os、python、pytorch（然后就放着没管）
今天又要弄东西，才发现release版加载模型闪退，2.3.5的release版GUI界面不报错，我运行的2.0.0版才看得到报错信息
environment折腾了大半个晚上，我麻婆豆腐炒了都没趁热吃@_@
