### ISSUE TITLE
数据丢失

### ISSUE THREAD

**Issue by dzt-dzt** [CVHub520/X-AnyLabeling#382]
使用软件中 标签管理功能，隐藏标签的显示，最后关闭隐藏的标签时，发现对应框数据丢失，导出的文件里和自动保存的 json中都没有对应数据，但是并没有完全丢失，只是一部分框数据丢失

**Comment by CVHub520** [comment]
> 使用软件中 标签管理功能，隐藏标签的显示，最后关闭隐藏的标签时，发现对应框数据丢失，导出的文件里和自动保存的 json中都没有对应数据，但是并没有完全丢失，只是一部分框数据丢失

你应该是不小心勾选到了删除标签，按理说程序逻辑都是固定的，要么全部丢失，要不不会丢失。如果确实存在问题，请提供可以稳定复现的步骤。
