### ISSUE TITLE
Batch Generation of Masks with SAM or SAM-HQ Model Without Manual Clicking

### ISSUE THREAD

**Issue by wqrz** [CVHub520/X-AnyLabeling#383]
现在一幅图好像要一个一个点或者框选，才能生成mask， 我想能否一次性批量生成？ 
比如我输入瓶子， 他就自动把所有瓶子都生成mask？ 没找到这个功能

**Comment by CVHub520** [comment]
> 现在一幅图好像要一个一个点或者框选，才能生成mask， 我想能否一次性批量生成？ 比如我输入瓶子， 他就自动把所有瓶子都生成mask？ 没找到这个功能

您好，这个不是`SAM`的功能，可以参考下[T-Rex])(https://github.com/IDEA-Research/T-Rex)项目，遗憾的是目前暂未开源。

**Comment by wqrz** [comment]
https://segment-anything.com/demo

这个是sam的官方网页版demo， 上传一幅图后， 点击everything按钮就可以把图片都标注出所有的object， sam应该有这个功能啊

**Comment by CVHub520** [comment]
> https://segment-anything.com/demo
> 
> 这个是sam的官方网页版demo， 上传一幅图后， 点击everything按钮就可以把图片都标注出所有的object， sam应该有这个功能啊

您好，你这个跟你提的需求不是同一个。SAM 这个模式只是通过创建网格来模拟用户的点提示输入，得到所有的objects对象再做个过滤去重而已，达不到你说的针对单个目标分割成同类的目标，模型会倾向于把所有可能的目标分割出来。

全图分割功能暂时没有集成，用户可以自定义，改下源码适配下就行。

**Comment by mcmy** [comment]
> https://segment-anything.com/demo
> 
> 这个是sam的官方网页版demo， 上传一幅图后， 点击everything按钮就可以把图片都标注出所有的object， sam应该有这个功能啊

感觉sam的是屏幕上每个位置都打点看有没有可分割的对象

**Comment by CVHub520** [comment]
#602

**Comment by bugsyyu** [comment]
请问全图分割功能还会增加吗
