### ISSUE TITLE
需求：批量修改标注的label名称

### ISSUE THREAD

**Issue by AImagicAI** [CVHub520/X-AnyLabeling#385]
建议优化方案：
1.批量修改label名称；
2.统计文件夹下label标注名称类别；

**Comment by CVHub520** [comment]
您好，该功能早已支持。

> 1.批量修改label名称；

可以打开上方菜单栏->工具->标签管理；

> 2.统计文件夹下label标注名称类别；

可通过快捷键 `Ctrl+G` 查看。

**Comment by AImagicAI** [comment]
我还想，统计aaa这个label名，一共有多少张图像，这个支持吗？
