### ISSUE TITLE
【功能需求】希望自动使用上一个标签可以跨图片使用...

### ISSUE THREAD

**Issue by mcmy** [CVHub520/X-AnyLabeling#390]
1. 在勾选自动使用上一个标签后在下一张图片使用的是第一个标签，没有使用上一页的上一个标签，希望能保留
2. 现在只有清除对象和完成对象有快捷按钮，希望增加+点的快捷键或者全功能自定义快捷键（比如新增配置文件按键对应某个方法）
3. 希望可以增加自动标注边缘按中心点自动扩大（只有矩形标注放大也行），框选的矩形太靠近内容，有些还会裁剪掉一部分

![image](https://github.com/CVHub520/X-AnyLabeling/assets/54695595/c5fdcbf9-45cd-4160-bc18-12eb7b9c7582)

**Comment by CVHub520** [comment]
您好，感谢你对X-AnyLabeling的支持与关注，现在一一回答下你的几个问题：

> 1. 在勾选自动使用上一个标签后在下一张图片使用的是第一个标签，没有使用上一页的上一个标签，希望能保留

如果你想使用上一页的标签，你应该勾选的是`保留上一张图像的标注`。当然，如果你是只想使用上一页的最后一次使用的标签，这个肯定是属于自定义功能的范畴，你需要自行实现。每个用户的需求都是千奇百怪的，不可能都去一一支持。

> 2. 现在只有清除对象和完成对象有快捷按钮，希望增加+点的快捷键或者全功能自定义快捷键（比如新增配置文件按键对应某个方法）

这个早就支持了，麻烦看下主页的[快捷键介绍](https://github.com/CVHub520/X-AnyLabeling#hotkeys)。

> 3. 希望可以增加自动标注边缘按中心点自动扩大（只有矩形标注放大也行），框选的矩形太靠近内容，有些还会裁剪掉一部分

自动扩大这个功能并不通用，同样属于一些极少数的个性化需求，你这边可以自行修改源码适配。
