### ISSUE TITLE
【BUG】AssertionError: cannot paint null image

### ISSUE THREAD

**Issue by jiangtangaaaa** [CVHub520/X-AnyLabeling#391]
大佬早上好，当我想尝试解决这个问题的时候[https://github.com/CVHub520/X-AnyLabeling/issues/386](url)，发现了一个bug导致界面闪退：当我们run app.py ==》不加载图像 ==》 按住Ctrl+滚轮 ==》界面闪退并报错
```
/anylabeling/views/labeling/label_widget.py", line 2265, in paint_canvas
    assert not self.image.isNull(), "cannot paint null image"
AssertionError: cannot paint null image

```
我是怎么发现这个问题的呢：在#386这个问题中，我已经能够把摄像头图像展示在canvas上面，但是图像无法缩放和自适应......但是就在刚刚，我没动任何代码的情况下，画面竟然能缩放了。 是因为，我在展示画面之前，我加载了文件夹的图像，然后再获取的摄像头画面
![image](https://github.com/CVHub520/X-AnyLabeling/assets/101043186/af093756-12f1-41c6-ae70-2d9821223699)

所以==》 我还想向您请教，想要摄像头图像支持自适应和缩放，我应该怎么修改我的代码呢？
麻烦您了！

**Comment by jiangtangaaaa** [comment]
虽然您在启动软件之前，禁用了zoom按钮，但是快捷键无法禁用或者快捷键还没有禁用.....就相当于我在缩放一个空图像，所以导致的闪退

**Comment by jiangtangaaaa** [comment]
@CVHub520 
您好

**Comment by CVHub520** [comment]
> 虽然您在启动软件之前，禁用了zoom按钮，但是快捷键无法禁用或者快捷键还没有禁用.....就相当于我在缩放一个空图像，所以导致的闪退

您好，这个当前是存在问题，不支持缩放空图像。

**Comment by CVHub520** [comment]
Thanks for reporting this! I've just pushed a fix for this, so it should be resolved now. Please feel free to test it out and let us know if everything looks good on your end!
