### ISSUE TITLE
Invalid Rank Error for Input ‘x’ When Using ONNX Runtime

### ISSUE THREAD

**Issue by DongRuiH** [CVHub520/X-AnyLabeling#395]
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: x Got: 3 Expected: 4 Please fix either the inputs or the model.
这个怎么解决呢

**Comment by CVHub520** [comment]
> onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: x Got: 3 Expected: 4 Please fix either the inputs or the model. 这个怎么解决呢

您好，自定义模型需要自行适配下。如果是官方已经适配过的模型，你可以使用 netron 工具对比下 onnx 模型的输入输出节点。

**Comment by Taichipeace** [comment]
> > onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: x Got: 3 Expected: 4 Please fix either the inputs or the model. 这个怎么解决呢
> 
> 您好，自定义模型需要自行适配下。如果是官方已经适配过的模型，你可以使用 netron 工具对比下 onnx 模型的输入输出节点。

@CVHub520 正好想请教一下，有详细些的适配教程么？ 
在custom_model.md里，针对未适配模型的集成流程，只有简单的几行介绍。
是否可以有个例子具体讲解一下，比如想要添加PPYOLOE plus的模型，需要在model.py和model_manager.py这2个文件里修改哪些地方？

非常喜欢X-AnyLabeling，是用过的最好用的标注工具，（用过Labelme，LabelImg，EasyData，roLabelImg）
希望可以进一步用好它，所以请您指点，感谢。

**Comment by CVHub520** [comment]
> > > onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: x Got: 3 Expected: 4 Please fix either the inputs or the model. 这个怎么解决呢
> > 
> > 
> > 您好，自定义模型需要自行适配下。如果是官方已经适配过的模型，你可以使用 netron 工具对比下 onnx 模型的输入输出节点。
> 
> @CVHub520 正好想请教一下，有详细些的适配教程么？ 在custom_model.md里，针对未适配模型的集成流程，只有简单的几行介绍。 是否可以有个例子具体讲解一下，比如想要添加PPYOLOE plus的模型，需要在model.py和model_manager.py这2个文件里修改哪些地方？
> 
> 非常喜欢X-AnyLabeling，是用过的最好用的标注工具，（用过Labelme，LabelImg，EasyData，roLabelImg） 希望可以进一步用好它，所以请您指点，感谢。

您好，这个暂时还没写详细教程，等后面有空找个时间录制下教学视频，敬请期待。

**Comment by CVHub520** [comment]
官方文档已正式上线，适配自定义模型可参考：[链接](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md#%E5%8A%A0%E8%BD%BD%E6%9C%AA%E9%80%82%E9%85%8D%E7%9A%84%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B)。
