### ISSUE TITLE
Issue with Exporting Annotations in YOLO Format

### ISSUE THREAD

**Issue by sxj0310** [CVHub520/X-AnyLabeling#398]
您好，开发者，该软件导入图片后自动调整图片方向，默认长边在水平方向，短边在竖直方向，而不是图片原来的方向。这样标注后，导出yolo格式，会导致标注框与图片中的图像不一致，尤其是图片不是1:1比例的情况，图片为1:1也会出现自动调整方向问题，导致YOLO导出格式标注出现问题。解决方案可能是https://cloud.tencent.com/developer/article/1523050或者https://blog.csdn.net/qq_40682833/article/details/123953980，但是我不知道如何修改您的源代码。

**Comment by CVHub520** [comment]
您好，可参考 #216.
