### ISSUE TITLE
How to include confidence information in the annotation results.

### ISSUE THREAD

**Issue by dejun219** [CVHub520/X-AnyLabeling#399]
Dear author,

In the annotation results of this model, each bounding box does not include the corresponding predicted confidence information. Could you guide me on how to modify the relevant script so that the output results in the JSON file include confidence information?

Best regards,

**Comment by CVHub520** [comment]
Hello, @dejun219:

Thank you for your interest in this project. Actually, there are several ways to add confidence or any other information into the label file. 

Most simply, here's an example with the use of [damo_yolo.py](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/damo_yolo.py), where you can save the information whatever you need as a dict pair in the `flags` field of the `Shape` object.  Remember, make sure to save it as a string :)
```python
...

        shapes = []
        for result in results:
            shape = Shape(
                label=result["label"],
                shape_type="rectangle",
                # Add this line
                flags={"score": str(result["score"])}
            )
            xmin = result["xmin"]
            ymin = result["ymin"]
            xmax = result["xmax"]
            ymax = result["ymax"]
            pt1 = QtCore.QPointF(xmin, ymin)
            pt2 = QtCore.QPointF(xmax, ymin)
            pt3 = QtCore.QPointF(xmax, ymax)
            pt4 = QtCore.QPointF(xmin, ymax)
            shape.add_point(pt1)
            shape.add_point(pt2)
            shape.add_point(pt3)
            shape.add_point(pt4)
            shapes.append(shape)
        result = AutoLabelingResult(shapes, replace=True)
        return result
```

Let me know if there are other points you want to clarify. Thank you.

Best Regards.

**Comment by CVHub520** [comment]
Hey there!

Right now, there isn't a built-in way to add output fields to label files, so you'll need to tweak the code a bit to make that happen. I suggest taking a closer look at the source code to figure out where you need to make those adjustments. Just make sure to give it a good test run after you've made your changes.

If you run into any snags, feel free to reach out.

Take care!

**Comment by dejun219** [comment]
作者您好
详细了解后，发现您也是中国人可能，我这边详细在请教下您：
![20240509-094224](https://github.com/CVHub520/X-AnyLabeling/assets/152482904/55d0604b-69bd-49f7-84c0-816be3862a14)
我是想在标注的结果Json文件中增加这个框的置信度信息，进而辅助我这个数据我是否要用，或者标注的是否正确。
您昨天提到了修改源码，我进行了尝试但是未成功，您能否详细再介绍下修改哪一部分源码？
谢谢回复。

**Comment by CVHub520** [comment]
您好，修改源码需要涉及几处改动：
1. https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/views/labeling/shape.py
2. 您的模型推理文件中的predict_shapes()
3. https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/views/labeling/label_file.py

更具体地，我之前添加过一个difficult参数，你可以搜下对应的commit记录，看下增加字段涉及哪些地方。

**Comment by CVHub520** [comment]
Hi @dejun219:

Just wanted to let you know that the feature request for displaying the confidence score has been implemented and pushed to the remote repository.

Now, you can now update your local source code to experience this new addition. Happy coding!

Best regards,
CVHub

**Comment by dejun219** [comment]
谢谢您，我这边更新下。
