### ISSUE TITLE
Label Editing Pop-up Window Does Not Adapt to Screen: Issue with Bottom Alignment

### ISSUE THREAD

**Issue by x7902178** [CVHub520/X-AnyLabeling#400]
![1715155817506](https://github.com/CVHub520/X-AnyLabeling/assets/142156360/52de0199-43ed-4dc8-8ef6-e9f248cc392a)
标签在底部的话，他也会跑到底部，不会自适应屏幕

**Comment by CVHub520** [comment]
您好，当前设置是跟随鼠标。

**Comment by CVHub520** [comment]
最新版本已修复。
