### ISSUE TITLE
Error in predict_shapes: list index out of range

### ISSUE THREAD

**Issue by hello50505** [CVHub520/X-AnyLabeling#402]
1.我使用这个命令得到我的onnx文件：
 python3 export_yoloV8.py -w best.pt -s 1280 960 --dynamic
（best.pt是我自己训练得到的yolov8s模型，class=1）

2.我在x-anylabeling使用自动标注，配置文件如下：
type: yolov8
name: yolov8s-r20230520
display_name: YOLOv8s Ultralytics
model_path: /home/xpc/Downloads/video_20240508_144952/best.onnx
nms_threshold: 0.45
confidence_threshold: 0.25
input_width: 1280
input_height: 960
classes:
  - dingzi
  
  
  3.当我点击推理图片的按钮后，命令窗口报错：
Error in predict_shapes: list index out of range

请问问题出在哪里？谢谢！

**Comment by CVHub520** [comment]
您好，暂不支持动态batch，可注释掉`--dynamic`参数重新导出。

**Comment by hello50505** [comment]
> 您好，暂不支持动态batch，可注释掉`--dynamic`参数重新导出。

我把导出的命令改为：
python3 export_yoloV8.py -w best.pt -s 1280 960 
或者python3 export_yoloV8.py -w best.pt -s 1280 960 --batch 1

能正常导出onnx文件，但是自动标注还是会报同样的错误

**Comment by CVHub520** [comment]
> > 您好，暂不支持动态batch，可注释掉`--dynamic`参数重新导出。
> 
> 我把导出的命令改为： python3 export_yoloV8.py -w best.pt -s 1280 960 或者python3 export_yoloV8.py -w best.pt -s 1280 960 --batch 1
> 
> 能正常导出onnx文件，但是自动标注还是会报同样的错误

使用netron工具检查下你的classes类别是否与yaml文件的类别定义完全一致。

**Comment by hello50505** [comment]
![Screenshot from 2024-05-09 19-48-36](https://github.com/CVHub520/X-AnyLabeling/assets/80430057/b86821b5-e4dc-483e-9d75-d0846690d4a2)
我自己看好像是没什么问题，class=1

**Comment by hello50505** [comment]
> > > 您好，暂不支持动态batch，可注释掉`--dynamic`参数重新导出。
> > 
> > 
> > 我把导出的命令改为： python3 export_yoloV8.py -w best.pt -s 1280 960 或者python3 export_yoloV8.py -w best.pt -s 1280 960 --batch 1
> > 能正常导出onnx文件，但是自动标注还是会报同样的错误
> 
> 使用netron工具检查下你的onnx模型中classes类别是否与yaml文件的类别定义完全一致。

![Screenshot from 2024-05-09 19-48-36](https://github.com/CVHub520/X-AnyLabeling/assets/80430057/24ba28f9-4b6e-4245-9b7f-19d46713c2bf)
我自己看好像是没什么问题，class=1

**Comment by CVHub520** [comment]
你这个输出节点没对应上，建议使用官方的[导出设置](https://docs.ultralytics.com/modes/export/#usage-examples)。如果你仍然需要使用自定义的导出模型，可自行修改[后处理](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/__base__/yolo.py#L182)代码进行适配。

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/b4fd1008-4160-459d-99ec-9b1e7a43ba4f)

**Comment by hello50505** [comment]
> 你这个输出节点没对应上，建议使用官方的[导出设置](https://docs.ultralytics.com/modes/export/#usage-examples)。如果你仍然需要使用自定义的导出模型，可自行修改[后处理](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/__base__/yolo.py#L182)代码进行适配。
> 
> ![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/b4fd1008-4160-459d-99ec-9b1e7a43ba4f)
> 
> 

好的谢谢!我按照yolov8官方方法导出，目前可以自动标注了

**Comment by 377343577** [comment]
> 你这个输出节点没对应上，建议使用官方的[导出设置](https://docs.ultralytics.com/modes/export/#usage-examples)。如果你仍然需要使用自定义的导出模型，可自行修改[后处理](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/__base__/yolo.py#L182)代码进行适配。
> 
> ![image](https://private-user-images.githubusercontent.com/72010077/329427133-b4fd1008-4160-459d-99ec-9b1e7a43ba4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDM2MzcsIm5iZiI6MTczNDk0MzMzNywicGF0aCI6Ii83MjAxMDA3Ny8zMjk0MjcxMzMtYjRmZDEwMDgtNDE2MC00NTlkLTk5ZWMtOWIxZTdhNDNiYTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA4NDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3M2NlYWRiMjFhM2ZiOGNlNzMxZjcxMDhlY2QwMGYyMWY1NWE1NTk4NThjOTcwN2E4ZjUzNjBlNWExMGIwNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5pzl8mF9FtleVeb5klScLDZnM6ulI_a6HzgVVSSdHnw)

作者您好，我也遇到了相同的问题，加载好自己训练的模型，在运行的时候提示model_manager:predict_shapes:2181 - Error in predict_shapes: list index out of range。我使用的是yolov5官方文件的export，导出的时候没有使用--dynamic。
在netron上我的onnx模型显示为下图。请问我如果修改后处理文件yolo.py，应该怎么修改？期待您的回复！
![60e344ce37f79fae17ac0ee276f6300](https://github.com/user-attachments/assets/0ca10be8-e6c2-4dea-9799-33774411d5d5)

**Comment by CVHub520** [comment]
Hey there! @377343577 :

The error is may caused by incorrect configuration. The `strides` parameter is only compatible with yolov5-v5.0 and below. Please remove this parameter. For more details, refer to the official documentation: [Custom Model Guide](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md).

**Comment by 377343577** [comment]
> 嘿，你好！ ：
> 
> 该错误可能是由不正确的配置引起的。该参数仅兼容 yolov5-v5.0 及以下版本。请删除此参数。更多详情请参考官方文档：[自定义模型指南](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md)。`strides`

感谢您的回答，我配置的ymal文件如下图。按照要求没有配置stride；anchors
![4eb42d099377dab43c30139b8888ba2](https://github.com/user-attachments/assets/f38def4e-e402-445a-b8b2-2383a1959088)

**Comment by CVHub520** [comment]
Clearly, there is a mismatch between your defined custom file (including 19 classes) and your exported ONNX model, which has 21 classes.

**Comment by 377343577** [comment]
> Clearly, there is a mismatch between your defined custom file (including 19 classes) and your exported ONNX model, which has 21 classes.

太感谢您啦！现在可以正常运行了。 真的非常抱歉，那么简单的问题我没发现。
最后，祝您工作顺利。

**Comment by ak747asdf** [comment]
用x-anylabeling 训练后导出的onnx模型，就一个class,AI推理 一直报这个错，截图如下，大佬帮忙看看：

<img width="318" height="156" alt="Image" src="https://github.com/user-attachments/assets/1eccfe83-faad-4eb5-8839-db6b51691fa4" />，

<img width="316" height="331" alt="Image" src="https://github.com/user-attachments/assets/6038c406-36c2-4797-b517-81284a353eb2" />

<img width="470" height="642" alt="Image" src="https://github.com/user-attachments/assets/8d4b1500-dce9-4cb1-b1cc-fd93a8689b73" />到底哪里问题出错了，全部按照说明一步一步来的 ，就是一直报这个错

**Comment by CVHub520** [comment]
@ak747asdf  `names` --> `classes`

<img width="521" height="177" alt="Image" src="https://github.com/user-attachments/assets/233f438a-e8cd-43e0-949a-4abd41afe9f8" />

https://github.com/CVHub520/X-AnyLabeling/blob/4487643041c390f054fa0222a0f47b9fad4e0ea9/anylabeling/configs/auto_labeling/yolo11s.yaml
