### ISSUE TITLE
导出错误

### ISSUE THREAD

**Issue by Luxf01** [CVHub520/X-AnyLabeling#403]
老板好：在标记完后导出YOLO、VOC、COCO标签时，出现错误消息：imageWith，是图片宽度太大了吗？（图片大小：2479*3508）
如下图：
![image](https://github.com/CVHub520/X-AnyLabeling/assets/27559520/f41d5edc-04ab-4195-bedb-1903e107afc6)

后三种导出格式正常，谢谢！

**Comment by CVHub520** [comment]
您好，可检查标签文件内容是否异常。

**Comment by Luxf01** [comment]
对了，之前没有选择 保存包括图像数据在内的文件 ，重新保存并生成一下json文件再导出就可以了，非常感谢！  
另外，对于这种已经有json文件的情况下，有没有什么操作可以自动全部重新生成json文件，目前要另存为并覆盖原json文件，图片比较多处理比较慢，谢谢！

**Comment by CVHub520** [comment]
> 对了，之前没有选择 保存包括图像数据在内的文件 ，重新保存并生成一下json文件再导出就可以了，非常感谢！ 另外，对于这种已经有json文件的情况下，有没有什么操作可以自动全部重新生成json文件，目前要另存为并覆盖原json文件，图片比较多处理比较慢，谢谢！

可以设置好，然后导入工具中过一遍试试。

**Comment by Luxf01** [comment]
好的，非常感谢！

**Comment by Luxf01** [comment]
已解决，感谢！
