### ISSUE TITLE
macos桌面版如何安装

### ISSUE THREAD

**Issue by teemo0803** [CVHub520/X-AnyLabeling#405]
您好，我的操作系统是macos，请问如何安装gui的版本，谢谢！

**Comment by CVHub520** [comment]
> 您好，我的操作系统是macos，请问如何安装gui的版本，谢谢！

您好，当前macos桌面版需要自行下载源码编译，具体可参考此[教程](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md#%E6%89%93%E5%8C%85%E7%BC%96%E8%AF%91)。
