### ISSUE TITLE
Auto-Annotation with Custom Model Fails

### ISSUE THREAD

**Issue by BBENG-DADA** [CVHub520/X-AnyLabeling#406]
我已确认该问题在issue中未被提出。如题，在anaconda虚拟环境中安装了x-anylabling，操作系统为Windows11,加载的自定义模型使用yolov5s,报错内容如下Error in predict_shapes: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4155: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'

**Comment by BBENG-DADA** [comment]
图片路径无误，软件中可正常加载并显示

**Comment by CVHub520** [comment]
> 我已确认该问题在issue中未被提出。如题，在anaconda虚拟环境中安装了x-anylabling，操作系统为Windows11,加载的自定义模型使用yolov5s,报错内容如下Error in predict_shapes: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4155: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'

您好，这边可以尝试使用常规图片测试下，如[assets](https://github.com/CVHub520/X-AnyLabeling/tree/main/assets)，排除下是图片本身的问题。

**Comment by BBENG-DADA** [comment]
> > 我已确认该问题在issue中未被提出。如题，在anaconda虚拟环境中安装了x-anylabling，操作系统为Windows11,加载的自定义模型使用yolov5s,报错内容如下Error in predict_shapes: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4155: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'
> 
> 您好，这边可以尝试使用常规图片测试下，如[assets](https://github.com/CVHub520/X-AnyLabeling/tree/main/assets)，排除下是图片本身的问题。

已经尝试过了，报错问题依旧存在

**Comment by BBENG-DADA** [comment]
这个是自定义模型的yaml文件type: yolov5
name: yolov5s-r20230520
display_name: EDS
model_path: yolov5s.onnx
nms_threshold: 0.45
confidence_threshold: 0.25
classes:
- 1
- 2
- 3
- 4

> > 我已确认该问题在issue中未被提出。如题，在anaconda虚拟环境中安装了x-anylabling，操作系统为Windows11,加载的自定义模型使用yolov5s,报错内容如下Error in predict_shapes: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4155: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'
> 
> 您好，这边可以尝试使用常规图片测试下，如[assets](https://github.com/CVHub520/X-AnyLabeling/tree/main/assets)，排除下是图片本身的问题。

**Comment by CVHub520** [comment]
> 这个是自定义模型的yaml文件type: yolov5 name: yolov5s-r20230520 display_name: EDS model_path: yolov5s.onnx nms_threshold: 0.45 confidence_threshold: 0.25 classes:
> 
> * 1
> * 2
> * 3
> * 4
> 
> > > 我已确认该问题在issue中未被提出。如题，在anaconda虚拟环境中安装了x-anylabling，操作系统为Windows11,加载的自定义模型使用yolov5s,报错内容如下Error in predict_shapes: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4155: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'
> > 
> > 
> > 您好，这边可以尝试使用常规图片测试下，如[assets](https://github.com/CVHub520/X-AnyLabeling/tree/main/assets)，排除下是图片本身的问题。

内置模型能正常推理吗？

**Comment by BBENG-DADA** [comment]
> > 这个是自定义模型的yaml文件type: yolov5 name: yolov5s-r20230520 display_name: EDS model_path: yolov5s.onnx nms_threshold: 0.45 confidence_threshold: 0.25 classes:
> > 
> > * 1
> > * 2
> > * 3
> > * 4
> > 
> > > > 我已确认该问题在issue中未被提出。如题，在anaconda虚拟环境中安装了x-anylabling，操作系统为Windows11,加载的自定义模型使用yolov5s,报错内容如下Error in predict_shapes: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4155: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'
> > > 
> > > 
> > > 您好，这边可以尝试使用常规图片测试下，如[assets](https://github.com/CVHub520/X-AnyLabeling/tree/main/assets)，排除下是图片本身的问题。
> 
> 内置模型能正常推理吗？
内置的可以正常标注，自定义模型也可以正常推理

**Comment by CVHub520** [comment]
> > > 这个是自定义模型的yaml文件type: yolov5 name: yolov5s-r20230520 display_name: EDS model_path: yolov5s.onnx nms_threshold: 0.45 confidence_threshold: 0.25 classes:
> > > 
> > > * 1
> > > * 2
> > > * 3
> > > * 4
> > > 
> > > > > 我已确认该问题在issue中未被提出。如题，在anaconda虚拟环境中安装了x-anylabling，操作系统为Windows11,加载的自定义模型使用yolov5s,报错内容如下Error in predict_shapes: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4155: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'
> > > > 
> > > > 
> > > > 您好，这边可以尝试使用常规图片测试下，如[assets](https://github.com/CVHub520/X-AnyLabeling/tree/main/assets)，排除下是图片本身的问题。
> > 
> > 
> > 内置模型能正常推理吗？
> 
> 内置的可以正常标注，自定义模型也可以正常推理

您好，非常抱歉刚看到你的回复，纯数字类别在定义时需要加入单引号避免转义：
```YAML
type: yolov5
...

classes:
  - '0'
  - '1'
  - '2'
  - '3'
```

**Comment by YY0010826** [comment]
解决方法：
1. anylabeling自定义读取的yaml（yaml文件是和xx.onnx文件是在一个文件夹里的），在yaml文件里新增”input_width: 640
input_height: 640“

以下是我的yaml文件供参考：
type: yolov10
name: yolov10n-r20240525-v1.0
display_name: YOLOv10n  by yy
model_path: D:/zhuomian/X-AnyLabeling-main/X-AnyLabeling-main/model/best.onnx
confidence_threshold: 0.25
input_width: 640  #新增
input_height: 640 #新增
classes:
  - '1'

**Comment by CVHub520** [comment]
Thank you for sharing your solution. It will undoubtedly be beneficial for others facing similar issues.

**Comment by prczsf** [comment]
Thank you! It is OK and solved with “ input_width: 640 ”and “input_height: 640” added

**Comment by TenYearOldJAVA** [comment]
> 解决方法：
> 
> 1. anylabeling自定义读取的yaml（yaml文件是和xx.onnx文件是在一个文件夹里的），在yaml文件里新增”input_width: 640
>    input_height: 640“
> 
> 以下是我的yaml文件供参考： type: yolov10 name: yolov10n-r20240525-v1.0 display_name: YOLOv10n by yy model_path: D:/zhuomian/X-AnyLabeling-main/X-AnyLabeling-main/model/best.onnx confidence_threshold: 0.25 input_width: 640 #新增 input_height: 640 #新增 classes:
> 
> * '1'

跪谢
