### ISSUE TITLE
是否支持多人的在线合作？

### ISSUE THREAD

**Issue by hxuaj** [CVHub520/X-AnyLabeling#408]
你好，
之前使用的是Label-studio，想请问X-AnyLabeling是否支持如下类似的功能：
* 软件本体安装于远程服务器
* 可以多人同时线上在不同终端对同一project中的图片进行标注

**Comment by CVHub520** [comment]
> 你好， 之前使用的是Label-studio，想请问X-AnyLabeling是否支持如下类似的功能：
> 
> * 软件本体安装于远程服务器
> * 可以多人同时线上在不同终端对同一project中的图片进行标注

您好，此功能暂不支持。

**Comment by hxuaj** [comment]
谢谢回复，希望以后能有相关的功能。
