### ISSUE TITLE
Export to YOLO Format Excludes Non-Rectangle Annotations: Empty Label File for Line Drawings

### ISSUE THREAD

**Issue by bianchh** [CVHub520/X-AnyLabeling#409]
### 我使用线条绘制，导出YOLO格式时，label 文档内容为空

![image](https://github.com/CVHub520/X-AnyLabeling/assets/42956643/739426e8-f778-491f-8be3-e256f4325bb3)

![image](https://github.com/CVHub520/X-AnyLabeling/assets/42956643/87e78e12-1127-4317-8f07-e6b9176ae50d)

**Comment by CVHub520** [comment]
> ### 我使用线条绘制，导出YOLO格式时，label 文档内容为空
> ![image](https://private-user-images.githubusercontent.com/42956643/329775335-739426e8-f778-491f-8be3-e256f4325bb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzM2NzUsIm5iZiI6MTcxNTQzMzM3NSwicGF0aCI6Ii80Mjk1NjY0My8zMjk3NzUzMzUtNzM5NDI2ZTgtZjc3OC00OTFmLThiZTMtZTI1NmY0MzI1YmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEzMTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5M2MyMTQ1OTUzY2U1YjYwNTVmOTM3NDlkNTNlOWY3MDAyNmZhM2YzY2NmM2ZiN2YwY2M1M2ExOTVlZjMyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iDimnHaynkIh7hZSlEtYFk8Xx5an-eYiie8vlFObOZM)
> 
> ![image](https://private-user-images.githubusercontent.com/42956643/329775423-87e78e12-1127-4317-8f07-e6b9176ae50d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzM2NzUsIm5iZiI6MTcxNTQzMzM3NSwicGF0aCI6Ii80Mjk1NjY0My8zMjk3NzU0MjMtODdlNzhlMTItMTEyNy00MzE3LThmMDctZTZiOTE3NmFlNTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEzMTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNjAwZmU1MjkyZTk4NDBlMTdiY2I2NDk5MGMxZTNjNmFmZDg4MjdlNTA0Mjg1MzhlNGQ1ZWNmYzYxODg1M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ngeVvQ9QrZIB-3xpmKbBobAVsX1r6YIDtNPN5vZ-BaY)

您好，目前支持导出的`shape_type`为`rectangle`、`polygon`和`rotation`.
