### ISSUE TITLE
Incompatibility with Windows 7: anythinglabel Error on app.py Execution

### ISSUE THREAD

**Issue by Yitong-web** [CVHub520/X-AnyLabeling#410]
在win10上安装运行一切正常，在win7上pip install -r requirements.txt后直接运行app.py会显示找不到anythinglabel，安装后打开app.py会直接出现anythinglabel的界面而非x-anythinglabel

**Comment by CVHub520** [comment]
> 在win10上安装运行一切正常，在win7上pip install -r requirements.txt后直接运行app.py会显示找不到anythinglabel，安装后打开app.py会直接出现anythinglabel的界面而非x-anythinglabel

您好，可执行`pip unisntall anylabeling`后再次运行 python anylabeling/app.py.
