### ISSUE TITLE
Grounding DINO detection failed?

### ISSUE THREAD

**Issue by kexul** [CVHub520/X-AnyLabeling#412]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/5920217/c3132780-d324-4551-9756-3bdce76cef1c)

Hi, Thanks for your great work! Grounding DINO seems to failed to detect anything in my picture, would you mind have a look? Sorry that I downloaded the GUI version of the app, there is no error log...

**Comment by kexul** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/5920217/56109410-9c74-4233-a892-7de145e61a34)
Here is another example, ideally the prompt `person` should detect all man in the court.

**Comment by kexul** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/5920217/4ca0158b-d218-455a-80fe-bc1120310b3e)
YoloWorld works here, but yolow does not support prompt so the use cases is limited.

**Comment by kexul** [comment]
OK, I cloned the sourced code and run the python script, now it works fine.

**Comment by esrefsamilzamanoglu** [comment]
hello can you share how did you handle to use yolo world with prompt?
