### ISSUE TITLE
能否设置点与线的大小与粗细

### ISSUE THREAD

**Issue by GrwyYJ** [CVHub520/X-AnyLabeling#413]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/118507922/ef21434f-5502-4a13-b8a1-6ee317f11421)
多边形起始点的大小与线的粗细能否设置的更小一点

**Comment by CVHub520** [comment]
https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/views/labeling/shape.py

**Comment by GrwyYJ** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/118507922/ddf23ea1-a96b-4d88-a7a5-1084a97fcf2c)
起始点能否缩小一点，或把外围扩大一圈的区域去除  
标注者嫌点太大挡住标注目标了

**Comment by GrwyYJ** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/118507922/ddf23ea1-a96b-4d88-a7a5-1084a97fcf2c)
起始点能否缩小一点，或把外围扩大一圈的区域去除  
标注者嫌点太大挡住标注目标了

**Comment by GrwyYJ** [comment]
解决方案：
设置线粗细
```python
            # Try using integer sizes for smoother drawing(?)
            # pen.setWidth(max(1, int(round(2.0 / self.scale))))
            # 固定设置线的粗细
            pen.setWidth(1)
```
与设置点大小  

```python
        # d = self.point_size / self.scale
        # 固定设置点的大小
        d = 1
```

**Comment by CVHub520** [comment]
Hi!

Thank you for your feedback on setting the size and thickness for points and lines. We appreciate your input! 🌟

It looks like you've found a solution that works for you, and we're glad to hear that. 

If you have any more suggestions or run into any other issues, feel free to let us know.
