### ISSUE TITLE
Guide Needed for Exporting JSON Annotations to YOLO OBB Training Format

### ISSUE THREAD

**Issue by mozeqiu123** [CVHub520/X-AnyLabeling#415]
你好，我标注完图片之后是一个json格式的。我标注玩之后推出了程序，现在只有图片文件和json文件，我要怎么把下面的json文件转换成yolo obb训练的格式，如下图这样。我第一次用这个标注工具，
![image](https://github.com/CVHub520/X-AnyLabeling/assets/139750690/0d0355ab-b271-4322-8fb4-e2d6a4db5201)

`{
  "version": "2.3.5",
  "flags": {},
  "shapes": [
    {
      "label": "barriergate",
      "points": [
        [
          51.18582262759597,
          495.3528952953652
        ],
        [
          408.90963356628106,
          1040.408345730925
        ],
        [
          357.9329269596456,
          1073.8647247871413
        ],
        [
          0.2091160209605789,
          528.8092743515816
        ]
      ],
      "group_id": null,
      "description": "",
      "difficult": false,
      "shape_type": "rotation",
      "flags": {},
      "attributes": {},
      "direction": 0.9899999999999999
    }
  ],
  "imagePath": "stream_1_frame_1.jpg",
  "imageData": null,
  "imageHeight": 1080,
  "imageWidth": 1920
}`

**Comment by CVHub520** [comment]
您好，可以参考[导出DOTA标签](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E6%A0%87%E7%AD%BE%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA)。

**Comment by mozeqiu123** [comment]
> 您好，可以参考[导出DOTA标签](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E6%A0%87%E7%AD%BE%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA)。

作者大大 我自己训练的模型要用起来是放在哪个目录呀，我看文档里没写

**Comment by CVHub520** [comment]
> > 您好，可以参考[导出DOTA标签](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E6%A0%87%E7%AD%BE%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA)。
> 
> 作者大大 我自己训练的模型要用起来是放在哪个目录呀，我看文档里没写

您好，可以参看[自定义模型](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md)章节
