### ISSUE TITLE
Segment Anything Model Export Error: Missing mask.json File

### ISSUE THREAD

**Issue by cupofbx** [CVHub520/X-AnyLabeling#418]
![屏幕截图 2024-05-14 234334](https://github.com/CVHub520/X-AnyLabeling/assets/163823211/464d527f-b706-4d8a-9ab1-1282f97c9dc6)

**Comment by cupofbx** [comment]
没有生成对应的mask.json文件

**Comment by CVHub520** [comment]
> 没有生成对应的mask.json文件

您好，导出掩码标签需要设置掩码映射表，具体可参考[用户手册-标签导入/导出-导出MASK标签](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md)。
