### ISSUE TITLE
Auto-tracking Bounding Boxes Across Consecutive Frames

### ISSUE THREAD

**Issue by JansherMughal** [CVHub520/X-AnyLabeling#421]
Hello,

I have a question regarding the functionality of x-anylabeling.

Is it possible to provide x-anylabeling with a bounding box (bbox) from one image and have it automatically apply this bbox to all subsequent images? Specifically, I am working with frames from a video, and I would like a bbox created on the first frame to be automatically built on the subsequent frames.

Thank you for your assistance.

Best regards,
Jansher Mughal

**Comment by CVHub520** [comment]
Hello @JansherMughal:

Thank you for reaching out and your interest in X-AnyLabeling.

We regret to inform you that the current version of X-AnyLabeling does not support the specific feature you mentioned, which is auto-tracking bounding boxes across consecutive frames. However, we do understand the importance and convenience of such functionality, especially for video object tracking applications.

While we cannot provide an immediate solution, we are open to integrating Video Object Segmentation (VOS) methods in future updates, which could potentially address your needs. We always prioritize the enhancement of our tools based on community feedback.

It also welcome contributions from the community. If you or anyone else is interested in adding this feature, I would be more than happy to review and merge a pull request.

Thank you for your understanding, and we look forward to a lively discussion on how we can improve X-AnyLabeling together.

Best regards,
CVHub

**Comment by CVHub520** [comment]
Hello Jansher Mughal,

Thank you for reaching out and for your interest in X-AnyLabeling.

I'm pleased to inform you that x-anylabeling does support the functionality you're asking about. You can indeed provide a bounding box for the first frame and have it automatically applied to all subsequent frames.

For more details on how to implement this, please refer to issue #602.
If you have any further questions or need additional assistance, feel free to ask.

Enjoy labeling! 😃
