### ISSUE TITLE
重复帧较多的视频中，如何避免重复数据提取较多？

### ISSUE THREAD

**Issue by GZhengyang** [CVHub520/X-AnyLabeling#425]
非常喜欢你们的工作！有个小问题，请问在重复帧较多的视频中进行标注时，为避免相似数据过多，请问目前有在视频标注中设置提取数据的规则的方法吗（例如，隔几秒钟提取标注一次数据）？如果没有，请问具体在代码的哪部分可以加入这样的功能？
    期待您的回复！

**Comment by CVHub520** [comment]
您好，当前没有对外设置接口，不过你可以直接在[此处](https://github.com/CVHub520/X-AnyLabeling/blob/dca185a1f06956f29ce0356f1793277f8e886070/anylabeling/views/labeling/label_widget.py#L4575)添加自定义逻辑即可。

**Comment by CVHub520** [comment]
Hey there! 🙋‍♂️ Thanks for your kind words and for using our tool! We're thrilled to hear that you're enjoying it. 😊

To address your question about avoiding the extraction of redundant frames in videos with many repeats, we've recently implemented a feature that allows you to specify a frame interval during the extraction process. This means you can now choose to extract frames every few seconds or based on a specific number of frames, helping to minimize data redundancy. 🎉

This functionality is now available in the latest version of our software. If you update to the most recent release, you'll find this option when you initiate the frame extraction from a video. You can set the frame interval according to your needs right from the interface. 🚀

If you have any further questions or need assistance with the update, feel free to reach out. We're here to help! 🤝

Happy annotating! 🎨

**Comment by GZhengyang** [comment]
> Hey there! 🙋‍♂️ Thanks for your kind words and for using our tool! We're thrilled to hear that you're enjoying it. 😊
> 
> To address your question about avoiding the extraction of redundant frames in videos with many repeats, we've recently implemented a feature that allows you to specify a frame interval during the extraction process. This means you can now choose to extract frames every few seconds or based on a specific number of frames, helping to minimize data redundancy. 🎉
> 
> This functionality is now available in the latest version of our software. If you update to the most recent release, you'll find this option when you initiate the frame extraction from a video. You can set the frame interval according to your needs right from the interface. 🚀
> 
> If you have any further questions or need assistance with the update, feel free to reach out. We're here to help! 🤝
> 
> Happy annotating! 🎨

Ok, thanks for the reply, and thank you for your wonderful work!
