### ISSUE TITLE
Feature Request: show the confidence score

### ISSUE THREAD

**Issue by jbruno79** [CVHub520/X-AnyLabeling#426]
First of all, congratulations for the project. It seems to me a very complete, intuitive and easy to install tool.
As in this image, I think it would be very helpful to have the possibility of visualizing the confidence score, in the case of detection and segmentation.
![206095831-cc439557-1a23-4a99-b6b0-b6f2e97e8c57](https://github.com/CVHub520/X-AnyLabeling/assets/89979737/8aa222ed-f3c0-4a64-98df-6ddfe5f1a460)

In the case of Yolov8-seg this information is available. 
I have enough experience as a developer and I am interested in this utility to be able to include this tool in my workflow.

Best regards,
Julián

**Comment by CVHub520** [comment]
Hello Julián,

Thank you for your feature request and your kind words about the project. I’m thrilled to hear that you find the tool comprehensive, intuitive, and easy to set up.

Regarding the visualization of the confidence score for detection and segmentation tasks, this is indeed a valuable feature that can greatly enhance the utility of the tool, especially for users who need to gauge the reliability of the predictions. I appreciate your interest in contributing to the project and including it in your workflow.

Given your experience as a developer, I would be more than happy to guide you through the process of creating a pull request for this feature. If you need any assistance or have further questions about the codebase, my contributing guidelines, or any technical aspects of the implementation, please feel free to reach out.

Certainly, I will review your pull request and provide feedback or suggestions if necessary. Once the changes are approved and pass all checks, I will merge them into the main codebase.

Looking forward to your contribution and seeing the confidence score visualization come to life!

Best regards, CVHub

**Comment by CVHub520** [comment]
#399

**Comment by CVHub520** [comment]
Hi @jbruno79:

Just wanted to let you know that the feature request for displaying the confidence score has been implemented and pushed to the remote repository. 

Now, you can now update your local source code to experience this new addition. Happy coding!

Best regards,
CVHub

**Comment by jbruno79** [comment]
Thank you very much, excellent work. I share with you the result on my zebra cross detector.
![image](https://github.com/CVHub520/X-AnyLabeling/assets/89979737/504b2c89-4e45-4128-a5d3-2328b5984e8a)
