### ISSUE TITLE
【多目标跟踪】是否支持在视频第一帧手动标注需要跟踪的目标，之后的帧标注只跟踪这一个目标？

### ISSUE THREAD

**Issue by GZhengyang** [CVHub520/X-AnyLabeling#427]
非常喜欢你们的工作！有两个问题想请教一下:
一、是否支持在视频第一帧手动标注需要跟踪的目标，之后的帧标注只跟踪这一个目标？如果不支持，请问可以在哪里自行修改设置吗？
二、请问目前是否支持只使用模型进行定位，手动或者自动从文件夹名中标注类别信息？
期待您的回复！

**Comment by CVHub520** [comment]
您好，感谢你的关注。现在解答下 你的两个疑问：

> 一、是否支持在视频第一帧手动标注需要跟踪的目标，之后的帧标注只跟踪这一个目标？如果不支持，请问可以在哪里自行修改设置吗？
A: 具体可参考 #421 的回复。

> 二、请问目前是否支持只使用模型进行定位，手动或者自动从文件夹名中标注类别信息？
这个问题可以再表述清楚些，没太明白你的需求。

**Comment by GZhengyang** [comment]
感谢您的回复！第二个问题的意思是在进行目标检测数据集自动标注的时候，是否支持先进行定位框的标注，类别信息可以从视频的名称（例如：Husky.mp4）中进行提取，而不是模型的预测输出（考虑到自己训练的模型对细粒度预测结果可能出现偏差）

**Comment by CVHub520** [comment]
> 感谢您的回复！第二个问题的意思是在进行目标检测数据集自动标注的时候，是否支持先进行定位框的标注，类别信息可以从视频的名称（例如：Husky.mp4）中进行提取，而不是模型的预测输出（考虑到自己训练的模型对细粒度预测结果可能出现偏差）

可以的，但需要改下代码适配。

**Comment by GZhengyang** [comment]
> > 感谢您的回复！第二个问题的意思是在进行目标检测数据集自动标注的时候，是否支持先进行定位框的标注，类别信息可以从视频的名称（例如：Husky.mp4）中进行提取，而不是模型的预测输出（考虑到自己训练的模型对细粒度预测结果可能出现偏差）
> 
> 可以的，但需要改下代码适配。

感谢您的回复！请问是具体修改哪个或哪些文件中的适配呢？

**Comment by CVHub520** [comment]
> > > 感谢您的回复！第二个问题的意思是在进行目标检测数据集自动标注的时候，是否支持先进行定位框的标注，类别信息可以从视频的名称（例如：Husky.mp4）中进行提取，而不是模型的预测输出（考虑到自己训练的模型对细粒度预测结果可能出现偏差）
> > 
> > 
> > 可以的，但需要改下代码适配。
> 
> 感谢您的回复！请问是具体修改哪个或哪些文件中的适配呢？

具体得看你用的什么模型，可以找到对应的模型推理服务自行调试下。

**Comment by GZhengyang** [comment]
> > > > 感谢您的回复！第二个问题的意思是在进行目标检测数据集自动标注的时候，是否支持先进行定位框的标注，类别信息可以从视频的名称（例如：Husky.mp4）中进行提取，而不是模型的预测输出（考虑到自己训练的模型对细粒度预测结果可能出现偏差）
> > > 
> > > 
> > > 可以的，但需要改下代码适配。
> > 
> > 
> > 感谢您的回复！请问是具体修改哪个或哪些文件中的适配呢？
> 
> 具体得看你用的什么模型，可以找到对应的模型推理服务自行调试下。

好的 感谢您的回复
