### ISSUE TITLE
Unable to Export VOC Labels for Polygon Format Annotations

### ISSUE THREAD

**Issue by nbutll** [CVHub520/X-AnyLabeling#428]
shape_type为rectangle可以导出，polygon的标签不能导出

**Comment by nbutll** [comment]
如图，是不支持polygon多边形的导出吗
![Snipaste_2024-05-22_15-38-47](https://github.com/CVHub520/X-AnyLabeling/assets/51043578/0a891e20-c171-42ca-80d0-ba3c94d675bb)

**Comment by CVHub520** [comment]
您好，当前VOC标签格式不支持polygon，可以在[此处](https://github.com/CVHub520/X-AnyLabeling/blob/dca185a1f06956f29ce0356f1793277f8e886070/anylabeling/views/labeling/label_converter.py#L604)自行添加，欢迎提PR！

**Comment by CVHub520** [comment]
@nbutll, Hi!

Thank you for your inquiry. We are happy to inform you that the latest version of X-AnyLabeling has been updated to support the export of VOC labels for polygon format annotations. This update addresses the issue you mentioned.

We encourage you to git pull the latest version of the software from our official repository to take advantage of this new feature.

If you encounter any further issues or have additional questions, please do not hesitate to reach out.

Best regards,
CVHub
