### ISSUE TITLE
Request for OCR Video Tutorial and Issues with Auto-Annotation, Label Export, and KIE Group Annotation

### ISSUE THREAD

**Issue by Gpy23** [CVHub520/X-AnyLabeling#429]
顺便还有一些问题
1、自动标注后，有修改的地方，可以针对这个修改的小框单独进行自动识别吗？
2、标签是需要自己来进行后处理吗？是不是没有paddleocr相关的一键导出标签？
3、kie group相关的标注信息也都是自己处理成想要的标签模式吗？

**Comment by CVHub520** [comment]
> 顺便还有一些问题 1、自动标注后，有修改的地方，可以针对这个修改的小框单独进行自动识别吗？ 2、标签是需要自己来进行后处理吗？是不是没有paddleocr相关的一键导出标签？ 3、kie group相关的标注信息也都是自己处理成想要的标签模式吗？

1. 自动标注是针对全图进行的，如果需要识别指定区域需要自行适配源码；
2. paddleocr 会根据识别到的区域自动提取对应的文字，对于识别不准的地方肯定是需要手动纠正的；
3. 是的。
