### ISSUE TITLE
Request for SAM-Med2D Batch Auto-Annotation Feature

### ISSUE THREAD

**Issue by AImagicAI** [CVHub520/X-AnyLabeling#431]
SAM_Med2D现在需要每张图像点一下才能标注，如何批量自动标注，自动点击图像中的任意一点作为prompt

**Comment by CVHub520** [comment]
> SAM_Med2D现在需要每张图像点一下才能标注，如何批量自动标注，自动点击图像中的任意一点作为prompt

此功能暂未实现，后面可以考虑下。

**Comment by AImagicAI** [comment]
您好，这个功能什么时候会更新呢？谢谢

**Comment by CVHub520** [comment]
Duplicate of #383.
