### ISSUE TITLE
How to Convert Horizontal Bounding Boxes to Rotated Boxes in X-AnyLabeling for YOLOv8-obb

### ISSUE THREAD

**Issue by byyuchun** [CVHub520/X-AnyLabeling#433]
我们现在用的是yolo v8检测类别，但是现在有个需求是改成yolo v8obb，我想用x-anylabeling实现预打标签，我在软件里导入了我的模型，一键生成标签，生成的标签是标准的矩形，我想旋转，但是按zxcv都没有反应，我想知道有办法实现吗。

**Comment by byyuchun** [comment]
我看readme上介绍说支持一键水平框转为旋转框 不知道怎么操作啊

**Comment by CVHub520** [comment]
您好，可以点这里转换：

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/9e538b9f-42c9-4763-9539-4ce0f0f5f47f)

转换后的目标框中心会有一个标识，代表当前框为旋转框，后续可以在编辑模式下，将鼠标移动到对应目标框上，高亮表示选中，最后便可以通过 zxcv 进行旋转操作。

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/e2d2580b-2854-44ee-a32b-3913705b34be)

如果遇到新的问题，欢迎随时提问。

**Comment by byyuchun** [comment]
thanks
