### ISSUE TITLE
I find a bug！！！PLease help

### ISSUE THREAD

**Issue by byyuchun** [CVHub520/X-AnyLabeling#435]
作者您好，我使用自己训练的模型进行一个预打标签，我的模型是yolo v8水平矩形的，我想在预打标签后进行旋转，然后输出dota格式，输出时我发现一个问题，所有的类标签id都是0

![Snipaste_2024-05-26_20-39-46](https://github.com/CVHub520/X-AnyLabeling/assets/59475347/43489551-8b5e-484c-92ac-41dcb16185b9)

**Comment by CVHub520** [comment]
Duplicate of #434.
