### ISSUE TITLE
Question About VOC annotation file?

### ISSUE THREAD

**Issue by aidenyao** [CVHub520/X-AnyLabeling#436]
voc的标签格式是这样的
![Screenshot from 2024-05-27 16-13-45](https://github.com/CVHub520/X-AnyLabeling/assets/23426604/34717f27-fab7-4fe5-a99f-48027a07e578)

但是X-AnyLabeling软件导出的voc格式为什么是这样的
[
![Screenshot from 2024-05-27 16-15-24](https://github.com/CVHub520/X-AnyLabeling/assets/23426604/547843cd-9b9c-4eec-9eca-c4cfbe820b59)
](url)

**Comment by CVHub520** [comment]
您好，你这边看到的标签是 X-AnyLabeling 内部的自定义标签，会在标注的过程中自动创建，默认保存在当前图像目录。

如果需要导出 voc 标签，请直接点击上方菜单栏的导出按钮，会默认保存在图片文件夹所在的父目录下。
