### ISSUE TITLE
【question】 Please advise on how to call rectangle

### ISSUE THREAD

**Issue by jiangtangaaaa** [CVHub520/X-AnyLabeling#437]
Hello developer, I would like to ask you two questions
I want to call the annotation method of rectangle, in addition to calling this function self. parent. loggle_draw_mode (False, There is no more direct way or directly call which method in canvas. py (createMode="rectangle")
Also, let me give an example: when I call the rectangle annotation, when I click on the second point with the mouse, the Labeldialog will pop up. Where is this logic written
Thank you, developers!

![image](https://github.com/CVHub520/X-AnyLabeling/assets/101043186/c3fbbe34-8848-48e2-8a3a-1be8569ff6cf)

**Comment by CVHub520** [comment]
Hi there!

Thank you for reaching out with your questions.

Regarding the annotation method for drawing rectangles, the approach you mentioned using `self.parent.loggle_draw_mode(False)` is indeed one way to toggle between drawing modes. However, for a more direct method or to understand the underlying logic, you might need to look into the source code, particularly within the `canvas.py` file where the drawing modes are defined. Unfortunately, I am unable to provide a specific method call for this functionality as it may vary depending on the implementation details of the project.

As for the logic that triggers the `LabelDialog` upon selecting the second point of the rectangle, this is also something that would be defined within the codebase, likely connected to the event handler for the mouse click that finalizes the rectangle drawing. To pinpoint exactly where this is written, you would need to search through the source code, focusing on the event handlers and the logic that manages user interactions with the drawing tools.

While I'm unable to provide the exact solutions, I encourage you to explore the source code, as this can be a valuable learning experience and may help you better understand the inner workings of the tool. If you encounter any issues or have further questions during your debugging process, please feel free to reach out for assistance.

Wishing you the best with your development efforts!

Warm regards,
CVHub

**Comment by jiangtangaaaa** [comment]
感谢您的指点，谢谢！
