### ISSUE TITLE
Custom YOLOv8n Segmentation Model Loads but Fails to Segment Objects

### ISSUE THREAD

**Issue by hamedgorji** [CVHub520/X-AnyLabeling#440]
Hello,

I am encountering an issue with X-AnyLabeling where my custom YOLOv8n segmentation model, in ONNX format, is successfully loaded into the software but fails to segment any objects in the provided images. I followed the instructions to create a YAML configuration file, and the model uploads without errors. However, it fails to identify any objects in the test images. I uploaded my ONNX model, the YAML file, and a test image. I would appreciate it if you could help me resolve the issue.

[labelstest.zip](https://github.com/CVHub520/X-AnyLabeling/files/15490985/labelstest.zip)

Thanks

**Comment by CVHub520** [comment]
Hi, here!

Thank you for reaching out. It appears that the issue may be related to an incorrect model type field in the YAML configuration file. Please ensure that the model type is correctly specified.

```YAML
type: yolov8_seg
...
```

Additionally, I recommend using the latest YOLOv8 from the official [Ultralytics](https://github.com/ultralytics/ultralytics) repository to export your model. 

Finally, verify the exported *.onnx model by running inference directly in the official repository, refer to the [docs](https://docs.ultralytics.com/modes/predict).

By following these steps, you can ensure that your model is correctly exported and functional. Please update the model type in the YAML file accordingly and try uploading the newly exported model.

If you continue to experience issues, please provide the updated YAML file, and I'll be happy to assist further.

Thanks.

**Comment by hamedgorji** [comment]
Hi,
Thanks for your help. I've changed the type to `yolov8_seg`, and now it seems the model is loading and working successfully. However, the issue is that despite detecting the objects, the polygons do not appear on the main screen. 
Please check the attached file.
Thanks
![X](https://github.com/CVHub520/X-AnyLabeling/assets/126809337/4cbf1eb9-83ea-4098-bb72-e966035703fb)

**Comment by hamedgorji** [comment]
@CVHub520 Any update on this issue?

**Comment by CVHub520** [comment]
Hi, there!

Thank you for your update. It's great to hear that you've managed to change the model type to yolov8_seg and that the model is now loading and functioning correctly.

As for the GPU version crashing when you upload your model, we understand that this can be frustrating. We recommend using the CPU version as a temporary solution until the GPU version is stable for your specific model.

For further assistance, we suggest you try debugging the issue by using the source code. You can locate the relevant files and debug the code to identify any potential issues. This will help us provide more targeted support and solutions.

Thank you for your patience and understanding. We're here to help you resolve any issues you may encounter.

Best regards,
CVHub

**Comment by pinnintipraneethkumar** [comment]
Hii, I have also same problem when loading the custom model, both CPU and GPU crashes while loading the model.
my config file:
type: yolov8
name: yolov8s-seg-custom
display_name: bottle
model_path: C:\Users\runs\segment\best.onnx
nms_threshold: 0.15
confidence_threshold: 0.15
classes:
  - bottle
