### ISSUE TITLE
Error with Error in loading model: exceptions must derive from BaseException 

### ISSUE THREAD

**Issue by maryhh** [CVHub520/X-AnyLabeling#441]
hi,我按照教程按照，cuda是11.6 onnxruntime-gpu==1.13.1 
app_info.py设置 __preferred_device__ = "GPU"  # GPU or CPU
下载的模型存放在yaml同级目录下了，yaml文件也修改了
![image](https://github.com/CVHub520/X-AnyLabeling/assets/26423386/e9b132c9-5582-41ef-84d7-2bf19f7be87f)

但是打开gui，load model 报错如下：
![image](https://github.com/CVHub520/X-AnyLabeling/assets/26423386/62543f34-5189-4c79-832a-32f26812ab35)

建议我应该从哪里进行排查呢？

**Comment by CVHub520** [comment]
> hi,我按照教程按照，cuda是11.6 onnxruntime-gpu==1.13.1 app_info.py设置 **preferred_device** = "GPU" # GPU or CPU 下载的模型存放在yaml同级目录下了，yaml文件也修改了 ![image](https://private-user-images.githubusercontent.com/26423386/335522553-e9b132c9-5582-41ef-84d7-2bf19f7be87f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDkyMTAsIm5iZiI6MTcxNzE0ODkxMCwicGF0aCI6Ii8yNjQyMzM4Ni8zMzU1MjI1NTMtZTliMTMyYzktNTU4Mi00MWVmLTg0ZDctMmJmMTlmN2JlODdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA5NDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZDY5NDUwN2IzZGVjMWMyZjg4ZDFiM2RhMzRlNGI0OTIwZjZmYzZjMTA0NjQzMDhiZWVmNWUyMDVlMTM4MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pw4PwP69Qte8yW5rxP-tqcj50zVgyz7tyyc10-yMXcs)
> 
> 但是打开gui，load model 报错如下： ![image](https://private-user-images.githubusercontent.com/26423386/335523308-62543f34-5189-4c79-832a-32f26812ab35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDkyMTAsIm5iZiI6MTcxNzE0ODkxMCwicGF0aCI6Ii8yNjQyMzM4Ni8zMzU1MjMzMDgtNjI1NDNmMzQtNTE4OS00Yzc5LTgzMmEtMzJmMjY4MTJhYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA5NDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiY2JkOWFkMzcwZjVjYTI1ZGQ0MmQ4NWY3M2I0NTdhMmM1MzNlY2Y3YzE2YTkwYWNlMmI1MTEzZjYzZjQ2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pXpG7VbpgJWlqrNV8EPchDS9I1czEfU8yeFTj81i-Ko)
> 
> 建议我应该从哪里进行排查呢？

您好，请先测试下其它模型是否能正常推理。另外麻烦提供下当前下载的版本号（菜单栏上方帮助选项下的版本信息），还有检查下你的文件是否下载完全。

**Comment by yutianku** [comment]
您好！运行自定义模型，也遇到楼主同样的问题，软件版本CPU 2.3.6/2.3.5,运行下载的模型能正常推理

**Comment by CVHub520** [comment]
> 您好！运行自定义模型，也遇到楼主同样的问题，软件版本CPU 2.3.6/2.3.5,运行下载的模型能正常推理

检查配置文件的各个参数是否与对应模型配置文件的参数一致，另外需要确认是否是已适配模型。

**Comment by maryhh** [comment]
> > hi,我按照教程按照，cuda是11.6 onnxruntime-gpu==1.13.1 app_info.py设置 **preferred_device** = "GPU" # GPU or CPU 下载的模型存放在yaml同级目录下了，yaml文件也修改了 ![image](https://private-user-images.githubusercontent.com/26423386/335522553-e9b132c9-5582-41ef-84d7-2bf19f7be87f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDkyMTAsIm5iZiI6MTcxNzE0ODkxMCwicGF0aCI6Ii8yNjQyMzM4Ni8zMzU1MjI1NTMtZTliMTMyYzktNTU4Mi00MWVmLTg0ZDctMmJmMTlmN2JlODdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA5NDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZDY5NDUwN2IzZGVjMWMyZjg4ZDFiM2RhMzRlNGI0OTIwZjZmYzZjMTA0NjQzMDhiZWVmNWUyMDVlMTM4MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pw4PwP69Qte8yW5rxP-tqcj50zVgyz7tyyc10-yMXcs)
> > 但是打开gui，load model 报错如下： ![image](https://private-user-images.githubusercontent.com/26423386/335523308-62543f34-5189-4c79-832a-32f26812ab35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDkyMTAsIm5iZiI6MTcxNzE0ODkxMCwicGF0aCI6Ii8yNjQyMzM4Ni8zMzU1MjMzMDgtNjI1NDNmMzQtNTE4OS00Yzc5LTgzMmEtMzJmMjY4MTJhYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA5NDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiY2JkOWFkMzcwZjVjYTI1ZGQ0MmQ4NWY3M2I0NTdhMmM1MzNlY2Y3YzE2YTkwYWNlMmI1MTEzZjYzZjQ2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pXpG7VbpgJWlqrNV8EPchDS9I1czEfU8yeFTj81i-Ko)
> > 建议我应该从哪里进行排查呢？
> 
> 您好，请先测试下其它模型是否能正常推理。另外麻烦提供下当前下载的版本号（菜单栏上方帮助选项下的版本信息），还有检查下你的文件是否下载完全。

我用yolov5-seg 自己下载放进去也不行，我确认了模型下载完整，版本信息就是最新的2.3.6 GPU版本
![image](https://github.com/CVHub520/X-AnyLabeling/assets/26423386/0f8d06dd-705f-48b9-96d2-d35e204c1653)
