### ISSUE TITLE
Bug: unable to upload voc labels 

### ISSUE THREAD

**Issue by maryhh** [CVHub520/X-AnyLabeling#442]
hi，如果我的xml标签和jpg是放在一个目录下，那么就没有办法自动识别标签文件，需要另外建一个文件夹把标签放过去，upload才可以，但是json格式的如果是放在同一个目录下就可以自动识别。

**Comment by CVHub520** [comment]
> hi，如果我的xml标签和jpg是放在一个目录下，那么就没有办法自动识别标签文件，需要另外建一个文件夹把标签放过去，upload才可以，但是json格式的如果是放在同一个目录下就可以自动识别。

您好，这边只会对接内置的json标签文件，其它格式标签统一通过[Upload&Export](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E6%A0%87%E7%AD%BE%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA)接口管理。
