### ISSUE TITLE
导出mask图片少于原始图片

### ISSUE THREAD

**Issue by XinZhenRen** [CVHub520/X-AnyLabeling#443]
按照如下json文件导出的mask少于正常图片数量
`{
    "type": "grayscale",
    "colors": {
        "LSIL": 64,
        "HSIL": 128,
        "CA": 255
    }
}
`
我似乎发现了出现问题的原因，如果这个图片中只含有Rectangular框，那这个图片就不会导出mask。

**Comment by CVHub520** [comment]
@XinZhenRen @lzd-1230 当前设定是这样的，mask 仅对 `polygon` 对象生效。如果需要自定义的可以修改此[函数](https://github.com/CVHub520/X-AnyLabeling/blob/98a95db7f7a310b1a5c094c912bc8a4aea2a86cd/anylabeling/views/labeling/label_converter.py#L754)。
