### ISSUE TITLE
去除标注区域内的阴影

### ISSUE THREAD

**Issue by GrwyYJ** [CVHub520/X-AnyLabeling#445]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/118507922/32b1b856-a655-4c35-bb04-3bb40e6a8e56)  
开发者你好，在标注多边形时标注区域内的白色阴影是否可以去除  
![image](https://github.com/CVHub520/X-AnyLabeling/assets/118507922/144b87e3-0196-486d-8407-c338d6a42ecb)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/118507922/ba0f3d9e-391e-462f-bfd6-adef6174bad3)

标注完成后，去除选定后标注区域内的阴影

**Comment by CVHub520** [comment]
@GrwyYJ，已支持，欢迎更新源码使用。

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/3398835d-7a3e-49ae-943c-b248f90bbe28)
