### ISSUE TITLE
Why the GUI Discrepancies Compared to Official X-AnyLabeling?

### ISSUE THREAD

**Issue by hwuscut** [CVHub520/X-AnyLabeling#450]
下载的X-AnyLabeling-2.3.6.zip版本，安装requirements-gpu-dev.txt。运行时界面上少了导入和导出按钮。还出现下面问题：
Skipping unexpected key in config: save_mode
Skipping unexpected key in config: save_mode
Skipping unexpected key in config: save_mode

![1717922841060](https://github.com/CVHub520/X-AnyLabeling/assets/12271927/c9dfdc34-6d69-4220-a7ce-033e2ab9eb25)

下载的X-AnyLabeling-CPU.exe，运行界面有导入和导出按钮：

![image](https://github.com/CVHub520/X-AnyLabeling/assets/12271927/c9390adc-c211-450d-b467-b4400ba2ab1f)

**Comment by CVHub520** [comment]
@hwuscut, Hi, there!

Thank you for your patience. It appears that uninstalling `anylabeling` using `pip` is the solution to the problems you're facing. This step will remove any conflicting or incorrect installations of the package.

To clarify, please run the following command in your Python environment to uninstall `anylabeling`:

```bash
pip uninstall anylabeling
```

After uninstalling, you can then follow the official [installation instructions](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md#%E6%BA%90%E7%A0%81%E8%BF%90%E8%A1%8C) provided for the X-AnyLabeling version you're using.

If you encounter any further issues or have additional questions, please don't hesitate to reach out. We're here to help!

Good lucks!
