### ISSUE TITLE
Label_Converter OBB Support Request

### ISSUE THREAD

**Issue by SwEngine** [CVHub520/X-AnyLabeling#451]
Can you add support of **yolo2custom** for **rotation** task? Its very crucial for yolov8-obb datasets.

**Comment by CVHub520** [comment]
Hello SwEngine,

Thank you for your inquiry. I'm glad to inform you that support for converting YOLO-OBB annotations to the custom format has been available for quite some time. You can download the latest version of X-AnyLabeling or update the source code to access this functionality. To upload YOLO-OBB annotations, simply visit the top menu bar -> Upload -> Upload YOLO-Obb Annotations.

We hope this information is helpful. If you have any further questions or issues, please don't hesitate to reach out.

Best regards,
CVHub

**Comment by SwEngine** [comment]
Annotation uploading is supported but label_converter does not has support of yolo2custom for rotation task.

**Comment by CVHub520** [comment]
https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/views/labeling/label_converter.py#L213

**Comment by SwEngine** [comment]
Thank you so much! I was looking at https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/label_converter.py 
The script has no support, but yours has. However, the script you gave can not be called from terminal.

**Comment by CVHub520** [comment]
Hi, there!

Thank you for your feedback. I understand that you're looking for a script that can be called from the terminal for batch processing.

The script you found in the repository (`label_converter.py`) is indeed an older version that may not be maintained. We recommend using the GUI interface for importing and exporting labels as it provides a more user-friendly experience and may include updates or fixes that the command-line script does not.

However, if you need to perform batch processing, you can look at the provided file as a reference and add the necessary functionality to the `label_converter.py` script yourself. This would allow you to call the script from the terminal and process multiple files at once.

If you encounter any issues or need further assistance with this, please let us know, and we'll do our best to help you out.

Good lucks!
CVHub
