### ISSUE TITLE
A suggestion: Quick change of confidence threshold

### ISSUE THREAD

**Issue by YoulQey** [CVHub520/X-AnyLabeling#454]
A suggestion:
Now, it can only decide whether to label based on the confidence parameter in the config.yaml file. If the value can be changed in real-time on the interface, it will be much more convenient.

**Comment by CVHub520** [comment]
Hi, there! @YoulQey

Thank you for your suggestion. It's a great idea to have the confidence parameter adjustable in real-time on the interface. This would allow for more flexibility in labeling and could be particularly useful for tasks where the optimal confidence threshold may vary based on the specific context or user preference.

I will take this suggestion into consideration and prioritize it based on our development schedule and the needs of our users. If we decide to implement this feature, we will be sure to notify you through the appropriate channels.

If you have any other suggestions or issues you'd like to share, please feel free to do so. Your input is invaluable to us.

Best regards,
CVHub

**Comment by CVHub520** [comment]
Exciting update! You can now adjust the confidence parameter in real-time on the interface. No more need to edit the config.yaml file manually. Go ahead, pull the latest changes, and test the new feature!

**Comment by YoulQey** [comment]
Exciting update! Quick and perfect work, tried and ran exactly as expected!
