### ISSUE TITLE
Feature Request: Option to Preserve Existing Annotations During Auto-Labeling

### ISSUE THREAD

**Issue by peters** [CVHub520/X-AnyLabeling#455]
The auto-labeling feature currently overwrites existing annotations, which can disrupt workflows where manual and automatic annotations coexist. To address this, I propose adding a checkbox labeled "Preserve existing annotations" in the auto-labeling settings. When checked, this option should allow the application to skip auto-labeling for data points that already have annotations, preserving any manual input while still labeling unannotated data.

**Comment by CVHub520** [comment]
Hi, @peters:

Thank you for your feature request. It's a great suggestion and we'll consider adding it to our roadmap.

The idea of allowing users to preserve existing annotations during auto-labeling is very useful for workflows where manual and automatic annotations are used together. We'll work on incorporating this feature into a future update of X-AnyLabeling.

Please stay tuned for updates, and if you have any other suggestions or issues, feel free to let me know.

Best regards,
CVHub

**Comment by CVHub520** [comment]
Great news! We’ve just added a ‘Preserve existing annotations’ checkbox to the auto-labeling settings. Now you can easily coexist with manual and automatic annotations without overwriting. Feel free to pull the latest code and give it a try!

**Comment by peters** [comment]
Wow, that was fast! :dancers:  I've pulled the latest code and it works as expected. Great work! Thank you :rocket:

**Comment by peters** [comment]
When switching between models, existing labels are not preserved. Restarting the application temporarily resolves the problem, but the issue reoccurs when changing models again.

**Steps to Reproduce**:

Open the application and load a model.
Add labels to the data.
Switch to a different model.
Observe that the previously added labels are not preserved.

**Expected Behavior**:
Labels should be preserved when switching between models.

**Actual Behavior**:
Labels disappear when changing models.

**Temporary Workaround**:
Restarting the application restores the labels, but they are lost again upon changing models.

**Comment by CVHub520** [comment]
Hello @peters 👋,

Thank you for reporting the issue with label preservation when switching between models. I'm pleased to inform you that this issue has been addressed and fixed as part of issue #590. 🎉

The latest update ensures that labels are now preserved when switching model instances, eliminating the need for a restart to maintain your annotations. Please pull the latest changes from the repository to incorporate this fix into your workflow.

If you encounter any further issues or have additional feedback, feel free to let us know. We appreciate your contribution to making X-AnyLabeling better! 🙏
