### ISSUE TITLE
AttributeError: 'LabelDialog' object has no attribute 'current_visibility'. Did you mean: 'get_visibility'?

### ISSUE THREAD

**Issue by zixindh** [CVHub520/X-AnyLabeling#457]
when I try to use rectangle to label umbrella. the python app.py will be closed abrubtly. The error is shown in my Anaconda Prompt: AttributeError: 'LabelDialog' object has no attribute 'current_visibility'. Did you mean: 'get_visibility'?. I am using Windows 10, Python 3.11. 

The python app.py will be closed after i created an umbrella label, and clicked OK in below interface. 

<img width="272" alt="xlabeling issue" src="https://github.com/CVHub520/X-AnyLabeling/assets/20818701/74ae9edb-b26c-4679-b64c-4720aa8f00a6">

**Comment by CVHub520** [comment]
Hi, @zixindh:

I apologize for the inconvenience you've experienced. It seems that there was an issue with the application that caused it to close abruptly. The error you've encountered is related to a missing attribute in the LabelDialog object, which suggests a bug in the application's code.

I have addressed this issue in the latest version of the application. You can update to the new version by re-cloning the repository or downloading the latest release. This should resolve the problem you've encountered.

If you continue to face issues, please report them in the appropriate issue tracker or contact support for further assistance.

Thank you for your patience, and i appreciate your understanding as my work to improve the application.

Best regards,
CVHub
