### ISSUE TITLE
yolov5_seg not working

### ISSUE THREAD

**Issue by SahadevPoudel** [CVHub520/X-AnyLabeling#458]
I wanna test my own yolo-based segmentation model. First, I tested default yolo_seg model to check. However everytime it shows invalid config file format.

I have attached the screenshot of the configuration file and the error.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/20927897/43e5075e-0b0c-4c71-af99-0ad88b8d86ad)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/20927897/bba00fad-73b0-4b2f-890b-453373736387)

How to solve this issue?Anyone facing same problem?

**Comment by CVHub520** [comment]
Hi, there! @SahadevPoudel:

Thank you for providing the details of the issue you're facing. The error message you're encountering suggests that the `model_path` you've provided in your configuration file is not valid.

To fix this issue, you need to ensure that the path you're specifying is correct and accessible from the location where the configuration file is being read. In your case, the path seems to be referencing a location within a Wins environment.

Here are a few tips to resolve the issue:

1. **Check the Path**: Verify that the path is correct and that the model file exists at the specified location.

2. **Relative vs. Absolute Paths**: Make sure you're using an absolute path if the model is not in the same directory as the configuration file.

3. **Escaping Characters**: If you're using backslashes in the path (as seen in your screenshot), ensure that they are properly escaped. On Windows, you might need to use double backslashes or use forward slashes (`/`) instead.

Here's an example of how you might correct the path:

```yaml
type: yolov5_seg
...
model_path: C:\\Users\\sahad\\Downloads\\X-AnuLabeling-2.3.6\\X-AnyLabeling-2.3.6\\custom_model\\yolov5s-seg.onnx
```

If you continue to face issues, please double-check the path and ensure that it is correct. If you’re still unable to resolve the problem, please provide more context or additional details, and we’ll do our best to assist you further.

Best regards,
CVHub

**Comment by SahadevPoudel** [comment]
Hi, i just checked as you suggested. I am getting same problem as before. However, it runs successfully in ubuntu. Seems like there are some issues while running in windows.
