### ISSUE TITLE
如何加载自定义语义分割模型

### ISSUE THREAD

**Issue by yo-WASSUP** [CVHub520/X-AnyLabeling#46]
https://github.com/JCruan519/EGE-UNet
您好，请问怎么将EGE-unet的onnx模型加载到此项目中呢？
训练的是分割单个类别的权重，但输入图像需要进行减均值除方差的处理。
因为直接用SAM自动标注的效果很差，所以想加载自己训练的模型。
感谢作者的解答

**Comment by CVHub520** [comment]
> https://github.com/JCruan519/EGE-UNet 您好，请问怎么将EGE-unet的onnx模型加载到此项目中呢？ 训练的是分割单个类别的权重，但输入图像需要进行减均值除方差的处理。 因为直接用SAM自动标注的效果很差，所以想加载自己训练的模型。 感谢作者的解答

您好，v0.2.0 分支已支持 SAM-Medical 相关系列模型，可以尝试一下[LVM-Med](https://github.com/CVHub520/X-AnyLabeling/tree/main/assets/examples/isic) 中的 ISIC 相关模型。关于 `EGE-UNet` 需要改动下源码自行适配下。
