### ISSUE TITLE
How can AnyLabeling directly export yolov-obb/yolov-seg/yolov-pose  formats?

### ISSUE THREAD

**Issue by wjhmiss** [CVHub520/X-AnyLabeling#460]
How can AnyLabeling directly export yolov-obb/yolov-seg/yolov-pose  formats?

**Comment by gbo999** [comment]
sorry to interfere, how much time do you think it would take?

**Comment by wjhmiss** [comment]
@CVHub520 Thank you for your reply. For YOLOv8，  I only saw the YOLO tag and did not see any other types of tags
![1718680449431](https://github.com/CVHub520/X-AnyLabeling/assets/6950490/b3a04d13-72bc-4c44-bdad-d749f1868fbe)
（YOLO-HBB, YOLO-OBB and YOLO-SEG ) format = yolo标签

**Comment by CVHub520** [comment]
> @CVHub520 Thank you for your reply. For YOLOv8， I only saw the YOLO tag and did not see any other types of tags ![1718680449431](https://private-user-images.githubusercontent.com/6950490/340524276-b3a04d13-72bc-4c44-bdad-d749f1868fbe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDM3NTcsIm5iZiI6MTcxODgwMzQ1NywicGF0aCI6Ii82OTUwNDkwLzM0MDUyNDI3Ni1iM2EwNGQxMy03MmJjLTRjNDQtYmRhZC1kNzQ5ZjE4NjhmYmUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTMyNDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTUyYmVkNGIyNDk5ZjM4M2UzZmIzYmJlMWY5ZTU2MjdlNWU1YjdiMzdjNjYzNjA1OTc3NWRhYzBjNzI3ZTNhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JUE7YyNpj2QMkAyij7bQ2ppL-jOA6y_R5qlcZlniE9s) （YOLO-HBB, YOLO-OBB and YOLO-SEG ) format = yolo标签

In this version, you can directly export in YOLO format.

**Comment by CVHub520** [comment]
> @CVHub520 Thank you for your reply. For YOLOv8， I only saw the YOLO tag and did not see any other types of tags ![1718680449431](https://private-user-images.githubusercontent.com/6950490/340524276-b3a04d13-72bc-4c44-bdad-d749f1868fbe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDM3NTcsIm5iZiI6MTcxODgwMzQ1NywicGF0aCI6Ii82OTUwNDkwLzM0MDUyNDI3Ni1iM2EwNGQxMy03MmJjLTRjNDQtYmRhZC1kNzQ5ZjE4NjhmYmUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTMyNDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTUyYmVkNGIyNDk5ZjM4M2UzZmIzYmJlMWY5ZTU2MjdlNWU1YjdiMzdjNjYzNjA1OTc3NWRhYzBjNzI3ZTNhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JUE7YyNpj2QMkAyij7bQ2ppL-jOA6y_R5qlcZlniE9s) （YOLO-HBB, YOLO-OBB and YOLO-SEG ) format = yolo标签

The new version will be released within this week, barring any unforeseen circumstances.

**Comment by CVHub520** [comment]
Hey, @wjhmiss @gbo999 :

🎉 The feature to directly export in yolov-obb/yolov-seg/yolov-pose formats is already supported in X-AnyLabeling. 

Please pull the latest source code to try it out. You can find the tutorial and documentation here: [user_guide.md](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide) or [用户手册](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md). 

Enjoy the new feature!

**Comment by CVHub520** [comment]
#5, #103, #117, #181, #215, #218

**Comment by CVHub520** [comment]
#394
