### ISSUE TITLE
关于grounding dino预处理代码的疑问

### ISSUE THREAD

**Issue by talebolano** [CVHub520/X-AnyLabeling#461]
请问为什么将specical_tokens 固定设为[101, 102, 1012, 1029]，是否可以提供一个输入让用户可以自主选择position_ids？
```python
specical_tokens = [101, 102, 1012, 1029]
```

**Comment by CVHub520** [comment]
Hi, @talebolano:

Thank you for your question! 🌟

The special tokens [101, 102, 1012, 1029] you're referring to are indeed used to represent the special tokens ["[CLS]", "[SEP]", ".", "?"]. These tokens are commonly used in NLP tasks, such as BERT (also designed for GroundingDINO text encoder), to identify the beginning and end of sentences, and to mark the end of input sequences.

Currently, the default values for these special tokens are hardcoded to ensure consistency across different models and tasks. However, we understand that users might have different requirements or might want to use custom special tokens.

To address this, we can consider adding a feature that allows users to specify their own set of special tokens. This would give users the flexibility to choose the tokens that best suit their specific use case.

We will take this suggestion into consideration and prioritize it based on our development schedule and the needs of our users. If we decide to implement this feature, we will be sure to notify you through the appropriate channels.

Thank you for your patience and understanding. We're here to help you resolve any issues you may encounter.

Best regards,
CVHub

**Comment by talebolano** [comment]
@CVHub520 非常感谢您的解释！关于grounding DINO还有另外一个问题，如何生成groundingdino_fuse_attention.onnx这样fuse了biasgelu和attention的模型
![image](https://github.com/CVHub520/X-AnyLabeling/assets/38694989/5fa61f5a-1a1c-4924-9620-21a49d367cb9)
