### ISSUE TITLE
是否支持mac M 系列芯片推理

### ISSUE THREAD

**Issue by swpucwf** [CVHub520/X-AnyLabeling#462]
是否支持mac M 系列芯片推理

**Comment by CVHub520** [comment]
Hi, there! @swpucwf:

Thank you for your inquiry! 🌟

At the moment, we haven't tested X-AnyLabeling on Macs with M-series chips. However, PyQt5 is a cross-platform GUI library, so in theory, X-AnyLabeling should work on Macs with M-series chips.

We recommend giving it a try on your own. If you encounter any issues, feel free to let us know, and we'll do our best to assist you.

Thank you for your support, and we hope you have a great experience with X-AnyLabeling! 🌟

Best regards,
CVHub
