### ISSUE TITLE
GPU is not working while auto labeling with AI models

### ISSUE THREAD

**Issue by JasonSloan** [CVHub520/X-AnyLabeling#464]
**Environment:**
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.27.5
Libc version: glibc-2.35

Python version: 3.9.17 (main, Jul  5 2023, 20:41:20)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070 SUPER
Nvidia driver version: 535.129.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.0
[pip3] torchmetrics==1.1.2
[pip3] torchvision==0.14.0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] torch                     1.13.0                   pypi_0    pypi
[conda] torchmetrics              1.1.2                    pypi_0    pypi
[conda] torchvision               0.14.0                   pypi_0    pypi
onnxruntime                    1.16.1
onnxruntime-gpu                1.18.0

**Description:**
I installed the gpu environment with "pip install -r requirements-gpu.txt" in a conda env.
I modified the device from "CPU" to "GPU" in file "app_info.py".
I run the "GroudingDino" model with anylabeling app.
The gpu wasnt used at all when I tried tp auto-label the images while the cpu was used heavily.
The usage of gpu and cpu is below:
![question](https://github.com/CVHub520/X-AnyLabeling/assets/92148610/9503f19b-9a83-4671-9fe4-6b2b8aa9160a)

How can I make use of gpu? Thanks!

Besides, my gpu works well with torch.
![q2](https://github.com/CVHub520/X-AnyLabeling/assets/92148610/a382c18b-c9c1-4ecc-ae4f-09a05ef6823d)

**Comment by CVHub520** [comment]
@JasonSloan, Hey!

To utilize your GPU with X-AnyLabeling, you need to ensure that the environment supports GPU acceleration. Currently, the inference backend is `onnxruntime-gpu`, which means that your GPU should be compatible with the version of ONNX Runtime you have installed.

Here's how you can proceed:

1. **Install ONNX Runtime GPU**: Make sure you have the ONNX Runtime GPU version installed. You can find installation instructions on the ONNX Runtime [official documentation](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html).

2. **Check GPU Support**: ONNX Runtime has a list of supported GPUs. You should check if your GPU is on that list. If it's not, you might not be able to use GPU acceleration with ONNX Runtime.

3. **Enable GPU in X-AnyLabeling**: Once ONNX Runtime GPU is installed and your GPU is supported, you should be able to enable GPU acceleration in X-AnyLabeling. This is usually done through the settings or configuration file.

4. **Verify GPU Usage**: After enabling GPU acceleration, you should check if X-AnyLabeling is actually using the GPU. This can be done by looking at the system resource usage or by checking the GPU utilization in the X-AnyLabeling interface.

If you have any issues with GPU support or if you need further assistance, please feel free to reach out, and we'll do our best to help you.

Best regards,
CVHub

**Comment by JasonSloan** [comment]
Thanks for your guidance, some of the problems are solved and i would like to make a record.
The problem below solved by "sudo apt install libxcb-*"
![q3](https://github.com/CVHub520/X-AnyLabeling/assets/92148610/2406faa4-ef63-4a78-ab99-937f2e0a0d7e)

The problem below solved by "pip install onnxruntime==1.11.0" and "pip uninstall opencv-python && pip install opencv-python-headless"
![image](https://github.com/CVHub520/X-AnyLabeling/assets/92148610/c5aaaa0f-ba70-4123-8812-3ab81ca7e051)

The problem below solved by 'pip install torch' and 'find libcublasLt**' and set  'LD_LIBRARY_PATH' to '~/.bashrc'
![image](https://github.com/CVHub520/X-AnyLabeling/assets/92148610/c7346fe0-e8d9-4095-93d1-a59bdd4f0c96)

**Comment by CVHub520** [comment]
👍 I'm glad to hear that you've resolved the issues you were facing! 

Thank you for sharing the solutions and providing feedback. It's great to know that the problems were solved by installing the necessary libraries and packages. 

If you encounter any more issues or have further questions, feel free to reach out again. Your contributions to the community's knowledge base are appreciated!

**Comment by CVHub520** [comment]
It's great to hear that you've been able to resolve some issues with your system! Here’s a summary of the solutions you applied:

1. **Missing XCB Libraries**
   - You encountered an issue related to missing `libxcb` libraries which was resolved by running:
     ```bash
     sudo apt install libxcb-*
     ```

2. **ONNX Runtime and OpenCV Compatibility**
   - The problem regarding ONNX Runtime and OpenCV compatibility was fixed by installing a specific version of ONNX Runtime and then reinstalling OpenCV in headless mode:
     ```bash
     pip install onnxruntime==1.11.0
     pip uninstall opencv-python
     pip install opencv-python-headless
     ```
Please refer to this [document](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html) to install the matching version of GPU.

3. **PyTorch Installation and CUDA Library Path**

Please note that X-AnyLabeling does not depend on any pytorch environment. It is recommended to create a new virtual environment and install it according to the [tutorial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md#%E6%BA%90%E7%A0%81%E8%BF%90%E8%A1%8C)

These steps should help others who might face similar issues when setting up their development environments. If you have any further questions or need additional assistance, feel free to ask! Your contributions to troubleshooting can also be very helpful to the community, so consider sharing your solutions on forums or documentation sites if you haven't already.

**Comment by JasonSloan** [comment]
> It's great to hear that you've been able to resolve some issues with your system! Here’s a summary of the solutions you applied:
> 
> 1. **Missing XCB Libraries**
>    
>    * You encountered an issue related to missing `libxcb` libraries which was resolved by running:
>      ```shell
>      sudo apt install libxcb-*
>      ```
> 2. **ONNX Runtime and OpenCV Compatibility**
>    
>    * The problem regarding ONNX Runtime and OpenCV compatibility was fixed by installing a specific version of ONNX Runtime and then reinstalling OpenCV in headless mode:
>      ```shell
>      pip install onnxruntime==1.11.0
>      pip uninstall opencv-python
>      pip install opencv-python-headless
>      ```
> 
> Please refer to this [document](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html) to install the matching version of GPU.
> 
> 3. **PyTorch Installation and CUDA Library Path**
> 
> Please note that X-AnyLabeling does not depend on any pytorch environment. It is recommended to create a new virtual environment and install it according to the [tutorial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md#%E6%BA%90%E7%A0%81%E8%BF%90%E8%A1%8C)
> 
> These steps should help others who might face similar issues when setting up their development environments. If you have any further questions or need additional assistance, feel free to ask! Your contributions to troubleshooting can also be very helpful to the community, so consider sharing your solutions on forums or documentation sites if you haven't already.

OK, thanks, I will close the issue now.
