### ISSUE TITLE
Error in predict_shapes: local variable 'keypoints' referenced before assignment

### ISSUE THREAD

**Issue by jackchen556** [CVHub520/X-AnyLabeling#465]
Error in predict_shapes: local variable 'keypoints' referenced before assignment，can't infer image through yolo detect model

**Comment by CVHub520** [comment]
@jackchen556  Hi, there!

🔍 It seems you've encountered an issue with the `predict_shapes` function where the variable `keypoints` is being referenced before it's assigned a value. This might be causing the failure to infer images through the YOLO detection model. 

Please try updating to the latest source code to see if the issue has been resolved. 

If you continue to experience this problem after updating, please provide the complete error message and any relevant code snippets. This will help in diagnosing the issue further.
