### ISSUE TITLE
Windows端Python兼容性

### ISSUE THREAD

**Issue by BetterWorld-Liuser** [CVHub520/X-AnyLabeling#466]
试了python3.10 python3.11 python 3.12 版本安装requirement-gpu后均无法从源码启动。Python3.8 通过。

**Comment by CVHub520** [comment]
Thank you for your feedback. 👀 

It's noted that you've encountered issues with Python versions 3.10, 3.11, and 3.12 when installing `requirement-gpu` and trying to start the application from source, while Python 3.8 is working fine. 

Currently, i haven't tested Python versions 3.10 and above on Windows systems. I will conduct further tests on these versions. Your report will help us improve compatibility and ensure a smoother experience for all users.

**Comment by protester16** [comment]
> [@BetterWorld-Liuser](https://github.com/BetterWorld-Liuser), Hey!
> 
> [@BetterWorld-Liuser](https://github.com/BetterWorld-Liuser)，嘿！
> 
> The compatibility issue with Python versions 3.10, 3.11, and 3.12 on the Windows platform has been resolved. 🎉
> 
> 与Windows平台上Python版本3.10、3.11和3.12的兼容性问题已得到解决。🎉
> 
> All versions from Python 3.8 to 3.12 have been tested and are working properly. Please update to the latest source code to enjoy the fixes.
> 
> 从Python 3.8到3.12的所有版本都经过测试并正常工作。请更新到最新的源代码以享受修复。
> 
> If you encounter any further issues, feel free to report them. Thank you for your patience and support!
> 
> 如果您遇到任何进一步的问题，请随时报告。感谢您的耐心和支持！

The latest version of python3.13 cannot be installed successfully, but python3.12 is OK
