### ISSUE TITLE
onnx推理代码

### ISSUE THREAD

**Issue by winner-4** [CVHub520/X-AnyLabeling#467]
作者您好，请问是否可以提供sam Onnx推理的python代码呢？我只想要一个类别的标签，例如胡须

**Comment by CVHub520** [comment]
https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/sam_onnx.py

**Comment by winner-4** [comment]
非常感谢您！能否提供使用的示例呢？

**Comment by winner-4** [comment]
请问prompt该怎么定义？

**Comment by CVHub520** [comment]
Certainly! You're welcome to modify and use the example provided in this [file](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/segment_anything.py) as a reference. 

If you have any specific questions or require further assistance, feel free to ask. Happy coding!
