### ISSUE TITLE
十字线 还有 打标线框的颜色可以自定义吗

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#470]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/a9b3c6b8-894b-406c-ad82-e8cd077540dd)
  如图上所示  您所看到的那样
  这个默认的绿色 辅助十字线 在我的图上几乎不可见 看起来很累
  我可以修改成其他颜色么
  还有可以 修改其尺寸吗 像这样 
  

https://github.com/CVHub520/X-AnyLabeling/assets/30548000/11b5d0ad-c419-49fa-9a89-c6eb4e40dbdc

**Comment by CVHub520** [comment]
Hey! @lhj5426:

I understand that you would like to customize the color and size of the crosshair and the marking box in the application. 👀

Currently, the feature to change the style of the crosshair is not available in the current version. However, I'm pleased to inform you that this feature is on our roadmap and will be included in the next version, which is expected to be released soon. 

Please look forward to the upcoming update, which will allow you to customize the crosshair to better suit your needs. 

Thank you for your patience and for suggesting improvements to the application!

**Comment by CVHub520** [comment]
Btw, although the current version of the application does not support direct customization of the crosshair and marking box colors and sizes, there is a workaround you can use to adjust the visibility of the crosshair. 

Specifically, you can open the menu bar at the top of the interface, go to `View`, and select `Brightness Contrast`. 🎨 

Here, you can tweak the contrast and saturation to reduce the visual impact. If you find a setting that works for you, you can also check the box for `Keep Previous Scale` or similar options to apply these changes to subsequent images.

Additionally, if you're comfortable with modifying the source code, you can download the source and make changes to the file `X-AnyLabeling/anylabeling/views/labeling/widgets/canvas.py`, specifically on line 1238. 

You can change the color and size of the crosshair by modifying the `QtGui.QColor` and `max(1, int(round(2.0 / Shape.scale)))` values to your desired settings.

Here's an example of how you can change the color and size:
```python
pen = QtGui.QPen(
    QtGui.QColor("#FF0000"),  # Change the color to red
    3,  # Set the line width to 3
    Qt.DashLine,
)
```

Remember to adjust the values to your preference. After making these changes, you'll need to rebuild the application. This temporary solution should help you customize the crosshair until the feature is officially added in the next version.

Best,
CVHub

**Comment by lhj5426** [comment]
> Btw, although the current version of the application does not support direct customization of the crosshair and marking box colors and sizes, there is a workaround you can use to adjust the visibility of the crosshair.
> 
> Specifically, you can open the menu bar at the top of the interface, go to `View`, and select `Brightness Contrast`. 🎨
> 
> Here, you can tweak the contrast and saturation to reduce the visual impact. If you find a setting that works for you, you can also check the box for `Keep Previous Scale` or similar options to apply these changes to subsequent images.
> 
> Additionally, if you're comfortable with modifying the _source_ code, you can_ download _the _source_ and make changes to the file `X-AnyLabeling/anylabeling/views/labeling/widgets/canvas.py`, specifically on line 1238.
> 
> You can change the color and size of the crosshair by modifying the `QtGui.QColor` and `max(1, int(round(2.0 / Shape.scale)))` values to your desired settings.
> 
> Here's an example of how you can change the color and size:
> 
> ```python
> pen = QtGui.QPen(
>     QtGui.QColor("#FF0000"),  # Change the color to red
>     3,  # Set the line width to 3
>     Qt.DashLine,
> )
> ```
> 
> Remember to adjust the values to your preference. After making these changes, you'll need to rebuild the application. This temporary solution should help you customize the crosshair until the feature is officially added in the next version.
> 
> Best, CVHub

Thank you for your response. 
I will try the temporary solution you proposed. 
And I am looking forward to the future new version. 
Thank you for your help.

**Comment by CVHub520** [comment]
Hey there! 🎉

I'm excited to let you know that we've just pushed an update to our repository, where we've implemented the feature you requested. You can now customize the color and size of the crosshair and marking box in our application. 🎨

Please give it a try and let us know if everything works as expected. Your feedback is invaluable to us, and we're always striving to improve your experience. 🚀

Thank you for your patience and for contributing to making our application better! If you have any further suggestions or issues, don't hesitate to reach out. 😊


https://github.com/CVHub520/X-AnyLabeling/assets/72010077/381bf84c-7ce0-4534-a9fd-c193e95f1182

**Comment by lhj5426** [comment]
> Hey there! 🎉
> 
> I'm excited to let you know that we've just pushed an update to our repository, where we've implemented the feature you requested. You can now customize the color and size of the crosshair and marking box in our application. 🎨
> 
> Please give it a try and let us know if everything works as expected. Your feedback is invaluable to us, and we're always striving to improve your experience. 🚀
> 
> Thank you for your patience and for contributing to making our application better! If you have any further suggestions or issues, don't hesitate to reach out. 😊
> 
>  1._mp4_

"So fast! Thanks to the efforts of the developers. So where should I download this latest version? I opened it here but it seems I can't see it? EXE"
https://github.com/CVHub520/X-AnyLabeling/releases

**Comment by CVHub520** [comment]
> > Hey there! 🎉
> > I'm excited to let you know that we've just pushed an update to our repository, where we've implemented the feature you requested. You can now customize the color and size of the crosshair and marking box in our application. 🎨
> > Please give it a try and let us know if everything works as expected. Your feedback is invaluable to us, and we're always striving to improve your experience. 🚀
> > Thank you for your patience and for contributing to making our application better! If you have any further suggestions or issues, don't hesitate to reach out. 😊
> > 1._mp4_
> 
> "So fast! Thanks to the efforts of the developers. So where should I download this latest version? I opened it here but it seems I can't see it? EXE" https://github.com/CVHub520/X-AnyLabeling/releases

The new gui version is not release yet, you can git clone the source code first.

**Comment by lhj5426** [comment]
> > > Hey there! 🎉
> > > I'm excited to let you know that we've just pushed an update to our repository, where we've implemented the feature you requested. You can now customize the color and size of the crosshair and marking box in our application. 🎨
> > > Please give it a try and let us know if everything works as expected. Your feedback is invaluable to us, and we're always striving to improve your experience. 🚀
> > > Thank you for your patience and for contributing to making our application better! If you have any further suggestions or issues, don't hesitate to reach out. 😊
> > > 1.__mp4__
> > 
> > 
> > "So fast! Thanks to the efforts of the developers. So where should I_ download _this latest version? I opened it here but it seems I can't see it? EXE" [https://github.com/CVHub520/X-AnyLabeling/_releases_](https://github.com/CVHub520/X-AnyLabeling/releases)
> 
> The new gui version is not _release_ yet, you can git clone the _source_ code first.



> > > Hey there! 🎉
> > > I'm excited to let you know that we've just pushed an update to our repository, where we've implemented the feature you requested. You can now customize the color and size of the crosshair and marking box in our application. 🎨
> > > Please give it a try and let us know if everything works as expected. Your feedback is invaluable to us, and we're always striving to improve your experience. 🚀
> > > Thank you for your patience and for contributing to making our application better! If you have any further suggestions or issues, don't hesitate to reach out. 😊
> > > 1.__mp4__
> > 
> > 
> > "So fast! Thanks to the efforts of the developers. So where should I_ download _this latest version? I opened it here but it seems I can't see it? EXE" [https://github.com/CVHub520/X-AnyLabeling/_releases_](https://github.com/CVHub520/X-AnyLabeling/releases)
> 
> The new gui version is not _release_ yet, you can git clone the _source_ code first.

Actually, I don't understand the code. I've been relying on GPT to get by.
I guess I'll just wait for the GUI EXE version to be released. Haha.

**Comment by lhj5426** [comment]
https://github.com/CVHub520/X-AnyLabeling/releases
"The last time you uploaded the packaged version was last month. Could you please release a new packaged version with the accumulated updates this month?"

**Comment by lhj5426** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/827ac0c8-2545-4f38-879c-ea8b97abbb62)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/667570ca-cfe3-4cf9-94f9-03b1d90c0846)

I woke up this morning and learned how to install and run from the source code, which was very helpful. I'm wondering, can the size of this marked box also be adjusted? It's too thin and uncomfortable to look at, and it strains my eyes

**Comment by lhj5426** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/f1888350-dafe-4754-a8df-e65a3cebe4a0)

**Comment by CVHub520** [comment]
Not support yet. I'm planning to add direct configuration support for the marker box size in the future, which will allow users to adjust it without modifying the source code.

Thank you for your understanding.

**Comment by lhj5426** [comment]
Thank you for your efforts.
I look forward to future updates and optimizations.

**Comment by CVHub520** [comment]
Dear user,

🎉 Great news! The feature you requested has been implemented. You can now adjust the size of the marking box for a more comfortable viewing experience. 📏✨ This should help alleviate eye strain and make your work easier on the eyes.

Usage: open  and edit the configruation file which under your custom user directory (~/.xanylabelingrc):
```YAML
...
# canvas
shape:
  # drawing
  line_color: [0, 255, 0, 128]
  fill_color: [220, 220, 220, 150]
  vertex_fill_color: [0, 255, 0, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 155]
  hvertex_fill_color: [255, 255, 255, 255]
  point_size: 8
  line_width: 2  # modify the value here!
...
```

Thank you for your patience and for providing valuable feedback. Your input is greatly appreciated and helps make this project better for everyone. 🙌

If you encounter any issues or have further suggestions, please don't hesitate to reach out. Enjoy the updated features!

Good lucks!

**Comment by lhj5426** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/ee86f379-d08c-4394-96b4-92a4129d1c36)
Dear Developer,
Thank you for your work. It's really great now. Using the computer from a distance, my eyes are not as tired as before. I really want to express my appreciation for your help

**Comment by lhj5426** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/68773d40-aad5-4817-bbd0-4ff41be0b33a)
"I also want to ask, is the color code value in RGBA format? I see that RGB has only three sets of values, but RGBA has four."

**Comment by CVHub520** [comment]
> ![image](https://private-user-images.githubusercontent.com/30548000/342448742-68773d40-aad5-4817-bbd0-4ff41be0b33a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzkzNDcsIm5iZiI6MTcxOTI3OTA0NywicGF0aCI6Ii8zMDU0ODAwMC8zNDI0NDg3NDItNjg3NzNkNDAtYWFkNS00ODE3LWJiZDAtNGZmNDFiZTBiMzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxMzA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOGNlNmE0NTAyNDEwMjYyNmE5NmFkOTM3YjUxYzgwMTgwMjBjMzA1Y2U3OTM1NjQ1YjJmODRmNzBmZjc4OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f7bYFGqX12DfkapSiC-mPdGTCYRSQOOTdEA8mSxtixo) "I also want to ask, is the color code value in RGBA format? I see that RGB has only three sets of values, but RGBA has four."

Yes, you're right. The value like `[0, 255, 0, 128]` represents that the `RGBA` format, where A means that the opacity.

**Comment by lhj5426** [comment]
Thank you very much.
I understand now.
