### ISSUE TITLE
我现在想导入mask的png到标注软件，但是加载json的时候报错，是什么原因

### ISSUE THREAD

**Issue by KangLifei** [CVHub520/X-AnyLabeling#473]
![113c378bcb264ecbac6e865755d0c6f](https://github.com/CVHub520/X-AnyLabeling/assets/44434204/1c9f34f3-31c5-4d12-8816-ca3d5241afb4)
![2003f20bce1eaaa1ec7b5051392f276](https://github.com/CVHub520/X-AnyLabeling/assets/44434204/d215edc4-7c06-4223-b710-0c7d8ce00f36)
如图所示，加载json报错

**Comment by CVHub520** [comment]
Hi there! 😊 It seems like you're encountering an issue with the JSON format. The error message `json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes` suggests that the keys in your JSON object need to be enclosed in double quotes.

Here's the corrected JSON snippet for you:

```json
{
    "type": "grayscale",
    "colors": {
        "zp": 1,
        "background": 0
    }
}
```

Make sure every key is wrapped with double quotes, as shown above. This should resolve the decoding error when you attempt to load the JSON file into the annotation software.

If the problem persists after making this change, please let me know, and we'll dig deeper into the issue together. Good luck, and happy annotating! 🎨💻

**Comment by KangLifei** [comment]
thanks,I took the suggestion and successfully resolved it
