### ISSUE TITLE
x-anylabeling在打开bmp格式图片时会显示报错

### ISSUE THREAD

**Issue by aboluo294** [CVHub520/X-AnyLabeling#476]
你好，不知道为什么，x-anylabeling在打开bmp格式图片时会显示”请放入有效图片“的报错，只有将格式转换为png或jpg后才能顺利读取出来。
![捕获](https://github.com/CVHub520/X-AnyLabeling/assets/172259948/83e8ab36-f658-4b60-97d0-9d75a10d2e92)
![捕获](https://github.com/CVHub520/X-AnyLabeling/assets/172259948/83e8ab36-f658-4b60-97d0-9d75a10d2e92)
![捕获](https://github.com/CVHub520/X-AnyLabeling/assets/172259948/b0785818-d80d-42cd-8d1e-2f00dc2fcfdb)
![捕获](https://github.com/CVHub520/X-AnyLabeling/assets/172259948/b0785818-d80d-42cd-8d1e-2f00dc2fcfdb)

**Comment by chenller** [comment]
我遇到了相同的问题。应该添加对bmp图片的支持，这在代码层面应该不复杂。非常感谢。

**Comment by CVHub520** [comment]
Fixed. #474
