### ISSUE TITLE
Export mask error: "imageWidth"

### ISSUE THREAD

**Issue by RLWang1997** [CVHub520/X-AnyLabeling#477]
I used the release version v2.3.6 of X-AnyLabeling-CPU.exe for SAM-based labeling, but when I tried to export the mask, a pop-up window reported an error "imageWidth". My json is like:
```json
{
  "version": "2.3.6",
  "flags": {},
  "shapes": [
    {
      "label": "1",
      "points": [
        [
          1082.5,
          970.5000000000002
        ],
        [
          963.7500000000001,
          1333.0000000000002
        ],
        [
          1320.0,
          1501.7500000000002
        ],
        [
          1376.25,
          1214.2500000000002
        ],
        [
          1157.5,
          976.7500000000002
        ]
      ],
      "group_id": null,
      "description": "",
      "difficult": false,
      "shape_type": "polygon",
      "flags": {},
      "attributes": {}
    }
  ],
  "imagePath": "7d56f811-bff7-401a-ad7a-ea81f1a3ffaa.jpeg",
  "imageData": null,
  "imageHeight": 3816,
  "imageWidth": 2740
}
```
And the screenshot is:
![屏幕截图 2024-06-26 161456](https://github.com/CVHub520/X-AnyLabeling/assets/34210387/4f026e49-1698-4efa-b25e-475c7bbe7ce2)

Thanks for your nice work!

**Comment by CVHub520** [comment]
Hey there! 🌟 

I'm sorry to hear about the trouble you're having with exporting masks. The error message "imageWidth" seems to indicate a problem with the image dimensions specified in your JSON file, though the provided JSON appears to have all necessary fields correctly populated.

Given the situation, it would indeed be insightful to run the application from the source code to gather more detailed error logs. 

This way, we can pinpoint exactly where the issue arises.

**Comment by gjd2017** [comment]
同样问题，，，怎么解决？？

**Comment by CVHub520** [comment]
> 同样问题，，，怎么解决？？

Hey there! @gjd2017:

Please pull the latest source code and re-export it. If the issue persists, copy the detailed error message and snippet here.

**Comment by gjd2017** [comment]
> > 同样问题，，，怎么解决？？
> 
> Hey there! @gjd2017:
> 
> Please pull the latest source code and re-export it. If the issue persists, copy the detailed error message and snippet here.
刚刚重新安装最新的，然后环境也是重新装了，还是这个问题
![截图 2024-07-10 11-37-53](https://github.com/CVHub520/X-AnyLabeling/assets/28797958/35fc07cc-45cf-4b71-8907-dbeaa2585cff)

**Comment by CVHub520** [comment]
If you still encounter problems after completing the aforementioned verification steps, please zip your exporting configuration file, image files and corresponding annotated files, and send the compressed package to the specified email address: [cv_hub@163.com](mailto:cv_hub@163.com).

**Comment by CVHub520** [comment]
In addition, please check whether there is a pure numeric definition in the current task tag. If so, please add single quotes.

**Comment by gjd2017** [comment]
> If you still encounter problems after completing the aforementioned verification steps, please zip your exporting configuration file, image files and corresponding annotated files, and send the compressed package to the specified email address: [cv_hub@163.com](mailto:cv_hub@163.com).

我采用脚本形式进行转换了“polygon_mask_conversion.py”，使用脚本时没有问题的。
