### ISSUE TITLE
yolov8 psose 标注之后转成yolo pose 报错

### ISSUE THREAD

**Issue by KangLifei** [CVHub520/X-AnyLabeling#479]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/44434204/566aef3f-aede-4998-a060-61566b424f18)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/44434204/92c331ec-a1e3-480e-9617-c5156065bcef)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/44434204/3f8b4054-7038-453c-9f47-14581cb35bf8)
如题，麻烦给看下是什么问题

**Comment by CVHub520** [comment]
@KangLifei, Hi!

For this question, you can refer to #471.
