### ISSUE TITLE
使用自定义的yolov8n模型时候，只能使用640尺寸的模型，其他尺寸的模型没有结果，请问是什么问题？

### ISSUE THREAD

**Issue by xuwei1119** [CVHub520/X-AnyLabeling#48]

**Comment by CVHub520** [comment]
您好，感谢关注。默认是640尺寸，如果需要使用其它尺寸，请修改下相应[配置文件](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov8n.yaml)的参数。

**Comment by xuwei1119** [comment]
修改了没报错，但是没有AI结果

**Comment by CVHub520** [comment]
> 修改了没报错，但是没有AI结果

请参考下帮助文档，或者直接源码运行，贴下具体的报错信息。
