### ISSUE TITLE
changin label dialog window?

### ISSUE THREAD

**Issue by pirik3** [CVHub520/X-AnyLabeling#481]
How do i change below dialog window ...

![x-label_dialog_1](https://github.com/CVHub520/X-AnyLabeling/assets/49645171/5ed48c5f-9d09-473e-9fd0-9f8177a62bad)

to this one, like which file do i have to change "X-AnyLabeling\anylabeling\views\labeling\widgets\label_dialog.py", it looks like this file that i have to play with if thats correct but i need to add to many variables and probably change some other files as well but any leading welcome.

![x-label_dialog_2](https://github.com/CVHub520/X-AnyLabeling/assets/49645171/6a8454da-021b-4e5d-9a16-29fb5a19b558)

**Comment by CVHub520** [comment]
Hello there! 🎉

It seems you're looking to customize the label dialog window in X-AnyLabeling. Here, i can guide you on how to generally approach modifying UI elements within the application.

The label dialog window is indeed managed by the `label_dialog.py` file located under `X-AnyLabeling\anylabeling\views\labeling\widgets`. This is the primary file you'll need to adjust to change the appearance and behavior of the dialog. 🛠️

Here's how you can go about customizing it:

1. **Open the File**: Start by opening `label_dialog.py` in your preferred code editor.

2. **Understand the Structure**: Familiarize yourself with the structure of the dialog. Look for where the widgets are defined and how they interact with each other.

3. **Modify Widgets**: To add more variables or change existing ones, look for the widget definitions and modify them according to your needs. You might need to add new fields or adjust existing ones.

4. **Update Layouts**: If you need to change the layout or styling, look for layout managers (`QVBoxLayout`, `QHBoxLayout`, etc.) and modify them as necessary.

5. **Connect Signals and Slots**: If you're adding new functionality, you might need to connect signals and slots for new buttons or actions.

6. **Test Your Changes**: After making modifications, run the application to test your changes. Make sure everything works as expected and there are no unexpected side effects.

Remember, if you're adding complex functionality or changing significant parts of the UI, you might need to touch other files as well. Anytime you make changes to UI components, it's a good idea to thoroughly test your application to ensure that all features continue to work correctly.

If you encounter any specific issues or have further questions during the customization process, feel free to ask! Happy coding! 🚀✨
