### ISSUE TITLE
No module named 'imgviz' and COM error 0xffffffff80010106

### ISSUE THREAD

**Issue by pirik3** [CVHub520/X-AnyLabeling#482]
im getting 2 error message ;

1st one:

```
\X-AnyLabeling\.\anylabeling\views\labeling\label_widget.py", line 14, 
in <module>
    import imgviz
ModuleNotFoundError: No module named 'imgviz'
```

but imgviz installed already.

2nd:

```
\X-AnyLabeling/anylabeling/app.py
Skipping unexpected key in config: show_cross_line
QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)"
```

**Comment by CVHub520** [comment]
Hey there! 🎉

It looks like you're encountering a couple of issues while trying to run X-AnyLabeling. The first one is a missing module error for 'imgviz', even though you've mentioned it's already installed. The second issue seems to be related to a COM error during the initialization process. 🛠️

To tackle these problems, let's start fresh with a clean Conda environment. This will ensure that all dependencies are properly installed and configured without any conflicts from your existing Python environment. Here's how you can do it:

1. **Create a new Conda environment**:
   ```bash
   conda create -n x-anylabeling python=3.9 -y
   ```

2. **Activate the new environment**:
   ```bash
   conda activate x-anylabeling
   ```

Once you have the environment set up, proceed to install the dependencies for X-AnyLabeling. You can find detailed instructions in our [Getting Started Guide](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/get_started.md#running-from-source-code).

Make sure to install the correct dependency file based on whether you're planning to use the CPU or GPU version of the software. For example, if you're planning to use the GPU version, you'll need to make sure that your CUDA version is compatible with the `onnxruntime-gpu` version for smooth GPU-accelerated model inference. 🎯

After installing the dependencies, set up the environment variable and launch the tool by executing the following command in the X-AnyLabeling project directory:
```bash
python anylabeling/app.py
```

This should help resolve the issues you're facing. Let me know if you need any further assistance or if you encounter any other errors during the setup process! 🚀✨

Happy coding! 💻
