### ISSUE TITLE
Convert Polygon to HBB

### ISSUE THREAD

**Issue by lwfld** [CVHub520/X-AnyLabeling#483]
我在进行segmentation的mask标注的时候无意中看到新版更新了这个功能，因为也有标记bbox的需求，所以进行了点击，但是点击之后我所有标记的mask多边形全部变成了矩形框，并且这个操作是不可逆的，我直接查看json文件发现里面只保存了四个点。请问本来就是这么设计的吗？我按撤销都没有用，现在标记的多边形数据全都没有了...

**Comment by CVHub520** [comment]
Hey there! 
It sounds like you've stumbled upon an unexpected behavior while using the tool for segmentation tasks. When you accidentally clicked on the bounding box feature, it seems to have converted all your carefully drawn polygon masks into rectangles, and unfortunately, this change wasn't reversible through the undo function.
