### ISSUE TITLE
软件闪退

### ISSUE THREAD

**Issue by winner-4** [CVHub520/X-AnyLabeling#484]
作者您好，我在windows端用sam标注时总是闪退，很影响体验，请问有什么方法可以避免吗？

**Comment by wtwan** [comment]
您好，我也是，win GPU版本加载yolov8x、yolov8s会闪退

**Comment by CVHub520** [comment]
> 您好，我也是，win GPU版本加载yolov8x、yolov8s会闪退

Note: The GPU version mentioned above is compiled based on CUDA 11.6. Different versions may result in issues with xxx functionality. It is recommended to consider running the application using the source code, especially if compatibility issues arise.

**Comment by CVHub520** [comment]
Hey there! @winner-4 

I understand that you're experiencing crashes while using SAM annotation on Windows, which is definitely not the smooth experience we aim for. 

To help troubleshoot this issue, it would be beneficial if you could run the software from source code. This way, you can see detailed error messages that will give us clues as to what might be causing the crashes. 🕵️‍♂️

Here are the steps to run X-AnyLabeling from source: [get_started](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md#%E6%BA%90%E7%A0%81%E8%BF%90%E8%A1%8C)

While running the application, keep an eye on the console output for any error messages that appear when the crash occurs. These details will be crucial in identifying and fixing the problem. 🛠️

Once you have the error information, please share it here so we can work together to resolve the issue. Your cooperation will greatly assist in improving the software for everyone. 🤝

Looking forward to your response! 🌟
