### ISSUE TITLE
How to customize the color here?"

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#487]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/c7cfedc2-1e73-41c1-8711-935ebd18d9c8)
"Hello,
As shown in the picture, I've chosen a color that is very close to the target I want to select, which makes it not very obvious. I want to ask, can the color in these areas be customized?"

"The color of the tags is beyond my control. Coincidentally, it has become a color very similar to the color of the rectangle of the target I'm selecting. This really makes it difficult when marking targets. Could you please help me? Thank you."

https://github.com/CVHub520/X-AnyLabeling/assets/30548000/6ce8ba36-c53e-41ae-bca2-2165e44d1a6e

"Currently, I can control the color of the rectangle during the marking process. However, I cannot control the color of the rectangle after the mark has been made."

![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/f8dd00e3-71c9-4a8f-9fc9-3d3eec451345)
"If possible, could it be presented in the form of a UI like this?"
"Having various color choices directly operable within the UI is more intuitive. Otherwise, to change a color, I would need to open an additional color palette software to find the color, which is not very convenient. Could you consider this?"

**Comment by lhj5426** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/9f75ce9e-025b-4f49-a3af-989c4603b676)
"Also, as shown in the picture, could we add numbers here? It would be convenient for viewing and reading, and it would allow us to intuitively know how many marks there are on the current page."

**Comment by CVHub520** [comment]
Hello, @lhj5426:

Thank you for reaching out with your issue. I'm pleased to inform you that the ability to customize the color of annotation boxes has been added in the latest version of the source code. To access this feature, please update your source code by running the command `git pull origin main`. Once updated, you can configure the annotation box colors under the `Tools` -> `Modify Label` menu option.

https://github.com/CVHub520/X-AnyLabeling/assets/72010077/78085f05-4bf9-4365-9b7f-044a89bb0b3d

Moreover, to differentiate between various annotation boxes, you can set a `group_id` parameter, assigning distinct values such as 0, 1, 2, 3, and so on to each group. This will help in managing and distinguishing between multiple targets.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/a39ca09b-fa1a-4246-80a8-292ea3f80b9f)

Regarding the UI, while the current update does not provide a direct color choice within the UI as you suggested, your idea of incorporating a color selection feature directly into the UI is appreciated and could be considered for future enhancements to improve user convenience. For the time being, after updating the source code, you will be able to customize the colors more easily without the need for an additional color palette software.

If you encounter any issues or need further assistance with the update or customization, please feel free to ask. I'm here to help.

**Comment by lhj5426** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/b64d7d5e-f08f-45f5-b484-03ebb14a02f6)
"I love you, such a fast speed. Thank you for adding the tag color selection feature. This is absolutely fantastic."

"The group feature you mentioned, well, it can be used as a tag to group items. However, it doesn't display the total number on the current page, and I have to count each time after making a mark. To be honest, it's not very convenient, and tagging itself is a tedious task. Counting on top of that, I'm afraid I might bore myself to sleep. Nonetheless, I appreciate your guidance and I'll give it a try. Still, I hope that the sequence number could be directly displayed on the side. Thank you for your help."

**Comment by CVHub520** [comment]
Hi, there! @lhj5426

May be you can try press `Ctrl+G`.

**Comment by CVHub520** [comment]
The label statistics component is currently being improved and will be available soon. Stay tuned for updates and thank you for your patience.

**Comment by lhj5426** [comment]
"Thank you. I will keep looking forward to future updates!!!"

**Comment by CVHub520** [comment]
Hi, @lhj5426:

I'm glad to inform you that you can obtain the statistics report for a given range by specifying the number.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/9aa4edd4-b928-4451-9403-579d060a6cf0)

**Comment by lhj5426** [comment]
> Hi, @lhj5426* :
> 
> I'm glad to inform you that you can obtain the statistics report for a given range by specifying the number.
> 
> ![image](https://private-user-images.githubusercontent.com/72010077/345451889-9aa4edd4-b928-4451-9403-579d060a6cf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTc3ODMsIm5iZiI6MTcyMDAxNzQ4MywicGF0aCI6Ii83MjAxMDA3Ny8zNDU0NTE4ODktOWFhNGVkZDQtYjkyOC00NDUxLTk0MDMtNTc5ZDA2MGE2Y2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE0MzgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YzExM2UxNjZiYmJiYWRkZDZmYWE3N2NhZjVmM2IxZGYyNzJhYjU5NTRmZTA0MmJjMjA0ZjEyNTI2ZTBkMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7t3n62XjgIfMX0Q7C-InUP74Bq1LpaPTKHpKezUmI_c)

Thank you!
I'll go ahead and update it now.
Thank you very much.

**Comment by lhj5426** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/e260768f-3c70-4f5d-a1ab-517c2b3bf712)
On Windows 10, after viewing, the close button in the top right corner is unclickable. I can't close the window or perform any other operations. I have to kill the process and restart.

**Comment by lhj5426** [comment]
Is this a bug?

**Comment by CVHub520** [comment]
Wait, let me check.

**Comment by CVHub520** [comment]
The issue has been resolved. Please update to the latest version by performing a git pull.

**Comment by lhj5426** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/6a453a56-a3d2-4a96-9d76-dca5010b0e22)
Yes, this time I was able to close it normally. Thank you.

**Comment by CVHub520** [comment]
You’re welcome. If you encounter any issue, please feel free to ask!

**Comment by lhj5426** [comment]
> Hello, @lhj5426* :
> 
> Thank you for reaching out with your issue. I'm pleased to inform you that the ability to customize the color of annotation boxes has been added in the latest version of the _source_ code. To access this feature, please update your _source_ code by running the command `git pull origin main`. Once updated, you can configure the annotation box colors under the `Tools` -> `Modify Label` menu option.
> 
>  20-11-30._mp4_ 
> Moreover, to differentiate between various annotation boxes, you can set a `group_id` parameter, assigning distinct values such as 0, 1, 2, 3, and so on to each group. This will help in managing and distinguishing between multiple targets.
> 
> ![image](https://private-user-images.githubusercontent.com/72010077/344669650-a39ca09b-fa1a-4246-80a8-292ea3f80b9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNTkzMTgsIm5iZiI6MTcyMDI1OTAxOCwicGF0aCI6Ii83MjAxMDA3Ny8zNDQ2Njk2NTAtYTM5Y2EwOWItZmExYS00MjQ2LTgwYTgtMjkyZWEzZjgwYjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDA5NDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MDA4YmM2ZmI2MWIxZjM3OWRiYTNiN2IyOWI5OWY4MWY1YmFlOGQ4OThmYTVjOGNiYzA2NjdkN2VjMTFjYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mmZvnbDoJVcqp1b5rnQ186bX_N450CjgL8NOVXfk5Ts)
> 
> If you encounter any issues or need further assistance with the update or customization, please feel free to ask. I'm here to help.

I also want to ask if the colors can be fixed here. I mean, after restarting the software, it should maintain the original colors. Currently, every time I restart or the software crashes, the colors revert to the default settings when I open it again. Can I permanently customize and fix this in the code?

**Comment by CVHub520** [comment]
@lhj5426, Just refer [this](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AE%BE%E7%BD%AE).

**Comment by lhj5426** [comment]
Thank you for the help. I have customized it successfully.

**Comment by CVHub520** [comment]
@lhj5426 you're welcome! 😊 I'm thrilled that the information was beneficial to you. If you run into any snags or have further questions, please don't hesitate to get in touch.

Furthermore, if you stumble upon any specific challenges or bugs, crafting a minimal reproducible example can significantly expedite our ability to pinpoint and rectify the issue.

As a final note, ensure that you are using the most current version of the X-AnyLabeling repo to leverage the latest enhancements and bug fixes. This often helps in resolving unexpected hiccups.

Wishing you a joyful annotating adventure and the best of luck with your project! 🌟🚀

**Comment by yyy1998-i** [comment]
> 您好：
> 
> 感谢您提出您的问题。我很高兴地通知您，最新版本的源代码中添加了自定义注释框颜色的功能。要访问此功能，请通过运行命令 来更新您的源代码。更新后，您可以在 -> 菜单选项下配置注释框颜色。`git pull origin main``Tools``Modify Label`
> 
>  20-11-30.mp4 
> 此外，要区分各种注释框，您可以设置一个参数，为每个组分配不同的值，例如 0、1、2、3 等。这将有助于管理和区分多个目标。`group_id`
> 
> ![图像](https://private-user-images.githubusercontent.com/72010077/344669650-a39ca09b-fa1a-4246-80a8-292ea3f80b9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjY1MzgsIm5iZiI6MTcyOTY2NjIzOCwicGF0aCI6Ii83MjAxMDA3Ny8zNDQ2Njk2NTAtYTM5Y2EwOWItZmExYS00MjQ2LTgwYTgtMjkyZWEzZjgwYjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2NTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOWQwNTExOTM3NWFhN2IwYTI2NTQzNDJhZWY3MjQzYjRlYzljNGE4OTZiNTNhNTNkNDRhYThlZDkyNWMxZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0YF8LvSVpZ0bVovv-Udumr6DrUhSpaUde4oeEYMiuws)
> 
> 如果您遇到任何问题或需要有关更新或自定义的进一步帮助，请随时提问。我是来帮忙的。



> Hello, @lhj5426:
> 
> Thank you for reaching out with your issue. I'm pleased to inform you that the ability to customize the color of annotation boxes has been added in the latest version of the source code. To access this feature, please update your source code by running the command `git pull origin main`. Once updated, you can configure the annotation box colors under the `Tools` -> `Modify Label` menu option.
> 
>  20-11-30.mp4 
> Moreover, to differentiate between various annotation boxes, you can set a `group_id` parameter, assigning distinct values such as 0, 1, 2, 3, and so on to each group. This will help in managing and distinguishing between multiple targets.
> 
> ![image](https://private-user-images.githubusercontent.com/72010077/344669650-a39ca09b-fa1a-4246-80a8-292ea3f80b9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjcwNjAsIm5iZiI6MTcyOTY2Njc2MCwicGF0aCI6Ii83MjAxMDA3Ny8zNDQ2Njk2NTAtYTM5Y2EwOWItZmExYS00MjQ2LTgwYTgtMjkyZWEzZjgwYjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2NTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MmJjYjNkYzdiNjcxZjg4ODcyNGIzZjRlZDAyMmIzNmVkN2E2MGNhMmRiYTM3MTM2YTg4Yzg5YTU4ZDUyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5f0-iM32a8_gR2PIFbH1x2sCXlAb72dHoVjHqGKkwxQ)
> 
> If you encounter any issues or need further assistance with the update or customization, please feel free to ask. I'm here to help.

Hello author, I did not find Tools -> Modify Label menu option in the latest version (2.4.4). Is there any other way to modify the color? Looking forward to your reply

**Comment by CVHub520** [comment]
![image](https://github.com/user-attachments/assets/349f442a-5846-4141-8773-c7df0af94e25)

**Comment by yyy1998-i** [comment]
> ![image](https://private-user-images.githubusercontent.com/72010077/379145022-349f442a-5846-4141-8773-c7df0af94e25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjgyNjgsIm5iZiI6MTcyOTY2Nzk2OCwicGF0aCI6Ii83MjAxMDA3Ny8zNzkxNDUwMjItMzQ5ZjQ0MmEtNTg0Ni00MTQxLTg3NzMtYzdkZjBhZjk0ZTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA3MTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3OGJkNDdkNWYwZjYzZmU0MzhkMDU3ZTMzMTBiZjVjMzA3ZDM1NTdmNzJkNzViMzk5NzE0Y2I3YmZjNmExNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6psa4nQxM9m9a63r3W9FMlhI_gebWVxp0xqwCYUVYXI)

Thank you very much！

**Comment by CVHub520** [comment]
You are welcome! If you find this project helpful, please give it a ⭐star. :)
