### ISSUE TITLE
How can I use GPU mode with source code?

### ISSUE THREAD

**Issue by dahaigui** [CVHub520/X-AnyLabeling#488]
I want to use the source code to call the GPU to run, what exactly should I do?

**Comment by CVHub520** [comment]
Hi, @dahaigui, you can refer to this [docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md#%E8%BF%90%E8%A1%8C%E6%A8%A1%E5%BC%8F).

**Comment by dahaigui** [comment]
改好了之后在我导入模型的时候报错“ImportError: DLL load failed while importing onnxruntime_pybind11_state: 动态链接库(DLL)初始化例程失败。”，这个是什么原因导致的？
![image](https://github.com/CVHub520/X-AnyLabeling/assets/47802187/1e37259b-63f1-4b34-9776-8125f47219a7)

**Comment by CVHub520** [comment]
如果您希望利用 GPU 进行模型推理加速，请务必确保本地 CUDA 版本与 onnxruntime-gpu 版本兼容，以确保顺利调用显卡。有关详细信息，请参考[官方文档](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html)。
