### ISSUE TITLE
车道线自动标注

### ISSUE THREAD

**Issue by Nian-Gao520** [CVHub520/X-AnyLabeling#489]
作者你好，我使用X-AnyLabeling自动标注车道线所生成的标签线形为“Line”，请问可以实现类型为“LineStrip”的标注吗？

**Comment by CVHub520** [comment]
Yes! You can try to make modifications [here](https://github.com/CVHub520/X-AnyLabeling/blob/d0706d632864bd3fadbda0cf5742529d8dfc741f/anylabeling/services/auto_labeling/clrnet.py#L193). Just adjust the `shape_type` value accordingly, e.g., replace `line` with `linestrip` .
