### ISSUE TITLE
Linux版如何打开GUI

### ISSUE THREAD

**Issue by DennisJcy** [CVHub520/X-AnyLabeling#49]
您好!
请问下Ubuntu下用什么打开它,我试了很多打开方式都打不开GUI

**Comment by CVHub520** [comment]
您好，linux 直接再终端运行即可，./xxx

**Comment by DennisJcy** [comment]
感谢您的回复
我就是在ubuntu下直接./ 运行,然后左上角会显示加载这个应用程序,然后就没了.
我感觉是闪退了

**Comment by CVHub520** [comment]
闪退的话应该是会有报错原因的，不过既然你都用ubuntu了，直接pip install下源码运行？

**Comment by DennisJcy** [comment]
好的,感谢回复~
