### ISSUE TITLE
Error in predict_shapes: list index out of range

### ISSUE THREAD

**Issue by HolaAn** [CVHub520/X-AnyLabeling#490]
当我导入自定义yolov8分割模型并点击运行时终端显示：Error in predict_shapes: list index out of range，而且图片没有标注上任何标签。
请问能看看是什么原因嘛？谢谢！

**Comment by CVHub520** [comment]
Ref #402

**Comment by HolaAn** [comment]
找到问题了，导入分割模型时，yaml文件里的type应该设为 yolovx_seg（type: yolov8_seg）
