### ISSUE TITLE
Ubuntu 20.04环境下，在使用自己训练的yolov5s模型进行自动标注时会终止程序，并在命令行中出现以下错误：

### ISSUE THREAD

**Issue by casualdays** [CVHub520/X-AnyLabeling#491]
`Traceback (most recent call last):
  File "/home//xiaohf/medicine/X-AnyLabeling/anylabeling/views/labeling/widgets/canvas.py", line 1077, in paintEvent
    shape.paint(p)`
` File "/home/xiaohf/medicine/X-AnyLabeling/anylabeling/views/labeling/shape.py", line 195, in paint
    assert len(self.points) in [1, 2, 4]
AssertionError`

**Comment by casualdays** [comment]
已解决，ONNX模型的问题，跟着官网重新export一个新的ONNX就能使用了。

**Comment by casualdays** [comment]
已解决，使用官方export .py转换一个新的ONNX模型即可使用。

参考命令：
`python3 export.py --weights ./yolov5s.pt --img 640 --batch 1 --include=onnx`

**Comment by CVHub520** [comment]
Great! I'm glad to hear you resolved the issue by converting the model to ONNX format using the official `export.py` script. 
Your solution will be helpful for others who may encounter a similar problem. If you have any more questions or need further assistance, feel free to ask. Happy annotating!

**Comment by ricoflower** [comment]
> `Traceback (most recent call last): File "/home//xiaohf/medicine/X-AnyLabeling/anylabeling/views/labeling/widgets/canvas.py", line 1077, in paintEvent shape.paint(p)` ` File "/home/xiaohf/medicine/X-AnyLabeling/anylabeling/views/labeling/shape.py", line 195, in paint assert len(self.points) in [1, 2, 4] AssertionError`

I also encountered the above problem, and I used export.py to convert pt to onnx, but it still didn't work

**Comment by ricoflower** [comment]
Specific steps for reproducing the problem
1 A self-trained yolov5s model best-pt
2 Convert to best.onnx using export.py in yolov5 version5.0
3 Copy the official yolov5s.yaml and modify it as shown below
4 Place best.onnx and yolo5s.yaml in the newly created auto_ele folder under auto_labeling
5. Load a custom model in x-anylabeling
[
![yolov5s.yaml](https://github.com/user-attachments/assets/1c100f4a-e6dd-41aa-8e19-b19dcbd5c414)

![input](https://github.com/user-attachments/assets/efa03af5-8334-4eee-968a-62c1deb042ef)
![output](https://github.com/user-attachments/assets/044c651e-9914-4328-8212-281bf25db1ab)

**Comment by CVHub520** [comment]
@casualdays, Plz follow this [instruction](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md#%E5%8A%A0%E8%BD%BD%E5%B7%B2%E9%80%82%E9%85%8D%E7%9A%84%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B) to deploy your custom model on X-AnyLabeling.

![image](https://github.com/user-attachments/assets/22b5bc4b-4cfd-4f0e-a4c3-be7a03019783)

**Comment by ricoflower** [comment]
Thanks for your answer, I modified yaml as follows and did not quit this program again
But a new error has appeared
“error in predict_shapes: operands could not be broadcast together with shapes (1,2,80,80,11) (19200,2)”
![1](https://github.com/user-attachments/assets/d89f891f-acbd-47d3-8347-b138a073eb03)

**Comment by CVHub520** [comment]
Thank you for providing an update on the issue. The error message you’re encountering suggests that there is a shape mismatch between the outputs of your model and the expected shapes for the post-processing steps.

Since you’ve modified the model architecture, it’s important to adjust the post-processing code accordingly. Once you’ve made the necessary adjustments, test the modified code to see if the error is resolved.

> https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/__base__/yolo.py

**Comment by NOTGOOOOD** [comment]
> 已解决，使用官方export .py转换一个新的ONNX模型即可使用。
> 
> 参考命令： `python3 export.py --weights ./yolov5s.pt --img 640 --batch 1 --include=onnx`

@CVHub520  By the way, where is the `export.py` ? I am confused that whether I should use the Ultralytics to export ONNX ?

**Comment by CVHub520** [comment]
> > 已解决，使用官方export .py转换一个新的ONNX模型即可使用。
> > 参考命令： `python3 export.py --weights ./yolov5s.pt --img 640 --batch 1 --include=onnx`
> 
> [@CVHub520](https://github.com/CVHub520) By the way, where is the `export.py` ?

https://github.com/ultralytics/yolov5/blob/master/export.py

**Comment by NOTGOOOOD** [comment]
> > > 已解决，使用官方export .py转换一个新的ONNX模型即可使用。
> > > 参考命令： `python3 export.py --weights ./yolov5s.pt --img 640 --batch 1 --include=onnx`
> > 
> > 
> > [@CVHub520](https://github.com/CVHub520) By the way, where is the `export.py` ?
> 
> https://github.com/ultralytics/yolov5/blob/master/export.py

OK, It's clear
