### ISSUE TITLE
operands could not be broadcast together with shapes (0,) (1,2)

### ISSUE THREAD

**Issue by HolaAn** [CVHub520/X-AnyLabeling#492]
![微信图片_20240702163734](https://github.com/CVHub520/X-AnyLabeling/assets/117055637/499f7de6-3ae4-4d74-8646-9120bd9ea111)
自动标注完标签后，将数据导出为YOLO标签时经常显示这个错误，请问是什么原因呢？求助

**Comment by CVHub520** [comment]
Please refer to issue #257 and update your source code, as this issue may have been addressed.
