### ISSUE TITLE
请问在使用自动标注时，如果出现较多没有标注信息的图片，有什么方法可以筛除吗？

### ISSUE THREAD

**Issue by GZhengyang** [CVHub520/X-AnyLabeling#493]

**Comment by CVHub520** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/1993d64d-ef45-4f17-bd39-1064e0c16251)

**Comment by GZhengyang** [comment]
是只能一张一张的删吗？或者有批量删除的方法吗？

**Comment by CVHub520** [comment]
Indeed, at present, it only supports deleting images one at a time.
