### ISSUE TITLE
处理视频文件，导出yolo水平格式后，cannot access local variable ‘converter’ where it is not associated with a value

### ISSUE THREAD

**Issue by GZhengyang** [CVHub520/X-AnyLabeling#494]
处理过一个视频文件后，导出yolo水平格式的标注文件，然后再打开第二个视频文件标注，点击导出yolo水平格式出现以下问题（提示选择class.txt之前）
![7b56232cb738cc8a031e1bb6bd0816d](https://github.com/CVHub520/X-AnyLabeling/assets/126135478/012b065a-fa3c-4615-98b4-ddbf6488891f)

是不能同时连续导出yolo水平格式的标签吗？我关闭之后再导出yolo水平格式的标签没有提示这个问题，但是每次处理第二个文件就会出现这个问题

**Comment by CVHub520** [comment]
Hey there! @GZhengyang:

Thank you for reporting this issue.  I have identified a bug in one of the intermediate branch that might be causing the problem you're experiencing. 

I recommend updating to the latest version of our code, as this version includes a fix for the issue you've described. I have tested the latest version and it does not exhibit the problems you've encountered. Please let me know if you continue to face issues after updating.

Best regards,
CVHub

**Comment by CVHub520** [comment]
Btw, if your annotation video contains a significant amount of background images, it's recommend adjusting the frame sampling frequency during the import process. This can help to reduce the number of frames that are processed, which can improve the efficiency of the annotation process. #493

**Comment by CVHub520** [comment]
https://github.com/CVHub520/X-AnyLabeling/assets/72010077/b00be825-289f-4f0b-8211-f7b7b028de42

**Comment by GZhengyang** [comment]
非常感谢您的工作！
