### ISSUE TITLE
新版的X-AnyLabeling-main  关于GPU推理遇到的个人解决方法

### ISSUE THREAD

**Issue by x7902178** [CVHub520/X-AnyLabeling#496]
![6e0287225a2508fcc6bf837ba3897e2](https://github.com/CVHub520/X-AnyLabeling/assets/142156360/a3ee9178-3e8f-4892-ab54-e0ae8c0959f7)
![1720026240727](https://github.com/CVHub520/X-AnyLabeling/assets/142156360/cde5b9f7-4f8e-414a-8fe4-08d24c91cbc3)
![1720026424791](https://github.com/CVHub520/X-AnyLabeling/assets/142156360/34436e79-8fe7-439d-abf4-f706ba988313)

第一个关于CV提示的报错，通过在配置文件里面指定模型输入大小解决，
第二个关于onnxruntime -GPU (ORT1.18.1版本)，自动安装后加载模型提示DLL初始化失败，平台win11 python3.11  3.12   CUDA12.X 
![9625c0822adf96b66e660dc2fe14a03](https://github.com/CVHub520/X-AnyLabeling/assets/142156360/5fab9767-f9be-4753-b2c7-89401d61d8e7)
 按照官方文档手动下载本地安装包进行安装后解决问题（ORT1.18.1默认适配CUDA118），#通过pip install onnxruntime-gpu==1.18.1# 这个命令安装的和requirements-gpu.txt自动安装的都没有成功加载，我是安装本地包解决的问题，其他的可能需要另行测试。
ORT官方文档说明链接包括CUDA和CUDNN的版本适配都有说明    # https://onnxruntime.ai/docs/install/

**Comment by CVHub520** [comment]
Thank you for sharing your solutions with the community. Your insights are greatly appreciated, and they will undoubtedly help others facing similar issues. 😄
