### ISSUE TITLE
Problems encountered by personal GPU models

### ISSUE THREAD

**Issue by zoushucai** [CVHub520/X-AnyLabeling#497]
Click to run the model, and the prediction result will not appear. Instead, the following information will be printed on the terminal

```
Error in predict_shapes: cannot access local variable 'keypoints' where it is not associated with a value 

```

<img width="554" alt="image" src="https://github.com/CVHub520/X-AnyLabeling/assets/15843338/630ce03d-67e9-4603-9126-d3860014d4a4">

**Comment by CVHub520** [comment]
Hi, @zoushucai, just update your source code, and this issue will disappear.

**Comment by CVHub520** [comment]
#465

**Comment by zoushucai** [comment]
I see. Thank you
