### ISSUE TITLE
可以自定义为关键点标注多加一个属性嘛？

### ISSUE THREAD

**Issue by automate11** [CVHub520/X-AnyLabeling#498]
作者您好！我想要在x-anylabeling进行人体关键点标注的话，对于每个关键点需要标注三个值，关键点的坐标x，y和关键点的可见性。即（x，y，visible），但是现在看着软件好像只能进行关键点标注，可以记录每个关键点的x和y坐标值，请问有什么方法可以为每一个关键点自定义多加一个visible属性嘛？期待作者的回复

**Comment by CVHub520** [comment]
Hi, there! 👋 

You can follow this [instruction](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#yolov8%E5%A7%BF%E6%80%81%E4%BC%B0%E8%AE%A1%E4%BB%BB%E5%8A%A1%E4%B9%8B%E5%85%B3%E9%94%AE%E7%82%B9%E6%A0%87%E6%B3%A8).
