### ISSUE TITLE
json转换coco格式的一些问题

### ISSUE THREAD

**Issue by A-chen23** [CVHub520/X-AnyLabeling#5]
感谢您提供的工具，这个工程十分有趣。但是我在运行过程中发现了一下问题，按照教程我进行json转coco格式时，报出如下信息
“Traceback (most recent call last):
  File "label_converter.py", line 247, in <module>
    main()
  File "label_converter.py", line 230, in main
    converter.to_coco(input_dir, output_dir)
  File "label_converter.py", line 71, in to_coco
    x_min = min(points[0][0], points[1][0])
IndexError: list index out of range”

根据提示，我在代码的第71行找到了如下代码：
“x_min = min(points[0][0], points[1][0])
            y_min = min(points[0][1], points[1][1])
            x_max = max(points[0][0], points[1][0])
            y_max = max(points[0][1], points[1][1])

            width = x_max - x_min
            height = y_max - y_min”
这部分似乎是在表示一个框，但是我进行的时关键点的标注，坐标值应该只有两个，这个问题应该如何解决？或者说，关键点标注必须标注一个框将其包括起来吗？期待您的回复。

**Comment by CVHub520** [comment]
您好，感谢你的关注。关键点转换可以先参考下这个脚本：
https://github.com/m5823779/labelme2coco-keypoints/blob/master/labelme2coco.py

**Comment by A-chen23** [comment]
感谢您的回复，这个问题已经解决，我对原来的代码进行了修改。期待软件可以早日集成该功能，感谢您的分享。

**Comment by ChaoliesTinnu** [comment]
我也遇到了这个问题，后来发现是因为我之前装过 AnyLabeling ，然后 X-AnyLabeling 的启动脚本会被 AnyLabeling 覆盖，你用 X-AnyLabeling 启动脚本启动的还是 AnyLabeling ，因为之前没用过X-AnyLabeling ，没有发现启动的不是X-AnyLabeling ，然后标注出来的就是旧版本的结果……
