### ISSUE TITLE
如果保持标注模式

### ISSUE THREAD

**Issue by johnnyallt** [CVHub520/X-AnyLabeling#501]
比如用矩形框标注，每次标注完一个框就会变成编辑模式，如何选定标注模式

**Comment by CVHub520** [comment]
To switch back to the creation mode after drawing a rectangle, you can simply press the 'R' key on your keyboard. This will allow you to start drawing a new rectangle without entering the editing mode for the previously created shape.

**Comment by johnnyallt** [comment]
How to keep  'R' mode until annotation ends, for example, I only press once the 'R' key  on keyboard, I can draw many rectangles.

**Comment by CVHub520** [comment]
Hey there! @johnnyallt 😄 

I sincerely apologize for the delay in addressing your request. I appreciate your patience and understanding.

I'm pleased to inform you that i have now implemented the continuous annotation mode you suggested. With this update, pressing the 'R' key once will allow you to draw multiple rectangles without needing to re-activate the mode for each new shape.

To get the latest source code with this feature, please perform a `git pull` in your local repository, or if you prefer to start fresh, you can use `git clone` to obtain a clean copy of the updated codebase.

Thank you for your valuable feedback. It helps us improve our software to better meet your needs.

Happy labeling! 🚀

**Comment by CVHub520** [comment]
#330

**Comment by johnnyallt** [comment]
Thank you very much, I wish your team continued success and prosperity.

Best regards,
Johnny Z
