### ISSUE TITLE
For obb detection, the corner of the box is not on the image

### ISSUE THREAD

**Issue by DWendou** [CVHub520/X-AnyLabeling#502]
For the box at the edge of the image, some box corners may not be on the image, how to deal with this? thank you

**Comment by CVHub520** [comment]
> For the box at the edge of the image, some box corners may not be on the image, how to deal with this? thank you

When exporting the image with bounding boxes, any box that is partially or completely outside the image boundaries will be automatically ignored. This ensures that only relevant annotations within the visible image area are considered. If the full object is not within the image frame, it will not be included in the exported data.

Additionally, if you require a more refined approach, you have the option to apply a mask to the image. This mask can be used to specifically define the areas of interest, allowing you to include or exclude certain parts of the bounding boxes that extend beyond the image edges. Currently, you should implement it by manully.

Currently, this feature is not automated, and you would need to implement it manually. This means you would have to create and apply the mask yourself according to your specific requirements.

**Comment by DWendou** [comment]
![ww](https://github.com/CVHub520/X-AnyLabeling/assets/49715088/49abb837-f573-40c3-9719-c6c49c43d33a)
Are you saying you don't want any goals like that? Or I can make a mask manually

**Comment by CVHub520** [comment]
Hi, @DWendou:

Thank you for raising the issue regarding handling boxes at the edge of the image.  I’ve addressed this and now support annotating rotated boxes that may extend beyond the image boundaries.

Please update to the latest source code and give it a try. If you encounter any further issues or need additional adjustments, feel free to let us know.

#545
