### ISSUE TITLE
Can this tag selection box be fixed in the same position?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#503]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/fb6d7299-c9ec-4780-b23c-eb312408a921)
Can this tag selection box be fixed in the same position?

This box flies to various positions on the full screen every time. Sometimes it flies to an awkward position as shown in the picture. My computer has dual screens (top and bottom), and it flies to a very awkward position.

Therefore, if this box can always be displayed or fixed in the same position every time, we can operate like this: because the position is fixed, we can use a mouse macro to record the fixed position of each tag. This way, every time we need to select a tag, we just need to press a button, and the mouse will automatically click the fixed position of the fixed tag. This can greatly reduce the number of times we have to move the mouse with our wrist, thereby indirectly reducing the bulk feeling brought by the operation.

I hope the developers can consider the possibility and convenience of this operation.

**Comment by lhj5426** [comment]
Nowadays, any brand of mouse or keyboard comes with macro functionalities. Additionally, tools like AHK (AutoHotkey) can be used to enhance user efficiency and reduce operational strain. I sincerely hope that developers can consider this idea.

By adding a setting option to allow the tag selection box to always be displayed or to remember its last displayed position, users could use mouse macros to quickly and easily add or modify tags with a single click. This would greatly improve the efficiency of operations.
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/9162d060-1472-4a6c-a178-e16142a4bc63)

**Comment by lhj5426** [comment]
Of course, if we could set up shortcuts for tagging, that would also be a good solution.
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/8e613827-0afa-4dda-979f-8037f45b4f9c)
To simplify the tedious workflow as much as possible with the press of a single button, I have been using this mouse with 12 side buttons for nearly 10 years. If there are shortcuts available, I can bind them to the side buttons of the mouse to tag with just one click.

**Comment by lhj5426** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/7c05e10d-5fb5-4eb8-ad64-12a67f53cbce)
And the only thing I can do with this software right now is use one of the buttons to perform a double-click with the left mouse button, simplifying the process that originally required two left-clicks to select a tag. This is very inefficient.

**Comment by lhj5426** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/d0de64d7-060b-4692-a61a-e2dca59293a5)
In our software, F1-F12 are currently unassigned according to the help documentation. Binding the first 12 tags to these 12 buttons would also be a good solution.
With the left hand resting on the WASD keys, it can easily reach the first few commonly used tags.

**Comment by CVHub520** [comment]
Thank you for your helpful suggestions! I appreciate your input and will give them serious consideration.

**Comment by CVHub520** [comment]
Hey! @lhj5426:

Understanding that each user may have a different interaction style, the current default behavior for the label editing box is to prioritize the position where the mouse is clicked as the starting coordinate. 

However, if you prefer to fix the position of the label editing box at a certain point on the screen, such as the center, you can modify the source code accordingly.

Here's an example of how you can do this. Locate the function definition for `pop_up` [here](https://github.com/CVHub520/X-AnyLabeling/blob/8244cce94f0f515b32cb6996b6f76392fe1c5d08/anylabeling/views/labeling/widgets/label_dialog.py#L556) and make the following changes:

```python
def pop_up(
    self,
    text=None,
    move=True,
    flags=None,
    group_id=None,
    description=None,
    difficult=False,
):
    # ...
    if move:
        # Calculate the center position to move the dialog to
        screen = QtWidgets.QApplication.desktop().screenNumber(QtWidgets.QApplication.desktop().cursor().pos())
        centerPoint = QtWidgets.QApplication.desktop().screenGeometry(screen).center()
        qr = self.frameGeometry()
        qr.moveCenter(centerPoint)
        self.move(qr.topLeft())
    if self.exec_():
        # ...
```

By following these instructions, you can adjust the position of the label editing box to better suit your workflow. This customization can improve comfort and efficiency during the labeling process.

**Comment by lhj5426** [comment]
> Hey! @lhj5426* :
> 
> Understanding that each user may have a different interaction style, the current default behavior for the label editing box is to prioritize the position where the mouse is clicked as the starting coordinate.
> 
> However, if you prefer to fix the position of the label editing box at a certain point on the screen, such as the center, you can modify the _source_ code accordingly.
> 
> Here's an example of how you can do this. Locate the function definition for `pop_up` [here](https://github.com/CVHub520/X-AnyLabeling/blob/8244cce94f0f515b32cb6996b6f76392fe1c5d08/anylabeling/views/labeling/widgets/label_dialog.py#L556) and make the following changes:
> 
> ```python
> def pop_up(
>     self,
>     text=None,
>     move=True,
>     flags=None,
>     group_id=None,
>     description=None,
>     difficult=False,
> ):
>     # ...
>     if move:
>         # Calculate the center position to move the dialog to
>         screen = QtWidgets.QApplication.desktop().screenNumber(QtWidgets.QApplication.desktop().cursor().pos())
>         centerPoint = QtWidgets.QApplication.desktop().screenGeometry(screen).center()
>         qr = self.frameGeometry()
>         qr.moveCenter(centerPoint)
>         self.move(qr.topLeft())
>     if self.exec_():
>         # ...
> ```
> 
> By following these instructions, you can adjust the position of the label editing box to better suit your workflow. This customization can improve comfort and efficiency during the labeling process.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/36c681ca-b43c-4849-9e72-4f4c35221024)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/dde41d50-7bcc-49cb-92c5-e2af12aca2f1)
Is it like this?"

**Comment by lhj5426** [comment]
ziiyue@DESKTOP-RF09FLV C:\Users\ziiyue
# conda activate yolo

ziiyue@DESKTOP-RF09FLV C:\Users\ziiyue
(yolo) # cd D:\000A\X-AnyLabeling-main

ziiyue@DESKTOP-RF09FLV C:\Users\ziiyue
(yolo) # d:

ziiyue@DESKTOP-RF09FLV D:\000A\X-AnyLabeling-main
(yolo) # python anylabeling/app.py
Traceback (most recent call last):
  File "anylabeling/app.py", line 24, in <module>
    from anylabeling.views.mainwindow import MainWindow
  File ".\anylabeling\views\mainwindow.py", line 6, in <module>
    from .labeling.label_wrapper import LabelingWrapper
  File ".\anylabeling\views\labeling\label_wrapper.py", line 5, in <module>
    from .label_widget import LabelingWidget
  File ".\anylabeling\views\labeling\label_widget.py", line 47, in <module>
    from .widgets import (
  File ".\anylabeling\views\labeling\widgets\__init__.py", line 10, in <module>
    from .label_dialog import (
  File ".\anylabeling\views\labeling\widgets\label_dialog.py", line 604
    screen = QtWidgets.QApplication.desktop().screenNumber(QtWidgets.QApplication.desktop().cursor().pos())
    ^
IndentationError: expected an indented block

ziiyue@DESKTOP-RF09FLV D:\000A\X-AnyLabeling-main
(yolo) #

"After modifying it according to what you said, it ran with errors."

**Comment by CVHub520** [comment]
Just replace this:

```
...

class LabelDialog(QtWidgets.QDialog):
    def __init__(
        self,
        text=None,
        parent=None,
        labels=None,
        sort_labels=True,
        show_text_field=True,
        completion="startswith",
        fit_to_content=None,
        flags=None,
        difficult=False,
    ):
    ...
        if move:
            self.move(QtGui.QCursor.pos())
    ...

```

with below code accorspondingly:

```
class LabelDialog(QtWidgets.QDialog):
    def __init__(
        self,
        text=None,
        parent=None,
        labels=None,
        sort_labels=True,
        show_text_field=True,
        completion="startswith",
        fit_to_content=None,
        flags=None,
        difficult=False,
    ):
    ...
    if move:
        # Calculate the center position to move the dialog to
        screen = QtWidgets.QApplication.desktop().screenNumber(QtWidgets.QApplication.desktop().cursor().pos())
        centerPoint = QtWidgets.QApplication.desktop().screenGeometry(screen).center()
        qr = self.frameGeometry()
        qr.moveCenter(centerPoint)
        self.move(qr.topLeft())
    ...

```

**Comment by CVHub520** [comment]
To apply the changes, simply replace the code in the [label_dialog.py file](https://github.com/CVHub520/X-AnyLabeling/blob/8244cce94f0f515b32cb6996b6f76392fe1c5d08/anylabeling/views/labeling/widgets/label_dialog.py#L556) with the provided code snippet.

**Comment by lhj5426** [comment]
(yolo) # python anylabeling/app.py
Traceback (most recent call last):
  File "anylabeling/app.py", line 24, in <module>
    from anylabeling.views.mainwindow import MainWindow
  File ".\anylabeling\views\mainwindow.py", line 6, in <module>
    from .labeling.label_wrapper import LabelingWrapper
  File ".\anylabeling\views\labeling\label_wrapper.py", line 5, in <module>
    from .label_widget import LabelingWidget
  File ".\anylabeling\views\labeling\label_widget.py", line 47, in <module>
    from .widgets import (
  File ".\anylabeling\views\labeling\widgets\__init__.py", line 10, in <module>
    from .label_dialog import (
  File ".\anylabeling\views\labeling\widgets\label_dialog.py", line 12
    TODO(unknown):
                 ^
SyntaxError: invalid syntax


"Yes, thank you for providing a very user-friendly modification for someone like me who is not very smart. However, I copied and pasted the entire code you sent, replaced it, saved it, and ran it again, but it still gave an error."

**Comment by lhj5426** [comment]
"Haha, how about using an even simpler method? Could you zip the modified file that runs correctly on your computer and upload it here? I know this might make me seem very foolish, but it doesn't matter at all. Haha, thank you for your help."

**Comment by lhj5426** [comment]
"Oh, I got it running. Now the window appears in the center."

**Comment by CVHub520** [comment]
I'm glad to hear that! If you encounter any issue, please feel free to ask me!

**Comment by lhj5426** [comment]
https://github.com/CVHub520/X-AnyLabeling/assets/30548000/6f09091a-e589-4127-a8aa-5aa1994d7300

"Very nice, now that the position is fixed, I can use a mouse macro to click at fixed coordinates. Thank you for your help."

**Comment by lhj5426** [comment]
"But I have a concern. If there's an update next time, will this file be overwritten? Will I have to modify it again to keep the window fixed?"

**Comment by lhj5426** [comment]
https://github.com/CVHub520/X-AnyLabeling/assets/30548000/65d9ae9e-9d85-459e-a1ac-c0e4bb5a536e

"It's very useful. Thank you so much for your help. Now I don't need to keep an eye on it; I can just press a shortcut key to tag it with one click."

**Comment by CVHub520** [comment]
> "But I have a concern. If there's an update next time, will this file be overwritten? Will I have to modify it again to keep the window fixed?"

Yes, I won't be merging this feature into the codebase for the reasons mentioned above. Thanks for you kindly understanding.

**Comment by lhj5426** [comment]
> > "But I have a concern. If there's an update next time, will this file be overwritten? Will I have to modify it again to keep the window fixed?"
> 
> Yes, I won't be merging this feature into the codebase for the reasons mentioned above. Thanks for you kindly understanding.



> > "But I have a concern. If there's an update next time, will this file be overwritten? Will I have to modify it again to keep the window fixed?"
> 
> Yes, I won't be merging this feature into the codebase for the reasons mentioned above. Thanks for you kindly understanding.

"Got it. Then I'll just go through the trouble of modifying it again each time there's an update. Anyway, thank you so much for your help."
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/8bee4f50-db92-4ccb-8ca2-b2c353f27b69)
