### ISSUE TITLE
作者咋导入pose模型进行标注啊，看了半天没看明白

### ISSUE THREAD

**Issue by yxl23** [CVHub520/X-AnyLabeling#504]

**Comment by CVHub520** [comment]
Hey there! 🌵 

1. 可以参考下以下指令将您本地的 yolov8-pose.pt 模型进行转换：
```
from ultralytics import YOLO
# Load a model
model = YOLO('yolov8n-pose.pt')  # load an official model
# Export the model
model.export(format='onnx', dynamic=False, simplify=True)
```

2. 参考 #23 导入自定义模型，[配置文件](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov8n_pose.yaml)定义如下，可修改对应的选项，如模型路径，关键点定义等：
```
type: yolov8_pose
name: yolov8n-pose-r20231103
display_name: YOLOv8n-Pose Ultralytics
model_path: #替换为您的onnx模型本地路径
confidence_threshold: 0.5
nms_threshold: 0.6
kpt_threshold: 0.25
has_visible: true
classes:
  person:
    - nose
    - left_eye
    - right_eye
    - left_ear
    - right_ear
    - left_shoulder
    - right_shoulder
    - left_elbow
    - right_elbow
    - left_wrist
    - right_wrist
    - left_hip
    - right_hip
    - left_knee
    - right_knee
    - left_ankle
    - right_ankle
```

3. 参考关键点标注规范：

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/6fe30efa-f44d-4007-9750-d001dc13751d)

4. 参考[导入导出设置](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E6%A0%87%E7%AD%BE%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA)：

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/8c9ae010-8834-41ce-a2ba-5844c164df6a)
