### ISSUE TITLE
下载模型,能不能提供国内路线选择

### ISSUE THREAD

**Issue by monkeycc** [CVHub520/X-AnyLabeling#505]
下载模型
能不能提供国内路线选择

github下载非常慢

**Comment by CVHub520** [comment]
Regarding the slow download speed for models, you can refer to the solution provided in issue #23. You have the option to download the model via Baidu Cloud and then import it offline. This allows you to conveniently obtain and use the model even when the download speed is slow. Please check the [docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md#%E4%B8%80%E5%A6%82%E4%BD%95%E5%8A%A0%E8%BD%BD%E5%86%85%E7%BD%AE%E6%A8%A1%E5%9E%8B) for the detailed steps on how to do this.

**Comment by CVHub520** [comment]
@monkeycc 您好！关于您此前提出的模型下载速度慢、希望提供国内下载路线的问题，我们很高兴地通知您，该功能现已支持！

我们添加了对可配置模型下载源的支持（ ModelScope），以优化国内用户的下载体验。

**欢迎您拉取最新的代码进行尝试。**

相关的配置说明请参考文档：
https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#77-%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD%E6%BA%90%E9%85%8D%E7%BD%AE

如果在配置或使用过程中遇到任何问题，欢迎随时反馈。感谢您的建议！
