### ISSUE TITLE
实例分割标注 函数： mask_to_polygon，是否可以支持多类型？

### ISSUE THREAD

**Issue by simzhangbest** [CVHub520/X-AnyLabeling#507]
目前阅读源码发现好像只支持了语义分割，单个标签，请问有后续开发计划吗

**Comment by CVHub520** [comment]
您好，感谢您的关注。当前，[label_converter.py](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/label_converter.py)脚本已不再维护，建议直接通过 GUI 界面进行导入和导出操作，具体可参考此[文档](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E6%A0%87%E7%AD%BE%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA)。当前支持`YOLOv5/v8`的实例分割数据集格式，具体定义可参考[Ultralytics 官方教程](https://docs.ultralytics.com/zh/datasets/segment)。

**Comment by simzhangbest** [comment]
> 您好，感谢您的关注。当前，[label_converter.py](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/label_converter.py)脚本已不再维护，建议直接 `git clone` 最新源码通过 GUI 界面进行导入和导出操作，具体可参考此[文档](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E6%A0%87%E7%AD%BE%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA)。当前支持`YOLOv5/v8`的实例分割数据集格式，具体定义可参考[Ultralytics 官方教程](https://docs.ultralytics.com/zh/datasets/segment)。

感谢您的回答，请问一下，如果我导入实例分割的标签，且标签上是 png的掩码图片，目前支持吗？

**Comment by CVHub520** [comment]
您需要依据用户手册进行对应配置文件的设置再进行上传。
















在 2024-07-07 17:42:10，"simzhang" ***@***.***> 写道：

您好，感谢您的关注。当前，label_converter.py脚本已不再维护，建议直接 git clone 最新源码通过 GUI 界面进行导入和导出操作，具体可参考此文档。当前支持YOLOv5/v8的实例分割数据集格式，具体定义可参考Ultralytics 官方教程。

感谢您的回答，请问一下，如果我导入实例分割的标签，且标签上是 png的掩码图片，目前支持吗？
