### ISSUE TITLE
CPU TO GPU

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#509]
Hello Developer, according to the instructions here
https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md

请务必将[app_info.py](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/app_info.py)配置文件中的__preferred_device__字段设置为GPU。
The instructions are not detailed enough. I would like to ask, among the two methods shown in the picture, which one is correct?"
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/ca1cb3bf-095e-4aa8-bb15-c9c33239bd7f)

Because I found that I seem to have been running the program on the CPU. It was previously written as CPU here. Because the manual is not detailed enough, I am not sure which method is correct." 

I have no coding background at all. If it weren't for GPT, I wouldn't even know how to use the software or run the source code. Please forgive me."

**Comment by lhj5426** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/1d193da7-0fad-4a1a-9380-e88b4c9e086b)
That was foolish.
I should have just asked GPT.
Problem solved, closing now. Sorry.

**Comment by CVHub520** [comment]
No problem! Glad you found the solution with GPT.
