### ISSUE TITLE
转换标注失败'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence

### ISSUE THREAD

**Issue by kwanxian** [CVHub520/X-AnyLabeling#51]
windows 10
python 3.10

```
(.venv) D:\Projects\X-AnyLabeling>python tools/label_converter.py --src_path source/valid/ --dst_path source/valid/ --mode custom2yolo

# 报错信息如下
 File "D:\Projects\X-AnyLabeling\tools\label_converter.py", line 162, in custom_to_yolov5
    data = json.load(f.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
```

**Comment by CVHub520** [comment]
您好，这个是文件编码问题，网上有很多参考解决方案，例如[这个](https://blog.csdn.net/mighty13/article/details/107132272)，可以自行搜索下。

**Comment by kwanxian** [comment]
> 您好，这个是文件编码问题，网上有很多参考解决方案，例如[这个](https://blog.csdn.net/mighty13/article/details/107132272)，可以自行搜索下。

确认JSON文件是utf8编码，PY文件也是utf8编码，with open 时也指定utf8。
如果指定utf8，则会报 0xff开头错误。

**Comment by CVHub520** [comment]
您好，@kwanxian ，如果方便的话可以提供下你的图片和JSON文件打包发我下。

**Comment by seejah** [comment]
这个问题解决了吗？我也遇到了同样的问题

**Comment by seejah** [comment]
File "D:\DeveFolder\X-AnyLabeling\tools\label_converter.py", line 251, in custom_to_coco
    data = json.load(f)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
-------
如果把250行处的with open，加上encoding='utf-8'，提示又变成：
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
说明也不对？

**Comment by CVHub520** [comment]
您好，@seejah ，可以提供下相关文件打包给我下吗，这边复现下。

**Comment by seejah** [comment]
al_train文件夹内是用X-AnyLabeling标注的4张图片，另外还有一个标签文件txt，只有一个标签：1
好像存在乱码，所以无论utf8还是gbk还是gb18030都出现了错误。用了您给的chardet函数解决方案也行不通。
期待您的好消息！
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Sep 11, 2023 04:54 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [CVHub520/X-AnyLabeling] 转换标注失败'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence (Issue #51)

&nbsp;



 
***@***.*** ，可以提供下相关文件打包给我下吗，这边复现下。

**Comment by seejah** [comment]
> 您好，@seejah ，可以提供下相关文件打包给我下吗，这边复现下。

邮件已发送，期待好消息！

**Comment by CVHub520** [comment]
> > 您好，@seejah ，可以提供下相关文件打包给我下吗，这边复现下。
> 
> 邮件已发送，期待好消息！

您好，可以发送到指定邮箱：cv_hub@163.com

**Comment by CVHub520** [comment]
@kwanxian @seejah 您好，bug 已修复，请更新代码重新转换，有问题欢迎随时反馈。
