### ISSUE TITLE
Does the code support command-line scripts without a GUI interface?

### ISSUE THREAD

**Issue by littlepiper** [CVHub520/X-AnyLabeling#510]
Since the interface seems unnecessary for batch automatic labeling, could you provide a way to operate without a GUI?

**Comment by CVHub520** [comment]
Hey there! @littlepiper,

Normally, the time spent on batch inference for supporting models is negligible compared to manual inspection. 

However, if your use case is limited to inference services only and does not require the functionality of automatic labeling, i recommend that you perform offline inference directly using the original training framework. This approach can avoid unnecessary interface overhead and allow for more efficient use of resources.
