### ISSUE TITLE
亮度对比度增强功能存在显示问题，已找到问题并修改

### ISSUE THREAD

**Issue by thgpddl** [CVHub520/X-AnyLabeling#511]
在“视图”--“亮度对比度”功能中，修改亮度或对比度后，导致图像画面损坏，效果如下图：
![image](https://github.com/CVHub520/X-AnyLabeling/assets/48787805/865464d8-0988-4024-9469-960370d97fa5)

经过排查，是在“BrightnessContrastDialog”类的“on_new_value”函数中有问题：
```python
    def on_new_value(self, _):
        """On new value event"""
        brightness = self.slider_brightness.value() / 50.0
        contrast = self.slider_contrast.value() / 50.0

        img = self.img
        if brightness != 1:
            img = PIL.ImageEnhance.Brightness(img).enhance(brightness)
        if contrast != 1:
            img = PIL.ImageEnhance.Contrast(img).enhance(contrast)
        # 此处PIL图像为RGBA模式
       
       # 但是在下方使用了RGB模式，导致显示出现问题
        qimage = QImage(
            img.tobytes(), img.width, img.height, QImage.Format_RGB888
        )
        self.callback(qimage)  # qimage已经是处理后的图片
```

解决办法为将PIL的RGBA模式转为RGB模式即可：
```python
        img = self.img
        if brightness != 1:
            img = PIL.ImageEnhance.Brightness(img).enhance(brightness)
        if contrast != 1:
            img = PIL.ImageEnhance.Contrast(img).enhance(contrast)
        
        img = img.convert("RGB")   #新增颜色模式转换代码
              
        qimage = QImage(
            img.tobytes(), img.width, img.height, QImage.Format_RGB888
        )
```
现在图像正常：
![image](https://github.com/CVHub520/X-AnyLabeling/assets/48787805/e5020bb6-f72d-4645-a6ef-da4467372ceb)

**Comment by thgpddl** [comment]
> Hi, @thgpddl:
> 
> Thank you very much for reporting the brightness and contrast enhancement display issue 🙏.
> 
> The issue has been resolved by converting the image to RGB mode. Additionally, i have made some optimizations including adding a reset button 🔄. Please update to the latest version to see these improvements 🚀.
> 
> ![image](https://private-user-images.githubusercontent.com/72010077/347014395-3a22a1f5-6f83-48b1-84fd-9f43013cf7ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzU1OTMsIm5iZiI6MTcyMDU3NTI5MywicGF0aCI6Ii83MjAxMDA3Ny8zNDcwMTQzOTUtM2EyMmExZjUtNmY4My00OGIxLTg0ZmQtOWY0MzAxM2NmN2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAxMzQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZTgyYjFiOGJiYjMyMjhlNDU4Nzc5YjZjM2M2ZGMxZTg4YWExNjE2ZDRkNWVjYjUwOWU4NjQwNzk3MWViOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OCH-DmEGA1jNGT-I7-DK3jLEDA3A4l7MCzmVT_W8oUc)

感谢您的工作，但是现在遇到了新的问题，当我打开一个图片文件夹后，调整亮度对比度后，通过按键"D"打开下一张图片时程序闪退，并报错如下：
```bash
TypeError: BrightnessContrastDialog.on_new_value() takes 1 positional argument but 2 were given
已放弃 (核心已转储)
```

**Comment by CVHub520** [comment]
> > Hi, @thgpddl:
> > Thank you very much for reporting the brightness and contrast enhancement display issue 🙏.
> > The issue has been resolved by converting the image to RGB mode. Additionally, i have made some optimizations including adding a reset button 🔄. Please update to the latest version to see these improvements 🚀.
> > ![image](https://private-user-images.githubusercontent.com/72010077/347014395-3a22a1f5-6f83-48b1-84fd-9f43013cf7ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzU1OTMsIm5iZiI6MTcyMDU3NTI5MywicGF0aCI6Ii83MjAxMDA3Ny8zNDcwMTQzOTUtM2EyMmExZjUtNmY4My00OGIxLTg0ZmQtOWY0MzAxM2NmN2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAxMzQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZTgyYjFiOGJiYjMyMjhlNDU4Nzc5YjZjM2M2ZGMxZTg4YWExNjE2ZDRkNWVjYjUwOWU4NjQwNzk3MWViOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OCH-DmEGA1jNGT-I7-DK3jLEDA3A4l7MCzmVT_W8oUc)
> 
> 感谢您的工作，但是现在遇到了新的问题，当我打开一个图片文件夹后，调整亮度对比度后，通过按键"D"打开下一张图片时程序闪退，并报错如下：
> 
> ```shell
> TypeError: BrightnessContrastDialog.on_new_value() takes 1 positional argument but 2 were given
> 已放弃 (核心已转储)
> ```

Fixed. Please git pull the latest code and try to adjust the brightness and contrast again. 😄
