### ISSUE TITLE
Ubuntu2204下进入软件后，打开文件或者打开目录均闪退

### ISSUE THREAD

**Issue by kubiwudi** [CVHub520/X-AnyLabeling#514]
Ubuntu2204下进入软件后，打开文件或者打开目录均闪退

**Comment by CVHub520** [comment]
> Ubuntu2204下进入软件后，打开文件或者打开目录均闪退

Hi, @kubiwudi:

For this issue, you can try to git pull the latest source code and re-run the X-AnyLabeling via terminal.
