### ISSUE TITLE
Error in model prediction: zero-size array to reduction operation maximum which has no identity. Please check the model.

### ISSUE THREAD

**Issue by wwmpython** [CVHub520/X-AnyLabeling#517]
<img width="1014" alt="微信图片_20240712113445" src="https://github.com/user-attachments/assets/209961fe-36fd-4bbc-a277-09600d0a0de7">

**Comment by CVHub520** [comment]
Hi there! @wwmpython, 😃 

Thank you for reporting the issue. To help me diagnose and replicate the problem, could you please package the ONNX file, the configuration file, and a sample image that you're certain the model should be able to predict the target on into a compressed archive? 

Please send the compressed package to the following email address for further investigation: cv_hub@163.com. Your assistance in providing these files is crucial for us to resolve the issue. Thank you in advance for your cooperation!

**Comment by wwmpython** [comment]
> Hi there! @wwmpython, 😃
> 
> Thank you for reporting the issue. To help me diagnose and replicate the problem, could you please package the ONNX file, the configuration file, and a sample image that you're certain the model should be able to predict the target on into a compressed archive?
> 
> Please send the compressed package to the following email address for further investigation: [cv_hub@163.com](mailto:cv_hub@163.com). Your assistance in providing these files is crucial for us to resolve the issue. Thank you in advance for your cooperation!

ok

**Comment by CVHub520** [comment]
Hey there, @wwmpython! After reviewing the files you provided, I noticed an issue with your ONNX file:

![image](https://github.com/user-attachments/assets/beed3e9e-6a84-4a85-9e7e-840734a31d9f)

It appears there's a mistake that needs correcting. Please re-export your `*.pt` file using the official YOLOv8 repository. You can follow the guidelines in this [tutorial](https://docs.ultralytics.com/modes/export/#usage-examples) for the export process. 

If you continue to experience issues, don't hesitate to reach out for further assistance.

**Comment by wwmpython** [comment]
当我按照官方的代码将我的权重文件转换为onnx模型时，出现如下错误：Traceback (most recent call last):
  File "F:\wwm\yolov8-pytorch-master\onnx_trans.py", line 10, in <module>
    model = YOLO("F:\wwm\yolov8-pytorch-master\model_data\yolov8_s.pt")
  File "F:\anaconda3\envs\onnx\lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "F:\anaconda3\envs\onnx\lib\site-packages\ultralytics\engine\model.py", line 149, in __init__
    self._load(model, task=task)
  File "F:\anaconda3\envs\onnx\lib\site-packages\ultralytics\engine\model.py", line 230, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "F:\anaconda3\envs\onnx\lib\site-packages\ultralytics\nn\tasks.py", line 857, in attempt_load_one_weight
    model = (ckpt.get("ema") or ckpt["model"]).to(device).float()  # FP32 model
KeyError: 'model'

进程已结束,退出代码1
<img width="1277" alt="飒飒的" src="https://github.com/user-attachments/assets/dc0a7b17-664d-4bd4-bd40-5df2bd7db30c">

**Comment by CVHub520** [comment]
I highly recommend utilizing the official repository (https://github.com/ultralytics/ultralytics) for training and exporting purposes. 

Upon reviewing the image you provided, it is evident that you are using a third-party repository, which is not advisable.

If you still have compelling reasons that necessitate using a non-official repository, I urge you to write your own export code to ensure consistency with the official standards.
