### ISSUE TITLE
在ubuntu20.04中源码运行，打开文件夹读取不到任何文件

### ISSUE THREAD

**Issue by elky98** [CVHub520/X-AnyLabeling#519]
在open_folder_dialog函数中
```python
target_dir_path = str(
            QtWidgets.QFileDialog.getExistingDirectory(
                self,
                self.tr("%s - Open Directory") % __appname__,
                default_open_dir_path,
                QtWidgets.QFileDialog.ShowDirsOnly
                | QtWidgets.QFileDialog.DontResolveSymlinks
            )
        )
 ```
 使用了原生的选择器，选择文件夹时只能选择到文件，并且选择的文件是一个符号链接，导致后续的读取错误。
 添加 QtWidgets.QFileDialog.DontUseNativeDialog 后恢复正常。
 ```python
target_dir_path = str(
            QtWidgets.QFileDialog.getExistingDirectory(
                self,
                self.tr("%s - Open Directory") % __appname__,
                default_open_dir_path,
                QtWidgets.QFileDialog.ShowDirsOnly
                | QtWidgets.QFileDialog.DontResolveSymlinks
                | QtWidgets.QFileDialog.DontUseNativeDialog
            )
        )
 ```

**Comment by CVHub520** [comment]
Hi, @elky98! 👏

Thank you for reporting this issue and providing a solution. I appreciate your detailed report and the steps you’ve taken to resolve the problem. 😄 

I'll take this into consideration and look into updating my codebase to prevent this issue for other users.

Once again, thank you for your contribution, and i hope you continue to have a positive experience with X-AnyLabeling.

Best regards,
CVHub

**Comment by elky98** [comment]
When I use the Upload YOLO-Hbb Annotations, I encountered the same problem. So there may be the same problem in other selection folders of the code, I hope you can check them together.
