### ISSUE TITLE
加载自定义模型用于自动标注报错

### ISSUE THREAD

**Issue by yangboning** [CVHub520/X-AnyLabeling#52]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/37468757/13e4e424-ab5d-4032-a77d-c3b071a1aa06)

显示也不是很完整。

![image](https://github.com/CVHub520/X-AnyLabeling/assets/37468757/438b12bf-d8cc-4d43-ba26-bd274bdcff14)

**Comment by CVHub520** [comment]
您好，请先确定你的gpu与cuda版本是否匹配并在本地确认确实能正常调用，另外需要使用gpu推理的化可自行下载源码按照教程自行打包编译下，具体可参考[帮助文档](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/Q&A.md)

**Comment by yangboning** [comment]
我是用这个GPU和Cuda版本进行模型训练的，然后现在安装了GPU版本的onnxruntime。
![image](https://github.com/CVHub520/X-AnyLabeling/assets/37468757/2f3d9fb1-a7cc-418f-a3e1-06a668b4aff1)
训练YOLO的时候，验证截图：
![image](https://github.com/CVHub520/X-AnyLabeling/assets/37468757/a7c1d69b-67c8-442a-880b-920e4eabc845)

**Comment by CVHub520** [comment]
@yangboning 您好，CPU版本报错目前是从没遇到过，这个可能性很低，你可以git clone下最新版本，从源码运行下。

**Comment by yangboning** [comment]
从源码环境安装报错
![image](https://github.com/CVHub520/X-AnyLabeling/assets/37468757/9aadd3c0-9b4a-46a5-ad3a-16fde0509a15)
心累。

**Comment by CVHub520** [comment]
> 之前使用CPU版本的onnxruntime也是同样报错，GPU版本也是这个报错。 我是用这个GPU和Cuda版本进行模型训练的，然后现在安装了GPU版本的onnxruntime。 ![image](https://user-images.githubusercontent.com/37468757/265907077-2f3d9fb1-a7cc-418f-a3e1-06a668b4aff1.png) 训练YOLO的时候，验证截图： ![image](https://user-images.githubusercontent.com/37468757/265907306-a7c1d69b-67c8-442a-880b-920e4eabc845.png) ![image](https://user-images.githubusercontent.com/37468757/265910459-bc76b098-0951-4c4f-ac4f-0910c44a6f19.png)

您好，@yangboning ，目前 CPU 版本问题已修复，可以重新下载使用，无需配置 CUDA 与 CUDnn。

**Comment by yangboning** [comment]
CPU版本还是报错。。。
