### ISSUE TITLE
Can the Loaded Model Have a Custom Name/Remark?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#520]
![image](https://github.com/user-attachments/assets/69b4ac4d-f7ae-4471-9193-ff4af91301c5)

Hello Developer,

I have trained many models and want to compare the differences between them. To do this, I need to load different models and run images through them. However, with multiple models loaded, it becomes difficult to remember which one is which. Therefore, I would like to ask if it's possible to add a custom name feature to the model loading process.

For example, I could name models like:

Model 1
0712 S3
0713 Trained Before Bed
0714
Such a feature would allow me to easily identify and manage the different models I have trained.

Thank you for your help.

**Comment by lhj5426** [comment]
Additionally, it would be great if after selecting a model, a prompt could appear allowing me to input a remark or name for the model. If I choose not to input a name, it could default to "User Model". If a name is provided, the current model name should display the custom input.

**Comment by CVHub520** [comment]
https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md#21-%E5%B7%B2%E9%80%82%E9%85%8D%E6%A8%A1%E5%9E%8B
@lhj5426

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/1de28234-172b-4498-8be6-1afa6c7fd737)
Thank you very much. The problem has been resolved.
