### ISSUE TITLE
多目标跟踪标注导出时报错

### ISSUE THREAD

**Issue by Rane2021** [CVHub520/X-AnyLabeling#523]
参考 https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#多目标跟踪的步骤，多目标跟踪标注导出 MOT标签时报错：

invalid literal for int() with base 10: 'video-7'

**Comment by CVHub520** [comment]
Hi @Rane2021:

Thank you for reporting the issue. We have fixed the error related to non-integer filenames during the MOT annotation export (`invalid literal for int() with base 10: 'video-7'`). The fix has been merged and push to repository.

You can now try to update your local copy of the repository with the latest changes by running `git pull`. This should resolve the error you encountered.

If you have any further questions or run into any other issues, please don't hesitate to let us know.

Thank you for using our software and for your support!

Best regards,
CVHub
