### ISSUE TITLE
Auto Use Last Label  Help!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by johnnyallt** [CVHub520/X-AnyLabeling#524]
Hello CVHub520
  I need help about "Auto Use Last Label" function, I want to the label is the one I chosen one, not the last label on the current page. Is there a way to achieve this function.

**Comment by CVHub520** [comment]
Hello! @johnnyallt:

You can modify the source code at this location: [label_widget.py#L5356](https://github.com/CVHub520/X-AnyLabeling/blob/3954abb8c38cfce62d28751bd670747201b0886d/anylabeling/views/labeling/label_widget.py#L5356).
