### ISSUE TITLE
同时加载多个模型！

### ISSUE THREAD

**Issue by sunmooncode** [CVHub520/X-AnyLabeling#525]
同时创建多个模型实例对图片进行预测！

**Comment by CVHub520** [comment]
You can refer to this [example](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/yolov5_car_plate.py).

**Comment by sunmooncode** [comment]
@CVHub520 我修改好程序后 如何编译软件包括CPU和GPU版本

**Comment by sunmooncode** [comment]
@CVHub520 打包的GPU版本加载模型时闪退，CPU版本正常。

**Comment by CVHub520** [comment]
Hi there, I see that you’re experiencing an issue where the GPU version of the software crashes when loading a model, while the CPU version works fine. This behavior is often indicative of a problem with the local CUDA libraries not being included or properly configured in the package for the GPU version.

To resolve this, please ensure that:
1. The CUDA libraries are correctly packaged with the GPU version of the software.
2. The CUDA version you’re using is compatible with the version of the GPU drivers installed on your system.
3. All necessary CUDA dependencies are included and that their paths are correctly set in your environment variables.

You may need to review the build process to make sure that the CUDA libraries are being linked correctly during compilation. Additionally, check the documentation for any specific instructions on packaging the GPU version of the software. 

If you continue to face issues, please provide more details about your setup, and we’ll do our best to help you troubleshoot further.

**Comment by sunmooncode** [comment]
@CVHub520 感谢及时回复，我从问题历史中找到了解决办法，我将ORT降级到1.16.0在打包就可以成功加载了。

**Comment by CVHub520** [comment]
You're welcome! I'm glad to hear it worked. If you have any more questions or need further assistance, feel free to ask. Happy labeling!
