### ISSUE TITLE
报错Error in predict_shapes: unsupported operand type(s) for /: 'str' and 'int'

### ISSUE THREAD

**Issue by YaDa721** [CVHub520/X-AnyLabeling#526]
能正常加载自定义模型 也能运行 但是运行后没有生成框 终端报错：Error in predict_shapes: unsupported operand type(s) for /: 'str' and 'int'
![微信截图_20240716193922](https://github.com/user-attachments/assets/5be151eb-69f4-4ff8-9148-268a43a50ad8)

**Comment by CVHub520** [comment]
Hey there! @YaDa721,

Thank you for bringing this to our attention! Could you please provide more detailed information, such as whether you are running this based on the latest source code and which model you are using? This will help us better pinpoint the issue.

**Comment by CVHub520** [comment]
Thank you for letting us know which model and version you are currently using. To ensure optimal performance and access to the latest features, we highly recommend that you update to the latest version of X-anylabeling. Here's a simplified process to get the latest version:

```bash
git clone https://github.com/CVHub520/X-AnyLabeling.git
```
After cloning the repository, you can follow the [installations](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md#%E6%BA%90%E7%A0%81%E8%BF%90%E8%A1%8C) to run:

```bash
python anylabeling/app.py
```
Should you encounter any issues during the update or while using the software, please feel free to reach out to us.

Happy labeling! 😄
