### ISSUE TITLE
进行自动化标注时，加载任意模型，窗口会关闭

### ISSUE THREAD

**Issue by libra-bola** [CVHub520/X-AnyLabeling#528]

**Comment by CVHub520** [comment]
Hi, I understand that you’re experiencing an issue where the window closes when loading any model during automated labeling. 

To troubleshoot this, please ensure that all necessary packages are installed correctly. Additionally, verify that they are compatible with your local environment, including the correct version of CUDA if you’re using GPU acceleration. Double-check the installation instructions and environment setup in the documentation to ensure everything is configured properly.

If the problem persists after verifying these steps, please provide more details so we can assist you further. Thanks!
