### ISSUE TITLE
所有模型下载，可否提供个百度网盘链接？

### ISSUE THREAD

**Issue by xinsuinizhuan** [CVHub520/X-AnyLabeling#53]

**Comment by CVHub520** [comment]
您好， @xinsuinizhuan ，这边后续会整理一份开放出来。

**Comment by xinsuinizhuan** [comment]
嗯。谢谢。一个一个下载太慢了

**Comment by CVHub520** [comment]
@xinsuinizhuan 您好，已打包整理好，欢迎使用，[链接](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/models_list.md)直达。
