### ISSUE TITLE
How to download the source code of an old version?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#531]
I made a mistake and downloaded the new version of the source code. There are two changes that I find very inconvenient.

One change is:
Previously, I could delete a marked box by just hovering the mouse over it and clicking delete. There was no need to click on the box, just moving the mouse over it was enough. Now, I have to click on the box first and then click delete.

The second change is:
Previously, when I pressed R, I could select a rectangle. After selecting, I could directly move or drag to adjust it. Now, after pressing R, it enters the drawing mode, and when I try to drag to adjust, it stays in the drawing mode! I have to exit the drawing mode first to adjust the rectangle?

So, I'm wondering if there is a way to download the old version of the source code? These two changes have made the software experience very poor."

Would you like more details or adjustments on this translation?

**Comment by lhj5426** [comment]
"I want to revert to the original operation mode. How can I change it back? Since there is no version control, I can't download the old version of the source code from GitHub."

Would you like any more assistance with this translation?

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/79ab1ad1-5a5f-4d57-8516-693db90b4f11)
Although version 2.3.7 has restored the original operation experience, the features you added previously, such as changing the label color, crosshair size, and border thickness, are all missing.

How can I revert to the original operation mode in the latest version while keeping all these features?

**Comment by lhj5426** [comment]
These operational changes should be settings options, allowing users to choose whether to enable continuous selection or to activate the marked box under the mouse pointer only by clicking, instead of making all these changes across the board. The current operation is not user-friendly and uncomfortable."

Please help me restore these two original operation modes and experiences. Thank you

**Comment by lhj5426** [comment]
https://github.com/user-attachments/assets/e778727a-9a9d-4a6e-ad05-17e9221e091a

The previous operation mode was really comfortable. How can I restore it?"

**Comment by CVHub520** [comment]
Hi @lhj5426:

Thank you for your feedback regarding the recent changes. To revert to the previous version of the source code where the behavior was as you described, you can check out the commit [47f4d76](https://github.com/CVHub520/X-AnyLabeling/commit/47f4d76b5497612636437d1d3736f0658f4ae688). Here are the steps:

1. **Open your terminal or command prompt**.
2. **Navigate to your project directory**.
3. **Checkout the previous commit**:

   ```sh
   git checkout 47f4d76
   ```

4. **Create a new branch (optional)**: If you want to make changes while keeping the ability to revert to the current version, you can create a new branch:

   ```sh
   git checkout -b old-version-branch 47f4d76
   ```

By following these steps, you should be able to revert to the version of the source code with the previous behavior.

If you need further assistance with this process or have any other questions, please let us know. We are here to help!

**Comment by lhj5426** [comment]
> 你好 ：
> 
> 感谢您对最近更改的反馈。要恢复到行为如您所描述的先前版本的源代码，您可以查看提交 47f4d76。步骤如下：
> 
> 1. 打开您的终端或通讯和提示符。
> 2. 导航到您的项目目录。
> 3. 查看之前的提交：
>    ```shell
>    git checkout 47f4d76
>    ```
> 4. 创建新分支（可选）：如果您想在进行更改的同时保持恢复到当前版本的能力，您可以创建一个新分支：
>    ```shell
>    git checkout -b old-version-branch 47f4d76
>    ```
> 
> 通过执行这些步骤，您应该能够恢复到具有先前行为的源代码版本。
> 
> 如果您在此过程中需要进一步帮助或有任何其他问题，请告诉我们。我们随时为您提供帮助！

I don't understand how to do this. Is there a way to download files and replace them? I don't know how to use this. I asked GPT, but I still don't understand."

> Hi @lhj5426* :
> 
> Thank you for your feedback regarding the recent changes. To revert to the previous version of the _source_ code where the behavior was as you described, you can check out the commit [47f4d76](https://github.com/CVHub520/X-AnyLabeling/commit/47f4d76b5497612636437d1d3736f0658f4ae688). Here are the steps:
> 
> 1. **Open your terminal or command prompt**.
> 2. **Navigate to your project directory**.
> 3. **Checkout the previous commit**:
>    ```shell
>    git checkout 47f4d76
>    ```
> 4. **Create a new branch (optional)**: If you want to make changes while keeping the ability to revert to the current version, you can create a new branch:
>    ```shell
>    git checkout -b old-version-branch 47f4d76
>    ```
> 
> By following these steps, you should be able to revert to the version of the _source_ code with the previous behavior.
> 
> If you need further assistance with this process or have any other questions, please let us know. We are here to help!

I don't understand how to do this. Is there a way to download files and replace them? I don't know how to use this. I asked GPT, but I still don't understand."

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/ca10c5bb-b302-417c-b309-914418ab9635)
 followed GPT's instructions for a while. Although I didn't quite understand the content in these boxes, it seems that I have indeed restored the previous operating state

**Comment by lhj5426** [comment]
Thank you very much. I'll leave the 'old' folder version as it is from now on. If I want to upgrade and try it out, I'll use a new path and a new folder to avoid discomfort if I can't revert back. Anyway, thank you
