### ISSUE TITLE
导入 yolov8 OBB label时候报错

### ISSUE THREAD

**Issue by Rane2021** [CVHub520/X-AnyLabeling#534]
'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte

**Comment by CVHub520** [comment]
@Rane2021, Hi!

Thank you for reaching out regarding the error you encountered while importing YOLOv8 OBB labels. The error message indicates that there is a character in your label file that cannot be decoded with the 'utf-8' codec, which suggests that the file may not be properly encoded in UTF-8.

To resolve this issue, please follow these steps to ensure your label file is saved in the `utf-8` format:
1. **Check File Encoding:**
   - Open the label file in a text editor that allows you to view and change the file encoding (such as Notepad++, Sublime Text, or Visual Studio Code).
   - Look for the encoding information in the editor. This is usually found in the status bar or within the file save options.
2. **Convert File to UTF-8:**
   - If the file is not in UTF-8, use the text editor to convert it:
     - In Notepad++, go to `Encoding` > `Convert to UTF-8 without BOM`.
     - In Sublime Text, go to `File` > `Save with Encoding` > `UTF-8`.
     - In Visual Studio Code, you can save the file with UTF-8 encoding by clicking `File` > `Save with Encoding` > `UTF-8`.
3. **Save the File:**
   - After converting the file to UTF-8, save it. Make sure to overwrite the original file or save it with a new name if you want to keep the original.
4. **Re-import the Labels:**
   - Try importing the label file again into YOLOv8 to see if the error has been resolved.
5. **Use Command Line (Optional):**
   - If you prefer using the command line, you can convert the file to UTF-8 using the `iconv` command:
     ```
     iconv -f ORIGINAL_ENCODING -t utf-8 input_file > output_file
     ```
     Replace `ORIGINAL_ENCODING` with the current encoding of your file, `input_file` with the path to your label file, and `output_file` with the desired output path.
6. **Check for Special Characters:**
   - If the file contains special characters that are not part of the UTF-8 character set, you may need to replace or remove them.

By following these steps, you should be able to resolve the encoding issue with your YOLOv8 OBB label file. If you continue to experience difficulties, please provide additional details about your file and the tools you are using to process it.

Best regards,
CVHub
