### ISSUE TITLE
导入Yolov5标签格式出错

### ISSUE THREAD

**Issue by bommbomm** [CVHub520/X-AnyLabeling#535]
将图片、标签【txt文件】，类别【classes.txt】放在同一个文件夹或者是不同文件的时候，用X-AnyLabeling导入Yolo水平框标签出错，
有点不是很了解该怎么查看已经标注好的数据集？以及类别文件该怎么导入比较好。麻烦作者有空可以回复一下哈~谢谢

**Comment by bommbomm** [comment]
试过好几种导入的方法，例如图片和标签在不同文件夹，但是还是不大行

**Comment by CVHub520** [comment]
Hey there! @bommbomm,

I understand you're facing difficulties with importing Yolo horizontal box labels using X-AnyLabeling. To ensure a smooth import process, please follow the steps outlined in our [tutorial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E6%A0%87%E7%AD%BE%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA) for importing and exporting YOLO labels. It's a straightforward process, and the guide should help clarify the steps.

Additionally, I highly recommend pulling the latest source code via git to ensure you're using the most up-to-date version of the software. If you continue to encounter errors after following the tutorial and updating the source code, please provide the specific error messages you're receiving. This will help us diagnose the issue more accurately and assist you further. 

Thank you for reaching out, and we'll do our best to help you resolve this.
