### ISSUE TITLE
运行完没有标签

### ISSUE THREAD

**Issue by Thompson21666** [CVHub520/X-AnyLabeling#536]
导入自己的模型自动标注，接下来点击播放那个按钮，一次性全部运行完毕后没有报错，但是生成的文件里面没有标签。这如何解决呢？
![749bcbcd05e3060747cc8c30e8a7bf5](https://github.com/user-attachments/assets/3285a3ac-ec30-47d3-a2ca-1565a43d5135)
![c097571c231802bc83c331a38639ed8](https://github.com/user-attachments/assets/9428ace8-5ddb-4aec-815c-36ffb7f8de55)
<img width="220" alt="75827a4404acc5c36fd5ebb6d7c77c2" src="https://github.com/user-attachments/assets/7caa3a30-393b-4f5f-90e8-ea0fd5d9a2df">

**Comment by CVHub520** [comment]
Hi there, @Thompson21666, 👏

Thank you for reaching out and providing details about the issue you're experiencing with importing your model for auto-annotation.

To help us diagnose the problem, could you please provide the following information?

1. The contents of your configuration file that you used for the model import.
2. A screenshot of the input and output node information for your ONNX model. This can typically be found in the model's documentation or by using tools like Netron to visualize the model graph.

Once we have this information, we'll be better equipped to identify why the labels are not being generated after the auto-annotation process completes without errors.

Looking forward to your reply so we can assist you further.

Best regards,
CVHub

**Comment by Thompson21666** [comment]
感谢你的回复，截图如下。
![微信图片_20240718204737](https://github.com/user-attachments/assets/8195126f-9ee8-468c-a589-c0b74caae71a)
![29d4050acd85e11accdc55486efd92f](https://github.com/user-attachments/assets/e65fc042-d014-4f25-af8e-d055793e479e)
![3c1c1e3b7e3c204da984df411bba858](https://github.com/user-attachments/assets/d0493d1e-4a2f-4406-83a5-60319bf2212b)

**Comment by CVHub520** [comment]
Thank you for your input. It seems that you are trying to employ dynamic inference, with the original resolution set at 640x640 and a custom resolution of 224x224. Unfortunately, dynamic inference is not a functionality that is currently offered by X-AnyLabeling. I recommend that you proceed with exporting the model for use in static mode instead.

**Comment by Thompson21666** [comment]
好的，谢谢你的回复。但是我应该具体怎么做呢？还可以用X-anylabeling实现自动标注裂缝图片吗？

**Comment by Thompson21666** [comment]
好的，谢谢你，问题已解决。
