### ISSUE TITLE
yaml中type字段和name字段的疑问

### ISSUE THREAD

**Issue by ZSBSB** [CVHub520/X-AnyLabeling#537]
![image](https://github.com/user-attachments/assets/409f0b34-12a5-4544-9dd1-541657418f5b)
您好，请问如果我的网络是使用yolov8l-obb训练的，如上图所示，其中type中写yolov8_obb不会报错，但是写yolov8l-obb会报如下图所示的错误，请问这是什么原因呢？期待您的回复。
![image](https://github.com/user-attachments/assets/08cde4d2-25b7-420a-a29b-abff19c33893)

如果我是基于yolov8l-obb训练的，name字段可以随便写吗？我看随便写也不会报错

**Comment by ZSBSB** [comment]
![image](https://github.com/user-attachments/assets/4ca3da82-189d-437e-953b-5371c454698e)
我没太看懂这里关于name和type字段的解释

**Comment by CVHub520** [comment]
您好，感谢对 `X-AnyLabeling`  的关注。现在回答下您的问题：
1. 当用户点击加载模型时，app内部会根据当前配置文件的`type`字段实例化对应的内置模型，因此此字段不得修改。
2. 对于`name`字段，主要用于内置模型索引对应的配置文件。因此，如果是用户自定义的模型，此字段可随意设置并不会生效。
3. 用户可以通过设置`display_name`来区分不同的模型。

**Comment by ZSBSB** [comment]
我明白您的意思了，感谢您的回复！
