### ISSUE TITLE
【功能需求】鼠标在编辑模式，配合键盘摁键，在图上画方框区域，批量选中方形区域，覆盖到的标注，删除后，用sam标注

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#54]
在图中具有很多目标，尤其是远处小目标，比较模糊下，自动标注模型，不能有效的识别，与区分

在自动标注后，需要批量删除局部区域的标注，然后使用sam对模糊的，重新一个个标注。

**Comment by CVHub520** [comment]
您好， @aiyou9 ，批量删除功能目前已经支持了，你可以先打开**编辑**模式，随后按住 `Ctrl` 键再配合鼠标左键逐个点击你需要删除的目标框，待全部选取后再按下 `Delete` 快捷键即可实现批量删除功能。

**Comment by aiyou9** [comment]
> 您好， @aiyou9 ，批量删除功能目前已经支持了，你可以先打开**编辑**模式，随后按住 `Ctrl` 键再配合鼠标左键逐个点击你需要删除的目标框，待全部选取后再按下 `Delete` 快捷键即可实现批量删除功能。

嗯，是的，比较多的话，还是结合画区域，批量选中，一起，更快捷
