### ISSUE TITLE
标注文件异常过大问题

### ISSUE THREAD

**Issue by macaulishxcoo** [CVHub520/X-AnyLabeling#540]
作者，你好，
     标注文件imageData字段值是不是可以再优化下，目前标注后产生的一长串值导致一个标注文件几十兆，而且导致标注的格式和其他第三方不兼容。

**Comment by macaulishxcoo** [comment]
> imageData

**Comment by CVHub520** [comment]
Hi @macaulishxcoo,

Thank you for your suggestion. To disable this option, you can simply uncheck `File > Save With Image Data` in the top menu bar.
