### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by Andy-HKU** [CVHub520/X-AnyLabeling#541]
After running command 'python anylabeling/app.py' the terminal shows following ---
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
---
How to fix it?

**Comment by CVHub520** [comment]
Hey there! @Andy-HKU,

This is a common issue that many users encounter, here the error message suggests that the Qt platform plugin "xcb" cannot be loaded, which is often related to missing dependencies or configuration issues.

You can typically resolve it by searching online for solutions by using keywords like `qt.qpa.plugin: Could not load the Qt platform plugin 'xcb'"` to find tutorials and forums that discuss this issue. There are numerous resources available that can guide you through the resolution process.

For instance, you can consult the following resource for more information: [Check out this article](https://blog.csdn.net/LOVEmy134611/article/details/107212845).

**Comment by Andy-HKU** [comment]
Thank you! this issue is solved.
However I noticed although I set the __preferred_device__ field to GPU in the app_info.py configuration file, the GPU is not working instead CPU is doing the work, how to fix this?

**Comment by CVHub520** [comment]
You might refer to #496 and #500.
