### ISSUE TITLE
x-anylabeling tool

### ISSUE THREAD

**Issue by divya70063** [CVHub520/X-AnyLabeling#542]
File "anylabeling/app.py", line 66
    f" {default_config_file})"
    ^
SyntaxError: invalid syntax

**Comment by CVHub520** [comment]
@divya70063, Hi!

The error indicates that an f-string is being used, a feature in Python for creating formatted string literals that was introduced starting with Python 3.6. 

As of now, X-AnyLabeling requires a Python version of 3.8 or higher. Please update your Python version and adhere to the official guidelines provided in the [installation instructions](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md#%E6%BA%90%E7%A0%81%E8%BF%90%E8%A1%8C) to set up the application.
