### ISSUE TITLE
预测的结果偏上

### ISSUE THREAD

**Issue by chaodreaming** [CVHub520/X-AnyLabeling#544]
使用ai标注的时候，用的自己的模型，v8和v5都试过了，标签没问题，训练出来的模型用v8的onnx推理的例子也没问题，但是使用model.predict推理的时候就会出现偏上一点，距离差不多正好是标签的大小，基本上每一个预测的结果都差这么一些，排除了标签问题，排除了onnx问题，现在发现v8和标注器都存在这个问题，找不到原因了，求助

**Comment by CVHub520** [comment]
Hello @chaodreaming,

Thank you for bringing this issue to our attention! 😊

It sounds like you're experiencing an alignment issue with the predicted results when using your own models for AI labeling. You’ve done a great job narrowing down the problem to the prediction phase. To further troubleshoot, I recommend debugging the relevant sections of our code to ensure everything aligns correctly with the official YOLOv8 preprocessing, inference, and post-processing steps.

You can start by comparing our implementation with the official YOLOv8 example [here](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/__base__/yolo.py). Specifically, check the following:

1. **Preprocessing**: Ensure that the input image is being resized, normalized, and transformed in the same way as in the official YOLOv8 implementation.
2. **Inference**: Verify that the model inference is correctly utilizing the ONNX model without any discrepancies.
3. **Post-processing**: Compare the decoding of the predicted results, including bounding box adjustments and any applied transformations.

This detailed comparison should help identify any potential misalignments that might be causing the predictions to be slightly offset.

If you find any specific discrepancies or need further assistance, please let us know. We're here to help! 👍

Best regards,
CVHub

**Comment by CVHub520** [comment]
Hi @chaodreaming ,

I noticed you closed the issue. Has it been resolved? If possible, could you please share the solution with the community? It would be greatly beneficial for everyone 🙏.

Thank you for your contribution.
