### ISSUE TITLE
如何取消标签？

### ISSUE THREAD

**Issue by Thompson21666** [CVHub520/X-AnyLabeling#546]
这个Crack 0.9如何取消掉呢，只保留多边形不要绿色的标签。
第一次运行的时候是正常的，第二次运行就生成很多个框是为什么？

**Comment by Thompson21666** [comment]
![0c3f1775ba4330969fbd11a6fb435a7](https://github.com/user-attachments/assets/84034183-7fe0-49e1-b954-0362c433b93e)

![屏幕截图 2024-07-25 180205](https://github.com/user-attachments/assets/a6902e8d-693a-4c0f-b88a-e36fad769537)

**Comment by CVHub520** [comment]
Hey there! 😊 Let's tackle your questions one by one:

> Q1: How do I remove the Crack 0.9 label? I want to keep the polygons but get rid of the green label.

A1: No worries! 😌 Just press 'Ctrl+L' and the text will disappear. 🪄

> Q2: Everything was normal the first time I ran it, but why does it generate so many boxes on the second run?

A2: It sounds like you might have tweaked the `Confidence` slider.  Simply adjust the threshold on the gui interface to filter out the low-scoring targets and you'll be good to go! 🚀
