### ISSUE TITLE
分割模型标注时，坐标点溢出

### ISSUE THREAD

**Issue by shangihuo** [CVHub520/X-AnyLabeling#547]
在使用多边形标注时，生成的坐标值，有的为负数，有的超过了图片的宽高限制，导出yolo标签后，有大于1和小于0的值存在。

**Comment by CVHub520** [comment]
Hi @ZSBSB 👋,

Thank you for reporting this issue. To assist you further, could you please provide the exported label file along with the corresponding images and the original JSON annotations? This will help us investigate the problem in more detail.

Kindly send the requested files to our designated 📨: [cv_hub@163.com](mailto:cv_hub@163.com).

Thank you for your cooperation!

Best regards,
CVHub Maintainer
