### ISSUE TITLE
How to change the recognition language model in PaddleOCR?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#548]
![image](https://github.com/user-attachments/assets/ca019a05-5327-499c-9299-9efccb99588d)
![image](https://github.com/user-attachments/assets/072fa666-ddaf-48a9-8efd-7dcdadb17a23)

Hello Developer,

Today, when I was loading a custom model, I noticed that the default setting in your software is ch_PP-OCRv4(PaddleOCR), which means it recognizes Chinese by default.

So, is it possible for me to change to other language recognition models, such as Japanese? However, I am unsure how to change it and where to find it on my computer.

Could you please let me know where the model is automatically downloaded to on the hard drive? I would like to switch to the Japanese OCR model.

Thank you.

**Comment by CVHub520** [comment]
Hello @lhj5426 ,

Thank you for reaching out with your question about changing the recognition language model in PaddleOCR.
Currently, our software defaults to the ch_PP-OCRv4 model, which is optimized for Chinese recognition. As of now, we haven't integrated a multi-language version into our software. However, you can certainly manually deploy a different language model, such as Japanese.

To assist you with this, I recommend checking out issue #538, where you can find guidance on how to deploy the model you need.

If you encounter any issues during this process, feel free to update this thread with the details, and I or someone from the community will be happy to help you further.

Happy modeling!
CVHub Maintainer 🚀

**Comment by lhj5426** [comment]
Thank you.

**Comment by CVHub520** [comment]
Hey! @lhj5426,

We’re happy to inform you that we’ve implemented this feature and it is now supported in our latest update.

The new lightweight model is designed to improve the performance of our Japanese recognition capabilities, especially on devices with limited resources. We’ve optimized the model to reduce its size while maintaining a high level of accuracy for Japanese text recognition tasks.

Please update to the latest version of our software to take advantage of this new feature. If you encounter any issues or have further questions, feel free to let us know.

Thank you for your continued support.

Happy labeling! 🚀

**Comment by lhj5426** [comment]
Thank you very much for informing me of this news. I will immediately update the source code to the latest version and try out the newly added Japanese recognition model. Thank you

**Comment by CVHub520** [comment]
Also, we are might be considering the possibility of adding a feature in the future that would allow users to directly export the annotated video tasks as a complete video file.
