### ISSUE TITLE
How to make the software remember the model that the user imports?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#550]
![image](https://github.com/user-attachments/assets/d231d175-6dd5-4c46-a5ba-cd32ebb82a68)
Hello developer,

Previously, I had several models imported here, and every time I restarted the software, I could select them again. However, today, just now, my Windows 10 system experienced a blue screen error. After I forced a restart, I found that the models were cleared. Additionally, when I imported the models again, the software didn't remember the previously imported models after closing and reopening the software.

Did the blue screen cause an issue with the software's configuration? How can I restore it so that the software remembers the imported models each time? Could you please help me? Thank you.

**Comment by CVHub520** [comment]
Hello @lhj5426,

Thank you for reaching out and sorry to hear about the trouble you've encountered. 😢 It sounds like the blue screen error might have affected the software's configuration files, which could be why it's not remembering the imported models.
To potentially resolve this issue, you can try the following steps:

1. Close the X-AnyLabeling software if it's currently open.
2. Navigate to your user directory. This is typically located at `C:\Users\YourUsername` on Windows 10.
3. Look for the files `.anylabelingrc` and `.xanylabelingrc` within your user directory.
4. If these files exist, delete them. Please make sure to back up these files before deleting them, just in case.
5. Restart the X-AnyLabeling software and try importing your models again.

This should reset the software's configuration and potentially fix the issue with remembering the imported models. 🤞 If the problem persists after trying this, please let us know, and we'll continue to assist you.

Thank you for your patience, and I hope this helps! 🌟

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/b1e6fc55-5861-4cc6-8bb2-90a5f425a952)


Thank you for your help. I followed your instructions, and the problem has been solved. The model can now remember things correctly again. I really appreciate your assistance.
