### ISSUE TITLE
导出yolo格式时，总是出现空文件0kb

### ISSUE THREAD

**Issue by SUN2024-AI** [CVHub520/X-AnyLabeling#551]

**Comment by CVHub520** [comment]
Hello @SUN2024-AI,

Thank you for reaching out about the issue you’re experiencing with exporting to YOLO format. I’m here to help you troubleshoot this. 😊

To address the issue of exporting empty files (0kb), please follow these steps:

1. **Ensure Latest Source Code**: Make sure you are using the latest version of the source code. If you are running the GUI version, it might not be up-to-date. Please switch to the latest source code and try again.
2. **Check Annotation Type**: Press Ctrl+G to review the type of the current annotation. It should match the expected type for the task. For instance, use ‘rectangle’ for horizontal bounding boxes, ‘polygon’ for segmentation, and ‘rotation’ for rotated bounding boxes.
3. **Label List File:** Double-check that the names of the labels you have annotated are included in the label list file that you uploaded.


If you’ve gone through these steps and are still encountering issues, please provide more details about your annotation process, and any error messages you might be seeing. This will help us get to the bottom of this issue more quickly. 🚀

Looking forward to your response!

Best regards, CVHub Maintainer 🛠️

**Comment by SUN2024-AI** [comment]
I used the latest source code library and the problem was solved, thank you!

**Comment by CVHub520** [comment]
You're welcome! 😊 I'm thrilled that the information was beneficial to you. If you run into any snags or have further questions, please don't hesitate to get in touch.

Furthermore, if you stumble upon any specific challenges or bugs, crafting a minimal reproducible example can significantly expedite our ability to pinpoint and rectify the issue.

As a final note, ensure that you are using the most current version of the X-AnyLabeling repo to leverage the latest enhancements and bug fixes. This often helps in resolving unexpected hiccups.

Wishing you a joyful annotating adventure and the best of luck with your project! 🌟🚀
