### ISSUE TITLE
标注目标较小较多且拥挤的视频数据并不方便，希望可以改进一下

### ISSUE THREAD

**Issue by fyw1999** [CVHub520/X-AnyLabeling#552]
作者您好，我在实际使用的过程中发现标注目标较小较多且拥挤的视频数据并不方便，在标该类注视频数据的时候很多时候会参考前后帧的标注情况，在这种情况下，如果我在当前帧缩放到某一个大小和区域后，切到下一帧的时候还是希望能按照上一帧的缩放大小锁定到上一帧聚焦的区域，但是现在的软件并不能实现这个功能，保持上一帧缩放大小的功能有时候有用有时没用，给标注视频数据造成了不小的困难，如果可以改进的话将进一步缩减标复杂视频数据的代价，谢谢！

**Comment by CVHub520** [comment]
Hi there! @fyw1999,

Thank you for your valuable feedback and for using our software! 🙏 I understand the challenge you're facing with annotating small, numerous, and crowded objects in video data, and the need for a consistent viewing experience across frames.

The feature you're requesting—to maintain the zoom level and focus area when navigating between frames—is indeed important for efficient annotation of such videos. Currently, the inconsistency you're experiencing with the zoom lock feature is something we are aware of and we agree that it could be improved.

We will take your suggestion into consideration for future updates. In the meantime, if you have any workarounds or additional suggestions that could improve your workflow, please feel free to share them. Your input is crucial for us to create a better tool for everyone. 🚀

Thank you for your patience and support. We'll keep you updated on the progress of this feature.

Best regards,
CVHub Maintainer
