### ISSUE TITLE
关于OCR模型是否使用的是PPOCR_V2版本？

### ISSUE THREAD

**Issue by maxi2015qwe** [CVHub520/X-AnyLabeling#554]
我在OCR的Yaml里面看到，检测图像的文字的时候，使用的还是ch_ppocr_mobile_v2.0_cls_infer.onnx 这个模型， 这是不是意味着使用的任然是v2版本的？而不是v4？

**Comment by CVHub520** [comment]
> 我在OCR的Yaml里面看到，检测图像的文字的时候，使用的还是ch_ppocr_mobile_v2.0_cls_infer.onnx 这个模型， 这是不是意味着使用的任然是v2版本的？而不是v4？

Hi, @maxi2015qwe, for this question, you can refer to this [docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/model_zoo.md#%E5%85%89%E5%AD%A6%E5%AD%97%E7%AC%A6%E8%AF%86%E5%88%AB).
