### ISSUE TITLE
SAM2上线了，该软件是否能直接使用SAM2呢？

### ISSUE THREAD

**Issue by hibobzz** [CVHub520/X-AnyLabeling#557]
MATA开源了 SAM2的模型，pt转onnx后能不能直接用。

**Comment by CVHub520** [comment]
@hibobzz,

🎉 First off, it's exciting to hear about the release of SAM2! Regarding your question about integrating SAM2 with our software, it's a great inquiry.

As of now, we haven't had the chance to delve into the specifics of the SAM2 model structure. However, you're on the right track with converting the `.pt` model to `.onnx`. This is often a necessary step for compatibility with various frameworks.
Here's what I suggest: 📝
- You can proceed with exporting the SAM2 model to an ONNX file.
- After that, use a tool like Netron to visualize and inspect the ONNX model. This will help you to compare it with the existing model structures in our software.

If the model architecture is compatible or can be adapted with minimal changes, it's likely that you could use SAM2 directly. We'd love to hear about your findings and any insights you gain from this exploration. If you encounter any issues or need further assistance, please feel free to share them here, and we'll do our best to support you.

Keep us posted on your progress, and thanks for being an active member of our community! 🌟

Best regards,
CVHub Maintainer

**Comment by vietanhdev** [comment]
Hi there! :smile: 
I added the support for SAM2 at AnyLabeling now: https://github.com/vietanhdev/anylabeling. You and use it as the reference.
SAMExporter can be used for model converson: https://github.com/vietanhdev/samexporter.

@hibobzz @CVHub520

**Comment by CVHub520** [comment]
Hey @vietanhdev, 😃

Great to hear that you’ve added support for SAM2 to AnyLabeling! 

I'd really appreciate it. SAMExporter is a useful tool for model conversion. I'll keep it in mind for future projects.
Thanks for sharing the updates!
