### ISSUE TITLE
The new version crashes when tagging.

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#558]
ModuleNotFoundError: No module named 'jsonlines'

ziiyue@DESKTOP-RF09FLV D:\000A\X-AnyLabeling-main (master)
(yolo) # pip install jsonlines
Collecting jsonlines
  Downloading jsonlines-4.0.0-py3-none-any.whl.metadata (1.6 kB)
Collecting attrs>=19.2.0 (from jsonlines)
  Downloading attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Downloading jsonlines-4.0.0-py3-none-any.whl (8.7 kB)
Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
   ---------------------------------------- 60.8/60.8 kB 190.6 kB/s eta 0:00:00
Installing collected packages: attrs, jsonlines
Successfully installed attrs-23.2.0 jsonlines-4.0.0

ziiyue@DESKTOP-RF09FLV D:\000A\X-AnyLabeling-main (master)
(yolo) # python anylabeling/app.py

ziiyue@DESKTOP-RF09FLV D:\000A\X-AnyLabeling-main (master)
(yolo) # python anylabeling/app.py
Traceback (most recent call last):
  File ".\anylabeling\views\labeling\label_widget.py", line 3009, in new_shape
    (
ValueError: not enough values to unpack (expected 6, got 5)

ziiyue@DESKTOP-RF09FLV D:\000A\X-AnyLabeling-main (master)
(yolo) #

https://github.com/CVHub520/X-AnyLabeling/issues/503

X-AnyLabeling-main\anylabeling\views\labeling\widgets\label_dialog.py

Today, I tried to upgrade the software and found that the tagging operation logic has reverted to the previous version. I followed the instructions provided earlier to replace the file, hoping to fix the tagging window in place. However, now it’s throwing an error. Can you help me with this?

Also, can't there be a direct option in the settings for this? I was worried that modifying the code might not work if the software was upgraded, and now my concern has been validated. In the new version, this method of modifying the code no longer works.

Could you add a fixed option to allow users to choose whether to fix the tag window position? This way, users won't have to modify the code and face crashes with every update, and developers will have fewer support requests. It would be more convenient for both the developers and the users.

**Comment by lhj5426** [comment]
Why not directly merge the fixed tagging function into the latest code? It's really troublesome to come here for help every time there's an issue. If you add this function directly, it would save everyone a lot of unnecessary trouble. What do you think?

**Comment by CVHub520** [comment]
@lhj5426,

🚨 I'm sorry to hear that you're experiencing crashes with the tagging operation in the new version. We appreciate your detailed report and your suggestions for improvement.

Firstly, I want to assure you that we've actually introduced a new feature that should address your concerns. You can now git pull the latest source code and modify the `move_mode` parameter in the configuration file to control the behavior of the tagging window. This should prevent the need for direct code modifications that could be overwritten during updates.

Here's how you can do it:
- Open the configuration file for the software.
- Look for the `move_mode` parameter.
- Set it according to your preference for the tag window position, i.e., 'center'.

Regarding your suggestion for a direct option in the settings, it's a valid point and we're considering it for future updates. Our aim is to make the software as user-friendly and stable as possible, and your feedback is crucial in achieving that.

We understand the inconvenience of coming back for help with each update. We're working on a more streamlined approach to ensure a smoother user experience. Thank you for your patience and for bringing this to our attention.

If you continue to experience issues after adjusting the `move_mode` parameter, please provide the error details, and we'll be happy to assist you further.

🌟 Your feedback is invaluable, and we're committed to making X-AnyLabeling better with each release.

Best regards,
CVHub Maintainer

**Comment by lhj5426** [comment]
https://github.com/user-attachments/assets/92d427f6-b6e5-430c-8814-aa37c5777722
Following your instructions, the label setting window is now back in a fixed position. This allows me to continue using keyboard and mouse macros to quickly tag items. Thank you very, very much!
![image](https://github.com/user-attachments/assets/c252db17-62c6-47c4-9300-a57d212b8a32)

Recently, using this method has significantly improved the efficiency of tagging. I've tagged tens of thousands of images for training. If it weren't for the fixed label selection window allowing the use of keyboard and mouse macros, I wouldn't have been able to tag so efficiently. Thank you very much!

**Comment by CVHub520** [comment]
@lhj5426 you're welcome! 😊 I'm thrilled that the information was beneficial to you. If you run into any snags or have further questions, please don't hesitate to get in touch.

Furthermore, if you stumble upon any specific challenges or bugs, crafting a minimal reproducible example can significantly expedite our ability to pinpoint and rectify the issue.

As a final note, ensure that you are using the most current version of the X-AnyLabeling repo to leverage the latest enhancements and bug fixes. This often helps in resolving unexpected hiccups.

Wishing you a joyful annotating adventure and the best of luck with your project! 🌟🚀
