### ISSUE TITLE
About editing the current image and moving the position of the image

### ISSUE THREAD

**Issue by lushikai** [CVHub520/X-AnyLabeling#559]
@CVHub520 Hello contributors! When i want to move the current editing image, I can only use the scroll wheels below and to the right to move the zoomed-in image. Is it possible to right-click the mouse to quickly move the position of the picture?

**Comment by CVHub520** [comment]
Hello @lushikai 👋,

Thank you for reaching out and for using X-AnyLabeling! 🌟

I understand your request for a more intuitive way to move the image while editing. Currently, X-AnyLabeling is designed to focus and zoom based on the mouse pointer's position. To reposition the image, you can use the scroll wheels below and to the right, as you've mentioned.

For a quick refit of the image to the window, you can use the `Ctrl+F` shortcut. To zoom in on a specific area, move your mouse to that detail and hold `Ctrl` while using the mouse scroll wheel.

We've found that with the right shortcut configurations, users can become quite accustomed to this workflow. However, I've noted your suggestion to add a right-click drag feature for moving the image. This could be a valuable enhancement for user convenience.

We'll consider this for future updates. In the meantime, I encourage you to experiment with the current shortcuts to see if they improve your experience. If you have any more feedback or encounter any issues, please don't hesitate to let us know!

Happy labeling! 🎨✨
