### ISSUE TITLE
kie_linking reference before assignment for Segment anything 2 model. 

### ISSUE THREAD

**Issue by jivankandel** [CVHub520/X-AnyLabeling#563]
X-AnyLabeling/anylabeling/views/labeling/label_widget.py", line 5966, in finish_auto_labeling_object
    shape.kie_linking = kie_linking
UnboundLocalError: local variable 'kie_linking' referenced before assignment
Aborted (core dumped)
Fix
"def finish_auto_labeling_object(self):
        kie_linking=[]  #Empty kie_linking defined.
        """Finish auto labeling object."""
        has_object, cache_label = False, None
        for shape in self.canvas.shapes:
            if shape.label == AutoLabelingMode.OBJECT:
                cache_label = shape.cache_label
                has_object = True
                break"

**Comment by CVHub520** [comment]
Hi @jivankandel, 👋

Thank you for bringing this to our attention and for the detailed report. I've reviewed the code snippet you've shared, and it appears that initializing `kie_linking` as an empty list before its usage is a valid solution to the issue you're encountering.

I'm happy to confirm that this issue has been addressed in the latest commit. 🚀 The fix should prevent the `UnboundLocalError` from occurring, allowing the `Segment anything 2` model to function as expected.

If you encounter any further issues or have additional suggestions, please feel free to let us know. We appreciate your contribution to the X-AnyLabeling project!

Best regards,
X-AnyLabeling Maintainer
