### ISSUE TITLE
Feature Request: Implement Direct Category Addition in GUI to Avoid Manual TXT File Edits

### ISSUE THREAD

**Issue by chenjs123** [CVHub520/X-AnyLabeling#565]
你好，可以提个改善不，现在的图像分类是固定加载txt去保存类别的，如果我有新的图片类别我就需要去重新修改txt类别配置文件，有什么办法可以直接在界面添加一个控件来新增需要的新类别吗

**Comment by CVHub520** [comment]
Hello @chenjs123 👋,

Thank you for reaching out and for your suggestion! 🙌 We appreciate the feedback and understand the inconvenience of having to manually update the txt file for new categories.

We are considering implementing a feature that would allow users to add new categories directly through the interface in upcoming versions. 🚀 This would streamline the process and make it more user-friendly.

We'll keep you updated on the progress of this feature. In the meantime, if you have any other ideas or questions, please feel free to share them here or open a new issue.

Best regards,
X-AnyLabeling Maintainer

**Comment by chenjs123** [comment]
> Hello @chenjs123 👋,
> 
> Thank you for reaching out and for your suggestion! 🙌 We appreciate the feedback and understand the inconvenience of having to manually update the txt file for new categories.
> 
> We are considering implementing a feature that would allow users to add new categories directly through the interface in upcoming versions. 🚀 This would streamline the process and make it more user-friendly.
> 
> We'll keep you updated on the progress of this feature. In the meantime, if you have any other ideas or questions, please feel free to share them here or open a new issue.
> 
> Best regards, X-AnyLabeling Maintainer

谢谢您的回复，x-anylabeling确实是款很好用的标注软件，也大大加快我的标注进度，我其实还有几点问题想跟您说下
