### ISSUE TITLE
用yolov5s迭代的模型推理图片时候报错

### ISSUE THREAD

**Issue by 133673** [CVHub520/X-AnyLabeling#567]
(sam2) E:\AI\SEG\source\X-AnyLabeling-2.3.7>python anylabeling/app.py
C:\Users\HP\.conda\envs\sam2\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
Error in predict_shapes: list index out of range
![image](https://github.com/user-attachments/assets/edf536e8-ba3f-4653-82dd-6c31226f9d02)
![image](https://github.com/user-attachments/assets/b3f31d62-cb43-40bb-b892-c54e315f5ec4)
这是为什么呢？

**Comment by CVHub520** [comment]
Hey there! @133673, 👋

Thank you for reaching out and for using X-AnyLabeling. I'm sorry to hear that you're encountering an error when trying to infer images with your YOLOv5s model.

To resolve this, please follow these steps:
1. Ensure that your model's input and output nodes are correctly aligned with those expected by X-AnyLabeling. You can find detailed instructions on how to do this in our documentation: [加载已适配的用户自定义模型](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md#%E5%8A%A0%E8%BD%BD%E5%B7%B2%E9%80%82%E9%85%8D%E7%9A%84%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B).
2. If you have made changes to the model architecture or dimensions, you may need to adjust the inference code accordingly. Double-check the dimensions of the input data and ensure they match the model's requirements.

If you continue to face issues after following these steps, please provide additional details about your environment setup and any modifications you've made to the model or code. This will help us to assist you more effectively.

Happy to help further! 🚀
