### ISSUE TITLE
自定義切割模型

### ISSUE THREAD

**Issue by nairb86** [CVHub520/X-AnyLabeling#57]
您好 我想用自己資料集所訓練出的切割模型應用於自動標駐上，不透過YOLO系列/SAM系列是可行的嗎?
例如我用Unet訓練我自己的特殊資料集(ex特殊工業用等)，將訓練完成的模型套用到自定義模型裡去增加資料集。
目前有成功讀取到模型，但本身模型output只有mask的結果，如果直接套用原始代碼會報錯誤，因unet沒有像yolo的bbox該如何改寫程序，謝謝

原始程序裡Yolov8_seg,py其中183行有段bboxes, masks = outputs[0], outputs[1] ，自定義模型我輸出只有mask而已，就會造成錯誤，能給些建議或改寫的方向嗎，感謝!

**Comment by nairb86** [comment]
> 嘿，你好， @nairb86 ，很高兴认识你。如果你想通过 UNet 模型进行推理的话，可以参考下 [mask_to_polygon](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/polygon_mask_conversion.py#L53) 该函数，将 `mask` 转换为 `polygon` 表示，并在此基础上做调整即可，如限制点的个数等。最后，等全部标注完成后再使用转换脚本转回 `mask` 即可。

**Comment by nairb86** [comment]
> 嘿，你好， @nairb86 ，很高兴认识你。如果你想通过 UNet 模型进行推理的话，可以参考下 [mask_to_polygon](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/polygon_mask_conversion.py#L53) 该函数，将 `mask` 转换为 `polygon` 表示，并在此基础上做调整即可，如限制点的个数等。最后，等全部标注完成后再使用转换脚本转回 `mask` 即可。

您好，謝謝您的回覆，我想重新理解一下，您的意思是透過我自定義的模型Unet推論出我要的mask，在藉由你的腳本[mask_to_polygon]，把mask轉換成polygon的json檔案，並且用X-AnyLabeling修正我的標記後再轉換為mask即可嗎?

還是是能夠透過軟件直接加載我的Unet直接一鍵推論與生成呢，謝謝!

**Comment by CVHub520** [comment]
> > 嘿，你好， @nairb86 ，很高兴认识你。如果你想通过 UNet 模型进行推理的话，可以参考下 [mask_to_polygon](https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/polygon_mask_conversion.py#L53) 该函数，将 `mask` 转换为 `polygon` 表示，并在此基础上做调整即可，如限制点的个数等。最后，等全部标注完成后再使用转换脚本转回 `mask` 即可。
> 
> 您好，謝謝您的回覆，我想重新理解一下，您的意思是透過我自定義的模型Unet推論出我要的mask，在藉由你的腳本[mask_to_polygon]，把mask轉換成polygon的json檔案，並且用X-AnyLabeling修正我的標記後再轉換為mask即可嗎?
> 
> 還是是能夠透過軟件直接加載我的Unet直接一鍵推論與生成呢，謝謝!

您好，这个**把mask轉換成polygon的json檔案逻辑**是可以直接实现在框架里面的，只是说让你借鉴下这个思路去实现这个逻辑。具体实现可以参考以下四个步骤自行适配：
X-AnyLabeling/anylabeling/configs/auto_labeling: 定义配置文件；
X-AnyLabeling/anylabeling/configs/auto_labeling/models.yaml: 添加配置文件；
X-AnyLabeling/anylabeling/services/auto_labeling：模型推理逻辑实现；
X-AnyLabeling/anylabeling/services/auto_labeling/model_manager.py：添加到模型管理。
