### ISSUE TITLE
可以支持线条标注转成mask吗

### ISSUE THREAD

**Issue by Ryzquo** [CVHub520/X-AnyLabeling#570]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

线条标注转成mask，可以自行设置线条宽度

### Use case

在标注车道类型数据的时候，使用线条比多连形方便不少

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hello @Ryzquo 👋,

I understand the utility of this feature, especially for tasks like lane marking in traffic data, where line annotations could indeed be more convenient than polygonal shapes.

Regarding the additional material, could you please provide an example of how you envision the line-to-mask conversion to work? A mock-up or a description of the desired outcome would be very helpful for us to understand your needs better.

If you're not in a position to submit a PR, that's completely fine. We'll take your request into consideration for future development. If you do change your mind and would like to contribute, we're always open to community contributions and would be happy to guide you through the process.

Looking forward to your response!

Best regards,
[X-AnyLabeling Maintainer] 🚀
