### ISSUE TITLE
mac 电脑启动后导入图片和使用 AI 标注时闪退

### ISSUE THREAD

**Issue by hb-2017** [CVHub520/X-AnyLabeling#572]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Tool, User Interface (UI)

### Bug

我在导入图片时会报以下错误，然后程序闪退
Traceback (most recent call last):
  File "/Users/admin/project/X-AnyLabeling-2.3.0/./anylabeling/views/labeling/widgets/canvas.py", line 1044, in paintEvent
    shape.paint(p)
  File "/Users/admin/project/X-AnyLabeling-2.3.0/./anylabeling/views/labeling/shape.py", line 191, in paint
    assert len(self.points) in [1, 2, 4]
AssertionError
zsh: abort      python anylabeling/app.py

### Information

这个命令并没有执行成功

(x-anylabeling) (gp_envn) admin@mark X-AnyLabeling-2.3.0 % python anylabeling/checks.py
python: can't open file '/Users/admin/project/X-AnyLabeling-2.3.0/anylabeling/checks.py': [Errno 2] No such file or directory

这是我虚拟环境中的版本
certifi                        2024.7.4
charset-normalizer             3.3.2
coloredlogs                    15.0.1
contourpy                      1.2.1
cycler                         0.12.1
Cython                         3.0.11
darkdetect                     0.8.0
filelock                       3.15.4
filterpy                       1.4.5
flatbuffers                    24.3.25
fonttools                      4.53.1
fsspec                         2024.6.1
huggingface-hub                0.24.5
humanfriendly                  10.0
idna                           3.7
imgviz                         1.5.0
importlib_resources            6.4.0
kiwisolver                     1.4.5
lapx                           0.5.5
matplotlib                     3.9.1.post1
mpmath                         1.3.0
natsort                        8.1.0
numpy                          1.25.0
onnx                           1.13.1
onnxruntime                    1.16.3
opencv-contrib-python-headless 4.7.0.72
packaging                      24.1
pillow                         10.4.0
pip                            24.0
ply                            3.11
protobuf                       3.20.3
pyclipper                      1.3.0.post5
pyparsing                      3.1.2
PyQt5                          5.15.9
PyQt5-sip                      12.12.2
python-dateutil                2.9.0.post0
PyYAML                         6.0
qimage2ndarray                 1.10.0
requests                       2.32.3
scipy                          1.13.1
setuptools                     72.1.0
shapely                        2.0.5
sip                            6.7.12
six                            1.16.0
sympy                          1.13.1
termcolor                      1.1.0
tokenizers                     0.20.0
toml                           0.10.2
tomli                          2.0.1
tqdm                           4.66.5
typing_extensions              4.12.2
urllib3                        2.2.2
wheel                          0.43.0
zipp                           3.19.2

### Link to a Reproducible Demonstration Video

https://github.com/user-attachments/assets/16a2c9bd-9653-4d5b-a75e-78ebe2db0c15

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
@hb-2017, Hi there,

Thank you for bringing this to our attention. Could you please try updating your source code to the latest version by running 'git pull origin main'? Typically, this action resolves most issues. ^_^

**Comment by hb-2017** [comment]
愿意是因为导入的文件夹中存在一个 json 文件，这个 json 文件是上一次点击自定义模型中的「运行」产生的文件，删除后即可使用
