### ISSUE TITLE
Hello, I noticed Requirement: Implement automaticannotation using YOLOV8 and SAMMED2D.

### ISSUE THREAD

**Issue by AImagicAI** [CVHub520/X-AnyLabeling#573]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Hello, I noticed that YOLOv5 SAM and YOLOv8 EfficientViT SAM have been implemented, but I couldn't find any cases of YOLOV8 and SamMed-2d.

### Additional

Requirement: Implement automaticannotation using YOLOV8 and SAMMED2D.

**Comment by CVHub520** [comment]
Hello,

Thank you for your inquiry. While we currently do not have a direct case study for the combination of YOLOv8 and SamMed-2d, you can certainly create your own setup by referencing our existing pipeline. You can also follow the instructions provided in this document ([link](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md#%E5%8A%A0%E8%BD%BD%E5%B7%B2%E9%80%82%E9%85%8D%E7%9A%84%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B)) to load and adapt a custom model according to your needs. Should you encounter any issues or require assistance, please feel free to reach out to us.

Wishing you a smooth setup process!
