### ISSUE TITLE
你好，在2.3.6版本中，当我点击Ctrl+Shift+D时，图片并没有被删除，还是在原来路径中，也没有生成delete文件夹

### ISSUE THREAD

**Issue by chelsea9067** [CVHub520/X-AnyLabeling#575]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

你好，在2.3.6版本中，当我点击Ctrl+Shift+D时，图片并没有被删除，还是在原来路径中，也没有生成delete文件夹

**Comment by CVHub520** [comment]
Hello @chelsea9067 👋,

Thank you for reaching out and reporting the issue you're experiencing with version 2.3.6. I'm sorry to hear that the expected deletion behavior isn't occurring when you use the Ctrl+Shift+D shortcut.

Our tests indicate that the feature is functioning as expected. However, there might be a few reasons why you're encountering this problem. First, could you please try updating to the latest version by running `git pull origin main` in your terminal to ensure you have the most recent changes?

Additionally, it's possible that there might be a shortcut key conflict on your system. As a workaround, you can manually delete the image by navigating to the menu bar and selecting File > Delete Image File to see if that resolves the issue.

If the problem persists after trying these steps, please let us know, and we'll be happy to assist you further. 🙏

Best regards,
X-AnyLabeling Maintainer
