### ISSUE TITLE
How to Infer YOLOv8's Rotated Rectangular OBB Model

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#576]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/1e6889fd-cac1-4edf-b429-14e68c0d8188)

First, I used software to locate the text in the bubbles of the comic using rotated rectangles. Then, I adjusted the angle appropriately and exported the rotated labels using the software's YOLO OBB export feature. After that, I performed preliminary training using yolov8s-obb.pt. Once training was complete, the inference code from YOLOv8 was able to perform inference correctly and normally, as shown in the image.
![image](https://github.com/user-attachments/assets/f7ad4e46-d0da-41fe-84e1-3fd098cb3e6c)

![image](https://github.com/user-attachments/assets/9db0843e-a651-4c2b-bdfc-56c808d9fa45)
However, after converting the model, as shown in the image...

When I load the model in the software and perform inference, nothing is detected. Did I make a mistake in the settings?

![image](https://github.com/user-attachments/assets/1dceab82-3f3e-4c15-b243-f345f6f92ecb)
This is the YAML file for the model I loaded. Can you help me? Thank you!

**Comment by CVHub520** [comment]
You might find this [file](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov8s_obb.yaml) useful.

**Comment by lhj5426** [comment]
> 您可能会发现此 [文件 ](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolov8s_obb.yaml)很有用。

Thank you very much, it was really useful. I’ve always trained with standard, square rectangles, and today was the first time I tried training with inclined rectangles. It has been a huge help. Love you and thanks!
