### ISSUE TITLE
Can rectangular data in detect format be converted to OBB format?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#577]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

I have no experience at all and am starting from scratch to train a model using YOLOv8. I have annotated over 20,000 images in detect format, and now I realize that I need a model that supports rotating OBB (Oriented Bounding Box). I don't want all my hard work, time, and effort to go to waste. So, I'm asking if it's possible to convert my data to OBB format. Can regular rectangles also be used for OBB?

**Comment by CVHub520** [comment]
Hello @lhj5426 👋,

Thank you for reaching out and for your dedication to annotating such a large dataset. I understand your concern about not wanting your efforts to go to waste.

Good news! You can indeed convert your rectangular data (HBB - Horizontal Bounding Box) to OBB (Oriented Bounding Box) format using X-AnyLabeling. Here's how you can do it:

1. Import your 20,000 images into the X-AnyLabeling tool.
2. Navigate to the top menu bar and select 'Tool'.
3. From the dropdown, choose 'Convert HBB to OBB'.
4. After the conversion, you will have the option to adjust the angle for each bounding box as needed.

This process should help you transition your dataset to the OBB format without starting from scratch. If you encounter any issues or need further assistance, feel free to ask. We're here to help! 🚀

Best regards,
X-AnyLabeling Maintainer

**Comment by CVHub520** [comment]
Btw, just a friendly reminder to always back up your original label data before performing any conversion or major changes. This ensures that you have a safety net in case anything unexpected happens during the conversion process.

**Comment by lhj5426** [comment]
> Btw, just a friendly reminder to always back up your original label data before performing any conversion or major changes. This ensures that you have a safety net in case anything unexpected happens during the conversion process.

Thank you very much for your help and advice.

I will first make a backup and try the data conversion method you suggested

**Comment by lhj5426** [comment]
https://github.com/user-attachments/assets/48a4703a-aa99-4f34-beac-e1c89dc0a712




This morning, I randomly picked a few images and converted the rectangular labels into rotatable labels. It was almost a lossless conversion, with the position of the rectangles remaining unchanged. It’s amazing! Then, I used these few labels converted from rectangular data to train a test model quickly. After testing, the converted labels were also able to train and infer correctly. I’m really, really grateful.

https://github.com/user-attachments/assets/6efb8112-ee39-4e5a-a97b-63e87b52f4b6
