### ISSUE TITLE
运行2.4.0版本在界面上没看到SAM2

### ISSUE THREAD

**Issue by liumingzhu6060** [CVHub520/X-AnyLabeling#579]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/ecac92c0-eab2-44f1-9639-db12d60f7d57)

**Comment by CVHub520** [comment]
Hello @liumingzhu6060 👋,

Thank you for reaching out and for using X-AnyLabeling. I'm sorry to hear that you're encountering issues with the SAM2 model.

Regarding the first issue of not seeing SAM2 in the interface, could you please ensure that you have the latest version of the software? If you've just updated to 2.4.0, it should be included, but it's always good to double-check.

As for the error message when loading the custom model, it seems like there might be an issue with the configuration file format. Here are two steps you can take to resolve this:
1. **Delete the Configuration File**: Please try deleting the configuration file in your user directory, which could be either `.anylabelingrc` or `.xanylabelingrc`. This will allow the application to reset to the default settings.
2. **Update to the Latest Code**: After deleting the configuration file, please make sure you have the latest code by running `git pull origin main` in your terminal from the root directory of the project.

If you continue to experience issues after following these steps, please let us know, and we'll be happy to assist you further. 

Also, if you could provide any additional error logs or context, which can excuate `python anylabeling/checks.py`, that would be greatly appreciated as it will help us diagnose the problem more effectively.

Thank you for your patience and for contributing to the X-AnyLabeling community! 🌟
