### ISSUE TITLE
ppocr 加载后，点击运行报错，argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by stupidrocket** [CVHub520/X-AnyLabeling#58]
Traceback (most recent call last):
  File "/Users/luoqiyuan/Documents/X-AnyLabeling-main/./anylabeling/views/labeling/widgets/canvas.py", line 856, in paintEvent
    p.fillRect(
TypeError: arguments did not match any overloaded call:
  fillRect(self, a0: QRectF, a1: Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, a0: QRect, a1: Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, b: Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, a0: QRectF, color: Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, a0: QRect, color: Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, b: Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, c: Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, r: QRect, c: Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, r: QRectF, c: Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, style: Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, r: QRect, style: Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, r: QRectF, style: Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, preset: QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, r: QRect, preset: QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, r: QRectF, preset: QGradient.Preset): argument 1 has unexpected type 'float'
zsh: abort      python anylabeling/app.py

**Comment by CVHub520** [comment]
您好， @stupidrocket ，感谢关注。我这边是没问题的，请问下可以将报错的图片打包发我复现下吗？如果方便的话，请发送到邮箱：cv_hub@163.com

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/b8735b0b-e72c-40a1-9afa-f1dff62a7571)

**Comment by stupidrocket** [comment]
@CVHub520 您好，我发现所有图片ocr识别后都会闪退，该bug应该与图片无关，因为ppocr识别的json已生成，重新打开app，再点击由ppocr生成了json的图片都会闪退，json文件已通过邮箱发送

**Comment by CVHub520** [comment]
> @CVHub520 您好，我发现所有图片ocr识别后都会闪退，该bug应该与图片无关，因为ppocr识别的json已生成，重新打开app，再点击由ppocr生成了json的图片都会闪退，json文件已通过邮箱发送

您好，非常抱歉，我刚尝试了很多图片，发现都能完美运行。可能由以下几个原因导致：
1. 测试图片格式有问题；（可以先尝试下[demo](https://github.com/CVHub520/X-AnyLabeling/tree/main/assets/examples/ocr)图片，不要修改保存路径，正常运行获取结果后再重新加载看看还会不会闪退）
2. 识别框超出边界；（这个可能需要麻烦你将图片打包一份给我）
3. 存放路径设置有问题；（根据您提供的 `*.json` 文件中 `imagePath` 字段的内容，您需要将 json 文件和图片文件存放在同一目录下）

**Comment by stupidrocket** [comment]
> > @CVHub520 您好，我发现所有图片ocr识别后都会闪退，该bug应该与图片无关，因为ppocr识别的json已生成，重新打开app，再点击由ppocr生成了json的图片都会闪退，json文件已通过邮箱发送
> 
> 您好，非常抱歉，我刚尝试了很多图片，发现都能完美运行。可能由以下几个原因导致：
> 
> 1. 测试图片格式有问题；（可以先尝试下[demo](https://github.com/CVHub520/X-AnyLabeling/tree/main/assets/examples/ocr)图片，不要修改保存路径，正常运行获取结果后再重新加载看看还会不会闪退）
> 2. 识别框超出边界；（这个可能需要麻烦你将图片打包一份给我）
> 3. 存放路径设置有问题；（根据您提供的 `*.json` 文件中 `imagePath` 字段的内容，您需要将 json 文件和图片文件存放在同一目录下）

1.测试图片也会报错
2.可排除
3.json都自动保存在图片同一路径下

我改了canvas文件的856-878行的代码（坐标加int()），发现之后都能正常识别和加载json文件了，demo图片也可正常识别。
![CB172323-5F74-4FD4-B0A9-888345E019DB](https://github.com/CVHub520/X-AnyLabeling/assets/55740635/402c65c7-1afe-4d44-bc86-c0462cc858aa)

**Comment by CVHub520** [comment]
> > > @CVHub520 您好，我发现所有图片ocr识别后都会闪退，该bug应该与图片无关，因为ppocr识别的json已生成，重新打开app，再点击由ppocr生成了json的图片都会闪退，json文件已通过邮箱发送
> > 
> > 
> > 您好，非常抱歉，我刚尝试了很多图片，发现都能完美运行。可能由以下几个原因导致：
> > 
> > 1. 测试图片格式有问题；（可以先尝试下[demo](https://github.com/CVHub520/X-AnyLabeling/tree/main/assets/examples/ocr)图片，不要修改保存路径，正常运行获取结果后再重新加载看看还会不会闪退）
> > 2. 识别框超出边界；（这个可能需要麻烦你将图片打包一份给我）
> > 3. 存放路径设置有问题；（根据您提供的 `*.json` 文件中 `imagePath` 字段的内容，您需要将 json 文件和图片文件存放在同一目录下）
> 
> 1.测试图片也会报错 2.可排除 3.json都自动保存在图片同一路径下
> 
> 我改了canvas文件的856-878行的代码（坐标加int()），发现之后都能正常识别和加载json文件了，demo图片也可正常识别。 ![CB172323-5F74-4FD4-B0A9-888345E019DB](https://user-images.githubusercontent.com/55740635/267976114-402c65c7-1afe-4d44-bc86-c0462cc858aa.png)

感谢您提供宝贵的反馈意见及修复建议。
