### ISSUE TITLE
需要部署到用户电脑,如何自定义模型目录

### ISSUE THREAD

**Issue by monkeycc** [CVHub520/X-AnyLabeling#580]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

需要部署到用户电脑

如何自定义模型目录

用户电脑访问不到GitHub

用户小白
不会自己去下载模型 放哪个文件夹

用户C盘空间有限，不能默认放C盘

用户只会标注

----------

如何修改默认的C盘用户模型地址
C:\Users\xxx\xanylabeling_data\models

**Comment by CVHub520** [comment]
You can refer this [docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md#%E6%A8%A1%E5%9E%8B%E5%8A%A0%E8%BD%BD).
