### ISSUE TITLE
"Can the size of the functionality area on the right side be adjusted?"

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#581]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

![image](https://github.com/user-attachments/assets/c2e8b8dd-f8b1-46ec-9aba-9184dd60b796)
"As shown in the image, when I rotate my monitor vertically, the functionality area on the right side takes up most of the screen space, reducing the area available for displaying and working with images. Is it possible to set it so that the size can be adjusted by dragging?"

### Use case

"Or could it be implemented like in the video, where the functionality area can be shown or hidden by clicking, similar to a drawer-style interface?"

https://github.com/user-attachments/assets/2934882f-572e-4da8-8088-ea2347200bc1

"Of course, if it's possible to have certain areas float outside the main interface, like in Photoshop, that would be great too. For example, if this functionality area is frequently used, it could be floated separately while the other parts of the interface are hidden. As shown in the picture."

https://github.com/user-attachments/assets/33f47c40-aaa2-47f1-ab99-3b88d79c3f0f

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lhj5426** [comment]
"Whether it's making the fixed right-side toolbar resizable, allowing it to be hidden, or enabling parts of the workspace to float independently, all of these options would greatly improve the effective use of screen space. Currently, it's too cramped. Could you please consider this? Thank you."

**Comment by CVHub520** [comment]
Thank you for your valuable feedback and suggestions on enhancing the workspace. 

We understand the importance of optimizing screen space for a more efficient user experience. At this time, we are unable to commit to the features you’ve mentioned, such as making the right-side toolbar resizable, allowing it to be hidden, or enabling parts of the workspace to float independently. 

We are continuously evaluating our product roadmap, but these specific changes are not currently on our immediate support plan. We appreciate your patience and will keep your suggestions in mind for future development. 

Thank you for your understandin

**Comment by lhj5426** [comment]
"Looking forward to a promising future."
