### ISSUE TITLE
How to import txt format pose Estimation annotations into X-anylabeling?

### ISSUE THREAD

**Issue by ddongcui** [CVHub520/X-AnyLabeling#582]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

How to import txt format pose Estimation annotations into X-anylabeling? my txt file and yaml file look like below :
txt: 0 0.87588 0.69697 0.128521 0.121212 0.871705 0.712841
yaml:has_visible: false
classes:
  women:
    - noose
  man:
    - noose
When I import txt file into X-anylabeling ,it throw an error 
![1723607151481](https://github.com/user-attachments/assets/0642bead-36af-4e82-aca1-fdc4bf53e18c)

**Comment by CVHub520** [comment]
Hi @ddongcui 👋,

Thank you for reporting this issue. To assist you further, could you please provide the yaml file along with the corresponding images and the txt annotations? This will help us investigate the problem in more detail.

Kindly send the requested files to our designated 📨: [cv_hub@163.com](mailto:cv_hub@163.com).

Thank you for your cooperation!

Best regards,
CVHub Maintainer

**Comment by CVHub520** [comment]
This issue has been fixed. You can now pull the updated source code from the repository. @ddongcui
