### ISSUE TITLE
In the Sam-med2d model, when clicking on a point on the image with the mouse, the obtained point is used as the pass parameter for the prompt. Where can I obtain the response of this mouse click point?

### ISSUE THREAD

**Issue by AImagicAI** [CVHub520/X-AnyLabeling#584]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

In the Sam-med2d model, when clicking on a point on the image with the mouse, the obtained point is used as the pass parameter for the prompt. Where can I obtain the response of this mouse click point?

**Comment by CVHub520** [comment]
👋 Hi @AImagicAI, thank you for reaching out regarding the Sam-med2d model in X-AnyLabeling!

I understand you're looking to obtain the response of the mouse click point when interacting with the image in the Sam-med2d model. The specific line you've referenced in the `sam_med2d.py` file is a good starting point.

To capture the response of the mouse click point, you'll want to look into the event handling mechanism that processes the mouse click event. Typically, this involves a callback function that is triggered when a mouse click occurs on the image.

For more detailed guidance, please refer to the following section of the code:
[Link to the relevant code snippet](https://github.com/CVHub520/X-AnyLabeling/blob/298a6c016764ea64693ffe8d4a2b2a6037e27c5a/anylabeling/services/auto_labeling/sam_med2d.py#L272)

If you need further assistance or have trouble locating the callback function, feel free to ask for more help. We're here to support you! 🌟

**Comment by AImagicAI** [comment]
@CVHub520 ，
![2024-08-15_13-47-41](https://github.com/user-attachments/assets/7e31c623-b017-49b6-bc28-e4716b166149)
I can get prompts (points, labels) here, and I fix these two values, for example: [10,10] [1]. But each time, it is still necessary to click on the points obtained from the event with the mouse to perform automatic annotation work.
How can we avoid relying on mouse clicks? Similar to YOLO's batch automatic annotation? Thank you for your answer!
