### ISSUE TITLE
X-AnyLabeling运行时提升缺少xcb库——qt.qpa.plugin: Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by Mr-MoNET** [CVHub520/X-AnyLabeling#586]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Install

### Bug

我在安装X-AnyLabeling的时候发现了一个bug，即运行python anylabeling/app.py；提示了以下的错误信息：

QObject::moveToThread: Current thread (0x557d2ffe4400) is not the object's thread (0x557d30751de0).
Cannot move to target thread (0x557d2ffe4400)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/cv/anaconda3/envs/darknet/lib/python3.6/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

![fbdd7e17c929bed737d1665cdf5a275](https://github.com/user-attachments/assets/2b99a268-7259-487d-bb59-13e79bb8e743)

这个问题主要是pyqt5版本问题造成了，此外我在安装QT Creator时也遇到过类似的问题；解决这个问题很简单，将pyqt5卸载后重装指定版本的即可，不需要重装conda虚拟环境。
直接卸载掉原来旧的pyqt5，然后输入命令“pip install pyqt5==5.12”；重装对应版本的pyqt5后，即可解决问题
参考链接：[https://blog.csdn.net/threestooegs/article/details/124424434](url)

### Information

APP Version：2.4.0
CUDA : 12.1
架构：linux-x86

Tips：对于cuda版本在12.x的设备，在安装onnxruntime时不能只是简单地“pip install onnxruntime”，否则会因为缺少相应依赖文件造成使用AI推理时发生onnxruntime的相关错误；需要参照[https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md](url)的内容。
使用`pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/安装onnxruntime`；否则无法使用AI推理的功能! ! !

### Link to a Reproducible Demonstration Video

![fbdd7e17c929bed737d1665cdf5a275](https://github.com/user-attachments/assets/cdf077f7-faef-4f32-b180-096410522ece)

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hello @Mr-MoNET,

Thank you for bringing this to our attention. We appreciate your detailed report regarding the missing xcb library issue when running X-AnyLabeling.

**Comment by ZJDATY** [comment]
@Mr-MoNET  我也是这个问题，但我不觉得是版本的问题，pyqt5都更新了那么多版本，如果是版本bug，应该早就有人反馈修复了。我觉得大概率还是某些库的依赖出了问题，可能库文件的查找路径不对？降版本只能说是规避环境依赖出错的问题，而不是彻底解决其根源的正确途径。我已经遇到了不少，系统环境里有这个依赖库文件，conda环境或是python环境也存在这个库文件，二者版本不同，应用启动时调错了依赖库，导致能找到依赖库却打不开应用。以上是我浅显的分析，欢迎一起讨论，探寻根源的问题。
