### ISSUE TITLE
导出为coco分割时，我可以自己定义group ID吗

### ISSUE THREAD

**Issue by coptersack** [CVHub520/X-AnyLabeling#589]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

感谢您的工作，我现在想用您的工具在图像上对多目标追踪和分割进行标记，但是好像现在暂时不支持MOTS的导出，只支持MOT，我现在的做法是每一帧图像导出为coco分割，但是这样的话标记时赋予的group id就不能自己定义了，只能默认的从小到大，帧与帧之间的同一个目标就对应不上，所以coco分割中的annotations的id可以自定义吗，或者MOTS的导出能更新支持吗？

**Comment by CVHub520** [comment]
> ### Search before asking
> * [x]  I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.
> 
> ### Question
> 感谢您的工作，我现在想用您的工具在图像上对多目标追踪和分割进行标记，但是好像现在暂时不支持MOTS的导出，只支持MOT，我现在的做法是每一帧图像导出为coco分割，但是这样的话标记时赋予的group id就不能自己定义了，只能默认的从小到大，帧与帧之间的同一个目标就对应不上，所以coco分割中的annotations的id可以自定义吗，或者MOTS的导出能更新支持吗？
> 
> ### Additional
> _No response_

Hi! @coptersack,

Can you show me an example about MOTS?

**Comment by coptersack** [comment]
每一行的具体字段如下（以空格分隔）：

Frame: 帧序号，表示该实例所在的帧数。
Object ID: 实例的唯一标识符，每个物体在不同的帧中都应该有相同的ID。
Class: 物体类别的标签（如 Car、Pedestrian 等）。
Visibility: 物体的可见性比例（从0到1），表示物体的可见部分占整个物体的比例。
BBox Left: 边界框的左上角 x 坐标。
BBox Top: 边界框的左上角 y 坐标。
BBox Right: 边界框的右下角 x 坐标。
BBox Bottom: 边界框的右下角 y 坐标。
Mask RLE: 分割掩码的 Run-Length Encoding (RLE) 编码。这个字段表示物体在图像中的像素掩码。
示例标签行：`0  1  Car  1.0  50  200  180  350  2 500 500 110000 110000 11110000`
0: 表示第0帧。
1: 物体的ID是1。
Car: 类别是Car。
1.0: 物体完全可见。
50, 200: 边界框左上角的坐标 (x=50, y=200)。
180, 350: 边界框右下角的坐标 (x=180, y=350)。
2 500 500 110000 110000 11110000: 分割掩码的 RLE 编码，表示物体的像素位置。

**Comment by CVHub520** [comment]
> 每一行的具体字段如下（以空格分隔）：
> 
> Frame: 帧序号，表示该实例所在的帧数。 Object ID: 实例的唯一标识符，每个物体在不同的帧中都应该有相同的ID。 Class: 物体类别的标签（如 Car、Pedestrian 等）。 Visibility: 物体的可见性比例（从0到1），表示物体的可见部分占整个物体的比例。 BBox Left: 边界框的左上角 x 坐标。 BBox Top: 边界框的左上角 y 坐标。 BBox Right: 边界框的右下角 x 坐标。 BBox Bottom: 边界框的右下角 y 坐标。 Mask RLE: 分割掩码的 Run-Length Encoding (RLE) 编码。这个字段表示物体在图像中的像素掩码。 示例标签行：`0 1 Car 1.0 50 200 180 350 2 500 500 110000 110000 11110000` 0: 表示第0帧。 1: 物体的ID是1。 Car: 类别是Car。 1.0: 物体完全可见。 50, 200: 边界框左上角的坐标 (x=50, y=200)。 180, 350: 边界框右下角的坐标 (x=180, y=350)。 2 500 500 110000 110000 11110000: 分割掩码的 RLE 编码，表示物体的像素位置。

您好，感谢分享。我这边查阅了关于 [MOTS](https://motchallenge.net/data/MOTS/) 的相关定义，从官方提供的[数据集标签](https://motchallenge.net/data/MOTSLabels.zip)定义来看，似乎与你的分享有所出入，请问中间时候有哪个环节没对齐？

```
time_frame，id，class_id，img_height，img_width，rle
# example
1 2029 2 1080 1920 kWn[19ZQ1;I0C>000000000000O13M5K2N00001O001O00001O1O005Df`b0
这代表着第 1 帧，目标 id 为 2029（分类 id 为 2，即行人；实例 id 为 29），图片大小为 1080*1920。
```

[MOTSLabels.zip](https://github.com/user-attachments/files/16670637/MOTSLabels.zip)

**Comment by coptersack** [comment]
> > 每一行的具体字段如下（以空格分隔）：
> > Frame: 帧序号，表示该实例所在的帧数。 Object ID: 实例的唯一标识符，每个物体在不同的帧中都应该有相同的ID。 Class: 物体类别的标签（如 Car、Pedestrian 等）。 Visibility: 物体的可见性比例（从0到1），表示物体的可见部分占整个物体的比例。 BBox Left: 边界框的左上角 x 坐标。 BBox Top: 边界框的左上角 y 坐标。 BBox Right: 边界框的右下角 x 坐标。 BBox Bottom: 边界框的右下角 y 坐标。 Mask RLE: 分割掩码的 Run-Length Encoding (RLE) 编码。这个字段表示物体在图像中的像素掩码。 示例标签行：`0 1 Car 1.0 50 200 180 350 2 500 500 110000 110000 11110000` 0: 表示第0帧。 1: 物体的ID是1。 Car: 类别是Car。 1.0: 物体完全可见。 50, 200: 边界框左上角的坐标 (x=50, y=200)。 180, 350: 边界框右下角的坐标 (x=180, y=350)。 2 500 500 110000 110000 11110000: 分割掩码的 RLE 编码，表示物体的像素位置。
> 
> 您好，感谢分享。我这边查阅了关于 [MOTS](https://motchallenge.net/data/MOTS/) 的相关定义，从官方提供的[数据集标签](https://motchallenge.net/data/MOTSLabels.zip)定义来看，似乎与你的分享有所出入，请问中间是否有哪个环节有出入？
> 
> ```
> time_frame，id，class_id，img_height，img_width，rle
> # example
> 1 2029 2 1080 1920 kWn[19ZQ1;I0C>000000000000O13M5K2N00001O001O00001O1O005Df`b0
> 这代表着第 1 帧，目标 id 为 2029（分类 id 为 2，即行人；实例 id 为 29），图片大小为 1080*1920。
> ```
> 
> [MOTSLabels.zip](https://github.com/user-attachments/files/16670637/MOTSLabels.zip)

我刚刚也仔细看了看，是我混淆了，所以我的问题是我在转而用coco标记实例分割时，每个实例的ID我似乎不能自行定义，这样就无法追踪每个个体，我知道上面的mots可能短时间也不能实现，那coco分割的annotations的ID可以在标记时就确定吗

**Comment by CVHub520** [comment]
https://github.com/CVHub520/X-AnyLabeling/blob/078148eb6a738193cbd7cfcdfcab886ee29f1051/anylabeling/views/labeling/label_converter.py#L1121-L1130

您好，可以在这里添加多一个字段即可：
```python
                annotation = {
                    "id": annotation_id,
                    "image_id": image_id,
                    "category_id": class_id + 1,
                    "bbox": bbox,
                    "area": area,
                    "iscrowd": 0,
                    "ignore": int(difficult),
                    "track_id": int(shape["group_id"]) if shape["group_id"] else -1
                    "segmentation": segmentation,
                }

```

**Comment by coptersack** [comment]
我超，太感谢了，还更新了MOTS部分，您辛苦了

**Comment by coptersack** [comment]
在使用您更新完之后的MOTS标记后发现记录了分割的点，但是没有转为RLE编码，这是我测试的结果
[custom_gt.txt](https://github.com/user-attachments/files/16685352/custom_gt.txt)

**Comment by CVHub520** [comment]
您好，是的，因为需要依赖到`pycocotools`库，你这边可以参考下[这里](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#46-mot%E6%A0%87%E7%AD%BE)。

![image](https://github.com/user-attachments/assets/69e468fa-e1c8-41fd-9e60-d877be1125e5)
