### ISSUE TITLE
建议和bug反馈

### ISSUE THREAD

**Issue by kiitio** [CVHub520/X-AnyLabeling#59]
非常感谢分享，以下是我在使用时发现的一些问题
建议：
1.有考虑更新根据个人训练的模型进行自动标注的功能吗，例如使用yolov5训练的xxx.pt格式的模型文件进行批量自动标注，
2.希望还是将标注数据集格式转换集成到软件当中，或者另外提供一个转换程序来实现，这样便利性提升真的很明显，我发现当前的很多自动标注功能的软件，它们通常是自动标注后导出的数据集格式仅仅是当前软件能打开的格式，但是无法进行训练，还需要进行额外的格式转换，而软件本身却并有没有提供这种转换功能，这就导致了因为无法使用导出后的数据集进行训练，所以自动标注这个功能就变成了摆设
bug：
1.自动标注的选择框为灰色无法选定，需要软件重启才能解决
   复现流程：
       1.打开软件随便指定一个图片文件夹，然后选择自动标注
       2.将自动标注的下拉框选择加载自定义模型，选择一个非列表提供的以.yaml结尾的文件，会提示加载自定义模型时出错
       3.此时点击自动标注右侧的红色❌号关闭自动标注，然后再点击自动标注按钮打开自动标注，会发现自动标注下拉框无法选择

**Comment by CVHub520** [comment]
您好， @kiitio 感谢你的建议和反馈。针对您提到的几点问题现逐一回复如下：
1. 目前 `X-AnyLabeling` 是支持将 `yolov5` 训练的模型文件进行自动标注的，但需要转换成 `onnx` 文件，然后根据提供的 `xxx.yaml` 文件配置修改相应的超参数即可；如果是修改了原始的网络结构，可以自行适配下，只需要按照[帮助文档](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/Q%26A.md)中的**如何支持自定义模型？**章节进行适配即可。
2. 考虑到每个人需要的训练格式各异，所以当前是设计成统一的 `*.json` 文件格式。如果需要集成到软件中自行自动格式转换一来是很难照顾到所有人的需求，二来是需要考虑很多 corner-case，稍微格式不一致便容易引起闪退，所以这适配流程是有点繁琐的，目前暂无多余精力开发，后续可以兼容下，同时也欢迎有兴趣的同学多提交PR，一起造福社区。此外，`X-AnyLabeling`目前是有提供一个转换脚本来实现这个从自定义格式到常规训练格式的转换的，可以参考上述帮助文档中的**标签转换**章节。
3. 关于您提到的 `bug` 问题，这个加载自定义模型时出错的原因千奇百怪，最直接的方法便是源码运行程序查看具体的报错信息再尝试解决，如解决不了可将信息贴上来一起交流下，或者直接将您的模型权重和配置文件打包发送到邮箱 cv_hub@163.com，这边抽空可以帮你排查下问题。

**Comment by kiitio** [comment]
> 您好，@kiitio感谢您的建议和反馈。针对您提到的要点问题，现逐一回复如下：
> 
> 1. 目前`X-AnyLabeling`是支持将`yolov5`训练的模型文件进行自动标注的，但需要转换成`onnx`文件，然后根据提供的`xxx.yaml`文件配置修改相应的超参数即可；如果是修改了原始的网络结构，可以自行适配下，只需要按照[帮助文档](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/Q%26A.md)中的**如何支持自定义模型？**章节进行装备即可。
> 2. 考虑到每个人需要的训练格式各不相同，所以当前是设计成统一的`*.json`文件格式。如果需要集成到软件中自动格式转换则很难满足到所有人的需求，其次是需要考虑很多角落-case，桥梁格式不一致的话很容易引起闪退，所以这个改装流程是有点繁琐的，目前暂无多余精力开发，后续可以兼容下，同时也欢迎有兴趣的同学多提交PR，一起造福社区。 ，`X-AnyLabeling`目前提供了一个转换脚本来实现从自定义格式到常规训练格式的转换，可以参考上述帮助文档中的**标签转换**章节。
> 3. 关于您提到的`bug`问题，这个加载自定义模型时出错的原因千奇百怪，最直接的方法就是源码运行程序查看具体的报错信息再尝试解决，如无法解决可将信息贴上来一起交流下，或者直接将您的模型权限重和配置文件文件夹发送到邮箱[cv_hub@163.com](mailto:cv_hub@163.com)，草莓抽空可以帮助排查下问题。

好的
