### ISSUE TITLE
When performing batch inference, existing labels will not be retained.

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#590]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

"After I perform inference with YOLOv8 for either horizontal rectangles or rotated rectangles, I want to retain the existing labels when running additional batch inferences. For example, after batch inference for horizontal rectangles, I want to retain those labels while running batch inference for rotated rectangles. Alternatively, after batch inference for rotated rectangles, I want to retain those labels while running batch inference for horizontal rectangles. Currently, even if I enable the setting to retain existing labels, it does not take effect during batch inference. The labels are only retained when I manually run inference for a single page. Is it possible to retain existing labels during batch inference as well?"

![image](https://github.com/user-attachments/assets/dffb02c3-0a48-4c1b-ae44-90be23f5d3b8)

**Comment by lhj5426** [comment]
"I have hundreds, even thousands of pages of images that need to be processed using two models for both horizontal and rotated rectangle inference. Currently, I can only perform single-page inference one page at a time, which is very frustrating and cumbersome."

**Comment by lhj5426** [comment]
https://github.com/user-attachments/assets/89809fce-ea4c-4e80-9719-5aca4efd781c

"After performing single-page recognition, the edges of the rectangles are extremely thin—almost invisible to the naked eye. I have to switch to the previous or next page and then switch back for the border thickness to match the set thickness. This seems like a bug, right? It really affects the user experience. Every time after pressing the single recognition button, I have to quickly switch between pages to restore the rectangle borders to the correct thickness; otherwise, they are completely invisible."

"Or is there a place where I can adjust the thickness of the rectangle borders immediately after recognition?"

**Comment by lhj5426** [comment]
"The current user experience is really poor."

**Comment by CVHub520** [comment]
Hey there! @lhj5426,

We apologize for the inconvenience you’ve experienced with the current user experience. We take your feedback very seriously and will be re-evaluating the user interface and overall experience to identify areas for improvement. 

Thank you for bringing this to our attention.

**Comment by CVHub520** [comment]
Hi, @lhj5426, 

> "After performing single-page recognition, the edges of the rectangles are extremely thin—almost invisible to the naked eye. I have to switch to the previous or next page and then switch back for the border thickness to match the set thickness. This seems like a bug, right? It really affects the user experience. Every time after pressing the single recognition button, I have to quickly switch between pages to restore the rectangle borders to the correct thickness; otherwise, they are completely invisible."

I’m pleased to inform you that this issue has already been addressed and fixed. 🐛🔧 The latest update should resolve the problem with the rectangle borders not displaying at the correct thickness after performing single-page recognition.

Btw, I’ve acknowledged the another issue you’ve reported and have added it to our list of things to address. I will carve out some time to delve into this problem and ensure it’s properly fixed.

**Comment by CVHub520** [comment]
@lhj5426, Hello, the below issue  you provided has been addressed and fixed now.

>"After I perform inference with YOLOv8 for either horizontal rectangles or rotated rectangles, I want to retain the existing labels when running additional batch inferences. For example, after batch inference for horizontal rectangles, I want to retain those labels while running batch inference for rotated rectangles. Alternatively, after batch inference for rotated rectangles, I want to retain those labels while running batch inference for horizontal rectangles. Currently, even if I enable the setting to retain existing labels, it does not take effect during batch inference. The labels are only retained when I manually run inference for a single page. Is it possible to retain existing labels during batch inference as well?"

To ensure that you can use this fixed feature, please make sure you are using the latest version of the software via `git pull origin main`. 

If you need further assistance or have any additional questions, feel free to reach out. I'm here to help! 😄

**Comment by lhj5426** [comment]
https://github.com/user-attachments/assets/bed23cc1-21f9-475d-bc08-642c284102a4

Thank you very much.

The issue of narrow borders after rectangle recognition has been confirmed fixed. I hope the problem with retaining tags can be resolved soon as well.

**Comment by lhj5426** [comment]
"No, that's not correct. After testing, it has been confirmed that the issue of different types of rectangular tags not being retained during batch runs of different models has been fixed. Thank you very much."

https://github.com/user-attachments/assets/ba83e8b8-824f-4809-a506-a2ec6f4b9dd3

Thank you very much for your work. Both mentioned issues have been resolved.
