### ISSUE TITLE
AttributeError for "set_auto_labeling_preserve_existing_annotations_state" in SegmentAnything and SegmentAnything2

### ISSUE THREAD

**Issue by jiangzhiwei2018** [CVHub520/X-AnyLabeling#593]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

User Interface (UI)

### Bug

1. I clone the latest version repo use `git clone https://github.com/CVHub520/X-AnyLabeling.git`
2.  Installed by [QuickStart Guides](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/get_started.md)
3.  run `python anylabeling/app.py`

Then I download AI Model (`segment_anything_2`) by UI, the window crashes. error messages show:
```shell
File "/home/user/software/X-AnyLabeling/./anylabeling/services/auto_labeling/model_manager.py", line 1580, in set_auto_labeling_preserve_existing_annotations_state
    self.loaded_model_config[
AttributeError: 'SegmentAnything2' object has no attribute 'set_auto_labeling_preserve_existing_annotations_state'
Aborted (core dumped)
```
 And I tried other models like `segment_anything`, `yolo`. `yolo` model load well, `segment_anything` also caused the window crash. 
```shell
File "/home/user/software/X-AnyLabeling/./anylabeling/services/auto_labeling/model_manager.py", line 1580, in set_auto_labeling_preserve_existing_annotations_state
    self.loaded_model_config[
AttributeError: 'SegmentAnything' object has no attribute 'set_auto_labeling_preserve_existing_annotations_state'
Aborted (core dumped)
```

-------------------------------------
I tried to find out what happens.
1. search `set_auto_labeling_preserve_existing_annotations_state` in folder `anylabeling/services/auto_labeling`
```shell
/home/user/software/X-AnyLabeling/anylabeling/services/auto_labeling/__base__/yolo.py
  197,9:     def set_auto_labeling_preserve_existing_annotations_state(self, state):

/home/user/software/X-AnyLabeling/anylabeling/services/auto_labeling/clrnet.py
  86,9:     def set_auto_labeling_preserve_existing_annotations_state(self, state):

/home/user/software/X-AnyLabeling/anylabeling/services/auto_labeling/damo_yolo.py
  75,9:     def set_auto_labeling_preserve_existing_annotations_state(self, state):

/home/user/software/X-AnyLabeling/anylabeling/services/auto_labeling/grounding_dino.py
  81,9:     def set_auto_labeling_preserve_existing_annotations_state(self, state):

/home/user/software/X-AnyLabeling/anylabeling/services/auto_labeling/model_manager.py
  1574,9:     def set_auto_labeling_preserve_existing_annotations_state(self, state):
  1582,15:             ].set_auto_labeling_preserve_existing_annotations_state(state)

/home/user/software/X-AnyLabeling/anylabeling/services/auto_labeling/rtdetr.py
  64,9:     def set_auto_labeling_preserve_existing_annotations_state(self, state):

/home/user/software/X-AnyLabeling/anylabeling/services/auto_labeling/rtdetrv2.py
  64,9:     def set_auto_labeling_preserve_existing_annotations_state(self, state):

/home/user/software/X-AnyLabeling/anylabeling/services/auto_labeling/yolo_nas.py
  286,9:     def set_auto_labeling_preserve_existing_annotations_state(self, state):

/home/user/software/X-AnyLabeling/anylabeling/services/auto_labeling/yolov5_obb.py
  79,9:     def set_auto_labeling_preserve_existing_annotations_state(self, state):

/home/user/software/X-AnyLabeling/anylabeling/services/auto_labeling/yolox.py
  73,9:     def set_auto_labeling_preserve_existing_annotations_state(self, state):
```

so I thought `def set_auto_labeling_preserve_existing_annotations_state(self, state):`  is missing in SAM class?

### Information

Application Information:
{'App name': 'X-AnyLabeling', 'App version': '2.4.0', 'Device': 'GPU'}

System Information:
{ 'CPU': 'x86_64',
  'CUDA': 'V11.8.89',
  'GPU': '0, NVIDIA GeForce RTX 3050 Ti Laptop GPU, 4096',
  'Operating System': 'Linux-5.15.0-117-generic-x86_64-with-glibc2.17',
  'Python Version': '3.8.19'}

Package Information:
{ 'ONNX Runtime GPU Version': '1.18.1',
  'ONNX Runtime Version': '1.19.0',
  'ONNX Version': '1.16.2',
  'OpenCV Contrib Python Headless Version': '4.10.0.84',
  'PyQt5 Version': '5.15.7'
}

### Link to a Reproducible Demonstration Video

1. I clone the latest version repo use `git clone https://github.com/CVHub520/X-AnyLabeling.git`
2.  Installed by [QuickStart Guides](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/get_started.md)
3.  run `python anylabeling/app.py`
4. select AI model `Segment Anythng 2 (base)` or `Segment Anythng  (VIT-base Quant)` or  any other SAM model.

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hi, @jiangzhiwei2018:

Thank you for bringing this to our attention. Don’t worry, it’s not a big deal; I’ll fix it later.

**Comment by CVHub520** [comment]
Hi there, the issue has been fixed. You can now pull the updated source code.

**Comment by jiangzhiwei2018** [comment]
@CVHub520 Thanks for [bug fixed], I will try it.
