### ISSUE TITLE
An error occurs after viewing several hundred or several thousand images

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#594]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/9b850553-9f40-479a-96b1-2477ecc65a12)
Hello, as shown in the image, when I'm viewing a few hundred or even a few thousand images, sometimes the error occurs even after viewing just a few dozen large images. Could this be due to the software not releasing memory properly? This error has existed in previous versions as well, but today it’s really frustrating, so I decided to ask about it.

I asked AI, and it suggested increasing my memory. However, without adding more physical memory to my computer, how can I do my best to avoid this issue? It happens several times a day, and it's really annoying.

**Comment by CVHub520** [comment]
Thank you for reaching out and providing details about the issue you’re experiencing. To better understand and diagnose the problem, could you please send me the error image along with the corresponding label files? You can send them to the following email address: cv_hub@163.com.

**Comment by lhj5426** [comment]
> Thank you for reaching out and providing details about the issue you’re experiencing. To better understand and diagnose the problem, could you please send me the error image along with the corresponding label files? You can send them to the following email address: [cv_hub@163.com](mailto:cv_hub@163.com)。-----------谷歌翻译-----------感谢您与我们联系并提供有关您遇到的问题的详细信息。为了更好地理解和诊断问题，您能否将错误图像以及相应的标签文件发送给我？您可以将它们发送到以下电子邮件地址：cv_hub@163.com。

When reviewing and annotating hundreds or even thousands of images, the software randomly crashes. This issue also causes the computer to become unresponsive, and the only solution is to restart the software, or in the worst case, restart the entire computer. After restarting, reopening the previously problematic images works fine, so this isn't an issue with a specific image or annotation. Instead, the problem occurs randomly

**Comment by lhj5426** [comment]
My current approach is to close and reopen the software after reviewing and annotating each comic. I'm not sure if this can prevent crashes. When working on a single comic with hundreds of pages, I close and reopen the software every 100 to 200 pages.

I hope that by closing the software each time, I can release the memory it occupies and restart it to avoid random crashes caused by insufficient memory.

**Comment by ClemSc** [comment]
Hello,

I also have this issue. When working on a folder of pictures, each time a new picture is viewed, it is loaded in memory, but is never released, see attached video. So the program will crash once the RAM is full.  It should be easy to fix, by simply closing the last picture when moving to the next one. Or at least keep only a limited number of pictures in buffer.

https://github.com/user-attachments/assets/2c71a18e-5a8a-4f30-ba80-7e5ace28cc32

**Comment by lhj5426** [comment]
> Hello,-----------谷歌翻译-----------你好，
> 
> I also have this issue. When working on a folder of _picture_s, each time a new _picture_ is viewed, it is loaded in memory, but is never _release_d, see attached video. So the program will crash once the RAM is full. It should be easy to fix, by simply closing the last _picture_ when moving to the next one. Or at least keep only a limited number of _picture_s in buffer.-----------谷歌翻译-----------我也有这个问题。处理图片文件夹时，每次查看新图片时，都会将其加载到内存中，但永远不会释放，请参阅随附的_视频_。所以一旦RAM满了程序就会崩溃。它应该很容易修复，只需在移动到下一张图片时关闭最后一张图片即可。或者至少在缓冲区中只保留有限数量的图片。
> 
>  memory_leak_demo._mp4_

The issue is that when I close a folder, the memory isn't being released. Currently, when I open a new image folder, the memory from the previous folder remains occupied and isn't freed up. If the memory is released when the folder is closed, it could be reloaded the next time a new folder is opened. However, as it stands, the memory usage keeps accumulating, which quickly fills up the memory and leads to crashes. Right now, I'm monitoring the memory usage, and when it gets close to full, I close and restart the software to free up the memory. It's only after a restart that the memory is actually released. I hope this issue can be fixed.

**Comment by ClemSc** [comment]
Yup, same here. I meant, the developers should fix the software so that it unload picture from the memory once this picture is no longer in view ;-). As a user, I also have to restart the software once the memory is full. And I am working on large picture, so it happens quite fast.

**Comment by CVHub520** [comment]
Hello @ClemSc and @lhj5426,

Thank you both for bringing this issue to our attention and for providing detailed reports on the memory management problem you’ve encountered. I understand how this can be frustrating, particularly when working with large image files, and I apologize for any inconvenience this may have caused.

Please be patient with us as my work on this fix. I will try to  address this issue as soon as I have a free window in my development schedule. I'm committed to improving the software and providing a smooth user experience for all our customers.

Thank you again for your feedback and support.

**Comment by CVHub520** [comment]
Fixed. @lhj5426 @ClemSc 

#549

**Comment by ClemSc** [comment]
Tested, it is fixed. Sweet ! Thanks a lot !
