### ISSUE TITLE
app was killed when auto label

### ISSUE THREAD

**Issue by zhoupan9109** [CVHub520/X-AnyLabeling#595]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

I use this app to auto labeling image, but app was killed when more than 2 thousands images have been labeled, which happening for servals times.

### Information

![image](https://github.com/user-attachments/assets/8c4e6050-b645-4799-82ff-2fc1a79e5e0d)

### Link to a Reproducible Demonstration Video

![image](https://github.com/user-attachments/assets/77175fe1-3cc4-483c-a575-84d5bfb74059)

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hi, @zhoupan9109, Could you please let us know which model you are currently using for the auto-labeling of images?

**Comment by zhoupan9109** [comment]
In the UI of APP, the model named YOLOv10l THUI-MIG

**Comment by CVHub520** [comment]
Hi, @zhoupan9109:

Thank you for your update and for testing the YOLOv10l THU-MIG model in our APP.

I’m glad to hear that everything is functioning properly after your tests. As a suggestion, to ensure the smooth operation of custom models, I recommend verifying that the input and output nodes of your custom model match those of the built-in models. You can easily do this by using a tool like Netron for model visualization.

If you encounter any issues or have further questions, please don’t hesitate to reach out.

![image](https://github.com/user-attachments/assets/535d1702-2cd0-469e-a234-48d325cc6cc3)
