### ISSUE TITLE
Can not export YOLO for the line?

### ISSUE THREAD

**Issue by mkygogo** [CVHub520/X-AnyLabeling#596]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

I draw line in the image, and try to export to YOLO data ,but the yolo .txt file always empty, how can I get the right yolo file?
![45ZXT99_RDAQ$R%O1@$IG0](https://github.com/user-attachments/assets/be4e8b67-dd88-436f-afee-977e5e813169)

**Comment by CVHub520** [comment]
Hello @mkygogo,

Thank you for reaching out regarding the export of YOLO format for lines. At present, the feature to directly export line shapes is not available. Could you please provide an example or share what the desired exported YOLO file should look like? This will help us better understand your needs.

**Comment by mkygogo** [comment]
In my project, it is necessary to detect which positions on the socket have been plugged in. Each socket position has a numerical label, and if plugged in, the numerical label for that position should be identified.
I tried to mark the label with rotation, it can export the YOLO labels, but I think mark with line will be more easy. 
I am not familiar with image recognition, and I am not very clear whether the YOLO model supports identification with lines.
![}KKPKK1JYGBBEHYE$QUHZWJ](https://github.com/user-attachments/assets/62910f15-addf-4647-9b48-0cad523078f5)

**Comment by CVHub520** [comment]
Hi, @mkygogo, thank you for your feedback.

You might want to first verify if the YOLO framework supports training with lines.
