### ISSUE TITLE
导出PPOCR标注未带label

### ISSUE THREAD

**Issue by phphappy** [CVHub520/X-AnyLabeling#598]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

导出标注时"transcription": ""显示为空，为什么没有带上label的名称？
我理解为应该是"transcription": "标注label"
具体示例如下：
./train/175dbd769cd7441e8fd58aef4f6b5d60.png_1.jpg	[{"transcription": "", "points": [[27, 120], [50, 72], [88, 46], [145, 28], [223, 27], [282, 49], [317, 76], [342, 124], [299, 123], [290, 98], [266, 81], [215, 68], [149, 63], [102, 79], [76, 101], [64, 125]], "difficult": false}, {"transcription": "", "points": [[89, 115], [277, 115], [277, 149], [89, 149]], "difficult": false}, {"transcription": "", "points": [[96, 199], [158, 216], [213, 214], [268, 198], [254, 157], [207, 171], [157, 169], [108, 160]], "difficult": false}]

**Comment by CVHub520** [comment]
Hi, @phphappy,

Could you please send your image along with the corresponding annotated JSON file to the email address: cv_hub@163.com? This will assist us in further debugging the issue.

**Comment by phphappy** [comment]
@CVHub520 email has been sent。

**Comment by CVHub520** [comment]
Based on the annotated file you provided, it appears that you are using a much earlier version. Please update to the latest version.

**Comment by phphappy** [comment]
@CVHub520 I downloaded a new version and exported ppocr, but it doesn't seem to work either。

**Comment by CVHub520** [comment]
@phphappy, Hello,

If you're looking to annotate OCR data, please follow the provided [instructions](https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/optical_character_recognition/text_recognition/README.md) for the annotation process.

In your case, it appears that you are not annotating an OCR task but rather filling in the text within bounding boxes. You can refer to the aforementioned tutorial for detailed steps. Should the current task not meet the data format you expect, you are welcome to parse the JSON script on your own to suit your needs.

**Comment by phphappy** [comment]
@CVHub520 Follow up, why is there no record of the four point annotation when exporting YOLO segment tags。
The export format is as follows：
0 0.07892174759644645 0.6586631957634721 0.02861952861952869 0.4533200841867304 0.11380877043527649 0.23540494537059628 0.3255648858058497 0.07825460487819189 0.5933025029410572 0.07092092232187967 0.8367003367003367 0.23540494537059628 0.9486633402296053 0.45646309099657845 0.9153989696158371 0.6911409327985689 0.810737901099347 0.6303761344748393 0.8131718794369397 0.4470340705670342 0.7466431382094033 0.33807650115896715 0.5868118940408098 0.24378629686352452 0.33367814693115905 0.24902464154660467 0.18114883777534382 0.3799832586236084 0.1543750760618231 0.5098942067639959 0.1787148594377511 0.6115180936157507

![image](https://github.com/user-attachments/assets/987c8143-5f9d-4e09-ad5b-9daf19422f6d)

**Comment by CVHub520** [comment]
> @CVHub520 Follow up, why is there no record of the four point annotation when exporting YOLO segment tags。 The export format is as follows： 0 0.07892174759644645 0.6586631957634721 0.02861952861952869 0.4533200841867304 0.11380877043527649 0.23540494537059628 0.3255648858058497 0.07825460487819189 0.5933025029410572 0.07092092232187967 0.8367003367003367 0.23540494537059628 0.9486633402296053 0.45646309099657845 0.9153989696158371 0.6911409327985689 0.810737901099347 0.6303761344748393 0.8131718794369397 0.4470340705670342 0.7466431382094033 0.33807650115896715 0.5868118940408098 0.24378629686352452 0.33367814693115905 0.24902464154660467 0.18114883777534382 0.3799832586236084 0.1543750760618231 0.5098942067639959 0.1787148594377511 0.6115180936157507
> 
> ![image](https://private-user-images.githubusercontent.com/2278180/362506117-987c8143-5f9d-4e09-ad5b-9daf19422f6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTc1ODEsIm5iZiI6MTcyNDg5NzI4MSwicGF0aCI6Ii8yMjc4MTgwLzM2MjUwNjExNy05ODdjODE0My01ZjlkLTRlMDktYWQ1Yi05ZGFmMTk0MjJmNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDIwODAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDg4NTdkMTM5ZmQwNzk5ZTI2MTkyNDU5NWUzYmNiYjA5MzQ1Yzc1NTQwY2JlNjY5Yjg0NWQxMTYwYTBkYTJhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5cu9vUi4jkUJjijAg5HG8l5n9RYKNNdiR096K8acDh0)

Please refer to the [official documentation](https://docs.ultralytics.com/zh/datasets/segment/#ultralytics-yolo-format) for more detailed information.

**Comment by phphappy** [comment]
@CVHub520 What I mean is why the annotation of the four point coordinates was not exported?
![1724898876793](https://github.com/user-attachments/assets/211eefe6-4f1f-42a1-80a8-717df76e7503)

**Comment by phphappy** [comment]
@CVHub520   is it judged based on 'shape_type' ? "shape_type": "polygon" can export ,  "shape_type": "rectangle" is not?

**Comment by CVHub520** [comment]
> @CVHub520 is it judged based on 'shape_type' ? "shape_type": "polygon" can export , "shape_type": "rectangle" is not?

Yes.

**Comment by CVHub520** [comment]
For more detail, you can refer [this func](https://github.com/CVHub520/X-AnyLabeling/blob/6a0b69f18a50ca07f83f19791160c22839061bdc/anylabeling/views/labeling/label_converter.py#L809).

**Comment by phphappy** [comment]
@CVHub520 thanks
