### ISSUE TITLE
线条序列标签要导出txt格式应该选哪个导出

### ISSUE THREAD

**Issue by YHao-o** [CVHub520/X-AnyLabeling#599]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

线条序列标签要导出txt格式应该选哪个导出

**Comment by CVHub520** [comment]
Duplicate of #596.
