### ISSUE TITLE
如何使用GPU

### ISSUE THREAD

**Issue by Chen94yue** [CVHub520/X-AnyLabeling#6]
如题

**Comment by CVHub520** [comment]
您好，可参考如下步骤：
1. 安装所需的 GPU 环境；
```bash
requirements-gpu.txt
```
2. 修改 ./anylabeling/app_info.py 文件：
```bash
...
__preferred_device__ = "GPU"  # GPU or CPU
```
3. 重新运行即可。

**Comment by CVHub520** [comment]
本版本基于 onnxruntime-gpu 1.14.0编译，CUDA和CuDNN适配版本参考官网[链接](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html)
