### ISSUE TITLE
请问如何添加自定义模型？

### ISSUE THREAD

**Issue by kiitio** [CVHub520/X-AnyLabeling#60]
你好，文档中的加载自定义模型描述我没有看懂
我训练的模型是.pt格式的，目前我已经将他转换为.onnx格式了
我按照文档中的步骤将模型文件放到指定目录
![image](https://github.com/CVHub520/X-AnyLabeling/assets/106864471/e0953154-d088-430b-a235-997907e2c0ad)
然后启动软件，但是在下拉框中没有发现“test”这一项
另外我还尝试了通过选择
![image](https://github.com/CVHub520/X-AnyLabeling/assets/106864471/f963340b-dc8f-4fcb-96b4-12c4cde535aa)
然后将文件夹内的模型文件替换为我自己训练的模型文件的方式尝试使用，但是我发现程序依然会自动下载模型文件，于是我将我的模型文件名称一并修改，虽然程序没有继续自动下载，但是点击运行并没有效果

**Comment by CVHub520** [comment]
您好，详情请参考 [custom_model.md](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md) 文档。

**Comment by kiitio** [comment]
> 您好，详情请参考[custom_model.md](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md)文档。

感谢您的回复，但是目前我仍然无法使用自定义模型实现自动标注

**Comment by kiitio** [comment]
> 您好，详情请参考[custom_model.md](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md)文档。

感谢您的回复，但我目前仍然无法使用自定义模型进行自动标注
我目前按照您最新提供的方式成功导入了自定义模型，但是我标注使用的是中文标签，我认为可能跟这个有关系，我首先使用yolov5的detect.py测试了模型可以正常进行标注，然后通过export.py将模型转换为onnx格式，最后进行导入，我发现导入后点击“运行”按钮后并没有出现标注框，为此我测试了多张图片但同样也是如此，我怀疑是yaml文件的编码问题，又将yaml中的编码全部替换为对应的汉字，但是替换后运行app.py报错提示gbk编码错误
![image](https://github.com/CVHub520/X-AnyLabeling/assets/106864471/d42d63b1-d641-4490-ba8f-08cff30d81d4)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/106864471/1d826f97-4aea-4355-9fd5-e3c9d74e4e2f)

**Comment by CVHub520** [comment]
您好，@kiitio ，麻烦将您的json文件（classes直接用中文就行）和权重文件（onnx）打个压缩包发送至邮箱：cv_hub@163.com，邮件主题：#60【bug排查】

**Comment by CVHub520** [comment]
您好，@kiitio ，这里默认的 stride 应该是 32 的整数倍才对，如果你没修改过原始结构的话，请设置为 32。改完后你可以保存文件后重新推理试试，或者发一张在服务端环境能够正常推理检测出结果的图片到指定邮箱给我。

**Comment by kiitio** [comment]
> 您好，@kiitio，这里默认的stride应该是32的整数倍才对，如果你没修改过原始结构的话，请设置为32。改完后你可以保存文件后重新推理尝试，或者在服务端能够环境发一张正常推理检测出结果的图片发送到指定邮箱给我。

感谢您的回复，是我将stride当作标签总数修改为34了，但是classes直接用中文启动app.py会报编码错误，用编码格式则可以正常启动，但是点击自动标注的运行按钮软件会闪退
![image](https://github.com/CVHub520/X-AnyLabeling/assets/106864471/75fd44fb-346b-46e6-b12d-5db4723a83b0)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/106864471/4605df4a-2cd1-4555-b338-b8f130173d6b)

**Comment by CVHub520** [comment]
@kiitio ，麻烦给一张测试图片和最新的yaml配置文件（带中文类别）发我下。

**Comment by kiitio** [comment]
> @kiitio，麻烦给一张测试图片和最新的yaml配置文件（带中文类别）发给我下。

已发送到邮箱

**Comment by CVHub520** [comment]
@kiitio 您好，已修复，请下载最新源码重新运行。另外，这个配置文件中 `classes`  字段请遵循以下格式，不要用字典格式：
```YAML
classes:
  - classA
  - classB
  - classC
  - ...
```

**Comment by kiitio** [comment]
> @kiitio您好，已修复，请下载最新源码重新运行。另外，此配置文件中`classes` 字段请遵循以下格式，不要用字典格式：
> 
> ```yaml
> classes:
>   - classA
>   - classB
>   - classC
>   - ...
> ```

好的，感谢您的回复
