### ISSUE TITLE
close the app and open it ,the models will be deleted and redownload, i has beend trouble me 3days  ,I downloaded the model locally, but the local model couldn't complete the markup and needed to be reloaded each time

### ISSUE THREAD

**Issue by junliuchengxia** [CVHub520/X-AnyLabeling#600]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

close the app and open it ,the models will be deleted and redownload, i has beend trouble me 3days  ,I downloaded the model locally, but the local model couldn't complete the markup and needed to be reloaded each time

### Information

close the app and open it ,the models will be deleted and redownload, i has beend trouble me 3days  ,I downloaded the model locally, but the local model couldn't complete the markup and needed to be reloaded each time

### Link to a Reproducible Demonstration Video

may day may day

### Execution Mode

Pre-compiled Executable

### Additional

sos 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hey there! @junliuchengxia,

Thank you for bringing this to our attention. Firstly, please check your local user directory to see if there are any third-party configuration files, such as `.anylabelingrc` or `anylabeling_data`. If these files exist, please consider deleting them and restarting the application, as they may be causing a conflict.
Typically, the models you have downloaded will be saved in the `anylabeling_data` directory within the current user's directory. You can check there. If you continue to experience issues, please provide the following additional information to help us troubleshoot:
1. Execute the command `python anylabeling/checks.py` and copy the output here.
2. Please inform us which model you downloaded that was deleted by the app.

**Comment by junliuchengxia** [comment]
well，I have solved this problem, the path cannot contain Chinese.
