### ISSUE TITLE
Is it possible to use Segment Anything v2 for video segmentation?

### ISSUE THREAD

**Issue by pythonzz0622** [CVHub520/X-AnyLabeling#602]
### Description

Thank you for your amazing project! 
I wanted to ask if it's possible to use Segment Anything v2 for video segmentation?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hi, @pythonzz0622 👏
Thanks for your interest in our project and for reaching out! 

As of now, Segment Anything v2 is not yet supported within X-AnyLabeling. However, you can integrate it into X-AnyLabeling via a http server for your video-related applications. 

Feel free to contribute a pull request if you have any improvements or new features in mind.

**Comment by CVHub520** [comment]
Hi! @pythonzz0622,

Thank you for your patient and for your interest in our project!

I’m excited to inform you that we have recently added support for video segmentation using Segment Anything v2. You can indeed use it for video segmentation tasks. 😄 

For detailed instructions on how to perform interactive video object segmentation, please refer to our [tutorial](https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/interactive_video_object_segmentation/README.md). This will guide you through the process step by step.

If you have any further questions or encounter any issues, please don’t hesitate to reach out. We’re here to help!

**Comment by sijieaaa** [comment]
Hi, 
It seems the video segmentation is not working well. I label the first frame, while the propagation to the successive frames is not working. 
I have also tried to use demo in Meta AI, it works instead.

**Comment by sijieaaa** [comment]
The first frame.
![image](https://github.com/user-attachments/assets/20735442-928e-4019-af92-b4421db3c2db)

Propagated second frame.
![image](https://github.com/user-attachments/assets/96cbee35-b900-4ad6-a904-4016428e2d28)

**Comment by pythonzz0622** [comment]
Wow,, Thank you for your fastest commit!!! 
I'm so exciting your contribute!
