### ISSUE TITLE
Can a shortcut key be added for merging rectangles?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#604]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

![image](https://github.com/user-attachments/assets/cc28c6f1-b946-4992-9a04-941a06871009)

Currently, the merging logic involves holding down CTRL and dragging to select everything. However, after selecting, I still need to use the right mouse button to open the menu and perform the merge. If a shortcut key could be used for merging, it would greatly improve efficiency. So, could the developer add a shortcut key for this function?

This way, after holding down CTRL and sliding the mouse to select, I can release CTRL and then press the shortcut key on the mouse to quickly merge. The operation would be seamless and wouldn’t disrupt the workflow's rhythm.

I hope you can add a shortcut key for this feature.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hi, @lhj5426,

Thank you for the suggestion! 🌟 We understand the importance of a seamless workflow and how a dedicated shortcut key can enhance efficiency. We're happy to announce that we've added a shortcut key for merging rectangles as per your request. 🎉

Now, after selecting the rectangles with the CTRL + drag method (Default `Ctrl+Shift+M`), you can use the new shortcut key to merge them without having to open the context menu. 

Please update to the latest version to take advantage of this feature. We'd love to hear your feedback on how this improves your experience with X-AnyLabeling. If there's anything else you'd like to see, feel free to let us know!

Keep the great ideas coming! 🚀

Best regards,
X-AnyLabeling Maintainer

**Comment by lhj5426** [comment]
https://github.com/user-attachments/assets/dc8776f9-e7f4-47e3-85b6-cddfc84b342d

Thank you very much.

This way, I can use REWASD to set different functions for pressing and releasing the Ctrl key.

After selecting a rectangular area, I only need to release the Ctrl key, and the selected rectangular area will instantly merge.

This is much more convenient than opening the right-click menu and visually locating the menu function position.

It really improves efficiency and doesn't disrupt the workflow rhythm.

Thank you for your help.
