### ISSUE TITLE
Regression in coco annotations upload (broken, wrong keyword parameter)

### ISSUE THREAD

**Issue by ClemSc** [CVHub520/X-AnyLabeling#605]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Export/Import

### Bug

Hi, since the last update, the coco annotation upload is broken:
On line 4177 of `anylabeling/views/labeling/label_widget.py`

should be 
`output_dir_path=output_dir_path,`
instead of 
`output_path=output_dir_path,`

;-)

### Information

 N/A

### Link to a Reproducible Demonstration Video

 N/A

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hey there! @ClemSc,

Thank you for catching this regression and for providing the exact line number and the fix! 🙌 This is incredibly helpful. We've updated the code as per your suggestion:

```python
output_dir_path=output_dir_path,
```

This change should now be reflected in the latest commit. 📝 We appreciate your contribution to the X-AnyLabeling project. If you encounter any more issues or have further suggestions, please don't hesitate to let us know. Keep up the great work! 🚀

Best regards,
X-AnyLabeling Maintainer
