### ISSUE TITLE
Edit tag

### ISSUE THREAD

**Issue by jiabao-zhang** [CVHub520/X-AnyLabeling#606]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Edit

### Bug

Hello, when I was segmentation annotation, I selected a category, I want to change it to another category, but I found that after the change, the attribute dictionary still retains the previous content, may I ask is the code mechanism problem? Or do I need to add other file properties?

### Information

版本：X-AnyLabeling-CPU.exe      2.4.1

### Link to a Reproducible Demonstration Video

Before modification：
![image](https://github.com/user-attachments/assets/8246cb0d-6baf-4ddb-a7c9-2f0815e78cdd)
After modification：
![image](https://github.com/user-attachments/assets/9007d393-1dcf-4504-8374-f9f170c6443d)

In fact, after the amendment, it should not appear except ["类别": "路沿（人行道）"]

### Execution Mode

Pre-compiled Executable

### Additional

None

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hey! @jiabao-zhang,

Thank you for reaching out. I must apologize, but I'm having some difficulty understanding the issue you've described. To assist you more effectively, could you please provide the `attributes.json` configuration file, the image `y`, and the corresponding label file that you are working with?

Please send these files to the following email address: cv_hub@163.com. This will help me to better diagnose the problem and provide a more accurate solution.

Looking forward to your prompt response.

Best regards,
X-AnyLabeling Maintainer

**Comment by jiabao-zhang** [comment]
Hello, I have sent the relevant email, looking forward to your reply!

**Comment by CVHub520** [comment]
Thank you for reaching out and providing detailed information about the issue you encountered with X-Anylabeling.

I understand that you used the freeSpace_attributes_v1.json as attributes.json for labeling. You’ve mentioned that when you change the category from “road” to “obs” and select the property “路沿（人行道）”, the related properties of “road” are not being removed from the annotation file, even after deleting all the comment files and rebuilding them.

Regarding the negative coordinates in the annotation file, this is indeed unusual and should not occur under normal circumstances. Negative coordinates can cause issues with the processing of the annotation data.

![image](https://github.com/user-attachments/assets/e0bd124c-9145-40e0-947d-2112df90d73e)

**Comment by jiabao-zhang** [comment]
For negative coordinates, I think it's a problem, but I want to ask a different question: When I do this, the value of attributes in the generated tag file gets messed up.
![image](https://github.com/user-attachments/assets/5f3e9938-1dc9-4720-be49-443437c43781)

**Comment by CVHub520** [comment]
Hi there,

Thank you for reaching out. I must apologize, but I’m not entirely clear on the specific issue you’re encountering with the attribute values in the generated tag file. It seems there might be some confusion or lack of detail in the description.

To better understand and address your concern, could you please provide a more detailed explanation or, ideally, record a short video that demonstrates the problem you’re facing? This would greatly help us in pinpointing the issue and providing a solution.

Looking forward to your response with the additional details or video.

**Comment by jiabao-zhang** [comment]
> ### 询问前先搜索
> * [x] 我搜索了 X-AnyLabeling[问题](https://github.com/CVHub520/X-AnyLabeling/issues)，没有发现类似的错误报告。
> 
> ### X-AnyLabeling 组件
> 编辑
> 
> ### 漏洞
> 你好，我在进行分词标注的时候，选中了一个类别，我想将其更改为另一个类别，但是发现更改之后，属性词典中仍然保留着之前的内容，请问是代码机制的问题吗？还是需要添加其他文件属性？
> 
> ### 信息
> 版本：X-AnyLabeling-CPU.exe 2.4.1
> 
> ### 可重现的演示视频链接
> 修改前： 修改后： ![图像](https://private-user-images.githubusercontent.com/87267028/363074531-8246cb0d-6baf-4ddb-a7c9-2f0815e78cdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDc5MTIsIm5iZiI6MTcyNTQ0NzYxMiwicGF0aCI6Ii84NzI2NzAyOC8zNjMwNzQ1MzEtODI0NmNiMGQtNmJhZi00ZGRiLWE3YzktMmYwODE1ZTc4Y2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDExMDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMmE4Y2MzYmQ3NzQzYWFhZWZjNWZkYThmMGU1NDA1NjUxMDU3NTVmNjQ1M2ZmNmRmZTUwZGE4MzQzNGY3MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HRfjgXGR6tOeWnF579p2cwnT72h6pLPrkStL6e40lSE) ![图像](https://private-user-images.githubusercontent.com/87267028/363074796-9007d393-1dcf-4504-8374-f9f170c6443d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDc5MTIsIm5iZiI6MTcyNTQ0NzYxMiwicGF0aCI6Ii84NzI2NzAyOC8zNjMwNzQ3OTYtOTAwN2QzOTMtMWRjZi00NTA0LTgzNzQtZjlmMTcwYzY0NDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDExMDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzM2IwMzI1ZmNkMjg4NTJkNzEyN2RlMmViYzE2ZjlmZWRjM2U0ODlmNDk3NWU5MTJjM2NiODBmMjVkMjVjY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cPS0ppNX2cIvTXzDYvlEEGsggSJcdDF_xNGX0hfDwFM)
> 
> 其实修改后，除了[“类别”:“路沿（人行道）”]之外，不应该出现
> 
> ### 执行模式
> 预编译可执行文件
> 
> ### 额外的
> 没有任何
> 
> ### 您愿意提交 PR 吗？
> * [ ] 是的，我愿意通过提交 PR 来提供帮助！
  For the properties in the red box, when I change the category "路沿（人行道）" to road, the line "类别"："路沿（人行道）" should not appear and should be removed.

  However, this problem should not be very important and may be solved by re-labeling.

**Comment by jiabao-zhang** [comment]
> ### Search before asking
> * [x]  I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.
> 
> ### X-AnyLabeling Component
> Edit
> 
> ### Bug
> Hello, when I was segmentation annotation, I selected a category, I want to change it to another category, but I found that after the change, the attribute dictionary still retains the previous content, may I ask is the code mechanism problem? Or do I need to add other file properties?
> 
> ### Information
> 版本：X-AnyLabeling-CPU.exe 2.4.1
> 
> ### Link to a Reproducible Demonstration Video
> Before modification： ![image](https://private-user-images.githubusercontent.com/87267028/363074531-8246cb0d-6baf-4ddb-a7c9-2f0815e78cdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDgzNTEsIm5iZiI6MTcyNTQ0ODA1MSwicGF0aCI6Ii84NzI2NzAyOC8zNjMwNzQ1MzEtODI0NmNiMGQtNmJhZi00ZGRiLWE3YzktMmYwODE1ZTc4Y2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDExMDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZWY0MzkzMjc4YzhmMTUwNTNjNTkzNTAyMWE1MTVhNzRmMWQ2NmRjMTZiZTliNTgwODU3MTk2ZjlkNDk3NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T76OnGwWZq8svE5Qv-P7XbLdg9YP9gOPjQmHOGK9QeI) After modification： ![image](https://private-user-images.githubusercontent.com/87267028/363074796-9007d393-1dcf-4504-8374-f9f170c6443d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDgzNTEsIm5iZiI6MTcyNTQ0ODA1MSwicGF0aCI6Ii84NzI2NzAyOC8zNjMwNzQ3OTYtOTAwN2QzOTMtMWRjZi00NTA0LTgzNzQtZjlmMTcwYzY0NDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDExMDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4Y2JhODM4MjExZWM0YzNmZWNmNWI0Y2FhY2NjMjE1MjJjNzNmY2U3NWIzZmZjNmIxZjc0NGIzYWIxMGRmNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0eZGgEa_0rRQ-T3AoOxEp89DBK2rDmhU4i8fw9rE-C0)
> 
> In fact, after the amendment, it should not appear except ["类别": "路沿（人行道）"]
> 
> ### Execution Mode
> Pre-compiled Executable
> 
> ### Additional
> None
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I'd like to help by submitting a PR!

  For the properties in the red box, when I change the category "路沿（人行道）" to road, the line "类别"："路沿（人行道）" should not appear and should be removed.

  However, this problem should not be very important and may be solved by re-labeling.
