### ISSUE TITLE
Errors are reported when exporting and uploading coco annotation files

### ISSUE THREAD

**Issue by CZG0712** [CVHub520/X-AnyLabeling#607]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Export/Import

### Bug

When I try to export coco split tags, I get an error like the one below：
![图片](https://github.com/user-attachments/assets/f59f3baf-72bb-42af-a7ef-37afafffaf20)
When I try to import coco split tags, the following will be reported：
![图片](https://github.com/user-attachments/assets/e6eee28e-3ceb-4c87-b39c-f20ac31d53a6)

### Information

The version I'm using is the latest version pulled today

### Link to a Reproducible Demonstration Video

none

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
@cZG0712, Hello there! What do you mean by 'COCO split tags'? Could you provide a detailed description of your question? Additionally, if possible, please feel free to upload a demo video directly so we can better understand your inquiry.

**Comment by CZG0712** [comment]
> @CZG0712, Hello there! What do you mean by 'COCO split tags'? Could you provide a detailed description of your question? Additionally, if possible, please feel free to upload a demo video directly so we can better understand your inquiry.

I'm so sorry about that， 'COCO split tags' means ‘segmentation annotations’. The follows are two demo video show the export and upload.

https://github.com/user-attachments/assets/8eedee50-2deb-42f8-ad45-fc15c7f41f65


https://github.com/user-attachments/assets/d3ee1c80-7c21-41b8-aba8-d56187d99f30

**Comment by CZG0712** [comment]
> @CZG0712, Hello there! What do you mean by 'COCO split tags'? Could you provide a detailed description of your question? Additionally, if possible, please feel free to upload a demo video directly so we can better understand your inquiry.

I'm so sorry about that.  'COCO split tags' means 'COCO Segmentation Annotations'. The follow video shows the problem uploading the coco segmentation annotations.

https://github.com/user-attachments/assets/64a10c1d-49d7-43c4-88c2-978adb31dbee

**Comment by CZG0712** [comment]
> @CZG0712, Hello there! What do you mean by 'COCO split tags'? Could you provide a detailed description of your question? Additionally, if possible, please feel free to upload a demo video directly so we can better understand your inquiry.

I'm so sorry about that. 'COCO split tags' means 'COCO Segmentation Annotations'. This is not a BUG, but a misuse. The reason for the problem is that I chose the annotation mode incorrectly when I segmented the annotation, using linestrip instead of polygons. The area field resulting in the exported coco segmentation annotations is 0. Thanks for your response!
