### ISSUE TITLE
调用MedSam 的时候直接闪退

### ISSUE THREAD

**Issue by simzhangbest** [CVHub520/X-AnyLabeling#608]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

![image](https://github.com/user-attachments/assets/ddbd3ee6-af8b-4bb0-a709-b4374b65b158)

App name: X-AnyLabeling
App version: 2.4.0
Device: CPU

Operating System: Windows-10-10.0.22631-SP0
CPU: Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
GPU: 0, NVIDIA RTX 2000 Ada Generation Laptop GPU, 8188
CUDA: V12.0.76
Python Version: 3.10.14

PyQt5 Version: 5.15.7
ONNX Version: 1.16.2
ONNX Runtime Version: None
ONNX Runtime GPU Version: 1.19.0
OpenCV Contrib Python Headless Version: None

使用的模型是 SAM-MED2D-256x vit base

闪退，报错： 
Could not locate cublasLt64_11.dll. Please make sure it is in your library path!
Invalid handle. Cannot load symbol cublasLtCreate

### Information

Application Information:
{'App name': 'X-AnyLabeling', 'App version': '2.4.0', 'Device': 'CPU'}

System Information:
{ 'CPU': 'Intel64 Family 6 Model 186 Stepping 2, GenuineIntel',
  'CUDA': 'V12.0.76',
  'GPU': '0, NVIDIA RTX 2000 Ada Generation Laptop GPU, 8188',
  'Operating System': 'Windows-10-10.0.22631-SP0',
  'Python Version': '3.10.14'}

Package Information:
{ 'ONNX Runtime GPU Version': '1.19.0',
  'ONNX Runtime Version': None,
  'ONNX Version': '1.16.2',
  'OpenCV Contrib Python Headless Version': None,
  'PyQt5 Version': '5.15.7'}

### Link to a Reproducible Demonstration Video

no video

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by simzhangbest** [comment]
重新找到一个，cublasLt64_11.dll 文件，然后放在 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin 即可

**Comment by CVHub520** [comment]
Thank you for reporting this issue. I'm pleased to hear that you've resolved the problem by placing the `cublasLt64_11.dll` file in the appropriate directory at `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin`.

I would like to point out that the version you are currently using, 2.4.0, has been identified to have a memory leak issue. To ensure optimal performance and stability, we strongly advise upgrading to the latest version of the software available. 

Please feel free to reach out if you need any assistance with the upgrade process.
