### ISSUE TITLE
导入yolo标签文件在大尺寸数据图片中会出现位置的改变

### ISSUE THREAD

**Issue by panda2830** [CVHub520/X-AnyLabeling#609]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

开发者你好，
导入yolo标签文件在大尺寸数据图片中会出现位置的改变
可能是因为图片像素过大
![image](https://github.com/user-attachments/assets/9fea6405-0687-46e1-9789-c3b766dd60d1)
![image](https://github.com/user-attachments/assets/4f2a146b-a7f7-449e-8e63-69ea366baf72)
![image](https://github.com/user-attachments/assets/7ebac9ae-1e31-414c-8afa-984ebd2fd024)

### Information

Application Information:
{'App name': 'X-AnyLabeling', 'App version': '2.4.1', 'Device': 'CPU'}

System Information:
{ 'CPU': 'Intel64 Family 6 Model 151 Stepping 2, GenuineIntel',
  'CUDA': 'V11.6.124',
  'GPU': '0, NVIDIA GeForce RTX 3090, 24576',
  'Operating System': 'Windows-10-10.0.22631-SP0',
  'Python Version': '3.8.19'}

Package Information:
{ 'ONNX Runtime GPU Version': '1.19.0',
  'ONNX Runtime Version': None,
  'ONNX Version': '1.16.2',
  'OpenCV Contrib Python Headless Version': '4.10.0.84',
  'PyQt5 Version': '5.15.7'}
App name: X-AnyLabeling
App version: 2.4.1
Device: CPU

Operating System: Windows-10-10.0.22631-SP0
CPU: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
GPU: 0, NVIDIA GeForce RTX 3090, 24576
CUDA: V11.6.124
Python Version: 3.8.19

PyQt5 Version: 5.15.7
ONNX Version: 1.16.2
ONNX Runtime Version: None
ONNX Runtime GPU Version: 1.19.0
OpenCV Contrib Python Headless Version: 4.10.0.84

### Link to a Reproducible Demonstration Video

[视频链接](https://www.bilibili.com/video/BV1HiHHe5Eyi/)
[导入yolo标签在大尺寸数据集中位置会出错.mp4](https://pan.baidu.com/s/1JEWsW7DaUJJkuie3Hy8Zog?pwd=ABAB)
提取码：ABAB

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
