### ISSUE TITLE
导出Yolo标签会为空

### ISSUE THREAD

**Issue by f549263766** [CVHub520/X-AnyLabeling#611]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

文件目录
- images
- labels
其中images用于存放图像文件，labels用于存放标注后的json文件，即更改输出目录为labels
问题：当选择导出Yolo-水平框标签时，导出的文件txt会删除掉里面的json文件，同时导出的txt内容为空

### Information

CPU，window

### Link to a Reproducible Demonstration Video

![image](https://github.com/user-attachments/assets/cafb7e55-6cb3-45ed-aca4-80de8c76fdea)

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by f549263766** [comment]
解决方法，将输出目录更改为json，即json标注文件存放到这里，则导出文件时，生成的txt文件才有标注内容

**Comment by CVHub520** [comment]
> 解决方法，将输出目录更改为json，即json标注文件存放到这里，则导出文件时，生成的txt文件才有标注内容

Thank you for sharing the solution. Your contribution is greatly appreciated.

**Comment by viwe-monai** [comment]
json文件是可能存储在image的目录下，将所有json文件移动到labels文件夹，然后再导出，生成的txt文件就有标签信息了

**Comment by richiy** [comment]
images为图片目录，json文件自动保存在images目录下，导出为yolo时，默认导入到labels目录下，但所有txt都是空的，请问如何解决？目录结构如下

- images
    - *.json
    - *.jpg
- labels
- classes.txt

**Comment by CVHub520** [comment]
> images为图片目录，json文件自动保存在images目录下，导出为yolo时，默认导入到labels目录下，但所有txt都是空的，请问如何解决？目录结构如下
> 
> * images
>   
>   * *.json
>   * *.jpg
> * labels
> * classes.txt

您好，按照流程正常导出是不可能为空的，请尝试下：
1. Ctrl+G 检查当前任务的标注类型是否为 `Rectangle`（假设你是检测任务），标签名称是否都包含在您的 classes.txt 文件中，是否选择的是 YOLO-Detection 选项导出？详情请参考官方用户手册-导入导出设置章节。
2. 更新到最新代码分支运行，确保对齐。
如仍然有问题，请提供演示视频，包含上述信息展示。

https://github.com/user-attachments/assets/f517fa94-c49c-4f05-864e-96b34f592079

**Comment by richiy** [comment]
> > images为图片目录，json文件自动保存在images目录下，导出为yolo时，默认导入到labels目录下，但所有txt都是空的，请问如何解决？目录结构如下
> > 
> > * images
> >   
> >   * *.json
> >   * *.jpg
> > * labels
> > * classes.txt
> 
> 您好，按照流程正常导出是不可能为空的，请尝试下：
> 
> 1. Ctrl+G 检查当前任务的标注类型是否为 `Rectangle`（假设你是检测任务），标签名称是否都包含在您的 classes.txt 文件中，是否选择的是 YOLO-Detection 选项导出？详情请参考官方用户手册-导入导出设置章节。
> 2. 更新到最新代码分支运行，确保对齐。
>    如仍然有问题，请提供演示视频，包含上述信息展示。
> 
>  annotation.mp4

https://github.com/user-attachments/assets/891e1068-198a-4005-b3df-8a9ae2cc4654

以上是我录制的视频，请查看!

**Comment by CVHub520** [comment]
你这打的是矩形框，你导出又选择分割标签，请先明确下究竟是做检测任务还是分割任务，检测任务请打矩形框，选择 Rectangle，分割任务请打多边形框，选择 Segmentation，以此类推。

**Comment by richiy** [comment]
> 你这打的是矩形框，你导出又选择分割标签，请先明确下究竟是做检测任务还是分割任务，检测任务请打矩形框，选择 Rectangle，分割任务请打多边形框，选择 Segmentation，以此类推。

那是搞错了，可以了，谢谢！
