### ISSUE TITLE
Yolo标签导出失败

### ISSUE THREAD

**Issue by Wuoo25** [CVHub520/X-AnyLabeling#612]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

标注完json文件是正常的，但是导出时，空白的yolo obb文件全部覆盖了原有文件。我是用自己的模型进行ai预测的

**Comment by CVHub520** [comment]
> 标注完json文件是正常的，但是导出时，空白的yolo obb文件全部覆盖了原有文件。我是用自己的模型进行ai预测的

Hi there, @Wuoo25:

Thank you for bringing this issue to our attention. It’s concerning to hear that the blank YOLO OBB files are overwriting your existing files during the export process. 

To better understand and address the problem, could you please provide details on how you organize your folder directory structure? 

Looking forward to your response.
