### ISSUE TITLE
Interactive Video Object Segmentation not working

### ISSUE THREAD

**Issue by sijieaaa** [CVHub520/X-AnyLabeling#613]
Hi, 
It seems the IVOS is not working. The first frame's annotations are not propagated to the succedding frames. 
By contrast, the annotations are successfully propagated in MetaAI's SAM2 demo.

The first frame.
![image](https://github.com/user-attachments/assets/20735442-928e-4019-af92-b4421db3c2db)

Propagated second frame.
![image](https://github.com/user-attachments/assets/96cbee35-b900-4ad6-a904-4016428e2d28)

_Originally posted by @sijieaaa in https://github.com/CVHub520/X-AnyLabeling/issues/602#issuecomment-2328543086_

MetaAI SAM2 demo
![image](https://user-images.githubusercontent.com/58644619/364344038-91c1baba-0986-4356-a03c-b273383af4af.png)

**Comment by sijieaaa** [comment]
resuls from MetaAI SAM2 demo (https://sam2.metademolab.com/demo) 

![image](https://github.com/user-attachments/assets/b367ec32-0a6a-4059-a578-b65a2b490acd)
![image](https://github.com/user-attachments/assets/045d7b59-f186-4197-8142-d6e398bd4221)

**Comment by CVHub520** [comment]
Hi, @sijieaaa,

Thank you for reaching out. To address the issue with IVOS, please ensure that you are following the [tutorial](https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/interactive_video_object_segmentation/README.md) step by step to avoid any potential oversights. Additionally, could you please check the terminal output logs for any error messages? Error logs often provide specific insights into the root cause of the problem, which will help us to identify and resolve the issue more efficiently.

If you encounter any error messages in the logs, please either take a screenshot or copy and paste the error log content here, and I will do my best to assist you further.

Looking forward to your response and hoping for a smooth experience for you.

Best regards,
X-AnyLabeling Maintainer

**Comment by sijieaaa** [comment]
Thanks for your prompt rely.
The error info is listed as follows:

```
(x-anylabeling-sam2) D:\Downloads\demo_labeling\X-AnyLabeling>python anylabeling/app.py
An error occurred while resetting the tracker: 'point_inputs_per_obj'
WARNING:root:Could not inference model
WARNING:root:cannot import name '_C' from 'sam2' (D:\Downloads\demo_labeling\segment-anything-2\sam2\__init__.py)
Traceback (most recent call last):
  File "D:\Downloads\demo_labeling\X-AnyLabeling\.\anylabeling\services\auto_labeling\segment_anything_2_video.py", line 351, in predict_shapes
    shapes, replace = self.video_process(cv_image, filename)
  File "D:\Downloads\demo_labeling\X-AnyLabeling\.\anylabeling\services\auto_labeling\segment_anything_2_video.py", line 316, in video_process
    _, out_obj_ids, out_mask_logits = self.video_predictor.add_new_prompt(
  File "C:\Users\63502\.conda\envs\x-anylabeling-sam2\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\Downloads\demo_labeling\segment-anything-2\sam2\sam2_camera_predictor.py", line 272, in add_new_prompt
    current_out, _ = self._run_single_frame_inference(
  File "D:\Downloads\demo_labeling\segment-anything-2\sam2\sam2_camera_predictor.py", line 985, in _run_single_frame_inference
    pred_masks_gpu = fill_holes_in_mask_scores(
  File "D:\Downloads\demo_labeling\segment-anything-2\sam2\utils\misc.py", line 223, in fill_holes_in_mask_scores
    labels, areas = get_connected_components(mask <= 0)
  File "D:\Downloads\demo_labeling\segment-anything-2\sam2\utils\misc.py", line 61, in get_connected_components
    from sam2 import _C
ImportError: cannot import name '_C' from 'sam2' (D:\Downloads\demo_labeling\segment-anything-2\sam2\__init__.py)
WARNING:root:Could not inference model
WARNING:root:list index out of range
Traceback (most recent call last):
  File "D:\Downloads\demo_labeling\X-AnyLabeling\.\anylabeling\services\auto_labeling\segment_anything_2_video.py", line 351, in predict_shapes
    shapes, replace = self.video_process(cv_image, filename)
  File "D:\Downloads\demo_labeling\X-AnyLabeling\.\anylabeling\services\auto_labeling\segment_anything_2_video.py", line 316, in video_process
    _, out_obj_ids, out_mask_logits = self.video_predictor.add_new_prompt(
  File "C:\Users\63502\.conda\envs\x-anylabeling-sam2\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\Downloads\demo_labeling\segment-anything-2\sam2\sam2_camera_predictor.py", line 272, in add_new_prompt
    current_out, _ = self._run_single_frame_inference(
  File "D:\Downloads\demo_labeling\segment-anything-2\sam2\sam2_camera_predictor.py", line 957, in _run_single_frame_inference
    ) = self._get_image_feature(frame_idx, batch_size)
  File "D:\Downloads\demo_labeling\segment-anything-2\sam2\sam2_camera_predictor.py", line 892, in _get_image_feature
    self.condition_state["images"][frame_idx].cuda().float().unsqueeze(0)
IndexError: list index out of range
WARNING:root:Could not inference model
WARNING:root:list index out of range
```

**Comment by CVHub520** [comment]
Thank you for your valuable feedback. Based on the error log you've submitted, it appears that there are two main issues:
> ImportError: cannot import name '_C' from 'sam2'

This log indicates that there is an issue with your environment setup. Specifically, you can navigate to the issue discussion section of the [Segment-Anything-2](https://github.com/facebookresearch/segment-anything-2/issues/25) repository to look for a solution.

> IndexError: list index out of range

This error is likely occurring during the secondary tracking phase. A more detailed investigation will be required to address and fix this issue.

Therefore, you might want to attempt a clean installation of your environment. It is recommended to create a new conda environment and follow the tutorial step by step for the installation, rather than using the existing sam2 environment. As for the second issue, you can temporarily avoid this operation while we look into a more permanent solution.

**Comment by sijieaaa** [comment]
Thanks for your reply! Now x-anylabeling works well for IVOS.
![Screenshot from 2024-09-04 23-13-53](https://github.com/user-attachments/assets/722e145f-3646-4529-9774-de553408f86a)

Besides, there is one more package missing in requirements.txt
```
(x-anylabeling-sam2) sijie@4090:~/X-AnyLabeling$ python3 anylabeling/app.py 
Traceback (most recent call last):
  File "/home/sijie/X-AnyLabeling/anylabeling/app.py", line 24, in <module>
    from anylabeling.views.mainwindow import MainWindow
  File "/home/sijie/X-AnyLabeling/./anylabeling/views/mainwindow.py", line 6, in <module>
    from .labeling.label_wrapper import LabelingWrapper
  File "/home/sijie/X-AnyLabeling/./anylabeling/views/labeling/label_wrapper.py", line 5, in <module>
    from .label_widget import LabelingWidget
  File "/home/sijie/X-AnyLabeling/./anylabeling/views/labeling/label_widget.py", line 42, in <module>
    from . import utils
  File "/home/sijie/X-AnyLabeling/./anylabeling/views/labeling/utils/__init__.py", line 3, in <module>
    from .general import (
  File "/home/sijie/X-AnyLabeling/./anylabeling/views/labeling/utils/general.py", line 4, in <module>
    from importlib_metadata import version as get_package_version
ModuleNotFoundError: No module named 'importlib_metadata'
```
I fixed this issue by simply installation
```
pip install importlib_metadata
```
Thanks.

**Comment by heroacool** [comment]
@CVHub520 
it reports error as following
> Error in loading model: cannot import name 'build_sam2_camera_predictor' from 'sam2.build_sam' (/home/ubuntu/segment-anything-2/sam2/build_sam.py)

after reviewing the sam2 video example notebook, I found thart it need to change build_sam2_camera_predictor to build_sam2_video_predictor. but it still has other errors when inferencing all the images.

I would like to know the segment-anything-2 repo commit id is 7e1596c0b6462eb1d1ba7e1492430fed95023598

**Comment by heroacool** [comment]
btw, it seem you did not tag v2.4.2 in the repo. @CVHub520

**Comment by CVHub520** [comment]
@heroacool

Regarding the first issue, please follow the [example](https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/interactive_video_object_segmentation/README.md) for installation. The problem you're encountering is due to downloading the wrong GitHub repository:

```
git clone https://github.com/CVHub520/segment-anything-2
```
Instead of `https://github.com/facebookresearch/segment-anything-2`.

For the second issue, the current feature is in a testing transition phase. The v2.4.2 version will be officially released once the functionality is stabilized.

Thank you for your patience and understanding.

**Comment by sijieaaa** [comment]
> Thank you for your valuable feedback. Based on the error log you've submitted, it appears that there are two main issues:
> 
> > ImportError: cannot import name '_C' from 'sam2'
> 
> This log indicates that there is an issue with your environment setup. Specifically, you can navigate to the issue discussion section of the [Segment-Anything-2](https://github.com/facebookresearch/segment-anything-2/issues/25) repository to look for a solution.
> 
> > IndexError: list index out of range
> 
> This error is likely occurring during the secondary tracking phase. A more detailed investigation will be required to address and fix this issue.
> 
> Therefore, you might want to attempt a clean installation of your environment. It is recommended to create a new conda environment and follow the tutorial step by step for the installation, rather than using the existing sam2 environment. As for the second issue, you can temporarily avoid this operation while we look into a more permanent solution.

The following fixed "ImportError: cannot import name '_C' from 'sam2'"
```
python setup.py build_ext --inplace
```

**Comment by CVHub520** [comment]
Thank you so much for sharing this solution! It will definitely help others who encounter the same error. If you have any more questions or run into other issues, feel free to ask. Have a great day! 🌟

**Comment by sijieaaa** [comment]
Thanks. This is a high-quality repo. I think people are willing to contribute to this great project.

**Comment by heroacool** [comment]
it works. many thanks! @CVHub520 @sijieaaa

**Comment by CVHub520** [comment]
You're welcome! I'm glad to hear that! 😊

**Comment by nidetaoge** [comment]
Thanks for your work! I have encountered a problem where SAM2 cannot run on a CPU machine. I see this repo can support CPU inference for SAM2. I wonder whether we can support CPU-based SAM2 in X-AnyLabeling. Thanks.
https://github.com/SauravMaheshkar/samv2

**Comment by CVHub520** [comment]
Hi @nidetaoge; I have added support for CPU devices in the latest commit. You can pull the latest code from both `https://github.com/CVHub520/segment-anything-2/tree/camera` and this repository to try it out. Thanks!

Remember, you should update the field `device_type` to `cpu` in the corresponding YAML file (e.g., `sam2_hiera_tiny_video.yaml` found at [this link](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/sam2_hiera_tiny_video.yaml)) to enable utilization of the CPU device.

**Comment by nidetaoge** [comment]
For interactive segment anything and visual tracking, this repo provides a more powerful ability based on SAM2. Will you consider supporting this? Thank you very much!
https://yangchris11.github.io/samurai/

**Comment by CVHub520** [comment]
> For interactive segment anything and visual tracking, this repo provides a more powerful ability based on SAM2. Will you consider supporting this? Thank you very much! https://yangchris11.github.io/samurai/

Thank you for your suggestion; I will take it into consideration for my development roadmap.
