### ISSUE TITLE
How can i use  custom yolov8 segmentaion model. I am able to use object detection model .

### ISSUE THREAD

**Issue by dhunjoshi** [CVHub520/X-AnyLabeling#617]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

How can i use  custom yolov8 segmentaion model. I am able to use object detection model .

**Comment by CVHub520** [comment]
Hello! 

To use your custom YOLOv8 segmentation model in X-AnyLabeling, please follow the instructions provided in the tutorial linked below:

**Custom Model Tutorial:** <https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/custom_model.md>

This tutorial will guide you through the process step by step, including how to prepare your model files and configure them within the X-AnyLabeling system.

If you encounter any issues or have further questions while following the tutorial, feel free to update this issue with more details, and we'll be happy to assist you. Good luck with integrating your custom YOLOv8 segmentation model! 🚀✨
