### ISSUE TITLE
SAM2预标注，输出矩形框，当图中没有跟踪目标时，会出现一个将全图框住的box

### ISSUE THREAD

**Issue by wangxiang0722** [CVHub520/X-AnyLabeling#618]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Model

### Bug

SAM2预标注，输出矩形框，当图中没有跟踪目标时，会初心一个将全图框住的box。
定位在anylabeling/services/auto_labeling/segment_anything_2_video.py   line231
没有判断len(approx_contours) 是否大于 0

### Information

None

### Link to a Reproducible Demonstration Video

None

### Execution Mode

Pre-compiled Executable

### Additional

None

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hello! Thank you for bringing this issue to our attention. It appears that there was an error in the code where a bounding box would be generated even when no target was present in the image.

We have identified the problem and fixed it in the latest version of the software. The fix has been implemented on line 231 of `segment_anything_2_video.py`, where we now check whether the number of approximated contours (`approx_contours`) is greater than zero before generating a bounding box.

We appreciate your willingness to contribute to our project by submitting a pull request. If you are interested in contributing further, please feel free to do so. In the meantime, please update to the latest version of the software to resolve this issue.

Thank you again for your support, and let us know if you have any further questions or concerns. 🙌🚀
