### ISSUE TITLE
Can we add an option to export only the modified image data during the export process?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#619]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

What do you mean? I mean, I have already trained a model with 50,000 to 60,000 images, and these 50,000 to 60,000 images are from an old dataset. Then, I use this model to process new images, let's say I processed 2,000 new images. Among these 2,000 images, I found that 400 images were inaccurately recognized by the model. I want to export these 400 images separately and add them to the old dataset for retraining. Of course, it's not just 400 images; this is just an example. This means I want to add additional training data, but I only want to add the inaccurately recognized data. Currently, the software cannot achieve the function of recording only the images that were manually corrected after AI inference and exporting only these manually corrected images.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lhj5426** [comment]
Currently, the method I use is to sort the JSON files generated by the software using Windows Explorer Directory Opus by grouping them according to the modification time. Modified files will be moved to the front. This way, after all annotations are completed, I only need to copy the filenames of the files that were modified most recently to filter the same-named image files and TXT files in the exported labels. This method allows me to manually filter out the images and files with modified labels. It's very cumbersome, so can the software itself add a feature to only export modified images and labels?

**Comment by CVHub520** [comment]
Hello there! 😊

Thank you for reaching out about this feature request. I understand how having an option to export only modified image data during the process can be useful, especially when retraining models with updated data.

As maintainers of this open-source tool, we encourage our users to explore their own customizations and enhancements. If you're willing to contribute to the project, feel free to submit a pull request (PR) with the new functionality. Our community will be happy to review and support your work. 🚀

In the meantime, I recommend checking out the documentation and resources available on our website to help you get started with implementing this feature yourself. Good luck, and don't hesitate to reach out if you have any further questions or concerns! 🤗

**Comment by lhj5426** [comment]
Yes, you are absolutely right. However, the premise is that if I understood coding, I would have already modified and redeveloped the software myself to better suit my needs. But in reality, I have only been using software and have never learned any programming languages from birth until now. That's why I am asking. If I knew how to code, I would be more than happy to contribute to the community. But I am really sorry, I don't have the foundation or the ability to do so. I can only apologize to you.

**Comment by CVHub520** [comment]
No worries at all! 😊 We completely understand that not everyone has the time or expertise to contribute code to open-source projects like ours. As an independent developer, I do my best to accommodate requests and improve the software, but sometimes it's challenging to meet every individual need.

If you ever decide to learn programming languages and want to contribute to the project, we'd be more than happy to welcome you aboard! In the meantime, keep an eye out for updates and improvements to the software. Thank you for using our tool, and let us know if you have any other questions or concerns. 🤗

**Comment by lhj5426** [comment]
I know that we are now in the era of AI. Saying that you can't program might be laughed at by others. But the reality is just like that. AI is not yet powerful enough to compensate for human shortcomings. So I feel helpless too. I have time, but I don't have the desire to learn unless I am truly interested. For example, I now use your software for more than 10 hours a day. My current interest is training a comic recognition model with an accuracy rate of at least 95%. So I spend a lot of time on data standardization. I have time, but I won't be dedicated to things I'm not interested in. Maybe once I am satisfied with the model training, I might develop an interest in programming and spend a lot of time learning it every day.

**Comment by CVHub520** [comment]
I appreciate your honesty, and I understand where you're coming from. It's great to hear that you're passionate about training a comic recognition model with high accuracy. 

Keep up the good work, and who knows? Maybe one day you'll develop an interest in programming too. If you have any other questions or concerns related to our software, feel free to ask. Have a great day!

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/390c4085-fbe2-430b-b65d-48c0e6beebeb)
For example, you provided a hint here, so I asked the AI, and perhaps it can solve the issue of mouse hover tips. However, asking me to develop a feature is something I truly cannot do. Of course, I am very grateful to you and all the developers in the open-source community for developing various useful and convenient tools. I am truly thankful; you are the heroes of the digital age.

**Comment by CVHub520** [comment]
Thank you for your kind words about our open-source community and developers. We are glad to hear that you appreciate their hard work and dedication to creating useful tools.

Regarding your question about disabling the tooltips, we apologize for any confusion caused by our previous response. Please rest assured that you do not need to develop a feature yourself. Instead, simply follow the steps outlined below to achieve the desired result:

1. Locate the file `X-AnyLabeling/anylabeling/views/labeling/widgets/canvas.py` on your local machine.
2. Find the code lines mentioned earlier (Lines 454-463) and add a "#" symbol at the beginning of each line to comment them out.

Here's an example of how to comment out those lines:

```python
# 454 if shape.group_id and shape.shape_type == "rectangle":
# 455     tooltip_text = "Click & drag to move shape '{label} {group_id}'".format(
# 456         label=shape.label, group_id=shape.group_id
# 457 )
# 458     self.setToolTip(self.tr(tooltip_text))
# 459 else:
# 460    self.setToolI
```

After commenting out these lines, save the changes and restart X-AnyLabeling. The tooltips should no longer appear when hovering over the elements.

If you face any difficulties or require additional support, feel free to reach out to us. We're always here to assist you.

Good luck!

**Comment by CVHub520** [comment]
#620

**Comment by lhj5426** [comment]
A year later, with the help of AI, the problem was finally solved.

<img width="1269" height="972" alt="Image" src="https://github.com/user-attachments/assets/4f7269ae-da2d-4f54-8e65-56984f8d57bd" />
