### ISSUE TITLE
Can this prompt be turned off somewhere?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#620]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/9aa02a26-07ae-44e1-9436-02bfe7e96c9b)

![image](https://github.com/user-attachments/assets/b16f6134-9586-4f4e-a292-6d8a7c97d62a)

These are the two tooltips that pop up when hovering the mouse over them. Sometimes, when dragging a rectangle, this pops up and obstructs my view, which is very annoying. I am already very familiar with the software, and these tooltips are now a nuisance for me. Could you please tell me where I can disable them? Can you help me? Thank you

**Comment by CVHub520** [comment]
Hello! Thank you for reaching out to us.

We understand that you would like to disable the tooltips that appear when hovering over certain elements in X-AnyLabeling. We appreciate your familiarity with our software and want to make sure you have the best experience possible.

To turn off these prompts, we recommend following the instructions provided by the developer. You can find the code lines to comment out at the following link:
https://github.com/CVHub520/X-AnyLabeling/blob/897e1b4a6ccd28a0ab2085d7fee5fca5a9cfff8c/anylabeling/views/labeling/widgets/canvas.py#L454-L463

Please search for these specific lines within the source code and add a "#" symbol at the beginning of each line to comment them out. This will prevent the tooltips from appearing during use.

If you encounter any issues or need further assistance, don't hesitate to reach out. We're here to help!

Best regards,
X-AnyLabeling Maintainer

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/bca6b2e6-5f8b-4f3c-81a0-4235a986130f)

According to the method you provided,
![image](https://github.com/user-attachments/assets/cabac261-3f61-4899-adbb-23fc78d76e6d)

 the prompt in this image is gone, 
 
 but the prompt in the first image is still there.
![image](https://github.com/user-attachments/assets/221d3068-582f-482d-b789-25f7bdf60c8c)

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/cb43c860-8a10-4f26-a716-e1b9e614fd5a)
"No worries, based on the AI's explanation, I cleared this part, and now there's no tooltip."

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/ac840556-190b-4c60-82af-31573e5fc08e)
If possible, could an option be added in these places, or perhaps an option added in the configuration file? This is currently a compromise solution, but with future updates and code changes, it might become ineffective. Regardless, I want to express my gratitude for your help

**Comment by CVHub520** [comment]
Hey there!

Thank you for your suggestion regarding adding an option to disable tooltips through the UI or configuration file. We understand your concern about future updates potentially affecting the effectiveness of the current solution.

However, please note that this request is not a common high-frequency demand, so we haven't considered implementing such a feature yet. If you prefer not to modify the source code directly, you may consider using a stable version of X-AnyLabeling that suits your needs and avoid updating unless necessary. This way, you won't be affected by potential changes in newer versions.

We hope this information helps, and thank you again for your kind words. If you have any other questions or concerns, please don't hesitate to reach out.
