### ISSUE TITLE
change id

### ISSUE THREAD

**Issue by sjobsL** [CVHub520/X-AnyLabeling#622]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

When multi-target tracking task, how to change one id all to another in all the pictures

**Comment by CVHub520** [comment]
You can open the Group ID Manager with Alt+G to modify the group_id. :)

**Comment by sjobsL** [comment]
If I get some object generated by the sam2 model, how do I mark the same object as the same id group

**Comment by sjobsL** [comment]
If I get some object generated by the sam2 model without id group , how do I mark the same object as the same id group

**Comment by sjobsL** [comment]
If I get some object generated by the sam2 model without id group , how do I mark the same object as the same id group？then export mot？

**Comment by CVHub520** [comment]
Hey there! 😊

Regarding your question about marking the same object as the same ID group when exporting MOT labels, you're correct that you need to set the `group_id` field for each object. The good news is that the latest update now supports assigning `group_id` during the process. So, you can go ahead and correct any incorrect IDs as needed.

Try to `git pull` the latest source code!  If you need further assistance or have more questions, feel free to ask! 

Happy labeling! 🚀

**Comment by CVHub520** [comment]
@sjobsL, Hi!

We have supported custom label and track ID settings, please refer to the discussion in #629.
