### ISSUE TITLE
How do you make a project into an exe file? it's important to me

### ISSUE THREAD

**Issue by junliuchengxia** [CVHub520/X-AnyLabeling#623]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

How do you make a project into an exe file? it's important to me

### Additional

How do you make a project into an exe file? it's important to me

**Comment by CVHub520** [comment]
Here is a [tutorial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/get_started.md#3-development) that can guide you through the process of building an .exe file.

**Comment by junliuchengxia** [comment]
many thanks
