### ISSUE TITLE
有没有Next Video的功能

### ISSUE THREAD

**Issue by Morgott-The-Omen-King** [CVHub520/X-AnyLabeling#624]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

首先非常感谢作者提供了这么有用的标注工具！

我目前用SAM2标注视频的分割数据，让我完成一个视频的分割之后，请问快捷切换到下一个视频？我目前知道的只有通过选择打开另一个文件夹。

**Comment by CVHub520** [comment]
Hello! Thank you for your question and for using X-AnyLabeling.

Currently, there is no preloading option for multiple video files. You can switch to a new video file by pressing `Ctrl+O` or select an image frame file by pressing `Ctrl+U`.

We appreciate your feedback. If you have any more questions or suggestions, feel free to ask! 🚀

**Comment by Morgott-The-Omen-King** [comment]
感谢您的回答！
