### ISSUE TITLE
内存占用问题

### ISSUE THREAD

**Issue by coptersack** [CVHub520/X-AnyLabeling#625]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

标记的时候内存占用极高，使用一段时间过后会由于内存不足强制关闭
![image](https://github.com/user-attachments/assets/102fd9a5-30ff-4682-89f5-cb7394cd51ca)

### Information

Application Information:
{'App name': 'X-AnyLabeling', 'App version': '2.4.0', 'Device': 'CPU'}

System Information:
{ 'CPU': 'Intel64 Family 6 Model 183 Stepping 1, GenuineIntel',
  'CUDA': 'V11.1.74',
  'GPU': '0, NVIDIA GeForce RTX 3090, 24576',
  'Operating System': 'Windows-10-10.0.22631-SP0',
  'Python Version': '3.9.19'}

Package Information:
{ 'ONNX Runtime GPU Version': '1.18.0',
  'ONNX Runtime Version': None,
  'ONNX Version': '1.16.2',
  'OpenCV Contrib Python Headless Version': '4.10.0.84',
  'PyQt5 Version': '5.15.7'}

### Link to a Reproducible Demonstration Video

None

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
@coptersack,

Thank you for reporting the bug with X-AnyLabeling Component. We have identified and resolved the issue where high memory usage was causing the application to crash after prolonged use. This fix has been included in our latest release. Please update your software to the most recent version to ensure you are benefiting from these improvements.

If you continue to experience any issues or if there's anything else we can assist you with, please don't hesitate to let us know.
