### ISSUE TITLE
Filtering annotated/unannotated images

### ISSUE THREAD

**Issue by hoeoek** [CVHub520/X-AnyLabeling#628]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

I have a dataset of a couple of thousand images, most of them annotated. However, there are a few not annotated images in there, and I'd like to filter the dataset to only show those without annotations, so i dont have to go manually truough every image. I've looked through the software and the issues, but i cant find a solution (surely there must be one?)

Thanks for your hard work with this great software!

**Comment by CVHub520** [comment]
Hey there! @hoeoek,

Thank you for reaching out and for your kind words about the software!

I understand the challenge you’re facing with the dataset. I’m happy to inform you that we are currently working on implementing a feature that will allow you to filter and display only the unannotated images. This feature should be available soon, and it will certainly help streamline your workflow.

We’ll make sure to update you as soon as it’s live. Stay tuned for the announcement!

**Comment by CVHub520** [comment]
@hoeoek, Hi!

I'm excited to announce that the feature to navigate between checked and unchecked images has been implemented. You can now easily move to the next or previous unchecked image using the shortcuts **Ctrl+Shift+D** for the next image and **Ctrl+Shift+A** for the previous image.

Additionally, for users who prefer a different behavior, we've added the flexibility to modify the `switch_to_checked` field in the user configuration file. When this field is set to `true`, the default action of the **Ctrl+Shift+D** and **Ctrl+Shift+A** shortcuts will be reversed, allowing you to quickly switch to the next or previous checked image instead.

To take advantage of this new feature, please ensure that your software is updated to the latest version. 

Should you have any questions, require assistance with updating, or need help with configuring the settings, feel free to contact us. We're committed to providing you with a smooth and customized experience.

Happy labeling! 🚀
