### ISSUE TITLE
Issue with Auto-Selecting Previous Tag (Ctrl+Y) After Switching Images！

### ISSUE THREAD

**Issue by 13203897132** [CVHub520/X-AnyLabeling#631]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Edit

### Bug

When using the "Select Previous Tag Name" feature during annotation, I have multiple tags such as "apple" and "banana" on an image. After labeling "apple" first and then "banana" on the first image, the system should automatically select the previous tag "banana" when I switch to the next image. However, it incorrectly auto-selects the "apple" tag instead.

Could you please address this issue? It would be greatly appreciated if the expected tag selection behavior could be implemented in the next update. Thank you for your attention to this matter.

### Information

'X-AnyLabeling', '应用版本': '2.4.2', '设备':'CPU'

### Link to a Reproducible Demonstration Video

Paste the link to your video here

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
@13203897132, Hey!

Thank you for reporting this issue. I'm pleased to inform you that we have addressed the auto-selection behavior you described. The feature to correctly auto-select the previous tag name (Ctrl+Y) after switching images has been implemented and is now available.

Here's what you can expect:
1. When you label "apple" and then "banana" on the first image
2. After switching to the next image and using Ctrl+Y
3. The system will now correctly auto-select "banana" as the previous tag

We encourage you to update to the latest version of X-AnyLabeling and give it a try. If you encounter any issues or if the behavior doesn't match your expectations, please don't hesitate to let us know.

Thank you for your patience and for helping us improve X-AnyLabeling. Your feedback is invaluable to us.
