### ISSUE TITLE
自动标注功能可以使用远端服务器GPU进行推理么？

### ISSUE THREAD

**Issue by AlphaJi** [CVHub520/X-AnyLabeling#636]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

自动标注功能可以使用远端服务器GPU进行推理么？客户端电脑打开标注工具，GPU推理通过远端服务器，可以这样么？该怎么做呢

**Comment by CVHub520** [comment]
Duplicate of #401.
