### ISSUE TITLE
想问下X-AnyLabeling支持yolov3模型么？是否也可以转化为onnx格式进行自动标注

### ISSUE THREAD

**Issue by bommbomm** [CVHub520/X-AnyLabeling#637]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

想问下X-AnyLabeling支持yolov3模型么？是否也可以转化为onnx格式进行自动标注

**Comment by CVHub520** [comment]
Hello @bommbomm,

Thank you for your inquiry. X-AnyLabeling doesn't support YOLOv3 model now. 

However, you can refer to the documentation for detailed instructions on loading and using your custom `yolov3` model within the X-AnyLabeling framework.

Please check the [Custom Model Loading section](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md#%E5%8A%A0%E8%BD%BD%E6%9C%AA%E9%80%82%E9%85%8D%E7%9A%84%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B) of the documentation for the steps you need to follow.

If you encounter any issues or have further questions, feel free to ask. We're here to help.

Best regards,
X-AnyLabeling Maintainer
