### ISSUE TITLE
yolov6lite_l_face.yaml  yolov6lite_m_face.yaml  yolov6lite_s_face.yaml 这些模型加载都提示 Error in loading model: 'has_visible'

### ISSUE THREAD

**Issue by jamesBaiyuhao** [CVHub520/X-AnyLabeling#638]
如题， yolov6lite_l_face.yaml  yolov6lite_m_face.yaml  yolov6lite_s_face.yaml 这些模型加载都提示 Error in loading model: 'has_visible'

我希望是能自动标注5个人脸特征，结果价值模型失败

**Comment by CVHub520** [comment]
Hey there! @jamesBaiyuhao, 😄 

Thank you for bringing your issue to our attention. I'm pleased to inform you that the problem you reported has been addressed.

Please pull the latest changes from the repository and test the updated code to ensure that the issue has been resolved to your satisfaction. If you encounter any further problems or have additional questions, do not hesitate to reach out.

Thank you for your patience and cooperation. 🚀 

Best regards,
X-AnyLabeling Maintainer
