### ISSUE TITLE
MOT: Group ID Manager Failed

### ISSUE THREAD

**Issue by TomX32** [CVHub520/X-AnyLabeling#639]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Hello, when I am using X-AnyLabeling-CPU-2.4.2(latest) for MOT annotation tasks, the Group IDs Manager fails to work, specifically the “IDs change” (Alt+G) becomes ineffective. I have tried multiple times and restarted the software, but it still doesn’t work. Although I was successful in the previous video frame sequence image, where it displayed “An error occurred while updating the Group IDs.” but the modification was still successful, now it displays the error message and the modification does not succeed.

-----
Like this: 👇
https://github.com/user-attachments/assets/7e8e9c06-9c5d-4793-84d3-330f303c6bd5

**Comment by CVHub520** [comment]
Hi TomX32,

Thank you for reaching out and providing detailed information.

We have identified a potential issue where `group_id` values might be `None`, causing the Group ID Manager to fail. We have implemented a fix to skip shapes with null `group_id` values during the modification process.

Please update to the latest version and try again. If the issue persists, feel free to provide additional details, and we will investigate further.

Best regards,
X-AnyLabeling Maintainer

**Comment by TomX32** [comment]
Many thx for your timely response and accurate fix. :smiley:
