### ISSUE TITLE
如何部署自己训练的基于sam微调的模型？

### ISSUE THREAD

**Issue by JAYCHOU2020** [CVHub520/X-AnyLabeling#64]
如何部署自己训练的基于sam微调的模型？

**Comment by CVHub520** [comment]
您好， @JAYCHOU2020 ，这个等后续出个教程，敬请留意。

**Comment by JAYCHOU2020** [comment]
> 您好， @JAYCHOU2020 ，这个等后续出个教程，敬请留意。

希望能尽快
感谢你们的工作！！！

**Comment by CVHub520** [comment]
> > 您好， @JAYCHOU2020 ，这个等后续出个教程，敬请留意。
> 
> 希望能尽快 感谢你们的工作！！！

您好，请参考此[文档](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md)。
