### ISSUE TITLE
有没有从大的图片截图，同时将截取的图片保存，并标注图片类别的功能？

### ISSUE THREAD

**Issue by Riki123666** [CVHub520/X-AnyLabeling#641]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

首先非常感谢作者提供了这么有用的标注工具！

我目前有一张很大的tif图片，我想边截图边标注它的类别，请问这个功能有实现吗

**Comment by CVHub520** [comment]
Hey there! @Riki123666,

Thank you for your feedback!

Currently, we don't have a feature to directly crop and label images from a large image. However, you can consider annotating rectangular boxes with labels first and then parsing them during post-processing.

**Comment by Riki123666** [comment]
我发现保存子图这个功能可以满足我的要求，就是画的矩形太多的话，需要处理的时间比较长
