### ISSUE TITLE
RMBG doesn't seem to do anything

### ISSUE THREAD

**Issue by quitmeyer** [CVHub520/X-AnyLabeling#644]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

I am using the latest september version of x-anylabelling and i went to try out the RMBG model, but it doesn't seem to do anything

i tried numerous types of images. it just says "inferencing model"
![image](https://github.com/user-attachments/assets/cc4e65e0-cab5-4766-9312-f9a7bcd2e05f)

And then it says "finished"

but there's no obvious change 

![image](https://github.com/user-attachments/assets/1aa5fdcf-54bc-4c17-8c36-42ec87e1c7a5)

### Information

i just have the exe file 

### Link to a Reproducible Demonstration Video

i uploaded images

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hello @quitmeyer!

Once the processing is complete, the output will be automatically saved in a directory named `x-anylabeling-matting`. This folder will be created within the same location as your original image file.

For your reference, we've prepared some example outputs that you can review. These examples should give you a clear idea of what to expect from the process. You can find them in our GitHub repository at the following link:

[Image Matting Examples](https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/matting/image_matting/README.md)

Feel free to take a look and let me know if you have any questions about the output or the process. We're here to help!

**Comment by quitmeyer** [comment]
Great! I see it now! thanks!

**Comment by quitmeyer** [comment]
Ahh one extra comment, I think one problem i had is sometimes it saves the "matting" folder OUTSIDE my current working folder. For some reason my windows 10 machine  automatically puts the matting folder  next to the target folder instead of as a subfolder (target folder in this example is called "bigmessofmoths")

my windows 11 machine seems fine and puts the matting folder as a subfolder. I even went and specifically set the output folder specifically as the target folder but it still puts the matting folder outsite. how odd!

![image](https://github.com/user-attachments/assets/22b17d7d-ef40-4129-b1cc-b35531423d11)

**Comment by CVHub520** [comment]
The issue you're experiencing with the "matting" folder being saved outside your current working folder can be addressed by modifying the saving logic in our codebase.

You can find the relevant code in the following file:
https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/rmbg.py

This file contains the logic for handling the matting process and saving the results. By adjusting the code in this file, we can ensure that the "matting" folder is consistently saved as a subfolder of the target folder, regardless of the Windows version.

We appreciate your detailed feedback, as it helps us improve the user experience for all our users. Let us know if you need any further assistance or clarification on this matter.
