### ISSUE TITLE
How to change the default model folder?

### ISSUE THREAD

**Issue by JasonSloan** [CVHub520/X-AnyLabeling#648]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

I know the default folder that stores the model weight is 'xanylabeling_data' under the home directory, how to change it to another place?

**Comment by CVHub520** [comment]
You can create a symbolic link to point to the new folder location.

**Comment by CVHub520** [comment]
Hey @JasonSloan;

Currently, there is no direct way to change the default model folder in X-Anylabeling, you should modify the source code to achieve this.

**Comment by JasonSloan** [comment]
> Hey @JasonSloan;
> 
> Currently, there is no direct way to change the default model folder in X-Anylabeling, you should modify the source code to achieve this.

OK, thank you very much

**Comment by CVHub520** [comment]
Alternatively, you may choose to load the model from a local path. For guidance on how to do this, please refer to our [dedicated guide](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/custom_model.md#loading-built-in-models) on loading built-in models.
