### ISSUE TITLE
注册表下载模型失败！

### ISSUE THREAD

**Issue by JAYCHOU2020** [CVHub520/X-AnyLabeling#65]
error in loading model :could not download or initialize encoder of segment anything

**Comment by aiyou9** [comment]
> 加载模型时出错：无法下载或初始化任何段的编码器

使用魔法，每月免费40gb的 ikuuu点艺术（中文换英文）

**Comment by CVHub520** [comment]
> error in loading model :could not download or initialize encoder of segment anything

您好， @JAYCHOU2020 ，感谢关注 `X-AnyLabeling`，请参考此[文档](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md)，从百度网盘下载权重，走本地加载方式。
