### ISSUE TITLE
NSFW Logo

### ISSUE THREAD

**Issue by IndyVC** [CVHub520/X-AnyLabeling#652]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Why does the logo look like a NSFW variant? \s

**Comment by CVHub520** [comment]
Hey there! @IndyVC,

Could you please specify which design elements gave you this impression?
