### ISSUE TITLE
about input

### ISSUE THREAD

**Issue by yyy1998-i** [CVHub520/X-AnyLabeling#653]
### Search before asking

- [X] I have searched the X-AnyLabeling [model_zoo](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/model_zoo.md) and found no similar model requests.

### Description

Hello, thank you for your excellent achievement, I want to have my own Sam model is loaded into the X-ray AnyLabeling inside, I use netron print sam_model_best_large_ssl_buidnewprocess decoder. Onnx input and output, What should I do if my model has no output from masks? Also, num_points how to define numbers (unlike fixed input image_embeddings: [1,256,64,64]), how can I modify and export the onnx model, I hope you can guide me.
![image](https://github.com/user-attachments/assets/89993002-483c-4e31-979c-25c1408fe077)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
If you're not familiar with ONNX, you can use the PyTorch inference engine directly.
For guidance, check out this [example](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/segment_anything_2_video.py) in the X-AnyLabeling repository.

**Comment by yyy1998-i** [comment]
> If you're not familiar with ONNX, you can use the PyTorch inference engine directly. For guidance, check out this [example](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/segment_anything_2_video.py) in the X-AnyLabeling repository.

Hello author, I did not find The ONNX Export of the SAM in X-AnyLabeling/tools/onnx_exporter. I want to import my own sam model. Will you consider releasing it in the future?

**Comment by CVHub520** [comment]
> > If you're not familiar with ONNX, you can use the PyTorch inference engine directly. For guidance, check out this [example](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/segment_anything_2_video.py) in the X-AnyLabeling repository.
> 
> Hello author, I did not find The ONNX Export of the SAM in X-AnyLabeling/tools/onnx_exporter. I want to import my own sam model. Will you consider releasing it in the future?

You can refer [this](https://github.com/vietanhdev/samexporter#sam-exporter).

**Comment by yyy1998-i** [comment]
> > > If you're not familiar with ONNX, you can use the PyTorch inference engine directly. For guidance, check out this [example](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/segment_anything_2_video.py) in the X-AnyLabeling repository.
> > 
> > 
> > Hello author, I did not find The ONNX Export of the SAM in X-AnyLabeling/tools/onnx_exporter. I want to import my own sam model. Will you consider releasing it in the future?
> 
> You can refer [this](https://github.com/vietanhdev/samexporter#sam-exporter).

Thank you very much!
