### ISSUE TITLE
window的版本不支持用户自定义模型导入吗？如果有麻烦告知怎么导入，谢谢。

### ISSUE THREAD

**Issue by ticshen2019** [CVHub520/X-AnyLabeling#656]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

window的版本不支持用户自定义模型导入吗？如果有麻烦告知怎么导入，谢谢。

**Comment by CVHub520** [comment]
Hey there! @ticshen2019,

You may refer to the following link for information on importing user-defined models: 
https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md

This documentation offers comprehensive instructions and steps that should address your queries on how to import custom models into X-AnyLabeling. 

Should you have any further questions after reviewing the documentation, please feel free to ask.

**Comment by Riki123666** [comment]
支持的，我在图片分类模型上已经成功了
