### ISSUE TITLE
Rough Annotation result in segmentation task.

### ISSUE THREAD

**Issue by hypochlorous** [CVHub520/X-AnyLabeling#662]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Using custom v11-seg model for inference ,the control points of polygon are relatively few.
Is there any parameter about control point counts? Half precision may effect?

I test different resolution, but the auto label is rougher than prediction directly.

**Comment by CVHub520** [comment]
Hi there, @hypochlorous

To address the issue of rough annotation results in the segmentation task, you can adjust the `epsilon_factor` value in the YAML configuration file. This factor is used for epsilon calculation in contour approximation. A smaller value will result in smoother contours but with more points. You can modify this value to achieve the desired level of smoothness in your annotations.

Here's an example of how to set the epsilon_factor in your YAML configuration file:
```
epsilon_factor: 0.001
```

You can adjust the value as needed to get the best results for your specific use case (default 0.005).

Let me know if you have any further questions or need additional assistance.

**Comment by hypochlorous** [comment]
Thanks for your reply.That's exactly what I want
