### ISSUE TITLE
关于自动标注的疑问

### ISSUE THREAD

**Issue by Riki123666** [CVHub520/X-AnyLabeling#663]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

这款软件对图像分类的自动标注是只能写在AutoLabelingResult中的description字段吗？

**Comment by Riki123666** [comment]
还有一个问题，为什么自动推理的时候，显卡利用率很低，标注特别慢（自己加载onnx的时候写一个循环进行推理的时候是很快的，不到10分钟就推理完整个数据集了）

**Comment by Riki123666** [comment]
自己写推理代码的时候是0.016s一张图片，使用软件的时候是0.7s一张图片，都使用的gpu

**Comment by Riki123666** [comment]
发现问题了，当我拿含有100张图片的文件夹进行自动标注时，不到10s就标注完了，但是我打开了包含有10k张图片的文件夹进行自动标注时，速度就慢很多，这算bug吗

**Comment by CVHub520** [comment]
Q: 这款软件对图像分类的自动标注是只能写在AutoLabelingResult中的description字段吗？
A: Yes, you are right. But you can change this behavior by modifying the code.
