### ISSUE TITLE
怎么导出为带掩码的格式或者voc形式的呢

### ISSUE THREAD

**Issue by junliuchengxia** [CVHub520/X-AnyLabeling#668]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

怎么导出为带掩码的格式或者voc形式的呢

### Additional

怎么导出为带掩码的格式或者voc形式的呢

**Comment by CVHub520** [comment]
For detailed instructions on importing and exporting labels, please consult the official [documentation](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#4-%E6%A0%87%E7%AD%BE%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA).
