### ISSUE TITLE
txt is NULL

### ISSUE THREAD

**Issue by asd13723654042** [CVHub520/X-AnyLabeling#672]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

按照手册上的步骤导出的YOLO分割标签txt文件是空的（已经有了配置文件）？

**Comment by CVHub520** [comment]
1. Check if the shape_type is set to 'polygon'. You can quickly verify this by pressing Ctrl+G to open the dialog for a quick scan.
2. Ensure that the annotated classes are included in your custom classes.txt file.

These steps should help address the "txt is NULL" issue. The problem likely stems from either an incorrect shape type or missing class definitions. By verifying these two aspects, you can troubleshoot and potentially resolve the issue.
