### ISSUE TITLE
Request for MOT task annotation enhancements

### ISSUE THREAD

**Issue by TomX32** [CVHub520/X-AnyLabeling#674]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

1.The software needs to be more stable when dealing with continuous copy-and-paste situations.

2.The Reid process should be more reasonable and accurate.

3.When downloading the model, you can consider further improving the user's experience

### Use case

1. The software is not very stable, and the frequency of crashes is high, and a specific scenario is that it is easy to cause crashes when the rectangular box is densely copied and pasted multiple times. At the same time, due to the poor detection effect in some low resolutions, could you develop a "select all" function to quickly and stably migrate all the annotations in one frame to other frames?
2. Auto-labeled ids sometimes jump and break, for example, there is a sequence containing frames 1, 2,..,8, objects A and B appear in the second frame, but A has ID number 1, B only has category information without number, and in the next few frames there are only A, B, and only A is numbered. On the 7th frame, the number of B appears, but it will be numbered as a larger number, 7 or 8, rather than compactly numbering from the number already in the id library, because the expected number is 2.
3. After annotating the same specific sequence and downloading the model, it seems that you don't need to download the model again when you reopen the sequence only after clicking "Run all images at once". However, after not clicking "Run all images at once", even if it is the same model, you still need to re-download the same model when opening different sequences, because of some special network problems, which affects the user experience to a certain extent.

**Comment by CVHub520** [comment]
Hi TomX32,

Thank you for your detailed feedback. I've taken note of the issues you've raised and will address them one by one.

**Regarding software stability:**
I understand that crashes can be frustrating, especially during copy-and-paste operations. We're looking into improving our error handling and recovery mechanisms. In the meantime, could you please provide any specific error messages or logs when these crashes occur? This information would greatly help us diagnose and fix the problem.

**On the 'Reid' process:**
We are indeed working on refining our reidentification algorithms to make them more robust and accurate. Your input is valuable, and we'll consider it as part of our ongoing improvements.

**Improving user experience during model download:**
This is something we're actively considering. We aim to streamline the process and reduce wait times where possible. If you have any suggestions on how we might enhance this aspect further, please let us know!

1. **Software instability:** We appreciate the specifics you provided regarding the crash scenarios. As mentioned earlier, we need those error logs to proceed with debugging.
   
2. **Auto-labeled IDs jumping:** This sounds like a potential bug in our tracking system. We'll investigate this issue thoroughly. Meanwhile, using SAM2-Video's video tracking feature might offer a workaround until we release a fix.

3. **Model downloading inconsistencies:** It seems there might be a misunderstanding. The model should only need to be downloaded once per session. If you encounter repeated downloads, it could indicate a caching issue or a misconfiguration. Please check if clearing your browser cache resolves the problem. If not, please share more details about the behavior you're experiencing so we can troubleshoot further.

If you have any additional comments or observations, feel free to add them here. Your insights are crucial for guiding our development efforts.

Best regards.

**Comment by TomX32** [comment]
For the first point you mentioned, since I'm using the CPU version, I haven't found where to display the error message or the log file, I can only recall the events that occurred at the moment of the crash.

**Comment by CVHub520** [comment]
> For the first point you mentioned, since I'm using the CPU version, I haven't found where to display the error message or the log file, I can only recall the events that occurred at the moment of the crash.

Hi there, to resolve the issue with logging in the terminal, please ensure that you have updated the application to the latest version. This should enable the logging feature as expected. If you encounter any further problems after updating, please let us know.

**Comment by TomX32** [comment]
I installed the latest version, but when it crashes, the mouse pointer changes to a constant circle, and the whole interface cannot be clicked or selected. In the end, I had to force close, and because this was a ".exe" file, I couldn't find any log logs to judge the error message, so I searched the folder where the model was downloaded but found nothing

**Comment by CVHub520** [comment]
Thank you for reporting this issue, TomX32. I apologize for the trouble you're experiencing. To better diagnose and potentially resolve this problem, I recommend using the source code version of the software instead of the compiled .exe file.

**Comment by TomX32** [comment]
there is a probability that two rectangular boxes will be obtained! Then delete one of them, the software crashes, and the following error appears; Another time is also pasting out two boxes at a time, maybe the mouse pointer is at the junction of the two boxes, press Delete, crash.

```
Traceback (most recent call last):
  File "C:\Users\85302\Desktop\X-AnyLabeling-2.4.4\anylabeling\views\labeling\label_widget.py", line 5950, in delete_selected_shape
    self.remove_labels(self.canvas.delete_selected())
  File "C:\Users\85302\Desktop\X-AnyLabeling-2.4.4\anylabeling\views\labeling\widgets\canvas.py", line 955, in delete_selected
    self.shapes.remove(shape)
ValueError: list.remove(x): x not in list
```

**Comment by CVHub520** [comment]
It seems like you're encountering a problem with rectangular boxes and crashes when using certain keyboard shortcuts. To potentially resolve this, we can try disabling a couple of auto-features.

Could you please locate the configuration file named "xanylabeling_config.yaml" in your user directory? 

Once you've found it, open the file in a text editor and look for these two lines:

```yaml
auto_highlight_shape: true
auto_switch_to_edit_mode: true
```

Change both of these to `false`, so it looks like this:

```yaml
auto_highlight_shape: false
auto_switch_to_edit_mode: false
```

Save the file after making these changes. This should disable the auto-highlighting and auto-switching features, which might be contributing to the issue you're experiencing.

After making these changes, please try your workflow again and let us know if the problem persists. If you have any trouble finding or editing the configuration file, don't hesitate to ask for further assistance.
