### ISSUE TITLE
使用矩形框标注时，可以实现亚像素标注，但是移动只能实现像素级移动

### ISSUE THREAD

**Issue by sky1279** [CVHub520/X-AnyLabeling#675]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

我在使用X-AnyLabeling进行矩形框标注时，想要实现在第一帧图像上标注矩形框能够在其他图像上进行矩形框亚像素级移动，比如每次移动0.1像素。

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
We appreciate your innovative thinking, but regret to inform you that implementing this feature will be your responsibility. Unfortunately, we are unable to assist directly with its development at this time. :(
