### ISSUE TITLE
添加对Florence2模型的支持

### ISSUE THREAD

**Issue by woddle** [CVHub520/X-AnyLabeling#679]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

Florence2具有很有的零样本泛化能力，是否可以支持

### Use case

可以不需要提前训练情况下支持进行目标检测，方便了标注，提高了标注效率

### Additional

无

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hello, @woddle! 😄 

We’re happy to let you know that support for the Florence-2 model has been successfully added to X-AnyLabeling. You can now deploy and use this model directly within the platform. If you encounter any issues or need further guidance, please feel free to reach out. 

Happy labeling! 🚀 

Best regards,
X-AnyLabeling Maintainer

**Comment by CVHub520** [comment]
#725

**Comment by nidetaoge** [comment]
Thanks so much for your work! I find that, if you only have CPU, Florence may fail to work which the requirement flash_attn can only be installed on GPU, with the error: 
error in loading model `florence2` with error: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`
When pip install flash_attn: 
flash_attn was requested, but nvcc was not found.

We may need to refer this to support Florence with CPU:
https://huggingface.co/qnguyen3/nanoLLaVA-1.5/discussions/4

**Comment by CVHub520** [comment]
@nidetaoge Thank you for your feedback and the solution you provided! Currently, Florence2 on X-AnyLabeling indeed only supports running on GPUs, and we strongly recommend using a GPU for optimal performance. However, we will consider adding support for CPU devices in future development plans.

We appreciate your understanding and support. If you have any further suggestions, feel free to share them!

**Comment by CVHub520** [comment]
@nidetaoge, thank you for your previous feedback and patience. I am pleased to inform you that the latest branch has added support for CPU devices. Now, Florence2 can run on CPUs, not just GPUs. 

If you encounter any problems or have any suggestions when using the new branch, please feel free to raise them. I will continue to work hard to improve to meet the needs of a wider range of users. Thanks again for your understanding and support!
