### ISSUE TITLE
自定义模型导入bug

### ISSUE THREAD

**Issue by kiitio** [CVHub520/X-AnyLabeling#68]
您好，我又发现了一个bug，当软件导入一个自定义模型以后，再次导入第二个自定义模型软件会闪退，重新启动app.py会发现并没有将第二个模型导入，这意味着首次导入自定义模型之后，只能通过修改当前配置文件来变更自定义模型，
建议：
1.另外是否可以新增一个功能按钮用来删除已经导入的自定义模型，我注意到当前软件自动标注页面右侧的红叉按钮并不能删除模型，这样可以有效避免自定义模型导入过多因而使得下拉列表过长的问题
2.标注完成后的类型转换功能是否可以提供更加丰富的导出设置，比如是否提供train目录、valid目录、以及用来训练的yaml配置文件，方便用户可以快速进行训练，下面我提供了一份转换文件，它会将当前目录的图片和json文件进行转换为txt格式的训练文件并一次性提供好train、valid目录和yaml配置文件，另外还支持字典格式的标注标签更改替换，您如果有需要的可以进行查阅，以便您快速编写转换功能
![image](https://github.com/CVHub520/X-AnyLabeling/assets/106864471/6dbebca0-7175-4563-8268-a55901dd7a7c)
[转换.zip](https://github.com/CVHub520/X-AnyLabeling/files/12656115/default.zip)

**Comment by CVHub520** [comment]
您好， @kiitio ，非常抱歉，关于您提到的 `bug` 这边没能复现出来，目前 `X-AnyLabeling` 默认设置是支持导入5个自定义模型的，并不需要做任何的修改，具体详情可查看下[源码](https://github.com/CVHub520/X-AnyLabeling/blob/55b5a2d57e855a8bffb81924dfc61601a8b96bac/anylabeling/services/auto_labeling/model_manager.py#L207)。

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/8cc93226-e1ab-4084-9a91-7d452858cd2b)

建议1：加载的自定义模型配置会默认缓存到用户目录下的 `.anylabelingrc` 文件中，只需将 custom_models 字段设置为空列表或者删除你不需要的配置即可，例如：

```
# Auto labeling
custom_models: []
```

建议2：导出设置这个主要考虑到用户需求各异，很难去兼顾每个用户的需求，因此设置成统一的导出样式无疑是最合适的，用户可以根据自己的需要写个脚本转换成合适的格式或者数据划分。对于常规的导出样式，目前也已经提供转换脚本给大家使用，可以参考帮助文档中的标签转换章节。
