### ISSUE TITLE
Can you add the ability to dynamically expand and shrink the pixels of all four boundaries?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#680]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

```
import os
import sys

# Default values (set for top, bottom, left, and right)
EXPAND_TOP = 0     # Pixels to expand upwards (negative value to shrink)
EXPAND_BOTTOM = 0  # Pixels to expand downwards (negative value to shrink)
EXPAND_LEFT = 0    # Pixels to expand leftwards (negative value to shrink)
EXPAND_RIGHT = 20   # Pixels to expand rightwards (negative value to shrink)
IMG_WIDTH = 640    # Default image width
IMG_HEIGHT = 640   # Default image height
TARGET_CLASS = 1   # Adjust only this class (e.g., 1 represents qipao)

def adjust_bbox(bbox, top, bottom, left, right, img_width, img_height):
    class_id, x_center, y_center, width, height = bbox
    
    # Convert pixel expansions to normalized values
    expand_top = top / img_height
    expand_bottom = bottom / img_height
    expand_left = left / img_width
    expand_right = right / img_width
    
    # Adjust width and height
    new_width = min(1.0, max(0, width + expand_left + expand_right))
    new_height = min(1.0, max(0, height + expand_top + expand_bottom))
    
    # Adjust the center position based on expansion direction
    x_center = max(new_width / 2, min(1 - new_width / 2, x_center + (expand_right - expand_left) / 2))
    y_center = max(new_height / 2, min(1 - new_height / 2, y_center + (expand_bottom - expand_top) / 2))
    
    return [class_id, x_center, y_center, new_width, new_height]

def process_file(file_path):
    with open(file_path, 'r') as f:
        lines = f.readlines()
    
    new_lines = []
    for line in lines:
        parts = line.strip().split()
        if len(parts) == 5:  # Ensure each line has 5 values
            class_id = int(parts[0])
            bbox = [class_id] + [float(p) for p in parts[1:]]
            
            # Only process the target class
            if class_id == TARGET_CLASS:
                new_bbox = adjust_bbox(bbox, EXPAND_TOP, EXPAND_BOTTOM, EXPAND_LEFT, EXPAND_RIGHT, IMG_WIDTH, IMG_HEIGHT)
                new_line = f"{new_bbox[0]} {new_bbox[1]:.6f} {new_bbox[2]:.6f} {new_bbox[3]:.6f} {new_bbox[4]:.6f}\n"
            else:
                new_line = line  # Keep the original line for non-target classes
            new_lines.append(new_line)
        else:
            new_lines.append(line)  # Keep original line if the format is incorrect
    
    # Overwrite the original file
    with open(file_path, 'w') as f:
        f.writelines(new_lines)
    
    print(f"Processing completed: {file_path}")
    return file_path

def process_folder(folder_path):
    processed_files = []
    for root, _, files in os.walk(folder_path):
        for file in files:
            if file.endswith('.txt'):
                file_path = os.path.join(root, file)
                new_file = process_file(file_path)
                processed_files.append(new_file)
    return processed_files

def main():
    if len(sys.argv) < 2:
        print("Please drag and drop a TXT file or a folder containing TXT files onto this script.")
        input("Press any key to exit...")
        return

    paths = sys.argv[1:]
    processed_files = []

    for path in paths:
        if os.path.isfile(path):
            if path.endswith('.txt'):
                new_file = process_file(path)
                processed_files.append(new_file)
            else:
                print(f"Skipping non-TXT file: {path}")
        elif os.path.isdir(path):
            processed_files.extend(process_folder(path))

    if processed_files:
        print("\nProcessed files:")
        for file in processed_files:
            print(file)
    else:
        print("No TXT files found or processed.")

    print(f"\nProcessing settings:")
    print(f"Expand Up: {EXPAND_TOP} pixels, Expand Down: {EXPAND_BOTTOM} pixels")
    print(f"Expand Left: {EXPAND_LEFT} pixels, Expand Right: {EXPAND_RIGHT} pixels")
    print(f"Image Width: {IMG_WIDTH}")
    print(f"Image Height: {IMG_HEIGHT}")
    print(f"Adjusting Class: {TARGET_CLASS}")

    input("\nPress any key to continue...")

if __name__ == "__main__":
    main()
```
I have already implemented this functionality using a script to expand and shrink the YOLO labels in the TXT file in all four directions and for specific labels. After batch modifying, I import them back into the software for review. This process is a bit inconvenient. So, can you add this functionality directly in the software?

When would this feature be used? The model has been trained, but during inference validation, although the model's annotation positions are correct, the bounding box sometimes has a range that is either too small or too large. Therefore, a batch scaling feature for specific labels is needed. That's why I created this script. However, importing and reviewing each time is really inconvenient and not intuitive enough. So, could we request the developers to add this feature directly into the software? This would allow for easy and intuitive adjustments of the bounding boxes

This makes it easier to adjust the bounding box sizes, which can greatly improve the efficiency of standardization and facilitate the generation and adjustment of training data for the next iteration

**Comment by CVHub520** [comment]
Hey there!

Thanks for bringing up this idea about adding the bounding box adjustment feature directly into the software. I can totally see why you'd want that - it would definitely streamline things compared to your current script-based workflow.

But I gotta admit, I have a few concerns about the whole batch adjustment thing. Here's the thing: every object in an image is unique, right? So their bounding boxes are all different sizes and shapes. Trying to adjust them all in one go might cause more headaches than it solves. You could end up making some boxes way too big while others are still too small.

Don't get me wrong - I'm all for making the process easier. But maybe we need to think about a more flexible solution? Like, what if we had a tool in the software that lets you quickly tweak individual boxes, but also group similar ones together when it makes sense?

What do you think? I'm really curious to hear your thoughts on this. Maybe you've got some ideas I haven't even considered? Let's brainstorm and see if we can come up with something that's both efficient and accurate. Sound good?

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/f2bda4d9-75ee-420a-99d1-ded6fbdeb7e8)
I may not have expressed myself clearly. I hope to have this feature available on each page, rather than in batch mode. It’s the batch usage that has caused some trouble, which is why I'm requesting support from the developers. I would like to see an additional feature in the software interface. For example, in this area of the software, this label currently has no functionality. Here’s my idea: on the current page, this label can have an interactive function. When clicked, it would select all the labels of the same type on the current page. Then, by using the shortcut keys Ctrl + Up/Down/Left/Right, we could adjust the margins of all the same type of labels on the current page by 1 pixel at a time.

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/b574b075-ee8a-4a0d-9777-4b1c0f7e80e8)
Additionally, the software does not have a 'Select All' function. The 'Select All' shortcut (Ctrl+A) has been assigned to activate the AI model function in this software. Therefore, I personally feel that the interaction at this location could also serve as a 'Select All' option. Users could click and drag the mouse to select everything, effectively substituting the missing Ctrl+A function. This is my idea; I wonder if it could be implemented

**Comment by lhj5426** [comment]
Then, Ctrl + Shift + Up/Down/Left/Right reduces the size by 1 pixel

**Comment by CVHub520** [comment]
Hey, I see where you're coming from with these ideas, but I've gotta throw a small wrench in the works here. Even when we're talking about objects of the same class in a single image, their bounding boxes can be all over the place in terms of size and shape. 

Think about it - take a bunch of cars in one photo. You might have a tiny car in the distance, a medium-sized one in the middle, and a huge truck up close. They're all "vehicles," but their boxes would be totally different, right?

So, while I get the appeal of batch adjustments, in reality, it would rarely (if ever) make sense to tweak all these varied boxes the same way. It's like trying to fit everyone with the same shoe size - it just doesn't work.

I'm all for finding ways to speed things up, but we might need to think outside the box (pun intended!) for a solution that actually improves accuracy while saving time. What do you think? Got any other ideas that might tackle this tricky balance?

**Comment by lhj5426** [comment]
This feature was not well thought out on my part. Since my focus is mainly on manga and game UI recognition, I didn’t consider broader applicability. So, I’ll close this one out and just use a script when needed, haha. Thank you for your response!
