### ISSUE TITLE
How do I change the format of the json file for segment anything 2(base)

### ISSUE THREAD

**Issue by WangShuJiu** [CVHub520/X-AnyLabeling#681]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

I want to add the coordinates of the positive and negative points in the return result of segment anything2. How do I add them

**Comment by CVHub520** [comment]
Thank you for your question. Currently, there is no direct way to add the coordinates of the positive and negative points to the result file of segment anything 2 through configuration alone. To achieve this, you would need to modify the source code.

As an alternative, you could consider using the logger to record this information. By adding appropriate logging statements in the code where the positive and negative points are processed, you could capture this data in log files without modifying the main output format.

**Comment by WangShuJiu** [comment]
> Thank you for your question. Currently, there is no direct way to add the coordinates of the positive and negative points to the result file of segment anything 2 through configuration alone. To achieve this, you would need to modify the source code.
> 
> As an alternative, you could consider using the logger to record this information. By adding appropriate logging statements in the code where the positive and negative points are processed, you could capture this data in log files without modifying the main output format.

I have an idea to locate the function in the code responsible for point annotation, retrieve the information of the annotated points, and then use that data in a JSON file. However, I haven’t yet identified the specific function corresponding to this feature.
