### ISSUE TITLE
Can you add a 'Select All' and persistent highlight feature?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#682]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

https://github.com/user-attachments/assets/15c82c4f-db28-4ccb-9ed8-0e19403d3adf

https://github.com/user-attachments/assets/1f8a70da-f8fd-4e10-8228-466b39968824
As shown in the video, I have also taken screenshots.  
Please refer to the images.
![image](https://github.com/user-attachments/assets/89ba9398-10b9-4317-97e9-d4bf9295bd29)

First, as shown in the image, if position 1 is empty, you can quickly select all by moving the mouse to position 2 and dragging upwards.

![image](https://github.com/user-attachments/assets/962357a2-5cac-4fc1-a741-b8aedcad301e)

Then, as shown in the image, when the number of labels exceeds the display capacity of the UI frame, the user must use the scrollbar on the right to scroll down to the very bottom, hold down the Shift key, and drag the scrollbar back to the top to select everything.

This method of not having a “select all” option makes copying position labels on similar pages somewhat inconvenient.
Secondly, if the highlight feature could have an on/off toggle and remain persistent, it would provide a clearer visual representation of the coverage area compared to a single rectangle. Please refer to the two comparison images.
![image](https://github.com/user-attachments/assets/d2c7b7f3-bbfb-4fb4-b5ca-2aacd2fc2ddc)

![image](https://github.com/user-attachments/assets/308df4c2-081e-497a-b583-c1772d2fee69)

Could an additional shortcut be added to show or hide all highlights, similar to the show/hide all rectangles function?

https://github.com/user-attachments/assets/44505773-a374-490d-9344-81727b33ce36

https://github.com/user-attachments/assets/e0e5f3a0-d73c-41a1-b30d-a06978cdbd60
Just like in the video, where a single keypress shows or hides rectangles, could a shortcut key be added to toggle all highlights on and off with one click? This would be extremely helpful for viewing the overall selected areas in the image. These two features have no downsides and would only improve efficiency.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/4ec52623-63bb-4d24-ae2b-723cda569f81)
I believe it is very necessary to have the ability to click the mouse to select all corresponding tags on the current page. The two features mentioned in this issue would only increase efficiency without any negative impact, unlike previous issues that didn't consider the timeframe. I hope the developers can seriously consider adding the options for selecting all tags by category and a persistent toggle for highlight coverage.

**Comment by lhj5426** [comment]
This feature is truly beneficial from a visual perception standpoint. It makes the areas much clearer and allows for an overview of all positions in the entire image, enabling global highlighting when needed.

**Comment by lhj5426** [comment]
The persistent highlight for intuitive viewing is very friendly for my eyes, especially since I use the software for over 10 hours a day for annotation and corrections. It provides a clearer view, eliminating the need to mouse over each rectangle to highlight it just to check the selected areas.
So, I sincerely hope that the developers can add this feature.

**Comment by lhj5426** [comment]
I don't have the technical skills to adjust the model's parameters, so I can only rely on investing a lot of time and effort into bulk annotation and corrections. My goal is to train an ideal model through sheer quantity. That's why I spend a significant amount of time annotating image data every day. After long hours, my eyes get very tired. However, this highlighting feature can really ease the strain on my eyes because it's so intuitive. It allows me to focus on where to make corrections immediately, without having to spend a long time checking before I make adjustments.

**Comment by CVHub520** [comment]
Hi @lhj5426; I understand your need very well, and I appreciate the detailed feedback you've provided about this feature. Your insights on how it would improve your workflow, especially for long annotation sessions, are valuable. 

I'm sorry that i currently don't have the resources to address every request, even though this one seems particularly beneficial. I hope that the community might be able to help develop this feature. Thank you for your passion and dedication to improving the tool!

**Comment by lhj5426** [comment]
Yes, thank you for your response. At least expressing this makes me feel a bit better. Otherwise, using the software every day would be uncomfortable, and keeping it bottled up doesn't feel good either. I hope the community can provide some help. I really regret not pursuing programming.

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/ad220fe4-c8db-4f05-adba-5b209e795ae0)
I tried using "highlight" as a keyword to search through the entire source code and found four files that contain the keyword.

![image](https://github.com/user-attachments/assets/86c793c2-6264-4f82-983c-6ccb644073dd)
Then, I uploaded these four files to the AI and made inquiries about them.


![image](https://github.com/user-attachments/assets/75eb3a61-66b5-4d39-b18e-666535cd8799)
D:\000A\X-AnyLabeling-yolo11\anylabeling\views\labeling\shape.py
I learned that by modifying the part of the source code shown in the image to change `self.selected =` to `True`, the highlights can be set to remain persistent by default.



https://github.com/user-attachments/assets/cbe8ce58-f5b9-4072-b8c4-d5509516b05d
As shown in the video, although there is no "select all" option, achieving a default global highlight solves part of the problem.

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/7ee9c694-7fb9-4dd1-88d1-c596bed05c83)
I also asked the AI how to add a shortcut key to enable global highlighting when needed. However, this involves modifying three files, and since I can only copy and paste, the AI keeps leaving out parts, so I end up unsure where to paste the code or where to find the right spots. It’s honestly beyond my ability, haha. Still, after consulting the AI, I discovered that the developer actually built this feature but just left it disabled by default. This alone was a big win for me, as now it’s much easier on my eyes. Thank you!
