### ISSUE TITLE
It shows "'BQ' is not in list", when exporting COCO label?

### ISSUE THREAD

**Issue by Lucky-person** [CVHub520/X-AnyLabeling#684]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

It shows "'BQ' is not in list", when exporting COCO label? Why?

**Comment by CVHub520** [comment]
Dup of #685.

**Comment by Lucky-person** [comment]
thanks you
