### ISSUE TITLE
Why is' BQ 'not in list displayed when exporting COCO tags?

### ISSUE THREAD

**Issue by Lucky-person** [CVHub520/X-AnyLabeling#685]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Why is' BQ 'not in list displayed when exporting COCO tags?
![屏幕截图 2024-10-17 143524](https://github.com/user-attachments/assets/2777c41c-6996-4be0-a4b5-fae3d089e12a)

**Comment by CVHub520** [comment]
We recommend that you upgrade to the latest version. Regarding your query, you should modify the classes file prior to exporting the COCO dataset. For more detailed instructions, please refer to the following [documentation](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#43-coco%E6%A0%87%E7%AD%BE).
