### ISSUE TITLE
Add new OCR features, such as re-running OCR on manually annotated local box areas.

### ISSUE THREAD

**Issue by Anleeno** [CVHub520/X-AnyLabeling#687]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

Re-running OCR on manually annotated local box areas.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
@Anleeno-Xu, Thank you for your feature request. I'm glad to inform you that the functionality you're looking for is already available in the current version of the software. You can achieve this by making a simple configuration change:

Just take the file `anylabeling/services/auto_labeling/ppocr_v4.py` as example, locate line 232 and set the `replace` parameter to `False`. The line should look like this:

```python
result = AutoLabelingResult(shapes, replace=False)
```

By setting `replace=False`, the model will re-run on the manually annotated local box areas without replacing existing annotations. This allows you to perform custom OCR specifically on the areas you've manually defined.

If you have any questions about implementing this change or if you encounter any issues, please don't hesitate to ask. We're here to help ensure you can make the most of this feature.

**Comment by Anleeno-Xu** [comment]
@CVHub520 Thanks. I have tried that, but it doesn't seem to be what I need. What I mean is running OCR on the localized annotation boxes, rather than the entire image, similar to **_PPOCRLabel_**. The existing functionality only saves our annotation results when running OCR.

**Comment by CVHub520** [comment]
Hey @Anleeno-Xu!

Certainly, I understand your request. Currently, this feature is not supported in our product. However, we are considering incorporating it into future development plans to enhance the user experience and meet more specific needs. We appreciate your feedback and will keep you updated on any progress or changes related to this functionality.

**Comment by CVHub520** [comment]
Now we have supported this feature. Feel free to try it:
https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/optical_character_recognition/text_recognition/README.md
