### ISSUE TITLE
SAM2 reverse propagation

### ISSUE THREAD

**Issue by quantaji** [CVHub520/X-AnyLabeling#688]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

It would be very convenient if I can annotate a frame in the middle of a period where the object is appearing. Therefore, it would be nice if the tool can also reversely propagate key frame's annotation!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
@quantaji The current software doesn't support propagating annotations backwards to frames k-1, k-2, k-3, etc. However, it can propagate annotations forward to subsequent frames k+1, k+2, k+3, and so on. This forward propagation allows you to extend annotations to future frames after annotating an object in frame k. If you need to annotate previous frames, you would need to navigate to those frames and annotate them individually using the process described earlier.

**Comment by quantaji** [comment]
Thank you for your reply! This can some times hard because there are cases when masks appear from a very small area of pixel and tracking from a small mask might be hard for the model and the result might be unreliable. 

I would like to ask if it is possible to put backward (or "reverse" as this is the word used in sam2) propagation as a future feature? This would be really helpful and make this annotation tool outstanding among other tools!

Thanks!
