### ISSUE TITLE
接入的Yolov5是什么版本？我导入YOLOv5s6u的onnx运行无结果，Error in predict_shapes: list index out of range

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#69]
训练的是yolov5s V6 版，
pycharm调试的报错是
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/c43b492e-7d51-4305-ba19-6a020afb522c)

配置config。yaml
```
type: yolov5
name: yolov5s6u
display_name: YOLOv5s6u
model_path: yolov5s6u.onnx
input_height: 640
input_width: 640
stride: 32
nms_threshold: 0.45
confidence_threshold: 0.45
classes:
- sc
```

**Comment by CVHub520** [comment]
您好，接入的是v7版本。

**Comment by aiyou9** [comment]
> 您好，接入的是v7版本。

好的，我这测试了YOLOv5su，yolov5s6u 都是一样的报错 Error in predict_shapes: list index out of range，我在试试V7

**Comment by CVHub520** [comment]
> > 您好，接入的是v7版本。
> 
> 好的，我这测试了YOLOv5su，yolov5s6u 都是一样的报错 Error in predict_shapes: list index out of range，我在试试V7

你的classes类别是否正确呢？可以用netron检查下输出类别定义是否与你的yaml配置文件一致。

**Comment by aiyou9** [comment]
> > > 您好，接入的是v7版本。
> > 
> > 
> > 好的，我这个测试了YOLOv5su，yolov5s6u都是一样的报错Error in Predict_shapes: list index out of range，我在尝试V7
> 
> 你的类类别是否正确呢？可以用netron检查下输出类别定义是否与你的yaml配置文件一致。

检查了，类别是正确的，单类别
![image](https://github.com/CVHub520/X-AnyLabeling/assets/15712822/f8210f60-aee9-40f9-ab17-c6a5d598834e)
怀疑是onnx版本，或者pytorch版本的问题，可能训练与导出使用了不同版本的pytorch

**Comment by aiyou9** [comment]
找到可能的原因了，可能是yolov5.py 和yolov5_SAM.py，不接受单目标，可能classes 只有一个时，就报Error in predict_shapes: list index out of range 错，yolov8.py 可以接受单目标

**Comment by CVHub520** [comment]
不至于，你可以在程序中加个断点简单打印下具体输出什么index

**Comment by aiyou9** [comment]
原因找到了，是我训练yolov8，yolov5的数据集，只有一个class，单目标训练，与检测，有可能报这个错误
https://github.com/ultralytics/ultralytics/issues/4542
