### ISSUE TITLE
最新版本的框比老版本粗了很多，这个框的粗细是否可以设置

### ISSUE THREAD

**Issue by bighaidao** [CVHub520/X-AnyLabeling#691]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

新版本的框比老版本粗了很多，是否可以设置？ 因为其严重影响了我们检查框是否贴边。 感谢

### Additional

是否可以优化或者配置

**Comment by CVHub520** [comment]
For reference, you can check out this [docs](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#76-%E5%AF%B9%E8%B1%A1%E5%B1%9E%E6%80%A7%E8%87%AA%E5%AE%9A%E4%B9%89).
