### ISSUE TITLE
Deployment tutorial for linux environment

### ISSUE THREAD

**Issue by houzhipinghzp** [CVHub520/X-AnyLabeling#694]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Deployment tutorial for linux environment
I have downloaded version 2.4.4, linux deployment has been having problems, please tutorial, thank you！

**Comment by CVHub520** [comment]
Hi @houzhipinghzp,

Could you please provide detailed feedback to facilitate further diagnosis?

**Comment by houzhipinghzp** [comment]
I according to the Quick Start , step by step, create conda, etc.
`conda create --name x-anylabeling python=3.9 -y
conda activate x-anylabeling
pip install onnxruntime

`
![image](https://github.com/user-attachments/assets/60ea7cbb-0d5e-4c7e-be5c-7b4c6b1bbc26)

`pip install -r requirements.txt
pyrcc5 -o anylabeling/resources/resources.py anylabeling/resources/resources.qrc
pip uninstall anylabeling -y


python anylabeling/app.py
`
results are as follows：
![image](https://github.com/user-attachments/assets/032c069f-0180-4eea-9dd2-e244eb93bbdb)

![image](https://github.com/user-attachments/assets/12ff3b0d-6f13-411c-b63e-6161d49ae36e)

**Comment by CVHub520** [comment]
Duplicate of #541.

**Comment by houzhipinghzp** [comment]
3Q，but follow your method，it does not work. oh please, help
![image](https://github.com/user-attachments/assets/8d04c059-0c39-4201-b135-bfeb3f1e6a73)
