### ISSUE TITLE
unsupported operand type(s) for *: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by johnnyallt** [CVHub520/X-AnyLabeling#695]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

I want to cover labels to YoloHBB format, same labels report this error
<img width="456" alt="8B80C7B2-7554-409f-805E-E80FE497E68D" src="https://github.com/user-attachments/assets/94d809be-8aba-4677-8afe-4dd76870f6bf">

**Comment by CVHub520** [comment]
Hi @johnnyallt,

To better assist with the unsupported operand type error you're encountering, could you please provide a sample of your input label format

This would help us identify exactly where the type mismatch is occurring between the 'int' and 'NoneType' values.

For faster assistance, you can also send your example dataset to cv_hub@163.com so we can reproduce and debug the issue directly.

Thank you for providing the additional details.

**Comment by johnnyallt** [comment]
Sorry, It was my personal mistake，Because my original JSON file did not include the width and height of the image
