### ISSUE TITLE
内存占用越来越高导致电脑死机

### ISSUE THREAD

**Issue by DWendou** [CVHub520/X-AnyLabeling#697]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

我是ubuntu20.04系统，我是直接运行python anylabeling/app.py，然后加载文件夹后，随着我标注了200张图像后，我发现我的电脑内存占用从40%直接涨到了99%，然后电脑卡死了，我关闭界面后，又回到40%了。我发现随着标注的数据越来越多，电脑的内存占用越来越大，为什么不能自动清除缓存？

**Comment by CVHub520** [comment]
Duplicate of #625

**Comment by DWendou** [comment]
> Duplicate of #625

非常感谢您的快速回复，那会我检索没搜到这个问题，我下载新版本再去试试，非常感谢。
