### ISSUE TITLE
Fail export coco dataset

### ISSUE THREAD

**Issue by Lucky-watermelon** [CVHub520/X-AnyLabeling#698]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Export/Import

### Bug

![image](https://github.com/user-attachments/assets/907cb606-2925-41f5-87cd-095675317865)
I get this error when I export the coco dataset, but not when VOC and YOLO

### Information

Application Information:
    {'App name': 'X-AnyLabeling', 'App version': '2.4.4', 'Device': 'CPU'}

System Information:
    {'CPU': 'Intel64 Family 6 Model 165 Stepping 2, GenuineIntel',
     'CUDA': 'V12.5.40',
     'GPU': '0, NVIDIA GeForce GTX 1650, 4096',
     'Operating System': 'Windows-10-10.0.19045-SP0',
     'Python Version': '3.9.20'}

Package Information:
    {'ONNX Runtime GPU Version': '1.19.2',
     'ONNX Runtime Version': None,
     'ONNX Version': '1.17.0',
     'OpenCV Contrib Python Headless Version': '4.10.0.84',
     'PyQt5 Version': '5.15.7'}

### Link to a Reproducible Demonstration Video

NONE

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Lucky-watermelon** [comment]
2024-10-30 11:22:21,987 | ERROR   | label_widget:export_coco_annotation:5160 - Error occurred while exporting annotations: local variable 'converter' referenced before assignment

**Comment by CVHub520** [comment]
Thank you for reporting this issue. The bug causing the 'converter' variable reference error during COCO dataset exports has been fixed in the latest version. Please update to the newest release of X-AnyLabeling to resolve this error. 

Let us know if you encounter any other issues.

**Comment by Lucky-watermelon** [comment]
Thanks for your quick reply very much.
After I pulled the new version, it solved the export issue with coco.
But I found another small bug, that is, when I click to open the folder, I need to click a second time before the selection page appears. However, this bug does not affect the use.

**Comment by CVHub520** [comment]
Thank you for letting us know about this behavior. Yes, this is actually the expected behavior - the app activation occurs when you trigger an arbitrary action.

Let me know if you have any other questions or concerns!

**Comment by JokerHDKing** [comment]
2025-04-27 11:57:29,021 | ERROR   | export:on_export_finished:629 - Error occurred while exporting annotations: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
This is newest release of X-AnyLabeling,How can I solve this?

**Comment by CVHub520** [comment]
> 2025-04-27 11:57:29,021 | ERROR | export:on_export_finished:629 - Error occurred while exporting annotations: int() argument must be a string, a bytes-like object or a real number, not 'NoneType' This is newest release of X-AnyLabeling,How can I solve this?

Thanks for reporting this issue. @JokerHDKing 

If you are exporting keypoint data, could you please ensure that you have assigned a `group_id` to each group (which typically includes a detection box and its associated keypoints) during the annotation process? This `group_id` is necessary for X-AnyLabeling to correctly understand the relationships between objects when exporting.

Let us know if this resolves the issue or if you need further assistance.

**Comment by JokerHDKing** [comment]
Thanks for your quick reply very much.with you help,I solve this question.But could you tell me about the relationship between `object_labek` and `group_id` or the difference?
