### ISSUE TITLE
使用自定义的模型的时候暂时还不能使用分割模型？

### ISSUE THREAD

**Issue by Chen94yue** [CVHub520/X-AnyLabeling#7]
我看文档中支持自定义模型，但是并没有给出分割的模型的配置文件写法，比如我基于自己训练的yolov8的分割模型，如何进行模型导入？

**Comment by CVHub520** [comment]
> 我看文档中支持自定义模型，但是并没有给出分割的模型的配置文件写法，比如我基于自己训练的yolov8的分割模型，如何进行模型导入？

感谢关注，争取下个版本支持。

**Comment by CVHub520** [comment]
@Chen94yue 您好，最新的 [v0.1.2](https://github.com/CVHub520/X-AnyLabeling/releases/tag/v0.1.2) 版本已支持自定义分割模型，欢迎尝试。
