### ISSUE TITLE
There is a problem with the exported coco format json file, file_name part

### ISSUE THREAD

**Issue by Lucky-watermelon** [CVHub520/X-AnyLabeling#700]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Export/Import

### Bug

![image](https://github.com/user-attachments/assets/810fc52d-89c0-42d2-80cd-a743cbe73863)
 For the images labeled under the same folder, the output coco format JSON file file_name different, such as "10.jpg" and "..\\label\\12.jpg"

### Information

Application Information:
{'App name': 'X-AnyLabeling', 'App version': '2.4.4', 'Device': 'CPU'}

System Information:
{'CPU': 'Intel64 Family 6 Model 165 Stepping 2, GenuineIntel',
'CUDA': 'V12.5.40',
'GPU': '0, NVIDIA GeForce GTX 1650, 4096',
'Operating System': 'Windows-10-10.0.19045-SP0',
'Python Version': '3.9.20'}

Package Information:
{'ONNX Runtime GPU Version': '1.19.2',
'ONNX Runtime Version': None,
'ONNX Version': '1.17.0',
'OpenCV Contrib Python Headless Version': '4.10.0.84',
'PyQt5 Version': '5.15.7'}

### Link to a Reproducible Demonstration Video

none

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Thank you for reporting this issue. After checking the JSON file, I notice that there are inconsistencies in the `file_name` field format:

- Some entries use simple filenames like `"10.jpg"`, `"11.jpg"`
- Others use relative paths with backslashes like `"..\\label\\12.jpg"`, `"..\\label\\13.jpg"`

I tried but wasn't able to reproduce the problem you mentioned.

Could you please zip your images and corresponding annotation files and send them to [cv_hub@163.com](mailto:cv_hub@163.com)? This will help us understand the exact scenario and better assist you with the problem.

**Comment by Lucky-watermelon** [comment]
The relevant files have been sent

**Comment by CVHub520** [comment]
The issue has been fixed. The file paths in the `file_name` field have been normalized in the COCO format JSON export. Please update to the latest version and let us know if you encounter any further problems.

Thanks for reporting this issue!

**Comment by Lucky-watermelon** [comment]
Thanks for your work, the problem has been solved
