### ISSUE TITLE
How to  modify the default export path for labels?

### ISSUE THREAD

**Issue by pcycccccc** [CVHub520/X-AnyLabeling#702]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Hello! First of all, thank you so much for the hard work in creating such an excellent annotation tool, which makes image annotation much easier and more convenient for everyone. However, I've encountered a small issue during usage. Regarding the already annotated labels, I need to export them in a specific label format I prefer. I noticed that the export path for YOLO labels is by default at the same level as the image file path. I was wondering if this could be made a bit more flexible, or could you kindly inform me where I could modify the default path if needed? Sometimes, a single folder of mine might contain several image folders, and when I have arranged JSON format labels for these images, exporting to the labels folder might cause conflicts, as it deletes the original label files in the labels folder before importing the new ones.

![image](https://github.com/user-attachments/assets/8b36e3d1-199b-4739-985b-0e0f8a541f49)

### Additional

Additionally, as a suggestion to improve the user experience, I noticed that you’ve also created a script for label file conversion. However, this requires using code or commands to accomplish the task. It might be helpful if you could integrate this feature directly into the interface of X-AnyLabelimg.

**Comment by CVHub520** [comment]
@pcycccccc Thank you for your feedback! 

I've just updated the tool to allow custom export paths for YOLO labels. In the latest version, you can now choose any directory for your exported labels through a new "Browse" button in the export dialog. 

This should help prevent conflicts when working with multiple image folders. Please update to the latest version from our GitHub repository to use this feature.
