### ISSUE TITLE
Using GPU for inference does not significantly improve performance

### ISSUE THREAD

**Issue by HFeliks** [CVHub520/X-AnyLabeling#703]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

I have used GPU acceleration, but the improvement is not significant. The inference speed is similar to when using CPU. When I checked the GPU memory usage, I found that it is low, although the GPU is being utilized. How can I resolve this issue?
I use the RTX 4060.

**Comment by CVHub520** [comment]
Hello HFeliks,

Thank you for reaching out. It seems like the GPU acceleration is not providing significant improvement in inference speed compared to CPU usage. One possible reason could be that you are loading too many images at once.

I recommend reducing the number of images loaded per task. For example, try limiting each task to around 2,000 images or fewer. This should help alleviate some of the strain on the GPU and potentially improve performance.

Additionally, it might be helpful to test the inference speed with a smaller batch size, such as processing only 100 images initially. This will give you an idea of how much improvement you can expect when using GPU acceleration.

Please let us know if these suggestions help resolve your issue. I'm here to assist you further if needed.

**Comment by CVHub520** [comment]
Thanks for sharing your output logs! Maybe you can try running a test with YOLOv5s model as well?
