### ISSUE TITLE
convert onnx

### ISSUE THREAD

**Issue by lucky-asia** [CVHub520/X-AnyLabeling#704]
### Search before asking

- [X] I have searched the X-AnyLabeling [model_zoo](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/model_zoo.md) and found no similar model requests.

### Description

After training Medsam with my own dataset, how do I convert the saved weights to onnx?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Here are some examples for your reference: [link](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/custom_model.md#model-export)
