### ISSUE TITLE
linux下运行出现QtCore.abi3.so:undefined symbol:_ZdaPvm version Qt_5

### ISSUE THREAD

**Issue by yang-chenyu104** [CVHub520/X-AnyLabeling#71]
linux下出现这个问题，是pyqt的版本不同还是linux下qt没有链接

**Comment by yang-chenyu104** [comment]
已经解决了

**Comment by yang-chenyu104** [comment]
但总是出现xcb没有找到可能是qt没设置好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月23日(周六) 下午2:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CVHub520/X-AnyLabeling] linux下运行出现QtCore.abi3.so:undefined symbol:_ZdaPvm version Qt_5 (Issue #71)




 
Closed #71 as completed.

**Comment by nrupatunga** [comment]
Anyone still facing this issue and are able to fix it?

**Comment by im8dxw** [comment]
> 已经解决了

请问您是如何解决的，目前我也遇到了这个问题
ImportError: /data/data6/Yinghong/.conda/envs/ml/lib/python3.6/site-packages/PyQt5/QtCore.abi3.so: symbol _ZTI20QTransposeProxyModel version Qt_5 not defined in file libQt5Core.so.5 with link time reference

**Comment by yang-chenyu104** [comment]
重新安装python-qt版本就是版本不符合要和conda环境下的qt版本一致



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月17日(周日) 中午1:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CVHub520/X-AnyLabeling] linux下运行出现QtCore.abi3.so:undefined symbol:_ZdaPvm version Qt_5 (Issue #71)




  
已经解决了
  
请问您是如何解决的，目前我也遇到了这个问题
 ImportError: /data/data6/Yinghong/.conda/envs/ml/lib/python3.6/site-packages/PyQt5/QtCore.abi3.so: symbol _ZTI20QTransposeProxyModel version Qt_5 not defined in file libQt5Core.so.5 with link time reference

**Comment by im8dxw** [comment]
你好，能请问您环境中安装的PyQt和Qt的版本嘛？
因为我发现在Qt官网不能下载5.14.2以上的linux.run文件，但是PyQt是5.15.6或者5.15.7下载的更多
请问您是下载的PyQt和Qt分别是什么版本的？
期待您的回复！


1518832639
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CVHub520/X-AnyLabeling"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月18日(星期一) 上午9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CVHub520/X-AnyLabeling] linux下运行出现QtCore.abi3.so:undefined symbol:_ZdaPvm version Qt_5 (Issue #71)





 重新安装python-qt版本就是版本不符合要和conda环境下的qt版本一致 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年3月17日(周日) 中午1:44 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [CVHub520/X-AnyLabeling] linux下运行出现QtCore.abi3.so:undefined symbol:_ZdaPvm version Qt_5 (Issue #71) 
 
 
 
 
    
 已经解决了 
    
 请问您是如何解决的，目前我也遇到了这个问题 
  ImportError: /data/data6/Yinghong/.conda/envs/ml/lib/python3.6/site-packages/PyQt5/QtCore.abi3.so: symbol _ZTI20QTransposeProxyModel version Qt_5 not defined in file libQt5Core.so.5 with link time reference

**Comment by yang-chenyu104** [comment]
之前是公司电脑版本忘记大概记得是5.16二个版本要一致



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月27日(周三) 晚上11:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CVHub520/X-AnyLabeling] linux下运行出现QtCore.abi3.so:undefined symbol:_ZdaPvm version Qt_5 (Issue #71)




 你好，能请问您环境中安装的PyQt和Qt的版本嘛？ 
 因为我发现在Qt官网不能下载5.14.2以上的linux.run文件，但是PyQt是5.15.6或者5.15.7下载的更多 
 请问您是下载的PyQt和Qt分别是什么版本的？ 
 期待您的回复！ 
 
 
 1518832639 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "CVHub520/X-AnyLabeling"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年3月18日(星期一) 上午9:21 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [CVHub520/X-AnyLabeling] linux下运行出现QtCore.abi3.so:undefined symbol:_ZdaPvm version Qt_5 (Issue #71) 
 
 
 
 
 
  重新安装python-qt版本就是版本不符合要和conda环境下的qt版本一致  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2024年3月17日(周日) 中午1:44  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [CVHub520/X-AnyLabeling] linux下运行出现QtCore.abi3.so:undefined symbol:_ZdaPvm version Qt_5 (Issue #71)  
   
   
   
   
      
  已经解决了  
      
  请问您是如何解决的，目前我也遇到了这个问题  
   ImportError: /data/data6/Yinghong/.conda/envs/ml/lib/python3.6/site-packages/PyQt5/QtCore.abi3.so: symbol _ZTI20QTransposeProxyModel version Qt_5 not defined in file libQt5Core.so.5 with link time reference
