### ISSUE TITLE
自定义的实例分割模型无法实现自动化标注

### ISSUE THREAD

**Issue by yiyang94** [CVHub520/X-AnyLabeling#711]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

我使用 YOLOv11x-seg.pt 训练的实例分割模型，无法实现自动化多边形标注功能。当我使用的时候,图片没有正常的被自动化标注!

**Comment by CVHub520** [comment]
请参考官方文档：https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md













在 2024-11-13 22:41:43，"yiyang94" ***@***.***> 写道：

Search before asking
I have searched the X-AnyLabeling Docs and issues and found no similar questions.
Question

我使用 YOLOv11x-seg.pt 训练的实例分割模型，无法实现自动化多边形标注功能。当我使用的时候,图片没有正常的被自动化标注!

Additional

No response

**Comment by CVHub520** [comment]
Hi @yiyang94,

The current version of X-AnyLabeling only supports ONNX model format for inference. You'll need to export your YOLOv11x-seg.pt model to ONNX format (.onnx) before using it in X-AnyLabeling.

Please check our [custom model integration guide](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md) for more details on supported model formats and integration steps.

Let me know if you have any questions.

Best regards

**Comment by liumufenghua** [comment]
如果只改变分类的类别，使用不同参数量的模型需要加载未适配的用户自定义模型操作吗

**Comment by liumufenghua** [comment]
你好，如果加载yolo11的其他分割模型，并且设定新的类别，需要加载未适配的用户自定义模型这一步吗？

**Comment by yiyang94** [comment]
> 您好 ，
> 
> 当前版本的 X-AnyLabeling 仅支持 ONNX 模型格式进行推理。在 X-AnyLabeling 中使用 YOLOv11x-seg.pt 模型之前，您需要将其导出为 ONNX 格式 （.onnx）。
> 
> 请查看我们的[自定义模型集成指南](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md)，了解有关支持的模型格式和集成步骤的更多详细信息。
> 
> 如果您有任何问题，请告诉我。
> 
> 此致敬意


尊敬的作者您好!
首先抱歉我没有对问题有一个清晰的描述! 在此我进行一个清晰的描述!
我使用多边形进行标注了很多图片,
然后使用yolov11x-seg.pt进行训练,
我获取了一个bast.pt,
我将这个bast.pt转换成了onnx文件,
并且设置了yaml文件,
我使用了ai标注功能,选中了指向我训练好的onnx文件的yaml文件,
这个时候是能够正常开启自动化标注功能的,但是ai自动化标注的是长方形而不是多边形,

举个例子:
                图片里面有一个不规则形状的石头,
                当我标注的时候用的是多边形进行标注(将石头的形状用多边形标注出来),
                训练的时候也是用yolov11-seg的分割模型进行训练,
                当我使用这个训练好的模型进行ai标注的时候,ai却没有将这个石头进行多 
                边形标注,而是长方形或者正方形进行标注,这不是我想要的.

我想要的效果是: 我使用多边形标注图片里面一块不规则形状的石头,使用分割模型训练出来以后,将这个模型作为批量标注的基础模型,当我执行批量标注的时候,图片里面的石头能够被ai使用多边形进行标注!

请问有没有什么好的办法能够实现?

十分感谢作者大人能够给予指点!

**Comment by yiyang94** [comment]
> 你好，如果加载yolo11的其他分割模型，并且设定新的类别，需要加载未适配的用户自定义模型这一步吗？

不是的,我的意思是我用自己训练出来的分割类型的模型,不能用于自动化多边形标注的基础模型,或许是yaml文件写错还是怎么,目前不清楚,现在还是用标注软件里面自带的模型进行半自动化标注,也就是我点击以下,模型自动帮我选取一块区域,然后我自己再进行保存,但是我想要的是一键全部自动进行标注

**Comment by CVHub520** [comment]
@yiyang94, could you please share your converted ONNX model along with the custom configuration YAML file?

**Comment by liumufenghua** [comment]
ok，非常感谢，刚开始用这个标注工具，请问yolo分割的平滑设定在哪？

**Comment by yiyang94** [comment]
fff

> @yiyang94，您能否分享转换后的 ONNX 模型以及自定义配置 YAML 文件？


是的,我可以上传了我的onnx文件和yaml配置文件,

**Comment by yiyang94** [comment]
> @yiyang94，您能否分享转换后的 ONNX 模型以及自定义配置 YAML 文件？


文件经过压缩,但是还是感觉体积太大了
提示: 文件大小太大：允许 25 MB，但尝试上传 194 MB。

**Comment by yiyang94** [comment]
> @yiyang94，您能否分享转换后的 ONNX 模型以及自定义配置 YAML 文件？

经过压缩onnx文件,显示文件体积过大,无法在这里分享onnx文件和yaml文件,请给我一个邮箱,谢谢
文件体积过大：允许 25 MB，但尝试上传 194 MB。

**Comment by CVHub520** [comment]
> ok，非常感谢，刚开始用这个标注工具，请问yolo分割的平滑设定在哪？

```YAML
type: yolo11_seg
name: yolo11s-seg-r20240930
display_name: YOLO11s-Seg Ultralytics
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.4/yolo11s-seg.onnx
nms_threshold: 0.45
confidence_threshold: 0.25
...
epsilon_factor: 0.005
...
```

**Comment by yiyang94** [comment]
> > > @yiyang94，您能否分享转换后的 ONNX 模型以及自定义配置 YAML 文件？
> > 
> > 
> > 经过压缩onnx文件,显示文件体积过大,无法在这里分享onnx文件和yaml文件,请给我一个邮箱,谢谢 文件体积过大：允许 25 MB，但尝试上传 194 MB。
> 
> [cv_hub@163.com](mailto:cv_hub@163.com)

文件已经通过邮件发送,请作者大人过目并提出修改意见,谢谢!

**Comment by yiyang94** [comment]
> 从您提供的 yaml 文件来看，它似乎指向检测（Det）输出，但您应该指向分割（Seg）输出。
> 
> 作为参考，请检查此配置文件：[https：//github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolo11s_seg.yaml](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolo11s_seg.yaml)

oh!!十分感谢!!我一直怀疑我的yaml文件没写正确,但我又不知道怎么编写yaml文件,这对我来说十分重要!!对我的帮助非常大!!但目前我没有时间验证这个做法是否可行!晚上有时间了我就去试试!!!十分感谢作者的指导!!

**Comment by yiyang94** [comment]
> 从您提供的 yaml 文件来看，它似乎指向检测（Det）输出，但您应该指向分割（Seg）输出。
> 
> 作为参考，请检查此配置文件：[https：//github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolo11s_seg.yaml](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/configs/auto_labeling/yolo11s_seg.yaml)

依据这个yaml配置文件,当我试图选定自定义模型时显示异常,异常信息如下:
2024-11-20 19:02:44,407 | ERROR   | model_manager:load_custom_model:248 - An error occurred while loading the custom model: The model type {model_config['type']} is not supported.

我并没有修改官方的yaml文件,读取是失败的,或许并不支持 yolo11_seg ,因为异常提示不支持 yolov11_seg.
当然,我也曾试图更改官方的yaml文件,依然提示异常,无法选定自定义的模型,目前为止只有 type:yolo8 是可行的!
作者是否有新的解决方案?

**Comment by CVHub520** [comment]
@yiyang94 
https://docs.ultralytics.com/
