### ISSUE TITLE
自定义标签的名字

### ISSUE THREAD

**Issue by left0ver** [CVHub520/X-AnyLabeling#712]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

<img width="1480" alt="image" src="https://github.com/user-attachments/assets/d40fc4a5-dd89-4df1-a31f-3d67f35ab3dd">
我使用GroundingSAM2进行AI自动标注的时候，例如我的prompt 是silkworm ，当他自动标注完之后的标签也是silkworm ，有没有办法可以自定义标签的名字

**Comment by CVHub520** [comment]
![image](https://github.com/user-attachments/assets/c0ad7411-d208-4440-ad87-0fa9792b14ce)
