### ISSUE TITLE
一次运行所有图片，并没有使用GPU。

### ISSUE THREAD

**Issue by KingBoyAndGirl** [CVHub520/X-AnyLabeling#715]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question
![image](https://github.com/user-attachments/assets/ca49b788-a642-4eb5-982d-0781d66ade6b)

![image](https://github.com/user-attachments/assets/b3c4ab53-610b-47e9-8b37-a3c36a4e9928)

一次运行所有图片，并没有使用GPU，但单独运行（i）会使用gpu
模型：yolov11 sem
平台：win11

### Additional

期待可以解决这个问题

**Comment by CVHub520** [comment]
@KingBoyAndGirl, Hi, thank you for reporting this issue! To help us investigate the problem, could you please provide the following additional information? 

1. **Terminal Output**: Include any logs or error messages generated when running the application.
2. **Converted ONNX Model Shape Information**: You can visualize this using tools like [Netron](https://netron.app/) and share the model's input/output details.
3. **Custom YAML Configuration File**: If you've modified or are using a custom YAML configuration file, please share its contents.

This information will help us better understand the problem and provide a more accurate solution. Thank you!

**Comment by wangsujia** [comment]
did you and how did you solve the problem? I run my labeling program on ubuntu and did not use a custom yaml but still came across with this problem.
