### ISSUE TITLE
Error occurred while exporting yolo obb labels

### ISSUE THREAD

**Issue by zsktju** [CVHub520/X-AnyLabeling#716]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Export/Import

### Bug

![屏幕截图 2024-11-22 161135](https://github.com/user-attachments/assets/b2ad6f2e-ae15-47bd-bea0-e437ccd510ba)
![屏幕截图 2024-11-22 161233](https://github.com/user-attachments/assets/f36f3729-4f62-43b7-8b57-b4b9c9afcde7)
![屏幕截图 2024-11-22 161254](https://github.com/user-attachments/assets/b130adff-3655-4d03-940c-bc6f473afeb9)
When i finish the labelling on a picture, i want to export the label to yolo obb format. But it will fail and prompt a dialog saying 
![点击输出yolo  obb](https://github.com/user-attachments/assets/ffd855c9-c218-490b-ac3f-5f8a5c920606)

### Information

Application Information:
    {'App name': 'X-AnyLabeling', 'App version': '2.4.4', 'Device': 'CPU'}

System Information:
    {'CPU': 'Intel64 Family 6 Model 183 Stepping 1, GenuineIntel',
     'CUDA': 'V11.6.55',
     'GPU': '0, NVIDIA GeForce RTX 3060, 12288',
     'Operating System': 'Windows-10-10.0.22631-SP0',
     'Python Version': '3.9.20'}

Package Information:
    {'ONNX Runtime GPU Version': '1.19.2',
     'ONNX Runtime Version': '1.19.2',
     'ONNX Version': '1.17.0',
     'OpenCV Contrib Python Headless Version': '4.10.0.84',
     'PyQt5 Version': '5.15.7'}

### Link to a Reproducible Demonstration Video

链接: https://pan.baidu.com/s/1HecyxQf8h3LdNmgoWbxPuQ?pwd=1111 提取码: 1111 复制这段内容后打开百度网盘手机App，操作更方便哦

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Please adhere to the guidelines provided in the [instruction](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md#41-yolo-annotation) to export your custom dataset. Additionally, ensure that you select the ‘classes.txt’ file for upload.
