### ISSUE TITLE
希望增加功能：记录缩放的位置

### ISSUE THREAD

**Issue by thgpddl** [CVHub520/X-AnyLabeling#718]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

当前项目已具备记录图片缩放比例的功能，并能自动应用这一比例到后续图片的缩放上。然而，现有的自动缩放功能默认以图片的中心点作为参照进行缩放。这导致当关注点位于图片边缘，例如左下角时，用户不得不先进行缩放，然后再手动调整位置。建议增加一个功能，即在记录缩放比例的同时，也保存当前的视图位置。这样，在新图片中应用缩放比例后，用户关注的区域（如左下角）能够保持在相同的相对位置，无需额外的调整。

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hi, @thgpddl;

After careful consideration; I think that retaining the previous zoom position when importing images of different sizes may cause unintended errors. Therefore, this feature will not be supported for now. I appreciate your input and look forward to your future suggestions. 🚀
