### ISSUE TITLE
How do i export the data that i labeling to yolo

### ISSUE THREAD

**Issue by JesussBeck** [CVHub520/X-AnyLabeling#722]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

When i click export to yolo-seg annotation. It want me select a specific classes file. So what does it mean by that, i dont understand

### Additional

Help please

**Comment by CVHub520** [comment]
Thank you for your inquiry. Please refer to the provided documentation for assistance. [link](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md#41-yolo-annotation)
