### ISSUE TITLE
标注小目标时，标签文字会挡住目标

### ISSUE THREAD

**Issue by suiyi146** [CVHub520/X-AnyLabeling#723]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

![QQ20241129-043031](https://github.com/user-attachments/assets/471b3d57-b9da-4fa6-a37d-2566dfa09104)
![QQ20241129-043045](https://github.com/user-attachments/assets/673d4cf4-7c29-42af-a5d5-96bf02f0606b)
被文字挡住后十分不方便检查，能否将标签文字改到矩形框外

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Thank you for the feedback on the label positioning issue. We appreciate you taking the time to share your thoughts. The current design does have some limitations, as you noted - the label item cannot be moved outside the box where it is currently designed for the description field.

We will review this limitation and consider ways to enhance the feature to provide more flexible label positioning options in a future update. In the meantime, using the Ctrl+L keyboard shortcut is a good temporary workaround to hide the label if it is obstructing the view.

Please feel free to provide any additional suggestions or use cases that could help us improve the functionality. We're committed to making the tool as user-friendly as possible.
