### ISSUE TITLE
 model_manager:predict_shapes:2123 - Error in predict_shapes: list index out of range

### ISSUE THREAD

**Issue by lz1pu** [CVHub520/X-AnyLabeling#724]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

1.我使用这个命令得到我的onnx文件：
    model = YOLO(r'E:\Desktop\yolo\ultralytics-20240609\runs\Tomatov5\yolov8n-300\weights\best.pt')
    model.export(format='onnx')
（best.pt是我自己训练得到的yolov8s模型，class=3）
2.我在x-anylabeling使用自动标注，配置文件如下：
type: yolov8
name: yolov8n-r20230415
display_name: yolov8_tomaot
model_path: best.onnx
confidence_threshold: 0.45
input_height: 640
input_width: 640
nms_threshold: 0.45
score_threshold: 0.5
stride: 32
classess:
  - fully-ripe
  - semi-ripe
  - green
  
3.当我点击推理图片的按钮后，命令窗口报错：
model_manager:predict_shapes:2123 - Error in predict_shapes: list index out of range

ONNX和yaml在一个文件夹下面，并且类别信息可以对的上，为什么出错呢

### Additional

这是我的权重和onnx模型

**Comment by CVHub520** [comment]
Hey there! @lz1pu:

The error is caused by incorrect configuration. The `strides` parameter is only compatible with yolov5-v5.0 and below. Please remove this parameter. For more details, refer to the official documentation: [Custom Model Guide](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md).

**Comment by lz1pu** [comment]
我将配置改成下面这样
type: yolov8
name: yolov8n-r20241129
display_name: yolov8_tomaot
model_path: best.onnx
nms_threshold: 0.45
confidence_threshold: 0.25
classess:
  - fully-ripe
  - semi-ripe
  - green
 
还是不可以，报同样的错误，这个yaml我尝试了很多次，都不可以的，还尝试过把nms_threshold和confidence_threshold删除

**Comment by lz1pu** [comment]
找到问题了，yaml文件中classes这个单词拼写错误。

**Comment by CVHub520** [comment]
🎉 Great to hear you’ve identified and resolved the issue! Typos can be tricky to catch sometimes. 😄 

If you encounter any more questions or need further assistance, feel free to open another issue—I'm here to help.

Happy labeling! 🚀
