### ISSUE TITLE
当物体存在遮挡关系时标签值叠加的问题

### ISSUE THREAD

**Issue by winner-4** [CVHub520/X-AnyLabeling#726]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

标注的时候往往会遇到物体相互遮挡，在标注完导出为mask时，标签值是两个标注值的叠加，例如14+15=29，而这不是我想要的，我想要的是标签值赋值为最上面区域的label，请问怎么解决这个问题呢？

**Comment by CVHub520** [comment]
Try to modify [here](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/views/labeling/label_converter.py#L1345C1-L1411C34)

**Comment by winner-4** [comment]
> Try to modify [here](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/views/labeling/label_converter.py#L1345C1-L1411C34)

非常感谢，根据你的提示已经解决了这个问题。

**Comment by CVHub520** [comment]
I'm glad to hear that! 🙌 

I’ve also just updated the feature to address this exact issue. 🎉 Please pull the latest changes and give it a try. Let me know if you encounter any further problems. Your feedback is always appreciated! 🚀
