### ISSUE TITLE
Can we use UPN with CPU?

### ISSUE THREAD

**Issue by nidetaoge** [CVHub520/X-AnyLabeling#727]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Can we use UPN with CPU? Thanks so much!

**Comment by CVHub520** [comment]
Thank you for bringing this to our attention. We’re sorry for the inconvenience, but it seems that the UPN currently does not implement the CPU version of `MultiScaleDeformableAttention` ops. 

We appreciate your understanding and will keep this in mind for future updates. If you have any other questions or concerns, feel free to reach out.
