### ISSUE TITLE
希望在mask里增加一个exclusion的功能

### ISSUE THREAD

**Issue by qbhnkkk** [CVHub520/X-AnyLabeling#728]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

我只要黑色区域的圆环部分，所以想要增加exclusion的功能，画出黑色圆的最外面的边缘（polygon）和白色的圆的边缘（exclusion），能否开发出这个功能？
![fea77f6785db2fdc294d7ded8378311](https://github.com/user-attachments/assets/9abb8cbd-27b8-4203-aff7-174d4f84d9b9)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Thank you for your suggestion. You can achieve this functionality by separately annotating the outer and inner boundaries using polygons shape. After that, you can write a custom script to process the annotations according to your specific requirements.

Let me know if you need further assistance!
