### ISSUE TITLE
标注小目标时，标注框比较粗，请问在哪个地方调整标注框的粗细

### ISSUE THREAD

**Issue by pand100** [CVHub520/X-AnyLabeling#729]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

标注小目标时，主要遇到以下几个问题：
1、标注小目标时，在不放大图像的情况下，标注框比较粗，看着会挡住挡住部分标注的物体，不知道在哪个位置调整这个标注框。
2、标注小目标时需要放大图像，鼠标点击图像拖动比较符合操作习惯，希望可以增加这部分功能。
3、（目标检测）自动标注的过程中，如果某一个物体被被检测为两种物体，且两个标注框完全重合，该怎么发现这种情况。

**Comment by poearrow** [comment]
我只知道第一个问题的解决办法：
1、关闭软件
2、找到用户主目录下面的.xanylabelingrc文件，在你的系统上可能是隐藏的。打开这个文件，找到line_width，将后面的数字修改为2，保存，关闭这个文件。
3、重新打开软件

**Comment by CVHub520** [comment]
Thank you for raising your questions. Here are the responses to your concerns:

1. Regarding custom object attributes, please refer to the following guide: [[Custom Object Attributes Guide](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#76-%E5%AF%B9%E8%B1%A1%E5%B1%9E%E6%80%A7%E8%87%AA%E5%AE%9A%E4%B9%89)](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#76-%E5%AF%B9%E8%B1%A1%E5%B1%9E%E6%80%A7%E8%87%AA%E5%AE%9A%E4%B9%89).

2. For zooming in and out on an image, you can hold the `Ctrl` key and use the mouse scroll wheel to zoom in or out around the cursor's current position. Additionally, you can press `Ctrl + Shift + n` to cycle through targets, which is especially helpful for inspecting small objects.

3. Currently, there is no direct feature for filtering. However, you can verify objects via the object editing panel on the right. By clicking on a specific label, the corresponding shape will be highlighted.
