### ISSUE TITLE
PyQt5 tool

### ISSUE THREAD

**Issue by mingtianquan** [CVHub520/X-AnyLabeling#730]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Excuse me, I need to customize the implementation of some buttons and functions myself. How do I load and design the UI
I don't see a. ui file in the source code directory. How can I use PyQt5 tools to add designs to the interface

**Comment by CVHub520** [comment]
Yes, this is the corresponding UI file.
