### ISSUE TITLE
The project is very good. Do you want to add or cancel the R build operation setting? Hold down the left mouse button

### ISSUE THREAD

**Issue by mingtianquan** [CVHub520/X-AnyLabeling#731]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

The project is very good. Do you want to add or cancel the R build operation setting? Hold down the left mouse button

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mingtianquan** [comment]
I think it's inconvenient to press the R key once for every annotation

**Comment by mingtianquan** [comment]
The created label cannot be deleted?

**Comment by CVHub520** [comment]
> The created label cannot be deleted?

Please make sure you are in edit mode. For more detail, refer to: https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#22-%E7%BC%96%E8%BE%91%E5%AF%B9%E8%B1%A1
