### ISSUE TITLE
打不开目录

### ISSUE THREAD

**Issue by mytk2012** [CVHub520/X-AnyLabeling#732]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

之前运行的都可以，但是今天忽然打不开目录了，能打开图片

### Information

之前运行的都可以，但是今天忽然打不开目录了，能打开图片

### Link to a Reproducible Demonstration Video

之前运行的都可以，但是今天忽然打不开目录了，能打开图片

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Please provide more detailed context.

**Comment by northhorse0208** [comment]
请问你这个问题解决了吗?我今天也碰到了同样的问题

**Comment by CVHub520** [comment]
> 请问你这个问题解决了吗?我今天也碰到了同样的问题

Use the source code to run and monitor the terminal log.

https://github.com/CVHub520/X-AnyLabeling/issues/1230
