### ISSUE TITLE
目标放大标注时候，部分目标需要拽动画布进行标注

### ISSUE THREAD

**Issue by rw1995** [CVHub520/X-AnyLabeling#733]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

目标放大标注时候，部分目标需要拽动画布进行标注
![Snipaste_2024-12-06_16-52-28](https://github.com/user-attachments/assets/2d27634e-640b-4acc-b696-a52d1ebac81d)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hey there! @rw1995, thank you for your suggestion!  

To address the requested functionality, here’s how the proposed interactions can work:  

1. **Move the Entire Object**:  
   When the cursor moves inside the polygon object area and the object is highlighted, you can move the entire object.  

2. **Add a New Vertex**:  
   When the cursor is on the edge of the polygon, dragging will add a new vertex at the desired location.  

3. **Edit or Remove Vertices**:  
   - When the cursor is on a polygon vertex, you can drag to move the selected vertex.  
   - To remove a vertex, hold the **Shift** key and left-click on the vertex to delete it.  

This workflow will make polygon editing more intuitive and efficient. Let us know if you have additional suggestions or enhancements!
