### ISSUE TITLE
我想将标注的格式导出为yolopose,遇见了报错| ERROR   | label_widget:export_yolo_annotation:4869 - Error occurred while exporting annotations: 'box_label'

### ISSUE THREAD

**Issue by MOON1234567890A** [CVHub520/X-AnyLabeling#736]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

我发现yolopose并没有兼容最新的yolov11的用户指南，参照报错我将我的yaml改为了
![image](https://github.com/user-attachments/assets/259edda9-1038-492e-83e5-d3ac8a7d7686)
![image](https://github.com/user-attachments/assets/70b70750-ab15-4a6c-94df-961d67945f65)
但是依然出现了问题，请问我该如何修改，或者是支持的是哪一个版本的yolopose？
![image](https://github.com/user-attachments/assets/a857604d-0a71-4722-bf66-1585015ec7f2)

**Comment by CVHub520** [comment]
Hello, please export according to the [tutorial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/user_guide.md#41-yolo%E6%A0%87%E7%AD%BE). 

In particular, you need to organize your yaml file according to the following [format](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/yolov8_pose.yaml).

**Comment by CVHub520** [comment]
Hello, mixed data structures are not supported. You should define a corresponding set of key points for each category.

**Comment by MOON1234567890A** [comment]
> 您好，不支持混合数据结构。您应该为每个类别定义一组相应的关键点。

你好，修改为这样，依然存在相同的问题
![image](https://github.com/user-attachments/assets/fa9bbf5b-f28c-467c-957a-dbb8f68df5c4)

**Comment by CVHub520** [comment]
For pose estimation annotation, each set of key points must have a corresponding bounding box (rectangle) annotation. When processing a set of key points, if the corresponding bounding box annotation cannot be found, data["box_label"] will not exist, thus causing an error. 

Specifically, you can set a breakpoint for debugging at [here](https://github.com/CVHub520/X-AnyLabeling/blob/4118efdc37987134344fd10e5010113ed36f41e4/anylabeling/views/labeling/label_converter.py#L883).

**Comment by MOON1234567890A** [comment]
> For pose estimation annotation, each set of key points must have a corresponding bounding box (rectangle) annotation. When processing a set of key points, if the corresponding bounding box annotation cannot be found, data["box_label"] will not exist, thus causing an error.
> 
> Specifically, you can set a breakpoint for debugging at [here](https://github.com/CVHub520/X-AnyLabeling/blob/4118efdc37987134344fd10e5010113ed36f41e4/anylabeling/views/labeling/label_converter.py#L883).

感谢提示，我仔细检查了之后，发现，问题出在json上面，我的json来源于labelme，我仅仅只修改了imagepath，但是转出需要"shape_type": "rectangle",而不是"shape_type": "polygon",，修改之后便没有报错了
![image](https://github.com/user-attachments/assets/0e5e7c0f-f494-4b80-9dab-bf17d6bd10ae)

**Comment by CVHub520** [comment]
Very glad to hear that you have found and solved the problem! If you have any further questions, please feel free to contact me at any time.

Enjoy labeling! 😄
