### ISSUE TITLE
用2.5版本的open_vision，加载时报错了，请问是什么原因呢？

### ISSUE THREAD

**Issue by jammingchiu** [CVHub520/X-AnyLabeling#737]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

2024-12-11 14:28:03,868 | INFO    | app:main:159 - 🚀 X-AnyLabeling v2.5.0 launched!
2024-12-11 14:28:03,869 | INFO    | app:main:162 - ⭐ If you like it, give us a star: https://github.com/CVHub520/X-AnyLabeling
2024-12-11 14:28:03,882 | INFO    | config:get_config:83 - 🔧️ Initializing config from local file: C:\Users\xxx\.xanylabelingrc
2024-12-11 14:28:47,024 | ERROR   | model_manager:_load_model:1103 - ❌ Error in loading model: open_vision with error: OpenVision model will not be available. Please install related packages and try again.

**Comment by CVHub520** [comment]
Please follow the instacution [hear](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md#11-%E4%BB%8E%E6%BA%90%E7%A0%81%E8%BF%90%E8%A1%8C) to install related packages and try it again.

**Comment by hsiong** [comment]
**As shown in the PR**, modify open_vision.py as follows:

```
try:
    import torch
    from .visualgd.datasets import transforms as T
    from .visualgd.registry import MODULE_BUILD_FUNCS
    from .visualgd.util.misc import nested_tensor_from_tensor_list
    from .visualgd.config.cfg_handler import ConfigurationHandler
    
    OPEN_VISION_AVAILABLE = True
except ImportError as e:
    print(f"ImportError: {e}")
    OPEN_VISION_AVAILABLE = False
```

Additionally, the following dependencies are required:

```
transformers
addict
yapf
pycocotools
```

**Comment by hsiong** [comment]
**As shown in the PR**, modify `open_vision.py` as follows:

```
try:
    import torch
    from .visualgd.datasets import transforms as T
    from .visualgd.registry import MODULE_BUILD_FUNCS
    from .visualgd.util.misc import nested_tensor_from_tensor_list
    from .visualgd.config.cfg_handler import ConfigurationHandler
    
    OPEN_VISION_AVAILABLE = True
except ImportError as e:
    print(f"ImportError: {e}")
    OPEN_VISION_AVAILABLE = False
```

Additionally, the following dependencies are required:

```
transformers
addict
yapf
pycocotools
```

Furthermore, comment out the following line in `ms_deform_attn.py`:

```
# import MultiScaleDeformableAttention as _C
```

**Comment by nanshen-ctf** [comment]
加载open_vision模型时报错，报错信息是：QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'，怎么解决
