### ISSUE TITLE
SAM模型如何输入mask作为prompt

### ISSUE THREAD

**Issue by Ggstuddu** [CVHub520/X-AnyLabeling#738]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

我看论文和SAM的官网提到可以使用mask输入作为prompt，我想试一下这个功能的效果，但是X-Anylabeling代码好像暂时没有支持这个功能。
请问大佬有打算在未来实现这个功能吗？

**Comment by CVHub520** [comment]
Hello, thank you for your attention! Currently, there is no plan to consider supporting mask prompt interaction. This is not a core function.

**Comment by Ggstuddu** [comment]
感谢大佬的及时回复，也十分感谢你开发了这么好用的标注软件。
