### ISSUE TITLE
The .json mask file exported by SAM auto-tagging is not available

### ISSUE THREAD

**Issue by hugogo07** [CVHub520/X-AnyLabeling#739]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Sorry to bother you, but I'm having problems labeling images with the latest version of [X-AnyLabeling-CPU.exe]ai autolabeling function, i.e., the autogenerated mask cannot be edited and the exported .json file does not contain the autolabeled data.
[New_A_S1_0_1024_1024_2048.json](https://github.com/user-attachments/files/18108242/New_A_S1_0_1024_1024_2048.json)
<img width="1280" alt="a3fc2b1eed81c25022d3d69c8635175" src="https://github.com/user-attachments/assets/345b4af0-eb46-47f5-96c1-e39169877b7a" />

**Comment by CVHub520** [comment]
By the way, I recommend using the app through the source code to access more detailed logs.

**Comment by hugogo07** [comment]
Solved！Thank you very much.
