### ISSUE TITLE
快捷键失效和建议

### ISSUE THREAD

**Issue by kiitio** [CVHub520/X-AnyLabeling#74]
在当前图片复制矩形边框对象后（ctrl+c）到下一个图片使用快捷键（ctrl+v）粘贴没有效果，但是可以通过手动右键选择粘贴对象实现
，
使用遇到的一些便利性问题：
1.删除标注框每次都提示“是否删除”这个可不可以加一个“不再提示”的选项？
2.自动标注功能可不可以在额外添加一个“运行全部”的选项一次性将当前目录的所有图片进行标注，因为使用自定义模型进行标注，大部分图片标注的信息都是正确的，仅需检查核对即可

**Comment by kiitio** [comment]
建议：
3.可不可以增加一个批量修改标注名称的功能
4.可不可以增加一个批量修改标签的功能，我发现在使用自定义模型进行标注时，有一种情况是某一项标注80%甚至100%全部是标注错误的，此时迫切的需要一个功能来一键更改所有图片的这个标签，我认为这个功能十分重要

**Comment by kiitio** [comment]
另外您有一些实时的交流渠道吗？例如qq群之类的，

**Comment by aiyou9** [comment]
> 另外您有一些实时的交流渠道吗？例如qq群之类的，

  微信公众号 CVHub  点击右下角 联系我，加号主，加微信群

**Comment by CVHub520** [comment]
> 在当前图片复制矩形边框对象后（ctrl+c）到下一个图片使用快捷键（ctrl+v）粘贴没有效果，但是可以通过手动右键选择粘贴对象实现 ， 使用遇到的一些便利性问题： 1.删除标注框每次都提示“是否删除”这个可不可以加一个“不再提示”的选项？ 2.自动标注功能可不可以在额外添加一个“运行全部”的选项一次性将当前目录的所有图片进行标注，因为使用自定义模型进行标注，大部分图片标注的信息都是正确的，仅需检查核对即可

您好， @kiitio “运行全部”功能已支持，可重新更新源码，导入图片，选择模型，按下快捷键：`Ctrl+M`尝试。

**Comment by kiitio** [comment]
> > 在当前图片复制近似对象后（ctrl+c）到下一张图片使用快捷键（ctrl+v）粘贴没有效果，但可以通过手动右键选择粘贴对象实现，使用时遇到一些便利性问题： 1.删除标注框每次都提示“是否删除”这个可以不可以加一个“不再提示”的选项吗？ 2.自动标注功能可以不可以另外添加一个“运行全部”的一次性将当前目录的所有选项图片进行标注，因为使用自定义模型进行标注，大部分图片标注的信息都是正确的，重点检查核对即可
> 
> 您好，@kiitio“运行全部”功能已支持，可重新更新源码，导入图片，选择模型，按键盘：`Ctrl+M`尝试。

好的！

**Comment by kiitio** [comment]
> > 另外您有一些实时的交流渠道吗？例如QQ群之类的，
> 
> 微信公众号CVHub 点击右下角联系我，加号主，加微信群

好的
