### ISSUE TITLE
Mac 下暗黑模式字体颜色问题

### ISSUE THREAD

**Issue by ChaXxl** [CVHub520/X-AnyLabeling#741]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

在 Mac 上的暗黑模式，这些文字都看不清了

![1](https://github.com/user-attachments/assets/9ad10c95-0066-47a7-8698-4f802310a6ff)

### Information

...

### Link to a Reproducible Demonstration Video

...

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Fixed. Please pull the latest commit and try it out.

**Comment by CVHub520** [comment]
![image](https://github.com/user-attachments/assets/01566b22-7a6a-4174-83f9-4da75f620e49)

![image](https://github.com/user-attachments/assets/3e5d4666-cac4-4d78-9c0e-a63f72053459)
