### ISSUE TITLE
Enhanced Drawing, Naming, and Attribute Features Proposal

### ISSUE THREAD

**Issue by chevydream** [CVHub520/X-AnyLabeling#742]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

建议1: 能否增加一种与labelImg一样的画框机制(原来的还保留, 用户可根据自己的使用习惯选择), 鼠标直接定位一拖就画好，不用先按R键, 再点两下鼠标。

建议2: 保存子图的文件名, 应该使用在原图文件名上添加后缀的方式, 方便基于 错误子图 定位 原始图。

建议3：导入标签时，能否跟图片一样， 支持多级目录

建议4：给绘制出来的目标框增加属性特征，像十字线一样

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
> **Q1:** 能否增加一种与 labelImg 一样的画框机制（原来的还保留，用户可根据自己的使用习惯选择），鼠标直接定位一拖就画好，不用先按 R 键，再点两下鼠标。

**A1:** Duplicate of #330.

> **Q2:** 保存子图的文件名应该使用在原图文件名上添加后缀的方式，方便基于错误子图定位原始图。

**A2:** Thank you for your suggestion. I will consider adding this feature in the next version.  

> **Q3:** 导入标签时，能否跟图片一样，支持多级目录？

**A3:** This feature is currently not supported.  

> **Q4:** 给绘制出来的目标框增加属性特征，像十字线一样。

**A4:** Please refer to [[multi-task-classification](https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/classification/shape-level/README.md#multi-task-classification)](https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/classification/shape-level/README.md#multi-task-classification) for the relevant settings.
