### ISSUE TITLE
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL)

### ISSUE THREAD

**Issue by CafeBabe202** [CVHub520/X-AnyLabeling#745]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Shortcut

### Bug

系统信息

![image](https://github.com/user-attachments/assets/13596967-2b56-47e6-b5c9-7407125f89e8)

### Information

当我打开文件或者文件夹时，会出现这个问题并程序闪退

❯ ./X-Anylabeling-Linux-CPU
2024-12-16 20:17:39,944 | INFO    | app:main:159 - 🚀 X-AnyLabeling v2.5.0 launched!
2024-12-16 20:17:39,944 | INFO    | app:main:162 - ⭐ If you like it, give us a star: https://github.com/CVHub520/X-AnyLabeling
2024-12-16 20:17:39,962 | INFO    | config:get_config:83 - 🔧️ Initializing config from local file: /home/zh/.xanylabelingrc
Gtk-Message: 20:17:39.988: Failed to load module "xapp-gtk3-module"
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

(X-Anylabeling-Linux-CPU:250375): Gtk-WARNING **: 20:17:54.437: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/zh/.local/share/icons/Colloid-Light/status/16/image-missing.svg: 加载用来载入图像的模块失败：/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so：/tmp/_MEILtulRs/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libicuuc.so.74) (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/zh/.local/share/icons/Colloid-Light/status/16/image-missing.svg: 加载用来载入图像的模块失败：/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so：/tmp/_MEILtulRs/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libicuuc.so.74) (gdk-pixbuf-error-quark, 5)
[1]    250359 IOT instruction (core dumped)  ./X-Anylabeling-Linux-CPU

### Link to a Reproducible Demonstration Video

![image](https://github.com/user-attachments/assets/63880e4c-cd5c-4bef-bc4e-1c4d23c746c2)

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Please directly git clone the source code and install the corresponding dependencies to run it. [link](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md)
