### ISSUE TITLE
旋转目标标注

### ISSUE THREAD

**Issue by whuhit** [CVHub520/X-AnyLabeling#746]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/095402ff-417c-4c01-9284-f671437e6c6a)
请问下旋转目标标注功能如何使用，看介绍没看出和一般矩形框的区别，在操作上也没法标注一个倾斜带角度的目标框，请帮忙解答一下，谢谢

**Comment by CVHub520** [comment]
Hi @whuhit, you can refer to this [example](https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/detection/obb/README.md).

**Comment by whuhit** [comment]
> Hi @whuhit, you can refer to this [example](https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/detection/obb/README.md).

好的好的，刚看到了。不过个人感觉这个标注方式是不是复杂了一点，可不可以考虑下，旋转目标标注的时候，鼠标就单击-移动-单击-移动-单击，这样的话，确定三个点就自动补齐第四个点，然后标注就完成了。这样是否会更简单一点点。

**Comment by CVHub520** [comment]
Thanks for your suggestion. Currently, there is no energy to develop. Looking forward to the support of the community.
