### ISSUE TITLE
SAM2 的VOS中ID不会传播的问题

### ISSUE THREAD

**Issue by SongJgit** [CVHub520/X-AnyLabeling#748]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

我尝试使用SAM2 Video 进行VOS，我在第一帧添加了目标的ID，但是发现ID并没有随之传播到后续的帧中。
但是我看到教程中是可以传播的？
![image](https://github.com/user-attachments/assets/ed315ba0-5b9b-4f02-9af4-db36abe030e9)

https://github.com/CVHub520/X-AnyLabeling/tree/main/examples/interactive_video_object_segmentation

**Comment by CVHub520** [comment]
https://github.com/user-attachments/assets/c7d6d441-5aef-41ef-bcd8-ebf2178ffa76

**Comment by CVHub520** [comment]
You can check your installation environment and review the terminal output logs for any errors. If everything seems normal, try upgrading to the latest version by running `git pull origin main` and test again.

**Comment by SongJgit** [comment]
> You can check your installation environment and review the terminal output logs for any errors. If everything seems normal, try upgrading to the latest version by running `git pull origin main` and test again.

teminal一切正常。
因为我的标签是会传播的，但是ID并没有传播，我也尝试更新了，目前都是最新版本

**Comment by CVHub520** [comment]
Please record a video demonstrating the issue.

**Comment by SongJgit** [comment]
> Please record a video demonstrating the issue. Before your start, remember click the `Reset Tracker` button to make sure everything is fine.

我在录制视频的时候，突然成功了一下。

当第一次运行，标签栏没有标签存在的时候，点击 '+点'，标记目标并且出现分割结果之后，按f确认完成对象，会弹出标签编辑框添加类别和group id，确认之后，开始自动标注，此时是可以传播id的。

但是如果，第一帧里面有两个相同类别的目标，点击 '+点'，标记目标并且出现分割结果之后，按f确认完成对象，不会会弹出标签编辑框。而是直接给了个类别，也就没有办法设置id，如果进入编辑模式额外添加id的话，这个方式添加的id他就不会传播了，第一个使用标签编辑框添加的id他就可以被传播

**Comment by CVHub520** [comment]
Thank you for the detailed information. Based on your situation, simply turning off the option shown below should resolve your issue.

![image](https://github.com/user-attachments/assets/acad97fd-ddee-4ed6-91d6-813b935a2e6d)

**Comment by SongJgit** [comment]
> Thank you for the detailed information. Based on your situation, simply turning off the option shown below should resolve your issue.
> 
> ![image](https://private-user-images.githubusercontent.com/72010077/396817094-acad97fd-ddee-4ed6-91d6-813b935a2e6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTIyNzUsIm5iZiI6MTczNDUxMTk3NSwicGF0aCI6Ii83MjAxMDA3Ny8zOTY4MTcwOTQtYWNhZDk3ZmQtZGRlZS00ZWQ2LTkxZDYtODEzYjkzNWEyZTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA4NTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZDY0M2MzMmZmOWRlYjExMThkZDBjZDA0ODE5OTU0N2M5ZTUzODVjMTAzODJhMDk0Mzc0MzI0YTEwNTc1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wmxoLda5tp2DCHqL_Z1KNxIzWw6O6iBk88oXhvqUdkQ)

可以了，非常感谢。
