### ISSUE TITLE
载入upn模型闪退问题

### ISSUE THREAD

**Issue by vitem98** [CVHub520/X-AnyLabeling#749]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

加载这个upn，无论是点击自定义或者直接点击upn，都会直接闪退

### Information

v2.5.0 版本

### Link to a Reproducible Demonstration Video

![image](https://github.com/user-attachments/assets/389cf453-0ec3-4dfe-92a0-5f86aa8a7a47)

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Please paste the output log of the terminal here.

**Comment by vitem98** [comment]
I downloaded the exe file directly and did not run it from the source code. Can I see the log file in this case?

**Comment by CVHub520** [comment]
![image](https://github.com/user-attachments/assets/7b53cbf1-ea19-4698-b3f7-cc40108e45b0)

https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md

**Comment by CVHub520** [comment]
The UPN model requires running from source. Please follow the tutorial to install the specified dependencies and then rerun it.

**Comment by vitem98** [comment]
Thank you for your answer




Vitem
***@***.***
