### ISSUE TITLE
关于自动标注的一点建议

### ISSUE THREAD

**Issue by chevydream** [CVHub520/X-AnyLabeling#750]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

对于已经有标注文件的图片进行自动标注时, 不应直接覆盖其内容, 而应是找出以下三类图片, 存于单独的文件夹中:
1) 模型多识别的, 即: 原标注文件中没有, 但模型识别到了
2) 模型少识别的, 即: 原标注文件中有, 但模型没有识别到
3) 重合度不够的, 即: 标注文件 和 模型识别 都有, 但重合度没有达到用户给定的阈值

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hi @chevydream,  

Thank you for your kind advice. Actually, we provide an option to retain the previous annotations for your convenience. To enable this, simply turn on the option shown below.

![1734572171643_d](https://github.com/user-attachments/assets/9a17f96d-4d32-40f2-ba07-c6c6a35b4270)

**Comment by CVHub520** [comment]
As you mentioned, there isn’t an optimal method for this design due to the significant computational resources required, especially when handling scenarios with multiple objects.

> 对于已经有标注文件的图片进行自动标注时, 不应直接覆盖其内容, 而应是找出以下三类图片, 存于单独的文件夹中:
> 模型多识别的, 即: 原标注文件中没有, 但模型识别到了
> 模型少识别的, 即: 原标注文件中有, 但模型没有识别到
> 重合度不够的, 即: 标注文件 和 模型识别 都有, 但重合度没有达到用户给定的阈值
Use case
