### ISSUE TITLE
按x或者c调整obb旋转方向的时候最小旋转度数在哪设置？目前经过测试感觉是0.5°，能让人自定义设置这个度数吗？我想要更低的度数。

### ISSUE THREAD

**Issue by poearrow** [CVHub520/X-AnyLabeling#754]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

比如0.25°，或者更低，可以自己设置那就更好了，否则画细长的矩形时有时候贴合度不高。

**Comment by CVHub520** [comment]
Just modify [here](https://github.com/CVHub520/X-AnyLabeling/blob/64db73c83c10674810eddc152e61628965b1c0a7/anylabeling/views/labeling/widgets/canvas.py#L23).

**Comment by poearrow** [comment]
> Just modify [here](https://github.com/CVHub520/X-AnyLabeling/blob/64db73c83c10674810eddc152e61628965b1c0a7/anylabeling/views/labeling/widgets/canvas.py#L23).

你的意思是让我自己去修改这个值，然后自己编译吗？

**Comment by CVHub520** [comment]
Yes, we recommend running it from the source code.

**Comment by poearrow** [comment]
> Yes, we recommend running it from the source code.

明白了，好的，我自己编译一个试试。
