### ISSUE TITLE
.xanylabelingrc可以多开独立配置吗

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#755]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

这个问题是这个问题的延伸
https://github.com/CVHub520/X-AnyLabeling/issues/682
软件本身是可以多开的并且可以使用不同的环境来多开
![image](https://github.com/user-attachments/assets/8f886c86-a6dd-47b2-b4b6-f9f522fde374)
![image](https://github.com/user-attachments/assets/d61d294a-995e-462a-9f5c-571ff4bf8b6e)

在有的时候我需要
我需要 使用常驻高亮 不需要鼠标悬浮来处理目标
![image](https://github.com/user-attachments/assets/479bb219-7fad-4f05-972a-9ef654aca003)
有的 时候又需要使用 不需要镂空 矩形外加 鼠标悬浮自动选择
![image](https://github.com/user-attachments/assets/5153a6cc-1f49-4088-814e-f824b2883651)

现在虽然程序可以使用不同的环境进行多开
但是 配置文件始终是一个
C:\Users\ziiyue\.xanylabelingrc
可以像OBS那样
![image](https://github.com/user-attachments/assets/1d577492-7ea8-4df3-84bb-b4329b9d6922)

在软件目录下 放一个便携版的配置 文件
或者 就直接修改程序把位置文件 直接改到 
![image](https://github.com/user-attachments/assets/400e9a04-ec27-4b52-af51-522e30557fbd)
软件的根目录下 这样就可以多开 且 可以独立配置了

这样就可以 根据实际需要切换不同功能的 软件窗口来继续进行

**Comment by lhj5426** [comment]
我试过用沙盘 来 打开 但是也是读取的C盘里的配置文件
![image](https://github.com/user-attachments/assets/7faa7c98-c65c-419e-89b4-c26cef2115ad)

**Comment by CVHub520** [comment]
You can specify your custom configuration file using:

```bash
python anylabeling/app.py --config /path/to/cfg.yaml
```

For more details, please refer to this [guide](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md#113-%E5%90%AF%E5%8A%A8).

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/741d77c4-631e-4b8f-8e09-c4d2a508f41d)
谢谢 原来还可以这样 学会了  这样就可以更灵活的多开切换配置了 谢谢帮助
