### ISSUE TITLE
使用rtdetr标注图像时报错

### ISSUE THREAD

**Issue by RaulWang97** [CVHub520/X-AnyLabeling#756]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

在办公机上离线成功导入rtdetr模型后，运行标注时报错Error in predict_shapes: Required inputs (['orig_target_sizes']) are missing from input feed (['images'])，请问有什么好的解决办法呀，谢谢

**Comment by CVHub520** [comment]
One approach is to ensure your converted ONNX weights match the built-in [ones](https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.1.0/rtdetr_r50vd_6x_coco.onnx). If you don't know how to convert, plz refer this [project](https://github.com/CVHub520/rtdetr-onnxruntime-deploy).  
Alternatively, you can modify the inference script [here](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/rtdetr.py) to adapt it to your custom model.
