### ISSUE TITLE
遍历标签，希望能直接选中被其他标注框遮挡的当前标注框，且鼠标能穿透其他框，或将遍历到的标注框置于顶层，便于进行调整

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#758]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

可以在菜单工具栏的前面，加一个√号示意启用自动选中遍历到的标注框

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by aiyou9** [comment]
主要是小目标标注
相关的issue
#729
#751

**Comment by aiyou9** [comment]
在选中被其他遮挡的四个角顶点的ui设计上，我想的是，选中标注框，鼠标能够穿透其他覆盖着的标注框，能吸附，锁定顶点，不知ui代码，能不能实现出来

**Comment by CVHub520** [comment]
Unfortunately, at the moment, i do not have the time and resources to develop this feature. As a workaround, you can use the W/S keys to control the visibility of the layers. We are hopeful for support from the community in this regard. If anyone in the community is interested in contributing to this feature, it would be greatly appreciated.
