### ISSUE TITLE
yolo系列模型做辅助标注时标签选择

### ISSUE THREAD

**Issue by RaulWang97** [CVHub520/X-AnyLabeling#763]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

作者您好，想请教一下，在使用yolo系列模型做目标检测辅助标注时，假如我们只希望他标出图像中的人和车，不标注红绿灯和猫狗等目标应该怎么设置呀？
尝试过在yaml配置文件的classes中删掉多余标签，只保留car和person，但是运行时会报错"Error in predict_shapes: list index out of range"，请问该怎么解决呀。感谢您在百忙之中的回复。

**Comment by CVHub520** [comment]
Thank you for your question about YOLO model auxiliary labeling. For mapping between YOLO detections and X-AnyLabeling classes, please refer to our documentation at [here](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md).

This guide specifically covers how to properly configure class mappings and handle the "list index out of range" error you're experiencing. The documentation includes examples of correct class configuration that should help resolve the issue between car/person detections.

Let me know if you need any clarification after reviewing the documentation!
