### ISSUE TITLE
Minimum CUDA Version Requirements and Runtime Environment for OpenVision

### ISSUE THREAD

**Issue by RaulWang97** [CVHub520/X-AnyLabeling#764]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

尊敬的作者您好，请问open vision运行支持的最低版本的CUDA是多少呀？该方法必须部署在具有独显的机器上面么？

**Comment by CVHub520** [comment]
Hello @RaulWang97,

Regarding the minimum CUDA version requirement for running `Open Vision`:

Based on our testing, we've primarily verified compatibility with CUDA 12.1 on dedicated GPU systems. This should be considered the recommended minimum version. However, the actual minimum requirements may vary depending on the specific dependencies in your build configuration.

I recommend:
1. Checking the hardware requirements for any dependent libraries you're using
2. Reviewing the OpenVision build documentation for your specific version
3. Verifying compatibility with your GPU hardware specifications

For the most accurate information, please refer to the dependency requirements of your specific OpenVison build and its associated libraries.

Let me know if you need any additional clarification.
