### ISSUE TITLE
上一张和下一张在 和删除 和鼠标，在挑选图片时，真的非常反人类！！

### ISSUE THREAD

**Issue by fangyaodong** [CVHub520/X-AnyLabeling#765]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

上一张和下一张在 和删除 和鼠标，在挑选图片时，真的非常反人类！！ 在挑选图片时  左手就是不停左右 来D 和del 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
I'm sorry to hear that you seem to have had a bad experience. However, please take the time to clearly describe the issue; I don't know what you're referring to.

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月29日 12:02 |
| 收件人 | CVHub520/X-AnyLabeling ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [CVHub520/X-AnyLabeling] 上一张和下一张在 和删除 和鼠标，在挑选图片时，真的非常反人类！！ (Issue #765) |

Search before asking
I have searched the X-AnyLabeling issues and found no similar feature requests.
Description

上一张和下一张在 和删除 和鼠标，在挑选图片时，真的非常反人类！！ 在挑选图片时 左手就是不停左右 来D 和del

Use case

No response

Additional

No response

Are you willing to submit a PR?
Yes I'd like to help by submitting a PR!

**Comment by lhj5426** [comment]
确实 有这个问题  但是我们可以用安静映射来解决呀
![image](https://github.com/user-attachments/assets/47ca5acd-b33b-48c2-b85e-2bc05a89402e)
你看我打标都是直接 按键映射到键盘的舒服位置上
还可以把右键设置成删除
![image](https://github.com/user-attachments/assets/3c1ad47e-aefe-4b49-8881-2d8c144ea196)
快捷键设置不 不舒服不合理完全可以用 安静映射重新调整到 自己喜欢 舒服的位置
