### ISSUE TITLE
能提供Mac os  Arm架构的应用支持么,感谢

### ISSUE THREAD

**Issue by RFSN** [CVHub520/X-AnyLabeling#77]
感谢大佬为开源社区做出的贡献。
能提供Mac os  Arm架构的应用支持么

**Comment by aiyou9** [comment]
直接系统安装python环境，运行？

**Comment by RFSN** [comment]
尝试自己编译的情况下卡住了。
 pip install -r requirements-gpu.txt

Collecting opencv-contrib-python-headless==4.7.0.72 (from -r requirements-gpu.txt (line 1))
  Using cached opencv_contrib_python_headless-4.7.0.72-cp37-abi3-macosx_11_0_arm64.whl (41.0 MB)
Collecting PyQt5==5.15.7 (from -r requirements-gpu.txt (line 2))
  Using cached PyQt5-5.15.7.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... -[1]    18203 killed     pip install -r requirements-gpu.txt

无法编译成功

**Comment by RFSN** [comment]
尝试使用 AnyLabeling 在 mac 上运行。
app 是能打开，但是要等好几分钟。
下载模型就闪退。
所以才找到了 [X-AnyLabeling](https://github.com/CVHub520/X-AnyLabeling) 但是没有mac os 版本，
自己编译也通不过

**Comment by aiyou9** [comment]
那就直接运行，不编译，模型可以自己去x-anylabeling的之前release下载 
https://github.com/CVHub520/X-AnyLabeling/releases/tag/v0.1.0  
放入对应文件夹
https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md

我没有mac，你找一下model文件夹

**Comment by aiyou9** [comment]
> Preparing metadata (pyproject.toml) ... -[1] 18203 killed pip install -r requirements-gpu.txt

mac的requirements是不是不一样？项目根目录，是有专门对mac的dev版，不知道build是不是没有用到，需要自己看看

**Comment by RFSN** [comment]
各种 requirements 都尝试过，都没有办法安装依赖，无法成功运行。

**Comment by CVHub520** [comment]
> 各种 requirements 都尝试过，都没有办法安装依赖，无法成功运行。

您好，这个暂时没法帮助你，因为我这边手头没有 Mac OS 环境。不过这个打包本质上取决于`pyinstaller`，你可以先打包其它工程看看能否成功，确保该第三方库能够正常使用。

**Comment by lusi1990** [comment]
arm 架构对 pyqt的支持不好 , 需要先解决 qt 的安装问题
