### ISSUE TITLE
加载不了 egment_anything_2

### ISSUE THREAD

**Issue by wyy9316** [CVHub520/X-AnyLabeling#770]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

Error in loading model: segment_anything_2_video with error: SegmentAnything2Video model will not be available. Please install related packages and try again.

### Information

1

### Link to a Reproducible Demonstration Video

1

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Duplicate of #613, #650, #719

**Comment by oneway-phil** [comment]
stil has problem

**Comment by CVHub520** [comment]
> stil has problem

Please provide more context.

**Comment by Kino-Eromisu** [comment]
still has this problem

**Comment by CVHub520** [comment]
> still has this problem

Hi @Kino-Eromisu, this isn’t actually a bug—it’s just that some required packages are missing. Please follow the [documentation](https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/interactive_video_object_segmentation/README.md) to install them and get everything working.

**Comment by Kino-Eromisu** [comment]
@CVHub520 Thanks! I got it, my bad...

**Comment by yuliangzhong** [comment]
For those used pip install: this is the source code. The error in the title is due to the `try` block failure.
```
try:
    import torch
    from sam2.build_sam import build_sam2, build_sam2_camera_predictor
    from sam2.sam2_image_predictor import SAM2ImagePredictor

    SAM2_VIDEO_AVAILABLE = True
except ImportError:
    SAM2_VIDEO_AVAILABLE = False
```

For example, maybe you forgot to install `torch` in your new (uv) virtual environment ...
