### ISSUE TITLE
请求加入更多的可编辑、绑定快捷键

### ISSUE THREAD

**Issue by tiancailin** [CVHub520/X-AnyLabeling#79]
我个人的建议主要集中在+point、-point、Rect、Clear(release错翻译成"明确"）这四个
相信其他人也会有多样的需求
希望开发组能够在配置文件中留出哪怕null的空位

**Comment by CVHub520** [comment]
@tiancailin 您好，快捷键已设置，可以通过 '+' '-' 'R' 来设置 +point、-point、Rect 功能，clear 功能暂时保留，防止误触。
