### ISSUE TITLE
编译打包成可执行文件无法在其他电脑上运行

### ISSUE THREAD

**Issue by maoqimq** [CVHub520/X-AnyLabeling#81]
报错信息：没有能处理“executable”文件的程序

**Comment by CVHub520** [comment]
您好，程序打包依赖于 `pyinstaller` 库，具体用户可以参考官方示例，本质上同当前工具无关。你也可以尝试使用其它打包工具，建议先尝试一个简单的程序看下打包程序是否能够正常工作。

**Comment by maoqimq** [comment]
问题解决了，需要修改文件权限，允许文件作为程序执行
