### ISSUE TITLE
EfficientViT-SAM无法下载

### ISSUE THREAD

**Issue by Horizon-42** [CVHub520/X-AnyLabeling#82]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/20414785/f35a644b-0637-46d3-8501-3db64059f3a3)

**Comment by CVHub520** [comment]
您好，@Horizon-42 ，欢迎关注 `X-AnyLabeling`，目前所有模型均已上传至百度网盘，如果下载不了可以直接从[网盘](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/models_list.md)下载。
