### ISSUE TITLE
X-AnyLabeling-GPU.exe

### ISSUE THREAD

**Issue by yeyun122** [CVHub520/X-AnyLabeling#83]
python：：CreateExecutionPrviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of Version

How do I use GPU inference?

**Comment by General110** [comment]
一开始我下载exe也是这样，下载源码 执行也是这样，pip install onnxruntime 后可以正常用了

**Comment by Z-eddy** [comment]
> 一开始我下载exe也是这样，下载源码 执行也是这样，pip install onnxruntime 后可以正常用了

这用的就是CPU，不是GPU
