### ISSUE TITLE
GPU版本闪退

### ISSUE THREAD

**Issue by toff1027** [CVHub520/X-AnyLabeling#85]
加载完模型后正常。导入文件夹成功后显示图片就卡死，闪退

**Comment by CVHub520** [comment]
> 加载完模型后正常。导入文件夹成功后显示图片就卡死，闪退

您好， @toff1027 ，出现闪退的原因千奇百怪，可以先尝试源码运行下定位出具体的报错信息贴上来一起讨论一下。

**Comment by ake020675** [comment]
gpu.exe版本，点加载groundDION模型就闪退。
win10,  1650显卡， cuda10.2

**Comment by CVHub520** [comment]
> gpu.exe版本，点加载groundDION模型就闪退。 win10, 1650显卡， cuda10.2

您好，可以尝试源码运行。我这边是基于cuda11.6版本编译的，可能跟你不兼容，也可以尝试用cpu版本先推理下，具体可参考[教程](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/Q%26A.md)-问题反馈-Grounding-DINO系列模型加载失败。

**Comment by yeyun122** [comment]
> > 加载完成模型后显示正常。导入文件夹成功后图片就卡死，闪退
> 
> 您好，@toff1027，出现闪退的原因千奇百怪，可以先尝试源码运行下定位出具体的报错信息贴上来一起讨论一下。

(Pytorch) F:\Code\X-AnyLabeling>python anylabeling/app.py
Traceback (most recent call last):
  File ".\anylabeling\utils.py", line 15, in run
    self.func(*self.args, **self.kwargs)
  File ".\anylabeling\services\auto_labeling\model_manager.py", line 512, in _load_model
    from .segment_anything import SegmentAnything
  File ".\anylabeling\services\auto_labeling\segment_anything.py", line 16, in <module> 
    from .model import Model
  File ".\anylabeling\services\auto_labeling\model.py", line 5, in <module>
    import onnx
  File "C:\Users\12243\.conda\envs\Pytorch\lib\site-packages\onnx\__init__.py", line 7, in <module>
    from onnx.external_data_helper import (
  File "C:\Users\12243\.conda\envs\Pytorch\lib\site-packages\onnx\external_data_helper.py", line 9, in <module>
    from .onnx_pb import AttributeProto, GraphProto, ModelProto, TensorProto
  File "C:\Users\12243\.conda\envs\Pytorch\lib\site-packages\onnx\onnx_pb.py", line 4, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "C:\Users\12243\.conda\envs\Pytorch\lib\site-packages\onnx\onnx_ml_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\12243\.conda\envs\Pytorch\lib\site-packages\google\protobuf\internal\__init__.py)

**Comment by CVHub520** [comment]
> > > 加载完成模型后显示正常。导入文件夹成功后图片就卡死，闪退
> > 
> > 
> > 您好，@toff1027，出现闪退的原因千奇百怪，可以先尝试源码运行下定位出具体的报错信息贴上来一起讨论一下。
> 
> (Pytorch) F:\Code\X-AnyLabeling>python anylabeling/app.py Traceback (most recent call last): File ".\anylabeling\utils.py", line 15, in run self.func(*self.args, **self.kwargs) File ".\anylabeling\services\auto_labeling\model_manager.py", line 512, in _load_model from .segment_anything import SegmentAnything File ".\anylabeling\services\auto_labeling\segment_anything.py", line 16, in from .model import Model File ".\anylabeling\services\auto_labeling\model.py", line 5, in import onnx File "C:\Users\12243.conda\envs\Pytorch\lib\site-packages\onnx__init__.py", line 7, in from onnx.external_data_helper import ( File "C:\Users\12243.conda\envs\Pytorch\lib\site-packages\onnx\external_data_helper.py", line 9, in from .onnx_pb import AttributeProto, GraphProto, ModelProto, TensorProto File "C:\Users\12243.conda\envs\Pytorch\lib\site-packages\onnx\onnx_pb.py", line 4, in from .onnx_ml_pb2 import * # noqa File "C:\Users\12243.conda\envs\Pytorch\lib\site-packages\onnx\onnx_ml_pb2.py", line 5, in from google.protobuf.internal import builder as _builder ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\12243.conda\envs\Pytorch\lib\site-packages\google\protobuf\internal__init__.py)

您好，这个是你没配置好科学上网，请走自定义模型加载，可参考此[教程](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md)。
