### ISSUE TITLE
【功能需求】希望能自定义模型下载的本地文件夹，c盘空间不够了

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#87]

**Comment by CVHub520** [comment]
您好，自定义模型目前均是由用户自行指定路径的，可以存放在任意合法路径上，具体可参考此[教程](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md#%E4%BA%8C%E5%A6%82%E4%BD%95%E5%8A%A0%E8%BD%BD%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B)。

**Comment by aiyou9** [comment]
x-anylabeling的官方模型，能不能自定义下载文件夹？

**Comment by aiyou9** [comment]
> 您好，自定义模型目前均是由用户自行指定路径的，可以存放在任意合法路径上，具体可参考此[教程](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/custom_model.md#%E4%BA%8C%E5%A6%82%E4%BD%95%E5%8A%A0%E8%BD%BD%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B)。

好像教程里，没有明确，我一直以为要和自带同一个文件夹 😂
