### ISSUE TITLE
使用GroundedDINO两个模型均报错

### ISSUE THREAD

**Issue by elepherai** [CVHub520/X-AnyLabeling#88]
onnxruntime版本是1.16.1，我这边pip搜不出1.14.1

使用GroundedDINO两个模型在指定prompt时预测都会出现以下错误，没有识别结果
![image](https://github.com/CVHub520/X-AnyLabeling/assets/43477405/31e64e3b-7f79-4086-80ec-5db42b1a5e7c)

**Comment by CVHub520** [comment]
> onnxruntime版本是1.16.1，我这边pip搜不出1.14.1
> 
> 使用GroundedDINO两个模型在指定prompt时预测都会出现以下错误，没有识别结果 ![image](https://user-images.githubusercontent.com/43477405/274765383-31e64e3b-7f79-4086-80ec-5db42b1a5e7c.png)

您好， @elepherai ，麻烦将您的系统环境和安装包版本等信息发上来这边复现下。

**Comment by elepherai** [comment]
windows11 cpu
python 3.11.0
X-AnyLabeling_v0.4.0
用的是v0.4.0的requirments.txt，只是onnxruntime版本改为1.16.1

**Comment by CVHub520** [comment]
@elepherai 已修复，请重新拉取最新源码。
