### ISSUE TITLE
yolov8预训练模型模型无法自动标注

### ISSUE THREAD

**Issue by yangboning** [CVHub520/X-AnyLabeling#89]
使用了yolov8m的预训练模型，训练出识别四个类的模型。
自动标注完成没有任何显示，详情如图：
![image](https://github.com/CVHub520/X-AnyLabeling/assets/37468757/d10aa510-af56-4d13-98f1-86c52ece18d3)

![image](https://github.com/CVHub520/X-AnyLabeling/assets/37468757/1af28a3a-6be5-4a5c-a03c-0b146063ec04)

![image](https://github.com/CVHub520/X-AnyLabeling/assets/37468757/bdfa3d7a-f15b-4de7-ac81-b4599637032f)

![image](https://github.com/CVHub520/X-AnyLabeling/assets/37468757/afa44b71-f31f-4782-93d7-49541f02ffe4)

**Comment by CVHub520** [comment]
您好， @yangboning ，请将你的 xxx.onnx, xxx.yaml 以及一张确保能检测出结果的测试图片打个压缩包发到指定邮箱：cv_hub@163.com

**Comment by yangboning** [comment]
已发送。

**Comment by yangboning** [comment]
邮箱应该是cv_hub@163.com没错吧

**Comment by CVHub520** [comment]
您好， @yangboning ，bug已修复，原因是标签出现纯数字。目前还未发布新版本，请更新源码重新运行下，可将*.yaml文件和*.onnx文件放置到同一目录下，新版本已简化yaml文件配置，相关文件已发送到你的邮箱上。

**Comment by yangboning** [comment]
原因找到。。。
等你软件新版本更新吧。
我看了一下我发给你的包里面也没改yaml文件，那个yaml文件的model_path需要写绝对地址，相对地址会报错。

**Comment by yangboning** [comment]
我想知道你是怎么知道是数字的问题？是阻断了模型中0的类然后自动标注就正常了吗？

**Comment by CVHub520** [comment]
这边日后出现问题建议源码运行，在终端会显示具体的报错信息，可以向上追溯调试。



在 2023-10-22 00:06:39，"BONING" ***@***.***> 写道：

我想知道你是怎么知道是数字的问题？是阻断了模型中0的类然后自动标注就正常了吗？

**Comment by CVHub520** [comment]
> 我想知道你是怎么知道是数字的问题？是阻断了模型中0的类然后自动标注就正常了吗？

您好，由于该工具在不断开发与完善中，目前或多或少或存在一些未知的bug，接下来发布的新版本会尽可能保持稳定性。后续如若出现问题，建议源码运行，方便及时查看报错信息，可以向上追溯，快速定位到问题所在。

**Comment by yangboning** [comment]
能不能添加一个转化yolo格式的功能，现在软件标注出来的文件是json格式。
你用模型自动标注输出的应该是先是匹配的目标模型的格式。
在同一文件夹下可以生成一个存放yolo格式的文件夹，或者其他模型输出格式的。

**Comment by CVHub520** [comment]
> 能不能添加一个转化yolo格式的功能，现在软件标注出来的文件是json格式。 你用模型自动标注输出的应该是先是匹配的目标模型的格式。 在同一文件夹下可以生成一个存放yolo格式的文件夹，或者其他模型输出格式的。可能需要格式之间互相同步

您好，该功能早就支持了，请参考此视频[教程](https://www.bilibili.com/video/BV18j411v7qB)。

**Comment by threerog** [comment]
今天刚刚拉的代码 标签为纯数字，运行自定义模型时程序就闪退
我把标签改成中文的就没事了 其他都没变
