### ISSUE TITLE
加载自定义模型闪退

### ISSUE THREAD

**Issue by Yuko1997** [CVHub520/X-AnyLabeling#9]
没有任何报错或提示，程序直接退出
type: test
name: testA
display_name: Test
model_path: ‪D:/Auto/best.onnx
input_width: 640
input_height: 640
score_threshold: 0.45
classes:
  - enemy
  - friend

**Comment by CVHub520** [comment]
您好，配置文件参数有误，`type` 字段为指定模型类型的标识符，目前支持：["segment_anything", "yolov5", "yolov6", "yolov7", "yolov8", "yolox", "yolov5_cls", "yolov6_face", "rtdetr"]，不可自定义。

**Comment by Yuko1997** [comment]
> 您好，配置文件参数有误， 字段为指定模型类型的标识符，目前支持：[“segment_anything”， “yolov5”， “yolov6”， “yolov7”， “yolov8”， “yolox”， “yolov5_cls”， “yolov6_face”， “rtdetr”]，不可自定义。`type`

你好，现在提示这个，是模型有要求吗，直接用yolov8自带命令导出onnx的
![20230616114047](https://github.com/CVHub520/X-AnyLabeling/assets/135049518/bcae15a2-83fe-4e33-816f-ed55c57c54cf)

**Comment by Yuko1997** [comment]
> 可以先下载 release 版本的 yolov8-onnx 模型，用 netron 对比下两个模型。解决不了的话可将模型和配置文件打个压缩包传到网盘发个链接给我看看。
这里有些区别
![20230616233323](https://github.com/CVHub520/X-AnyLabeling/assets/135049518/f213ae5b-1517-48e4-a439-5de2c5d44bcb)
![20230616233331](https://github.com/CVHub520/X-AnyLabeling/assets/135049518/16973921-a816-49dd-99bd-0a080d5b8b5d)
配置和模型https://wwut.lanzoul.com/ii7av0zboj7c

**Comment by Yuko1997** [comment]
> > > 您好，配置文件参数有误， 字段为指定模型类型的标识符，目前支持：[“segment_anything”， “yolov5”， “yolov6”， “yolov7”， “yolov8”， “yolox”， “yolov5_cls”， “yolov6_face”， “rtdetr”]，不可自定义。`type`
> > 
> > 
> > 你好，现在提示这个，是模型有要求吗，直接用yolov8自带命令导出onnx的 ![20230616114047](https://user-images.githubusercontent.com/135049518/246311140-bcae15a2-83fe-4e33-816f-ed55c57c54cf.png)
> 
> 可以先下载 release 版本的 yolov8-onnx 模型，用 netron 对比下两个模型。解决不了的话可将模型和配置文件打个压缩包传到网盘发个链接给我看看。

这里有些区别
![20230616233323](https://github.com/CVHub520/X-AnyLabeling/assets/135049518/a538bde5-54d2-42c4-a421-f29ed675a13d)
![20230616233331](https://github.com/CVHub520/X-AnyLabeling/assets/135049518/4fe86817-0612-4bcf-8fb0-1901456d0845)
模型和配置https://wwut.lanzoul.com/ii7av0zboj7c

**Comment by CVHub520** [comment]
@Yuko1997 您好，这边复现了下发现是 onnx 与 opencv 和 torch 版本的兼容问题，请确保 torch <= 1.11，并修改 opset 版本（默认是 14）：

```python
# pip install ultralytics 
from ultralytics import YOLO

model = YOLO("yolov8n.yaml")  # build a new model from scratch
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

path = model.export(format="onnx", opset=12)  # export the model to ONNX format
```

测试版本为：torch==1.11.0 | opencv-python==4.6.0.66 | onnx==1.12.0

后续会对多版本做兼容，敬请留意，再次感谢您的关注与支持。

**Comment by weiweiboni2** [comment]
![image](https://github.com/user-attachments/assets/eaa52955-cc56-49c4-ab2f-7759c14f03d7)
导入模型后在自动标注时一直报这个错误：
2024-11-19 16:51:08,673 | ERROR   | model_manager:predict_shapes:2101 - Error in predict_shapes: list index out of range
