### ISSUE TITLE
GUI crashes to desktop when doing anything

### ISSUE THREAD

**Issue by AlbertoOddness** [CVHub520/X-AnyLabeling#90]
Hello!

I am using the latest CPU version of GUI release 0.4 on Ubuntu 22.

When I open the GUI there are no problems, however when I click on any function (open, open directory, change output directory, etc.) the first time it's not recognized, and the second time it crashes silently without freezing.

What could be the cause of the error? Lack of memory or missing dependency? Something else?

Thank you!

**Comment by CVHub520** [comment]
Hello, @AlbertoOddness,

Thank you for your valuable feedback. It appears that the GUI version you are using has some lingering bugs. I am continuously working on improving the software, and there is a new version in the pipeline. I recommend keeping an eye out for updates.

In the meantime, if you urgently need to use the software, you may consider running it from the source code. This can sometimes provide a more stable experience while I work on addressing these issues in the official release.

I appreciate your patience and understanding as I strive to make the GUI version more robust and reliable.

Best regards,
CVHub

**Comment by AlbertoOddness** [comment]
Thank you @CVHub520, I built from source and that works perfectly.
