### ISSUE TITLE
旋转矩形框如何旋转？

### ISSUE THREAD

**Issue by mztony** [CVHub520/X-AnyLabeling#91]
请问要如何将矩形框旋转？默认的旋转矩形框是0度的，要怎么修改角度？

**Comment by CVHub520** [comment]
> 请问要如何将矩形框旋转？默认的旋转矩形框是0度的，要怎么修改角度？

您好， @mztony ，创建矩形框后可在开启编辑模式下使用快捷键`zxcv`就行旋转，分别是控制旋转的方向和角度，你可以自行试试。

**Comment by mztony** [comment]
好的感谢！

**Comment by CVHub520** [comment]
> 好的感谢！

您好， @mztony ，旋转框标注、显示以及模型自动打标功能之前存在一些bug，现已全部修复，请及时更新源码运行，后续将会发布稳定版本，敬请关注。
