### ISSUE TITLE
please create a  yolov8-sam combined usage model

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#92]

**Comment by CVHub520** [comment]
Hi, @aiyou9 , creating a YOLOv8-SAM combined usage model is currently in the process of being refactored. I'm actively working on this, and as i make progress, i will be introducing support for this combination. Your patience is greatly appreciated, and i look forward to bringing you this functionality in the near future. Stay tuned for updates! :)

Best regards,
CVHub

**Comment by CVHub520** [comment]
Great news! It now support YOLOv8-EfficientViT_SAM. You can update the source code to take advantage of this feature. I'm constantly working to enhance my offerings, and your feedback is invaluable in driving these improvements. Thank you for your support, and I look forward to your continued engagement with our project!

Best regards,
CVHub

**Comment by aiyou9** [comment]
没有在 x-anylabeling 0.2.4上传 EfficientViT_SAM models

**Comment by CVHub520** [comment]
@aiyou9 已上传，请重新拉取。

**Comment by ckcraig01** [comment]
I downloaded [X-AnyLabeling-CPU.exe](https://github.com/CVHub520/X-AnyLabeling/releases/download/v1.0.0/X-AnyLabeling-CPU.exe), But when I try: YOLOv8-EfficientViT_SAM, for bbox and point, the appeared polygon is located above the region I specified (indicate a smaller "y" value) could that be any issue in the build?

**Comment by CVHub520** [comment]
Hi, @ckcraig01 :

I've tested this version, and the inference results appear to be normal. If the polygon is appearing above the region you specified with a smaller "y" value, it might not necessarily be an issue with the build. You could try switching to a different image to further investigate the problem.

Additionally, please make sure you're using this model correctly. You can follow these steps:
- Click 'Run (i)' or use the shortcut 'i' for initial labeling.
- Use '+Point' to add points that belong to the object.
- Use '-Point' to remove any points you want to exclude from the object.
- Use '+Rect' to draw a rectangle around the object. Segment Anything will automatically segment the object.
- You can use 'Clear' to remove all auto segmentation markings.
- After finishing marking the object, press 'Finish Object (f).' You can then enter the label name and save the object.

> Please note that each target needs to be processed separately and ends with `f`.

For more guidance, you can also refer to a demo [video](https://www.youtube.com/watch?v=7af52qzHA-I), and you can jump directly to the part around 15:35 for a demonstration.

If the issue persists, please feel free to provide more details, and we'll do our best to assist you further.

Best regards,
CVHub
