### ISSUE TITLE
How to import annotated datasets

### ISSUE THREAD

**Issue by ss7892946** [CVHub520/X-AnyLabeling#94]
I want to use the annotated Coco dataset, but the format is different. Is there any way to convert the format

**Comment by CVHub520** [comment]
Hi, @ss7892946:
Yes, you can convert the annotated Coco dataset format easily. After completing all the annotation tasks, navigate to the menu bar at the top of the interface. Click on 'Format' and select 'COCO'. You'll need to upload your classes.txt file, which is used to map the categories to the correct IDs. This process will allow you to smoothly export the dataset in the desired format. If you have any further questions, please don't hesitate to reach out to me.

Note: only the latest source code support this function, please update your local code and run it. Futhermore, you can reference this video [toturial](https://www.bilibili.com/video/BV18j411v7qB/). By the way, the classes.txt example you can look at [this](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/classes.txt).

Best regards,
CVHub

**Comment by ss7892946** [comment]
不好意思，我没有说明清楚。是需要导入本地已经注释过的coco数据集，该怎么操作呢

**Comment by CVHub520** [comment]
您好，如果是需要导入本地已经注释过的coco数据集，只需要使用标签转换脚本一键转换成 custom 格式加载即可，具体可参考此[运行指令：
```bash
cd X-AnyLabeling
python tools/label_converter.py --task xxx --src_path xxx.json --dst_path xxx_folder --img_path xxx_folder --classes xxx.txt --mode coco2custom
```

**Comment by ss7892946** [comment]
请问是在cmd上执行吗，输入后系统提示找不到指定路径，抱歉我是个初学者

**Comment by ss7892946** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/148734859/93328844-bc65-4a17-8543-07713326a6f8)
我使用python将标签文件转化为这样后软件依旧识别不到该怎么解决呢

**Comment by CVHub520** [comment]
您好，可以将您的 *.json 文件和几张图片打成一个压缩包发到指定邮箱：cv_hub@163.com，我晚点帮你看下。

**Comment by ss7892946** [comment]
好的已发送，非常感谢

**Comment by CVHub520** [comment]
> 好的已发送，非常感谢

您好，请重新拉取源码，参考执行指令：
```bash
python tools/label_converter.py --task polygon --src_path xxx/train/_annotations.coco.json --img_path xxx/images/ --mode coco2custom
```

我看了你发送的 `_annotations.coco.json` 内容，里面的 id 编号都是从 0 开始的。按照 `coco` 数据集官方的标准，`categories` IDs、`images` IDs、`annotations` IDs 的编号应该是从 1 开始。 所以要么你将你的 `json` 文件里面涉及到的 IDs 号都减去1，要么修改下 `label_converter.py` 文件中的 `self.classes[dic_info["category_id"]-1],` 修改为 `self.classes[dic_info["category_id"]],` 再运行上述脚本。

**Comment by ss7892946** [comment]
你好，请问一下
`python tools/label_converter.py --task polygon --src_path yolo_folder --img_path img_folder --classes xxx.txt --mode yolo2custom`
这里面的`xxx.txt`填的是什么，以下是我的yolo标注文件列表，非常感谢
![image](https://github.com/CVHub520/X-AnyLabeling/assets/148734859/4cc88920-d7cf-49e1-a98e-7cac94f3f047)

**Comment by Chimaco37** [comment]
请问比如说yolov8实例分割系列的模型的输出结果(多边形的点)也能转换为可以导入到软件中的格式吗？有的话请问应该怎么操作？
![image](https://github.com/CVHub520/X-AnyLabeling/assets/77201421/7112e797-7cd4-47e9-b298-774f702aadad)
这样子的格式，每行代表一个多边形，后面分别是xy坐标。

**Comment by CVHub520** [comment]
> 你好，请问一下 `python tools/label_converter.py --task polygon --src_path yolo_folder --img_path img_folder --classes xxx.txt --mode yolo2custom` 这里面的`xxx.txt`填的是什么，以下是我的yolo标注文件列表，非常感谢 ![image](https://user-images.githubusercontent.com/148734859/277600824-4cc88920-d7cf-49e1-a98e-7cac94f3f047.png)

你好，classes.txt 就是一个类别标签文件，每一行代表一个 `class`，序号从上到下从0开始编号，例如：
```
person
car
dog
apple
```

**Comment by CVHub520** [comment]
> 请问比如说yolov8实例分割系列的模型的输出结果(多边形的点)也能转换为可以导入到软件中的格式吗？有的话请问应该怎么操作？ ![image](https://user-images.githubusercontent.com/77201421/277604456-7112e797-7cd4-47e9-b298-774f702aadad.png) 这样子的格式，每行代表一个多边形，后面分别是xy坐标。

您好，可以的，请参看[帮助文档](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/Q%26A.md)——**标签转换**章节，参考运行指令：
```bash
python tools/label_converter.py --task polygon --src_path yolo_folder --img_path img_folder --classes xxx.txt --mode yolo2custom
```

**Comment by ss7892946** [comment]
你好，我在转换完标签后，在anylabeling中选择文件打开，然后就闪退了，我查看转换完的文件版本为0.4.0，而用anylabeling标注完的版本为0.3.3，是这个导致的闪退吗？如果是的话怎么解决呢，因为我在网上找不到0.4.0的版本

**Comment by CVHub520** [comment]
> 你好，我在转换完标签后，在anylabeling中选择文件打开，然后就闪退了，我查看转换完的文件版本为0.4.0，而用anylabeling标注完的版本为0.3.3，是这个导致的闪退吗？如果是的话怎么解决呢，因为我在网上找不到0.4.0的版本

您好，0.4.0版本存在较多bug已删除，目前新版本预估这几天发布。此外，建议下载最新源码运行，如果还报错方便查看具体报错信息，欢迎随时反馈。

**Comment by ss7892946** [comment]
您好，我在下载完最新源码后运行，结果版本变为1.0.0，其他的属性也没发生变化，anylabeling读取完还是闪退

**Comment by CVHub520** [comment]
> 您好，我在下载完最新源码后运行，结果版本变为1.0.0，其他的属性也没发生变化，anylabeling读取完还是闪退

您好，可以将您的图片和标签文件打个压缩包发到指定邮箱下。

**Comment by ss7892946** [comment]
好的已发送，非常感谢您的耐心解答

**Comment by CVHub520** [comment]
> 好的已发送，非常感谢您的耐心解答

您好，我看了下 你的标注任务是多边形，但你转换后的的标注文件中 "shape_type": "rectangle"。
你需要在转换的时候，将 --task 字段设置为 `polygon`，例如：
```bash
python tools/label_converter.py --task polygon --src_path yolo_folder --img_path img_folder --classes xxx.txt --mode yolo2custom
```

**Comment by ss7892946** [comment]
这个我倒是没有输错，之前也是设置`[polygon]`
![image](https://github.com/CVHub520/X-AnyLabeling/assets/148734859/95b3ac7a-2f51-4884-b77e-b541f386dd8d)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/148734859/81c94bac-0a56-4e5a-af37-c18a00eb9d36)

**Comment by Chimaco37** [comment]
> 这个我倒是没有输错，之前也是设置`[polygon]` ![image](https://user-images.githubusercontent.com/148734859/277880490-95b3ac7a-2f51-4884-b77e-b541f386dd8d.png) ![image](https://user-images.githubusercontent.com/148734859/277880433-81c94bac-0a56-4e5a-af37-c18a00eb9d36.png)

我也遇到了和你一样的问题  请问你解决了吗？
也是读取标签文件时闪退，正确设置了polygon但是输出的标签结果是rectangle，有没有可能自行将json文件中的rectangle改为polygon就可以了？   我是下载的可执行window-cpu.exe文件，在windows上不太方便直接操作源码。

**Comment by ss7892946** [comment]
> > 这个我倒是没有输错，之前也是设置`[polygon]` ![image](https://user-images.githubusercontent.com/148734859/277880490-95b3ac7a-2f51-4884-b77e-b541f386dd8d.png) ![image](https://user-images.githubusercontent.com/148734859/277880433-81c94bac-0a56-4e5a-af37-c18a00eb9d36.png)
> 
> 我也遇到了和你一样的问题 请问你解决了吗？ 也是读取标签文件时闪退，正确设置了polygon但是输出的标签结果是rectangle，有没有可能自行将json文件中的rectangle改为polygon就可以了？ 我是下载的可执行window-cpu.exe文件，在windows上不太方便直接操作源码。

解决了，但是我最后是调试完，然后把代码中的这部分的rectangle改为polygon，本质上就是修改json文件中的shape_type类型
![image](https://github.com/CVHub520/X-AnyLabeling/assets/148734859/2efbe108-be6a-4df9-bbe5-19c83ab6b86a)

**Comment by Chimaco37** [comment]
> > > 这个我倒是没有输错，之前也是设置`[polygon]` ![image](https://user-images.githubusercontent.com/148734859/277880490-95b3ac7a-2f51-4884-b77e-b541f386dd8d.png) ![image](https://user-images.githubusercontent.com/148734859/277880433-81c94bac-0a56-4e5a-af37-c18a00eb9d36.png)
> > 
> > 
> > 我也遇到了和你一样的问题 请问你解决了吗？ 也是读取标签文件时闪退，正确设置了polygon但是输出的标签结果是rectangle，有没有可能自行将json文件中的rectangle改为polygon就可以了？ 我是下载的可执行window-cpu.exe文件，在windows上不太方便直接操作源码。
> 
> 解决了，但是我最后是调试完，然后把代码中的这部分的rectangle改为polygon，本质上就是修改json文件中的shape_type类型 ![image](https://user-images.githubusercontent.com/148734859/278576251-2efbe108-be6a-4df9-bbe5-19c83ab6b86a.png)

可以可以  我也尝试了一下 没问题  可以正常导入了    就是闪退现象还是经常发生  有点影响   谢谢啦！

**Comment by CVHub520** [comment]
> > > > 这个我倒是没有输错，之前也是设置`[polygon]` ![image](https://user-images.githubusercontent.com/148734859/277880490-95b3ac7a-2f51-4884-b77e-b541f386dd8d.png) ![image](https://user-images.githubusercontent.com/148734859/277880433-81c94bac-0a56-4e5a-af37-c18a00eb9d36.png)
> > > 
> > > 
> > > 我也遇到了和你一样的问题 请问你解决了吗？ 也是读取标签文件时闪退，正确设置了polygon但是输出的标签结果是rectangle，有没有可能自行将json文件中的rectangle改为polygon就可以了？ 我是下载的可执行window-cpu.exe文件，在windows上不太方便直接操作源码。
> > 
> > 
> > 解决了，但是我最后是调试完，然后把代码中的这部分的rectangle改为polygon，本质上就是修改json文件中的shape_type类型 ![image](https://user-images.githubusercontent.com/148734859/278576251-2efbe108-be6a-4df9-bbe5-19c83ab6b86a.png)
> 
> 可以可以 我也尝试了一下 没问题 可以正常导入了 就是闪退现象还是经常发生 有点影响 谢谢啦！

您好，有条件的话建议源码运行下，可以看到具体闪退的信息，一劳永逸。另外也可以下载最新版本，运行更加稳定。
