### ISSUE TITLE
为什么我自定义的模型导入后，点击自动注释后没有任何结果的输出

### ISSUE THREAD

**Issue by Chimaco37** [CVHub520/X-AnyLabeling#95]
我训练了一个yolov8x-seg的实例分割模型，训练完成后将生成的pt文件转换成了onnx文件，我已经确认了这个文件在我的服务器上可以正常的输出标注内容，但我现在想将这个模型导入到X-AnyLabeling软件当中去为我后续的数据标注工作进行自动注释，但是试了几次完全没有输出内容。这里是我的模型配置文件。
![image](https://github.com/CVHub520/X-AnyLabeling/assets/77201421/72d76112-ab36-4306-b419-d1ef9a2a5d20)

**Comment by CVHub520** [comment]
您好， @Chimaco37 ，麻烦将 `onnx` 文件、测试图片和你的 `yaml` 配置文件打包发到指定邮箱：cv_hub@163.com

**Comment by Chimaco37** [comment]
> 您好， @Chimaco37 ，麻烦将 `onnx` 文件、测试图片和你的 `yaml` 配置文件打包发到指定邮箱：[cv_hub@163.com](mailto:cv_hub@163.com)

已发送，请查收，感谢！

**Comment by CVHub520** [comment]
> > 您好， @Chimaco37 ，麻烦将 `onnx` 文件、测试图片和你的 `yaml` 配置文件打包发到指定邮箱：[cv_hub@163.com](mailto:cv_hub@163.com)
> 
> 已发送，请查收，感谢！

您好，请重新下载源码运行，另外你的 yaml 文件配置有问题，第一个是输入分辨率，你的模型是(640, 640)，如果你不确定的话可以不需要加input_height和input_width两个字段；第二个是num_masks值，默认值是32，如果你没修改yolo框架这个值请按默认值填写。其它没什么问题。

**Comment by Chimaco37** [comment]
> > > 您好， @Chimaco37 ，麻烦将 `onnx` 文件、测试图片和你的 `yaml` 配置文件打包发到指定邮箱：[cv_hub@163.com](mailto:cv_hub@163.com)
> > 
> > 
> > 已发送，请查收，感谢！
> 
> 您好，请重新下载源码运行，另外你的 yaml 文件配置有问题，第一个是输入分辨率，你的模型是(640, 640)，如果你不确定的话可以不需要加input_height和input_width两个字段；第二个是num_masks值，默认值是32，如果你没修改yolo框架这个值请按默认值填写。其它没什么问题。

好的，我再试一下。我是直接下载的exe文件的版本。num_masks这个值意思是检测到的masks上限数对吗？请问有没有对这些特定配置文件的字段解释帖子呢？谢谢解答！

**Comment by CVHub520** [comment]
> > > > 您好， @Chimaco37 ，麻烦将 `onnx` 文件、测试图片和你的 `yaml` 配置文件打包发到指定邮箱：[cv_hub@163.com](mailto:cv_hub@163.com)
> > > 
> > > 
> > > 已发送，请查收，感谢！
> > 
> > 
> > 您好，请重新下载源码运行，另外你的 yaml 文件配置有问题，第一个是输入分辨率，你的模型是(640, 640)，如果你不确定的话可以不需要加input_height和input_width两个字段；第二个是num_masks值，默认值是32，如果你没修改yolo框架这个值请按默认值填写。其它没什么问题。
> 
> 好的，我再试一下。我是直接下载的exe文件的版本。num_masks这个值意思是检测到的masks上限数对吗？请问有没有对这些特定配置文件的字段解释帖子呢？谢谢解答！

您好，yolo框架中提供的分割算法在是基于 《YOLACT: Real-time Instance Segmentation》（https://arxiv.org/abs/1904.02689）实现的，如果你想了解其中的技术原理，可以先读下这篇论文再配合源码看。
这里 mask 主要是指 prototype mask，每个 mask 用于提取原图像的一些特征，例如空间信息、位置信息、或者得到position-sensitive的区域信息。mask 多了意味着计算量的提升虽然可能会提升精度，一般 trade-off 便设置成 32.

**Comment by Chimaco37** [comment]
> > > > > 您好， @Chimaco37 ，麻烦将 `onnx` 文件、测试图片和你的 `yaml` 配置文件打包发到指定邮箱：[cv_hub@163.com](mailto:cv_hub@163.com)
> > > > 
> > > > 
> > > > 已发送，请查收，感谢！
> > > 
> > > 
> > > 您好，请重新下载源码运行，另外你的 yaml 文件配置有问题，第一个是输入分辨率，你的模型是(640, 640)，如果你不确定的话可以不需要加input_height和input_width两个字段；第二个是num_masks值，默认值是32，如果你没修改yolo框架这个值请按默认值填写。其它没什么问题。
> > 
> > 
> > 好的，我再试一下。我是直接下载的exe文件的版本。num_masks这个值意思是检测到的masks上限数对吗？请问有没有对这些特定配置文件的字段解释帖子呢？谢谢解答！
> 
> 您好，yolo框架中提供的分割算法在是基于 《YOLACT: Real-time Instance Segmentation》（[https://arxiv.org/abs/1904.02689）实现的，如果你想了解其中的技术原理，可以先读下这篇论文再配合源码看。](https://arxiv.org/abs/1904.02689%EF%BC%89%E5%AE%9E%E7%8E%B0%E7%9A%84%EF%BC%8C%E5%A6%82%E6%9E%9C%E4%BD%A0%E6%83%B3%E4%BA%86%E8%A7%A3%E5%85%B6%E4%B8%AD%E7%9A%84%E6%8A%80%E6%9C%AF%E5%8E%9F%E7%90%86%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%85%88%E8%AF%BB%E4%B8%8B%E8%BF%99%E7%AF%87%E8%AE%BA%E6%96%87%E5%86%8D%E9%85%8D%E5%90%88%E6%BA%90%E7%A0%81%E7%9C%8B%E3%80%82) 这里 mask 主要是指 prototype mask，每个 mask 用于提取原图像的一些特征，例如空间信息、位置信息、或者得到position-sensitive的区域信息。mask 多了意味着计算量的提升虽然可能会提升精度，一般 trade-off 便设置成 32.

感谢！刚刚重新导入了一下之后可以正常输出结果了，只是没有自己在服务器上使用模型预测的精度高。不过已经解决啦👍👍

**Comment by dahaigui** [comment]
我也遇到了这个问题，我的yaml文件如下所示
![image](https://github.com/CVHub520/X-AnyLabeling/assets/47802187/cf65c6a7-a25b-406a-ba98-c8a1f0848270)
