### ISSUE TITLE
groundingdino导出的onnx模型支持切换图像分辨率吗

### ISSUE THREAD

**Issue by acai66** [CVHub520/X-AnyLabeling#96]
我导出的onnx只能用导出时的尺寸，推理时更换分辨率会失败。如果不支持切换分辨率的话，设为固定分辨率可能会有一定的加速效果。

**Comment by acai66** [comment]
我看源码里新release还没发布，暂时下载不到量化后的模型，这是我导出的onnx，输入图像大小固定为1200x800，可以测试对比下该模型与新release模型的性能吗

```python
import time
import os
import onnxruntime as ort

import cv2
import numpy as np
from typing import Dict
from tokenizers import Tokenizer


class OnnxBaseModel():
    def __init__(self, model_path, device_type: str = 'gpu'):

        self.sess_opts = ort.SessionOptions()
        if "OMP_NUM_THREADS" in os.environ:
            self.sess_opts.inter_op_num_threads = int(os.environ["OMP_NUM_THREADS"])

        self.providers = ['CPUExecutionProvider']
        if device_type.lower() == 'gpu':
            self.providers = ['CUDAExecutionProvider']

        self.ort_session = ort.InferenceSession(
                        model_path, 
                        providers=self.providers,
                        sess_options=self.sess_opts,
                    )

    def get_ort_inference(self, blob, inputs=None, extract=True, squeeze=False):
        if inputs is None:
            inputs = self.get_input_name()
            outs = self.ort_session.run(None, {inputs: blob})
        else:
            outs = self.ort_session.run(None, inputs)
        if extract:
            outs = outs[0]
        if squeeze:
            outs = outs.squeeze(axis=0)
        return outs
    
    def get_input_name(self):
        return self.ort_session.get_inputs()[0].name

    def get_input_shape(self):
        return self.ort_session.get_inputs()[0].shape

    def get_output_name(self):
        return [out.name for out in self.ort_session.get_outputs()]


class Grounding_DINO():
    """Open-Set object detection model using Grounding_DINO"""

    def __init__(self, model_config=None) -> None:

        self.config = model_config
        model_abs_path = self.config["model_path"]
        if not model_abs_path or not os.path.isfile(model_abs_path):
            raise FileNotFoundError(
                print('file not found: ', model_abs_path)
            )

        self.net = OnnxBaseModel(model_abs_path, device_type=self.config["device_type"])
        self.max_text_len = self.config["max_text_len"]
        self.tokenizer = self.get_tokenlizer(self.config["text_encoder_type"])
        self.box_threshold = self.config["box_threshold"]
        self.text_threshold = self.config["text_threshold"]
        self.target_size = (self.config["input_width"], self.config["input_height"])

    def preprocess(self, image, text_prompt, img_mask=None):
        # Resize the image
        image = cv2.resize(image, self.target_size, interpolation=cv2.INTER_LINEAR)

        image = image.astype(np.float32) / 255.0
        mean = np.array([0.485, 0.456, 0.406])
        std = np.array([0.229, 0.224, 0.225])
        image = (image - mean) / std
        image = np.transpose(image, (2, 0, 1))
        image = np.expand_dims(image, 0).astype(np.float32)

        # encoder texts
        captions = self.get_caption(text_prompt)
        #tokenized = self.tokenizer(captions, padding="longest", return_tensors="np")
        #specical_tokens = self.tokenizer.convert_tokens_to_ids(["[CLS]", "[SEP]", ".", "?"])
        tokenized_raw_results = self.tokenizer.encode(captions)
        tokenized = {
            "input_ids": np.array([tokenized_raw_results.ids], dtype=np.int64),
            "token_type_ids": np.array([tokenized_raw_results.type_ids], dtype=np.int64),
            "attention_mask": np.array([tokenized_raw_results.attention_mask])
        }
        specical_tokens = [101, 102, 1012, 1029] # [self.tokenizer.token_to_id(i) for i in ["[CLS]", "[SEP]", ".", "?"]]
        (
            text_self_attention_masks,
            position_ids,
            _,
        ) = self.generate_masks_with_special_tokens_and_transfer_map(
            tokenized, specical_tokens)
        if text_self_attention_masks.shape[1] > self.max_text_len:
            text_self_attention_masks = text_self_attention_masks[
                :, : self.max_text_len, : self.max_text_len]
            
            position_ids = position_ids[:, : self.max_text_len]
            tokenized["input_ids"] = tokenized["input_ids"][:, : self.max_text_len]
            tokenized["attention_mask"] = tokenized["attention_mask"][:, : self.max_text_len]
            tokenized["token_type_ids"] = tokenized["token_type_ids"][:, : self.max_text_len]

        inputs = {}
        inputs["img"] = image
        if img_mask is None:
            inputs["img_mask"] = np.zeros((1, image.shape[0], image.shape[2], image.shape[3]), dtype=np.float32)
        else:
            inputs["img_mask"] = img_mask
        inputs["input_ids"] = np.array(tokenized["input_ids"], dtype=np.int64)
        inputs["attention_mask"] = np.array(tokenized["attention_mask"], dtype=bool)
        inputs["token_type_ids"] = np.array(tokenized["token_type_ids"], dtype=np.int64)
        inputs["position_ids"] = np.array(position_ids, dtype=np.int64)
        inputs["text_token_mask"] = np.array(text_self_attention_masks, dtype=bool)

        return image, inputs, captions

    def postprocess(self, outputs, caption, with_logits=True, token_spans=None):
        logits, boxes = outputs
        logits_filt = np.squeeze(logits, 0) #[0]  # prediction_logits.shape = (nq, 256)
        boxes_filt = np.squeeze(boxes, 0) #[0]  # prediction_boxes.shape = (nq, 4)
        # filter output
        if token_spans is None:
            filt_mask = logits_filt.max(axis=1) > self.box_threshold
            logits_filt = logits_filt[filt_mask]  # num_filt, 256
            boxes_filt = boxes_filt[filt_mask]  # num_filt, 4

            # get phrase
            tokenlizer = self.tokenizer
            tokenized_raw_results = tokenlizer.encode(caption)
            tokenized = {
                "input_ids": np.array(tokenized_raw_results.ids, dtype=np.int64),
                "token_type_ids": np.array(tokenized_raw_results.type_ids, dtype=np.int64),
                "attention_mask": np.array(tokenized_raw_results.attention_mask)
            }
            # build pred
            pred_phrases = []
            for logit in logits_filt:
                posmap = logit > self.text_threshold
                pred_phrase = self.get_phrases_from_posmap(posmap, tokenized, tokenlizer)
                if with_logits:
                    pred_phrases.append([pred_phrase, logit.max()])
                else:
                    pred_phrases.append([pred_phrase, 1.0])
        else:
            # TODO: Using token_spans.
            raise NotImplementedError
        return boxes_filt, pred_phrases

    def predict_shapes(self, image, image_path=None, text_prompt=None, img_mask=None):
        """
        Predict shapes from image
        """

        if image is None:
            return []

        start_time = time.time()
        blob, inputs, caption = self.preprocess(image, text_prompt, img_mask)
        end_time = time.time()
        print("Preprocess time: {:.3f}s".format(end_time - start_time))
        start_time = time.time()
        outputs = self.net.get_ort_inference(blob, inputs=inputs, extract=False)
        end_time = time.time()
        print("Inference time: {:.3f}s".format(end_time - start_time))
        
        start_time = time.time()
        boxes_filt, pred_phrases = self.postprocess(outputs, caption)
        end_time = time.time()
        print("Postprocess time: {:.3f}s".format(end_time - start_time))

        shapes = []
        img_h, img_w, _ = image.shape
        boxes = self.rescale_boxes(boxes_filt, img_h, img_w)
        for box, label_info in zip(boxes, pred_phrases):
            x1, y1, x2, y2 = box
            label, conf = label_info

            shapes.append([label, conf, x1, y1, x2, y2])

        return shapes


    @staticmethod
    def rescale_boxes(boxes, img_h, img_w):
        converted_boxes = []
        for box in boxes:
            # from 0..1 to 0..W, 0..H
            converted_box = box * np.array([img_w, img_h, img_w, img_h])
            # from xywh to xyxy
            converted_box[:2] -= converted_box[2:] / 2
            converted_box[2:] += converted_box[:2]
            converted_boxes.append(converted_box)
        return np.array(converted_boxes, dtype=int)


    @staticmethod
    def get_caption(text_prompt):
        caption = text_prompt.lower()
        caption = caption.strip()
        if not caption.endswith("."):
            caption = caption + "."
        captions = caption
        return captions

    @staticmethod
    def get_tokenlizer(text_encoder_type):
        tokenizer = Tokenizer.from_file(f"./tokenizer/{text_encoder_type}.json")
        #tokenizer.enable_padding(length=256)
        #tokenizer.enable_truncation(max_length=256)
        return tokenizer

    @staticmethod
    def get_phrases_from_posmap(
        posmap: np.ndarray, tokenized: Dict, tokenizer, left_idx: int = 0, right_idx: int = 255
    ):
        assert isinstance(posmap, np.ndarray), "posmap must be numpy.ndarray"
        if posmap.ndim == 1:
            posmap[0: left_idx + 1] = False
            posmap[right_idx:] = False
            non_zero_idx = np.where(posmap)[0]
            token_ids = [tokenized["input_ids"][i] for i in non_zero_idx]
            return tokenizer.decode(token_ids)
        else:
            raise NotImplementedError("posmap must be 1-dim")

    @staticmethod
    def generate_masks_with_special_tokens_and_transfer_map(tokenized, special_tokens_list):
        input_ids = tokenized["input_ids"]
        bs, num_token = input_ids.shape
        # special_tokens_mask: bs, num_token. 1 for special tokens. 0 for normal tokens
        special_tokens_mask = np.zeros((bs, num_token), dtype=bool)
        for special_token in special_tokens_list:
            special_tokens_mask |= (input_ids == special_token)

        # idxs: each row is a list of indices of special tokens
        idxs = np.argwhere(special_tokens_mask)

        # generate attention mask and positional ids
        attention_mask = np.eye(num_token, dtype=bool).reshape(1, num_token, num_token)
        attention_mask = np.tile(attention_mask, (bs, 1, 1))
        position_ids = np.zeros((bs, num_token), dtype=int)
        cate_to_token_mask_list = [[] for _ in range(bs)]
        previous_col = 0
        for i in range(idxs.shape[0]):
            row, col = idxs[i]
            if (col == 0) or (col == num_token - 1):
                attention_mask[row, col, col] = True
                position_ids[row, col] = 0
            else:
                attention_mask[row, previous_col + 1: col + 1, previous_col + 1: col + 1] = True
                position_ids[row, previous_col + 1: col + 1] = np.arange(0, col - previous_col)
                c2t_maski = np.zeros((num_token), dtype=bool)
                c2t_maski[previous_col + 1: col] = True
                cate_to_token_mask_list[row].append(c2t_maski)
            previous_col = col

        cate_to_token_mask_list = [
            np.stack(cate_to_token_mask_listi, axis=0)
            for cate_to_token_mask_listi in cate_to_token_mask_list
        ]

        return attention_mask, position_ids, cate_to_token_mask_list

    def unload(self):
        del self.net

if __name__ == '__main__':
    configs = {
        'model_path': './grounded_fuse_attention.onnx', # './grounded.onnx', 'bert_large_fp32.onnx', 'clip_large_fp32.onnx', 'grounded_attn'
        'device_type': 'gpu',
        'box_threshold': 0.3,
        'text_threshold': 0.25,
        'input_width': 1200,
        'input_height': 800,
        'max_text_len': 256,
        'text_encoder_type': 'bert-base-uncased',
    }

    model = Grounding_DINO(configs)

    image_path = 'C:/Users/acai1/Pictures/w/1.jpg'
    text_prompt = 'Excavator.car.'

    image = cv2.imread(image_path, cv2.IMREAD_COLOR)

    loop = 10
    for i in range(loop):
        model.predict_shapes(image, text_prompt=text_prompt)
    
    start_time = time.time()
    for i in range(loop):
        predict_results = model.predict_shapes(image, text_prompt=text_prompt)
    end_time = time.time()
    print('avg time: ', (end_time - start_time) / loop)

    print('predict_results: ', predict_results)

```

**Comment by acai66** [comment]
【阿里云盘】我给你发了 mo...ls.zip, 快来看看 https://www.aliyundrive.com/t/Fysm8ENiFay2fwJc9v91 点击链接即可保存。

**Comment by CVHub520** [comment]
> 【阿里云盘】我给你发了 mo...ls.zip, 快来看看 https://www.aliyundrive.com/t/Fysm8ENiFay2fwJc9v91 点击链接即可保存。

收到，晚点抽空试试。

**Comment by CVHub520** [comment]
> 我看源码里新release还没发布，暂时下载不到量化后的模型，这是我导出的onnx，输入图像大小固定为1200x800，可以测试对比下该模型与新release模型的性能吗
> 
> ```python
> import time
> import os
> import onnxruntime as ort
> 
> import cv2
> import numpy as np
> from typing import Dict
> from tokenizers import Tokenizer
> 
> 
> class OnnxBaseModel():
>     def __init__(self, model_path, device_type: str = 'gpu'):
> 
>         self.sess_opts = ort.SessionOptions()
>         if "OMP_NUM_THREADS" in os.environ:
>             self.sess_opts.inter_op_num_threads = int(os.environ["OMP_NUM_THREADS"])
> 
>         self.providers = ['CPUExecutionProvider']
>         if device_type.lower() == 'gpu':
>             self.providers = ['CUDAExecutionProvider']
> 
>         self.ort_session = ort.InferenceSession(
>                         model_path, 
>                         providers=self.providers,
>                         sess_options=self.sess_opts,
>                     )
> 
>     def get_ort_inference(self, blob, inputs=None, extract=True, squeeze=False):
>         if inputs is None:
>             inputs = self.get_input_name()
>             outs = self.ort_session.run(None, {inputs: blob})
>         else:
>             outs = self.ort_session.run(None, inputs)
>         if extract:
>             outs = outs[0]
>         if squeeze:
>             outs = outs.squeeze(axis=0)
>         return outs
>     
>     def get_input_name(self):
>         return self.ort_session.get_inputs()[0].name
> 
>     def get_input_shape(self):
>         return self.ort_session.get_inputs()[0].shape
> 
>     def get_output_name(self):
>         return [out.name for out in self.ort_session.get_outputs()]
> 
> 
> class Grounding_DINO():
>     """Open-Set object detection model using Grounding_DINO"""
> 
>     def __init__(self, model_config=None) -> None:
> 
>         self.config = model_config
>         model_abs_path = self.config["model_path"]
>         if not model_abs_path or not os.path.isfile(model_abs_path):
>             raise FileNotFoundError(
>                 print('file not found: ', model_abs_path)
>             )
> 
>         self.net = OnnxBaseModel(model_abs_path, device_type=self.config["device_type"])
>         self.max_text_len = self.config["max_text_len"]
>         self.tokenizer = self.get_tokenlizer(self.config["text_encoder_type"])
>         self.box_threshold = self.config["box_threshold"]
>         self.text_threshold = self.config["text_threshold"]
>         self.target_size = (self.config["input_width"], self.config["input_height"])
> 
>     def preprocess(self, image, text_prompt, img_mask=None):
>         # Resize the image
>         image = cv2.resize(image, self.target_size, interpolation=cv2.INTER_LINEAR)
> 
>         image = image.astype(np.float32) / 255.0
>         mean = np.array([0.485, 0.456, 0.406])
>         std = np.array([0.229, 0.224, 0.225])
>         image = (image - mean) / std
>         image = np.transpose(image, (2, 0, 1))
>         image = np.expand_dims(image, 0).astype(np.float32)
> 
>         # encoder texts
>         captions = self.get_caption(text_prompt)
>         #tokenized = self.tokenizer(captions, padding="longest", return_tensors="np")
>         #specical_tokens = self.tokenizer.convert_tokens_to_ids(["[CLS]", "[SEP]", ".", "?"])
>         tokenized_raw_results = self.tokenizer.encode(captions)
>         tokenized = {
>             "input_ids": np.array([tokenized_raw_results.ids], dtype=np.int64),
>             "token_type_ids": np.array([tokenized_raw_results.type_ids], dtype=np.int64),
>             "attention_mask": np.array([tokenized_raw_results.attention_mask])
>         }
>         specical_tokens = [101, 102, 1012, 1029] # [self.tokenizer.token_to_id(i) for i in ["[CLS]", "[SEP]", ".", "?"]]
>         (
>             text_self_attention_masks,
>             position_ids,
>             _,
>         ) = self.generate_masks_with_special_tokens_and_transfer_map(
>             tokenized, specical_tokens)
>         if text_self_attention_masks.shape[1] > self.max_text_len:
>             text_self_attention_masks = text_self_attention_masks[
>                 :, : self.max_text_len, : self.max_text_len]
>             
>             position_ids = position_ids[:, : self.max_text_len]
>             tokenized["input_ids"] = tokenized["input_ids"][:, : self.max_text_len]
>             tokenized["attention_mask"] = tokenized["attention_mask"][:, : self.max_text_len]
>             tokenized["token_type_ids"] = tokenized["token_type_ids"][:, : self.max_text_len]
> 
>         inputs = {}
>         inputs["img"] = image
>         if img_mask is None:
>             inputs["img_mask"] = np.zeros((1, image.shape[0], image.shape[2], image.shape[3]), dtype=np.float32)
>         else:
>             inputs["img_mask"] = img_mask
>         inputs["input_ids"] = np.array(tokenized["input_ids"], dtype=np.int64)
>         inputs["attention_mask"] = np.array(tokenized["attention_mask"], dtype=bool)
>         inputs["token_type_ids"] = np.array(tokenized["token_type_ids"], dtype=np.int64)
>         inputs["position_ids"] = np.array(position_ids, dtype=np.int64)
>         inputs["text_token_mask"] = np.array(text_self_attention_masks, dtype=bool)
> 
>         return image, inputs, captions
> 
>     def postprocess(self, outputs, caption, with_logits=True, token_spans=None):
>         logits, boxes = outputs
>         logits_filt = np.squeeze(logits, 0) #[0]  # prediction_logits.shape = (nq, 256)
>         boxes_filt = np.squeeze(boxes, 0) #[0]  # prediction_boxes.shape = (nq, 4)
>         # filter output
>         if token_spans is None:
>             filt_mask = logits_filt.max(axis=1) > self.box_threshold
>             logits_filt = logits_filt[filt_mask]  # num_filt, 256
>             boxes_filt = boxes_filt[filt_mask]  # num_filt, 4
> 
>             # get phrase
>             tokenlizer = self.tokenizer
>             tokenized_raw_results = tokenlizer.encode(caption)
>             tokenized = {
>                 "input_ids": np.array(tokenized_raw_results.ids, dtype=np.int64),
>                 "token_type_ids": np.array(tokenized_raw_results.type_ids, dtype=np.int64),
>                 "attention_mask": np.array(tokenized_raw_results.attention_mask)
>             }
>             # build pred
>             pred_phrases = []
>             for logit in logits_filt:
>                 posmap = logit > self.text_threshold
>                 pred_phrase = self.get_phrases_from_posmap(posmap, tokenized, tokenlizer)
>                 if with_logits:
>                     pred_phrases.append([pred_phrase, logit.max()])
>                 else:
>                     pred_phrases.append([pred_phrase, 1.0])
>         else:
>             # TODO: Using token_spans.
>             raise NotImplementedError
>         return boxes_filt, pred_phrases
> 
>     def predict_shapes(self, image, image_path=None, text_prompt=None, img_mask=None):
>         """
>         Predict shapes from image
>         """
> 
>         if image is None:
>             return []
> 
>         start_time = time.time()
>         blob, inputs, caption = self.preprocess(image, text_prompt, img_mask)
>         end_time = time.time()
>         print("Preprocess time: {:.3f}s".format(end_time - start_time))
>         start_time = time.time()
>         outputs = self.net.get_ort_inference(blob, inputs=inputs, extract=False)
>         end_time = time.time()
>         print("Inference time: {:.3f}s".format(end_time - start_time))
>         
>         start_time = time.time()
>         boxes_filt, pred_phrases = self.postprocess(outputs, caption)
>         end_time = time.time()
>         print("Postprocess time: {:.3f}s".format(end_time - start_time))
> 
>         shapes = []
>         img_h, img_w, _ = image.shape
>         boxes = self.rescale_boxes(boxes_filt, img_h, img_w)
>         for box, label_info in zip(boxes, pred_phrases):
>             x1, y1, x2, y2 = box
>             label, conf = label_info
> 
>             shapes.append([label, conf, x1, y1, x2, y2])
> 
>         return shapes
> 
> 
>     @staticmethod
>     def rescale_boxes(boxes, img_h, img_w):
>         converted_boxes = []
>         for box in boxes:
>             # from 0..1 to 0..W, 0..H
>             converted_box = box * np.array([img_w, img_h, img_w, img_h])
>             # from xywh to xyxy
>             converted_box[:2] -= converted_box[2:] / 2
>             converted_box[2:] += converted_box[:2]
>             converted_boxes.append(converted_box)
>         return np.array(converted_boxes, dtype=int)
> 
> 
>     @staticmethod
>     def get_caption(text_prompt):
>         caption = text_prompt.lower()
>         caption = caption.strip()
>         if not caption.endswith("."):
>             caption = caption + "."
>         captions = caption
>         return captions
> 
>     @staticmethod
>     def get_tokenlizer(text_encoder_type):
>         tokenizer = Tokenizer.from_file(f"./tokenizer/{text_encoder_type}.json")
>         #tokenizer.enable_padding(length=256)
>         #tokenizer.enable_truncation(max_length=256)
>         return tokenizer
> 
>     @staticmethod
>     def get_phrases_from_posmap(
>         posmap: np.ndarray, tokenized: Dict, tokenizer, left_idx: int = 0, right_idx: int = 255
>     ):
>         assert isinstance(posmap, np.ndarray), "posmap must be numpy.ndarray"
>         if posmap.ndim == 1:
>             posmap[0: left_idx + 1] = False
>             posmap[right_idx:] = False
>             non_zero_idx = np.where(posmap)[0]
>             token_ids = [tokenized["input_ids"][i] for i in non_zero_idx]
>             return tokenizer.decode(token_ids)
>         else:
>             raise NotImplementedError("posmap must be 1-dim")
> 
>     @staticmethod
>     def generate_masks_with_special_tokens_and_transfer_map(tokenized, special_tokens_list):
>         input_ids = tokenized["input_ids"]
>         bs, num_token = input_ids.shape
>         # special_tokens_mask: bs, num_token. 1 for special tokens. 0 for normal tokens
>         special_tokens_mask = np.zeros((bs, num_token), dtype=bool)
>         for special_token in special_tokens_list:
>             special_tokens_mask |= (input_ids == special_token)
> 
>         # idxs: each row is a list of indices of special tokens
>         idxs = np.argwhere(special_tokens_mask)
> 
>         # generate attention mask and positional ids
>         attention_mask = np.eye(num_token, dtype=bool).reshape(1, num_token, num_token)
>         attention_mask = np.tile(attention_mask, (bs, 1, 1))
>         position_ids = np.zeros((bs, num_token), dtype=int)
>         cate_to_token_mask_list = [[] for _ in range(bs)]
>         previous_col = 0
>         for i in range(idxs.shape[0]):
>             row, col = idxs[i]
>             if (col == 0) or (col == num_token - 1):
>                 attention_mask[row, col, col] = True
>                 position_ids[row, col] = 0
>             else:
>                 attention_mask[row, previous_col + 1: col + 1, previous_col + 1: col + 1] = True
>                 position_ids[row, previous_col + 1: col + 1] = np.arange(0, col - previous_col)
>                 c2t_maski = np.zeros((num_token), dtype=bool)
>                 c2t_maski[previous_col + 1: col] = True
>                 cate_to_token_mask_list[row].append(c2t_maski)
>             previous_col = col
> 
>         cate_to_token_mask_list = [
>             np.stack(cate_to_token_mask_listi, axis=0)
>             for cate_to_token_mask_listi in cate_to_token_mask_list
>         ]
> 
>         return attention_mask, position_ids, cate_to_token_mask_list
> 
>     def unload(self):
>         del self.net
> 
> if __name__ == '__main__':
>     configs = {
>         'model_path': './grounded_fuse_attention.onnx', # './grounded.onnx', 'bert_large_fp32.onnx', 'clip_large_fp32.onnx', 'grounded_attn'
>         'device_type': 'gpu',
>         'box_threshold': 0.3,
>         'text_threshold': 0.25,
>         'input_width': 1200,
>         'input_height': 800,
>         'max_text_len': 256,
>         'text_encoder_type': 'bert-base-uncased',
>     }
> 
>     model = Grounding_DINO(configs)
> 
>     image_path = 'C:/Users/acai1/Pictures/w/1.jpg'
>     text_prompt = 'Excavator.car.'
> 
>     image = cv2.imread(image_path, cv2.IMREAD_COLOR)
> 
>     loop = 10
>     for i in range(loop):
>         model.predict_shapes(image, text_prompt=text_prompt)
>     
>     start_time = time.time()
>     for i in range(loop):
>         predict_results = model.predict_shapes(image, text_prompt=text_prompt)
>     end_time = time.time()
>     print('avg time: ', (end_time - start_time) / loop)
> 
>     print('predict_results: ', predict_results)
> ```

您好，量化后的模型是2.71s，你转出来的这个测出来是0.52s，加速还是挺明显的，可以加 vx: ww10874 交流下。

**Comment by CVHub520** [comment]
包括量化后的或者其它所有模型都可以在 [model_list.md](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/models_list.md) 下载的，可以看下里面的百度网盘链接。
