### ISSUE TITLE
打mac包失败，怎么排查问题?

### ISSUE THREAD

**Issue by sunshine2176** [CVHub520/X-AnyLabeling#97]
请问打cpu版mac包失败，应该怎么排查问题？

**Comment by CVHub520** [comment]
>  @请问打cpu版mac包失败，应该怎么排查问题？

您好，打包工具用的是 `pyinstaller` 库，你可以尝试先随便打包一个文件看看能不能正常使用。确认可以正常使用之后再贴上具体的报错信息看看。

**Comment by sunshine2176** [comment]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/5172675/76dd5022-99d9-42d8-8627-72e3a1a759ea)
包打出之后，运行出现以上提示

**Comment by CVHub520** [comment]
> ![image](https://user-images.githubusercontent.com/5172675/278183637-76dd5022-99d9-42d8-8627-72e3a1a759ea.png) 包打出之后，运行出现以上提示

你这边本地是否有尝试其它的程序打包测试，可以先参考下这个[教程](https://www.pythonguis.com/tutorials/packaging-pyqt5-applications-pyinstaller-macos-dmg/)。

**Comment by sunshine2176** [comment]
解决了，是opencv-python-版本的问题，新建个虚拟环境，重新安装依赖就行了
