### ISSUE TITLE
a set of json

### ISSUE THREAD

**Issue by JAYCHOU2020** [CVHub520/X-AnyLabeling#98]
How to modify the X-AnyLabeling code so that it can read a set of json at once just like reading a set of pictures at once, and can also switch up and down json files

**Comment by CVHub520** [comment]
Hi, @JAYCHOU2020 :
In fact, you can import JSON files (of course must in [custom format](https://github.com/CVHub520/X-AnyLabeling/blob/main/assets/demo.json)) directly without the need to modify the code. The program will automatically read the images based on the "imagePath" field in the JSON files. Therefore, make sure that the image paths are correctly defined in your JSON files, and the tool will handle the rest.

If you have any more questions or need further assistance, feel free to reach out.

Best regards,
CVHub
