### ISSUE TITLE
yolov5-seg

### ISSUE THREAD

**Issue by TonFard** [CVHub520/X-AnyLabeling#99]
为啥我的模型不能预测出来分割的点，预测的都是框呢

type: yolov5
name: yolov5-seg
display_name: yolov5-seg
model_path: F:\gsq_py\yolov5-master\runs\train-seg\exp6\weights\best.onnx
score_threshold: 0.25
nms_threshold: 0.45
confidence_threshold: 0.4
num_masks: 32
classes:
  - line

**Comment by CVHub520** [comment]
Hi, @TonFard :
It seems like you're trying to use the YOLOv5-seg model, but currently, I haven't implemented support for segmentation. I'm planning to include this feature in a future update. Please be patient and stay tuned for the upcoming developments.

If you have any other questions or concerns, feel free to let us know.

Best regards,
CVHub

**Comment by CVHub520** [comment]
Hi, @TonFard , it's great to inform you that the feature is now supported. You can start using it by updating to the latest source code. Feel free to give it a try, and if you encounter any issues or have further questions, don't hesitate to reach out for assistance.

**Comment by TonFard** [comment]
您看为啥会出现这个情况，只有框没有标好的分割图
![Snipaste_2023-10-27_16-42-32](https://github.com/CVHub520/X-AnyLabeling/assets/77236666/5daea1fd-3a29-4141-a118-cdcc17edfbd6)
